### ISSUE TITLE
Support for additional resources

### ISSUE THREAD

**Issue by jason-riddle** [helm/charts#10]
I don't expect this to be supported anytime soon but I just wanted to bring this up. Kubernetes 1.2 was released about a week ago and with the release it brought a new resource.
#### Config Map

Now it is possible to use a config map to define your environment variables, an example I threw together is shown here

``` yaml
env:
  - name: TEAMCITY_SERVER_MEM_OPTS
    value: '-Xmx2500m'
  - name: TEAMCITY_SERVER_OPTS
    value: '-Dteamcity.git.fetch.separate.process=false'
  - name: TEAMCITY_DATA_PATH
    value: '/var/lib/teamcity'
  - name: CATALINA_OPTS
    valueFrom:
      configMapKeyRef:
      name: catalina-config
      key: proxy.properties
```

This isn't supported by the <code>github.com/kubernetes/charts/common/replicatedservice:v2</code> template at the moment due to the assumption that every entry in env will have the keys 'name' and 'value'.

https://github.com/kubernetes/charts/blob/2ecf8f3cd3a12e36c2d9d4e1faf4ddd531c55838/common/replicatedservice/v2/replicatedservice.py#L192-L194.

``` python
for entry in tmp_env:
  if isinstance(entry, dict):
    env.append({'name': entry.get('name'), 'value': entry.get('value')})
```

Also, it looks like the following aren't supported at the moment as well, which Kubernetes has had prior to 1.2.
#### Limits and Requests

``` yaml
resources:
  requests:
    memory: "3Gi"
  limits:
    memory: "4Gi"
```
#### Liveness Probe

``` yaml
livenessProbe:
  httpGet:
    path: /mnt
    port: 8111
  initialDelaySeconds: 20
  timeoutSeconds: 2
```

I'd be happy to submit a pull request adding functionality to <code>replicatedservice:v2</code>, but I had a few questions first.
1. As Kubernetes comes out with support for additional resources, how quickly will these be supported? Is this template (<code>replicatedservice:v2</code>) trying to support all of the resources or only a popular subset?
2. Should this just be added to <code>v2</code> or should a <code>v3</code> be created?
3. Is someone already aware / working on this and should I just be patient and wait?

I know I can just fork and modify the template to suit my needs and then just use that, but then that wouldn't be any use to the community.
