### ISSUE TITLE
[stable/gitlab-ce] Relative url leading to livenessProbe and readnessProbe always fail

### ISSUE THREAD

**Issue by jiminHuang** [helm/charts#1001]
After setting relative url via ``external_url`` of ``values.yaml`` as suggested in [documents](https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-a-relative-url-for-gitlab)

```yaml
externalUrl: http://your-domain.com/relative_url
```

Created pod never become healthy and consistently recreates itself.

``kubectl describe`` suggests that the pod always fails in livenessProbe and readnessProbe.

After checking the logs of the pod, it appears that the livenessProbe and readnessProbe failed due to the nginx not responding the request ``/help``

```bash
/var/opt/gitlab/nginx/html/help (no such file or directory)
```

Fix this by altering the request path of livenessProbe and readnessProbe.

```yaml
livenessProbe:
          httpGet:
            path: /relative_url/help
            port: http
readnessProbe:
          httpGet:
            path: /relative_url/help
            port: http
```

However, it will be more convenient if we set an external parameter ``relative_url`` and dynamically generate the ``external_url`` and ``request_path``. Or at least, we should add a note in the documentation about the latent crash when setting ``relative url``
