### ISSUE TITLE
[incubator/kafka] Expose externally using AWS ELB

### ISSUE THREAD

**Issue by EmilienMottet** [helm/charts#10025]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST 

**Version of Helm and Kubernetes**: helm : 2.12.0, kubernetes : 1.10.11 on AWS

**Which chart**: kafka 0.13.1

**What happened**:
We are trying to deploy a Kafka on a Kubernetes cluster using Helm.
We want to send data from an external [glances](https://github.com/nicolargo/glances) (that runs on our laptop, or any other machine NOT inside the Kubernetes cluster). To do so, we need to expose an entrypoint so that Kafka is reachable outside the K8s cluster.

The NodePort solution does not fit our needs because it involves to open ports cluster wide, we don't think it is a best practice. We'd rather prefer having an ELB attached to our service and reach kafka from this ELB.
This solution works, we can deploy it using simple K8s YAML files, but we would like to achieve it using Helm.

Our yaml:
```yaml
replicas: 3
configurationOverrides:
  "offsets.topic.replication.factor": 3
  "auto.leader.rebalance.enable": true
  "auto.create.topics.enable": true
  "confluent.support.metrics.enable": false
  "advertised.listeners": |-
    EXTERNAL://mykafka.api.emottet.fr:$((31090 + ${KAFKA_BROKER_ID}))
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  "listeners": "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092"
external:
  type: LoadBalancer
  enabled: true
  distinct: false
  domain: api.emottet.fr
rbac:
  enabled: true
```
This config creates 3 services (1 for each pod of the StatefulSet) with 3 different ELB (1 per service). We would like to have only one service with one ELB that acts a a LoadBalancer for the 3 pods.

When we try to produce mesages to Kafka, using one of the created ELB, we have the following error: 
```
Cannot connect to Kafka server a9aa79b7cffb111e8911e0654409fad4-1561402113.eu-west-3.elb.amazonaws.com:31090 (NoBrokersAvailable)
```

and with ./kafka-console-producer.sh :
```bash
./kafka-console-producer.sh --broker-list a9aa79b7cffb111e8911e0654409fad4-1561402113.eu-west-3.elb.amazonaws.com:31090 --topic test2

# [2018-12-14 16:16:26,125] ERROR Error when sending message to topic test2 with key: null, value: 11 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

**What you expected to happen**:
No errors at all, the message being well delivered to Kafka.

**How to reproduce it** (as minimally and precisely as possible):
Use the above config and try to access from the created ELB, associated to the service.

**Anything else we need to know**:
The cluster is deployed using Kops on AWS, if it helps .
We use 0.13.1 because we have the same issue as #9781 

 We've went through #8876 and #9062

Thanks and regards,
/cc @cyril-dussert
