### ISSUE TITLE
[incubator/vault] enable UI

### ISSUE THREAD

**Issue by sercanacar** [helm/charts#10112]
**Version of Helm and Kubernetes**:

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", 
Server: &version.Version{SemVer:"v2.11.0"

**Which chart**:
vault cart version=0.14.2 
Vault app version=0.11.2

**What happened**:

Is it possible to enable UI using the values? I've tried many combinations of values but no luck

ui:
  enable: true

**Comment by bradleygolden** [comment]
I'm also having no luck after referencing the instructions [here](https://learn.hashicorp.com/vault/getting-started/ui#non-dev-servers).

Here is an example of my values.yaml:
```yaml
replicaCount: 1
vault:
  dev: false
  config:
    storage:
      gcs:
        bucket: ...
    ui: true
```

Connection with the GCS storage backend works well but when I port forward from my local using:

```bash
kubectl port-forward -n vault vault-pod 8200
```

I get this error in the browser:

```
{"errors":[]}
```

Even if I set vault.dev to true I still get the same error.
