### ISSUE TITLE
[stable/postgresql] Values.initdbScripts is ignored if files/docker-entrypoint-initdb.d is empty

### ISSUE THREAD

**Issue by nightkr** [helm/charts#10160]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.11.0, Kubernetes 1.10.0, Kubectl 1.12.3

**Which chart**: stable/postgresql 3.2.1

**What happened**:

I installed a chart with the following `requirements.yaml`:

```yaml
dependencies:
- name: postgresql
  version: 3.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
```

And the following `values.yaml`:

```yaml
postgresql:
  initdbScripts:
    setup.sql: |
      CREATE USER dbuser WITH PASSWORD 'secret';
      CREATE DATABASE mydb WITH OWNER dbuser;
```

**What you expected to happen**:

A configmap named `${app}-postgresql-init-scripts` should exist, containing my setup script. It doesn't.

**Anything else we need to know**:

This seems to be caused by #10124, which added a [guard on whether to create the ConfigMap](https://github.com/helm/charts/commit/7030efc7b37676a65d20ffa6d1adcd3333a6a542#diff-20676a17a649540c464d07c8e3ca7fb9R1). v3.2.0 of the chart works fine.
