### ISSUE TITLE
Traefik: ability to use existing PVC?

### ISSUE THREAD

**Issue by olalonde** [helm/charts#1016]
It would be useful to be able to specify an existing PVC to use for the acme persistence. This would enable me to transfer existing certs after I delete and re-create my k8s from scratch.

**Edit**: Actually, what would be really helpful would be the ability to set the initial content of acme.json through helm

**Comment by kachkaev** [comment]
Hi @olalonde. Were you able to implement this outside the current stable chart? Just wondering how this could be done in theory.

**Comment by olalonde** [comment]
I started this PR: https://github.com/kubernetes/charts/pull/1063 but stopped using Traefik now.

**Comment by kachkaev** [comment]
Thanks for the info @olalonde. What Traefik alternative can you recommend?

**Comment by olalonde** [comment]
@kabakaev I've simply been using nginx-ingress + kube-lego

In my `requirements.yaml`:

```yaml
dependencies:
  - name: nginx-ingress
    version: 0.4.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kube-lego
    version: 0.1.9
    repository: https://kubernetes-charts.storage.googleapis.com
```

In my `values.yaml`:

```yaml
nginx-ingress:
  controller:
    config:
      body-size: 100m
kube-lego:
  image:
    tag: 0.1.4
  config:
    LEGO_EMAIL: info+tls@mydomain.com
    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
```

And example ingress that uses lego to get automatic https:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "metabase-ingress"
  labels:
    app: "metabase"
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: metabase-tls
    hosts:
    - "metabase.{{ .Values.global.envDomain }}"
  rules:
  - host: "metabase.{{ .Values.global.envDomain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: metabase
          servicePort: 80
```
