### ISSUE TITLE
[stable/coredns] serviceAccount <-> roleBinding not generated correctly

### ISSUE THREAD

**Issue by sjincho** [helm/charts#10191]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/coredns`

**What happened**:
If I run:
```
helm install --dry-run --debug --set serviceAccount.name=foo --set serviceAccount.create=true stable/coredns --name mycoredns
```

the generated service account & bindings are:
```
# Source: coredns/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
  labels:
    heritage: "Tiller"
    release: "mycoredns"
    chart: "coredns-1.2.2"
    k8s-app: "coredns"
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    app: coredns
```
```
# Source: coredns/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mycoredns-coredns
  labels:
    heritage: "Tiller"
    release: "mycoredns"
    chart: "coredns-1.2.2"
    k8s-app: "coredns"
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    app: coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mycoredns-coredns
subjects:
- kind: ServiceAccount
  name: mycoredns-coredns  <-- Wrong. Should be foo
  namespace: sjcho
```

**What you expected to happen**:
Use correct service account name in cluster role binding

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else we need to know**:
https://github.com/helm/charts/blob/master/stable/coredns/templates/clusterrolebinding.yaml
should use `{{ template "coredns.serviceAccountName" . }}` instead of `{{ template "coredns.fullname" . }}`.
