### ISSUE TITLE
[keycloak:4.0.8] You need local access to create the initial admin user ?

### ISSUE THREAD

**Issue by tony-kerz** [helm/charts#10217]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug-report

**Version of Helm and Kubernetes**:  `2.12.1`, `1.10.x`

**Which chart**: keycloak `4.0.8`

**What happened**:

installed with following values:
```
keycloak:
  password: "my-secret"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: internal
      ingress.kubernetes.io/affinity: cookie
    hosts:
      - keycloak.me.com
    tls:
      - hosts:
        - keycloak.me.com
```
<img width="327" alt="screen shot 2018-12-21 at 10 34 45 pm" src="https://user-images.githubusercontent.com/1223231/50370220-c6b90100-0570-11e9-8d57-15c1ae739f1a.png">

**What you expected to happen**:

expect to be able to login with user = `keycloak` and password = `my-secret`

**How to reproduce it** (as minimally and precisely as possible):

`helm install` with above values

**Anything else we need to know**:
