### ISSUE TITLE
[stable/concourse] localuser with username other than test gets access denied

### ISSUE THREAD

**Issue by dperezmavro** [helm/charts#10343]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm version: 
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.26", GitCommit:"25365995b58530998bdcd4ea6383682858a0fb7b", GitTreeState:"clean", BuildDate:"2018-12-11T02:37:25Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: 

`stable/concourse version 3.0.1`

**What happened**: 

When installing this chart, I am trying to customize the `localUser` list to have a different name for the concourse user and a non-default password. 

I can login with fly correctly after the chart is installed (using `fly -t main login -u admin -p somePass -c http://concourse-host-ip:8080 -n main`), however any fly command related to pipelines (e.g. : `fly -t main set-pipeline -p test2 -c ~/Desktop/sample-concourse.yml`) only fails with `error: forbidden`.

I can correctly authenticate to the concourse web ui and via fly, but any subsequent pipeline commands fail.

**What you expected to happen**:
I expect it to be able to login with the new credentials, and once authenticated via fly, to be able to set and update pipelines. 

**How to reproduce it** (as minimally and precisely as possible):
On GKE with a working tiller installation, use the following values:
```
web:
  service:
    type: LoadBalancer
concourse:
  auth:
    mainTeam:
      localUser: "admin"
secrets:
  localUsers: "admin:$2a$10$cyjpfKPYfXFIHOcxQCJl8OQo9OHa25oW8q.fnIWnTXRNeCMoDNokK"
```

And then install:
`helm install --name concourse-1 stable/concourse --version 3.0.1 -f ./values.yml`

Login using fly: 
`fly -t main login -u admin -p somePass -c http://concourse-ip:8080 -n main`

Using the following sample concourse file:
```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello, world!"]
```

**Anything else we need to know**:
The default `test:test` credentials work with no issue, as does just the username `test` with any password. The problems are observed on my side when I'm changing the user name.

**Comment by cirocosta** [comment]
Hey @dperezmavro ,

Looking at the `values.yml` file you provided, it seems like the path from `concourse` to `localUser` misses `web`:

https://github.com/helm/charts/blob/c74c09dc3040ee7864bde44cff1e465b9ac62d6f/stable/concourse/templates/web-deployment.yaml#L529-L532

You can verify that by templating that locally:

```yml
# values.yml
concourse:
  auth:
    mainTeam:
      localUser: "admin"
secrets:
  localUsers: "admin:admin"
```

```sh
helm template \
  --values ./values.yml \
  -x templates/web-deployment.yaml ./stable/concourse | \
  ag -A 1 CONCOURSE_MAIN_TEAM_LOCAL_USER
            - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
              value: "test"
```

Now, if we change `values.yml` to the following:

```yaml
concourse:
  web:
    auth:
      mainTeam:
        localUser: "admin"
secrets:
  localUsers: "admin:admin"
```

We can see the environment variable being properly set:

```sh
helm template \
  --values ./values.yml \
  -x templates/web-deployment.yaml ./stable/concourse | \
  ag -A 1 CONCOURSE_MAIN_TEAM_LOCAL_USER
            - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
              value: "admin"
```

Please let me know if that works for you!

Thanks!
