### ISSUE TITLE
grafana datasource should use "tpl" so that release name can be used in connection strings

### ISSUE THREAD

**Issue by Place1** [helm/charts#10342]
Currently there's no way to deploy stable/grafana and stable/prometheus and have a datasource configured automatically via values.yaml.

stable/prometheus will create a service called `{{ .Release.Name }}-prometheus-server` and ideally we could configure a datasource for grafana pointing to this, but as [this issue](https://github.com/helm/helm/issues/2492) points out, it's not possible to do so in values.yaml

Consider the config below:

```yaml
# values.yaml
grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://{{ .Release.Name }}-prometheus-server:80
          access: proxy
          editable: false
          basicAuth: false
```

For this to work the grafana template needs to use `tpl` here: https://github.com/helm/charts/blob/master/stable/grafana/templates/configmap.yaml#L25

Is this something that could be changed? It'd be a nice usability improvement - googling up on the issue highlighted some workarounds that weren't great.
