### ISSUE TITLE
[stable/keycloak] add ability to define volumeClaimTemplates on StatefulSet

### ISSUE THREAD

**Issue by brunnels** [helm/charts#10412]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which chart**: stable/keycloak

It's possible to define `extraVolumeMounts` and `extraVolumes` to point to an existing PVC.

If you want to scale the StatefulSet then you would need to define `volumeClaimTemplates` instead of the `extraVolumes`

```
spec:
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: keycloak-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: rbd
  template:
      containers:
          volumeMounts:
            - name: keycloak-vol
              mountPath: /opt/jboss/keycloak/standalone/data
```
