### ISSUE TITLE
[stable/kiam] Consider auto-generating secrets

### ISSUE THREAD

**Issue by tspacek** [helm/charts#10420]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature suggestion

**Which chart**:
stable/kiam

A secret template like this:
```
{{- $ca := genCA "Kiam CA" 365 -}}
{{- $serverCert := genSignedCert "Kiam Server" (list "127.0.0.1") (list "kiam-server" "kiam-server:443" "127.0.0.1:443" "127.0.0.1:9610") 365 $ca -}}
{{- $agentCert := genSignedCert "Kiam Agent" nil nil 365 $ca -}}
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: kiam-wrapper-server-tls
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  ca: {{ $ca.Cert | b64enc }}
  cert: {{ $serverCert.Cert | b64enc }}
  key: {{ $serverCert.Key | b64enc }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: kiam-wrapper-agent-tls
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  ca: {{ $ca.Cert | b64enc }}
  cert: {{ $agentCert.Cert | b64enc }}
  key: {{ $agentCert.Key | b64enc }}
```

Allows Helm to automatically generate certs and upload them as a secret. This has the following benefits:
a) it's more convenient to get up and running or try the chart out
b) the certs aren't persisted into Helm's meta-data via values.yaml history
