### ISSUE TITLE
[stable/sonatype-nexus]: add ability to expose docker endpoint via ingress

### ISSUE THREAD

**Issue by valerius257** [helm/charts#10467]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.12.1
Kubernetes: v1.11.5-eks-6bad6d

**Which chart**:
stable/sonatype-nexus

**What happened**:
There is no way to expose docker endpoint via ingress in current version of the stable/sonatype-nexus chart.
nexusDockerHost and nexusHttpHost are using same service and port.
```yaml
spec:
  rules:
    - host: {{ .Values.nexusProxy.env.nexusDockerHost }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nexus.fullname" . }}
              servicePort: {{ .Values.nexusProxy.port }}
            path: {{ .Values.ingress.path }}
    - host: {{ .Values.nexusProxy.env.nexusHttpHost }}
      http:
        paths:
          - backend:
              serviceName: {{ template "nexus.fullname" . }}
              servicePort: {{ .Values.nexusProxy.port }}
            path: {{ .Values.ingress.path }}
```

**What you expected to happen**:
nexusHttpHost is pointing to nexus web UI and docker service is available via nexusDockerHost.

**How to reproduce it** (as minimally and precisely as possible):
Deploy stable/sonatype-nexus chart with enabled ingress.

**Comment by valerius257** [comment]
@rjkernick could you look at the issue?

**Comment by jeff-knurek** [comment]
@valerius257 While both endpoints do point to the same service, that service is the nexus-proxy, which then directs the traffic to the nexus pod via the header sent. In other words, exposing docker via the ingress is exactly how we're using the chart, so at least it works in version `1.15.0` for us.

Can you maybe provide a little more detail in how to reproduce? as in, what are the values you're using for:
```
nexusProxy:
  env:
    nexusDockerHost:
    nexusHttpHost:
```
Based on what's documented, and how we use the chart, those two values should be different.
