### ISSUE TITLE
[stable/mongodb-replicaset] how to expose my mongodb service on the internet

### ISSUE THREAD

**Issue by auriou** [helm/charts#10515]
hello , 
I start with kubernetes and helm, 
how to expose my mongodb service on the internet ? 

I added a service but it does not work
````
apiVersion: v1
kind: Service
metadata:
  name: db-lb-mongodb
spec:
  selector:
    app: db-mongodb-replicaset
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017

````

thank you

**Comment by auriou** [comment]
Hi @juan131 , thx
I used GKE Google Kubertenes Engine.

Commands 
````
helm install --name db -f mongo-replica.yaml stable/mongodb-replicaset

kubectl apply -f loadbalancer.yaml
````
 mongo-replica.yaml, I just modified mongo config for listen all ip
````
# Entries for the MongoDB config file
configmap:
  net:
    port: 27017
    bindIp: 0.0.0.0

````

Loadbalancer.yaml
````
apiVersion: v1
kind: Service
metadata:
  name: db-lb-mongodb
spec:
  selector:
    app: db-mongodb-replicaset
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
````

**Comment by auriou** [comment]
I found, as I created a release, it must be specified in the selector

````
apiVersion: v1
kind: Service
metadata:
  name: db-lb-mongodb
spec:
  selector:
    app: mongodb-replicaset
    release: db    # my release
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
````
