### ISSUE TITLE
[stable/prestashop] Can't install stable prestashop helm 

### ISSUE THREAD

**Issue by Nittarab** [helm/charts#10532]
**Is this a BUG REPORT** 

**Version of Helm and Kubernetes**:
- helm v2.12.1
- kubernetes v 1.12.4

**Which chart**:
stable/prestashop

**What happened**:
```
2. Complete your PrestaShop deployment by running:

  helm upgrade historical-bobcat stable/prestashop \
    --set prestashopHost=$APP_HOST,prestashopPassword=$APP_PASSWORD,mariadb.db.password=$APP_DATABASE_PASSWORD
```

**What you expected to happen**:

After the  #10335 i expect i need to set the `ingress.hosts 0 name`

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/prestashop`

**Anything else we need to know**:

I try to create a values.yaml with this set:

```
ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: true

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations:
  #  kubernetes.io/ingress.class: nginx

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: test.com
    path: /

    # Set this to true in order to enable TLS on the ingress record
    tls: false

    ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
    tlsSecret: prestashop.local-tls

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: prestashop.local-tls
  #   key:
  #   certificate:
```

then `helm install stable/prestashop --name t2 -f values.yaml`

i get
```
Error: release t2 failed: Deployment.apps "t2-prestashop" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"prestashop", "chart":"prestashop-6.0.0", "release":"t2"}: `selector` does not match template `labels`
```
