### ISSUE TITLE
[stable/mongodb]: Error executing 'postInstallation': If you defined an username you must define a password and a database too

### ISSUE THREAD

**Issue by todkap** [helm/charts#10539]
**Version of Helm and Kubernetes**:
- Kubernetes version
`1.12.3_1531`
- helm version
> Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
> 
> Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
> 

**Which chart**:
stable/mongodb

**What happened**:

>  helm status my-release
> LAST DEPLOYED: Thu Jan 10 13:53:07 2019
> NAMESPACE: default
> STATUS: DEPLOYED
> 
> RESOURCES:
> ==> v1beta1/PodDisruptionBudget
> NAME                          MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
> my-release-mongodb-arbiter    1              N/A              0                    15m
> my-release-mongodb-primary    1              N/A              0                    15m
> my-release-mongodb-secondary  1              N/A              0                    15m
> 
> ==> v1/Secret
> NAME                TYPE    DATA  AGE
> my-release-mongodb  Opaque  2     15m
> 
> ==> v1/Service
> NAME                         TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)    AGE
> my-release-mongodb-headless  ClusterIP  None           <none>       27017/TCP  15m
> my-release-mongodb           ClusterIP  172.21.98.127  <none>       27017/TCP  15m
> 
> ==> v1/StatefulSet
> NAME                          DESIRED  CURRENT  AGE
> my-release-mongodb-arbiter    1        1        15m
> my-release-mongodb-primary    1        1        15m
> my-release-mongodb-secondary  1        1        15m
> 
> ==> v1/Pod(related)
> NAME                            READY  STATUS            RESTARTS  AGE
> my-release-mongodb-arbiter-0    0/1    CrashLoopBackOff  4         15m
> my-release-mongodb-primary-0    0/1    CrashLoopBackOff  7         15m
> my-release-mongodb-secondary-0  0/1    CrashLoopBackOff  4         15m
> 
> 

**What you expected to happen**:
> Pods to enter ready state.   Error message logged for primary-0
> Welcome to the Bitnami mongodb container
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
>  nami    INFO  Initializing mongodb
> mongodb INFO  ==> Deploying MongoDB from scratch...
> mongodb INFO  ==> No injected configuration files found. Creating default config files...
> Error executing 'postInstallation': If you defined an username you must define a password and a database too

**How to reproduce it** (as minimally and precisely as possible):

>  helm install --name my-release stable/mongodb --set replicaSet.enabled=true --set persistence.enabled=false

**Anything else we need to know**:
This is a simplified example that dragged in dependencies (such as PVCs and PVs) from what I was previously doing but still hitting same issue.

**Comment by juan131** [comment]
What version of MongoDB chart are you using?

I was unable to reproduce the issue using the lates version of the chart:

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ helm install --name my-release stable/mongodb --set replicaSet.enabled=true --set persistence.enabled=false
NAME:   my-release
LAST DEPLOYED: Fri Jan 11 10:57:35 2019
NAMESPACE: default
STATUS: DEPLOYED
...
$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
my-release-mongodb-arbiter-0     1/1     Running   0          89s
my-release-mongodb-primary-0     1/1     Running   0          89s
my-release-mongodb-secondary-0   1/1     Running   0          89s
$ kubectl logs -f my-release-mongodb-primary-0

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Creating root user...
mongodb INFO  ==> Enabling authentication...
mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb INFO  ==> Configuring MongoDB replica set
mongodb INFO  ==> Enabling MongoDB replica set name
mongodb INFO  ==> Configuring MongoDB primary node
mongodb INFO
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Root Password: **********
mongodb INFO     Replication Mode: primary
mongodb INFO   (Passwords are not shown for security reasons)
mongodb INFO  ########################################################################
mongodb INFO
nami    INFO  mongodb successfully initialized
INFO  ==> Starting mongodb...
INFO  ==> Starting mongod...
2019-01-11T10:01:28.690+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-01-11T10:01:28.718+0000 I CONTROL  [initandlisten] MongoDB starting : pid=186 port=27017 dbpath=/opt/bitnami/mongodb/data/db 64-bit host=my-release-mongodb-primary-0
...
```

**Comment by todkap** [comment]
I tried the latest version (ie did not reference chart version) and 4.8.4.  Did you by chance try it on the same version of K8 that I did?

**Comment by dplummer** [comment]
I've run into this same issue, it looks like it's because enabling a replica set uses a different config (`deployment-standalone` vs `statefulset-primary-rs`).

In `deployment-standalone.yaml`:

```
        {{- if and .Values.mongodbUsername .Values.mongodbDatabase }}
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{- else }}{{ template "mongodb.fullname" . }}{{- end }}
              key: mongodb-password
        {{- end }}
```

in `statefulset-primary-rs.yaml`:

```
            {{- if or .Values.mongodbPassword .Values.existingSecret }}
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{- else }}{{ template "mongodb.fullname" . }}{{- end }}
                key: mongodb-password
            {{- end }}
```

so I think you have to set the `existingSecret` value?
