### ISSUE TITLE
[stable/traefik] Remote I/O error while accessing /acme directory

### ISSUE THREAD

**Issue by andrejmlyncar** [helm/charts#10596]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm version:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/traefik

**What happened**:
While creating traefik container, following errors are displayed:
```
{"level":"error","msg":"Failed to read new account, ACME data conversion is not available : open /acme/acme.json: remote I/O error","time":"2019-01-13T22:02:48Z"}
{"level":"error","msg":"Unable to add ACME provider to the providers list: unable to get ACME account : open /acme/acme.jso``n: remote I/O error","time":"2019-01-13T22:02:48Z"}`
```
When I manually connect (bash) into traefik pod, and trying to list /acme direcotry, same error is displayed:
```
/ # ls -la /acme
ls: /acme: Remote I/O error
```
Follwing record can be found in mount listing. IP address is instance of running nfs-provisioner. 
```
10.152.183.130:/export/pvc-ee667503-177e-11e9-99b9-fe2fb28fc453 /acme nfs4 rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.202.90.154,local_lock=none,addr=10.152.183.130 0 0
```
Persistent volume claim is successfully created and path /export/pvc-ee667503-177e-11e9-99b9-fe2fb28fc453 is located on nfs-provisioner instance.

When I try to manually remount directory (as root), following message is displayed:
`mount: permission denied (are you root?)`

Traefik coniguration

```

imageTag: 1.7.7-alpine
ssl:
  enabled: true
  enforced: true
acme:
  logging: true
  enabled: true
  email: mymail@mymail.com
  challengeType: dns-01
  staging: true
  domains:
    enabled: true
    domainsList:
      - main: "*.mydomain.com" 
  persistence:
    enabled: true
    storageClass: nfs
    accessMode: ReadWriteOnce
    size: 1Gi
dashboard:
  enabled: true
  domain: dashboard.mydomain.com
  auth:
    basic:
      test: $mypass.
kubernetes:
  namespaces:
    - default
    - kube-system
```

**What you expected to happen**:
/acme directory should be accessible

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/nfs-server-provisioner
helm install --values traefik.yaml stable/traefik
```
