### ISSUE TITLE
[stable/redis] make it possible to configure somaxconn and THP to fix warnings

### ISSUE THREAD

**Issue by denisvlr** [helm/charts#10666]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**: 2.10, 1.10

**Which chart**: stable/redis

**What happened**:
When deploying Redis with the default values, I see the following Warnings:
```
# WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
# WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis.
```

**What you expected to happen**:
Possible solutions:
* Have the default deployment work without warnings
* Make it possible to customize these settings
* Make it possible to configure a custom initContainer

For example, I had to manually add the following initContainer to set somaxconn:
```
initContainers:
  - name: init-sysctl
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      sysctl -w net.core.somaxconn=10000
    securityContext:
      privileged: true
      runAsUser: 0
```

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --name redis-test stable/redis
```
then print logs on the slave or master pod.

**Anything else we need to know**:
I'm willing to contribute a PR, let me know which solution would be best. Running containers with privileges might raise security concerns, we might prefer to avoid in the default configuration.
