### ISSUE TITLE
[incubator/goldfish] Ingress (wildcard) path introduced with #6403 does not work on community ingress

### ISSUE THREAD

**Issue by skliche** [helm/charts#10722]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
HELM:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

KUBERNETES:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5+IKS", GitCommit:"93ab2680ca982746b1cc0827f59bb53143ebfc08", GitTreeState:"clean", BuildDate:"2018-12-03T21:32:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
INGRESS Chart: nginx-ingress-0.31.0

**Which chart**:
[incubator/goldfish] 0.2.7

**What happened**:
After deploying the chart the helm release is not available over the ingress route and callers are getting routed to the default backend (404).

In #6403 the ingress path annotation has been changed to 
```yaml
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /* <-- new wildcard
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
```
The wildcard expression however is invalid when using the nginx community ingress. When removing the wildcard asterisk, the ui is accessible.

**What you expected to happen**:
There should not be a wildcard expression in the path definition.

**How to reproduce it** (as minimally and precisely as possible):
Use the community nginx-ingress controller quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0 and install the helm chart. 

**Anything else we need to know**:
There is a community discussion regarding ingress path expressions going on in the nginx github project under https://github.com/kubernetes/ingress-nginx/issues/555 which states that there are different interpretations regarding wildcard expressions for ingress paths.

From reading the discussion, it seems as if `path: /*` would only work on GCE and `path: /`is the correct default for the nginx controller.
