### ISSUE TITLE
mariadb PV claim is not disabled in Wordpress chart

### ISSUE THREAD

**Issue by devlaptop** [helm/charts#1073]
I am trying to deploy Wordpress on a single node kubernates cluster and don't have Persistent volumes configured on Kubernates, and the k8s cluster is running on Bluemix so I don't think it supports dynamic provisioning of volumes.

Hence I cannot get the application to run even with --set persistence.enabled=false, because although this works for Wordpress, PVC is still used for mariadb.

Is there a way to still run this without requiring persistent volumes ?

**Comment by kachkaev** [comment]
Same here. Tried quite a few things in `--set` before realising that the claim comes from a dependent chart, not the wordpress chart itself.

```bash
helm install --name wordpress-test --set "persistence.enabled=false" --dry-run stable/wordpress --debug
```

Output:
```
COMPUTED VALUES:
...
persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 10Gi
...
---
# Source: wordpress/charts/mariadb/templates/pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-test-mariadb
  labels:
    app: wordpress-test-mariadb
    chart: "mariadb-0.6.2"
    release: "wordpress-test"
    heritage: "Tiller"
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
...
```

The whole section `# Source: wordpress/charts/mariadb/templates/pvc.yaml` was not expected here.

@bcorijn @scottrigby could you please help? (saw you editing the wordpress chart recently)

I'm a total newbie in k8s and helm, this is my first day =)
