### ISSUE TITLE
Prometheus cannot list pods, nodes or endpoints

### ISSUE THREAD

**Issue by japettyjohn** [helm/charts#1075]
I've got a cluster running k8s 1.6.2. I've just installed stable/prometheus-3.0.2 through helm. It's running bare metal on CentOS 7 installed through kubeadm and using flanneld.

Prometheus is up and running but I've got this errors in the journal on the node its running in. Seems like a RBAC issue preventing it from collecting metrics throughout the cluster?

```
dockerd-current[23751]: time="2017-05-14T04:58:57Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Pod: the server does not allow access to the requested resource (get pods)" component="kube_client_runtime" source="kubernetes.go:73"
dockerd-current[23751]: time="2017-05-14T04:58:57Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Endpoints: the server does not allow access to the requested resource (get endpoints)" component="kube_client_runtime" source="kubernetes.go:73"
dockerd-current[23751]: time="2017-05-14T04:58:57Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Node: the server does not allow access to the requested resource (get nodes)" component="kube_client_runtime" source="kubernetes.go:73"
dockerd-current[5084]: E0514 05:35:11.888317       1 reflector.go:199] k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Node: the server does not allow access to the requested resource (get nodes)
dockerd-current[5084]: E0514 05:35:11.888324       1 reflector.go:199] k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1beta1.DaemonSet: the server does not allow access to the requested resource (get daemonsets.extensions)
dockerd-current[5084]: E0514 05:35:11.888365       1 reflector.go:199] k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1beta1.Deployment: the server does not allow access to the requested resource (get deployments.extensions)
dockerd-current[5084]: E0514 05:35:11.888375       1 reflector.go:199] k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ResourceQuota: the server does not allow access to the requested resource (get resourcequotas)
```

I had done two mods to get it running in the first place:

1) Removing the storageClass attribute from the PVC, I'm using NFS with no storageClass and it would not match up without it.

2) I used this as a config yaml as suggested in #955 :
```
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
```
