### ISSUE TITLE
[stable/rabbitmq] Persistence not working on GKE and AKS

### ISSUE THREAD

**Issue by gboor** [helm/charts#10841]
**Is this a request for help?**: Yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**: Helm 2.11.0, K8S 1.10.11-gke.1

**Which chart**: stable/rabbitmq

**What happened**:

I installed RabbitMQ with persistence enabled. After a node failure due to some far too heavy load being deployed, RabbitMQ automatically came back up, but all users were gone, all exchanges were gone and all queues were gone. I had to manually recreate all the users and exchanges.

**What you expected to happen**:

Recovery with all persistent data intact.

**How to reproduce it** (as minimally and precisely as possible):

1) Deploy stable/rabbitmq on a small cluster
2) Crash cluster by deploying something stupid like a massive neural network without limitations on resources
3) Delete offending pod, wait for recovery - persistent data is gone.

**Anything else we need to know**:

Values.yaml used;

```
rabbitmq:
  username: XXXXXX
  plugins: |-
      [rabbitmq_management,rabbitmq_peer_discovery_k8s].

  clustering:
    address_type: ip
    k8s_domain: cluster.local

  configuration: |-
      ## Clustering
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.node_cleanup.interval = 10
      cluster_formation.node_cleanup.only_log_warning = false
      cluster_partition_handling = autoheal
      ## queue master locator
      queue_master_locator=min-masters
      ## enable guest user
      loopback_users.guest = false

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m

replicas: 2

nodeSelector:
  beta.kubernetes.io/arch: amd64

ingress:
  enabled: false

metrics:
  enabled: true
```
