### ISSUE TITLE
[stable/logstash] Feature request: plugins

### ISSUE THREAD

**Issue by PosicubeBeege** [helm/charts#10889]
Feature Request: Allow specification of plugins to be installed in Logstash

We'd like to be able to specify plugins for Logstash to install and run on startup. This appears to be possible via `spec.containers[].command` in the StatefulSet and a [cli option](https://github.com/elastic/logstash-docker/issues/43#issuecomment-342080648), though my Kubernetes/Helm knowledge is new and limited. I could see problems with specifying multiple plugins due to the templating language, but at least one should be possible, correct?

Are there reasons for not having this? Is there a constraint I'm not thinking of? Is there a way to do this already? Should I attempt a PR?

Thanks

**Comment by PosicubeBeege** [comment]
I managed to get it working by copying down the entire logstash chart and add this condition around the plugin value and its contents:

```
        ## logstash
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.plugin }}
          command: ["/bin/sh", "-c"]
          args: ["/usr/share/logstash/bin/logstash-plugin install {{ .Values.plugin }} ; /usr/local/bin/docker-entrypoint"]
          {{- end }}
          ports:
```

However, I think there should be a better way than this. Thoughts?
