### ISSUE TITLE
[stable/external-dns] Unable to use aws role with external-dns

### ISSUE THREAD

**Issue by onyxet** [helm/charts#10886]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm: v2.11.0 & kubernetes: 1.11

**Which chart**:
stable/external-dns

**What happened**:
Can't assume role credentials using `values.yaml`

**What you expected to happen**:
Assuming aws role as a start paramater for external-dns

**How to reproduce it** (as minimally and precisely as possible):
Fill in `aws.roleArn` value and deploy latest stable chart version

**Anything else we need to know**:

**Comment by dancb10** [comment]
hello, when is this going to be pushed? We are blocked by the same issue

**Comment by markuszm** [comment]
Same issue here
At the moment the property aws.roleArn from the values.yaml is unused in the template

Temporary workaround is to set the role via the podAnnotations property.
Example in values.yaml:
```yaml
podAnnotations: 
  iam.amazonaws.com/role: <route53-access-role>
```

**Comment by cortopy** [comment]
The workaround does not seem to work for me either. 
I've tried with both `aws.roleArn` and `podAnnotations` but still getting the following error: `NoCredentialProviders: no valid providers in chain`

Also, in the pod logs the config property `AWSAssumeRole` is empty

**Comment by cortopy** [comment]
Actually the workaround did work. I had kube2iam misconfigured.

**Comment by alkar** [comment]
It's confusing because the `aws.roleArn` property is not related to the `--aws-assume-role` flag. It seems to only be used when you provide hardcoded credentials to the helm chart, at which point it will generate `~/.aws/config` in the container. You can always do the following, however:
```
extraArgs:
  aws-assume-role: "arn:aws:iam::<account-id>:role/my-external-dns-role"
```

**Comment by lanmalkieri** [comment]
This is still broken. You cannot currently use the documented values aws.roleArn to specify a role arn for external DNS to utilize.

**Comment by demisx** [comment]
Same issue here. Can't use the chart because of this bug.

**Comment by millaguie** [comment]
When using RBAC you need to use something like this: 
```
aws:
  zoneType: public
  # assumeRoleArn: "arn:aws:iam::<ACCOUNT>:role/<YOUR-external-dns>" # You have to remove this line to ensure it works
  region: <your-aws-region>
serviceAccount:
  create: true
  name: external-dns
  annotations: "arn:aws:iam::<ACCOUNT>:role/<YOUR-external-dns>"  # here is were you assign the IAM role to the service account
```
