### ISSUE TITLE
[stable/rocketchat] Missing option for adjusting rules in ingress

### ISSUE THREAD

**Issue by elwood218** [helm/charts#10995]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.12.2
Kubernetes: v1.11.6-gke.3

**Which chart**: 
rocketchat

**What happened**:
I tried to use the ingress-gce instead of nginx. But there was only a rule `/`applied in the ingress. In my case the GCP Loadbalancer was not forwarding the requestes correctly. When I was adjusting the lines manually with `k edit ingresses.extensions -n rocketchat rocketchat-rocketchat` and added a second backend path it worked.

```
spec:
  rules:
  - host: rocketchat-test.rocketchat
    http:
      paths:
      - backend:
          serviceName: rocketchat-rocketchat
          servicePort: 3000
        path: /
     - backend:
          serviceName: rocketchat-rocketchat
          servicePort: 3000
        path: /*
```

**What you expected to happen**:
Forward also `/*` to backend not only `/`.

**How to reproduce it** (as minimally and precisely as possible):
Just set "gce" for ingress.class and deploy on GKE.

**Anything else we need to know**:
