### ISSUE TITLE
[stable/prometheus-operator] the chart to download is incomplete

### ISSUE THREAD

**Issue by michemoche** [helm/charts#11004]
**Is this a request for help?**:

Well, it's more update the helm repo with the files present in Git

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report, I guess :)

**Version of Helm and Kubernetes**:
helm v2.11.0
k8s v1.13.2

**Which chart**:
stable/prometheus-operator

**What happened**:
the chart available for use doesn't not contain **endpoints.yaml** for 2 exporters
- prometheus-operator/templates/exporters/kube-scheduler/
- prometheus-operator/templates/exporters/kube-controller-manager/

**What you expected to happen**:
to have those manifests so as to have my endpoints working correctly :)

**How to reproduce it** (as minimally and precisely as possible):
edit the values.yaml with those kind of lines : 

```
kubeControllerManager:
  endpoints:
    - 192.168.0.254
  service:
    port: 10252
    targetPort: 10252

kubeEtcd:
  endpoints:
    - 192.168.0.254
  service:
    port: 2379
    targetPort: 2379

kubeScheduler:
  enabled: true
  endpoints:
    - 192.168.9.254
  service:
    port: 10251
    targetPort: 10251
```
And only the Etcd will have its endpoint works correctly

**Anything else we need to know**:
doing a great job, thx guys :)
