### ISSUE TITLE
[incubator/patroni] option to customize bootstrap

### ISSUE THREAD

**Issue by k1ng440** [helm/charts#11014]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Which chart**:
incubator/patroni

**What happened**:
n/a

**What you expected to happen**:
Please make the chart more configurable by adding `PATRONI_CONFIGURATION` to ENV so we can modify bootstrap

https://github.com/zalando/spilo/blob/87f081c918da8e4d0b390eddb550da47730723e0/kubernetes/spilo_kubernetes_aws.yaml#L72

```
        - name: PATRONI_CONFIGURATION
          value: | ## https://github.com/zalando/patroni#yaml-configuration
            bootstrap:
              pg_hba:
                - hostnossl all all all reject
                - hostssl   all all all md5
```

**How to reproduce it** (as minimally and precisely as possible):
n/a

**Anything else we need to know**:
n/a
