### ISSUE TITLE
[stable/minio] Add support for specifying PVC selectors

### ISSUE THREAD

**Issue by predakanga** [helm/charts#11028]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
Helm: v2.12.3
Kubernetes: v1.13.2 (baremetal)

**Which chart**:
stable/minio

It would be very helpful if the minio chart had the ability to specify selectors for the generated PVC claims, both in Standalone and Distributed mode.

In order to achieve this, I'm currently using a modified chart that accepts this configuration like this:
```yaml
persistence:
  enabled: true
  storageClass: hdd
  selector:
    matchLabels:
      reserved-for: "minio"
```

Happy to provide a PR if this feature is acceptable.
