### ISSUE TITLE
[stable/redis-ha] Replicas do not initialize with networkpolicy present

### ISSUE THREAD

**Issue by gbates101** [helm/charts#11082]
**Is this a request for help?**: Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Kubernetes: `v1.11.3`
Helm:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

**Which chart**:
stable/redis-ha

**What happened**:
When applying the following network policy (which only allows ingress and egress traffic to redis pods in the same namespace), the replica pods fail to initialize with the following `config-init` container logs:

```
Could not connect to Redis at redis-io-redis-ha:26379: Try again
Initializing config..
/readonly-config/init.sh: line 91: Could not resolve the announce ip for this pod: not found
```

`networkpolicy.yaml`:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-io
spec:
  podSelector:
    matchLabels:
      app: redis-ha
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
```

**What you expected to happen**:
Redis should be able to initialize a cluster with the above network policy in place. The cluster is behaving as if it cannot talk to itself. Perhaps I am not writing the network policy properly?

**How to reproduce it** (as minimally and precisely as possible):
1. Apply above network policy manifest.
2. Deploy redis-ha chart to same namespace as network policy.

**Anything else we need to know**:
We're trying to configure a network policy to control which pods have access to the redis cluster because setting a password doesn't work (liveness probe fails since it does not specify AUTH key on request, which is another issue I'll probably open separately). Network policies also apparently do not work, unless I apply the network policy AFTER each replica is running.
