### ISSUE TITLE
[stable/kibana] failure to install plugins

### ISSUE THREAD

**Issue by hoffoo** [helm/charts#11136]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b"
Kubernetes: Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1"

**Which chart**: stable/kibana

**What happened**: the plugin install script errors out here: https://github.com/helm/charts/blob/master/stable/kibana/templates/deployment.yaml#L71

```
~ $ kubectl logs -f kibana-794d876496-rws9g -n kibana -c kibana-plugins-install
rm: cannot remove 'plugins/lost+found': Permission denied
```

**What you expected to happen**: the plugins to be installed 

**How to reproduce it** (as minimally and precisely as possible): 

```
kibana:
  plugins:
    enabled: true
    values:
      - searchguard,6.5.1-18,https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-kibana-plugin/6.5.1-18/search-guard-kibana-plugin-6.5.1-18.zip
```

**Anything else we need to know**: same error occurs when using a PVC
