### ISSUE TITLE
[stable/mongodb] Error: YAML parse error on mongodb/templates/svc-primary-rs.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by dabeeru** [helm/charts#11157]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
`Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`
`Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`

**Which chart**:
stable/mongodb

**What happened**:
`Error: YAML parse error on mongodb/templates/svc-primary-rs.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context`

**What you expected to happen**:
Chart evaluated properly, and new release created 

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/mongodb --set replicaSet.enabled=true,service.clusterIP=None`

**Anything else we need to know**:
It seems that when replicaSet.enabled=true and service.clusterIP=None then there is additional indent in `clusterIP: None` line.

Take a look on part of `helm template ../charts/stable/mongodb/ --set replicaSet.enabled=true,service.clusterIP=None` output:

```
# Source: mongodb/templates/svc-primary-rs.yaml

apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-mongodb
  labels:
    app: mongodb
    chart: mongodb-5.3.0
    release: "RELEASE-NAME"
    heritage: "Tiller"
spec:
  type: ClusterIP
   clusterIP: None  # Additional indent is this line
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb
    release: "RELEASE-NAME"
    component: primary
```
