### ISSUE TITLE
[stable/kubernetes-dashboard] Can't sign on to dashboard (401 error on loading login page, error in console) using Ingress

### ISSUE THREAD

**Issue by rafaelalmeida** [helm/charts#11170]
BUG (possible bug) report

**Version of Helm and Kubernetes**: Helm `v2.11.0`, k8s 1.10 (`v1.10.11-eks`)

**Which chart**: `stable/kubernetes-dashboard` (chart version `1.2.0`)

**What happened**: Can't sign on to dashboard (401 error on loading login page, error in console) using Ingress

**What you expected to happen**: Dashboard should load normally (works fine with `kubectl proxy`)

**How to reproduce it** (as minimally and precisely as possible): Use the following configurations in `values.yaml` in the Ingress part:

```
ingress:
  enabled: true
  paths: 
    - /
  hosts:
    - k8s-dashboard.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/tls-acme: 'true'
```

Then observe error in console:

![screen shot 2019-02-05 at 16 41 47](https://user-images.githubusercontent.com/898911/52296455-91704300-2965-11e9-99a3-ca7b4db4a0cd.png)

Then try to login using either method (I'm using token), and notice that nothing happens in the screen, although the login requests were made and were successful:

![screen shot 2019-02-05 at 16 45 03](https://user-images.githubusercontent.com/898911/52296463-96cd8d80-2965-11e9-813f-ba464b301f40.png)
