### ISSUE TITLE
[stable/sonatype-nexus] Ingress template creates rules unconditionally

### ISSUE THREAD

**Issue by gypsydiver** [helm/charts#11193]
**BUG REPORT**

**Version of Helm and Kubernetes**:
Helm v2.12.3
K8s v1.10.5

**Which chart**:
stable/sonatype-nexus

**What happened**:
Enabling ingress but not setting `.Values.nexusProxy.env.nexusDockerHost` or `.Values.nexusProxy.env.nexusHttpHost` results in "hostless" ingress rules that could have unintended effects in the cluster depending on the ingress controller deployed. For Traefik, this results in the nexus service becoming the default fallback for unknown ingress hosts.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
[...]
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: [REDACTED]-sonatype-nexus
          servicePort: 80
        path: /
  - host: REDACTED
    http:
      paths:
      - backend:
          serviceName: [REDACTED]-sonatype-nexus
          servicePort: 80
        path: /
[...]
```
**What you expected to happen**:
Respective ingress rules aren't created if `.Values.nexusProxy.env.nexusDockerHost` or `.Values.nexusProxy.env.nexusHttpHost` are not provided.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the chart with `.Values.ingress.enabled` set to `true` without setting `.Values.nexusProxy.env.nexusDockerHost` or `.Values.nexusProxy.env.nexusHttpHost`.

**Anything else we need to know**:
Can provide PR for this.
