### ISSUE TITLE
[table/prometheus-operator] Add Grafana Datasource with API Key

### ISSUE THREAD

**Issue by rewt** [helm/charts#11204]
Will someone please advise how to convert this [datasource](https://grafana.com/plugins/ayoungprogrammer-finance-datasource) to YAML?

![screen shot 2019-02-06 at 12 38 38 pm](https://user-images.githubusercontent.com/2464206/52361462-570db100-2a0c-11e9-8b3e-e90a49b3187e.png)

I've referenced the `configmaps-datasources.yaml` but unsure how to specify API Key

```
{{- if and .Values.grafana.enabled .Values.grafana.sidecar.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-grafana-datasource
  labels:
    {{ $.Values.grafana.sidecar.datasources.label }}: "1"
    app: {{ template "prometheus-operator.name" $ }}-grafana
{{ include "prometheus-operator.labels" $ | indent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ template "prometheus-operator.fullname" . }}-prometheus:9090/{{ trimPrefix "/" .Values.prometheus.prometheusSpec.routePrefix }}
      access: proxy
      isDefault: true
{{- end }}
```
