### ISSUE TITLE
[stable/jaeger-operator] Missing cronjob privileges

### ISSUE THREAD

**Issue by gregoryfranklin** [helm/charts#11237]
BUG REPORT

Version 1.9.0 of the jaeger-operator added two cronjobs (https://github.com/jaegertracing/jaeger-operator/pull/162) that require the additional rules adding to the role
```
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - "*"
```
Without this permission, jaeger-operator will report the following error when trying to create a jaeger:
```
level=error msg="failed to create" error="cronjobs.batch is forbidden: User \"system:serviceaccount:default:jaeger-operator\" cannot create cronjobs.batch in the namespace \"default\""
```
