### ISSUE TITLE
[stable/prometheus] unable to add storage.tsdb.no-lockfile argument

### ISSUE THREAD

**Issue by pastukhov** [helm/charts#11269]
There is no way to add --storage.tsdb.no-lockfile argument with server.extraargs for stable/prometheus chart.
server.extraargs expect for key:value array, but prometheus server expect --storage.tsdb.no-lockfile without any value.
Here is the logs 
```
Error parsing commandline arguments: unexpected true
prometheus: error: unexpected true
```

**Comment by pastukhov** [comment]
Part of yalues.yaml that ok for helm but not ok to prom:
```
prometheus:
  server:
    extraArgs:
      storage.tsdb.no-lockfile: true
      log.level: debug
```
How it can be:
```
prometheus:
  server:
    extraArgs:
      --storage.tsdb.no-lockfile
      --log.level=debug
```
