### ISSUE TITLE
[stable/unifi] #10789 breaks LoadBalancer services

### ISSUE THREAD

**Issue by bootc** [helm/charts#11268]
**Is this a request for help?**:

This is a bug introduced with #10789.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/unifi` 0.3.0

**What happened**:

#10789 was merged, combining the STUN and discovery services into one, which combines TCP and UDP ports in one service now. This makes it impossible to use with `LoadBalancer` services, which is how I was exposing the UniFi service to my network (with MetalLB and its options to combine multiple `LoadBalancer` services into one external IP address).

**What you expected to happen**:

I did not expect breaking changes in a chart with only a minor revision bump for a start.

**How to reproduce it** (as minimally and precisely as possible):

I use the following values in a `values.yaml` file (among others) with MetalLB to expose the service:

```
    controllerService: &lb-service
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: k8s-ext57
      loadBalancerIP: 192.0.2.123  # example IP

    stunService: *lb-service

    discoveryService: *lb-service
```

**Anything else we need to know**:

It should be fine to combine the STUN and discovery services, just not also the controller service. I don't really see the utility of having a single cluster IP as you can't connect access points and switches to a cluster-internal-only IP address unless you're doing something unusual...
