### ISSUE TITLE
[stable/prometheus-operator] Does not detect ServiceMonitor and Prometheus kind

### ISSUE THREAD

**Issue by kamilgregorczyk** [helm/charts#11310]
**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

minikube version: v0.33.1
```

**Which chart**:
stable/prometheus-operator

**What happened**:
After installing ServiceMonitor and Prometheus configs I don't see any new targets in Prometheus/targets endpoint. Http service that I use is exposing /metrics endpoint with properly formatted response.

**What you expected to happen**:
I expected new endpoint to be registered

**How to reproduce it** (as minimally and precisely as possible):
Apply following configs for prometheus
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micronaut-blog
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: micronaut-blog
    namespaceSelector:
      matchNames:
        - micronaut-blog
  endpoints:
    - port: http-server
      interval: 30s

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector:
    matchLabels:
      prometheus: kube-prometheus
    namespaceSelector:
      matchNames:
        - micronaut-blog
```

I'm also having such deployment & service:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micronaut-blog
  namespace: micronaut-blog
  labels:
    app: micronaut-blog
spec:
  replicas: 1
  template:
    metadata:
      name: micronaut-blog
      labels:
        app: micronaut-blog
    spec:
      containers:
        - name: micronaut-blog
          image: uniqe15/micronaut-blog:0.13
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-mongodb
                  key: mongodb-root-password
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: user
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: host
      restartPolicy: Always
  selector:
    matchLabels:
      app: micronaut-blog
---
apiVersion: v1
kind: Service
metadata:
  name: micronaut-blog
  namespace: micronaut-blog
  labels:
    app: micronaut-blog
spec:
  selector:
    app: micronaut-blog

  ports:
    - name: http-server
      port: 8080
  type: NodePort
```

Here are my pods
```
➜  blog git:(master) ✗ kubectl get pods --all-namespaces                
NAMESPACE        NAME                                                      READY   STATUS    RESTARTS   AGE
kube-system      coredns-86c58d9df4-59jnm                                  1/1     Running   0          54m
kube-system      coredns-86c58d9df4-xcv52                                  1/1     Running   0          54m
kube-system      etcd-minikube                                             1/1     Running   0          53m
kube-system      heapster-mm4cq                                            1/1     Running   0          54m
kube-system      influxdb-grafana-qjb8k                                    2/2     Running   0          54m
kube-system      kube-addon-manager-minikube                               1/1     Running   0          53m
kube-system      kube-apiserver-minikube                                   1/1     Running   0          53m
kube-system      kube-controller-manager-minikube                          1/1     Running   0          53m
kube-system      kube-proxy-76jf9                                          1/1     Running   0          54m
kube-system      kube-scheduler-minikube                                   1/1     Running   0          53m
kube-system      kubernetes-dashboard-ccc79bfc9-qgr5l                      1/1     Running   0          54m
kube-system      metrics-server-6fc4b7bcff-xz7rs                           1/1     Running   0          54m
kube-system      storage-provisioner                                       1/1     Running   0          54m
kube-system      tiller-deploy-69ffbf64bc-894zk                            1/1     Running   0          54m
micronaut-blog   micronaut-blog-6dbdbc6fb-4bc8x                            1/1     Running   0          39m
micronaut-blog   mongo-mongodb-5c79bd4784-8qwhk                            1/1     Running   0          32m
monitoring       alertmanager-prometheus-operator-alertmanager-0           2/2     Running   0          53m
monitoring       prometheus-operator-grafana-8559d7df44-rrlk4              3/3     Running   0          53m
monitoring       prometheus-operator-kube-state-metrics-7769f5bd54-sj4ls   1/1     Running   0          53m
monitoring       prometheus-operator-operator-7967865bf5-6mhz9             1/1     Running   0          53m
monitoring       prometheus-operator-prometheus-node-exporter-dkgdn        1/1     Running   0          53m
monitoring       prometheus-prometheus-0                                   3/3     Running   1          5m50s
monitoring       prometheus-prometheus-operator-prometheus-0               3/3     Running   1          52m
```

**Comment by tbuchier** [comment]
Hello

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector:
    matchLabels:
      prometheus: kube-prometheus
    namespaceSelector:
      matchNames:
        - micronaut-blog
```

Here, you configured prometheus to look for serviceMonitors in the namespace "micronaut-blog"
(namespaceSelector) but previously you defined your serviceMonitor in the namespace "monitoring"

```
kind: ServiceMonitor
metadata:
  name: micronaut-blog
  namespace: monitoring
```

that's why there aren't detected

**Comment by kamilgregorczyk** [comment]
Thanks, I think I fixed my service monitor but I'm still not able to see it even if running on GCP:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micronaut-blog
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: micronaut-blog
    namespaceSelector:
      matchNames:
        - micronaut-blog
  endpoints:
    - port: http-server
      interval: 30s

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector:
    matchLabels:
      prometheus: kube-prometheus
    namespaceSelector:
      matchNames:
        - monitoring
```

**Comment by tbuchier** [comment]
Hmm just to test, could you try with an empty serviceMonitorSelector, so Prometheus will select all serviceMonitor running anywhere in the cluster, an the check if some target appear ?

With this config in the values.yaml :
```
    serviceMonitorSelectorNilUsesHelmValues: false
    ## serviceMonitorSelector will limit which servicemonitors are used to create scrape
    ## configs in Prometheus. By default all are loaded
    ##
    serviceMonitorSelector: {}
    ## serviceMonitorNamespaceSelector will limit namespaces from which serviceMonitors are used to create scrape
    ## configs in Prometheus. By default all namespaces will be used
    ##
    serviceMonitorNamespaceSelector: {}
```

Which should produce the following config in your prometheus CRD : 
```
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
```

**Comment by kamilgregorczyk** [comment]
Ok, I installed operator with this command:
```
helm install stable/prometheus-operator --namespace monitoring --name prometheus-operator --set serviceMonitorSelectorNilUsesHelmValues=false
```
and with such ServiceMonitor and Prometheus:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micronaut-blog
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: micronaut-blog
    namespaceSelector:
      matchNames:
        - micronaut-blog
  endpoints:
    - port: http-server
      interval: 30s

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
```
and I still can't see anything in targets
