### ISSUE TITLE
[stable/postgresql] error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext

### ISSUE THREAD

**Issue by frwickst** [helm/charts#11351]
I'm using Helm templates but not Tiller for deploying Postgres and is running into the following issues after a patch that was recently introduced.

**Version of Helm and Kubernetes**:
Helm: 2.12.3
Kubernetes: 1.11.6 (`kubectl` from the same version)

**Which chart**:
stable/postgresql

**What happened**:
When applying the config files the follow error appears:

error: error validating "<_REDACTED_path_to_rendered_templates>/statefulset.yaml": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**:
No error

**How to reproduce it** (as minimally and precisely as possible):
```
helm fetch stable/postgresql --untar --untardir ./database/helm
mkdir -p ./database/manifests
helm template database/helm/postgresql \
  --namespace "<NAMESPACE>" \
  --name "<NAME>" \
  --set image.tag="<POSTGRES_VERSION-DOES-NOT-MAKE-A-DIFFERENCE>" \
  --set postgresqlUsername="<USERNAME>" \
  --set postgresqlPassword="<PASSWORD>" \
  --set postgresqlDatabase="<DATABASE>" \
  --output-dir ./database/manifests

kubectl apply --recursive -f ./database/manifests/postgresql
```

**Anything else we need to know**:
This started happening after the following patch was introduced:
https://github.com/helm/charts/commit/895ef9b7d095ddaace220c2f8230cccf45346eef#diff-7cc3f808fcb264d3efe83e85db9b5ef2

**Comment by frwickst** [comment]
After googling around I have yet to find one place that specifies `fsGroup` under containers.securityContext. Is this a mistake in the template?
Here you can see a redacted version of the rendered template (note that some full lines has been removed and some text has been redacted, this is more for showing the structure then anything):

```
# Source: postgresql/templates/statefulset.yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: <REDACTED>
  labels:
    app: postgres
    chart: postgresql-3.10.2
    release: "<REDACTED>"
    heritage: "Tiller"
spec:
  serviceName: <REDACTED>-postgres-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: postgres
      release: "<REDACTED>"
      role: master
  template:
    metadata:
      name: <REDACTED>-postgres
      labels:
        app: postgres
        chart: postgresql-3.10.2
        release: "<REDACTED>"
        heritage: "Tiller"
        role: master
    spec:
      initContainers:
      - name: init-chmod-data
        image: docker.io/bitnami/minideb:latest
        command:
          - sh
          - -c
          - |
            chown -R 1001:1001 /bitnami
            if [ -d /bitnami/postgresql/data ]; then
              chmod  0700 /bitnami/postgresql/data;
            fi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
      containers:
      - name: <REDACTED>
        image: docker.io/bitnami/postgresql:<REDACTED>
        securityContext:
          fsGroup: 1001
          runAsUser: 1001
```
