### ISSUE TITLE
[stable/gitlab-ce] gitlab-ce pod `FailedScheduling` due to `NoVolumeZoneConflict`

### ISSUE THREAD

**Issue by crackmac** [helm/charts#1136]
Bottomline: PVCs for gitlab-ce pod (gitlab-ce-data & gitlab-ce-etc) are not guarenteed to launch in same availability zone in a multi-zone k8s node topology. This prevents the  gitlab-ce pod from being scheduled since it can not mount the volumes. 

Maybe there is a way to link or bundle the the two PVCs or force them into a specific zone?

**Comment by justinsb** [comment]
I encountered a similar issue with a different gitlab chart, and I combined the etcd and data volumes to work around this.

**Comment by rishka** [comment]
you can create a separate storage class that is only available in one AZ, thats how I got around it.

**Comment by crackmac** [comment]
Thanks @justinsb. I ditched the etcd volume and used subpaths in the `deployment.yaml` to split up the gitlab-data volume. 

```
 volumeMounts:
 - name: gitlab-data
   mountPath: /etc/gitlab
   subPath: gitlab
 - name: gitlab-data
   mountPath: /gitlab-data
   subPath: gitlab-data
```

Works and I'll monitor the gitlab-data volume for space issues.
