### ISSUE TITLE
Keycloak Invalid parameter: redirect_uri nginx-ingress

### ISSUE THREAD

**Issue by miguel-veliz** [helm/charts#11396]
**Is this a request for help?**:

Yes

**Version of Helm and Kubernetes**:

EKS

**Which chart**:

stable/keycloak

**What happened**:
Invalid parameter: redirect_uri

**How to reproduce it** (as minimally and precisely as possible):

Base install of stable/keycloak with the follwing values.yaml   
```
extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
```

Base install of stable/nginx-ingress with the following values.yaml

```
controller:
  config:
    proxy-protocol: "true"
    real-ip-header: "proxy_protocol"
    set-real-ip-from: "0.0.0.0/0"
  
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:xxxx"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
```

web-ingress looks like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations :
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: auth.mydomain.com
    http:
      paths:
      - backend:
          serviceName: keycloak-http
          servicePort: 80
```

So when i try going to https://auth.mydomain.com and click on admin console i get: Invalid parameter: redirect_uri
