### ISSUE TITLE
[stable/jenkins] Master.Sidecars.other and Master.JCasC.enabled do not work in combination

### ISSUE THREAD

**Issue by torstenwalter** [helm/charts#11412]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Which chart**: stable/jenkins

**What happened**:

Master.Sidecars.other is rendered within sidecar for CasC. So the rendered Deployment is invalid.

**What you expected to happen**:

I expect a valid DeploymentConfig

**How to reproduce it** (as minimally and precisely as possible):

helm install with the following values fails:
```
Master:
  JCasC:
    enabled: true
  Sidecars:
    configAutoReload:
      enabled: true
    other:
      - name: smee
        image: quay.io/cloudifire/smee-client:1.0.2
        args: ["--port", "{{ .Values.Master.ServicePort }}", "--path", "/github-webhook/", "--url", "https://smee.io/new"]
```

**Anything else we need to know**:
