### ISSUE TITLE
Nginx-ingress post requests return "The method is not allowed for the requested URL"

### ISSUE THREAD

**Issue by devops-tl** [helm/charts#11429]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Version of Helm and Kubernetes**:
Helm Version: v2.12.3
Kubernetes Version: v1.13.3

**Which chart**:
stable/nginx-ingress

**What happened**:
HTTP POST requests returns 405 error code : The method is not allowed for the requested URL

Output from nginx-ingress controller pod: 
`***** - [*****] - - [14/Feb/2019:16:11:30 +0000] "POST /<service>/request/action HTTP/1.1" 405 64 "-" "PostmanRuntime/7.6.0" 433 0.004 [default-<service>-80] ****:80 64 0.004 405 31e6d12e4ba1402008f678f08825118e`

When i used port-forwarding to the service - the application responded as expected

**What you expected to happen**:
The Application respond to the request

**How to reproduce it** (as minimally and precisely as possible):
It happend to on helm version: 1.3.0 app version: 0.22.0

Ingress configuration:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: hostname.domainname
    http:
      paths:
      - backend:
          serviceName: servicename
          servicePort: 80
        path: /servicename
```

**Anything else we need to know**:
Rolleback to helm version: 1.1.2 app version: 0.21.0 "fixed" the issue
