### ISSUE TITLE
[Airflow] Allow multiple secrets in secretsMapping

### ISSUE THREAD

**Issue by strobus** [helm/charts#11425]
**Is this a request for help?**: 

No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Version of Helm and Kubernetes**:

Helm 2.12, Kube 1.11

**Which chart**:

Airflow

**What happened**:

I am bringing my own Postgres and Redis deployments. They have separate secrets in kubernetes containing their passwords. The current Airflow chart only supports one `.Values.existingAirflowSecret` from which to pull both Postgres and Redis secrets.

**What you expected to happen**:

I would like to be able to specify the name of the secret to pull from for each value in `.Values.airflow.secretsMapping`

**How to reproduce it** (as minimally and precisely as possible):

Create a secret in kubernetes named `postgres`. It should contain only the Postgres password.
Create a second secret named `redis`. It should contain only the Redis password.

Set `.Values.existingAirflowSecret` to `postgres`.

Set a `.Values.airflow.secretsMapping`:
```
  secretsMapping:
  - envVar: POSTGRES_PASSWORD
    secretKey: postgres-password
  - envVar: REDIS_PASSWORD
    secretKey: redis-password
```

Note that there is no way to specify the `secretName`.

This is what I would like to be able to do:

```
  secretsMapping:
  - envVar: POSTGRES_PASSWORD
    secretName: postgres
    secretKey: postgres-password
  - envVar: REDIS_PASSWORD
    secretName: redis
    secretKey: redis-password
```

**Anything else we need to know**:

PR is forthcoming.
