### ISSUE TITLE
Can't access grafana login with /grafana path.

### ISSUE THREAD

**Issue by ghost** [helm/charts#11436]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
```
lient: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

k8: 1.11.7

```

**Which chart**:
grafana

**What happened**:
I have a domain foo.bar, and I am using an nginx-ingress controller to access the grafana service. Here is the relevant chunk of my values.yaml. 
```
ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     ingress.kubernetes.io/secure-backends: "true"
  labels:
  path: /grafana
  hosts:
    - foo.bar
  tls:
    - secretName: foo.bar
      hosts:
        - foo.bar
```
Here is the grafana.ini chunk:
```
grafana.ini:
  server:
    root_url: https://foo.bar/grafana
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
```
This resulted in 
![image](https://user-images.githubusercontent.com/28328606/52815731-484e7c00-3054-11e9-82c9-1873ef185aca.png)

**What you expected to happen**:
I expected to be able to access grafana login. Everything with the above setup works correctly if I use "/" for the ingress path instead of "/grafana".

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I have tried this suggestion with no luck 
https://github.com/helm/charts/issues/6264#issuecomment-399363457

**Comment by asychev** [comment]
Maybe this helps: https://github.com/grafana/grafana/issues/2066#issuecomment-464158266

**Comment by jrvanalstine** [comment]
Ok thanks I will try this and post here if it was the problem.

**Comment by kpkristjansson** [comment]
I believe you need to add the following:

```yaml
grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
```
