### ISSUE TITLE
Ghost chart doesn't work correctly when ClusterIP used

### ISSUE THREAD

**Issue by acim** [helm/charts#11470]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

v1.13.2, v2.12.3

**Which chart**:

stable/ghost

**What happened**:

This is the relevant part of my configuration:
```
ghostProtocol: http
ghostHost: www.mysite.net
ghostPath: /
service:
  type: ClusterIP
  port: 80
service:
  type: ClusterIP
  port: 80
  nodePorts:
    http: ""
  externalTrafficPolicy: Cluster
ingress:
  enabled: true
  certManager: true
  annotations:
   kubernetes.io/ingress.class: nginx
  hosts:
  - name: www.mysite.net
    path: /
    tls: true
    tlsSecret: mysite-net-tls
```
Then URL's generated by Ghost are like http:/www.mysite.net/:80 instead of https://www.mysite.net

In the Deployment object I can find this:

```
        - name: GHOST_HOST
          value: www.mysite.net/
        - name: GHOST_PROTOCOL
          value: http
        - name: GHOST_PORT_NUMBER
          value: "80" 
```

**What you expected to happen**:

And I think it should be:
```
          value: "www.mysite.net"
        - name: GHOST_PROTOCOL
          value: "https"
        - name: GHOST_PORT_NUMBER
          value: 443
```
Maybe even without the GHOST_PORT_NUMBER

**How to reproduce it** (as minimally and precisely as possible):

Install chart using the above values.

**Anything else we need to know**:
