### ISSUE TITLE
[stable/janusgraph] Ability to set arbitrary Env vars or JAVA_OPTIONS

### ISSUE THREAD

**Issue by etiennedi** [helm/charts#11543]
**Is this a request for help?** :

no

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

The standard java options (including heap-size) are set in `bin/gremlin-server.sh`, but they can be overwritten with the env var `JAVA_OPTIONS`. We thus need 

- either the  ability to set the `JAVA_OPTIONS` variable through the `values.yaml`
- or the ability to set any environment variable through the `values.yaml`

## Please let me know which option you prefer and I'm happy to submit a PR.

**Version of Helm and Kubernetes**:
n/a

**Which chart**:
`@stable/janusgraph`

**What happened**:
n/a (feature request)

**What you expected to happen**:
n/a (feature request)

**How to reproduce it** (as minimally and precisely as possible):
n/a (feature request)

**Anything else we need to know**:

**Comment by etiennedi** [comment]
This is still very much relevant for us. Commenting to remove the `stale` label. An answer would be appreciated, I am also happy to submit the relevant PR if we agree that this feature should be added.

**Comment by etiennedi** [comment]
Commenting to remove the stale label. Could someone comment on one of the two options outlined in the OP, still happy to provide a PR. Thanks.

**Comment by bobvanluijt** [comment]
Would be much appreciated if someone could help regarding the PR options. Maybe @carrodher or 
@javsalgar know the answer?

**Comment by carrodher** [comment]
I'm sorry but I don't know how this chart works. According to https://github.com/helm/charts/blob/master/stable/janusgraph/Chart.yaml#L11 you should ping @samizuh.

In the other hand, you can do something like:
```yaml
      containers:
     - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.javaOpts }}
        - name: JAVA_OPTS
          value: {{ .Values.javaOpts | quote }}
        {{- end }}
```
in the _deployment.yaml_. Also add the option in the _values.yaml_:
```
## Customize JVM parameters
##
# javaOpts:
```

But the image should work with this env. variable
