### ISSUE TITLE
[stable/sonarqube] liveness probe fails due to small timeout period

### ISSUE THREAD

**Issue by hassbert** [helm/charts#11578]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

I would like to define the timout seconds for the liveness probe via the values.yml.
The option `timeoutSeconds` should be added to the values.yml so it gets defined in the deployment template:
```
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.sonarWebContext }}sessions/new
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
```

**Version of Helm and Kubernetes**:
Helm: 2.12.1
Kubernetes: v1.11.6

**Which chart**:
stable/sonarqube

**What happened**:
My SonarQube pod is getting restarted from time to time due to a failed liveness probe. As I did not identify any issues with the application I assume it is due to a too short timeout period.

**What you expected to happen**:
I would like to define the timeout period via the values.yml

**How to reproduce it** (as minimally and precisely as possible):
Increase the load and requests on SonarQube.

**Anything else we need to know**:
