### ISSUE TITLE
[stable/spinnaker] Redis password is stored in configmap

### ISSUE THREAD

**Issue by darend** [helm/charts#11589]
**Which chart**:

stable/spinnaker 1.6.0

**What happened**:

When configuring spinnaker to use an external redis, the password is stored in a configmap

https://github.com/helm/charts/blob/76071209a8014e0abaa54482bd11fdfa708a6056/stable/spinnaker/templates/configmap/service-settings.yaml#L11

**What you expected to happen**:

The redis configuration is stored as a secret. 

**How to reproduce it** (as minimally and precisely as possible):

In your values file, set the following:

```
redis:
  enabled: false
  external:
    host: redis.spinnaker
    password: my_password
```
