### ISSUE TITLE
[stable/prometheus-operator] add ServiceMonitor for Grafana

### ISSUE THREAD

**Issue by losil** [helm/charts#11598]
** FEATURE REQUEST**

The grafana sub chart does not provide a servicemonitor resource. Can you add something like this to the grafana subchart?

```
{{- if .Values.selfServiceMonitor }}
apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "grafana.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: grafana
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}    
  name: {{ template "grafana.fullname" . }}
spec:
  jobLabel: {{ template "grafana.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "grafana.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: http
    interval: 30s
{{- end }
```
