### ISSUE TITLE
[stable/rabbitmq] Chart not using defined K8s secrets for existingPasswordSecret or existingErlangSecret

### ISSUE THREAD

**Issue by chrisbelyea** [helm/charts#11628]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**:
```shell
# helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
# k8s version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: stable/rabbitmq-4.3.0

**What happened**:
Installing the chart did not use the `existingPasswordSecret` or `existingErlangSecret` values I had passed in my values.yaml.

```shell
# Installing the chart
helm install \
  --name rabbit-cluster \
  --values values.yaml \
  stable/rabbitmq
```

This is my Kubernetes secret:
```json
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "rabbit-cluster"
  },
  "data": {
    "rabbitmq-password": "base64abc123=",
    "rabbitmq-cookie": "base64xyz890="
  },
  "type": "Opaque"
}
```

This is the relevant snippet of values.yaml:
```yaml
  ## RabbitMQ application password
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  # password:
  # existingPasswordSecret: name-of-existing-secret
  existingPasswordSecret: rabbit-cluster

  ## Erlang cookie to determine whether different nodes are allowed to communicate with each other
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  # erlangCookie:
  # existingErlangSecret: name-of-existing-secret
  existingErlangSecret: rabbit-cluster
```

**What you expected to happen**:
I expected that the chart would use the password and cookie values I had in the K8s secret for configuring RabbitMQ.

**How to reproduce it** (as minimally and precisely as possible):
1. Create the K8s secret as defined above (insert some real base64-encoded values).
1. Use the [default values.yaml](https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml) and substitute in the section above with `existingPasswordSecret` and `existingErlangSecret`.
1. Run the `helm install` command above.
1. Check the `RABBITMQ_ERL_COOKIE` environment variable of the pod(s) created.

**Anything else we need to know**:
https://github.com/helm/charts/pull/10699 may be relevant.
