### ISSUE TITLE
[stable/minio] `export` volume not found in standalone mode

### ISSUE THREAD

**Issue by WoLfulus** [helm/charts#11659]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm v2.12.1
Kubernetes v1.10.11

**Which chart**:

stable/minio

**What happened**:

```
release minio failed: Deployment.apps "minio" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "export"
```

**What you expected to happen**:

Chart installed successfully

**How to reproduce it** (as minimally and precisely as possible):

Run in standalone mode with s3 gateway enabled.

```yaml
ingress:
  enabled: true
  path: /storage
  hosts:
    - myhost.com
defaultBucket: 
  enabled: true
  name: mybucket
s3gateway:
  enabled: true
  replicas: 1
```

**Anything else we need to know**:

Seems like the check that appends the export volumeMount is different from the one that appends the volume.

https://github.com/helm/charts/blob/master/stable/minio/templates/deployment.yaml#L85

https://github.com/helm/charts/blob/master/stable/minio/templates/deployment.yaml#L165
