### ISSUE TITLE
[stable/wordpress] Metrics resource limits and requests at once

### ISSUE THREAD

**Issue by triqster** [helm/charts#11733]
---
**BUG REPORT**:

**Version of Helm and Kubernetes**:
Helm: v2.11.0
Kubernetes: v1.12.5

**Which chart**:
stable/wordpress

**What happened**:
When using both resource limits and requests it fails on rendering the template.

**What you expected to happen**:
Be able to set both resource limits and requests

**How to reproduce it** (as minimally and precisely as possible):

```
metrics:
  resources:
    limits:
      memory: 100Mi
      cpu: 50m
    requests:
      memory: 50Mi
      cpu: 20m
```
in the values file

**Anything else we need to know**:
PR inc to fix this
