### ISSUE TITLE
grafana does not mount dashboard volumes of type 'file'

### ISSUE THREAD

**Issue by kwtalley** [helm/charts#11825]
**Is this a request for help?**: 
yes

---

**Is this a BUG REPORT or FEATURE REQUEST?**: 
bug report

**Version of Helm and Kubernetes**: 
k8s: v1.10.11
helm: v2.12.3

**Which chart**: 
grafana

**What happened**: 
adding dashboard json file to 'dashboards' in values.yaml does not mount in container.

**What you expected to happen**: 
json dashboard file is added to grafana dashboards provider path in container

**How to reproduce it** (as minimally and precisely as possible): 
create dashboard json file. add to 'dashboards' section in values.yaml using key type **file**.

**Anything else we need to know**:
the ConfigMap is created correctly, however it is not mounted in the container due to:
https://github.com/helm/charts/blob/fbc9f1d3654ee8bd2f29dac1e7035a2e24600b5a/stable/grafana/templates/deployment.yaml#L155-L158
line 155 needs ```(or (hasKey $value "json") (hasKey $value "file"))``` statement instead, same as
https://github.com/helm/charts/blob/fbc9f1d3654ee8bd2f29dac1e7035a2e24600b5a/stable/grafana/templates/dashboards-json-configmap.yaml#L17

**Comment by maorfr** [comment]
Hey @kwtalley,

Thanks for bringing this up! I was the one who added the `file` dashboard type, must have missed that.
As this is your first issue with helm, would you like to get further involved and try to tackle this issue? :)

**Comment by alexvicegrab** [comment]
Seeing similar issue myself

**Comment by alexvicegrab** [comment]
My configmap has something like this:

```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    dashboardA:
      file: dashboardA.json
    dashboardB:
      file: dashboardB.json

dashboardsConfigMaps:
   default: "grafana--dashboards"
```
