### ISSUE TITLE
[stable/nginx-ingress] AWS Load Balancer (ELB) configuration does not update

### ISSUE THREAD

**Issue by sallar** [helm/charts#11834]
**Is this a request for help?**:

YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT (I think)

**Version of Helm and Kubernetes**:

Helm v2.10.0 
Kubernetes v1.10.12

**Which chart**:

stable/nginx-ingress

**What happened**:

I tried adding the following annotation to my values.yml file:

```yaml
controller:
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:XX-XXXX-X:XXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
```

And then tried to upgrade helm chart to apply these changes:

```sh
helm upgrade -f nginx-ingress.yaml nginx-ingress stable/nginx-ingress
```

But the settings (AWS SSL Cert config) are not applied to my ELB on AWS. Seems like the chart upgrade does not re-configure the AWS ELB.

**What you expected to happen**:

The ELB should have been upgraded with correct SSL info.

**How to reproduce it** (as minimally and precisely as possible):

- Deploy nginx-ingress without the above configuration (on AWS)
- Use normally without https
- Try to upgrade the chart to add the new annotations
- Annotations are not applied to the AWS ELB

**Anything else we need to know**:
