### ISSUE TITLE
[stable/ghost] Liveness probe with https protocol fails with reverse proxy redirecting to https

### ISSUE THREAD

**Issue by Dennor** [helm/charts#11844]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST (I think)

**Version of Helm and Kubernetes**:

Helm:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"archive", BuildDate:"2019-02-15T08:21:09Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: stable/ghost

**What happened**: 

Running ghost behind reverse proxy that forces https redirect causes liveness probe to faile because of redirect loop.

**What you expected to happen**: Running release

**How to reproduce it** (as minimally and precisely as possible):

Setup minikube with ingress enabled and CoreDNS config edited to include hosts plugin mapping host.local to host ip
```
ghostHost: host.local
ghostProtocol: https
persistence:
  enabled: false
service:
  port: 443
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
  - name: host.local
    tls: true

```

**Anything else we need to know**:
A small workaround I used was to add:
```
{{- if eq .Values.ghostProtocol "https" }}
- name: X-Forwarded-Proto
  value: https
{{- end }}
```
to liveness and readiness probes httpHeaders in `deployment.yaml`

So this is either a feature request to support reverse proxies that redirect all traffic to https or if that is inteded use case, it is a bug report.
