### ISSUE TITLE
Remove chart version from label.chart

### ISSUE THREAD

**Issue by remmeier** [helm/charts#11858]
Many charts make use of:

```
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
```

Having `{{ .Chart.Version }}` in the yaml leads to issues with the Kubernetes up-to-date checking, triggering an update of components that did not change. In particular in larger deployments with many components this is undesired.

If that should remain the desired default, maybe it would be worthwhile to add a template that allows customization of the chart name.
