### ISSUE TITLE
[stable/elasticsearch] plugin installation not working

### ISSUE THREAD

**Issue by cortopy** [helm/charts#11855]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.12.3
Kubernetes 1.11

**Which chart**:
stable/elasticsearch

**What happened**:
Plugins are not installed in the nodes

**What you expected to happen**:
Plugins to be installed

**How to reproduce it** (as minimally and precisely as possible):
Create a values file

```
cluster:
  plugins:
    - repository-s3
```
And run

```
helm install stable/elasticsearch -f myfile.yaml
```

Then, when I query the cluster with `GET _nodes` the `respository-s3` is not installed in any of the nodes

**Comment by azman0101** [comment]
I'm not able to install plugin to and get multiple error:

```
kubectl logs -n elasticsearch es-customer-elasticsearch-client-6499f86669-wdgmd -c es-plugin-install
-> Downloading repository-gcs from elastic
[=================================================] 100%??
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission setFactory
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.URLPermission http://www.googleapis.com/* *:
* java.net.URLPermission https://www.googleapis.com/* *:
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed repository-gcs```


And then, the POD keep crashing:

```
es-customer-elasticsearch-client-6499f86669-wdgmd   0/1       CrashLoopBackOff   3          2m
```

with this error:

```
[2019-03-06T20:07:31,721][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-customer-elasticsearch-client-6499f86669-wdgmd] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.ml.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.15.jar:5.6.15]
Caused by: java.lang.IllegalArgumentException: unknown setting [xpack.ml.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.node.Node.<init>(Node.java:344) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.15.jar:5.6.15]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.15.jar:5.6.15]
	... 6 more
	Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.monitoring.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

**Comment by rendhalver** [comment]
Installing plugins at container startup makes for inconsistent containers and slows down your startup.
Please do this in your container.

**Comment by chicken231** [comment]
@azman0101 I think it's worth noting explicitly that you're not using the default image with the chart. At least, it looks like you're using the non-OSS image since you're trying to use x-pack.

@rendhalver Maybe you should take your suggestion to the maintainers of the chart, not this guy who is just trying to _use_ the chart.

---

I don't have issues with installing the `repository-s3` plugin:

K8s version: `1.11.5`
Helm version: `2.13.0`
Chart version: `1.21.2`

```
cluster:
  plugins:
    - repository-s3
```

```
GET _nodes
```

```
...
      "plugins" : [
        {
          "name" : "repository-s3",
          "version" : "6.5.4",
          "elasticsearch_version" : "6.5.4",
          "java_version" : "1.8",
          "description" : "The S3 repository plugin adds S3 repositories",
          "classname" : "org.elasticsearch.repositories.s3.S3RepositoryPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        }
...
```

**Comment by desaintmartin** [comment]
As one of the chart maintainers, I reviewed and accepted the PR introducing this feature. Do you think it was a mistake? Of course it will not work for all cases and maybe this should be documented, but lightweight plugins like s3 take less than 10 seconds to install and free us from the burden of maintaining a custom image on top of the official one.

**Comment by cortopy** [comment]
Also, the s3 plugin is officially supported by the elastic team themselves. Here is the [full list](https://github.com/elastic/elasticsearch/tree/master/plugins)

Maybe this feature could be limited to just that small list?

**Comment by jankenr** [comment]
I installed the plugin called "analysis-icu" but when trying to apply it and create a template with an analyzer and filter, i receive this error:
```
{
  "error": {
    "root_cause": [{
      "type": "remote_transport_exception",
      "reason": "[elasticsearch-master-0][10.4.20.19:9300][indices:admin/template/put]"
    }],
    "type": "illegal_argument_exception",
    "reason": "Unknown filter type [icu_folding] for [locationnames]"
  },
  "status": 400
}
```

It seems the plugin is installed on the clients but not on the master or data nodes.
How can I fix this?

**Comment by anapsix** [comment]
I've came across a similar issue with Elasticsearch v5.6.x
By default, the following plugins are installed: `x-pack`, `ingest-geoip`, and `ingest-user-agent`. When using `cluster.plugins: [ repository-s3 ] ` to install `repository-s3`,  the plugins directory gets reinitialized, and is missing the default plugins, specifically `x-pack`, which is required to join X-Pack enabled cluster.
Including `x-pack` into `cluster.plugins:` does not help, since `/usr/share/elasticsearch/bin/x-pack` directory is not empty, causing installation of `x-pack` plugin to fail.

In a roundabout way, I'm reinstalling default plugins via `extraInitContainers`, while installing `repository-s3` via chart's mechanism, to ensure `plugins` directory is added to `volumes` and `volumeMounts` across `client` Deployment, and StatefulSets for `master` and `data`.
```
cluster:
  plugins:
  - repository-s3

extraInitContainers: |-
  - name: es-plugin-default
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - SYS_RESOURCE
    command:
    - "sh"
    - "-c"
    - |
      rm -rf /usr/share/elasticsearch/bin/x-pack /usr/share/elasticsearch/plugins/x-pack
      /usr/share/elasticsearch/bin/elasticsearch-plugin install -b x-pack
      /usr/share/elasticsearch/bin/elasticsearch-plugin install -b ingest-geoip
      /usr/share/elasticsearch/bin/elasticsearch-plugin install -b ingest-user-agent
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/plugins/
      name: plugindir
    - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
      name: config
      subPath: elasticsearch.yml
```
