### ISSUE TITLE
[stable/prometheus-operator] Allow to specify resources requests and limits for grafana and kube-state-metrics

### ISSUE THREAD

**Issue by mleneveut** [helm/charts#11861]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
k8s 1.12.4, helm 2.12.3

**Which chart**:
stable/prometheus-operator

**What happened**:
We can't sepcify the resources requests/limits for grafana and kube-state-metrics

**What you expected to happen**:
Be able to specify them.

**How to reproduce it** (as minimally and precisely as possible):
helm install --name prometheus stable/prometheus-operator

**Anything else we need to know**:

**Comment by vsliouniaev** [comment]
@mleneveut Both of these components are simply sub-charts of the prometheus-operator chart and limits must be set on them by accessing sub-chart values

**Comment by mleneveut** [comment]
Thanks it works.

Added this to my custom-values.yaml : 

```
grafana:
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 200Mi
  adminPassword: "mysecurepassword"

kube-state-metrics:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 50Mi

prometheus-node-exporter:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 20Mi

alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        cpu: 10m
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi
prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 250m
        memory: 2000Mi
      requests:
        cpu: 50m
        memory: 1300Mi
```
