### ISSUE TITLE
[stable/sentry] passwords reset on every deployment

### ISSUE THREAD

**Issue by ahmadalli** [helm/charts#11879]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Version of Helm and Kubernetes**: Helm 1.13.0

**Which chart**: stable/sentry

**What happened**: on every `helm upgrade --install` new secrets with new values is created for sentry, postgress and redis password while the passwords mustn't change.

**What you expected to happen**:
Passwords must remain the same

**How to reproduce it** (as minimally and precisely as possible):
run `helm upgrade --install stable/sentry` twice

**Anything else we need to know**:
this is a known issue with helm installation. As far as I know, the best solution is to get secrets from the user

**Comment by tkuther** [comment]
Cloning the initially generated sentry-postgresql and sentry-redis secrets to ...-custom and using following in values.yaml works fine here:
```
postgresql:
  existingSecret: "sentry-postgresql-custom"

redis:
  existingSecret: "sentry-redis-custom"
```
