### ISSUE TITLE
[stable/prometheus-operator] Add ability to configure MetricRelabelings to node-exporter

### ISSUE THREAD

**Issue by weikinhuang** [helm/charts#11877]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: v2.12.0
Kubernetes: v1.13.4

**Which chart**:
stable/prometheus-operator

**What happened**:
I enabled `--collector.mountstats` on `prometheus-node-exporter` to collect stats from my nfs mounts, which is my PV provider for my homelab. However I really only want the stats for read bytes and write bytes for each mount.

It seems unnecessary to collect all the stats into prometheus, ex. `node_mountstats_nfs_operations_response_time_seconds_total` and `node_mountstats_nfs_operations_sent_bytes_total`.

I really only want for example `node_mountstats_nfs_total_read_bytes_total` and `node_mountstats_nfs_total_write_bytes_total` to be written to save storage space in prometheus.

**What you expected to happen**:
Be able to specify relabelings with node-exporter like with the kubelet option `kubelet.serviceMonitor.cAdvisorMetricRelabelings` I want to be able to drop itemss
```
    - sourceLabels: [__name__]
      separator: ;
      regex: node_mountstats_nfs_operations
      replacement: $1
      action: drop
```

**How to reproduce it** (as minimally and precisely as possible):
Create a pod with a nfs provided volume.

Set the values:
```
prometheus-node-exporter:
  extraHostVolumeMounts:
    - name: rootfs
      hostPath: /
      mountPath: /host/rootfs
      readOnly: true
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/rkt/pods/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
    - --collector.mountstats
```

**Anything else we need to know**:
