### ISSUE TITLE
stable/opa mgmt container args improperly formatted when multiple cluster and namespace level API resources are provided

### ISSUE THREAD

**Issue by akniffe1** [helm/charts#11870]
**Is this a request for help?**:
Nope
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
helm 
```Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}```
kube: 
```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}```

**Which chart**:
stable/opa

**What happened**:

When either mgmt.replicate.namespaces or mgmt.replicate.cluster have more than one value:

```
mgmt:
  replicate:
    cluster:
      - "v1/nodes"
    namespace:
      - "v1/pods"
      - "extensions/v1beta1/ingresses"
    path: kubernetes
```
    
The deployment of the mgmt container ends up with malformed args: 

```
Args:
  --opa-url=http://127.0.0.1:8181/v1
  --replicate-path=kubernetes
  --enable-policies=false
  --replicate=v1/pods,extensions/v1beta1/ingresses
  --replicate-cluster=v1/nodes
  ```

  Kube-mgmt can't interpret ```--replicate=v1/pods,extensions/v1beta1/ingresses```
  and gets confused with whatever the second object in that list becomes. kube-mgmt logs the following error:

  ```E0301 19:22:38.250112       1 reflector.go:201] github.com/open-policy-agent/kube-mgmt/pkg/data/generic.go:80: Failed to list *unstructured.Unstructured: invalid resource "v1beta1/ingresses": [may not contain '/']```

The offending lines are: 
https://github.com/helm/charts/blob/master/stable/opa/templates/deployment.yaml#L88
https://github.com/helm/charts/blob/master/stable/opa/templates/deployment.yaml#L91

**What you expected to happen**:

the args for the mgmt container should have been formatted like this:

```Args:
      --opa-url=http://127.0.0.1:8181/v1
      --replicate-path=kubernetes
      --enable-policies=false
      --replicate=v1/pods
      --replicate=extensions/v1beta1/ingresses
      --replicate-cluster=v1/nodes
```

**How to reproduce it** (as minimally and precisely as possible):
in values.yaml update the rbac section as follows: 

```
rbac:
  # If true, create & use RBAC resources
  #
  create: true
  rules:
    cluster:
     - apiGroups:
         - v1
         - extensions
       resources:
         - pods
         - ingresses
       verbs:
         - get
         - list
         - watch
         - describe
```

and:

```
mgmt:
  replicate:
    cluster:
      - "v1/nodes"
    namespace:
      - "v1/pods"
      - "extensions/v1beta1/ingresses"
    path: kubernetes
```

**Anything else we need to know**:
