### ISSUE TITLE
[stable/mongodb-replicaset] support volumeClaimTemplates selector

### ISSUE THREAD

**Issue by lixianyang** [helm/charts#11972]
**Is this a request for help?**:
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

*I use local volume, and create pv with some labels, I want to select pv in volumeClaimTemplates.*

local volume pv:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-mongo-repl-web5
  labels:
    app: test-mongo-repl
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disk01/local-volumes/test-mongo-repl
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - arch-k8s-web5.
```

want statefulset support:
```yaml
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
      spec:
        selector:
          matchLabels:
              app: test-mongo-repl
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "32Gi"
        storageClassName: "local-storage"
```

**Version of Helm and Kubernetes**:
helm: v2.11.0
kubernetes: v1.12.4

**Which chart**:
stable/mongodb-replicaset
