### ISSUE TITLE
stable/drone - Pod crashloop backoff with Gitea provider, no explicit log and missing documentation

### ISSUE THREAD

**Issue by metal3d** [helm/charts#11991]
**Is this a request for help?**:
help (or bug... don't know)
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**:
Helm:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
stable/drone

**What happened**:

Want to use Gitea connection, it seems to be very complicated to make the chart working. I really don't know if I didn't set the right Env Vars, or if something is missing. My Gitea website (launched in Kubernetes) is working great and as a public domain name, cert is Let's Encrypt (via cert-manager)

Drone Pods crashloop backoff saying that the livenessProbe fails. Maybe you can provide better documentation about environment variable to set. At this time, I'm unable to make it working.

**What you expected to happen**:
Entire pods running and server responding.

**How to reproduce it** (as minimally and precisely as possible):
I installed gitea on your Kubernetes cloud, then installed Drone helm chart with several ENV:

```yaml
sourceControl:
    provider: gitea
    gitea: https://git.k8s.XXX.XXX
server:
    host: "drone.k8s.XXX.XXX"
    adminUser: metal3d
    env:
        DRONE_DATABASE_DRIVER: "sqlite3"
        DRONE_DATABASE_DATASOURCE: "/var/lib/drone/drone.sqlite"
        DRONE_GITEA_SERVER: https://git.k8s.XXX.XXX
        DRONE_PROVIDER: gitea
        DRONE_RPC_SECRET: YYYYYY
```

**Anything else we need to know**:

Documentation is not clear about the "sourceControl.secret", how to create it and what to put inside for Gitea. How to get the righe sercret string ? And so on...

Actually, at this time, the documentation is missing to be able to make it working as expected.

BTW: 
I am not trying to criticize the excellent work behind this project. My report speaks only of my experience, and I deeply respect the work done on this repository.

**Comment by mrala** [comment]
@metal3d, were you able to figure out how to use the Drone chart with Gitea? I'm having the same issues, the documentation is unclear on the required env vars and the server component does not start.

**Comment by metal3d** [comment]
At this time, no. I'm unable to use it (and it's sad).

No one seems to help on that helm chart, documentation is poor, and I haven't got the time to spend on the subject at this time.

If someone can help...

**Comment by metal3d** [comment]
OK - it seems to work now.
Updated version, and it's now pretty simple to install and use drone.

My values are:
```yml
# at this time, some problems to resolve dind access to my private registry
# so I use insecure registry, but "docker" is not ok in agent for now
dind:
  args: '["--insecure-registry="10.0.0.0/8"]'
sourceControl:
  provider: gitea
  gitea:
    server: https://git.WWWWWW

# optional
service:
  exportGRPC: true

ingress:
  enabled: true

  annotations:
    # I'm using nginx-controller, I set up SSL with cert-manager
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'

  # change it to your need if you want https
  hosts:
    - drone.WWWWWW

  tls:
    - secretName: drone-ls-crt
      hosts:
        - drone.WWWWWW
```
