### ISSUE TITLE
[stable/fluent-bit] systemd enabled in values, does not come in configmap

### ISSUE THREAD

**Issue by Vince-Cercury** [helm/charts#12010]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm v2.11.0
Kubernetes v1.11.3

**Which chart**:
fluent-bit

**What happened**:
systemd settings does not appear in configmap even though it's enabled in values.yaml

**What you expected to happen**:
I should see an entry in configmap for systemd:

```
   [INPUT]
        Name            systemd
        Tag             host.*
...
```

But this is missing from configmap

**How to reproduce it** (as minimally and precisely as possible):
Enable systemd in values.yaml 
```  
  tail:
    memBufLimit: 6MB
    parser: docker
    path: /var/log/containers/*.log
systemd:
    enabled: true
    filters:
      systemdUnit:
        - docker.service
        - kubelet.service
        - node-problem-detector.service
    maxEntries: 1000
    readFromTail: true
    tag: host.*
```

In the above I set memBufLimit to 6MB just to be sure changes in values.yaml get picked up.

Install
` helm install --namespace splunk-fluent-bit --name fluent-bit -f splunk-fluent-bit-values.yaml stable/fluent-bit`

`kubectl -n splunk-fluent-bit get configmap fluent-bit-fluent-bit-config -o yaml`

The content of the configmap, fluent-bit-input.conf is:
```
  fluent-bit-input.conf: "[INPUT]\n    Name             tail\n    Path             /var/log/containers/*.log\n
    \   Parser           docker\n    Tag              kube.*\n    Refresh_Interval
    5\n    Mem_Buf_Limit    6MB\n    Skip_Long_Lines  On\n    "
```

As you can see there is nothing for systemd
