### ISSUE TITLE
lwander must be an org member or not an approver

### ISSUE THREAD

**Issue by fejta** [helm/charts#12033]
This user is in the OWNERS file:

https://github.com/helm/charts/blob/38706b310cb7a4225f8f5e5c486828b31c0dbc42/stable/spinnaker/OWNERS#L3

https://github.com/helm/charts/blob/38706b310cb7a4225f8f5e5c486828b31c0dbc42/stable/spinnaker/OWNERS#L8

However github cannot assign issues/PRs this user as they are neither a helm/charts repo collaborator nor a helm org member.

Please correct this by either removing the user from the OWNERS file or adding them as a repo collaborator or org member

/assign @viglesiasce @dwardu89 @paulczar 

```yaml
jsonPayload: {
  author:  "rverma-nikiai"   
  component:  "hook"   
  error:  "could not request a PR review from the following user(s): lwander."   
  event-GUID:  "34f7a670-4221-11e9-8da0-bafd00d7c844"   
  event-type:  "pull_request"   
  level:  "error"   
  msg:  "Error handling PullRequestEvent."   
  org:  "helm"   
  plugin:  "blunderbuss"   
  pr:  12032   
  repo:  "charts"   
  url:  "https://github.com/helm/charts/pull/12032"   
 }
```

ref #12032
