### ISSUE TITLE
InfluxDB Chart issue with

### ISSUE THREAD

**Issue by srflaxu40** [helm/charts#12064]
InfluxDB chart does not respect `INFLUXDB_DB` env var unless I change monitoring attribute db to that db name.  

NOTE - I used the chart out of master branch, and latest tag.
```
image:
  repo: "influxdb"
  tag: "latest"
  pullPolicy: IfNotPresent
```

Ex:
```
## The InfluxDB image uses several environment variables to automatically
## configure certain parts of the server.
## Ref: https://hub.docker.com/_/influxdb/
env:
  - name: INFLUXDB_DB
    value: default
```

When I update this:
```
  monitor:
    store_enabled: true
    store_database: default
    store_interval: 10s
```

It is then created.

Does not create `default` although the *environment variable exists*.  Instead *_internal* exists.  I went into the monitoring section and  changed the default value of *_internal* to *default*, and then the database was created.
