### ISSUE TITLE
[stable/nginx-ingress] vts-status page not working

### ISSUE THREAD

**Issue by 2PacIsAlive** [helm/charts#12103]
**Is this a request for help?**:
yes

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
```
dependencies:
  - name: nginx-ingress
    version: 1.3.1
    repository: https://kubernetes-charts.storage.googleapis.com
```

**What happened**:
I am not able to see the expected vts status page at http://localhost:18080/nginx_status, a much more simple version is provided, that only shows:
```
Active connections: 3 
server accepts handled requests
 3301 3301 3870 
Reading: 0 Writing: 1 Waiting: 2 
```

**What you expected to happen**:
I expected to see the full html output detailed at https://github.com/vozlt/nginx-module-vts. 
![image](https://user-images.githubusercontent.com/6954424/54163292-227f8180-441e-11e9-9585-a7819bb9be79.png)

**How to reproduce it** (as minimally and precisely as possible):
Install the stable/nginx-ingress chart with the following config:
```
nginx-ingress:
  controller:
    service:
      type: NodePort

      nodePorts:
        http: 30972

    stats:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  defaultBackend:
    enabled: false
```

**Anything else we need to know**:
I am trying to get response code level metrics, which seem to be enabled through the vts stats. It seems like something is not getting set up properly, as the
```
vhost_traffic_status_display;
vhost_traffic_status_display_format html;
```
settings are not configured in the `/etc/nginx/nginx.conf`, even though the `controller.stats.enabled` flag is true, which is described in the docs as the way to enable the vts status page. 

If further steps are required to get everything set up properly, it would be really helpful if they were documented here https://github.com/helm/charts/tree/master/stable/nginx-ingress#prometheus-metrics
