### ISSUE TITLE
Docker can't push to insecure

### ISSUE THREAD

**Issue by mattthehearn** [helm/charts#12131]
**Is this a request for help?**: Yes.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 1.13.1

**Which chart**: docker-registry

**What happened**: I was able to deploy the chart, however it seems to run in insecure mode, and when I try to push to it, I get:

```
╰ 09:33:58 $ docker push registry.hearn.local/nginx
The push refers to repository [registry.hearn.local/nginx]
Get https://registry.hearn.local/v2/: x509: certificate has expired or is not yet valid
```

Docker clearly wants to push to an HTTPS service.  I do see a TLS option in the "ingress" section of values.yaml, but ingress is disabled, and I'm hoping to just use NodePort (I have an external HAProxy loadbalancer I can use to direct http/https traffic to the nodeport).

**What you expected to happen**:

I expect to be able to push and pull to my registry.

**How to reproduce it** (as minimally and precisely as possible):
Edit values.yaml thusly:
```
# Default values for docker-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy:
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

podAnnotations: {}

image:
  repository: registry
  tag: 2.6.2
  pullPolicy: IfNotPresent
# imagePullSecrets:
    # - name: docker
service:
  name: registry
  type: NodePort
  # clusterIP:
  port: 5000
  nodePort: 30180
  annotations: {}
  # foo.io/bar: "true"
ingress:
  enabled: false
  path: /
  # Used to create an Ingress record.
  hosts:
    - registry.hearn.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: registry-cert
      hosts:
        - registry.hearn.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
persistence:
  accessMode: 'ReadWriteOnce'
  enabled: false
  size: 10Gi
  storageClass: "gluster-heketi"

# set the type of filesystem to use: filesystem, s3
storage: filesystem

# Set this to name of secret for tls certs
# tlsSecretName: registry.docker.example.com
secrets:
  haSharedSecret: ""
  htpasswd: ""
# Secrets for Azure
#   azure:
#     accountName: ""
#     accountKey: ""
#     container: ""
# Secrets for S3 access and secret keys
#   s3:
#     accessKey: ""
#     secretKey: ""
# Secrets for Swift username and password
#   swift:
#     username: ""
#     password: ""

# Options for s3 storage type:
# s3:
#  region: us-east-1
#  regionEndpoint: s3.us-east-1.amazonaws.com
#  bucket: my-bucket
#  encrypt: false
#  secure: true

# Options for swift storage type:
# swift:
#  authurl: http://swift.example.com/
#  container: my-container

configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3

securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 1000

priorityClassName: ""

nodeSelector: {}

tolerations: []
```

Run helm install .

Attempt to push to the new registry.

**Anything else we need to know**:
It may or may not be related, but it doesn't seem like it created a PersistentVolumeClaim either.  I can certainly do that manually, but the persistence config seems to indicate that it wants to do so itself (values.yaml doesn't offer a field for a pre-made PVC name).
