### ISSUE TITLE
[incubator/patroni] doesn't work if deployment name isn't "patroni"

### ISSUE THREAD

**Issue by thomasboni** [helm/charts#12153]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
* Helm client & server: "v2.12.3"(GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e")
* Kubernetes: 1.12.6-0
* Spilo image tag: 1.5-p5

**Which chart**: incubator/patroni

**What happened**:

When installing the chart with a release name which isn't `patroni`, patroni doesn't boostrap the cluster because it can't retrieve the list of pods due to a bad label selector.

Pods are launched with `app: {{ template "patroni.name" . }}` label and patroni try to retrive them with selector `app=patroni.fullname` retrieved from `SCOPE` environement variable.

If you install the chart with release name `patroni` you don't have any issues because `patroni.name` == `patroni.fullname`. But if you launch the chart with a different name, it doesn't work.

Example of first pod logs after a `helm install` with name `myapp-postgres` in namespace `myapp-prod`:

```
2019-03-12 17:13:40,887 INFO: Could not take out TTL lock                                                                                                                                                            
2019-03-12 17:13:40,963 INFO: following new leader after trying and failing to obtain lock                                               
2019-03-12 17:13:50,973 INFO: Could not take out TTL lock                                        
2019-03-12 17:13:51,107 INFO: following new leader after trying and failing to obtain lock 
2019-03-12 17:13:50,973 INFO: Could not take out TTL lock                                        
2019-03-12 17:13:51,107 INFO: following new leader after trying and failing to obtain lock 
...
```

**What you expected to happen**:

It should work with any release name

**How to reproduce it** (as minimally and precisely as possible):

Install the chart in a namespace with the name `myapp-postgres`. Cluster never bootstrap. 

I install the chart with the variable image.tag=1.5-p5. But the bug is present with version of `values.yaml` (1.4-p16) too.

**Anything else we need to know**:

I see two solutions:
* launch pods with label `app=patroni.name` instead of fullname
* set the `SCOPE` environment variable value to `patroni.name` instead of `patroni.fullname`

Part of templates concerned:
```
apiVersion: apps/v1beta1
kind: StatefulSet
...
  template:
    metadata:
      name: {{ template "patroni.fullname" . }}
      labels:
        app: {{ template "patroni.name" . }}
        release: {{ .Release.Name }}
    spec:
...
        - name: SCOPE
          value: {{ template "patroni.fullname" . }}
```

I will make a PR with the second option. It seems to be the option with less impact but I don't have enough knowledge on patroni/spilo to anticipate all possible side-effects related to this SCOPE variable.
