### ISSUE TITLE
[stable/kibana,metricbeat,filebeat] default config is merged to user defined config

### ISSUE THREAD

**Issue by kimxogus** [helm/charts#12199]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
```plain
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Which chart**: `stable/filebeat` `stable/kibana` `stable/metricbeat`

**What happened**: As default `kibana.yml`, `metricbeat.yml` and `filebeat.yml` config values are defined in yaml, those values are automatically merged to user defined configs.
As a result, my `kibana.yml` become mixed as below
```yaml
elasticsearch:
  hosts:
  - user-defined-es-host
elasticsearch.url: http://elasticsearch:9200
server:
  host: "0"
  rewriteBasePath: true
server.host: "0"
server.name: kibana
xpack:
  canvas.enabled: false
  infra.enabled: false
  logstash.enabled: false
  monitoring:
    enabled: true
    kibana:
      collection:
        enabled: true
```

**What you expected to happen**: Only user defined config values are set in config file. Default config values needs to be empty

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by puetzp** [comment]
I am experiencing the same issue. When I define logstash output for metricbeat in values.yaml file like so:
```
...
  config:
    metricbeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    processors:
    - add_cloud_metadata:
    output.logstash:
      hosts: ["<snip>:<snip>"]
  modules:
    system:
      enabled: true
      config:
...
```
the decoded metricbeat.yml include both the custom and default config:
```
    metricbeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    output.file:
      filename: metricbeat
      number_of_files: 5
      path: /usr/share/metricbeat/data
      rotate_every_kb: 10000
    output.logstash:
      hosts:
      - <snip>:<snip>
    processors:
    - add_cloud_metadata: null
```
