### ISSUE TITLE
[stable/concourse] Ensure that values that should have defaults from the Concourse binary don't end up using empty environment variables

### ISSUE THREAD

**Issue by cirocosta** [helm/charts#12221]
Recently, https://github.com/helm/charts/issues/12053 uncovered the fact that some of the configuration blocks that we have (especially for auth providers) have their environment variables being configured without a check regarding the emptiness of the value like we have for other variables.

For instance, in the case of Vault, we only check if `concourse.web.auth.vault.enabled` evaluates to `true` and then move forward assuming that the variables are always set:

https://github.com/helm/charts/blob/121a1a88197a56adb40aed1faabbec0f06a2aa50/stable/concourse/templates/web-deployment.yaml#L352-L357

This ends up making the variables that are not set being reported as empty environment variables:

```yaml
            - name: CONCOURSE_VAULT_URL
              value: 
            - name: CONCOURSE_VAULT_PATH_PREFIX
              value: 
            - name: CONCOURSE_VAULT_AUTH_BACKEND
              value: ""
```

The problem of that is that `concourse` is then not able to apply its default configurations:

```sh
concourse web --help 2>&1 | ag vault-path-prefix
          --vault-path-prefix=       Path under which to namespace credential lookup. 
                                     (default: /concourse) [$CONCOURSE_VAULT_PATH_PREFIX]
```

As a result, folks who have previously not configured values for those blocks end up possibly having a broken configuration.

This got broken in the PR I submitted a while ago (https://github.com/helm/charts/pull/11296) when moving from defaults in the Chart to defaults from the `concourse` binary.

---

As acceptance criteria for this, we should ensure that:

- variables that previously had default values are not being set as empty values (special attention to blocks with `enabled`).

Thanks!
