### ISSUE TITLE
Need to be able to provide serviceName and servicePort for Ingress Host Rules

### ISSUE THREAD

**Issue by mikesigs** [helm/charts#12261]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:
Helm Client + Server: v2.12.0-rc.2
Kubernetes Client: v1.10.3
Kubernetes Server: v1.11.8-eks-7c34c0

**Which chart**:
chartmuseum

**What happened**:
Ingress rules use a hard-coded `serviceName` and `servicePort` for all rules. This is fine as a default behavior, but should be overridable by the user.

I am using the aws-alb-ingress-controller which allows you to configure ingress annotations for custom actions to be created on the ALB. One very common use case for these custom actions is to create an SSL redirect. This is currently not possible to achieve with the chartmuseum chart because it requires defining an Ingress Host Rule like so:

```yaml
- host: example.com
  http:
    paths:
    - path: /*
      backend:
        serviceName: ssl-redirect
        servicePort: use-annotation
```

The name serviceName `ssl-redirect` is used to match an alb annotation like this:

```yaml
alb.ingress.kubernetes.io/actions.ssl-redirect: {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
```

**What you expected to happen**:
The user should be able to define host rules like this:
```yaml
hosts:
  - name: example.com
    path: /*
    serviceName: ssl-redirect
    servicePort: use-annotation
  - name: example.com
    path: /*
```
The first rule should use `.serviceName` and `.servicePort` supplied in the rule. The second rule should use the default values, as in the current behavior.

**How to reproduce it** (as minimally and precisely as possible):
Try to define a rule with serviceName and servicePort properties. It doesn't work (yet :))

**Anything else we need to know**:
Here is a full sample of using the AWS ALB Ingress Controller to do SSL redirection.
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/

TIA
