### ISSUE TITLE
[stable/metricbeat] How to setup autodiscover?

### ISSUE THREAD

**Issue by Jeeppler** [helm/charts#12289]
**This is a HELP/FEATURE REQUEST**

**Version of Helm and Kubernetes**:

- Kubernetes 1.11 (AWS EKS)
- Helm v2.12.3

**Which chart**:

stable/metricbeat

**Description**:

I tried to configure the [autodiscover](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html) feature in Metricbeat. First I am not sure where to put the configuration on the `daemonset` or the `deployment`. I tried both without any success. 

The application I tried to deploy is a container with Nginx and one single static `index.html` file. The only special part about the configuration is the `/nginx_status` part. The Nginx status page uses the [ngx_http_stub_status_module](https://nginx.org/en/docs/http/ngx_http_stub_status_module.html). This is needed by Metricbeat to collect metrics from Nginx.

I added this snippet to the Metricbeat chart `values.yaml`:

```
daemonset:
  config:
    # Autodiscovery
    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          include_annotations: "nginx"
          templates:
            - condition:
                contains:
                  kubernetes.annotations.nginx: "true"
              config:
                - module: nginx
                  metricsets:
                    - stubstatus
                  enabled: true
                  period: 10s

                  # Nginx hosts
                  hosts: ["http://{data.host}:{data.port}"]

                  # Path to server status. Default server-status
                  server_status_path: "nginx_status"
```

Here is the corresponding Kubernetes `simple-container.yaml` definition:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-container
  labels:
    app: simple-container

spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-container
  template:
    metadata:
      labels:
        app: simple-container
      annotations:
        nginx: "true"

    spec:
      containers:
      - name: simple-container
        image: <registry>/simple-container:latest
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: simple-container
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "120"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

spec:
  selector:
    app: simple-container
  ports:
  - name: port-80
    protocol: TCP
    port: 80
    targetPort: 80

  type: LoadBalancer
```

The `nginx` config:

```
user                            www-data;
worker_processes                1;

error_log                       /var/log/nginx/error.log warn;
pid                             /var/run/nginx.pid;

events {
    worker_connections          1024;
}

http {
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;
    sendfile                    on;
    access_log                  /var/log/nginx/access.log;
    keepalive_timeout           3000;
    server {
        listen                  80;
        root                    /www;
        index                   index.html index.htm;
        server_name             localhost;
        client_max_body_size    32m;
        error_page              500 502 503 504  /50x.html;
        location = /50x.html {
              root              /var/lib/nginx/html;
        }

        location /nginx_status {

          # Turn on nginx status page
          stub_status on;

          # Do not log access queries for status page
          access_log   off;

          # Only allow access from 127.0.0.1
          # allow 127.0.0.1;
          allow 0.0.0.0;

          # Deny the rest of the connections
          # deny all;
        }
    }
}

daemon off;

```

**Comment by Jeeppler** [comment]
MetricBeat autodiscover watches pods for start and stop events. It does that by connecting to the [Kubelet (node-agent)](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) running on every node. To be able to watch for those events, MetricBeat has to run on every node. Therefore autodiscover has to be configured in the `daemonset` configuration.

```
daemonset:
    # Autodiscovery
    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          include_annotations: ["metricbeat.nginx"]
          in_cluster: true
          host: "${NODE_NAME}"
          templates:
            - condition:
                contains:
                  kubernetes.annotations.metricbeat.nginx: "true"
              config:
                - module: nginx
                  metricsets:
                    - stubstatus
                  enabled: true
                  period: 10s

                  # Nginx hosts
                  hosts: ["http://${data.host}:80"]

                  # Path to server status. Default server-status
                  server_status_path: "nginx_status"
```

Two lines in the configuration are important. 
First, you have to set the `host` parameter. The reason is the [`daemonset.yaml`](https://github.com/helm/charts/blob/master/stable/metricbeat/templates/daemonset.yaml) is set to use [`hostNetwork: true`](https://github.com/helm/charts/blob/master/stable/metricbeat/templates/daemonset.yaml#L119):

```
serviceAccountName: {{ template "metricbeat.serviceAccountName" . }}
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```

Second, ports are not getting exposed. Therefore it is required to set the port of the service. The `data.host` value comes from the [Kubernetes autodiscover provider](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html#_kubernetes).

Furthermore, the `kubernetes.annotations` are injected by the Kubernetes autodiscover provider and do not exist in ElasticSearch. The values are only accessible to the Kuberetes autodiscover provider and are not send or index in ElasticSearch.

Here is the deployment configuration of the `simple-container`. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-container
  labels:
    app: simple-container

spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-container
  template:
    metadata:
      labels:
        app: simple-container
      annotations:
        metricbeat.nginx: "true"

    spec:
      containers:
      - name: simple-container
        image: <my-image>:latest
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: simple-container
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "120"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

spec:
  selector:
    app: simple-container
  ports:
  - name: port-80
    protocol: TCP
    port: 80
    targetPort: 80

  type: LoadBalancer
```

and here is the `nginx` config file:

```
user                            www-data;
worker_processes                1;

error_log                       /var/log/nginx/error.log warn;
pid                             /var/run/nginx.pid;

events {
    worker_connections          1024;
}

http {
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;
    sendfile                    on;
    access_log                  /var/log/nginx/access.log;
    keepalive_timeout           3000;
    server {
        listen                  80;
        root                    /www;
        index                   index.html index.htm;
        server_name             localhost;
        client_max_body_size    32m;
        error_page              500 502 503 504  /50x.html;
        location = /50x.html {
              root              /var/lib/nginx/html;
        }

        location /nginx_status {

          # Turn on nginx status page
          stub_status on;

          # Do not log access queries for status page
          access_log   off;

          # Allow access from everywhere
          allow 0.0.0.0;
        }
    }
}

daemon off;
```

MetricBeat `autodiscover` will start the Nginx collection runner. The runner will connect to `/nginx_status` via HTTP, collect the metrics from the HTTP endpoint and send it to ElasticSearch. Make sure that the Nginx collection runner can access the HTTP `/nginx_status` endpoint. Otherwise you will see several errors.

For security reasons limit and protect the HTTP `/nginx_status` endpoint. For example, create a firewall rule in your setup which blogs any access from outside the cluster or limit the `allow 0.0.0.0;` to the network addresses of your Kubernetes cluster.
