### ISSUE TITLE
[stable/redis] Change "master" to "primary" and "slave" to "replica"

### ISSUE THREAD

**Issue by maflaven** [helm/charts#12290]
**Is this a request for help?**:

No.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

_Feature Request_
"master" and "slave" are antiquated terms. They should be replaced with something like "primary" and "replica". This should either be the hardcoded service, deployment, etc. names, or they should be overridable by values.yaml.

**Comment by juan131** [comment]
Hi @maflaven 

I agree that the current naming is antiquated. However, I'm afraid that renaming the different K8s resources (deployment, services, etc.) will break backwards compatibility and it won't be possible to upgrade from previous versions of the chart.

That's why I think we should keep the current naming to avoid this "upgradability issues". Maybe it's the best of bad options.

**Comment by maflaven** [comment]
@juan131 that's fair. Though configurability would be appreciated for recent installers like me. Like the default could be master/slave with the option to pass in replacements.

**Comment by juan131** [comment]
I'm not sure if I understood you correctly @maflaven. Do you mean to have some kind of flag to indicate whether to use the current naming (master-slave) or use an updated naming (primary-replica)?

**Comment by maflaven** [comment]
I was thinking of using values.yaml with an `alias` nested in both `master` and `slave`.
```yaml
master:
  ## [Optional] The alias for related deployment and service manifests (e.g. release-name-alias).
  ## The default alias is "master" (e.g. release-name-master).
  alias: primary

slave:
  ## Similar comment to above ^^
  alias: replica
```
