### ISSUE TITLE
Question - add secret to env for admin user/password

### ISSUE THREAD

**Issue by fritchie** [helm/charts#12317]
General question:

Would it be possible to have the admin username/password stored in a secret that is loaded in the grafana container env, ie:

```
env:
- name: GF_SECURITY_ADMIN_USER
  valueFrom:
    secretKeyRef:
      key: admin-user
      name: grafana-admin
- name: GF_SECURITY_ADMIN_PASSWORD
  valueFrom:
    secretKeyRef:
      key: admin-password
      name: grafana-admin
```
