### ISSUE TITLE
Does not scrape any data from cadvisor

### ISSUE THREAD

**Issue by vovkanaz** [helm/charts#12341]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Seems like a bug

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}

Kubernetes 1.11

**Which chart**:
prometheus-operator

**What happened**:
There are no cadvisor endpoints

![image](https://user-images.githubusercontent.com/6215653/54533930-fae76680-4993-11e9-81fb-f1fd70e1a422.png)

**What you expected to happen**:
Scrape metrics from a pods

**How to reproduce it** (as minimally and precisely as possible):
helm install --name prom --namespace monitoring --set grafana.sidecar.datasources.enable=true --set grafana.sidecar.datasources.label=grafana_datasource  --set grafana.sidecar.dashboards.enabled=true --set grafana.sidecar.dashboards.label=grafana_dashboard stable/prometheus-operator
**Anything else we need to know**:

**Comment by scjudd** [comment]
Running into this with an EKS cluster, as well.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by vovkanaz** [comment]
> Running into this with an EKS cluster, as well.
> 
> ```
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
> ```
yes, we are also have this issue in  AWS EKS

**Comment by vsliouniaev** [comment]
Try setting this: `kubelet.serviceMonitor.https=true`

**Comment by vovkanaz** [comment]
Thanks a lot!!! Now all working like a charm!

**Comment by vsliouniaev** [comment]
[There's a PR open to fix the defaults - they are using very old selectors.](https://github.com/helm/charts/pull/12292) For now, you can try this:
```yaml
#prometheus:
#  prometheusSpec:
#    secrets: [etcd-certs]
kubelet:
  enabled: true
  serviceMonitor:
    https: true
kubeControllerManager:
  service:
    selector:
      k8s-app: null
      component: kube-controller-manager
coreDns:
  service:
    selector:
      k8s-app: kube-dns
kubeScheduler:
  service:
    selector:
      k8s-app: null
      component: kube-scheduler
kubeEtcd:
#  serviceMonitor:
#    scheme: https
#    insecureSkipVerify: true
#    caFile:   /etc/prometheus/secrets/etcd-certs/ca.crt
#    certFile: /etc/prometheus/secrets/etcd-certs/client.crt
#    keyFile:  /etc/prometheus/secrets/etcd-certs/client.key
  service:
    port: 2379
    targetPort: 2379
    selector:
      k8s-app: null
      component: etcd
```

The most common approach to scraping etcd will require you to provision a secret with client credentials to get access to its pods. If you have alternative configurations for where you're running it, that may require some other tweaks

**Comment by vsliouniaev** [comment]
This is now permanently fixed
/close

**Comment by vovkanaz** [comment]
Hi guys, another kind of problem, and we have not idea how to fix this, We are using AWS EKS, and we noticed that no such kind of metrics in the Prometheus, that's why grafana can't get data points:
![image](https://user-images.githubusercontent.com/6215653/56346692-673fca80-61cb-11e9-83de-026e5f19c59f.png)
------
![image](https://user-images.githubusercontent.com/6215653/56346777-8b9ba700-61cb-11e9-92b7-fa60622772f8.png)
Hope you can help us. Thanks in advance!

**Comment by vsliouniaev** [comment]
Please open a separate issue for a separate problem.
You are most likely not scraping your coredns pods, or not using coredns

**Comment by Nuru** [comment]
I would not say this issue is really fixed, more like shifted around. For a cluster created by `kops 1.11` and (probably some other ways), `kublet` is not configured to authenticate a bearer token, and the HTTPS endpoint requires authentication, so Prometheus cannot access it because even if it presents a valid token, `kubelet` will not recognize it. The HTTP endpoint does not require authentication (it is protected by network access rules), so Prometheus can access `kubelet` that way. See https://github.com/coreos/prometheus-operator/issues/926

So for the `kops` cluster, you need
```
      kubelet:
        serviceMonitor:
          https: false
      kubeControllerManager:
        service:
          selector:
            k8s-app: "kube-controller-manager"
            component: null
      kubeScheduler:
        service:
          selector:
            k8s-app: "kube-scheduler"
            component: null
```
Note that monitoring `etcd` is a [whole other problem](https://github.com/kubernetes/kops/issues/4975#issuecomment-381055946)
