### ISSUE TITLE
[stable/prometheus-operator] Service monitors namespaceSelector does not seem to work.

### ISSUE THREAD

**Issue by boxcee** [helm/charts#12394]
**Is this a request for help?**:
Yes

**Version of Helm and Kubernetes**:
kubernetes client version: v1.12.3
kubernetes server version: v1.12.3
helm client version: v2.12.2+g7d2b0c7

**Which chart**:
stable/prometheus-operator:4.3.3

**What happened**:
When adding
```
- endpoints:
  - interval: 30s
    path: /_prometheus/metrics
    port: http
  name: kube-prometheus-elasticsearch
  selector:
    matchLabels:
      monitoring: elasticsearch
   namespaceSelector:
     matchNames:
     - NAMESPACE
```
to the `additionalServiceMonitors` prometheus will create scrape jobs for not only `NAMESPACE` but also other namespaces which match the selector.

**What you expected to happen**:
In the prometheus config file I only expect scrape_configs for `NAMESPACE` but get scrape_configs for all namespaces which have a service that matches the selector label.

**How to reproduce it** (as minimally and precisely as possible):
Merge this to `values.yaml` and replace `NAMESPACE`.
```
prometheus:
  additionalServiceMonitors:
    - endpoints:
        - interval: 15s
          path: /metrics
          port: promjmx
      name: kube-prometheus-cp-kafka
      selector:
        matchLabels:
          app: cp-kafka
      namespaceSelector:
        matchNames:
          - NAMESPACE
```
