### ISSUE TITLE
[stable/logstash] set environment variables from kubernetes secrets

### ISSUE THREAD

**Issue by ChrisSchreiber** [helm/charts#12446]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** Feature Request

**Version of Helm and Kubernetes**: 1.11

**Which chart**: stable/logstash

I have secrets for passwords and tokens stored as secrets in Kuberntets which I need to reference in my logstash pipeline. I would like to be able to set these as environment variables in my container as outlined here https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables.

Example of command to create secret
```
kubectl create secret generic elasticsearch-secrets --from-literal=ELASTICSEARCH_USER=admin --from-literal=ELASTICSEARCH_PASSWORD=p@ssw0rd
```

Example expected container spec for logstash stateful set
```
spec:
  containers:
  - name: logstash
    image: "docker.elastic.co/logstash/logstash-oss:6.6.1"
    ....
    env:
      - name: ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: ELASTICSEARCH_USER
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-secrets
            key: ELASTICSEARCH_PASSWORD
```

Example logstash pipeline using created environment variables
```
output {
   elasticseardch {
     user: "${ELASTICSEARCH_USER}"
     password: "${ELASTICSEARCH_PASSWORD}"
```

**Comment by iahmad-khan** [comment]
Hi,

Is there any solution posted? I need to do the same.

I have the password stored in a secret created by ES operator and I need to access that in logstash deployment

**Comment by jgato** [comment]
The same here, how to solve that?

**Comment by teebu** [comment]
This works: 

```
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username

secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/elasticsearch/config/certs
```
