### ISSUE TITLE
[stable/lamp] ReadString: expects " or n, but found 3

### ISSUE THREAD

**Issue by himpierre** [helm/charts#12479]
**Is this a request for help?**: Yes

---

**Version of Helm and Kubernetes**: v1.13.4

**Which chart**: stable/lamp

**What happened**:

As soon as I try to activate the git part i get:

`
Error: release privatebin failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 3, error found in #10 byte of ...|,"value":30},{"name"|..., bigger context ...|e":"FETCH_HEAD"},{"name":"GIT_SYNC_WAIT","value":30},{"name":"GIT_SYNC_DEST","value":"/git"}],"image|...
`

This is the git part:

```
git:
  ## git.enabled Enables Git service
  enabled: true

  ## git.repoURL Git Repository URL
  repoURL: https://github.com/PrivateBin/PrivateBin

  ## git.branch Repository branch to sync
  branch: master

  ## git.revision Revision to sync
  revision: FETCH_HEAD

  ## git.wait Time between Git syncs
  wait: 30

  ## git.resources resource requests/limits
  #resources: true
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi
```

As you can see, i'm trying to get the privatebin repository. Am i doing it wrong?

**What you expected to happen**:

privatebin repository gets checked out to /var/www/html

thanks and cheers
