### ISSUE TITLE
[stable/unifi] Unable to install with ingress enabled

### ISSUE THREAD

**Issue by thiemok** [helm/charts#12481]
**Is this a request for help?**:
Maybe, otherwise its a bug
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1+unreleased", GitCommit:"dd4bf49f3214bbcfcd7fba8618f930f4808b1285", GitTreeState:"dirty"}
```
Kubernetes:
v1.13.4-k3s.1

**Which chart**:
stable/unifi

**What happened**:
Install with enabled ingress fails manifest rendering.
My values file looks like this:
```yaml
image:
  repository: thiemok/unifi
  tag: latest
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rewrite-target: "/"
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
  path: /unifi
  hosts:
    - unifi.example.com
timezone: Europe/Berlin
```
I ran this command to test the install:
`helm install -f config.yaml stable/unifi --dry-run --debug`
And it fails with the following error:
`Error: render error in "unifi/templates/ingress.yaml": template: unifi/templates/ingress.yaml:35:28: executing "unifi/templates/ingress.yaml" at <.Values.unifiedService.enabled>: can't evaluate field Values in type interface {}`

**What you expected to happen**:
The template is rendered successfully

**How to reproduce it** (as minimally and precisely as possible):
Try to install stable/unifi with ingress enabled
`helm install --set ingress.enabled=true stable/unifi --dry-run --debug`

**Anything else we need to know**:
nope
