### ISSUE TITLE
[stable/rabbitmq-ha] Error:release ha failed: Service in version "v1" cannot be handled as a Service.

### ISSUE THREAD

**Issue by Aisuko** [helm/charts#12557]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

  Bug Report

**Version of Helm and Kubernetes**:

`helm version`

```
➜  rabbitmq-ha git:(mq-ha) ✗ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

`Kubernetes version`

```
➜  rabbitmq-ha git:(mq-ha) ✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/rabbitmq-ha](https://github.com/helm/charts/tree/master/stable/rabbitmq-ha)

**What happened**:
When I deploy the chart, I got an error 
```
➜  rabbitmq-ha git:(mq-ha) helm install --namespace rabbitmq -n ha .            
Error: release ha failed: Service in version "v1" cannot be handled as a Service: v1.Service: Spec: v1.ServiceSpec: Ports: []v1.ServicePort: v1.ServicePort: NodePort: readUint32: unexpected character: �, parsing 254 ...odePort":n... at {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"rabbitmq-ha","chart":"rabbitmq-ha-1.23.0","heritage":"Tiller","release":"ha"},"name":"ha-rabbitmq-ha","namespace":"rabbitmq"},"spec":{"clusterIP":"None","ports":[{"name":"http","nodePort":null,"port":15672,"protocol":"TCP","targetPort":"http"},{"name":"amqp","nodePort":null,"port":5672,"protocol":"TCP","targetPort":"amqp"},{"name":"epmd","nodePort":null,"port":4369,"protocol":"TCP","targetPort":"epmd"}],"selector":{"app":"rabbitmq-ha","release":"ha"},"type":"ClusterIP"}}
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
I have nothing change the chart and just to deploy it .

**Anything else we need to know**:

And my solution is to remove the Services Spec.ports.nodeport. Because of kubernetes can automation and random specify node port for services when service type=="Nodeport". So, why there need to set a node port for every service manually?

**Comment by steven-sheehy** [comment]
> So, why there need to set a node port for every service manually?

Random is fine for humans, but it can't be used by a tool that expects a well known port.

We probably need to check if service type is node port and port is not null.

@jasquat Since you added the nodePort feature in PR #11580, would you be able to take a look?

**Comment by jasquat** [comment]
I cannot replicate this. Running an equivalent command with default configs deploys rabbitmq-ha fine. Our kuberenetes server version is 1.12.5 instead of 1.9.0 and our helm version is 2.12.1 instead of 2.13.0. Could they have changed something in one of the versions?

@Aisuko if you put conditionals around the nodePort keys in templates/service.yaml, does that fix your issue? Something like:
```
diff --git stable/rabbitmq-ha/templates/service.yaml stable/rabbitmq-ha/templates/service.yaml
index 2ff343a3e..66a498818 100644
--- stable/rabbitmq-ha/templates/service.yaml
+++ stable/rabbitmq-ha/templates/service.yaml
@@ -39,17 +39,23 @@ spec:
     - name: http
       protocol: TCP
       port: {{ .Values.rabbitmqManagerPort }}
+      {{- if and (eq .Values.service.type "NodePort") .Values.service.managerNodePort }}
       nodePort: {{ .Values.service.managerNodePort }}
+      {{- end }}
       targetPort: http
     - name: amqp
       protocol: TCP
       port: {{ .Values.rabbitmqNodePort }}
+      {{- if and (eq .Values.service.type "NodePort") .Values.service.amqpNodePort }}
       nodePort: {{ .Values.service.amqpNodePort }}
+      {{- end }}
       targetPort: amqp
     - name: epmd
       protocol: TCP
       port: {{ .Values.rabbitmqEpmdPort }}
+      {{- if and (eq .Values.service.type "NodePort") .Values.service.epmdNodePort }}
       nodePort: {{ .Values.service.epmdNodePort }}
+      {{- end }}
       targetPort: epmd
     {{- if .Values.rabbitmqSTOMPPlugin.enabled }}
     - name: stomp-tcp
```

**Comment by Aisuko** [comment]
@steven-sheehy Thanks for your reply. There I have another question, Sometimes we need to create service for every pod so we can not set `nodeport ` manually, so how it can be  used by a tool? Like that:

```
{{- $num := int .Values.replicaCount }}
{{- $root := . }}
{{- range $i := until $num }}
---
apiVersion: v1
kind: Service
metadata:
{{- if or $root.Values.service.annotations (and $root.Values.prometheus.exporter.enabled (not $root.Values.prometheus.operator.enabled)) }}
  annotations:
{{- end }}
{{- if $root.Values.service.annotations }}
{{ toYaml $root.Values.service.annotations | indent 4 }}
{{- end }}
{{- if and $root.Values.prometheus.exporter.enabled (not $root.Values.prometheus.operator.enabled) }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ $root.Values.prometheus.exporter.port | quote }}
{{- end }}
  name: {{ template "rabbitmq-ha.fullname" $root }}-{{ $i }}
  labels:
    app: {{ template "rabbitmq-ha.name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
{{- if ne $root.Values.service.type "NodePort" }}
  clusterIP: "{{ $root.Values.service.clusterIP }}"
{{- end }}
{{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $root.Values.rabbitmqManagerPort }}
      targetPort: http
    - name: amqp
      protocol: TCP
      port: {{ $root.Values.rabbitmqNodePort }}
      targetPort: amqp
    - name: epmd
      protocol: TCP
      port: {{ $root.Values.rabbitmqEpmdPort }}
      targetPort: epmd

  selector:
    app: {{ template "rabbitmq-ha.name" $root }}
    release: {{ $root.Release.Name }}
  type: {{ $root.Values.service.type }}
{{- end }}
```


@jasquat Yes, You are right. The conditionals are work for me, and I use `--dry-run --debug ` and get template content like below

```
# Source: rabbitmq-ha/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tailored-rottweiler-rabbitmq-ha
  labels:
    app: rabbitmq-ha
    chart: rabbitmq-ha-1.23.0
    release: tailored-rottweiler
    heritage: Tiller
spec:
  clusterIP: "None"
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: http
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: epmd
      protocol: TCP
      port: 4369
      targetPort: epmd
    
  selector:
    app: rabbitmq-ha
    release: tailored-rottweiler
  type: ClusterIP

```

The template contents before not put conditionals, see below：

```
---
# Source: rabbitmq-ha/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: xrayed-bison-rabbitmq-ha
  labels:
    app: rabbitmq-ha
    chart: rabbitmq-ha-1.23.0
    release: xrayed-bison
    heritage: Tiller
spec:
  clusterIP: "None"
  ports:
    - name: http
      protocol: TCP
      port: 15672
      nodePort: 
      targetPort: http
    - name: amqp
      protocol: TCP
      port: 5672
      nodePort: 
      targetPort: amqp
    - name: epmd
      protocol: TCP
      port: 4369
      nodePort: 
      targetPort: epmd
    
  selector:
    app: rabbitmq-ha
    release: xrayed-bison
  type: ClusterIP
```

I will close this issue and thanks for your help.
