### ISSUE TITLE
[stable/kong] initcontainer error after helm upgrade

### ISSUE THREAD

**Issue by deepaksood619** [helm/charts#12575]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/kong

**What happened**:
After helm upgrade init container has errors
```
Error: [PostgreSQL error] failed to retrieve server_version_num: FATAL: password authentication failed for user "kong"
   Run with --v (verbose) or --vv (debug) for more details
```

**What you expected to happen**:
Init container should have finished and kong started

**How to reproduce it** (as minimally and precisely as possible):
Changed the kong image tag to `1.0.3` from `1.0.2` in values.yaml. After this ran `helm upgrade` command

**Anything else we need to know**:
After purge delete and deploy again it works seamlessly. Same problem if any other update to values.yaml. Helm upgrade never seems to work.

**Comment by MilanDasek** [comment]
I have same problem. Upgrade does not work. No matter if I use exactly same values.yaml - STATUS: FAILED with --dry-run --debug

**Comment by phlegx** [comment]
Update: Also with Helm Chart Kong version `0.10.3` we experience the same issue still.

**Comment by hbagdi** [comment]
The root of this problem is here: https://github.com/helm/charts/issues/5167


You can solve this problem only if you specify a postgres password yourself as part of your installation or upgrade, otherwise every time you perform an upgrade, a new password will be generated and Kong will not be able to talk to psql anymore.

This is really a limitation in Helm and not Kong's Helm chart.

**Comment by rolandg** [comment]
Are there any news on this? 
How do you work with this limitation?
Can I set my password somewhere in plain text to get upgrades working somehow?
Is there another way to work around this issue?

We cannot use the helm charts like this.

**Comment by wrdls** [comment]
@rolandg You can set the password (and other values for the `postgresql` dependency) in your values file:

```
postgresql:
  postgresqlPassword: K6W9qBFzTQPj8xQiSouA
```

**Comment by rolandg** [comment]
Found out that if you setup your own postgres and disable the one from the kong charts then upgrades are possible.

**Comment by ammggmrtl** [comment]
Hi.

I'm having this issue even when running for example:

helm install stable/kong --name kong --namespace api-gateway --set env.pg_database=kong --set env.pg_user=kong --set env.pg_password=0000000 --set postgresql.postgresqlPassword=0000000

Still, in the end, I keep getting the following: 
```
2019-06-18 09:22:41.205 GMT [1635] FATAL:  password authentication failed for user "kong"
2019-06-18 09:22:41.205 GMT [1635] DETAIL:  Password does not match for user "kong".
	Connection matched pg_hba.conf line 95: "host     all             all             0.0.0.0/0               md5"
```

```
  Run with --v (verbose) or --vv (debug) for more details
waiting for db
Error: [PostgreSQL error] failed to retrieve server_version_num: FATAL: password authentication failed for user "kong
```

Any ideas?

**Comment by rolandg** [comment]
@ammggm I needed to disable postgres with `--set postgresql.enabled=false`
here are my answers:
```
---
  image:
    tag: "latest"
  proxy: 
    http: 
      hostPort: "80"
    tls: 
      hostPort: "443"
    type: "ClusterIP"
  admin: 
    type: "ClusterIP"
    useTLS: true
  postgresql:
    enabled: false
  env: 
    pg_password: "00000000"
    pg_host: "kong-psql.kong.svc.cluster.local"
    pg_database: "kong"
    pg_user: "kong"
    pg_port: 5432
  nodeSelector: 
    deploy/kong-proxy: "true"
  replicaCount: "2"
```

**Comment by ammggm** [comment]
But in that case it will not create the pod for the psql, what I don't seem to see working is that the user and pass I'm setting are just ignored.

**Comment by ammggm** [comment]
So, in the end, managed to have it running if I don't give a --name during the helm install command.

Kinda strange for me that if you don't keep a random-name the all helm install will fail.

**Comment by F0otsh0T** [comment]
So what is the definitive fix when "--name" is specified during the helm install?

**Comment by hbagdi** [comment]
The error shouldn't really happen if `--name` is specified.

A potential solution that can work here is creating a secret in k8s for postgres password and then passing it to Kong and postgresql helm chart (via postgresql.postgresqlPassword param)

**Comment by F0otsh0T** [comment]
^^Didn't see that env/param - did see this one:

env.pg_password | Postgres database password (required if you are using your own database) | kong

**Comment by F0otsh0T** [comment]
Attempted to set both the env.pg_password and postgresql.postgresqlPassword in the values.yml / or via --set and still getting the same failure when attempting to specific --name for the helm release

**Comment by MarcinGinszt** [comment]
Issue still exist, Kong does not work if the `name` parameter is specified

**Comment by MarcinGinszt** [comment]
Upgrading Helm release causes reroll of the postgres-password in the <release_name>-postgresql secret, without rerolling the actuall postgresql password. 
Workaround is setting the postgresql password.

**Comment by zffocussss** [comment]
I am facing the same issue.

**Comment by morvencao** [comment]
Same issue after I installed with kong-operator.

/cc @gyliu513 @zxdiscovery

**Comment by morvencao** [comment]
Workaround the issue by the following paramaters:
```
  # workaround for https://github.com/helm/charts/issues/12575
  env:
    pg_password: password
    database: postgres
  postgresql:
    enabled: true
    postgresqlUsername: kong
    postgresqlPassword: password
    postgresqlDatabase: kong
    service:
      port: 5432
```
