### ISSUE TITLE
Local storage with persistent volume on docker for windows caused errors to charts

### ISSUE THREAD

**Issue by tetrar124** [helm/charts#12614]
**Is this a request for help?**:
  yes   

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT  

**Version of Helm and Kubernetes**:
k8s: v1.13.0 on docker for windows
Helm: client: v2.12+unreleased, server: canary+unreleased   

**Which chart**:
Grafana and Mysql  

**What happened**:
I applied local persistence volume to charts of Grafana or Mysql with docker for windows.
It caused ErrImagePull or CrashLoopBackOff to the charts.
But when this local persistence volume settings used without helm, it worked fine.   

**How to reproduce it** (as minimally and precisely as possible):
sc.yaml
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
pv.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /c/k/share/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
       - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
```
pvc.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mysql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
```
conf.yaml (this file is same for mysql and grafana)
```yaml
persistence:
  enabled: true
  storageClass: local-storage
  existingClaim: local-mysql-claim
  accessMode: ReadWriteOnce
  size: 1Gi
```
**Grafana: ImagePullBackOff**
**Mysql: CrashLoopBackOff**

Would you plese tell me how to fix these problems
