### ISSUE TITLE
How to configure nfs-server-provisioner to satisfy the persistent volume claim dynamically and define affinity to ensure that NFS service is provided by a specific k8s node

### ISSUE THREAD

**Issue by davesargrad** [helm/charts#12626]
Hi. 
The chart I am trying to use is [nfs-server-provisioner](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner)

I've attempted to install the chart as follows
```
helm install --name nfs-server-provisioner stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=5Gi
```

The resulting claim is in a pending state
```
[root@togo work]# kubectl get pvc
NAME                            STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-nfs-server-provisioner-0   Pending                                                     20h
```

As is the resulting pod
```
[root@togo work]# kubectl get pod
NAME                       READY   STATUS    RESTARTS   AGE
nfs-server-provisioner-0   0/1     Pending   0          20h
```

Its clear that the claim is in this state since there is no persistent volume
```
[root@togo work]# kubectl describe pvc data-nfs-server-provisioner-0
Name:          data-nfs-server-provisioner-0
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        app=nfs-server-provisioner
               release=nfs-server-provisioner
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type       Reason         Age                    From                         Message
  ----       ------         ----                   ----                         -------
  Normal     FailedBinding  4m8s (x4944 over 20h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  nfs-server-provisioner-0
```

Its also clear that the pod is pending because its claim is not satisfied
```
[root@togo work]# kubectl describe pod/nfs-server-provisioner-0
Name:               nfs-server-provisioner-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=nfs-server-provisioner
                    chart=nfs-server-provisioner-0.2.1
                    controller-revision-hash=nfs-server-provisioner-69bc6f77dd
                    heritage=Tiller
                    release=nfs-server-provisioner
                    statefulset.kubernetes.io/pod-name=nfs-server-provisioner-0
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      StatefulSet/nfs-server-provisioner
Containers:
  nfs-server-provisioner:
    Image:       quay.io/kubernetes_incubator/nfs-provisioner:v1.0.9
    Ports:       2049/TCP, 20048/TCP, 111/TCP, 111/UDP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/UDP
    Args:
      -provisioner=cluster.local/nfs-server-provisioner
    Environment:
      POD_IP:          (v1:status.podIP)
      SERVICE_NAME:   nfs-server-provisioner
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /export from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nfs-server-provisioner-token-xg22t (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-nfs-server-provisioner-0
    ReadOnly:   false
  nfs-server-provisioner-token-xg22t:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nfs-server-provisioner-token-xg22t
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  54s (x1277 over 20h)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 5 times)
[root@togo work]# helm list
NAME                    REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
dashboard-demo          1               Wed Mar 27 11:43:20 2019        DEPLOYED        kubernetes-dashboard-1.3.0      1.10.1          kube-system
khaki-squid             1               Thu Mar 28 09:00:07 2019        DEPLOYED        rook-ceph-v0.9.3                                rook-ceph-system
nfs-server-provisioner  1               Wed Mar 27 12:42:48 2019        DEPLOYED        nfs-server-provisioner-0.2.1    1.0.8           default
```

This is not a production system. Its a learning system. 
I'd like to define a node affinity such that the NFS server is tied to a specific node (e.g. tonga in the following):
```
[root@togo work]# kubectl get nodes
NAME                    STATUS   ROLES    AGE   VERSION
benin.corp.sensis.com   Ready    <none>   22h   v1.13.4
chad.corp.sensis.com    Ready    <none>   23h   v1.13.4
qatar.corp.sensis.com   Ready    <none>   23h   v1.13.4
spain.corp.sensis.com   Ready    <none>   22h   v1.13.4
togo.corp.sensis.com    Ready    master   23h   v1.13.4
tonga.corp.sensis.com   Ready    <none>   22h   v1.13.4
```

Id then like to satisfy the claim in as simple a way as possible (I would like to dynamically provision the persistent volume, rather than manually create it).

I've tried several configuration tweaks. The latest I've tried is as follows:
```
[root@togo work]# cat values.yaml
replicaCount: 1


image:
  repository: quay.io/kubernetes_incubator/nfs-provisioner
  tag: v1.0.9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

  nfsPort: 2049
  mountdPort: 20048
  rpcbindPort: 51413

  externalIPs: []

persistence:
  enabled: true


  accessMode: ReadWriteMany
  size: 5Gi

storageClass:
  create: true


  defaultClass: true

  name: nfs

  parameters:
    mountOptions: vers=4.1

  reclaimPolicy: Delete

rbac:
  create: true

  serviceAccountName: default

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
```

I then install with
```
helm install --name nfs-server-provisioner stable/nfs-server-provisioner -f values.yaml
```

Can someone please guide me in updating the configuration to achieve this.

1. Ensure NFS service is provided by node tonga
2. Ensure that the PV is dynamically generated so that the PVC finds an appropriate volume

Again this is not a production system, so I am looking for a simple mod to configuration
Thanks.

**Comment by gridworkz** [comment]
I use OpenEBS to setup storage classes. Then I do something like:

`helm install stable/nfs-server-provisioner --name=addons --set=persistence.enabled=true,persistence.storageClass=openebs-jiva-default,persistence.size=5Gi,storageClass.name=addons-nfs-sc1`

Then create a pvc:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: nfs-addons
 namespace: saas
 annotations:
  volume.beta.kubernetes.io/storage-class: "addons-nfs-sc1"
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 5G
```
I setup a pod to copy my Odoo addons to:

```
kind: Pod
apiVersion: v1
metadata:
  name: nfs-addons
  namespace: saas
spec:
  containers:
  - name: nfs-addons
    image: alpine/git
    command: ['sh', '-c', 'while true; do sleep 5; done']
    volumeMounts:
      - name: addons
        mountPath: "/var/nfs"
  restartPolicy: "Never"
  volumes:
   - name: addons
     persistentVolumeClaim:
       claimName: nfs-addons
```
Then in the Odoo deployment yaml:

```
....
        volumeMounts:
        - mountPath: /bitnami/odoo
          name: odoo-data
        - mountPath: /mnt/addons
          name: odoo-addons
....
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: b1-s2-odoo
      - name: odoo-addons
        persistentVolumeClaim:
          claimName: nfs-addons
.....
```
