### ISSUE TITLE
[stable/grafana] Can't import dashboard from json file

### ISSUE THREAD

**Issue by petrokashlikov** [helm/charts#12679]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

Helm:
`Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
`
Kubernetes: 
`Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**:
[stable/grafana]

**What happened**:
I'm trying to setup grafana to load charts from dashboards folder in chart as per documentation. Created dashboard folder in my chart folder and put sample redis.json file there. In values.yaml configured following:
```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
```

```
dashboards:
  default:
    redis:
      file: dashboards/redis.json
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
#    local-dashboard:
#      url: https://example.com/repository/test.json
#    local-dashboard-base64:
#      url: https://example.com/repository/test-b64.json
#      b64content: true`
```

When I deploy grafana prometheus-stats dashboard is loaded, but redis one no. I see that chart created config map with following contents. Also in container file redis.json was copied to /var/lib/grafana/dashboards/default, but it is empty.   Does it mean it was not able to parse json or something like that, as there is empty value?  
If I run 
`helm install  --dry-run --debug --name grafana --namespace monitoring -f values.yaml stable/grafana`
there is no errors thrown.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-default
  labels:
    app: grafana
    chart: grafana-3.0.1
    release: grafana
    heritage: Tiller
    dashboard-provider: default
data:
  redis.json:
    ""
```

**What you expected to happen**:

Expect dashboard to be imported

**How to reproduce it** (as minimally and precisely as possible):

Using helm install command and modifying values.yaml file with above values
helm install  --name grafana --namespace monitoring -f values.yaml stable/grafana

**Anything else we need to know**:
