### ISSUE TITLE
[stable/prometheus-operator] am I configuring correctly?

### ISSUE THREAD

**Issue by mjschmidt** [helm/charts#12687]
I launched loki to the default namespace and now I am attempting to launch prometheus-operator to the default namespace with loki added as an additional datasource, but I am getting a configuration error that causes helm to not fire off. If anyone on here would double check my configs I am pretty sure I am just doing something wrong? Thank! 

```
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources: []
   - name: loki
     access: proxy
     basicAuth: false
     basicAuthPassword: pass
     basicAuthUser: daco
     editable: false
     jsonData:
         tlsSkipVerify: true
     orgId: 1
     type: loki
     url: http://loki:3100/
     version: 1
```

**Comment by adamelliotfields** [comment]
At first glance it appears that you're setting `additionalDataSources` to an empty array, and then trying to list an object in that array.

Remove the `[]` and you should be good to go, but I can't speak to the other settings.

I always run my YAML through a YAML-JSON converter to see what it actually means, since my brain understands JSON better. Here's one: <https://www.json2yaml.com/convert-yaml-to-json>

**Comment by mjschmidt** [comment]
@adamelliotfields it really isn't the worst thing in the world, but I always want to automate when possible, especially something as straight forward as, yes I want logs, yes I want metrics, everytime, everycluster.

**Comment by adamelliotfields** [comment]
@mjschmidt Yeah I hear you, that's what the additional data sources property is there for! Might as well use it.

BTW, did removing the brackets fix the YAML issue?

You may also want to check out [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus), which sets up a full monitoring stack for you, complete with really nice Grafana dashboards.

**Comment by mjschmidt** [comment]
I am actually right now trying to build it into the brackets first as an array. I will get back to you!

**Comment by mjschmidt** [comment]
@adamelliotfields passing in the [] array did not work because I didn't understand the syntax of it and was passing it in incorrectly. However, when I took your advice and passed it in via the yaml array configuration method and removed the [] it fired up beautifully. Its a rather straight forward add, eventually Prometheus may consider adding Loki as the default commented out example! Who knows, thank you for your help! here is my config in case you want it
```
  ## Configure additional grafana datasources
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources:
   - name: loki
     access: proxy
     basicAuth: false
     basicAuthPassword: pass
     basicAuthUser: daco
     editable: false
     jsonData:
         tlsSkipVerify: true
     orgId: 1
     type: loki
     url: http://loki:3100/
     version: 1
```
