### ISSUE TITLE
atlantis OWNERS file includes people who are not repo-collaborators

### ISSUE THREAD

**Issue by fejta** [helm/charts#12834]
https://github.com/helm/charts/blob/605673127bd204f733535beaf3a25fc6d6aecc25/stable/atlantis/OWNERS

includes people who are not repo collaborators in github. This causes github to reject adding them as assignees. Both the blunderbuss and lgtm prow plugins require OWNERS to be assigned.

Please add these individuals as repo collaborators and/or org members.

Consider using peribolos https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos to make it easier to manage who has what access to the org (like kubernetes does at kubernetes/org)

/assign @mattfarina @foxish @lachie83 

```yaml
jsonPayload: {
  author:  "justinhauer"   
  component:  "hook"   
  error:  "could not request a PR review from the following user(s): callmeradical."   
  event-GUID:  "e790a4a0-5705-11e9-83d6-fb18738cb22c"   
  event-type:  "pull_request"   
  level:  "error"   
  msg:  "Error handling PullRequestEvent."   
  org:  "helm"   
  plugin:  "blunderbuss"   
  pr:  12831   
  repo:  "charts"   
  url:  "https://github.com/helm/charts/pull/12831"   
 }
```
