### ISSUE TITLE
kafka with a loadbalancer not using the correct targetport

### ISSUE THREAD

**Issue by bonovoxly** [helm/charts#12853]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
- Helm v2.12.1
- Kubernetes v1.11.8-eks-7c34c0

**Which chart**:

[incubator/kafka](https://github.com/helm/charts/tree/master/incubator/kafka)

**What happened**:

Note: I'm using this in AWS, with external-dns creating the DNS entries linked to the ELBs.

When deploying using a load balancer and `external.distinct: true`, it seems one of two things is incorrect and not lining up with the ELB:

- The [targetPort](https://github.com/helm/charts/blob/master/incubator/kafka/templates/service-brokers-external.yaml#L58) is incorrect. The `servicePort` should be used (default: `19092`).
- The other option is the [port](https://github.com/helm/charts/blob/master/incubator/kafka/templates/service-brokers-external.yaml#L51) is incorrect. The `externalListenerPort` should be used (default: `31090` + pod number).

All of this is dependent on the `configurationOverrides` setting, which configures the listeners (and I'm wondering if I have this wrong, I'm unsure).

The following will use port `19092` as the external listener port in the pod:

```
configurationOverrides:
  advertised.listeners: |-
    EXTERNAL://${POD_NAME}.example.org:19092
  listener.security.protocol.map: |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
```

And the following will use port `31090 + X` as the external listener port in the pod:

```
configurationOverrides:
  advertised.listeners: |-
    EXTERNAL://kafka.cluster.local:$((31090 + ${KAFKA_BROKER_ID}))
  listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
```

Both of these settings do NOT line up with the LoadBalancer service that is created, which will listen on `19092` and connect to pod port `31090 + X`.

**What you expected to happen**:

I expect the LoadBalancer service to line up the advertised listener ports.

**How to reproduce it** (as minimally and precisely as possible):

Example values.yml:

```
configurationOverrides:
  advertised.listeners: |-
    EXTERNAL://${POD_NAME}.example.org:19092
  listener.security.protocol.map: |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

external:
  distinct: true
  enabled: true
  domain: example.org
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

persistence:
  size: 25Gi

prometheus:
  jmx:
    enabled: true
  kafka:
    enabled: true

topics:
  - name: Testing
    partitions: 3
    replicationFactor: 3
```

**Anything else we need to know**:

I think if you insert the following after [line 54](https://github.com/helm/charts/blob/master/incubator/kafka/templates/service-brokers-external.yaml#L54), things should work as expected:

```
      {{- else if and (eq $root.Values.external.type "LoadBalancer") ($root.Values.external.distinct) }}
      targetPort: {{ $servicePort }}
```

To muddy the waters a bit more, the other option is to remove the ` (not $root.Values.external.distinct)` from line 50.

(I also accept that I am missing something with the advertised listener/listener configuration).

I'm more than willing to dig into this, I thought I would create an issue first to see if I was `doing it wrong`.
