### ISSUE TITLE
[stable/cerebro] Basepath don't change in healthcheck

### ISSUE THREAD

**Issue by roonie007** [helm/charts#12910]
**BUG REPORT** :

**Version of Helm and Kubernetes**: v2.12.1
**Which chart**: stable/cerebro

**What happened**:

When I deploy the cerebro helm with the config.basePath set to something else than "/", the pod will restart forever, since the healthcheck is Fixed only on "/" example :

```yaml
  ingress:
    enabled: true
    path: /cerebro/
    hosts:
    - example.net
  config:
    basePath: "/cerebro/"
    hosts:
    - host: "http://elasticsearch-client:9200"
      name: "elasticsearch"
```

When i disable the healthcheck everything works as expected

https://github.com/helm/charts/blob/7b1290efb7172de960b43a9f8bc603e4c38e2594/stable/cerebro/templates/deployment.yaml#L51

**What you expected to happen**:

The deployment works without restarting forever

**How to reproduce it** (as minimally and precisely as possible):

Just change the `ingress.path` and `config.basePath` to something different than "/"

**Anything else we need to know**:

Make the healthcheck Optional
