### ISSUE TITLE
[stable/prometheus-operator] Not able to create new PrometheusRule

### ISSUE THREAD

**Issue by prasus** [helm/charts#12930]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**:

chart: prometheus-operator-5.0.4, AppVersion: 0.29.0 (stable/prometheus-operator)
Kubernetes Version: v1.14 

**Which chart**:

stable/prometheus-operator
chart: prometheus-operator-5.0.4
AppVersion: 0.29.0

**What happened**:

I am currently testing alert manager features and have configured Prometheus via helm chart, trying to add a new alert rule using `PrometheusRule` CRD using the below manifest. but unfortunately,  it's not working for some reason :( 

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  labels:
    app: prometheus-operator
    release: prompoc
    role: alert-rules
  name: prompoc-prometheus-operato-nichu.rules
  namespace: default
spec:
  groups:
  - name: nichu.rules
    rules:
    - alert: TargetDown
      annotations:
        message: '{{ $value }}% of the {{ $labels.job }} targets are down.'
      expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
      for: 10m
      labels:
        slack: yes
    - alert: Watchdog
      annotations:
        message: |
          This is an alert meant to ensure that the entire alerting pipeline is functional.
          This alert is always firing, therefore it should always be firing in Alertmanager
          and always fire against a receiver. There are integrations with various notification
          mechanisms that send a notification when this alert is not firing. For example the
          "DeadMansSnitch" integration in PagerDuty.
      expr: vector(1)
      labels:
        slack: yes
```
The rule selector label matches with the prometheus object as seen below
```
kubectl get prometheus prompoc-prometheus-operato-prometheus -o yaml | grep -i -A5 ruleselector
  ruleSelector:
    matchLabels:
      app: prometheus-operator
      release: prompoc
  securityContext:
    fsGroup: 2000
```
The `PrometheusRule` object deploys without any issues, but the rules `ConfigMap` is  not getting updated after the deployment.,

`kubectl get configmap prometheus-prompoc-prometheus-operato-prometheus-rulefiles-0 -o yaml | grep nichu`

I also tried to directly edit the cofigmap for Prometheus rules but the changes are reverted as soon as I save the changes. 

**How to reproduce it** (as minimally and precisely as possible):

1. Deploy Prometheus with helm using the below command

`helm install --name prompoc --set alertmanager.enabled=true --set persistence.enabled=false stable/prometheus-operator`

2. Create a new `PrometheusRule` CRD object.

3. Check the rules configMap, afaik, this should add the new alert rule to the `configMap`, but in my case it didn't. 

**Anything else we need to know**:
-

**Comment by vsliouniaev** [comment]
stable/prometheus does not use the operator

**Comment by prasus** [comment]
@vsliouniaev, Thanks and sorry for providing the wrong chart name,  I am actually facing this issue with `stable/prometheus-operator` chart. The chart is deployed using the below command as you can see in the "how to reproduce" section mentioned above. Appreciate if you could shed some light on this. Thank you!

`helm install --name prompoc --set alertmanager.enabled=true --set persistence.enabled=false stable/prometheus-operator`

**Comment by prasus** [comment]
It works if I attempt to add new alert rules to one of the default `PrometheusRules` CRDs created by the helm install. I tried appending a new rule (see below) to `prometheus-operator-general.rules` using `kubectl edit PrometheusRule prometheus-operator-general.rules` and it successfully updates the rules `configMap`

```
   - alert: Testing
        message: '{{ $value }}% of the {{ $labels.job }} targets are down.'
        expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
        for: 2m
        labels:
          slack: "yes"
```
but it fails to update the `configMap` when trying to create new PrometheusRule CRD's as explained earlier.

I have also tried adding new `PrometheusRule` using `additionalPrometheusRules:` in the chart `values.yaml`  and it works w/o issues, but this requires  a `helm upgrade` every-time we need to add new PrometheusRule CRD's, Thanks!
