### ISSUE TITLE
[stable/grafana] Allow passing ENV vars for kiwigrid/k8s-sidecar

### ISSUE THREAD

**Issue by den-is** [helm/charts#12984]
Sorry but somehow this issue is not getting enough attention so I'm duplicating it here.

Grafana is refusing to work in my environment until I manually edit grafana deployment and insert next ENV var into deployment containers:
```yaml
    spec:
...
      initContainers:
      - env:
...
        - name: SKIP_TLS_VERIFY
          value: "true"
...

      containers:
      - env:
...
        - name: SKIP_TLS_VERIFY
          value: "true"
```

- **kiwigrid/k8s-sidecar** which is used in grafana deployment `spec.containers.name=grafana-sc-dashboard` and in `spec.initContainers.name=grafana-sc-datasources`

- Please allow passing user-defined ENV variable to that containers.

- Please allow attaching secrets with certs/CAs to that image

https://github.com/kiwigrid/k8s-sidecar/issues/18
https://github.com/helm/charts/issues/11287
