### ISSUE TITLE
[stable/metrics-server] PSP probably way too broad.

### ISSUE THREAD

**Issue by SleepyBrett** [helm/charts#12993]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
kubernetes 1.13
helm N/A

**Which chart**:
stable/metrics-server

**What happened**:
Upon inspection of the chart I found a psp that is wide open. What permissions does this thing actually need?

**What you expected to happen**:
I expect an official stable chart to be secured properly.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
nope.

**Comment by steven-sheehy** [comment]
I recently narrowed the permissions for metrics-server in PR https://github.com/helm/charts/pull/12997. You're welcome to submit a PR that changes the PSP accordingly. Here's the securityContext:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["all"]
  readOnlyRootFilesystem: true
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001
```
