### ISSUE TITLE
[stable/stellar-core] incorrect quorumSet config for thresholdPercent 

### ISSUE THREAD

**Issue by tsmgeek** [helm/charts#12990]
upstream satoshipay config for quorumset is different from README

**threshold_percent** vs **thresholdPercent** 

```
quorumSet:
  - path: primary
    threshold_percent: 51
    validators:
      - $$sdf1
      - $$sdf2
      - $$sdf3
```
