### ISSUE TITLE
SonarQube chart - values file ignored, defaults used

### ISSUE THREAD

**Issue by OmpahDev** [helm/charts#13017]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Version of Helm and Kubernetes**: 1.12. Helm version 2.13

**Which chart**: stable/sonarqube

**What happened**: Values file is ignored. Everything I'm trying to pass is disregarded and it runs the deployment with default files.

Using this values file:
```
persistence:
  enabled: true
  existingClaim: sonarqube-claim

database:
  type: "postgresql"
  enabled: false
  postgresServer: "<redacted>"
  postgresUser: "<redacted>"
  postgresPassword: "<redacted>"
  postgresDatabase: "sonarDB"
  service:
    port: 5432

```

and with this launch command:
helm install stable/sonarqube --namespace <redacted> -f sonarqube-config.yml

**What you expected to happen**:
I expect it to launch while using my custom pvc and predefined postgres, as per the values file above. Instead it ignores all this and creates its own pvc and its own postgres pod.

**How to reproduce it** (as minimally and precisely as possible):
Have that values file saved as "sonarqube-config.yml" and run the helm deploy command I listed.

**Comment by carrodher** [comment]
The sections related to the database are a little different:
```yaml
## Configuration value to select database type
## Option to use "postgresql" or "mysql" database type, by default "postgresql" is chosen
## Set the "enable" field to true of the database type you select (if you want to use internal database) and false of the one you don't select
database:
  type: "postgresql"

## Configuration values for postgresql dependency
## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
postgresql:
  # Enable to deploy the PostgreSQL chart
  enabled: true
  # To use an external PostgreSQL instance, set enabled to false and uncomment
  # the line below:
  # postgresServer: ""
  # To use an external secret for the password for an external PostgreSQL
  # instance, set enabled to false and provide the name of the secret on the
  # line below:
  # postgresPasswordSecret: ""
  postgresUser: "sonarUser"
  postgresPassword: "sonarPass"
  postgresDatabase: "sonarDB"
  # Specify the TCP port that PostgreSQL should use
  service:
    port: 5432
```

Can you try using this wording?
