### ISSUE TITLE
[stable/prometheus-operator] Federation config from prometheus to prometheus-operator

### ISSUE THREAD

**Issue by oleksandr-semak** [helm/charts#13030]
**Which chart**:

prometheus-operator v5.0.3

**What happened**:

I am trying create `additionalServiceMonitors` for scrap metrics from prometheus-server in others cluster which spinup by prometheus-operator:
```
  additionalServiceMonitors:
    - name: agg-prometheus-aggregator
      additionalLabels:
        release: agg-prometheus
      namespaceSelector:
        any: true
      endpoints:
        - path: /federate
          port: https
          interval: 30s
          scheme: https
          honorLabels: true
          params:
            match[]:
              - '{job="kube-state-metrics"}'
          tlsConfig:
            insecureSkipVerify: true
          staticConfigs:
            targets:
              - prometheus.wx-dev-001.us-east.xxx
              - prometheus.wx-prod-001.us-south.xxx
              - prometheus.wx-prod-002.us-south.xxx
              - prometheus.wx-prod-003.eu-de.xxx
              - prometheus.wx-prod-004.eu-de.xxx
              - prometheus.wx-prod-005.au-syd.xxx
              - prometheus.wx-prod-006.sng01.xxx
              - prometheus.wx-prod-007.xxx
              - prometheus.wx-prod-008.xxx 

```
but config above doesn't work.
I also create the same with `stable/prometheus` chart and everything work fine:
```
extraScrapeConfigs: |
  - job_name: 'agg-prom'
    scrape_interval: 45s
    metrics_path: /federate
    honor_labels: true
    scheme: https
    params:
      match[]:
        - '{job="kube-state-metrics"}'
    static_configs:
      - targets: [prometheus.wx-dev-001.us-east.xxx]
        labels:
          cluster_name: wx-dev-001
      - targets: [prometheus.wx-prod-001.us-south.xxx]
        labels:
          cluster_name: wx-prod-001
      - targets: [prometheus.wx-prod-002.us-south.xxx]
        labels:
          cluster_name: wx-prod-002
      - targets: [prometheus.wx-prod-003.eu-de.xxx]
        labels:
          cluster_name: wx-prod-003
      - targets: [prometheus.wx-prod-004.eu-de.xxx]
        labels:
          cluster_name: wx-prod-004
      - targets: [prometheus.wx-prod-005.au-syd.xxx]
        labels:
          cluster_name: wx-prod-005
      - targets: [prometheus.wx-prod-006.sng01.xxx]
        labels:
          cluster_name: wx-prod-006
      - targets: [prometheus.wx-prod-007-517180.xxx]
        labels:
          cluster_name: wx-prod-007
      - targets: [prometheus.wx-prod-008.us-east.xxx]
        labels:
          cluster_name: wx-prod-008
    tls_config:
      insecure_skip_verify: true
```

Looks like `servicemonitor` can't reveal staticConfig.targets

**Comment by AlexandrSemak** [comment]
OPS, my faults, have to use additionalScrapeConfigs

**Comment by Moulick** [comment]
@alexandrsemak  Can you post here your final working file?

**Comment by Sanjanare** [comment]
Though i add in the additionalScrapeConfigs it doesnot add to the configurations @alexandrsemak @Moulick can you post the working configurations?

**Comment by shivpathak** [comment]
@Moulick 
Can you please help @alexandrsemak here?

by the way i also need to pass additionalScrapConfigs?

**Comment by alexandrsemak** [comment]
use additionalScrapeConfigs instead of additionalServiceMonitors, I came decision use clean prometheus and grafana chart for aggregator and prometheus operator for cluster monitoring, because prometheus operator has a bunch needless config

**Comment by shivpathak** [comment]
@alexandrsemak can you please help me how to pass this addionalScrapeConfigs to prometheus operator installation using helm.

I am installing prometheus operator like below - 

`helm install --name prometheus-operator stable/prometheus-operator --tiller-namespace tiller`

I know we can pass parameters like `--set prometheus.prometheusSpec.additionalScrapeConfigs` 
but I am confused how we can pass a yaml federation configuration to this param?

--

**Comment by alexandrsemak** [comment]
You need --values flag for helm which can pass yaml file

**Comment by shivpathak** [comment]
@alexandrsemak ohh.. yeah.. got it.. Thanks.

**Comment by MakeshKathirvel** [comment]
@alexandrsemak 
Can you share the config for stable prometheus & grafana aggregator and prometheus operator for cluster monitor setup

I am trying to implement the same with prometheus operator as both aggregator and cluster monitoring, not sure how the alertmanager's setup will be?

it would be helpful if you share your setup for reference to many people

**Comment by alexandrsemak** [comment]
I use default alertmanager with prometheus-operator which pointing to the same slack channel. It bring you extra faulttolerance.
alertmanager config for prometheus-operator:
```
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/............'
    route:
      group_by: ['alertname', 'cluster', 'region', 'zone', 'cloud', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 84h
      receiver: 'slack'
      routes:
      - receiver: 'null'
        match:
          alertname: Watchdog
      - receiver: 'null'
        match:
          alertname: CPUThrottlingHigh
      - receiver: '...............'
        match:
          type: nginx-ingress
    receivers:
    - name: 'null'
    - name: 'slack'
      slack_configs:
      - channel: '#...............'
        send_resolved: false
        color: '{{ if eq .CommonLabels.severity "critical" }}danger{{ else if eq .CommonLabels.severity "warning" }}warning{{ else }}good{{ end }}'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
        title_link: '{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver }}'
        text: |-
          *Cloud:* {{ .CommonLabels.cloud }} | *Region:* {{ .CommonLabels.region }} | *Zone:* {{ .CommonLabels.zone }} | *Cluster:* {{ .CommonLabels.cluster }} 
          {{- range .Alerts }}
          *Message:* {{ .Annotations.message }}
          {{- end }}
    - name: '.................'
      slack_configs:
      - channel: '#..................'
        send_resolved: false
        color: '{{ if eq .CommonLabels.severity "critical" }}danger{{ else if eq .CommonLabels.severity "warning" }}warning{{ else }}good{{ end }}'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
        title_link: '{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver }}'
        text: |-
          *Cloud:* {{ .CommonLabels.cloud }} | *Region:* {{ .CommonLabels.region }} | *Zone:* {{ .CommonLabels.zone }} | *Cluster:* {{ .CommonLabels.cluster }} 
          {{- range .Alerts }}
          *Message:* {{ .Annotations.message }}
          {{- end }}   
```

prometheus config for prometheus-operator:

```
prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.............
    tls:
      - secretName: .............
        hosts:
          - prometheus..............
  prometheusSpec:
    externalUrl: "https://prometheus.............."
    externalLabels:
      cluster: .............
      region: .............
      zone: .............
      cloud: ..........................
    retention: 14d
    retentionSize: 50GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "............."
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 55Gi
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
```
