### ISSUE TITLE
Postgresql helm chart does not seem to honor existingClaim Template

### ISSUE THREAD

**Issue by JulianGindi** [helm/charts#13099]
**Version of Helm and Kubernetes**:

Kubernetes: 1.12.6
Helm: 2.13.0

**Which chart**:
postgresql

**What happened**:
I am unable to use a templated name for the persistence.existingClaim value. For example

```
  persistence:
    existingClaim: ".Release.Name"
```

I also tried

```
  persistence:
    existingClaim: "{{ .Release.Name }}"
```

Both times, the literal value (not correct value that the template should resolve to) ended up in my final template. I also get the following parsing error:

```
Error: YAML parse error on mariana-django/charts/postgresql/templates/statefulset.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface $
}]interface {}{".Release.Name":interface {}(nil)}
```

**What you expected to happen**:
It is documented that you can use a templated variable for the existingClaim field. This would allow me to create a PersistentVolumeClaim with the name of {{ .Release.Name }} and have postgresql use that.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a PersistantVolumeClaim that will be set to the release name

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```
for example.

2. Try setting the persistence fields like I specified above under the postgres service in values.yaml
3. Try using helm to install that postgres instance to the cluster, it will not use the created volume claim.

**Anything else we need to know**:

You will most likely run into the specified error above as well. I might just be doing something silly, but it seems like the documentation could be updated if that is the case.

**Comment by juan131** [comment]
Hi @JulianGindi 

As you can check in the link below, the `persistence. existingClaim` parameter's value is evaluated as a template :

https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml#L304

To include a template in the values.yaml use single quotes `''`:

```
persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  ## The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
  ##
  existingClaim: '{{ .Release.Name }}'
```

As you can check, it works:

```
$ helm repo update
$ helm install -f values.yaml stable/postgresql --name my-release --dry-run --debug
...
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: my-release
```
