### ISSUE TITLE
Prometheus ConfigMap override

### ISSUE THREAD

**Issue by travishaagen** [helm/charts#1310]
I would like a way to override the Prometheus Helm Chart's  `server` and `alertmanager` `ConfigMap`s. Presently, you can add data to them using `values.yaml`, but this doesn't work well for parent Helm Charts. I suggest that we allow for overriding the _name_ of the `ConfigMap` that gets mounted to the persistent volume. That way, the parent chart could create, and even make templates for, these `ConfigMap`s.

Related issues: #544 , #922

For example `values.yaml` could have the following fields added:

```
## alertmanager ConfigMap entries
##
alertmanagerFiles:
  # ConfigMap override where full-name is {{.Release.Name}}-{{.Values.alertmanagerFiles.configMapOverrideName}}
  configMapOverrideName: ""
...

## Prometheus server ConfigMap entries
##
serverFiles:
  # ConfigMap override where full-name is {{.Release.Name}}-{{.Values.serverFiles.configMapOverrideName}}
  configMapOverrideName: ""
...
```
Changes would then be made to `alertmanager-deployment.yaml` and `server-deployment.yaml` to use these overrides if present.
