### ISSUE TITLE
help needed jaegerUI

### ISSUE THREAD

**Issue by ashish1993** [helm/charts#13131]
**Is this a request for help?**:
Yes
**Version of Helm and Kubernetes**:
kubernetes 1.13

**What happened**:
Installed Jaeger develop enviroment via helm.
able to access jaeger Ui via simplest-query service and port 16686.
However not able to see any services except jaeger-query.
Deployed all-in-one deployement my app

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # (1)
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: acme/myapp:myversion 
```

But nothing can be seen in jaeger UI..how can one test Jaegr UI  not given in docs.
