### ISSUE TITLE
[stable/filebeat] Remove the deprecated prospectors option in the configuration

### ISSUE THREAD

**Issue by pjanuario** [helm/charts#13166]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Version of Helm and Kubernetes**:

```
 $ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
``` 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:49:54Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/filebeat

**What happened**:

The current chart configuration make use of a configuration property that was deprecated at version 6.3 and now it was removed on the verison 7.0

**What you expected to happen**:

Change the chart to support the configuration version of 7.0

**How to reproduce it**:

Run the chart with the tag 7.0.0 of the image.

**Anything else we need to know**:

Information about the release notes: https://www.elastic.co/guide/en/beats/libbeat/7.0/release-notes-7.0.0.html

**Comment by pjanuario** [comment]
using the `overrideConfig` property allow us to bypass the problem, but I guess this needs to be fixed.

**Comment by ianhuang92** [comment]
@pjanuario Hi , could you please provide more information on how to bypass this problem, I've encountered this as well. Thank you

**Comment by pjanuario** [comment]
@ianhuang92 The `overrideConfig` property allow you to override the all config something like this is possible, so basicly the values of the chart without what is broken.

```
---
image:
  repository: docker.elastic.co/beats/filebeat
  tag: 7.0.0
overrideConfig:
  filebeat.config:
    modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
  filebeat.inputs:
  - enabled: true
    paths:
    - /var/log/*.log
    - /var/log/messages
    - /var/log/syslog
    type: log
  - containers.ids:
    - '*'
    processors:
    - add_kubernetes_metadata:
        in_cluster: true
    - drop_event:
        when:
          equals:
            kubernetes.container.name: filebeat
    type: docker
  http.enabled: true
  http.port: 5066
  output:
    elasticsearch:
      hosts:
      - http://elasticsearch-master:9200
    file:
      enabled: false
  output.file:
    filename: filebeat
    number_of_files: 5
    path: /usr/share/filebeat/data
    rotate_every_kb: 10000
  processors:
  - add_cloud_metadata: null
monitoring:
  enabled: false
```

**Comment by ianhuang92** [comment]
Thanks @pjanuario , I've tried but it seems the `overrideConfig` does not affect the default config.
This is my values.yaml 
```
image:
  repository: docker.elastic.co/beats/filebeat
  tag: 7.0.0
  pullPolicy: Always
overrideConfig:
  filebeat.config:
    modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
  filebeat.inputs:
    - enabled: true
      paths:
      - /var/log/*.log
      - /var/log/messages
      - /var/log/syslog
      type: log
    - containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
      - drop_event:
          when:
            equals:
              kubernetes.container.name: filebeat
      type: docker
  http.enabled: true
  http.port: 5066
  output:
    file:
      enabled: false
    logstash:
      hosts:
        - "logstash.logging:5044"
  processors:
    - add_cloud_metadata: null
  monitoring:
    enabled: false
```
And this is the Pod log from filebeat 
![image](https://user-images.githubusercontent.com/30798206/56940581-baface00-6b52-11e9-866c-a94284820f2e.png)
