### ISSUE TITLE
[stable/prometheus-operator] Cannot add additionalPeers to alertmanager

### ISSUE THREAD

**Issue by rajiteh** [helm/charts#13266]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

**Which chart**:

stable/prometheus-operator

**What happened**:

Documentation states that the `additionalPeers` value in `alertmanager.alertmanagerSpec` should be a string array but in the template it is rendered as a serialized go list rather than a yaml array.

**What you expected to happen**:

alertmanager CRD object receiving additional peers as a string array 

**How to reproduce it** (as minimally and precisely as possible):

Simply supply few endpoints to the additionalPeers value as a string array, the apply will fail as the templated alertmanager.yaml is no longer valid yaml syntax.

**Anything else we need to know**:

A dirty work around is to supply the `additionalPeers` value to the chart as a json encoded string array.

```
# does not work
alertmanager:
  alertmanagerSpec:
    additionalPeers: ['ip1:123', 'ip2:123']

# works
alertmanager:
  alertmanagerSpec:
    additionalPeers: "['ip1:123', 'ip2:123']"
```

**Comment by vsliouniaev** [comment]
Thanks for reporting this! Apologies for the delay in answering - just going through a long backlog of issues today.

Do you think there's a way to fix this that would be backwards-compatible with your workaround?

**Comment by rajiteh** [comment]
Hi @vsliouniaev! Sorry for the late response. I've proposed a PR for this here: https://github.com/helm/charts/pull/14624

Let me know what you think.

**Comment by rajiteh** [comment]
For testing purposes, you may use the following override values.

```
# overrides-array.yaml ; this will fail on current head
---
alertmanager:
  alertmanagerSpec:
    additionalPeers:
    - 'amhost1:123'
    - 'amhost2:123'
    - 'amhost3:123'
    - 'amhost4:123'
    - 'amhost5:123'
    - 'amhost6:123'
```    
```
# overrides-string.yaml ; this is the work around that I'm using right now, however, spec dictates value must be a string array.
---
alertmanager:
  alertmanagerSpec:
    additionalPeers: "['amhost1:123', 'amhost2:123', 'amhost3:123', 'amhost4:123', 'amhost5:123', 'amhost6:123']"
