### ISSUE TITLE
[stable/prometheus-operator ] Default label selector for kubeControllerManager and KubeScheduler

### ISSUE THREAD

**Issue by faheem-nadeem** [helm/charts#13275]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**: 1.11 / Kops, Helm v2.13.0 

**Which chart**: prometheus-operator

**What happened**:
Default selector labels injected for kubescheduler and kubecontroller:
```
kubeScheduler:
  service:
    selector:
      component: kube-scheduler

kubeControllerManager:
  service:
    selector:
      component: kube-controller-manager
```

**What you expected to happen**:
For kops created clusters the pods have label `k8s-app` rather than component. Adding these selector in default values is bad i.e. cannot remove them, hence no endpoints and alerts are fired for both of them being down.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
