### ISSUE TITLE
[stable/airflow] airflow worker doesn't have queue arguments

### ISSUE THREAD

**Issue by sangwonl** [helm/charts#13357]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Any version of Helm and K8s

**Which chart**:
stable/airflow

**What happened**:
Airflow worker can run with the specific queues (not only `default` queue) by giving `-q` argument. (https://airflow.apache.org/cli.html#worker)

Using dedicated queues is useful for running a time-consuming job or a worker host bound job (example, broadcasting log cleanup job for each worker host). But the current chart template doesn't support `-q` argument.

**What you expected to happen**:
```yaml
workers:
  enabled: true
  ##
  ## Number of workers pod to launch
  replicas: 3
  ##
  ## Custom resource configuration
  resources:
    limits:
      cpu: "4"
      memory: "4G"
    requests:
      cpu: "2"
      memory: "2G"
  ##
  ## Annotations for the Worker pods
  podAnnotations: {}
    ## Example:
    ## iam.amazonaws.com/role: airflow-Role
  ##
  ## Celery worker configuration
  celery:
    ##
    ## number of parallel celery tasks per worker
    instances: 8
  ##
  ## Directory in which to mount secrets on worker nodes.
  secretsDir: /var/airflow/secrets
  ##
  ## Secrets which will be mounted as a file at `secretsDir/<secret name>`.
  secrets: []
  queues:                              # <-- it passes into `airflow worker` arguments
  - default
  - "$(hostname)"
```

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
