### ISSUE TITLE
[stable/airflow] scheduler.resources has wrong key in values.yaml 

### ISSUE THREAD

**Issue by sangwonl** [helm/charts#13352]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Version of Helm and Kubernetes**:
Not a specific version

**Which chart**:
stable/airflow

**What happened**:
Scheduler resources spec is defined as below in `values.yaml`
```
scheduler:
  resources:
    scheduler: {}               # <-- it's not accessed in template
    # limits:
    #   cpu: "1000m"
    #   memory: "1Gi"
    # requests:
    #   cpu: "500m"
    #   memory: "512Mi"
```

But it's not used in scheduler template, `deployments-scheduler.yaml`. So, k8s says an error that `scheduler` key is not allowed in `resources` spec.
```
      ...
      containers:
        - name: {{ .Chart.Name }}-scheduler
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy}}
          envFrom:
          - configMapRef:
              name: "{{ template "airflow.fullname" . }}-env"
          env:
          {{- include "airflow.mapenvsecrets" . | indent 10 }}
          resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
```

**What you expected to happen**:
We don't need `scheduler` object in `resources` object because it's unnecessary. (I think it was a mistyped one.) 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by hagridaaron** [comment]
I'm also having this issue. My upgrade pipelines broke yesterday while running this command:

`helm upgrade --values values-int.yaml --values secrets-int.yaml --namespace airflow-int "airflow-int" stable/airflow --debug --version 2.8.2`

```
UPGRADE FAILED
Error: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field "scheduler" in io.k8s.api.core.v1.ResourceRequirements
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field "scheduler" in io.k8s.api.core.v1.ResourceRequirements
```

my values.yaml for the `scheduler` and `web`:

```
scheduler:
  resources: {}

web:
  resources: {}
```

**Comment by wktmeow** [comment]
Workaround that works for me until this gets merged:

--set scheduler.resources.scheduler=null

**Comment by hagridaaron** [comment]
Thank you so much!

 

Thanks,

 

Aaron Tracy

Hagridaaron.com

@hagridaaron

**Comment by hagridaaron** [comment]
Ah! Thank you, that's great!!

**Comment by billcrook** [comment]
I see this as well, but I did not update the dependency version from 2.8.2. Was 2.8.2 republished with this issue?

**Comment by hagridaaron** [comment]
Pulled current version of `2.3.0`:

`helm fetch stable/airflow --version 2.3.0`

Looks like it is 😞 

```yaml

scheduler:
  resources:
    scheduler: {}
    # limits:
    #   cpu: "1000m"
    #   memory: "1Gi"
    # requests:
    #   cpu: "500m"
    #   memory: "512Mi"
```

We should get this fix pushed in ASAP. I haven't really contributed before, but I'll take a look at what I can figure out. Last time I checked there were some automated tests that hadn't passed for this PR.
