### ISSUE TITLE
node-exporter fail to pass arguments

### ISSUE THREAD

**Issue by ensonic** [helm/charts#13407]
This is a similar issue like https://github.com/helm/charts/issues/4409

**Which chart**:

prometheus-operator-5.0.3

**What happened**:

```
prometheus-node-exporter:
  extraArgs:
    collector.wifi: ""
```
results in
```
...
      containers:
        - name: node-exporter
          image: "quay.io/prometheus/node-exporter:v0.17.0"
          imagePullPolicy: IfNotPresent
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --web.listen-address=0.0.0.0:9100
            collector.wifi: ""
```

Using
```
prometheus-node-exporter:
  extraArgs:
  - --collector.wifi
```
works though.
