### ISSUE TITLE
[Stable/Telegraf] prometheus output plugin support

### ISSUE THREAD

**Issue by michemoche** [helm/charts#13403]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
k8s : 1.12.3
helm : 2.11.0

**Which chart**:
stable/telegraf

**What happened**:
the service just managed the input plugins, moreover, we should be able to activate or not that service if none of the input plugin need an endpoint

**What you expected to happen**:
- add this option in the values.yaml (like the "official" chart [here](https://github.com/influxdata/tick-charts/blob/master/telegraf-s/values.yaml#L42)
```
service:
  enabled: false
```
- add a section for a service_output.yaml and create a template file like the one attached
```
service_output:
  enabled: true
  type: ClusterIP
```

**How to reproduce it** (as minimally and precisely as possible):
add those lines to the input/output part of the values.yaml

```
  outputs:
    - prometheus_client:
        listen: ":9273"
        path: "/metrics"
  inputs:
    - influxdb:
        urls: 
        - "http://influxdb-dev.influxdb.svc.cluster.local:8086/debug/vars"
        timeout: "5s"
```

**Anything else we need to know**:
this is the service_output i've created

```
{{- if .Values.service_output.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-output
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service_output.type }}
  ports:
  {{- range $objectKey, $objectValue := .Values.config.outputs }}
  {{- range $key, $value := . -}}
    {{- $tp := typeOf $value -}}
    {{- if eq $key "prometheus_client" }}
   - port: {{ trimPrefix ":" $value.listen | int64 }}
     targetPort: {{ trimPrefix ":" $value.listen | int64 }}
     name: "prometheus-client"
    {{- end }}
  {{- end -}}
  {{- end }}
  selector:
    app: {{ template "fullname"  .}}
{{- end -}}
```
