### ISSUE TITLE
Document convention around usage of image digests

### ISSUE THREAD

**Issue by jlegrone** [helm/charts#13449]
Related to https://github.com/helm/charts/issues/3011.

There has been some recent work to add a digest reference to the `image` object that is conventionally included in many charts.

An explanation of what image digests are and why they're useful is available here: https://success.docker.com/article/images-tagging-vs-digests.

Today, running `helm create mychart` results in a values file that contains:

```yaml
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
```

## Option A

The first proposal is to add a new `digest` field that overrides the `tag` field if present:

```yaml
image:
  repository: nginx
  tag: stable
  digest: sha256:d39d5dc009d238ac3e69156987e9d31d5ea33aa3e7cdc3e106d6b5cb757ca296
  pullPolicy: IfNotPresent
```

## Option B

A second option would be to reference digests directly in the tag field:

```yaml
image:
  repository: nginx
  tag: stable@sha256:d39d5dc009d238ac3e69156987e9d31d5ea33aa3e7cdc3e106d6b5cb757ca296
  pullPolicy: IfNotPresent
```

**Comment by scottrigby** [comment]
Once we agree on a best practice for this repo, we can track it in #3011, and add to the correct place (REVIEW_GUIDELINES etc).

**Comment by scottrigby** [comment]
Personally I'd love to see container image digests supported in charts by default. Interestingly most charts split up the image values by `registry` and `tag`, then combine them again in templates. If we just set the full image image as in the pod spec, this would be supported in charts OOTB 🤷‍♂ It seems funny to add this templating logic for pulling it apart, and then putting it back together again with either a `@` or `:` delimiter 🤔

**Comment by jlegrone** [comment]
I see significant positives for both options.

### Option A
- Indicates more clearly to chart users that digests are supported
- If a digest is specified, chart authors should always be able to set image pull policy to `IfNotPresent` in the template

### Option B
- Existing charts and charts created with `helm create` do not need to be updated
- Does not require the more involved templating of option A which would lead to lots of duplicated template logic between each chart, with the potential for divergent behaviors

Right now I'm leaning more towards B, but would be strongly in favor of documenting how image digests can be used (and potentially setting image tags to digests in `values.yaml` for charts in this repository).

**Comment by drastawi** [comment]
I agree B is a better option, but one significant advantage of A over B is that A can easily be implemented in a backwards compatible way.

**Comment by jlegrone** [comment]
>Something like `<image-name>:@sha256:d39d5dc009d238ac3e69156987e9d31d5ea33aa3e7cdc3e106d6b5cb757ca296` is not a valid docker reference AFAIK (and would not allow one to pull an image without a tag specified).

@drastawi you're right; I've amended the example in the issue description. Theoretically charts could be patched to also accept raw digests in addition to annotated digests using the [hasPrefix](http://masterminds.github.io/sprig/strings.html#hasprefix-and-hassuffix) function, but we'd run into the same problem of requiring patches everywhere.

**Comment by scottrigby** [comment]
@drastawi is right, only A above is backwards compatible on upgrade with existing values. B would be a breaking change, [requiring a MAJOR version bump](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#versioning).

What I suggested above would also be a breaking change. None of this is dictated by Helm, but are just conventions repeated to attempt consistency across charts in the helm/charts repo. When there's a good enough reason, they can be updated as needed. I'm not yet sure if supporting digests is a good enough reason (especially given our goal of moving charts from the monolith to distributed repos), but if we decide is is, we could follow a simpler pattern like this:

## Option C
`values.yaml`
```yaml
container:
  image: nginx:stable
  imagePullPolicy: IfNotPresent
```

Any template containing a `pod` spec:
```yaml
image: "{{ .Values.container.image }}"
```

Users could then override the full image without extra templating logic:
```console
helm install mychart/ --set container.image=nginx@sha256:05838c9a9204f377987bd87645026610ba4de67c7072fae7db1a437fe4ab8974
```

Whatever we agree on, it could be a good idea to update chartutil `helm create` command to help spread best practices for newly created charts.

**Comment by jlegrone** [comment]
@scottrigby one of my examples was incorrect and I removed it from the issue description. Here it is for posterity:

```yaml
image:
  repository: nginx
  tag: sha256:d39d5dc009d238ac3e69156987e9d31d5ea33aa3e7cdc3e106d6b5cb757ca296
  pullPolicy: IfNotPresent
```

That wouldn't work with existing charts, but the current example for option B does work without any changes. This is because it is possible to "annotate" image digests, so something like `nginx:v1.15@sha256:05838c9a9204f377987bd87645026610ba4de67c7072fae7db1a437fe4ab8974` is valid.

Unfortunately I haven't found any good documentation to link to on this, but as long as `something@sha256...` is passed in, we're good. Requiring annotated digests _could_ also be viewed as a feature, not a bug 😉but to be fair it's not exactly the same as supporting raw digests.

**Comment by kfox1111** [comment]
> Personally I'd love to see container image digests supported in charts by default. Interestingly most charts split up the image values by `registry` and `tag`, then combine them again in templates. If we just set the full image image as in the pod spec, this would be supported in charts OOTB man_shrugging It seems funny to add this templating logic for pulling it apart, and then putting it back together again with either a `@` or `:` delimiter thinking

Yeah, I kind of like the idea behind splitting up the values. it makes it very easy to switch out a tag. but it does not let you mirror the containers to your own mirror easily.

In my own charts I've started doing: https://github.com/pnnl-miscscripts/miscscripts/blob/master/charts/image-library-charts/build#L47-L76
server, prefix, org, repo and tag.
server being like 'docker.io'.
prefix defaulting to nothing but allowing tweaking the url just after the server. This can be useful for self hosting a repo under some ingress path.
org being the org that created it. so, like pnnl.
repo being the actual repo or container name. ipmitool, dhcp, etc.
and tag being the particular version/build.

This means, to copy a whole suite of containers to a local mirror, you may just have to tweak the server var. or you tweak server and org, but repo or tag.

With the way things are done now, you have to fetch the repo value, and start parsing it, trying to determine what the server part is, or the repo name, and seperate them so you can replace the server but not the repo...

Flatting it all the way down to image has some advantages, but makes mirroring / updating a build even harder.

**Comment by kfox1111** [comment]
I would prefer option A.

**Comment by drastawi** [comment]
Do we think we are aligned enough to edit the review guideline in line with option A? I opened up a pr https://github.com/helm/charts/pull/13451.

**Comment by jlegrone** [comment]
@drastawi I would prefer to wait until we've had a chance to discuss this issue on the next chart maintainers call on May 14th. You are welcome to join (details are in the #charts channel in the kubernetes slack)!

**Comment by jlegrone** [comment]
I think Option A actually turns out to be a breaking change if a default digest is ever provided by the chart. Given an existing user-defined `values.yaml` like this:

```yaml
image:
  repository: nginx
  tag: 1.15.12
```

And a new chart version with `values.yaml` containing:

```yaml
image:
  repository: nginx
  tag: stable
  digest: sha256:d39d5dc009d238ac3e69156987e9d31d5ea33aa3e7cdc3e106d6b5cb757ca296
```

The merged values that will be applied to create/upgrade a release will be:

```yaml
image:
  repository: nginx
  tag: 1.15.12
  digest: sha256:d39d5dc009d238ac3e69156987e9d31d5ea33aa3e7cdc3e106d6b5cb757ca296
```

Since the proposed `digest` field takes precedence over `tag`, the deployed image ends up being what is defined as the chart's default digest, _not_ the tag that users expected to be deployed for previous versions of the chart. At a minimum this would be a very subtle issue to debug when something goes wrong, but could also be a vector for deploying vulnerable images under the noses of existing chart users.
