### ISSUE TITLE
[stable/prometheus-operator] how to add additional labels to the default Prometheus alerts for kubernetes system alerts.

### ISSUE THREAD

**Issue by aliartiza75** [helm/charts#13457]
Hello everyone,

I am using `prometheus-operator` chart for monitoring. 

###  Problem Statement
I want to assign custom labels to default Prometheus alerts?

### What I did

I used `defautlRules.labels.kind` parameter to assign a label to Prometheus alerts but that label was applied to rules `metadata` level instead of individual rules. 

* Label value
```yaml
defaultRules:
   labels:
     testLabel: testing
```

* Applied values

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-kubernetes-resources
  labels:
    app: test
    
    chart: prometheus-operator-5.0.13
    release: "RELEASE-NAME"
    heritage: "Tiller"
    expose: "true"
    
    testLabel: testing
    
spec:
  groups:
  - name: kubernetes-resources
    rules:
    - alert: KubeCPUOvercommit
      annotations:
        message: Cluster has overcommitted CPU resource requests for Pods and cannot tolerate node failure.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit
      expr: |-
        sum(namespace_name:kube_pod_container_resource_requests_cpu_cores:sum)
          /
        sum(node:node_num_cpu:sum)
          >
        (count(node:node_num_cpu:sum)-1) / count(node:node_num_cpu:sum)
      for: 5m
      labels:
        severity: warning
```

* Instead, I want the label on this alert level like this:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-kubernetes-resources
  labels:
    app: test
    
    chart: prometheus-operator-5.0.13
    release: "RELEASE-NAME"
    heritage: "Tiller"
    expose: "true"
    

    
spec:
  groups:
  - name: kubernetes-resources
    rules:
    - alert: KubeCPUOvercommit
      annotations:
        message: Cluster has overcommitted CPU resource requests for Pods and cannot tolerate node failure.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit
      expr: |-
        sum(namespace_name:kube_pod_container_resource_requests_cpu_cores:sum)
          /
        sum(node:node_num_cpu:sum)
          >
        (count(node:node_num_cpu:sum)-1) / count(node:node_num_cpu:sum)
      for: 5m
      labels:
        severity: warning
        testLabel: testing
```
After looking at the template file I found out that there is no way to assign `custom label` to `alerts`

### Proposal
I want to change the structure of `defaultRules.rules.kubernetesResources` from `boolean` to `json` with following keys:

```yaml
defaultRules:
   rules:
       kubernetesResources:
           enabled: boolean
           labels:
               label1: label1Value
               label2: label2Value
```

* `enabled` key will be used to enable and disable the KubernetesResources alerts.
* `labels` keys values will be used to assign custom labels to alerts `labels` parameter.

I want to make the above changes for these alerts.

| Parameter | Description | Default |
| ----- | ----------- | ------ |
| `defaultRules.rules.kubeApiserver` | Create Api Server default rules| `true` |
| `defaultRules.rules.kubePrometheusNodeAlerting` | Create Node Alerting default rules| `true` |
| `defaultRules.rules.kubePrometheusNodeRecording` | Create Node Recording default rules| `true` |
| `defaultRules.rules.kubeScheduler` | Create Kubernetes Scheduler default rules| `true` |
| `defaultRules.rules.kubernetesAbsent` | Create Kubernetes Absent (example API Server down) default rules| `true` |
| `defaultRules.rules.kubernetesApps` | Create Kubernetes Apps  default rules| `true` |
| `defaultRules.rules.kubernetesResources` | Create Kubernetes Resources  default rules| `true` |
| `defaultRules.rules.kubernetesStorage` | Create Kubernetes Storage  default rules| `true` |
| `defaultRules.rules.kubernetesSystem` | Create Kubernetes System  default rules| `true` |

Kindly reply asap as this change is required for a task I am working on. 

Thank you
