### ISSUE TITLE
[stable/kong] Remove --default-backend-service if ingress controller >=0.4.0

### ISSUE THREAD

**Issue by cr1cr1** [helm/charts#13478]
**Describe the bug**
Using ingress controller image 0.4.0, pods will not start because --default-backend-service parameter was removed.

**Version of Helm and Kubernetes**:
- helm: v2.12.3
- kubernetes: v1.14.1

**Which chart**:
stable/kong

**What happened**:
Ingress controller got a new release: 0.4.0

**What you expected to happen**:
`--default-backend-service` should be removed if tag >= 0.4.0 so ingress controller pod could start

**How to reproduce it** (as minimally and precisely as possible):
Use tag 0.4.0 in values.yaml for ingressController:
```yaml
ingressController:
  enabled: true
  image:
    repository: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller
    tag: 0.4.0
```

**Anything else we need to know**:
