### ISSUE TITLE
[stable/redis] persistence does not work

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#13503]
**Describe the bug**

State is not persisted across reboots although `.Values.persistence` is enabled and a pvc is mounted.

**Version of Helm and Kubernetes**:
latest GKE and latest helm

**Which chart**:
redis 6.4.5 and beyond, have not confirmed behaviour with older versions of chart, i do remember it working as expected in the past however
cluster mode is disabled
persistence is enabled

**What happened**:

i enable persistence (pvc mounted on `/data` by chart)
i create a key
i restart the redis-master pod
and the key no longer exists

**What you expected to happen**:
i expect the key to persist across restarts

**How to reproduce it** (as minimally and precisely as possible):
install redis as a dependency in a chart with these options
```
redis:
  enabled: true
  cluster:
    enabled: false
  networkPolicy:
    enabled: true
    allowExternal: false
  serviceAccount:
    create: true
  rbac:
    create: true
  usePassword: true
  metrics:
    enabled: true
```

**Anything else we need to know**:
no `dump.rdb` present in `/data`
```
redis-master-0:/data$ ls
lost+found
```
Also logs do not indicate any `bgsave` actions
