### ISSUE TITLE
[stable/wordpress] mariadb is always insstalled

### ISSUE THREAD

**Issue by heroic** [helm/charts#13513]
**Describe the bug**
When installing wordpress, even if mariadb.enabled is set to false, statefulset for mariadb is always installed. It would appear that the commited requirements.lock file might be causing this.

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

```
1.12.7-gke.10
```

**Which chart**:
stable/wordpress

**What happened**:
Mariadb gets installed

**What you expected to happen**:
Mariadb should not be installed

**How to reproduce it** (as minimally and precisely as possible):
set mariadb.enabled to false, and install chart. StatefulSet mariadb is created.

**Anything else we need to know**:
No

**Comment by tompizmor** [comment]
Hello @heroic,

I tried to reproduce the issue but I couldn't. Can you provide the exact command you are using to install the chart and the chart version?

I just tested the WordPress chart version 5.9.0 with this command and MariaDB resources were not created.

```
helm install --name wordpress --set mariadb.enabled=false stable/wordpress
```

**Comment by heroic** [comment]
This is my requirements.yaml
```
dependencies:
- name: wordpress
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 5.9.0
```

This is my values.yaml
```
wordpress:
  mariadb:
    enabled: false
  externalDatabase:
    host: ip
    user: username
    password: password
    database: dbname
```

**Comment by tompizmor** [comment]
I see you are using WordPress as a dependency. So in order to disable MariaDB chart, you should use this values.yaml file.

```
mariadb:
  enabled: false
wordpress:
  mariadb:
    enabled: false
  externalDatabase:
    host: ip
    user: username
    password: password
    database: dbname
```
The condition to enable or disable MariaDB in WordPress chart is `mariadb.enabled` and according to [helm chart docs](https://helm.sh/docs/developing_charts/#tags-and-condition-fields-in-requirements-yaml
), this condition is evaluated from the top parent's values (which is the parent of the WordPress chart)

Apart from that, you also need to specify `mariadb.enabled=false` in the WordPress chart context so it is configured properly.

> Condition - The condition field holds one or more YAML paths (delimited by commas). If this path exists in the top parent’s values and resolves to a boolean value, the chart will be enabled or disabled based on that boolean value. Only the first valid path found in the list is evaluated and if no paths exist then the condition has no effect.
