### ISSUE TITLE
Failed to install ambassador in single namespace mode

### ISSUE THREAD

**Issue by emlin** [helm/charts#13557]
I followed the instruction to install ambassador in single namespace mode, but helm installation always fail with this error:
```
Error: release ambassador failed: roles.rbac.authorization.k8s.io "ambassador" is forbidden: attempt to grant extra privileges: [{[get] [] [namespaces] [] []} {[list] [] [namespaces] [] []} {[watch] [] [namespaces] [] []}] user=&{system:serviceaccount:vmc-pdx-default:tiller b8c7bb31-d714-11e8-a101-021687ad4004 [system:serviceaccounts system:serviceaccounts:vmc-pdx-default system:authenticated] map[]} ownerrules=[{[get watch list] [storage.k8s.io] [storageclasses] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]} {[use] [policy] [podsecuritypolicies] [default] []} {[*] [] [pods endpoints services replicationcontrollers secrets configmaps persistentvolumeclaims serviceaccounts] [] []} {[*] [] [pods/log pods/exec pods/attach pods/portforward] [] []} {[get watch list] [] [resourcequotas] [] []} {[*] [apps] [deployments statefulsets daemonsets replicasets] [] []} {[*] [extensions] [daemonsets ingresses deployments replicasets] [] []} {[*] [batch] [jobs cronjobs] [] []} {[*] [rbac.authorization.k8s.io] [rolebindings roles] [] []} {[*] [policy] [poddisruptionbudgets] [] []} {[get watch list] [] [namespaces] [vmc-pdx-system] []}] ruleResolutionErrors=[]
```
I set the following values in values.yaml file:
```
rbac:
  # Specifies whether RBAC resources should be created
  create: true
  namespaced: true
scope:
  # tells Ambassador to only use resources in the namespace or namespace set by namespace.name
  singleNamespace: true
```

The solution for me worked, is to remove the `namespace` service requirement in the template rbac.yaml file at here: https://github.com/helm/charts/blob/master/stable/ambassador/templates/rbac.yaml#L18

Can you help to fix this issue?
