### ISSUE TITLE
[stable/elastic-stack] cant start stack with 1 master 

### ISSUE THREAD

**Issue by damouse** [helm/charts#13558]
**Describe the bug**
I can't start an elastic-stack with default configuration except that I'm running a single master node. None of the pods brought up by elasticsearch can reach `elasticsearch-discovery`. 

I understand 1 master node erodes HA, but I'm currently testing and don't have the resources to deploy more than that in this environment.

**Version of Helm and Kubernetes**:
Helm: v2.13.1
Kubernetes: v1.11.9

**Which chart**: elastic-stack

**What happened**: Can't start the cluster.

**What you expected to happen**: The cluster to start with mostly default values and a single master node.

**How to reproduce it** (as minimally and precisely as possible): See comments below. 

**Anything else we need to know**:

I'm installing the stack with:

```
helm install -f elk_overrides.yaml --set rbac.create=true --name elk stable/elastic-stack
```

Contents of `elk_overrides.yaml`:

```
elasticsearch:
  client:
    replicas: 1
    heapSize: "256m"
  master:
    replicas: 1
    heapSize: "256m"
    podDisruptionBudget:
        minAvailable: 1
  data:
    replicas: 1
    heapSize: "512m"
  cluster:
    env:
      MINIMUM_MASTER_NODES: "1"
kibana:
  files:
    kibana.yml:
      elasticsearch.url: http://elk-elasticsearch-client:9200
```

Log output from `elk-elasticsearch-master-0`:

```
[2019-05-06T22:23:36,879][INFO ][o.e.b.BootstrapChecks    ] [elk-elasticsearch-master-0] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2019-05-06T22:23:36,950][WARN ][o.e.d.z.UnicastZenPing   ] [elk-elasticsearch-master-0] failed to resolve host [elk-elasticsearch-discovery]
java.net.UnknownHostException: elk-elasticsearch-discovery: Name or service not known
```

Log output from `elk-elasticsearch-data-0`:

```
[2019-05-06T22:23:46,237][WARN ][o.e.d.z.UnicastZenPing   ] [elk-elasticsearch-data-0] failed to resolve host [elk-elasticsearch-discovery]
java.net.UnknownHostException: elk-elasticsearch-discovery
```

`$ kubectl describe service elk-elasticsearch-discovery`:

```
Name:              elk-elasticsearch-discovery
Namespace:         default
Labels:            app=elasticsearch
                   chart=elasticsearch-1.22.0
                   component=master
                   heritage=Tiller
                   release=elk
Annotations:       <none>
Selector:          app=elasticsearch,component=master,release=elk
Type:              ClusterIP
IP:                None
Port:              <unset>  9300/TCP
TargetPort:        transport/TCP
Endpoints:         100.96.7.45:9300
Session Affinity:  None
Events:            <none>
```

I get the feeling I'm doing something stupid, but it feels like the steps I'm using here aren't too far removed from the default instructions.
