### ISSUE TITLE
[stable/ambassador] imagePullSecrets is buggy

### ISSUE THREAD

**Issue by Cellebyte** [helm/charts#13614]
**Describe the bug**

The template is misbehaving when specifying imagePullSecrets.

**Version of Helm and Kubernetes**:

HELM: 
 * Client: v2.11.0
 * Server: v2.11.0

Kubernets:
 * Client: v1.13.1
 * Server: v1.10.11

**Which chart**:
stable/ambassador

**What happened**:
No deployment happend and a template error ocurred.

**What you expected to happen**:
Installation of ingress/ambassador.

**How to reproduce it** (as minimally and precisely as possible):
```yaml
replicaCount: 2
daemonSet: true
namespace:
  name: ingress-ambassador
imagePullSecrets:
  - secret_for_docker_registry
```

**Anything else we need to know**:
```bash
Error: UPGRADE FAILED: v1.DaemonSet.Spec: v1.DaemonSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.ImagePullSecrets: []v1.LocalObjectReference: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|ecrets":["secret_for_docker_registry"|..., bigger context ...|],"dnsPolicy":"ClusterFirst","imagePullSecrets":["secret_for_docker_registry"],"nodeSelector":{"node-role.kubernetes.|...

```
