### ISSUE TITLE
prometheus-operator: Grafana: Unable to Log in, Failed to get settings

### ISSUE THREAD

**Issue by msschl** [helm/charts#13621]
**What happened?**
Running grafana with helm chart prometheus-operator-4.1.1 app version 0.29.0

**Did you expect to see**
Login Page

**What did you see instead? Under which circumstances?**
Error Page:
```
Grafana / Server Error
Sadly something went wrong
Failed to get settings

Check the Grafana server logs for the detailed error message.
```

**How to reproduce it (as minimally and precisely as possible)**:
Here is my helm chart configuration, which overrides the default provided values.yaml:
```
defaultRules:
  create: false

alertmanager:
  enabled: false

grafana:
  adminPassword: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "public"
    hosts:
      - metrics.domain.local
    tls:
      - secretName: public/domain-local-tls
        hosts:
          - metrics.domain.local
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi

prometheus-node-exporter:
  tolerations:
    - effect: "NoSchedule"
      key: "node-role.kubernetes.io/master"

commonLabels:
  prometheus: prometheus-monitoring

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "public"
    hosts:
      - prometheus.domain.local
    tls:
      - secretName: public/domain-local-tls
        hosts:
          - prometheus.domain.local

  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: prometheus-monitoring
```

**Environment**

* Prometheus Operator version:
version: 5.5.1
appVersion: 0.29.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
kubeadm

* Prometheus Operator Logs:
```
 t=2019-05-08T09:11:06+0000 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="disk I/O error"
t=2019-05-08T09:11:08+0000 lvl=eror msg="failed to search for dashboards" logger=provisioning.dashboard type=file name=default error="disk I/O error" 
` t=2019-05-08T09:11:12+0000 lvl=eror msg="Failed to start session" logger=context error="mkdir /var/lib/grafana/sessions: input/output error"
t=2019-05-08T09:11:12+0000 lvl=eror msg="Failed to get settings" logger=context userId=0 orgId=0 uname= error="disk I/O error"
t=2019-05-08T09:11:12+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login status=500 remote_addr=172.17.42.46 time_ms=19 size=1727 referer= 
```

**Which chart**:
stable/prometheus-operator
