### ISSUE TITLE
[incubator/kafka] Service type NodePort for external use broken

### ISSUE THREAD

**Issue by ncrothe** [helm/charts#13713]
**Describe the bug**
In it's current stage the external service to make kafka available outside the cluster via NodePort is broken. Specifically, there is an issue with the template incubator/kafka/templates/service-brokers-external.yaml. For external.type:NodePort the service attribute targetPort gets expressed with $externalListenerPort (which is 31090+ by default), but it needs to point to the container's port (`9092`). As far as I understand, this should also be the case for other service types.

**Version of Helm and Kubernetes**:
Helm: v2.12.3
Kubernetes 1.11 (EKS)

**Which chart**:
incubator/kafka

**What happened**:
Kafka is not available outside the cluster. `kafkacat -b kafka.cluster.local:31090 -L` returns `% ERROR: Failed to acquire metadata: Local: Broker transport failure`

**What you expected to happen**:
Kafka should listen to e.g. `kafkacat -b kafka.cluster.local:31090 -L` should return something indicating a connection.

**How to reproduce it** (as minimally and precisely as possible):
Configure helm chart as needed, use
```
external:
  enabled: true
  type: NodePort
```

**Anything else we need to know**:
I was able to fix it locally for my use case by pointing targetPort to 9092. Might be able to whip together a Pull Request later, but not entirely sure about non-NodePort requirements.

**Comment by ncrothe** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#is-the-service-correct would indicate that targetPort should always be the container's containerPort.

**Comment by ncrothe** [comment]
Nevermind, I simply did not understand what's happening. If we tie the service's NodePort to the containers 9092, traffic will be treated as internal and broadcast internal endpoints which fails the rest.

**Comment by GaniMarquez** [comment]
Hi @ncrothe, can you kindly share your `values.yml` I'm currently stuck with this issue and would really use your help. Thank you.

**Comment by ncrothe** [comment]
After much trial and error we ended up with this fairly short values.yml:
```
external:
  enabled: true
  domain: mydomain.com
  type: NodePort #redundant, because default, added for clarity
configurationOverrides:
  "advertised.listeners": |-
    EXTERNAL://kafka.mydomain.com:$((31090 + ${KAFKA_BROKER_ID}))
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
persistence:
  enabled: true
  storageClass: gp2
```
