### ISSUE TITLE
[stable/elasticsearch] client replica is override by replicaset annotations of client deployment

### ISSUE THREAD

**Issue by vikranttkamble** [helm/charts#13902]
Hi,

When I set client replica to 1, I noticed Relicaset annotations overrides it and minimum 2 pods are created. There is provision to update podAnnotation but Relicaset annotations overrides it.

```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-05-16T08:59:22Z
  generation: 4
  labels:
    app: elasticsearch
    component: client
```
