### ISSUE TITLE
[stable/sentry] Sentry's postgresql and redis can't bound pvc to pv

### ISSUE THREAD

**Issue by WandersonAlves** [helm/charts#13934]
**Describe the bug**
I'm trying to deploy this chart in my cluster with the following command:
`helm install --name e3-sentry --namespace sentry --wait stable/sentry --set persistence.storageClass=manual`

**Version of Helm and Kubernetes**:
Kubernetes:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6+IKS", GitCommit:"ac5f7341d5d0ce8ea8f206ba5b030dc9e9d4cc97", GitTreeState:"clean", BuildDate:"2019-05-09T13:26:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Helm:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Which chart**:
stable/sentry

**What happened**:
The pods related to postgresql and redis never initializes because their pvc's don't bound to any unbound pv existent

**What you expected to happen**:
Postgresql pvc bound to volume

**How to reproduce it** (as minimally and precisely as possible):

- Create three pv's:
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: e3-sentry
spec:
  capacity:
    storage: 10Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/sentry"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: e3-sentry-postgresql
  labels:
    app: postgresql
    release: e3-sentry
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgresql"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: e3-sentry-redis
  labels:
    app: redis
    release: e3-sentry
spec:
  capacity:
    storage: 2Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"
```
- Run `helm install --name e3-sentry --namespace sentry --wait stable/sentry --set persistence.storageClass=manual`

- `kubectl describe pvc/<pvc-name>` and see the error

**Anything else we need to know**:

- This cluster runs on IBM Cloud.
- I'm trying to create volume to hostPath
- Postgresql pod describe:
```
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  e3-sentry-postgresql
    ReadOnly:   false
  default-token-vv6zx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-vv6zx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  20s (x11 over 4m45s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
```
- `kube get pvc`
```
→ kube get pvc                                                                                                                                                                       [abbccca]
NAME                                  STATUS    VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS   AGE
e3-sentry                             Bound     e3-sentry   10Gi       RWO            manual         5m25s
e3-sentry-postgresql                  Pending                                                        5m25s
redis-data-e3-sentry-redis-master-0   Pending                                                        5m25s
```
- `kube describe pvc/e3-sentry-postgresql`
```
Name:          e3-sentry-postgresql
Namespace:     sentry
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=postgresql
               chart=postgresql-0.18.0
               heritage=Tiller
               release=e3-sentry
Annotations:   helm.sh/resource-policy: 
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason         Age                  From                         Message
  ----       ------         ----                 ----                         -------
  Normal     FailedBinding  10s (x25 over 6m3s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  e3-sentry-postgresql-5c48d7c7f6-gb9v8
```
- `kube get pv`
```
NAME                   CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM              STORAGECLASS   REASON   AGE
e3-sentry              10Gi       RWO            Retain           Bound       sentry/e3-sentry   manual                  6m55s
e3-sentry-postgresql   5Gi        RWO            Retain           Available                      manual                  6m54s
e3-sentry-redis        2Gi        RWO            Retain           Available                      manual                  6m54s
```
- `kube describe pv/e3-sentry-postgresql`
```
Name:            e3-sentry-postgresql
Labels:          app=postgresql
                 release=e3-sentry
Annotations:     kubectl.kubernetes.io/last-applied-configuration:
                   {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"app":"postgresql","release":"e3-sentry"},"name":"e3-s...
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    manual
Status:          Available
Claim:           
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        5Gi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/data/postgresql
    HostPathType:  
Events:            <none>
```

**Comment by nvtkaszpir** [comment]
please run `kubect get sc`
also see `Events:
  Type       Reason         Age                  From                         Message
  ----       ------         ----                 ----                         -------
  Normal     FailedBinding  10s (x25 over 6m3s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  e3-sentry-postgresql-5c48d7c7f6-gb9v8`

**Comment by WandersonAlves** [comment]
Hi @nvtkaszpir 
`kubectl get sc` outputs these storage classes

```
NAME                      PROVISIONER        AGE
default                   ibm.io/ibmc-file   6d11h
ibmc-file-bronze          ibm.io/ibmc-file   6d11h
ibmc-file-custom          ibm.io/ibmc-file   6d11h
ibmc-file-gold            ibm.io/ibmc-file   6d11h
ibmc-file-retain-bronze   ibm.io/ibmc-file   6d11h
ibmc-file-retain-custom   ibm.io/ibmc-file   6d11h
ibmc-file-retain-gold     ibm.io/ibmc-file   6d11h
ibmc-file-retain-silver   ibm.io/ibmc-file   6d11h
ibmc-file-silver          ibm.io/ibmc-file   6d11h
```

I changed my volumes to use the `default` class, but the pvcs didn't bound to the volumes

**Comment by nvtkaszpir** [comment]
Looks like you did not define storageclass `manual`, thus k8s has no idea how to match pv with pvc.

**Comment by WandersonAlves** [comment]
I changed my volume to use the `default` storageClass that is available on my `kubectl get sc`

```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: e3-sentry-postgresql
  labels:
    app: postgresql
    release: e3-sentry
spec:
  storageClassName: default
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgresql"
```

And the pvcs created by the chart doesn't bound to my volumes.
