### ISSUE TITLE
[stable/rabbitmq] Created secrets are not valid enviroment variable names

### ISSUE THREAD

**Issue by dariovillar** [helm/charts#1394]
**Is this a request for help?**:

NO

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
rabbitmq 0.5.3

**What happened**:
The name of the variables stored in the secret (rabbitmq-erlang-cookie, rabbitmq-password) by the chart on install are not valid enviroment variables names.

**What you expected to happen**:
The stored variables should have enviroment variable friendly names in order to use the secret in an envfrom section to inject the secret as enviroment variables

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/rabbitmq --name rabbitmq

Insert in a file.yaml
``` yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dapi-test-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dapi-test-pod
    spec:
      containers:
        - name: test-container
          image: gcr.io/google_containers/busybox
          command: [ "/bin/sh", "-c", "env" ]
          envFrom:
            - secretRef:
                name : rabbitmq-rabbitmq
```
kubectl create -f file.yaml
kubectl describe pod dapi-test-deployment-xxxxxxxxxxxxx

**Anything else we need to know**:
The error I'm seeing is:
	Warning	InvalidEnvironmentVariableNames	Keys [rabbitmq-erlang-cookie, rabbitmq-password] from the EnvFrom secret default/rabbitmq-rabbitmq were skipped since they are considered invalid environment variable names.
