### ISSUE TITLE
stable/grafana extraContainer config is broken

### ISSUE THREAD

**Issue by HaveFun83** [helm/charts#13986]
**Describe the bug**
When the value extraContainer is used. the chart don't get deployed successfully.
```
YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 104: did not find expected '-' indicator
```
**Version of Helm and Kubernetes**:
k8s: 1.14.1
helm: v2.13.1

**Which chart**:
stable/grafana

**What happened**:

**What you expected to happen**:
The chart should be deployed successful with the extraContainer config

**How to reproduce it** (as minimally and precisely as possible):
enable the extraContainer config 

**Anything else we need to know**:
fixed by changing the templates/deployment.yaml
```diff
--- a/stable/grafana/templates/deployment.yaml
+++ b/stable/grafana/templates/deployment.yaml
@@ -290,8 +290,8 @@ spec:
 {{ toYaml .Values.readinessProbe | indent 12 }}
           resources:
 {{ toYaml .Values.resources | indent 12 }}
-{{- if .Values.extraContainers }}
-{{ toYaml .Values.extraContainers | indent 8}}
+{{- with .Values.extraContainers }}
+{{ tpl . $ | indent 8 }}
 {{- end }}
     {{- with .Values.nodeSelector }}
       nodeSelector:
```

**Comment by HaveFun83** [comment]
can somebody help here?

**Comment by bailsman** [comment]
Could you post your config as well?

**Comment by grstein** [comment]
Please, accept the PR from @HaveFun83, I'm having the same problem.

**Comment by HaveFun83** [comment]
> Could you post your config as well?

Sure:
```
  extraContainers: |
    - name: proxy
      image: keycloak/keycloak-gatekeeper:6.0.1
      args:
      - --client-id=grafana
      .. omit more args ...
```

**Comment by grstein** [comment]
> Could you post your config as well?

I have this values.yaml:

`
extraContainers: |
  - name: proxy
    image: quay.io/gambol99/keycloak-proxy:latest
    args:
    - -discovery-url=https://sso.lab.xxx.xxx.br/auth/realms/laboratory
    - -client-id=grafana
    - -client-secret=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX
    - -email-domain=xxx.xxx.br
    - -http-address=http://0.0.0.0:4181
    - -upstream-url=http://127.0.0.1:3000
    ports:
      - name: proxy-web
        containerPort: 4181
`
which renders to:
`
        |
          - name: proxy
            image: quay.io/gambol99/keycloak-proxy:latest
            args:
            - -discovery-url=https://sso.lab.xxx.xxx.br/auth/realms/laboratory
            - -client-id=grafana
            - -client-secret=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX
            - -email-domain=xxx.xxx.br
            - -http-address=http://0.0.0.0:4181
            - -upstream-url=http://127.0.0.1:3000
            ports:
              - name: proxy-web
                containerPort: 4181
`

Thus, leading to this message:

`Error: YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 103: did not find expected '-' indicator`

**Comment by grstein** [comment]
> Could you post your config as well?

I have this values.yaml:

```
extraContainers: |
  - name: proxy
    image: quay.io/gambol99/keycloak-proxy:latest
    args:
    - -discovery-url=https://sso.lab.xxx.xxx.br/auth/realms/laboratory
    - -client-id=grafana
    - -client-secret=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX
    - -email-domain=xxx.xxx.br
    - -http-address=http://0.0.0.0:4181
    - -upstream-url=http://127.0.0.1:3000
    ports:
      - name: proxy-web
        containerPort: 4181
```
which renders to:
```
        |
          - name: proxy
            image: quay.io/gambol99/keycloak-proxy:latest
            args:
            - -discovery-url=https://sso.lab.xxx.xxx.br/auth/realms/laboratory
            - -client-id=grafana
            - -client-secret=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX
            - -email-domain=xxx.xxx.br
            - -http-address=http://0.0.0.0:4181
            - -upstream-url=http://127.0.0.1:3000
            ports:
              - name: proxy-web
                containerPort: 4181
```

Thus, leading to this message:
```
Error: YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 103: did not find expected '-' indicator
```
