### ISSUE TITLE
RBAC rule error when deploying an instance of prometheus in another namespace

### ISSUE THREAD

**Issue by cyperplex** [helm/charts#14001]
Hi,

Ive deployed the operator and via HELM into my cluster successfully and its working with the out-of the box components .

Now when i deploy an instance via the operator into another name space to monitor application specific metrics, i get an error with permissions.

ie

level=error ts=2019-05-20T10:47:37.700320466Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:300: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:test-namespace:default" cannot list endpoints in the namespace "test-namespace""
level=error ts=2019-05-20T10:47:38.701151262Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:test-namespace:default" cannot list pods in the namespace "test-namespace""
level=error ts=2019-05-20T10:47:38.707869372Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:300: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:test-namespace:default" cannot list endpoints in the namespace "test-namespace""
level=error ts=2019-05-20T10:47:38.707885891Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:301: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:test-namespace:default" cannot list services in the namespace "test-namespace""
level=error ts=2019-05-20T10:47:39.70255881Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:test-namespace:default" cannot list pods in the namespace "test-namespace""

I created the application instance of prometheus with the following configuration.
```yml
apiVersion: v1
kind: Service
metadata:
name: prometheus-test
labels:
service: prometheus-test-instance-service
application: test
spec:
ports:

    port: 9090
    name: http
    selector:
    application: test

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
name: prometheus-test-instance
namespace: test
labels:
application: test
spec:
replicas: 1
serviceMonitorSelector:
matchLabels:
application: test
ruleSelector:
matchLabels:
role: prometheus-rulefiles-test
namespaceSelector:
namespace: test
containers:
resources:
limits:
cpu: 200m
memory: 100Mi
requests:
cpu: 100m
securityContext:
runAsNonRoot: true
runAsUser: 65534
serviceAccountName: prometheus

alerting:
alertmanagers:
- namespace: test
name: alertmanager-main
port: web
```
By default i set via the Helm values to set the service account for the RBAC rules to be named prometheus.

Do you know what extra configuration i need to add to the above file to configure it to inherit the permissions of the account created by the operator. Which has rights to all namespaces.

Thanks

**Comment by cyperplex** [comment]
Ive trace the problem to be the deployment via operator of the Prometheus instance within the application name space. The issue is the Prometheus pods spun up via operator is attempting to use the default service account for accessing the Kubeneteies API to access the  endpoints being scraped.  I then ran the following to create a service account and permissions 
apiVersion: rbac.authorization.k8s.io/v1beta1 
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints 
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"] 
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: prometheus
  namespace: test-instance
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus 
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: test-instance


Then added in the following to the CRD request for the prom instance:
apiVersion: v1  
kind: Service
metadata:
  name: prometheus-mapviewglobal
  labels:
    service: prometheus-mapview-global-service
    application: mapviewglobal
spec:
  ports:
  - port: 9090
    name: http
  selector:
    application: mapviewglobal

apiVersion: monitoring.coreos.com/v1
kind: Prometheus 
metadata:
  name: prometheus-mapview-global
  namespace: test-instance
  labels:
    application: mapviewglobal
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
        application: mapviewglobal 
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles-mapviewglobal
  namespaceSelector:
     namespace: test-instance
  spec:
    serviceAccountName: prometheus 
  containers:
  resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
  alerting:
    alertmanagers:
      - namespace: test-instance
        name: alertmanager-main
        port: web

Still getting the same error from the Prometheus pod:


level=error ts=2019-05-21T10:38:41.772740031Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:test-instance:default\" cannot list pods in the namespace \"test-instance\""
level=error ts=2019-05-21T10:38:42.757423222Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:301: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:test-instance:default\" cannot list services in the namespace \"test-instance\""
level=error ts=2019-05-21T10:38:42.768011753Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:300: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:test-instance:default\" cannot list endpoints in the namespace \"test-instance\""
level=error ts=2019-05-21T10:38:42.768938688Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:test-instance:default\" cannot list pods in the namespace \"test-instance\""

Its still attempting to access the api via the default service account

**Comment by cyperplex** [comment]
Fixed by  ensuring you create the rbac configuration for the prom server you are spining up using the prometheus crd and specifiying the serviceAccountName to match within the prometheus spec.  

ie 

**Rbac:**
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: prometheus

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints 
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"] 
  verbs: ["get"]

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects: 
- kind: ServiceAccount
  name: prometheus
  namespace: test

**Prometheus:** 

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-test
  namespace: test
  labels:
    application: test
spec:
  replicas: 1
  serviceAccountName: prometheus 

Read:

https://github.com/coreos/prometheus-operator/tree/master/example/rbac

**Comment by NickLarsenNZ** [comment]
@cyperplex, are you able to edit your posts above with code fences?

~~~md
```yml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
```
~~~

It's quite hard to look at as plain text without indentation, etc...
