### ISSUE TITLE
[stable/mysqldump] Backup multiple dbs but not all

### ISSUE THREAD

**Issue by fbongiovanni29** [helm/charts#14064]
Ability to back up multiple databases but not all of them using `mysql.db`. The idea would be to make the `mysql` key an array of databases and back up each one specified. Example:

```yaml
mysql:
  - host:
     username: root
     password:
     port: 3306
      db: dbname1
  - host:
     username: root
     password:
     port: 3306
      db: dbname2
```

The problem is I have multiple MySQL databases I'd like backups of but not all of them

Solution would be to allow an array of databases and dump each

Alternatives for me would be to either just back up all instead or build something custom

I could probably open up a PR with the functionality myself if this feature will be added
