### ISSUE TITLE
[incubator/cassandra] Pods CrashLoopBackOff Using configmap

### ISSUE THREAD

**Issue by stephenh1991** [helm/charts#14098]
**Describe the bug**
When adding the following config map:
```
configOverrides:
  cassandra.yaml: |
    auto_bootstrap: false
    cluster_name: staging
    endpoint_snitch: GossipingPropertyFileSnitch
```
Pods will not start and log the following output: 
`chown: changing ownership of '/etc/cassandra/cassandra.yaml': Read-only file system`
**Version of Helm and Kubernetes**:
helm 2.11
kubernetes: 1.11.5

**Which chart**:
incubator/cassandra

**What happened**:
Added config map which caused pods to crash on start

**What you expected to happen**:
Config map to be added and successfully start the pod.

**How to reproduce it** (as minimally and precisely as possible):
Add something similar to the configOverrides:

```
configOverrides:
  cassandra.yaml: |
    auto_bootstrap: false
    cluster_name: staging
    endpoint_snitch: GossipingPropertyFileSnitch
```
**Anything else we need to know**:
