### ISSUE TITLE
[stable/redis] Template error when Slave persistence is set to false

### ISSUE THREAD

**Issue by KathigitAnguras** [helm/charts#14115]
**Describe the bug**
When disabling persistence for Slave, the StatefulSet template fails to define the volume "redis-data" with emptyDir. This will cause the pod to fail as /data is not found. Master does not have the same issue.

**Version of Helm and Kubernetes**:
Kube: 1.13.5, latest helm

**Which chart**:
stable/redis:8.0.1

**What happened**:
Pod failed after deployment. Kubernetes reports the following:
>create Pod blabla-slave-0 in StatefulSet blabla-slave failed error: Pod "blabla-slave-0" is invalid: spec.containers[0].volumeMounts[1].name: Not found: "redis-data"

**What you expected to happen**:
For slave to mount the "redis-data" volume with an emptyDir. Both master and slave should work without persistence.

**How to reproduce it** (as minimally and precisely as possible):
install redis as a dependency in a chart with these options:
```
redis:
  enabled: true
  usePassword: false  
  redisPort: 6379
  persistence:
    enabled: false
  cluster:
    enabled: true
    slaveCount: 1
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  sentinel:
    enabled: false
  networkPolicy:
    enabled: false      
  serviceAccount:
    create: false  
  rbac:
    create: false  
  metrics:
    enabled: false
```

**Anything else we need to know**:
