### ISSUE TITLE
How can monitor the matrics of kafka 

### ISSUE THREAD

**Issue by abhi-dwivedi** [helm/charts#14117]
Hi have already enabled the jmx exporter and kafka-exporter which deployed the kafka-exporter pod on my one of namespace.

Now i have deployed Prometheus-operator in monitoring name space now how can i get the mertics on my Prometheus and then grafana.

**Comment by vsliouniaev** [comment]
You will need to set up `servicemonitor`s to make prometheus scrape the exporters. Please see the [documentation in the coreos/prometheus-operator repo](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/running-exporters.md)

**Comment by deepaksood619** [comment]
Or you can add a scrape target for kafka in additionalScrapeConfigs in prometheus operator [here](https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L1370).

Scrape configuration -
```
additionalScrapeConfigs:
  - job_name: 'kafka'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['ke-cp-zookeeper.kafka:5556', 'ke-cp-kafka.kafka:5556', 'ke-cp-kafka-connect.kafka:5556', 'ke-cp-kafka-rest.kafka:5556', 'ke-cp-schema-registry.kafka:5556']
```

**Comment by ashishxooa** [comment]
The incubator/kafka documentation says that is supports auto-configuration of Promethues explorter and alert manager. 

This is an excerpt from my helm value file. 
```

prometheus:
  ## Prometheus JMX Exporter: exposes the majority of Kafkas metrics
  jmx:
    enabled: true

  ## Prometheus Kafka Exporter: exposes complimentary metrics to JMX Exporter
  kafka:
    enabled: true

  operator:
    enabled: true

  operator:
    serviceMonitor:
      selector: { k8s-app: prometheus }
```

So it should automatically register to the Prometheus operator. This seems to be not working. Anyone has any idea for this?
