### ISSUE TITLE
[stable/redis-ha] Pods restart frequently

### ISSUE THREAD

**Issue by candidoma** [helm/charts#14118]
Hi,
i installed the latest redis-ha chart, but after a while i see pods restart count is not zero.
``` bash
$ kubectl get pods -n redis-ha-2
NAME                  READY   STATUS    RESTARTS   AGE
redis-ha-2-server-0   2/2     Running   37         38d
redis-ha-2-server-1   2/2     Running   52         39d
redis-ha-2-server-2   2/2     Running   25         18d
```

No logs show me why pods restart. I suppose process exit and pod restart.
No kubernetes events.

This is the pod describe where i can see the termination error, but is not clear for me
``` yaml
    State:          Running
      Started:      Fri, 24 May 2019 09:18:16 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 23 May 2019 09:59:10 +0200
      Finished:     Fri, 24 May 2019 09:18:15 +0200
```
How i can debug or understand the exit error?
There's any workaround?

Kubectl version :
``` bash
> kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Helm version :
``` bash
> helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

StatefuleSet

``` yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: redis-ha
    chart: redis-ha-3.3.3
    heritage: Tiller
    release: redis-ha
  name: redis-ha-server
  namespace: redis-ha
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-ha
      release: redis-ha-2
  serviceName: redis-ha-2
  template:
    metadata:
      annotations:
        checksum/init-config: 473423e6b4720521d6c51cc7d7d0943946d8466f5397a4d52596372b8dfe2f92
        checksum/probe-config: 2fac99ab3cbc364532f511cb76fb826fb5f4c6ff38a0e7097160e58d1f37cc42
      labels:
        app: redis-ha
        release: redis-ha-2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: redis-ha
                  release: redis-ha-2
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: redis-ha
                release: redis-ha-2
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - /data/conf/redis.conf
        command:
        - redis-server
        image: redis:5.0.3-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - /probes/readiness.sh
            - "6379"
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - /probes/readiness.sh
            - "6379"
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /probes
          name: probes
      - args:
        - /data/conf/sentinel.conf
        command:
        - redis-sentinel
        image: redis:5.0.3-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - /probes/readiness.sh
            - "26379"
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: sentinel
        ports:
        - containerPort: 26379
          name: sentinel
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - /probes/readiness.sh
            - "26379"
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /probes
          name: probes
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - /readonly-config/init.sh
        command:
        - sh
        env:
        - name: SENTINEL_ID_0
          value: 52665e1efda8b130ae27802f1dad738d0296a5d8
        - name: SENTINEL_ID_1
          value: 1ed8da0bfbbad0711bbc8c98cf88ed93f24e7c6e
        - name: SENTINEL_ID_2
          value: 9658f2bbe6417f357b2d412fcb88180303ae6f8e
        image: redis:5.0.3-alpine
        imagePullPolicy: IfNotPresent
        name: config-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /readonly-config
          name: config
          readOnly: true
        - mountPath: /data
          name: data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: redis-ha-2
      serviceAccountName: redis-ha-2
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: redis-ha-2-configmap
        name: config
      - configMap:
          defaultMode: 420
          name: redis-ha-2-probes
        name: probes
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 10Gi
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: redis-ha-2-server-7b9697d574
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: redis-ha-2-server-7b9697d574
  updatedReplicas: 3
``` 

redis.conf
``` 
dir "/data"
maxmemory 0
maxmemory-policy volatile-lru
min-slaves-max-lag 5
min-slaves-to-write 1
rdbchecksum yes
rdbcompression yes
repl-diskless-sync yes
save 900 1

``` 
sentinel.conf
``` 
dir "/data"
sentinel down-after-milliseconds mymaster 10000
sentinel failover-timeout mymaster 180000
sentinel parallel-syncs mymaster 5

```

**Comment by sdnetwork** [comment]
i have exactly the same problem ... no clue :( maybe the readynessprobe but no events so ....

in witch kubernetes provider aws, gce ?

**Comment by DandyDeveloper** [comment]
@Zero-2 What does the pod log say? `kubectl logs <pod> -n <namespace> --previous`?

**Comment by SergeyD** [comment]
`redis-ha-server-XXX` pods has multiple containers running within it: `redis`, `sentinel` and `redis-exporter`. If one of container restarts pod restarts counter will be increased. In our case `redis` and `sentinel` container running without restart, while `redis-exporter` restarts and it happens more often on highly loaded clusters (to check which containers restart inside pod describe it with `kubectl describe` and check `Restart Count` for each container).
As also seen from pod describe, k8s kills `redis-metrics` container by it's liveness probe. There is a hardcoded 1s timeout for liveness probe which could be the reason. I've temporary increased timeout by editing stateful set and will see how it goes.
@DandyDeveloper

**Comment by SergeyD** [comment]
UPDATE: with increased timeout from 1s to 5s `redis-exporter` container running without restarts.

**Comment by DandyDeveloper** [comment]
@SergeyD The container should still state why it's restarting. Do you get anything in the log? 

The exporter is super lightweight, so it should have very few problems. Are you using the latest version of the chart?

**Comment by kimiazhu** [comment]
I have the same problem, and I have changed timeout to 3s, failure count to 5, but after about 2 days I still get one restart count coursed by the sentinel.

**Comment by SergeyD** [comment]
@DandyDeveloper

Just returned from vacation and checked cluster with 5s timeout - 0 restart for past 18 days, other highly loaded clusters with 1s default got a lot of restarts.

Nothing in logs (tried in debug mode as well).
From kubectl:

```
root@XXXXXX-kube1:~# kubectl describe po redis-ha-server-1 -n redis-ha
    Name:           redis-ha-server-1

    redis-exporter:

    ...

    Port:           9121/TCP
    State:          Running
      Started:      Sat, 10 Aug 2019 23:47:19 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 10 Aug 2019 10:41:04 +0000
      Finished:     Sat, 10 Aug 2019 23:47:17 +0000
    Ready:          True
    Restart Count:  17

    ...

    Liveness:  http-get http://:9121/metrics delay=15s timeout=1s period=15s #success=1 #failure=3

    ...

    Events:
  Type     Reason     Age                    From                   Message
  ----     ------     ----                   ----                   -------
  Warning  Unhealthy  31m (x29877 over 19d)  kubelet, 10.118.18.94  Liveness probe failed: Get http://172.16.2.85:9121/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

```

From log messages it just seen that restart happened; no errors:

<img width="1231" alt="Screen Shot 2019-08-12 at 18 08 17" src="https://user-images.githubusercontent.com/769527/62875883-7e7f6680-bd2c-11e9-8a9a-629b1c5c6884.png">


Chart version is 3.6.1, redis-ha image tag: 5.0.3-alpine, exporter image tag: v1.0.3.

**Comment by kimiazhu** [comment]
UPDATE: Change the timeout doesn't take effect to my redis-ha cluster. I think my case is about the **somaxconn** which default value is too small (just 128 in docker container), I change this  with setting the initContainer and restore timeout to the default ones. Now it's stable for some days.

values.yaml:
`
sysctlImage:
  enabled: true
  command: 
    - /bin/sh
    - -c
    - |-
      install_packages systemd
      sysctl -w net.core.somaxconn=1024
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
  registry: docker.io
  repository: bitnami/minideb
  tag: latest
  pullPolicy: Always
  mountHostSys: true
`

Now didn't restart for the past 4 days:
![redis-restarting](https://user-images.githubusercontent.com/936708/63572748-370f9a80-c5b6-11e9-813d-c460b5473eb9.jpg)

**Comment by Zero-2** [comment]
> @Zero-2 What does the pod log say? `kubectl logs <pod> -n <namespace> --previous`?

Sorry @DandyDeveloper  i miss this message...
No errors in the log...:-(
I've one restart per day...

NAME                  READY   STATUS    RESTARTS   AGE
redis-ha-2-server-0   2/2     Running   38         30d
redis-ha-2-server-1   2/2     Running   27         30d
redis-ha-2-server-2   2/2     Running   0          17m

No solution...

**Comment by Zero-2** [comment]
> UPDATE: Change the timeout doesn't take effect to my redis-ha cluster. I think my case is about the **somaxconn** which default value is too small (just 128 in docker container), I change this with setting the initContainer and restore timeout to the default ones. Now it's stable for some days.
> 
> values.yaml:
> 
> ```
> sysctlImage:
>   enabled: true
>   command: 
>     - /bin/sh
>     - -c
>     - |-
>       install_packages systemd
>       sysctl -w net.core.somaxconn=1024
>       echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
>   registry: docker.io
>   repository: bitnami/minideb
>   tag: latest
>   pullPolicy: Always
>   mountHostSys: true
> ```
> 
> Now didn't restart for the past 4 days(first three pods are the newer looks nice...Last three just change the timeout which still restart):
> ![redis-restarting](https://user-images.githubusercontent.com/936708/63572748-370f9a80-c5b6-11e9-813d-c460b5473eb9.jpg)

No sysctl in that image...

> root@e80a8afb9cdc:/# sysctl -w net.core.somaxconn=1024
bash: sysctl: command not found

**Comment by kimiazhu** [comment]
> > UPDATE: Change the timeout doesn't take effect to my redis-ha cluster. I think my case is about the **somaxconn** which default value is too small (just 128 in docker container), I change this with setting the initContainer and restore timeout to the default ones. Now it's stable for some days.
> > values.yaml:
> > ```
> > sysctlImage:
> >   enabled: true
> >   command: 
> >     - /bin/sh
> >     - -c
> >     - |-
> >       install_packages systemd
> >       sysctl -w net.core.somaxconn=1024
> >       echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
> >   registry: docker.io
> >   repository: bitnami/minideb
> >   tag: latest
> >   pullPolicy: Always
> >   mountHostSys: true
> > ```
> > 
> > 
> > Now didn't restart for the past 4 days(first three pods are the newer looks nice...Last three just change the timeout which still restart):
> > ![redis-restarting](https://user-images.githubusercontent.com/936708/63572748-370f9a80-c5b6-11e9-813d-c460b5473eb9.jpg)
> 
> No sysctl in that image...
> 
> > root@e80a8afb9cdc:/# sysctl -w net.core.somaxconn=1024
> > bash: sysctl: command not found
> 
> You should install procps also

No need. change your value.yaml, it supports initContainer, Don't get into the container and run sysctl manually...

**Comment by Zero-2** [comment]
> > > UPDATE: Change the timeout doesn't take effect to my redis-ha cluster. I think my case is about the **somaxconn** which default value is too small (just 128 in docker container), I change this with setting the initContainer and restore timeout to the default ones. Now it's stable for some days.
> > > values.yaml:
> > > ```
> > > sysctlImage:
> > >   enabled: true
> > >   command: 
> > >     - /bin/sh
> > >     - -c
> > >     - |-
> > >       install_packages systemd
> > >       sysctl -w net.core.somaxconn=1024
> > >       echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
> > >   registry: docker.io
> > >   repository: bitnami/minideb
> > >   tag: latest
> > >   pullPolicy: Always
> > >   mountHostSys: true
> > > ```
> > > 
> > > 
> > > Now didn't restart for the past 4 days(first three pods are the newer looks nice...Last three just change the timeout which still restart):
> > > ![redis-restarting](https://user-images.githubusercontent.com/936708/63572748-370f9a80-c5b6-11e9-813d-c460b5473eb9.jpg)
> > 
> > 
> > No sysctl in that image...
> > > root@e80a8afb9cdc:/# sysctl -w net.core.somaxconn=1024
> > > bash: sysctl: command not found
> > 
> > 
> > You should install procps also
> 
> No need. change your value.yaml, it supports initContainer, Don't get into the container and run sysctl manually...
> 
> Now the old ones keeping restarting. the new ones are stable
> ![redis-restarting](https://user-images.githubusercontent.com/936708/63630813-658e8380-c651-11e9-8b62-6db64faa2c9c.jpg)

Yeah, i used it into initContainer, but bitnami/minideb doesn't have sysctl installed by default, so pod goes in crashloopbackoff.
I need to install sysctl before use it.

```yaml
sysctlImage:
 enabled: true
  command: 
  - "sh"
  - "-c"
  - |
    set -e
    install_packages systemd procps
    sysctl -w net.core.somaxconn=1024
  registry: docker.io
  repository: bitnami/minideb
  tag: latest
  pullPolicy: Always
  mountHostSys: true
```
