### ISSUE TITLE
[stable/velero] Deployment incomplete

### ISSUE THREAD

**Issue by elisiano** [helm/charts#14130]
**Describe the bug**
Velero deployment is missing command arguments and environment variables

**Version of Helm and Kubernetes**:
Helm: 2.14.0
Kibernetes: 1.11.8

**Which chart**:
stable/velero

**What happened**:
No errors but the output is not what's expected

**What you expected to happen**:
I expected the deployment to have arguments and environment variables based on the passed values.

**How to reproduce it** (as minimally and precisely as possible):
cleaned values:
```
➭ egrep -v "^[ ]*(#|$)" $HOME/velero_values.yaml
image:
  repository: gcr.io/heptio-images/velero
  tag: v1.0.0
  pullPolicy: IfNotPresent
podAnnotations:
  iam.amazonaws.com/role: PLACEHOLDER
resources: {}
initContainers: []
tolerations: []
nodeSelector: {}
metrics:
  enabled: false
  scrapeInterval: 30s
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: /metrics
  serviceMonitor:
    enabled: false
    additionalLabels: {}
configuration:
  provider: aws
  backupStorageLocation:
    name: aws
    bucket: PLACEHOLDER
    prefix: null
    config:
      region: PLACEHOLDER
  volumeSnapshotLocation:
    name: aws
    config:
      region: PLACEHOLDER
  backupSyncPeriod: null
  resticTimeout: null
  restoreResourcePriorities: null
  restoreOnlyMode: null
  extraEnvVars:
    AWS_CLUSTER_NAME: PLACEHOLDER
rbac:
  create: true
serviceAccount:
  server:
    create: true
    name: velero
credentials:
  useSecret: false
  existingSecret: null
  secretContents: {}
deployRestic: false
schedules:
  sugarbackup:
    schedule: 0 0 * * *
    template:
      ttl: 240h
```

Then execute the deployment template:
```
➭ cd /path/to/helm-charts/stable/velero
➭ helm template . --values=$HOME/velero_values.yaml -x templates/deployment.yaml
---
# Source: velero/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: velero-2.0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Tiller
        helm.sh/chart: velero-2.0.2
      annotations:
        iam.amazonaws.com/role: PLACEHOLDER

        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"

    spec:
      restartPolicy: Always
      serviceAccountName: velero
      containers:
        - name: velero
          image: "gcr.io/heptio-images/velero:v1.0.0"
          imagePullPolicy: IfNotPresent
          command:
            - /velero
          args:
            - server
          volumeMounts:
            - name: plugins
              mountPath: /plugins
      volumes:
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
```

**Anything else we need to know**:

Seems that the snippets for the [command args](https://github.com/helm/charts/blob/2792ff545cb1e7a52e21a80c2c70bbe7c94b6260/stable/velero/templates/deployment.yaml#L50-L63) and [extraEnvVars](https://github.com/helm/charts/blob/2792ff545cb1e7a52e21a80c2c70bbe7c94b6260/stable/velero/templates/deployment.yaml#L90-L94) are not working properly.

There might be additional issues but these are the first I came across
