### ISSUE TITLE
[stable/mongodb-replicaset] Chart does not render PVC annotations correctly. Strips quotes away from numbers.

### ISSUE THREAD

**Issue by juliohm1978** [helm/charts#14139]
Using chart version 3.9.4, I am unable to use annotations on the PersistentVolumeClaim templates created by the chart.

Simple test case, use the following `values.yaml`:

```yaml
persistentVolume:
  annotations:
    myannotation: "123"
```

Trying to `helm install...` I get the error:

```
Error: release mmm failed: StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.VolumeClaimTemplates: []v1.PersistentVolumeClaim: v1.PersistentVolumeClaim.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 1, error found in #10 byte of ...|otation":123},"name"|..., bigger context ...|tes":[{"metadata":{"annotations":{"myannotation":123},"name":"datadir"},"spec":{"accessModes":["Read|...
```

Using helm with `--dry-run --debug` flags, it's possible to see the rendered StatefulSet is missing quotes around the annotation value.

```
## snippet ...

  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
          myannotation: 123

## snippet ...
```
