### ISSUE TITLE
[stable/redis-ha] mkdir: can't create directory '/data/conf/': Permission denied

### ISSUE THREAD

**Issue by danielsatanik** [helm/charts#14183]
**Describe the bug**
Installing of redis-ha halts, claiming that it has no permissions to create a directory.

**Version of Helm and Kubernetes**:
Kubernetes-Version: v1.13.5
Helm-Version: v2.10+unreleased

**Which chart**:
stable/redis-ha

**What happened**:
Installation is stuck

Messages:

in Rancher: 
```
Container with incomplete status [config-init]
CrashLoopBackOff: Back-off 5m0s restarting failed container=config-init pod=redis-ha-server-0_redis-ha(4d606898-8146-11e9-8dad-e4b97a6bc1b3)
```
config-init container:
```
Could not connect to Redis at redis-ha:26379: Try again
mkdir: can't create directory '/data/conf/': Permission denied
```

**What you expected to happen**:
Finish the installation until the pod is running

**How to reproduce it** (as minimally and precisely as possible):
1. Create a cluster
2. Add a PV with min. 10Gb storage
3. Install with "helm install stable/redis-ha"

**Anything else we need to know**:
I'm using rancher v2.2.3 in a single-node installation on an ubuntu 18.04LTS

**Edit:**
I temporarily fixed it by adding answers for values.yml during helm installation with the following values

```
securityContext:
  runAsUser: 0
  fsGroup: 0
  runAsNonRoot: false
hostPath:
  ## path is evaluated as template so placeholders are replaced
  # path: "/data/{{ .Release.Name }}"

  # if chown is true, an init-container with root permissions is launched to
  # change the owner of the hostPath folder to the user defined in the
  # security context
  chown: false
```
