### ISSUE TITLE
stable/spinnaker

### ISSUE THREAD

**Issue by romilpunetha** [helm/charts#14250]
**Describe the bug**
The `imageTag` field for minio doesnt work. Nomatter the tag, it always picks `RELEASE.2018-08-25T01-56-38Z` as tag. 

**Version of Helm and Kubernetes**:
K8s: 1.12
Helm: v2.14.0 

**Which chart**:
stable/spinnaker

**What happened**:
Minio always installing with a fixed tag.

**What you expected to happen**:
Minio installs with the new tag

**How to reproduce it** (as minimally and precisely as possible):
Try deploying the helm chart for spinnaker, with minio.imageTag : RELEASE.2019-05-23T00-29-34Z

**Anything else we need to know**:

**Comment by vchrisb** [comment]
the chart is generating:
```
  image:
    pullPolicy: IfNotPresent
    repository: minio/minio
    tag: RELEASE.2018-08-25T01-56-38Z
  imageTag: RELEASE.2019-02-13T19-48-27Z
```
