### ISSUE TITLE
[stable/prometheus-operator] Drill-down links don't work when hosting grafana on sub path

### ISSUE THREAD

**Issue by ducas** [helm/charts#14300]
**Describe the bug**
Grafana dashboards in the prometheus-operator chart use absolute URLs in links. This makes the drill-down links break when grafana is hosted behind a reverse proxy (e.g. nginx) with a sub path.

**Version of Helm and Kubernetes**:
helm 2.12
kubernetes 1.12

**Which chart**:
stable/prometheus-operator

**What happened**:
Deployed with grafana behind nginx on sub path. Links in tables don't work.

**What you expected to happen**:
Links in tables work.

**How to reproduce it** (as minimally and precisely as possible):
Deploy with grafana behind nginx on sub path

**Anything else we need to know**:
no

**Comment by sudeep-ib** [comment]
Any update on this?

**Comment by MisterTimn** [comment]
We host our Grafana under subpath as well and our drilldown links work

just setup your `grafana.ini` server config accordingly:
```yaml
  grafana.ini:
    server:
      domain: your-domain.com
      root_url: https://your-domain.com/monitoring/grafana
```
