### ISSUE TITLE
 stable/atlantis on gke broken image links (/static/images/atlantis-icon.png)

### ISSUE THREAD

**Issue by red8888** [helm/charts#14527]
I created a new GKE cluster

I installed atlantis via the helm chart: https://www.runatlantis.io/docs/deployment.html#deployment-2

```
helm inspect values stable/atlantis > values.yaml
helm install -f values.yaml --name my-atlantis stable/atlantis --debug
```

I edited values.yaml to include my bitbucket creds and changed the "host:" under "ingress:"

It deploys fine but there is an issue with the path of images:
![image](https://user-images.githubusercontent.com/6265399/58936612-26315480-873e-11e9-9fda-569caa08199c.png)

**Comment by red8888** [comment]
confused about how this works. I exec into the pod and I can find no html files or png files or a "static" directory. where is all of that in the container?

**Comment by red8888** [comment]
ok this took way longer for me to figure out than it should have

Just need to add a wildcard to the path

@max-rocket-internet can you make the default path in values.yaml `path: /*` pleassseeeee

The documentation says to just build your base config like this: `helm inspect values stable/atlantis > values.yaml`

should probably default to wildcard right? no other paths are defined expect "/"

**Comment by max-rocket-internet** [comment]
Are you talking about the `Ingress` resource? This works fine for me:

```
spec:
  rules:
  - host: atlantis.xxxx.com
    http:
      paths:
      - backend:
          serviceName: atlantis
          servicePort: 80
        path: /
```

**Comment by red8888** [comment]
Im using what documentation says and generating a values.yaml. do you have to edit the ingress directly?

**Comment by max-rocket-internet** [comment]
No. We use a values file for the chart:

```yaml
ingress:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: atlantis.xxx-xxx.com

atlantisUrl: https://atlantis.xxx-xxx.com
```

There's no need to do this: `helm inspect values stable/atlantis > values.yaml`
