### ISSUE TITLE
[stable/reloader] Bump app version to v0.0.29

### ISSUE THREAD

**Issue by GreenKnight15** [helm/charts#14573]
I would like to see the version of Reloader updated in the charts/stable version to match the tags in https://github.com/stakater/Reloader 

v0.0.25 -> v0.0.29

**Is your feature request related to a problem? Please describe.**
I tried to using the existing stable/reloader chart and can into an issue reloaded a deployment based on specific configmaps
```yaml
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: 'foo-bar'
``` 
**Describe the solution you'd like**
After updating the image to v0.0.29 it worked exactly as I expected

**Describe alternatives you've considered**
I considered using the chart describe in https://github.com/stakater/Reloader

**Additional context**
N/A

**Additional Comments**
Is support for the stable/reloader chart going to be dropped for the chart in https://github.com/stakater/Reloader?
