### ISSUE TITLE
[stable/nginx-ingress] integration with prometheus for monitoring

### ISSUE THREAD

**Issue by polganesh** [helm/charts#14577]
**Is it request for help ?**
Yes

**what I am trying to achieve?**
I want to push stats  from Nginx to prometheus server hosted on specific URL

**My Observations**
```
  metrics:
    enabled: true

    service:
      annotations: {prometheus.io/scrape: "true",prometheus.io/port: "10254"}

```
not sure but i am unable to get any way by which i will mention prometheus server URL.
or steps by which i can monitor NgInx
