### ISSUE TITLE
[stable/datadog] Improve documentation for usage with custom metrics

### ISSUE THREAD

**Issue by nicgirault** [helm/charts#14615]
I've spent 2 days trying to install datadog but I continue blocking to get custom metrics from my python app. I don't even now how to debug. Debug logs in dd-agent does not help me to understand where the problem comes from. The user experience is sadly horrible. As a comparison I installed kube-prometheus and get it work in 30 minutes...

I think this poor user experience could be very easily fixed with an example in the doc. My use case does not seem unique.

**Comment by nicgirault** [comment]
To be more precise, here is my detailed issue:

Here is my values.yaml for the datadog chart:

```
datadog:
    logLevel: DEBUG
    useDogStatsDSocketVolume: true
    apiKey: xxx
```

Then the deployment of my app looks like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app:  my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  my-app
  template:
    metadata:
      labels:
        app:  my-app
    spec:
      containers:
        - name:  my-app
          image: "xxx"
          volumeMounts:
            - name: dsdsocket
              mountPath: /var/run/datadog
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: dsdsocket
```

Then in my app I initialize the datadog agent client like this (note that this section is not documented in the chart documentation):

```
from datadog import initialize, statsd
initialize(statsd_socket_path='/var/run/datadog/dsd.socket')
```

When running my app I can't find my metrics in the metrics explorer on datadog. I don't know how to debug this since neither the agent & the client logs about received & sent message.

The only logs I get are the following on the agent part:

```
[ AGENT ] 2019-06-09 19:08:50 UTC | DEBUG | (pkg/dogstatsd/listeners/uds_common.go:111 in NewUDSListener) | dogstatsd-uds: /var/run/datadog/dsd.socket successfully initialized
[ AGENT ] 2019-06-09 19:08:50 UTC | INFO | (pkg/dogstatsd/listeners/uds_common.go:117 in Listen) | dogstatsd-uds: starting to listen on /var/run/datadog/dsd.socket
```

Note that I receive non custom metrics from this cluster which means that the agent is working correctly.

Any idea how I can fix this?
