### ISSUE TITLE
stable/atlantis how to use environment param with secretKeyRef

### ISSUE THREAD

**Issue by red8888** [helm/charts#14625]
There is an "environment" param to inject arbitrary environment variables into the atlantis container

But I see no examples of how to inject arbitrary environment variables that get their value from secrets

How would I use this chart to do this? for example:
```
        env:
        - name: GET_THIS_VAR_IN_ATLANTIS
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: abc
```
