### ISSUE TITLE
[stable/mongodb] PodDisruptionBudget evict scale-down

### ISSUE THREAD

**Issue by caiohasouza** [helm/charts#14706]
**Describe the bug**
The helm chart always create a pdb when the replicaset is enabled, with pdb and the min 1 the pod disruption budget can't move the pods.

**Version of Helm and Kubernetes**:
Helm v2.14.1
Kubernetes 1.12.7

**Which chart**:
stable/mongodb

**What you expected to happen**:
I think that in cases when the pod number is <= 0 the pdb can be disabled.

**How to reproduce it** (as minimally and precisely as possible):
Just a simple deploy without params.

**Comment by tompizmor** [comment]
You can configure the min available parameter through the values.yaml and values-production.yaml

```yaml
  ## Pod Disruption Budget
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  pdb:
    minAvailable:
      primary: 1
      secondary: 1
      arbiter: 1
```
Would it work if you put 0 for the components with only 1 replica?

Do you think there should be an option to completely disable PDB for a specific component (primary, secondary, or arbiter) ?
