### ISSUE TITLE
[stable/heartbeat] output.file always get appended in heartbeat.yaml file

### ISSUE THREAD

**Issue by mazharul** [helm/charts#14760]
**Describe the bug**

```
 output.file:
    enable: false
    filename: heartbeat
    number_of_files: 5
    path: /usr/share/heartbeat/data
    rotate_every_kb: 10000
```

`output.file` always gets appended in the values.yaml file

**Version of Helm and Kubernetes**:
```
┗ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

```
┗ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:

stable/heartbeat

**What happened**:
This is my partial values.yaml file:

```
image:
  repository: docker.elastic.co/beats/heartbeat
  tag: 6.7.0
  pullPolicy: Always

config:
  heartbeat.monitors:
  - type: http
    schedule: '@every 5s'
    urls:
      - https://www.google.com
    check.response.status: 200


  processors:
  - add_cloud_metadata: ~

  output.elasticsearch:
    hosts: '[localhost:9000]'
    username: 'elastic'
    password: 'changeme'

  setup.kibana:
    host: 'localhost:5601'
```

This is what I get after I run ` helm install --debug --values values.yaml stable/heartbeat`

```
REVISION: 1
RELEASED: Thu Jun 13 00:51:19 2019
CHART: heartbeat-1.2.0
USER-SUPPLIED VALUES:
config:
  heartbeat.monitors:
  - check.response.status: 200
    schedule: '@every 5s'
    type: http
    urls:
    - https://www.google.com
  output.elasticsearch:
    hosts: '[localhost:9000]'
    password: changeme
    username: elastic
  processors:
  - add_cloud_metadata: null
  setup.kibana:
    host: localhost:5601
image:
  pullPolicy: Always
  repository: docker.elastic.co/beats/heartbeat
  tag: 6.7.0

COMPUTED VALUES:
config:
  heartbeat.monitors:
  - check.response.status: 200
    schedule: '@every 5s'
    type: http
    urls:
    - https://www.google.com
  output.elasticsearch:
    hosts: '[localhost:9000]'
    password: changeme
    username: elastic
  output.file:
    filename: heartbeat
    number_of_files: 5
    path: /usr/share/heartbeat/data
    rotate_every_kb: 10000
  processors:
  - add_cloud_metadata: null
  setup.kibana:
    host: localhost:5601
extraVars: {}
extraVolumeMounts: []
extraVolumes: []
hostNetwork: false
image:
  pullPolicy: Always
  repository: docker.elastic.co/beats/heartbeat
  tag: 6.7.0
nodeSelector: {}
plugins: []
priorityClassName: ""
rbac:
  create: true
resources: {}
serviceAccount:
  create: true
  name: null
tolerations: []
```

**What you expected to happen**:
There shouldn't be any `output.file` keys. Because of this heartbeat exits without starting properly. Error in the pods:

`Exiting: more than one namespace configured accessing 'output' (source:'heartbeat.yml')`
