### ISSUE TITLE
[stable/orangehrm] Https bad request

### ISSUE THREAD

**Issue by agustinlare** [helm/charts#14765]
**Describe the bug**
Unable to make it work with https.

**Version of Helm and Kubernetes**: 
Helm 2.12.2
K8n: Major:"1", Minor:"13", GitVersion:"v1.13.2"

**Which chart**: orangehrm

**What happened**:
I'm kinda new to the kubernetes technology, sorry if I'm asking something really dumb. I've been trying to install orangehrm with helm, with no major problems actually and the http works fine but when I try to acces through the https url, it shows me the error of bad request.

**Curl output**
```
* About to connect() to orangehrm.[REDACTED].com port 443 (#0)
*   Trying 192.168.20.250...
* Connected to orangehrm.[REDACTED].com (192.168.20.250) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=orangehrm.[REDACTED].com,O=Internet Widgits Pty Ltd,ST=Some-State,C=AU
*       start date: Jun 07 13:01:54 2019 GMT
*       expire date: Jun 04 13:01:54 2029 GMT
*       common name: orangehrm.[REDACTED].com
*       issuer: O=[REDACTED],L=C.A.B.A.,ST=Buenos Aires,C=AR
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: orangehrm.[REDACTED].com
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Server: nginx/1.15.8
< Date: Wed, 12 Jun 2019 19:23:20 GMT
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 362
< Connection: keep-alive
< Strict-Transport-Security: max-age=15724800; includeSubDomains
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
</body></html>
* Connection #0 to host orangehrm.[REDACTED].com left intact
```
**How to reproduce it** (as minimally and precisely as possible):
`helm install --debug --name orangehrm --set service.type=NodePort,service.port=80,service.httpsPort=443,persistence.apache.accessMode=ReadWriteOnce,persistence.apache.storageClass=slow,persistence.apache.size=16Gi,persistence.orangehrm.accessMode=ReadWriteOnce,persistence.orangehrm.storageClass=slow,persistence.orangehrm.size=8Gi,orangehrmUsername=admin,orangehrmPassword=admin,mariadb.enabled=false,externalDatabase.host=192.168.0.132,externalDatabase.user=orangehrm_user,externalDatabase.password=[REDACTED],externalDatabase.database=orangehrm,ingress.enable=true,ingress.annotations="kubernetes.io/ingress.class: nginx",ingress.hosts[0].name=orangehrm.[REDACTED].com,ingress.hosts[0].path=/ stable/orangehrm`

**Anything else we need to know**:
I have a nginx load balancer with the following ingress:
```
apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    name: https
  spec:
    rules:
      - host: orangehrm.[REDACTED].com
        http:
          paths:
            - backend:
                serviceName: orangehrm-orangehrm
                servicePort: 443
              path: /       
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - orangehrm.[REDACTED].com
          secretName: orangehrm-https
```

**Pod StartUp Logs**
```
Welcome to the Bitnami orangehrm container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-orangehrm
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-orangehrm/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing orangehrm
orangeh INFO  Configuring permissions
orangeh INFO  Creating the database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at 192.168.0.132:3306
mysql-c INFO  MySQL server listening and working at 192.168.0.132:3306
orangeh INFO  Preparing webserver environment...
orangeh INFO  Passing wizard, please be patient
orangeh INFO  Configuring SMTP...
orangeh INFO  Setting OrangeHRM version...
orangeh INFO
orangeh INFO  ########################################################################
orangeh INFO   Installation parameters for orangehrm:
orangeh INFO     Username: admin
orangeh INFO     Password: **********
orangeh INFO     Site URL: http://127.0.0.1/
orangeh INFO   (Passwords are not shown for security reasons)
orangeh INFO  ########################################################################
orangeh INFO
nami    INFO  orangehrm successfully initialized
```
Please let me know if you need more info, i will gladly provide it.
Kind Regards
