### ISSUE TITLE
[stable/prometheus-opeartor] unable to modify `CPUThrottingHigh` alert configurations

### ISSUE THREAD

**Issue by aliartiza75** [helm/charts#14801]
Hello everyone,

I want to disable `CPUThrottlingHigh` (https://github.com/helm/charts/blob/9aeaf2095c8b302718968829505a87ef4201ff6a/stable/prometheus-operator/templates/prometheus/rules/kubernetes-resources.yaml#L87) alert because it is trigging with huge frequency.

I want to do two things:

• change the threshold values(but can't do it now because it is hardcoded)
• Somehow disable this alert(suggestion: by using enable or disable flag)

Would you people (prometheus-operator-maintainer) accept a PR regarding this issue?

**Comment by devolutionsbot** [comment]
Hi @aliartiza75. I have the same issue and I found some informations about it:
- https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/108
- https://devops.stackexchange.com/a/6753/15494

If you want to get rid of this alert, I found a way to do this without using inhibit rules. In Prometheus configuration, it's fine to fire an alert against an empty receiver:

Alertmanager configuration:
```yaml
route:
  routes:
  - match:
      alertname: 'CPUThrottlingHigh'
    receiver: 'silent-receiver'
receivers:
  - name: silent-receiver
```

I don't think it's a good idea to get rid of this alert or changing the treshold values (I already tried and this does not fix the problem).

**Comment by richerlariviere** [comment]
Hi @aliartiza75. I have the same issue and I found some informations about it:
- https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/108
- https://devops.stackexchange.com/a/6753/15494

If you want to get rid of this alert, I found a way to do this without using inhibit rules. In Prometheus configuration, it's fine to fire an alert against an empty receiver:

Alertmanager configuration:
```yaml
route:
  routes:
  - match:
      alertname: 'CPUThrottlingHigh'
    receiver: 'silent-receiver'
receivers:
  - name: silent-receiver
```

I don't think it's a good idea to get rid of this alert or changing the treshold values (I already tried and this does not fix the problem).
