### ISSUE TITLE
[stable/grafana] Issues providing custom dashboards

### ISSUE THREAD

**Issue by kri5** [helm/charts#14844]
**Describe the bug**
While trying to use this chart, i wanted to only configure it using a `values.yaml` file.

To provide additionnal custom dashboards, the chart use `.Files.Get`, so it is not possible to use without forking it, and having to maintain your own, OR you can provide dashboards inline in the `values.yaml` file directly in json.

However, doing so, if you have multiple dashboard, it will generate a single `ConfigMap` and likely hit the size limit of a `ConfigMap` (1MB iirc, due to underlying storage in etcd).

There seems to be a third way using a sidecar loader but it assumes you have to provision your dashboards `ConfigMap` yourself, and doing so you're leaving the helm workflow.

A way to work around might be to generate a `ConfigMap` per dashboard?

**Version of Helm and Kubernetes**:
***Helm Version***
```version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}```
***Kubernetes Version***
```Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}```
```Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.5", GitCommit:"46b3ddd492a78deae773f24b47c5c564a9b928b1", GitTreeState:"clean", BuildDate:"2019-05-18T01:19:43Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}```

**Which chart**:
stabe/grafana version 3.4.2

**What happened**:
`The ConfigMap "prometheus-operator-grafana-dashboards-default" is invalid: metadata.annotations: Too long: must have at most 262144 characters`

**What you expected to happen**:
Users shouldn't have to be aware of how underlying storage works.

**How to reproduce it** (as minimally and precisely as possible):
Create a `values.yaml` with something like

```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    example1:
      json: |-
        {
          ...
        }
    example2:
      json: |-
        {
          ...
        }
```

Where the examples dashboards are long enough to hit the issue.

**Comment by HaveFun83** [comment]
We run into this in a similar way.
Try to use the dashboard-side car instead. 
```
## Sidecars that collect the configmaps with specified label and stores the included files them into the respective folders
## Requires at least Grafana 5 to work and can't be used together with parameters dashboardProviders, datasources and dashboards
sidecar:
  image: kiwigrid/k8s-sidecar:0.0.16
  imagePullPolicy: IfNotPresent
  resources: {}
#   limits:
#     cpu: 100m
#     memory: 100Mi
#   requests:
#     cpu: 50m
#     memory: 50Mi
  # skipTlsVerify Set to true to skip tls verification for kube api calls
  # skipTlsVerify: true
  dashboards:
    enabled: false
    # label that the configmaps with dashboards are marked with
    label: grafana_dashboard
    # folder in the pod that should hold the collected dashboards (unless `defaultFolderName` is set)
    folder: /tmp/dashboards
    # The default folder name, it will create a subfolder under the `folder` and put dashboards in there instead
    defaultFolderName: null
    # If specified, the sidecar will search for dashboard config-maps inside this namespace.
    # Otherwise the namespace in which the sidecar is running will be used.
    # It's also possible to specify ALL to search in all namespaces
searchNamespace: null
```
here you can provide the dashboards via configmap.
as one configmap per dashboard
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-example-dashboard
  namespace: monitoring
  labels:
     grafana_dashboard: example
data:
  example.json: |-
```

**Comment by rombert** [comment]
I see the same problem with custom dashboards. I have a workaround in place, but it would be good to not have to use it as I need to step out of helm. The idea is to:

1. Manually replace the config maps for the custom dashboards

`$ kubectl create configmap grafana-dashboards-default --from-file=sling-metrics.json -o yaml --dry-run | kubectl replace -f -`

2. Delete the grafana pods so the mounts are refrehsed

`$ kubectl delete pods -l=app=grafana`

**Comment by rombert** [comment]
Would still be great to have a resolution to this :-)

**Comment by rombert** [comment]
https://github.com/helm/charts/issues/14844#issuecomment-528760886

**Comment by Siegfriedk** [comment]
@rombert got the same problem.
What workes for me is to configure one provider per dashboard. I only change the name and folder:


```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
      - name: 'bigdashboard'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/bigdashboard
```

Didn't wanna go the yaml route as with that i was forced to quote the dashboard json. Its much easier to export it as grafana as json and just put it in place without any modifications.
