### ISSUE TITLE
[stable/etcd-operator] Unable to set cluster.enabled

### ISSUE THREAD

**Issue by arthur0** [helm/charts#1484]
BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**
etcd-operator

**How to reproduce it**:
**Create tiller service account and cluster role binding**
`$ cat tiller-rbac.yaml` 
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
$ kubectl create -f tiller-rbac.yaml 
serviceaccount "tiller" created
clusterrolebinding "tiller-clusterrolebinding" created
```

**Init helm passing the tiller service account**
```bash
$ helm init --upgrade --service-account tiller
$HELM_HOME has been configured at /root/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
# Tiller is running: 
$ kubectl get po -n kube-system | grep tiller
tiller-deploy-4160234829-z9k0m              1/1       Running   0          22s
```

**Create a namespace called core**
```
$ kubectl create ns core
namespace "core" created
```

**Install helm etcd-operator Chart on this namespace**
It's not possible to set cluster.enabled on install: https://github.com/kubernetes/charts/issues/728
So I set `cluster.enabled=true` and `rbac.install=true` properties on upgrading:
```
$ helm install stable/etcd-operator --name core --namespace core
NAME:   core
LAST DEPLOYED: Wed Jul 19 15:03:40 2017
NAMESPACE: core
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
core-etcd-operator  1        1        1           0          <invalid>


NOTES:
1. etcd-operator deployed.
  If you would like to deploy an etcd-cluster set cluster.enabled to true in values.yaml
  Check the etcd-operator logs
    export POD=$(kubectl get pods -l app=core-etcd-operator --namespace core --output name)
    kubectl logs $POD --namespace=core
$ helm upgrade core stable/etcd-operator --namespace core --set cluster.enable=true,rbac.install=true
Release "core" has been upgraded. Happy Helming!
LAST DEPLOYED: Wed Jul 19 15:03:54 2017
NAMESPACE: core
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/ClusterRoleBinding
NAME                AGE
core-etcd-operator  <invalid>

==> v1beta1/Deployment
NAME                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
core-etcd-operator  1        1        1           0          10s

==> v1/ServiceAccount
NAME                SECRETS  AGE
core-etcd-operator  1        <invalid>

==> v1beta1/ClusterRole
NAME                AGE
core-etcd-operator  <invalid>


NOTES:
1. etcd-operator deployed.
  If you would like to deploy an etcd-cluster set cluster.enabled to true in values.yaml
  Check the etcd-operator logs
    export POD=$(kubectl get pods -l app=core-etcd-operator --namespace core --output name)
    kubectl logs $POD --namespace=core
```

**Logs:**
```
$ export POD=$(kubectl get pods -l app=core-etcd-operator --namespace core --output name)
$ kubectl logs $POD --namespace=core
time="2017-07-19T18:03:56Z" level=info msg="etcd-operator Version: 0.3.3" 
time="2017-07-19T18:03:56Z" level=info msg="Git SHA: bcad5ae" 
time="2017-07-19T18:03:56Z" level=info msg="Go Version: go1.8.1" 
time="2017-07-19T18:03:56Z" level=info msg="Go OS/Arch: linux/amd64" 
time="2017-07-19T18:03:57Z" level=info msg="Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"core", Name:"etcd-operator", UID:"a512a175-6cac-11e7-ad54-fa163e194ff5", APIVersion:"v1", ResourceVersion:"142714", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' core-etcd-operator-679172444-bnzc3 became leader" 
time="2017-07-19T18:03:57Z" level=info msg="finding existing clusters..." pkg=controller 
time="2017-07-19T18:03:57Z" level=info msg="starts running from watch version: 142715" pkg=controller 
time="2017-07-19T18:03:57Z" level=info msg="start watching at 142715" pkg=controller 
```

**No clusters found**
```
$  kubectl get clusters --all-namespaces
No resources found.
```

**Comment by arthur0** [comment]
https://github.com/kubernetes/charts/issues/728

**Comment by arthur0** [comment]
It seems me a problem of the etcd-operator and not of the helm chart .
I deployed the etcd-operator without a chart, after that, I tried to create the etcd-cluster:
```
apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "example-etcd-cluster"
spec:
  size: 3
  version: "3.1.8"
```

And I got the same problem: `Error: UPGRADE FAILED: apiVersion "etcd.coreos.com/v1beta1" in etcd-operator/templates/cluster.yaml is not available`

Issue closed, for now.

**Comment by arthur0** [comment]
It seems me a problem of the etcd-operator and not of the helm chart .
I deployed the etcd-operator without a chart, after that, I tried to create the etcd-cluster:
```
apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "example-etcd-cluster"
spec:
  size: 3
  version: "3.1.8"
```

And I got the same problem: `Error: UPGRADE FAILED: apiVersion "etcd.coreos.com/v1beta1" in etcd-operator/templates/cluster.yaml is not available`

Issue closed, for now.
