### ISSUE TITLE
[stable/prometheus-operator] render error

### ISSUE THREAD

**Issue by runningman84** [helm/charts#14947]
**Describe the bug**
The latest chart produces render errors in the tiller log.

**Version of Helm and Kubernetes**:
helm 2.x
k8s 1.14

**Which chart**:
stable/prometheus-operator

**What happened**:
```
kube-system/tiller-deploy-59b99695d8-jhprz[tiller]: [tiller] 2019/06/20 19:27:48 failed install prepare step: render error in "prometheus-operator/charts/grafana/templates/tests/test.yaml": template: prometheus-operator/charts/grafana/templates/tests/test.yaml:27:16: executing "prometheus-operator/charts/grafana/templates/tests/test.yaml" at <.Values.image.pullSe...>: can't evaluate field pullSecrets in type interface {}
```

**What you expected to happen**:
There should be no render errors

**How to reproduce it** (as minimally and precisely as possible):
install the latest version

**Anything else we need to know**:
I have installed the chart using weave flux:
```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.prometheus: semver:~2.10
    flux.weave.works/tag.alertmanager: semver:~0.17
    flux.weave.works/tag.grafana: semver:~6.2
    #flux.weave.works/locked: 'true'
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 5.12.3
  releaseName: prometheus
...
```
I have not configured any pull secret.
