### ISSUE TITLE
[nginx-ingress] Add default-ssl-certificate flag

### ISSUE THREAD

**Issue by Jank1310** [helm/charts#1495]
**Which chart**: nginx-ingress

Add the **default-ssl-certificate** flag to the controller-deployment. The flag is documented here: https://github.com/kubernetes/ingress/tree/master/controllers/nginx#default-ssl-certificate.

**Comment by mpalumbo7** [comment]
This was debated previously, with the conclusion being that you should use the extraArgs property instead of a bespoke default-ssl-certificate property.

So you can set the default SSL cert secret like this:
```yaml
controller:
  extraArgs:
    default-ssl-certificate: kube-system/tls-secret
```
However, I noticed the values.yaml still has the controller.default-ssl-certificate value, despite it not being used anywhere.
