### ISSUE TITLE
[stable/concourse] Lost OIDC setting on main team, when web pod restarted

### ISSUE THREAD

**Issue by yue-wen** [helm/charts#14984]
**Describe the bug**

Lost OIDC setting of main team, when web pod recreated

**Version of Helm and Kubernetes**:

Helm:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/concourse
version: 5.3.0

**What happened**:

Lost OIDC setting of main team, when web pod restarted.

**What you expected to happen**:

Keep the setting, when web pod restarted

**How to reproduce it** (as minimally and precisely as possible):

I have two teams setting: **main** and **shared**

#### Role setting
main_role.yaml: 

```yaml
roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["/ci/main/owner"]
- name: member
  oidc:
    groups: ["/ci/main/member"]
- name: pipeline-operator
  oidc:
    groups: ["/ci/main/pipeline-operator"]
- name: viewer
  oidc:
    groups: ["/ci/main/viewer"]
```

shared_role.yaml: 

```yaml
roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["/ci/shared/owner"]
- name: member
  oidc:
    groups: ["/ci/shared/member"]
- name: pipeline-operator
  oidc:
    groups: ["/ci/shared/pipeline-operator"]
- name: viewer
  oidc:
    groups: ["/ci/shared/viewer"]
```
#### Set up Role

```bash
TARGET=main
fly -t $TARGET set-team -n main -c main_role.yaml
fly -t $TARGET set-team -n shared -c shared_role.yaml
```
#### Check teams details
````
fly -t main teams --details
````
<pre><b>name/role</b>                  <b>users</b>            <b>groups</b>                                      
main/member                none             oidc:/ci/main/member              
main/owner                 local:admin      oidc:/ci/main/owner               
main/pipeline-operator     none             oidc:/ci/main/pipeline-operator   
main/viewer                none             oidc:/ci/main/viewer                       
shared/member              none             oidc:/ci/shared/member            
shared/owner               local:admin      oidc:/ci/shared/owner             
shared/pipeline-operator   none             oidc:/ci/shared/pipeline-operator 
shared/viewer              none             oidc:/ci/shared/viewer </pre>

## Actual Results

After web  pod recreated

````
fly -t main teams --details
````
<pre><b>name/role</b>                  <b>users</b>            <b>groups</b>                                      
main/owner                 local:admin      oidc:/ci/main/owner               
shared/member              none             oidc:/ci/shared/member            
shared/owner               local:admin      oidc:/ci/shared/owner             
shared/pipeline-operator   none             oidc:/ci/shared/pipeline-operator 
shared/viewer              none             oidc:/ci/shared/viewer </pre>

The main team has only owner role setting, other setting are lost. 

**Anything else we need to know**:

This is because in helm  [concourse/templates/web-deployment.yaml](https://github.com/concourse/charts/blob/master/stable/concourse/templates/web-deployment.yaml
) , the  env  `CONCOURSE_MAIN_TEAM_OIDC_GROUP` reset the main team oidc setting, when web pod restarted or recreated.
``` yaml
{{- if .Values.concourse.web.auth.mainTeam.oidc.group }}
 - name: CONCOURSE_MAIN_TEAM_OIDC_GROUP
   value: {{ .Values.concourse.web.auth.mainTeam.oidc.group | quote }}
{{- end }}
```
The main/owner role was define by web web-deployment env. Other addition oidc setting are set up after concourse deployed through fly cli. 

If does not set ` {{ .Values.concourse.web.auth.mainTeam.oidc.group  }}`, the oidc setting of main team will remove completely.

**Comment by liuyuewen91** [comment]
We can mount roles config yaml into pods, and  in `{{ .Values.concourse.web.auth.mainTeam.config }}` set up the yaml file path.
 
### In `values.yaml` at `{{ .Values.concourse.web.auth.mainTeam }}` add
```yaml
mainTeam:
  config: /concourse-auth/main-roles-config
  mainRolesConfig: |-
    roles:
    - name: owner
      local:
        users: ["admin"]
      oidc:
        groups: ["/ci/main/owner"]
    - name: member
      oidc:
        groups: ["/ci/main/member"]
    - name: pipeline-operator
      oidc:
        groups: ["/ci/main/pipeline-operator"]
    - name: viewer
      oidc:
        groups: ["/ci/main/viewer"]
```

### In `web-secrets.yaml` add
```yaml
  {{- if .Values.concourse.web.auth.mainTeam.mainRolesConfig }}
  main-roles-config: {{ .Values.concourse.web.auth.mainTeam.mainRolesConfig | b64enc | quote }}
  {{- end }}
```

### In `web-deployment.yaml` add

at `spec.template.spec.volumes[name: auth-keys]` add
```yaml
{{- if .Values.concourse.web.auth.mainTeam.mainRolesConfig }}
- key: main-roles-config
  path: main-roles-config
{{- end }}
```

Your can also use `{{.Values.web.additionalVolumeMounts}}` and ` {{.Values.web.additionalVolumes}}` mount your roles config yaml.
