### ISSUE TITLE
[stable/ambassador] AMBASSADOR_ID not set on ambassador-pro containers

### ISSUE THREAD

**Issue by bloxgate** [helm/charts#15025]
**Describe the bug**
When using Ambassador Pro and a non-default AMBASSADOR_ID, the environment variable needs to be set on both containers, as stated [here](https://www.getambassador.io/reference/running/#ambassador_id). However, AMBASSADOR_ID is only set on the ambassador container.

**Version of Helm and Kubernetes**:
Helm: v2.13.1
Kubernetes: 1.10.11

**Which chart**:
`stable/ambassador` v2.8.2

**What happened**:
A pod containing `ambassador` and `ambassador-pro` containers was created. The `AMBASSADOR_ID` environment variable was only set on the `ambassador` container.

**What you expected to happen**:
The `AMBASSADOR_ID` variable is set on both the `ambassador` and `ambassador-pro` containers.

**How to reproduce it** (as minimally and precisely as possible):
Install the helm chart with the following values:
```yaml
daemonSet: true

env:
  AMBASSADOR_ID: "ambassador-staging"

pro:
  enabled: true
  licenseKey:
    value: [license key here]
```

**Anything else we need to know**:
![image](https://user-images.githubusercontent.com/2079324/60045006-4f803900-9689-11e9-8bfa-4d4855d211cd.png)
