### ISSUE TITLE
[stable/graylog] .snapshot in journal volume causes init pod crash loop

### ISSUE THREAD

**Issue by oscarlofwenhamn** [helm/charts#15040]
**Describe the bug**
Edit: I realized the fault seems to lie in the init pod.
Graylog init pod won't complete after manual (and automatic) installation of dependencies.

**Version of Helm and Kubernetes**:
Helm: v2.14.1
Kubernetes:
- Client: v1.14.0
- Server: v1.14.2

**Which chart**:
stable/graylog

**What happened**:
After following the Manual Install Dependencies + Install Chart [guide](hub.helm.sh/charts/stable/graylog), mongodb and elasticsearch seem to be starting correctly but the Graylog pod is stuck in a CrashLoop. The same thing happens when I run the Quick Installation.
```sh
graylog-0                               0/1     Init:0/1                12         38m
graylog-0                               0/1     Init:Error              12         38m
graylog-0                               0/1     Init:CrashLoopBackOff   12         38m
```
Commands used:
- `helm install --namespace "graylog" -n "mongodb" stable/mongodb-replicaset`
- `helm install --namespace "graylog" -n "elasticsearch" stable/elasticsearch`
- `helm install --namespace "graylog" -n "graylog" stable/graylog --set tags.install-mongodb=false --set tags.install-elasticsearch=false --set graylog.mongodb.uri=mongodb://mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.graylog.svc.cluster.local:27017/graylog?replicaSet=rs0 --set graylog.elasticsearch.hosts=http://elasticsearch-client.graylog.svc.cluster.local:9200`

Init pod logs:
```sh
λ kubectl logs -n graylog graylog-0 -c setup
Connecting to storage.googleapis.com (172.217.20.48:443)
wget: note: TLS certificate validation not implemented
saving to '/k8s/kubectl'
kubectl                7% |**                              | 3278k  0:00:11 ETA
kubectl               24% |*******                         |  9.9M  0:00:06 ETA
kubectl               40% |************                    | 16.6M  0:00:04 ETA
kubectl               57% |******************              | 23.4M  0:00:03 ETA
kubectl               73% |***********************         | 30.1M  0:00:01 ETA
kubectl               89% |****************************    | 36.8M  0:00:00 ETA
kubectl              100% |********************************| 41.1M  0:00:00 ETA
'/k8s/kubectl' saved
chown: /usr/share/graylog/data/journal/.snapshot/hourly.2019-06-25_1205: Read-only file system
chown: /usr/share/graylog/data/journal/.snapshot/hourly.2019-06-25_1205: Resource temporarily unavailable
chown: /usr/share/graylog/data/journal/.snapshot/hourly.2019-06-25_1305: Read-only file system
chown: /usr/share/graylog/data/journal/.snapshot/hourly.2019-06-25_1305: Resource temporarily unavailable
chown: /usr/share/graylog/data/journal/.snapshot/hourly.2019-06-25_1105: Read-only file system
chown: /usr/share/graylog/data/journal/.snapshot/hourly.2019-06-25_1105: Resource temporarily unavailable
chown: /usr/share/graylog/data/journal/.snapshot: Read-only file system
chown: /usr/share/graylog/data/journal/.snapshot: Read-only file system
```

**What you expected to happen**:
For Graylog to get deployed and to start.

**Comment by oscarlofwenhamn** [comment]
The .snapshot directory it complains about when trying to run `chown -R 1100:1100 ...` already is owned by 1100:1100 as far as I can see, but for some reason the .snapshot directory complains as it _for some reason_ seems to be set to Read Only.. I don't understand why the .snapshot directory is even there, since afaik it should be and empty volume. 

I am running an nfs storage for my cluster, where .snapshots seem to be made on a root level, but they shouldn't be mounted into the volumes since these are placed as sub-directories.

After editing the StatefulSet `graylog` so that the init container no longer `chown`s the directory, the pod starts by instead I get the following errors:

**Comment by oscarlofwenhamn** [comment]
```sh
2019-06-26 12:49:14,847 ERROR   [LogManager] - There was an error in one of the threads during logs loading: kafka.common.KafkaException: Found directory /usr/share/graylog/data/journal/.snapshot, '.snapshot' is not in the form of topic-partition
```
This is at the top of the flow of errors, further strengthening my feeling that .snapshot shouldn't be there in the first place..

**Comment by oscarlofwenhamn** [comment]
I found a workaround by modifying the StatefulSet into using subPath instead:
```yaml
volumeMounts:
  - mountPath: /usr/share/graylog/data
    name: data
    subPath: journal
```
This makes moves the mount point (and .snapshot directory) one level up, avoiding the issue. It is still a workaround, and I'm going to want to keep looking for a more permanent solution, but it is not a Helm Chart issue.

**Comment by xavierzhao** [comment]
@oscarlofwenhamn Hi, same problem, could you help me to share your solution if you solved it.Thanks!

**Comment by oscarlofwenhamn** [comment]
Hi, in the end we managed to get our storage service provider to configure our nfs storage so that `.snapshot` directories are no longer visible in the mounts. 
Are you using an nfs storage as well, and is it self-hosted or provided by someone? If you want I can contact our provider and see what configuration they did. 

The workaround that worked before we got the configuration fixed was as follows:
(*Including `--namespace` is optional*)
- Install mongodb-replicaset and elasticsearch (v 6.8.1)
```sh
$ helm install --name mongodb-replicaset --namespace graylog stable/mongodb-replicaset

# We add the elastic repo since the 'stable' repo will be deprecated further on
$ helm repo add elastic https://helm.elastic.co
# We run elasticsearch version 6.8.1 since Graylog v3 currently is incompatible with later versions.
$ helm install elastic/elasticsearch --name elasticsearch --namespace graylog --set imageTag=6.8.1

# Wait for deployments to complete, then you can test to see all went well
$ helm test mongodb-replicaset
$ helm test elasticsearch
```
- Extraxt Graylog deployment template
```sh
$ helm fetch --untar stable/graylog
$ helm dependency update graylog 
$ helm template graylog  -n graylog -f graylog-values.yaml > graylog-template.yaml
```
```yaml
#graylog-values.yaml
tags:
  install-mongodb: false
  install-elasticsearch: false
graylog:
  mongodb:
    uri: "mongodb://mongodb-replicaset-0.mongodb-replicaset.graylog.svc.cluster.local:27017/graylog?replicaSet=rs0"
  elasticsearch:
    hosts: "http://elasticsearch-client.graylog.svc.cluster.local:9200"
# + any further values
```
- Add `namespace: graylog` to all objects in `graylog-template.yaml`
- Add `subPath: mount` to all `volumeMounts` where a persistent volume is used (in this case `name: journal`) in `graylog-template.yaml`
```yaml
...
        volumeMounts:
        - mountPath: /usr/share/graylog/data/journal
          name: journal
+         subPath: mount
...
        volumeMounts:
        - mountPath: /usr/share/graylog/data/journal
          name: journal
+         subPath: mount
...
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: journal
```
This can be done quickly in vim by typing `:g/name: <volume-name>/norm osubPath: mount`. *Please note the lack of a space between "o" and "subPath"*, and note that this will add the line to the volumeClaimTemplate as well, which needs to be removed. "`mount`" can also be called something else.
- Deploy
```sh
$ kubectl apply -f graylog-template.yaml 
```

---
Since this is no longer our primary way of deploying some errors may have occurred, please let me know if something seems off and I will follow up.
