### ISSUE TITLE
[stable/kibana] Error with tpl in Kibana deployment

### ISSUE THREAD

**Issue by spica29** [helm/charts#15041]
**Describe the bug**
I saw you recently merged pull request #14905. Since this PR I cannot deploy Kibana helm chart. Problem is with variable env. The error I get is: 
**"Error: render error in \"kibana/templates/deployment.yaml\": template: kibana/templates/deployment.yaml:141:20: executing \"kibana/templates/deployment.yaml\" at <tpl>: wrong number of args for tpl: want 2 got 1"**

**Version of Helm and Kubernetes**:
Helm: v2.14.0
Kubernetes: v1.14.2

**Which chart**:
stable/kibana

**How to reproduce it** (as minimally and precisely as possible):
1. Add variables to my own variables file, for example:
```
env:
  ELASTICSEARCH_HOSTS: http://elasticsearch-client:9200
  SERVER_DEFAULTROUTE: /app/kibana
  SERVER_REWRITEBASEPATH: false
  LOGGING_VERBOSE: true
```

2. Install helm chart:
` helm install --name kibana stable/kibana -f kibana.yaml --tiller-namespace {{ tiller_namespace}} --namespace {{ namespace }} `
