### ISSUE TITLE
[incubator/kafka] Prometheus operator or alertmanager is not updated when prometheus.operator is enabled. 

### ISSUE THREAD

**Issue by ashishxooa** [helm/charts#15056]
**Describe the bug**
I am trying to install kafka using the helm chart and I have enabled for prometheus operator. However I dont see any service being exposed or any change done to Prometheus configuration to scrape this service endpoints. 

```
prometheus:
  ## Prometheus JMX Exporter: exposes the majority of Kafkas metrics
  jmx:
    enabled: true

  ## Prometheus Kafka Exporter: exposes complimentary metrics to JMX Exporter as below.   kafka:
    enabled: true

  operator:
    enabled: true

  operator:
    serviceMonitor:
      selector: "k8s-app: prometheus"
```

**Version of Helm and Kubernetes**:

**Helm version**
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

**K8 version**

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[incubator/kafka]

**What you expected to happen**:
It should register itself as a target to prometheus operator. 

**How to reproduce it** (as minimally and precisely as possible):
Just install the chart.
