### ISSUE TITLE
[stable/prometheus-operator] configured targets 'kube-controller-manager', 'kube-scheduler' unable to be scraped

### ISSUE THREAD

**Issue by poidag-zz** [helm/charts#15084]
**Describe the bug**
Targets for configured ServiceMonitors `kube-controller-manager` and `kube-scheduler` unable to be reached by Prometheus

**Version of Helm and Kubernetes**:

```
➜  ~ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

[stable/prometheus-operator]

**What happened**:

Installed default installation of the prometheus-operator chart, navigated to the configured targets page and saw unreachable targets.

**What you expected to happen**:

All configured targets defined in ServiceMonitors to be up and reachable. I'm not sure what the plan for this in the future is. Whether this gets moved into node-exporter or something else. But wanted to raise this as a bug as there is red out of the box with a standard installation. Hopefully, someone here is able to let me know what the future plans for gathering metrics from these components are!

**How to reproduce it** (as minimally and precisely as possible):

`helm install stable/prometheus-operator --name prometheus --namespace monitoring`
`kubectl -n monitoring port-forward service/prometheus-operated 9090:9090`
 
 Navigate to
 
[Prometheus Targets](http://localhost:9090/targets)

**Anything else we need to know**:

[CIS Kubernetes Benchmark 1.4.0](https://www.cisecurity.org/benchmark/kubernetes/)

Sections:
`1.2.2` kube-scheduler and `1.3.7` kube-controller-manager respectively state;

`Ensure that the --address argument is set to 127.0.0.1 (Scored)`

This appears to be the default setting in [Kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details)

An example of a workaround I've implemented is as follows. A small proxy deployed to each control plane node with HostNetwork permissions and a Service/ServiceMonitor running to proxy metric scrapes for the `kube-controller-manager` and `kube-scheduler`

An example of for controller-manager below:

`main.go`

```
package main

import (
    "io"
    "log"
    "net/http"
)

func main() {
    http.HandleFunc("/metrics", fetchMetrics)
    log.Fatal(http.ListenAndServe(":8080", nil))
}
func fetchMetrics(w http.ResponseWriter, r *http.Request) {
    res, err := http.Get("http://127.0.0.1:10252/metrics")
    if err != nil {
        w.WriteHeader(http.StatusInternalServerError)
        w.Write([]byte(err.Error()))
        return
    }
    io.Copy(w, res.Body)
}
```

`Dockerfile`

```
FROM golang:1.12.5 AS build
WORKDIR /exporter

COPY cmd .

RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux GOFLAGS=-ldflags=-w go build -o /go/bin/exporter -ldflags=-s 
FROM scratch AS final
COPY --from=build /go/bin/exporter /bin/exporter
```

`manifest.yaml`

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: exporter
  name: exporter
spec:
  selector:
    matchLabels:
      app: exporter
  template:
    metadata:
      labels:
        app: exporter
    spec:
      containers:
      - command:
        - exporter
        image: quay.io/pickledrick/exporter
        imagePullPolicy: Always
        name: exporter
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exporter
    jobLabel: kube-controller-manager-exporter
    release: prometheus
  name: exporter
spec:
  ports:
  - port: 8080
    name: http-metrics
    protocol: TCP
    targetPort: 8080
  selector:
    app: exporter
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-kube-controller-manager-exporter
    release: prometheus
  name: prometheus-prometheus-operator-kube-controller-manager-exporter
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: exporter
```
