### ISSUE TITLE
install elasticsearch version 7.1.1

### ISSUE THREAD

**Issue by mounaBoo** [helm/charts#15081]
Hello I am new on elasticsearch and also using the helm chart to used it I want to install the helm chart you provide but I need to install version 7.1.1 of elasticsearch I ahve already chaged the values file I added this lines : 

`appVersion: "7.1.1"`

```
image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch"
  tag: "7.1.1"
```

and I enabled xpack as mentioned 
```
cluster:
  name: "elasticsearch"
  xpackEnable: true

  config: {}

  additionalJavaOpts: ""
  bootstrapShellCommand: ""
  env:
    XPACK_MONITORING_ENABLED: true
```

now I am getting this error 

the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured 

can someone help me please I need to install version 7.1.1 with xpack enabled in it .

thank you in advance
