### ISSUE TITLE
[stable/grafana] unable to import dashboard : download_dashboards.sh failed

### ISSUE THREAD

**Issue by obeyler** [helm/charts#15083]
**Describe the bug**
I want to upload grafana dashboard  by the id but I'm behind a proxy
even with the env http_proxy,https_proxy,no_proxy set the pod doesn't start
the 

**Version of Helm and Kubernetes**:
K8S 1.14.2

**Which chart**:
Stable/grafana
```
      rbac:
        pspEnabled: true
        create: true
      serviceAccount:
        name: tiller
        create: true

      deploymentStrategy: RollingUpdate
      image:
        repository: grafana/grafana
        tag: 5.2.2
        pullPolicy: IfNotPresent
      securityContext:
        runAsUser: 472
        fsGroup: 472

      downloadDashboardsImage:
        repository: appropriate/curl
        tag: latest
        pullPolicy: IfNotPresent

      plugins:
      persistence:
        enabled: false

      adminUser: admin
      adminPassword:XXXX
      grafana.ini:
        server:
          root_url: https://ingress-mydomain/grafana/
      dashboards:
        default:
          kubernetes-cluster:
            gnetId: 7249
            datasource: Prometheus
          nginx-ingress:
            gnetId: 9614
            datasource: Prometheus
          kubernetes-cluster-monitoring-prometheus:
            gnetId: 8588
            datasource: Prometheus
      extraEmptyDirMounts:
      - name: dashboards
        mountPath: /var/lib/grafana/dashboards/default
      sidecar:
        imagePullPolicy: IfNotPresent
        datasources:
          enabled: true
          label: grafana_datasource
        dashboards:
          enabled: true
          label: grafana_dashboard
      env:
        https_proxy: ((https_proxy))
        http_proxy: ((http_proxy))
        no_proxy: ((no_proxy))
        HTTPS_PROXY: ((https_proxy))
        HTTP_PROXY: ((http_proxy))
        NO_PROXY: ((no_proxy))


```
**What happened**:

The grafana deployment fail
![image](https://user-images.githubusercontent.com/23224162/60220576-c6c6f000-9876-11e9-9eb3-3bf6450b06fb.png)

the download-dashboard container is not able to download dashboard :

```
kubectl logs grafana-5fc4b5946f-thm2k -c download-dashboards -n monitoring
/etc/grafana/download_dashboards.sh: line 8: can't create /var/lib/grafana/dashboards/default/kubernetes-cluster.json: nonexistent directory
```

**What you expected to happen**:
I espect that dashboards can be uploaded even if my K8S is located behind a proxy
