### ISSUE TITLE
[stable/concourse] Do not add local users if local auth disabled

### ISSUE THREAD

**Issue by cirocosta** [helm/charts#15124]
**Is your feature request related to a problem? Please describe.**

Currently, consumers of the Chart who disable local authentication (but enable
other forms of auth) and forget to remove the default addition of the "test"
user to the `main` team end up with a `CrashloopBackoff`.

To reproduce:

```yaml
concourse:
  web:
    localAuth:
      enabled: false
```

Then, after installing, see that the `web` component keeps failing, with the
following message in the logs:

```
server: no connectors specified
```

To fix that, one needs to also set `concourse.web.auth.mainTeam.localUser` to a
zero value (something not very trivial for a consumer of Concourse to figure
out):

```yaml
concourse:
  web:
    auth:
      mainTeam:
        localUser: ""
    localAuth:
      enabled: false
```

**Describe the solution you'd like**

Be smarter about the environment variables that get set depending on whether
`localAuth` is enabled or not.

More specifically, this drills down to having conditionals where `CONCOURSE_*LOCAL*`
environment variables get set to account for the fact that it might have been
disabled through `concourse.web.localAuth.enabled: false`.

**Describe alternatives you've considered**

**Additional context**

The `server: no connectors specified` error message comes from `concourse/dex`,
our fork of https://github.com/dexidp/dex, which is the piece in Concourse that
deals with authentication.

If you search for that error in `concourse/concourse`, that'll not show up.
