### ISSUE TITLE
[stable/nginx-ingress] Add StatefulSet kind

### ISSUE THREAD

**Issue by chrono2002** [helm/charts#15126]
Hello

I'm trying to mount PVC to my controller. I've succeed only when I got 1 replica, but when I add more replicas or change kind to Daemonset all other pod stuck waiting for PVC to come, which is already claimed by the first replica.
```
pod/nginx-nginx-ingress-controller-b2sct   0/1     Pending   0          30m
pod/nginx-nginx-ingress-controller-jxczl   1/1     Running   0          30m
pod/nginx-nginx-ingress-controller-mb4bn   0/1     Pending   0          30m
pod/nginx-nginx-ingress-controller-vrd4d   0/1     Pending   0          30m
pod/nginx-nginx-ingress-controller-xmbjl   0/1     Pending   0          30m
```

I describe PVC like this:
```
  extraVolumeMounts:
  - mountPath: /var/cache/nginx
    name: cache

  extraVolumes:
  - name: cache
    persistentVolumeClaim:
      claimName: nginx-cache
```

Why don't you make StetefulSet with volumeClaimTemplates instead to solve this issue?
```
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: sdg1
    spec:
      storageClassName: "local"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 372G
  - metadata:
      name: sdh1
    spec:
      storageClassName: "local"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 372G
```
