### ISSUE TITLE
[stable/oauth2-proxy]can't evaluate field config at <.Values.config.exist...> _helpers.tpl

### ISSUE THREAD

**Issue by thodquach** [helm/charts#15148]
**Describe the bug**
After i fill my values.yaml file, i just print here the change part:
```
# Oauth client configuration specifics
config:
  # OAuth client ID
  clientID: "xxx"
  # OAuth client secret
  clientSecret: "xxx"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  # Use an existing secret for OAuth2 credentials (see secret.yaml for required fields)
  # Example:
  # existingSecret: secret
  cookieSecret: "xxx=="
  google:
    adminEmail: system@admin.com
    serviceAccountJson: xxx
    # Alternatively, use an existing secret (see google-secret.yaml for required fields)
    # Example:
    # existingSecret: google-secret
  # Default configuration, to be overridden
  configFile: |-
    email_domains = [ "admin.com" ]
    upstreams = [ "http://ex.admin.com" ]
  # Custom configuration file: oauth2_proxy.cfg
  # configFile: |-
  #   pass_basic_auth = false
  #   pass_access_token = true
  # Use an existing config map (see configmap.yaml for required fields)
  # Example:
  # existingConfig: config
```
I run this command:
```
helm install stable/oauth2-proxy --name my-release -f values.yaml
```
And this is the console log:
```
Error: UPGRADE FAILED: render error in "oauth2-proxy/templates/deployment.yaml": template: oauth2-proxy/templates/_helpers.tpl:38:14: executing "oauth2-proxy.secretName" at <.Values.config.exist...>: can't evaluate field config in type interface {}
```

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Which chart**:
```
stable/oauth2-proxy
```

**What happened**:
It can not get <.Values.config.exist...>
When the chart check that field exist or not

**What can i do to fix it?**

**Comment by masterkain** [comment]
I have the same issue, how to fix?

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system-ingress
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: oauth2-proxy
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: oauth2-proxy
    version: 1.2.0
  values:
    config:
      clientID: "blabla"
      clientSecret: "blabla"
      cookieSecret: "blabla"
      google:
        adminEmail: blabla
        serviceAccountJson: {"web":{"client_id":"xxxxxxxxx..."]}}
    ingress:
      enabled: true
      hosts:
        - auth.int.mydomain.com
      annotations:
        kubernetes.io/ingress.class: nginx
    extraArgs:
      whitelist-domain: .int.mydomain.com
      cookie-domain: .int.mydomain.com
      provider: google
```

**Comment by thodquach** [comment]
Hello @masterkain,
Can you show me the file `_helpers.tpl` in here?

**Comment by masterkain** [comment]
hello @thodquach it's the one provided with the chart: https://github.com/helm/charts/blob/master/stable/oauth2-proxy/templates/_helpers.tpl

**Comment by masterkain** [comment]
I have the same issue even specifying a created secret, oof

```
  values:
    config:
      existingSecret: oauth2-proxy-creds
```

**Comment by thodquach** [comment]
Hi @masterkain ,
Below are my values.yaml for oauth2-proxy, hope this can help you find the way to make out.
```
# Oauth client configuration specifics
config:
  # OAuth client ID
  clientID: "<clientID>"
  # OAuth client secret
  clientSecret: "<clientSecret>"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  # Use an existing secret for OAuth2 credentials (see secret.yaml for required fields)
  # Example:
  # existingSecret: secret
  cookieSecure: "true"
  cookieName: "_oauth2_proxy"
  cookieSecret: "<cookie secret>"
  google: {}
    # adminEmail: xxxx
    # serviceAccountJson: xxxx
    # Alternatively, use an existing secret (see google-secret.yaml for required fields)
    # Example:
    # existingSecret: google-secret
  # Default configuration, to be overridden
  configFile: |-
    email_domains = [ "example.com" ]
  # upstreams = [ "" ]

  # Custom configuration file: oauth2_proxy.cfg
  # configFile: |-
  #   pass_basic_auth = false
  #   pass_access_token = true
  # Use an existing config map (see configmap.yaml for required fields)
  # Example:
  # existingConfig: config
```
-  Command to create cookie secret: ```╰─➤  openssl rand -base64 32```
