### ISSUE TITLE
[stable/mysql] test-configmap.yaml always deploys to the default namespace

### ISSUE THREAD

**Issue by costimuraru** [helm/charts#15183]
**Describe the bug**
When trying to deploy the stable/mysql, some (test) resources get deployed to the `default` namespace, even though the desired behavior is to deploy it to a dedicated ns.

**Version of Helm and Kubernetes**:

**Which chart**:
stable/mysql

**What happened**:
Some resources did not get created in the required namespace.

**What you expected to happen**:
The resources should be deployed to the desired namespace.

**How to reproduce it** (as minimally and precisely as possible):

```
helm fetch stable/mysql
helm template mysql-1.2.1.tgz --namespace myns
```

Notice the `namespace` is missing below: 
```
# Source: mysql/templates/tests/test-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-mysql-test
  labels:
    app: release-name-mysql
    chart: "mysql-1.2.1"
    heritage: "Tiller"
    release: "release-name"
```

```
apiVersion: v1
kind: Pod
metadata:
  name: release-name-mysql-test
  labels:
    app: release-name-mysql
    chart: "mysql-1.2.1"
    heritage: "Tiller"
    release: "release-name"
  annotations:
    "helm.sh/hook": test-success
```

**Anything else we need to know**:
