### ISSUE TITLE
[stable/elasticsearch] How to use the keystore with a secret

### ISSUE THREAD

**Issue by maximerenou50** [helm/charts#15182]
_(This is a question/support request, not an issue)_

Hello,

I would like to configure ES backups to S3. I installed the [repository-s3](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3.html) plugin, all good but the tricky part comes when I want to configure the credentials to access the bucket. I need to configure the Keystore to add two secure values:
* s3.client.default.access_key
* s3.client.default.secret_key

According to the README, we can use the `cluster.keystoreSecret` setting to specify the name of the secret holding secure options. But when I look at how this secret is used, it seems to be directly mounted to:
```/usr/share/elasticsearch/config/elasticsearch.keystore```
(this seems to be the PR that added that functionality: https://github.com/helm/charts/pull/7477/files)

If I exec into one pod and look into that file, it's a binary and I cannot read it directly.
I tried to create a secret with something like that:
```
apiVersion: v1
kind: Secret
metadata:
  name: eskeystore
data:
  s3.client.default.access_key: xxx
  s3.client.default.secret_key: xxx
```
and set `cluster.keystoreSecret` to `eskeystore` but it doesn't work. 

So my question is: how can I generate the Keystore with the 2 values written above?

Thanks a lot!

**Comment by macgyver603** [comment]
You actually need to [add those settings to an ES keystore](https://www.elastic.co/guide/en/elasticsearch/plugins/6.8/repository-s3-client.html) and store the keystore as the secret with something like:

```
kubectl create secret generic eskeystore --from-file=./elasticsearch.keystore
```

Then, just make sure `cluster.keystoreSecret` matches the secret name and restart your ES nodes for the change to take effect. I had to do this with a cluster I had already deployed, so I just added the S3 settings to the keystore on one of the nodes in the cluster, used `kubectl` to copy the keystore to my local machine, and then ran the above command to deploy it in my ES cluster's namespace.

**Comment by maximerenou50** [comment]
Thanks a lot @macgyver603! I did as you said, I manually added the values into the keystore, and I used `kubectl cp` to copy the file from the container to my local machine. Then I created the secret containing the keystore and I configured the backup for ES (with something like that):
```
curl -H 'Content-Type: application/json' -X PUT \
-d '{"type": "s3", "settings": { "bucket": "my.awesome.bucket", "base_path": "elasticsearch/backup", "compress": "true", "storage_class": "standard" }}' \
http://elasticsearch-client.elastic-stack.svc:9200/_snapshot/backup
```
Then in my elasticsearch curator configuration, I configured the snapshot:
```
configMaps:
  action_file_yml: |-
    ---
    actions:
      1:
        action: snapshot
        description: "Create snapshot"
        options:
          repository: backup
          continue_if_exception: False
          wait_for_completion: True
          disable_action: False
        filters:
          - filtertype: pattern
            kind: regex
            value: ".*$"
```
I needed to fix the policy as well but I just followed the plugin documentation.

And now it's working, I get snapshots uploaded to S3! :)

That's a fairly good solution, I would have hoped not to have to do those manual steps for the Keystore, it's a bit dodgy but it's gonna be good enough for now!
