### ISSUE TITLE
Chart not using some parameters specified in values.yaml - stable/mongo 5.20.0

### ISSUE THREAD

**Issue by coreyperkins** [helm/charts#15221]
The current secrets template does not appear to be honoring the following items, they have been specified in my values like so:
```
mongodbDatabase: "ARandomDatabase"
mongodbUsername: "admin"
mongodbPassword: "punkybrewster"
mongodbRootPassword: "punkywunkybrewster"
```

The secrets.yaml file in 5.20.0 looks like this:
```
{{ if and .Values.usePassword (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.mongodbRootPassword }}
  mongodb-root-password:  {{ .Values.mongodbRootPassword | b64enc | quote }}
  {{- else }}
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.mongodbUsername .Values.mongodbDatabase }}
  {{- if .Values.mongodbPassword }}
  mongodb-password:  {{ .Values.mongodbPassword | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.replicaSet.enabled }}
  {{- if .Values.replicaSet.key }}
  mongodb-replica-set-key:  {{ .Values.replicaSet.key | b64enc | quote }}
  {{- else }}
  mongodb-replica-set-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
```

Could be I am missing something, but I think my values should be honored rather than the ones in the base chart. I will be glad to provide more feedback if it will help.

Thanks,

Corey

**Comment by tompizmor** [comment]
Hi Corey, 

Yes, your values should be honored. I just try to reproduce the issue but I couldn't:

I set the following properties in my values.yaml:


```diff
-# mongodbRootPassword:
+mongodbRootPassword: qwer1234

 ## MongoDB custom user and database
 ## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
 ##
-# mongodbUsername: username
-# mongodbPassword: password
-# mongodbDatabase: database
+mongodbUsername: tomas
+mongodbPassword: asdf1234
+mongodbDatabase: tomasdb
```
After deploying the chart from local copy with this command, `helm install --name mongodb`, this is the secret I get:

```
$ kubectl get secret -o yaml mongodb
apiVersion: v1
data:
  mongodb-password: YXNkZjEyMzQ=
  mongodb-root-password: cXdlcjEyMzQ=
kind: Secret
metadata:
  creationTimestamp: "2019-07-03T06:52:30Z"
  labels:
    app: mongodb
    chart: mongodb-5.20.0
    heritage: Tiller
    release: mongodb
  name: mongodb
  namespace: tomas
  resourceVersion: "144595057"
  selfLink: /api/v1/namespaces/tomas/secrets/mongodb
  uid: 2065a5de-9d5f-11e9-b05f-42010a9601ac
type: Opaque
```

And finally, if we decrypt the data:

```
$ echo "YXNkZjEyMzQ=" | base64 -D
asdf1234

$ echo "cXdlcjEyMzQ=" | base64 -D
qwer1234
```

Your issue is the secret not being created or it is created but with the default values?
Can you let me know how did you deploy the chart?

**Comment by coreyperkins** [comment]
@tompizmor I had success using this suggestion (https://helm.sh/docs/developing_charts/#alias-field-in-requirements-yaml) from SO (https://stackoverflow.com/questions/56862322/how-to-use-my-values-yamls-values-in-stable-mongo-subcharts-secrets/56866796#56866796). 

In a nutshell my chart's values file had to use an alias for the mongodb dependency.

my values.yaml
```
DbName: ADbName
mongodbsubchart:
  mongodbDatabase: "ADbName"
  mongodbUsername: "admin"
  mongodbPassword: "anadminpassword"
  mongodbRootPassword: "arootpassword"
```

Then inside my requirements.yaml I used an alias like so:

```
dependencies:
  - name: mongodb
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 5.20.0
    alias: mongodbsubchart
```

Oh yeah, I was deploying my chart like so: 

`helm install --name mychartname ./mychartname `

I hope that helps to clarify the issue. Closing since I found a solution.

Thanks for jumping in!

Corey

**Comment by tompizmor** [comment]
Oh, I was missing that you were using MongoDB as a dependency. In that case, you would have to add the following values to your parent chart:

```
mongodb:
  mongodbDatabase: "ARandomDatabase"
  mongodbUsername: "admin"
  mongodbPassword: "punkybrewster"
  mongodbRootPassword: "punkywunkybrewster"
```

The alias thing you added in the requirements yaml is only needed if you want to change the name to access the MongoDB values. However, by default is `mongodb` (the name of the subchart )
