### ISSUE TITLE
[stable/nginx-ingress] nodePort for tcp/udp requires explicit port mapping

### ISSUE THREAD

**Issue by aegershman** [helm/charts#15234]
**Describe the bug**

Change in #15203 requires setting `controller.service.nodePorts.tcp` with explicit port mappings. Formerly you could allow for random assignments.

If left uncommented, the following code will cause the error message below:

```yml
controller:
  replicaCount: 2
  # service:
  #   nodePorts:
  #     tcp:
  #       2222: 30090

tcp:
  2222: "concourse-web/concourse-web-web:2222"
```

```sh
Error: UPGRADE FAILED: render error in "nginx-ingress/templates/controller-service.yaml": template: nginx-ingress/templates/controller-service.yaml:66:13: executing "nginx-ingress/templates/controller-service.yaml" at <index $.Values.controller.service.nodePorts.tcp $key>: error calling index: index of untyped nil
```

**Version of Helm and Kubernetes**:
helm 2.14.0, kubernetes 1.13.latest

**Which chart**:
nginx-ingress

See also: https://github.com/helm/charts/pull/15203#issuecomment-508144697
