### ISSUE TITLE
[stable/elastic-stack] Not able to pass values to ElasticSearch dependent chart

### ISSUE THREAD

**Issue by MohammedFadin** [helm/charts#15281]
**Describe the bug**
When adding additional values to the Values.yaml under ElastichSearch section, they are not passed to the dependent subchart -- ElasticSearch

**Version of Helm and Kubernetes**:
Helm Version 2.9.1
Kubernetes Version 1.14

**Which chart**:
Stable/elastic-stack

**What happened**:
The default values from the dependent subschart are not being overriden by the elastic-stack chart.

**What you expected to happen**:
The default values from the dependent subschart are supposed to be overriden if values passed from the parent chart (elastic-stack)

**How to reproduce it** (as minimally and precisely as possible):
Add the following values to your Elastic-Stack values.yaml
```
elasticsearch:
  enabled: true (PASSED to Dependency chart)
  clusterName: "elasticsearch" (PASSED to Dependency chart)
  roles: (NOT PASSED to Dependency chart)
    master: "true"
    ingest: "true"
    data: "true"
  replicas: 1 (PASSED to Dependency chart)
  labels:
    failure-domain.beta.kubernetes.io/zone: netherland
  minimumMasterNodes: 2
  nodeSelector:
    node-role.kubernetes.io/my-critical-node:"true" (NOT PASSED to Dependency chart)
  persistence:
    - enabled: true (PASSED to Dependency chart)
      storageClass: mystorage (NOT PASSED to Dependency chart)
      accessMode: ReadWriteOnce (NOT PASSED to Dependency chart)
      size: 50Gi (NOT PASSED to Dependency chart)
```

**Anything else we need to know**:
None
