### ISSUE TITLE
[stable/traefik] add values for volumes and volumeMounts

### ISSUE THREAD

**Issue by ghost** [helm/charts#15300]
**Is your feature request related to a problem? Please describe.**
I have a log scraper that needs access to the traefik access logs. I expose the access logs by writing them to a directory in the traefik container `/var/log/traefik/access.log`. I need to be able to expose those logs to the underlying host through a volume of `hostPath`

**Describe the solution you'd like**
I would like to be able to configure volumes and volumeMounts with the values.yaml like so
```yaml
---
# traefik.values.yaml

accessLogs:
  enabled: true
  filePath: /var/log/traefik/access.log

extraVolumes: |
  - name: accesslogs
    hostPath:
      path: /var/log/traefik
      type: DirectoryOrCreate

extraVolumeMounts: |
  - mountPath: /var/log/traefik
    name: accesslogs
```

**Describe alternatives you've considered**
Haven't thought of any at the moment, I believe this would be an extensible feature of the Traefik helm chart. 

**Additional context**
