### ISSUE TITLE
[stable/heartbeat] support for loading environment variables from secrets

### ISSUE THREAD

**Issue by hkailantzis** [helm/charts#15386]
Ability to support loading environment variables from secrets, e.g. something like:

```
envsFromSecrets:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secretName
          key: username
```

Use case: e.g. Elasticsearch username and password when SSL is enabled.
