### ISSUE TITLE
[stable/nextcloud] Nextcloud sends 500 request after installing

### ISSUE THREAD

**Issue by nick-lehmann** [helm/charts#15410]
**Describe the bug**
After installing nextcloud via helm and waiting for all pods to be up and running, I get a 500 response when accessing the login page.

**Version of Helm and Kubernetes**:

Helm

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```
Kubernetes

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"2019-06-08T16:22:01Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

Nextcloud (stable/nextcloud)

**What happened**:

After I installed my first nextcloud instance via helm and the `values.yaml` that can be found at the end of the issue, everything worked fine. A few days later, I purchased a new domain, delete my old nextcloud (upgrading caused an error) and tried to reinstall my nextcloud instance under the new domain. While the first installation went flawless, I now receive an unstyled 500 error every time I use the browser trying to access nextcloud with the following message:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

In the kubernetes logs, I only see the following lines, which do not help to debug this problem:

```
10.244.0.57 - - [10/Jul/2019:22:30:02 +0000] "GET / HTTP/1.1" 302 954 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
10.244.0.57 - - [10/Jul/2019:22:30:03 +0000] "GET /login HTTP/1.1" 500 1236 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```

I started a bash session in the pod containing the apache trying to find further logs, without any luck.

**What you expected to happen**:

Nextcloud greets me with the default login window.

**How to reproduce it** (as minimally and precisely as possible):

Use the following values file to deploy a nextcloud installation via `helm install --namespace nextcloud -n nextcloud -f values.yaml stable/nextcloud` 

```yaml
image:
  repository: nextcloud
  tag: 16.0.1-apache
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

nextcloud:
  host: cloud.nicklehmann.sh
  username: nick
  password: very_secret
  update: 0
  datadir: /var/www/html/data
  tableprefix:
  mail:
    enabled: false

internalDatabase:
  enabled: false
  name: nextcloud

##
## External database configuration
##
externalDatabase:
  enabled: false

  ## Database host
  host:

  ## Database user
  user: nextcloud

  ## Database password
  password:

  ## Database name
  database: nextcloud

##
## MariaDB chart configuration##
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true

  db:
    name: nextcloud
    user: nextcloud
    password: very_secret

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi

redis:
  enabled: true
  usePassword: true

## Cronjob to execute Nextcloud background tasks
## ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron-jobs
##
cronjob:
  enabled: true
  # Every 15 minutes
  # Note: Setting this to any any other value than 15 minutes might
  #  cause issues with how nextcloud background jobs are executed
  schedule: "*/15 * * * *"
  annotations: {}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2

service:
  type: ClusterIP
  port: 8080
  loadBalancerIP: nil

persistence:
  enabled: true
  existingClaim: nextcloud-data

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

nodeSelector:
  role: master

tolerations: []

affinity: {}
```

I tried it using the internal database as well as with the included mariadb deployment. Both resulted in the 500 error.

**Anything else we need to know**:

```
kubectl --namespace nextcloud get pods
NAME                         READY   STATUS      RESTARTS   AGE
nextcloud-1562797800-sl5vf   0/1     Completed   0          5m2s
nextcloud-7c49bb8b5c-tnmqf   1/1     Running     0          18m
nextcloud-mariadb-master-0   1/1     Running     0          18m
nextcloud-mariadb-slave-0    1/1     Running     0          18m
nextcloud-redis-master-0     1/1     Running     0          18m
nextcloud-redis-slave-0      1/1     Running     0          18m
nextcloud-redis-slave-1      1/1     Running     0          17m
```

Since I am not familiar with setting up a nextcloud manually or the internal, I was not able to find further information to debug this issue. @chrisingenhaag @billimek if you need any further information, I am happy to share them with you.
