### ISSUE TITLE
[stable/elastic-stack] Elasticsearch Master and Data Crash Upon Deployment

### ISSUE THREAD

**Issue by james-crowley** [helm/charts#15496]
**Describe the bug**
Upon deployment of the elastic-stack chart, the Master and Data pod's fail to initialize. They get stuck in a CrashLoopBackOff state. Thus causing the client pod not be able to connect to the Master. 

Another user seemed to have a similar issue, #11464 but the issue got closed by accident. 

**Version of Helm and Kubernetes**:
HELM:
 - Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
 - Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

KUBE:
 - Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
 - Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp-ee", GitCommit:"d03f6421b5463042d87aa0211f116ba4848a0d0f", GitTreeState:"clean", BuildDate:"2019-01-17T13:14:09Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Stable/Elastic-Stack but the issue looks like it deals with the elasticsearch sub chart.

**What happened**:
I was trying to spin up the ELK stack on my Kube cluster. Logstash and Kibana looks like it comes up fine minus them looking for connections to Elasticsearch. 

**What you expected to happen**:
I expect the Elastic pods to spin up and work.

**How to reproduce it** (as minimally and precisely as possible):
Pull down the Elastic-Stack Stable charts then run, `helm install ./ --tls`.

**Anything else we need to know**:
I am working on s390x. So the the ELK containers had to be made by myself. Here are the values I need to override in my `values.yaml` file.

```
# Default values for elk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  enabled: true
  image:
    repository: test.icp:8500/elkf/elasticsearch
    tag: 7.1.1
  nodeSelector:
    beta.kubernetes.io/arch: s390x
  master:
    persistence:
      storageClass: nfs-retain
  data:
    persistence:
      storageClass: nfs-retain
  cluster:
      config:
        bootstrap.system_call_filter: false
        xpack.ml.enabled: false
  initImage:
    repository: "s390x/busybox"
    tag: "latest"

kibana:
  enabled: true
  image:
    repository: test.icp:8500/elkf/kibana
    tag: 7.1.1
  nodeSelector:
    beta.kubernetes.io/arch: s390x
  persistentVolumeClaim:
    storageClass: nfs-retain
  env:
    ELASTICSEARCH_HOSTS: http://{{ .Release.Name }}-elasticsearch-client:9200

logstash:
  enabled: true
  image:
    repository: test.icp:8500/elkf/logstash
    tag: 7.1.1
  nodeSelector:
    beta.kubernetes.io/arch: s390x
  persistence:
    storageClass: nfs-retain
  # elasticsearch:
  #   host: elastic-stack-elasticsearch-client
```

I tried to stick to the defaults as much as I could. Swapped out the images, added our NFS provisioner storage class, disabled xpack and system call filter for s390x.
