### ISSUE TITLE
[stable/concourse] Error: the namespace from the provided object does not match the namespace

### ISSUE THREAD

**Issue by fpiedrah** [helm/charts#15516]
**Describe the bug**
While running "**helm install stable/concourse --version 8.1.0 --generate-name**" I get "**Error: the namespace from the provided object "concourse-1563143525-main" does not match the namespace "default". You must pass '--namespace=concourse-1563143525-main' to perform this operation.**"  I've tried running "helm install concourse stable/concourse --version 8.1.0 --namespace=concourse-main" and get "helm install concourse stable/concourse --version 8.1.0 --namespace=concourse-main" I might be doing something wrong here.

**Version of Helm and Kubernetes**: 
Client Version:version.Info{
   Major:"1",
   Minor:"12",
   GitVersion:"v1.12.5",
   GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec",
   GitTreeState:"archive",
   BuildDate:"2019-03-05T13:36:50Z",
   GoVersion:"go1.12",
   Compiler:"gc",
   Platform:"linux/amd64"
}

Server Version:version.Info{
   Major:"1",
   Minor:"14",
   GitVersion:"v1.14.3",
   GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0",
   GitTreeState:"clean",
   BuildDate:"2019-06-06T01:36:19Z",
   GoVersion:"go1.12.5",
   Compiler:"gc",
   Platform:"linux/amd64"
}

**Which chart**: stable/concourse

**What happened**: While running "**helm install stable/concourse --version 8.1.0 --generate-name**" I get "**Error: the namespace from the provided object "concourse-1563143525-main" does not match the namespace "default"

**What you expected to happen**: I would expect that running "**helm install stable/concourse --version 8.1.0 --generate-name**" would install my chart into the kubernetes cluster

**How to reproduce it** (as minimally and precisely as possible):  "**helm install stable/concourse --version 8.1.0 --generate-name**"

**Comment by jasper-nl** [comment]
Got the same issue. I did not do the helm install but client only to get the generated yaml. The yaml contains for the rolebinding the namespace for the ...-main. This causes the error as that namespace does not match the namespace the yaml is applied with. 
Based on the generated yaml the following yaml can be applied to get the authorization on the secrets working (https://github.com/helm/charts/tree/master/stable/concourse#kubernetes-secrets). 
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: release-name-web
  namespace: <namespace>-main
  labels:
    app: release-name-web
    chart: concourse-8.1.0
    heritage: Tiller
    release: release-name
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: release-name-web-main
  namespace: <namespace>-main
  labels:
    app: release-name-web
    chart: concourse-8.1.0
    heritage: Tiller
    release: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-web
subjects:
- kind: ServiceAccount
  name: release-name-web
  namespace: <namespace>
```
