### ISSUE TITLE
[stable/datadog] incorrect datadog-agent kubernetes permissions since 1.31.5

### ISSUE THREAD

**Issue by PHameete** [helm/charts#15530]
**Describe the bug**
Since commit 81405b0a337ee7e96515654343fe17d46765d45e (version 1.31.5) the datadog agent no longer has the correct permissions for the kubernetes API.

**Version of Helm and Kubernetes**:
Helm 2.14 and Kubernetes 1.12

**Which chart**:
stable/datadog

**What happened**:
After recreating our Datadog agent daemonset with the latest helm chart, all log and metric collection stopped working. Executing `agent status` on the pod shows the kubelet collector is in ERROR state.

`agent diagnose` shows the following error for the kubelet collector:

```
[ERROR] error: temporary failure in apiserver, will retry later: check resources failed: event collection: 
"events is forbidden: User \"system:serviceaccount:default:datadog-agent\" cannot list resource \"events\" in API group \"\" at the cluster scope", service collection: "services is forbidden: User \"system:serviceaccount:default:datadog-agent\" cannot list resource \"services\" in API group \"\" at the cluster scope", pod collection: "pods is forbidden: User \"system:serviceaccount:default:datadog-agent\" cannot list resource \"pods\" in API group \"\" at the cluster scope", node collection: "nodes is forbidden: User \"system:serviceaccount:default:datadog-agent\" cannot list resource \"nodes\" in API group \"\" at the cluster scope" - 1563180833290195095
```

**What you expected to happen**:
The datadog agent to work as before the upgrade.

**How to reproduce it** (as minimally and precisely as possible):
- Remove your datadog agent daemonset: `helm delete datadog-agent --purge`. 
- Create a new datadog agent daemonset: `helm install --name datadog-agent -f kubernetes/datadog/datadog-values.yaml --set datadog.apiKey=<APIKEY> stable/datadog`
- Log into the created datadog-agent pod: `kubectl exec -it datadog-agent-xxxxx -- /bin/bash` and run `agent status` and/or `agent diagnose` 
- You will find the kubelet collector in ERROR state and docker collector in PENDING.
- Try with `--version 1.31.4` and you will find it still working.

**Anything else we need to know**:
contents of my datadog-values.yaml file:

```yaml
image:
  repository: datadog/agent
  tag: 6.12.1
  pullPolicy: Always
datadog:
  collectEvents: true
  logsEnabled: true
  logsConfigContainerCollectAll: true
  nonLocalTraffic: true
  apmEnabled: true
  env:
    - name: DD_LOG_LEVEL
      value: "INFO"
    - name: DD_LOGS_INJECTION
      value: "true"
    - name: DD_USE_DOGSTATSD
      value: "true"
    - name: DD_LOG_FORMAT_JSON
      value: "true"
daemonset:
  useHostPort: true
```
