### ISSUE TITLE
[stable/prometheus-operator] alertmanagerSpec needs logFormat set

### ISSUE THREAD

**Issue by jnaulty** [helm/charts#15572]
<!-- Thanks for filing an issue! Before hitting the button, please answer these questions. It's helpful to search the existing GitHub issues first. It's likely that another user has already reported the issue you're facing, or it's a known issue that we're already aware of 

Fill in as much of the template below as you can.  If you leave out information, we can't help you as well.

Be ready for followup questions, and please respond in a timely manner. If we can't reproduce a bug or think a feature already exists, we might close your issue.  If we're wrong, PLEASE feel free to reopen it and explain why.
-->

**Describe the bug**
There is an issue deploying prometheus-operator alertmanager pod. It goes into `CrashLoopBackOff`.

**Version of Helm Chart and prometheus-operator App Version**
Chart: prometheus-operator-5.15.0      
App: 0.31.1

**Version of Helm and Kubernetes**:
Helm: v2.12.0
Kubernetes: v1.12

**Which chart**:
stable/prometheus-operator

**What happened**:
Stateful set after deploy:
```
    spec:                                                                                                                                                                                                          
      containers:                                                                                                                                                                                                  
      - args:                                                                                                                                                                                                      
        - --config.file=/etc/alertmanager/config/alertmanager.yaml                                                                                                                                                 
        - --cluster.listen-address=[$(POD_IP)]:6783                                                                                                                                                                
        - --storage.path=/alertmanager                                                                                                                                                                             
        - --data.retention=120h                                                                                                                                                                                    
        - --web.listen-address=:9093                                                                                                                                                                               
        - --web.external-url=http://prometheus-operator-alertmanager.prometheus-operator:9093                                                                                                                      
        - --web.route-prefix=/                                                                                                                                                                                     
        - --log.format=<nil>                                                                                                                                                                                       
        - --cluster.peer=alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.prometheus-operator.svc:6783  
```

**What you expected to happen**:
`log.format` should equal `logfmt`

**How to reproduce it** :
Deploy prometheus-operator at this specific version with default values.

**Anything else we need to know**:
I think the logFormat value could be uncommented, The logFormat option is set to <null>
[values.yaml](https://github.com/helm/charts/blob/afdcbd010c407108bffe8cc5cfc3f7a5299c5a86/stable/prometheus-operator/values.yaml#L248) when deploying with default values.


or provide a default value 'behind-the-scenes' (e.g. [here](https://github.com/helm/charts/blob/afdcbd010c407108bffe8cc5cfc3f7a5299c5a86/stable/prometheus-operator/templates/alertmanager/alertmanager.yaml#L29)
