### ISSUE TITLE
[stable/oauth2-proxy] provide `ca-certificates.crt` file to oauth2_proxy deployment

### ISSUE THREAD

**Issue by figaw** [helm/charts#15621]
We're using a self-signed certificate and need to provide at certificate-bundle for the oauth2_proxy.

**Describe the solution you'd like**

I would like, just like the `existingConfig` to be able to specify a `existingCertificateSecret` that would contain an entry called `ca-certificates.crt` which would be mounted to `/etc/ssl/certs/ca-certificates.crt` in the container.

**Describe alternatives you've considered**
- Being able to paste a certificate-bundle directly into the `values.yaml` file, 
just like the `configFile: |- ... ` currently available, but that'd immediately lead to bloat, as a certificate-bundle is often "lots-of-lines"-long.
- Being able to specify arbitrary `extraVolumes` and `extraVolumeMounts` that are mounted accordingly to the container. But we don't really need to mount any other files, so it feels unnecessary.

**Additional context**
Our current solution is manually deploying the oauth2_proxy deployment with,

```yaml
    spec:
      volumes:
        - name: ca-bundle-cert
          secret: 
            secretName: <secret-name>
...
        containers:
            volumeMounts:
            - mountPath: /etc/ssl/certs/
              name: ca-bundle-cert 
```

and a secret, `<secret-name>` with an entry called `ca-certificates.crt`
