### ISSUE TITLE
[stable/prometheus] Prometheus is down (404 Not Found)

### ISSUE THREAD

**Issue by proskehy** [helm/charts#15677]
**Describe the bug**
The Prometheus endpoint's status is Down with the code 404. The same code is a result of any attempts to add Prometheus as datasource into Grafana.

![screenshot](https://user-images.githubusercontent.com/24292015/61453611-e1b0ef80-a95e-11e9-8c87-b6e212a835fa.png)

**Version of Helm and Kubernetes**:
Helm: v2.12.3
K8s: v1.14.1

**Which chart**:
stable/prometheus

**What happened**:
I brought up the chart with the following config
```
alertmanager:
  persistentVolume:
    enabled: false
server:
  baseURL: http://serverurl/prometheus   
  prefixURL: "/prometheus"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
      nginx.ingress.kubernetes.io/enable-access-log: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - "/prometheus"
  persistentVolume:
    enabled: false
extraScrapeConfigs: |
      ...omitted
```

**What you expected to happen**:
To be able to use Prometheus with Grafana and see the Prometheus endpoint as UP.

**How to reproduce it** (as minimally and precisely as possible):
I'm not sure exactly, but the issue arose when I upgraded from the chart version 8.7.1 to 8.14.0. Everthing was still working on 8.14.0, but the memory usage went up drastically, so I decided to go back to 8.7.1 and I've been hitting this issue ever since (even if I upgrade back up to 8.14).
