### ISSUE TITLE
[stable/concourse] provide `web.hardAntiAffinity` in `values`

### ISSUE THREAD

**Issue by cirocosta** [helm/charts#15681]
**Is your feature request related to a problem? Please describe.**

We currently allow the configuration of `worker.hardAntiAffinity` to ease the
burden on the user of providing an entire `affinity` rule.

Rather than

```yaml
# manually specifying the whole affinity rule
# (note how you need to know the release name before-hand)
#
worker:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: $RELEASE_NAME-worker
            release: "$RELEASE_NAME"
        topologyKey: kubernetes.io/hostname
```

One can simply

```yaml
worker:
  hardAntiAffinity: true
```

Which is quite convenient.

**Describe the solution you'd like**

Have a `web.hardAntiAffinity` field just like `worker` does.

**Describe alternatives you've considered**

Have a `web.hardAntiAffinity` field just like `worker` does.

**Additional context**

We've seen in [`hush-house`](https://github.com/concourse/hush-house) (our
largest deployment of Concourse leveraging this Helm chart) that it's very
important to have the `web` nodes getting placed in different VMs as with
improvements like [parallel input streaming](https://github.com/concourse/concourse/issues/3992#issuecomment-504036411)
and [the use of zstd for compression](https://github.com/concourse/baggageclaim/pull/22)
we tend now to reach the full available bandwidth of the machines where they
land on.

Thus, having the ability to tell folks to just use `web.hardAntiAffinity: true`
would be great 😁 

Thanks!
