### ISSUE TITLE
[stable/velero] Why is the credential secret for azure handled differently versus the cli install?

### ISSUE THREAD

**Issue by jonaspetersorensen** [helm/charts#15701]
**Describe the bug**
Pod fails because it cannot find expected environment variables for the azure credentials.

**Version of Helm and Kubernetes**:
Helm client v2.12.2, server v2.14.1
AKS, k8s v1.12.8

**Which chart**:
velero v2.1.1

**What happened**:
I installed the secret as described in the README, 
`kubectl create secret generic cloud-credentials --namespace velero --from-file cloud=credentials-velero`

and then deployed the helm chart using
```sh
# Just showing the important values
configuration.provider=azure
credentials.useSecret=true
credentials.existingSecret=credentials-velero
```

**What you expected to happen**:
I expected the deployment to look some what similar to what the cli tool produce.
If I compare the helm deployment and the cli tool deployment then they differ a lot in how they handle the credential secret.
The cli install will handle AKS just fine due to how it handle the secret.

**How to reproduce it** (as minimally and precisely as possible):
Just run the helm install in AKS as described in the README for chart v2.1.1
It will fail due to the credentials will not appear as expected in the pod.

**Anything else we need to know**:

Note how the payload from a secret in AKS is added as env vars in
https://github.com/helm/charts/blob/master/stable/velero/templates/deployment.yaml#L64

Then look at how the same secret is handled for anyone else in https://github.com/helm/charts/blob/master/stable/velero/templates/deployment.yaml#L82

These are not compatible for how the secret payload is made available in the pod environment, at least not when creating a secret as shown in the README.

The fix for AKS when using chart v2.1.1 is to create a secret that is compatible with how the secret is used by the chart:
```
# As found in https://github.com/helm/charts/blob/master/stable/velero/templates/deployment.yaml#L64
envFrom:
   - secretRef:
         name: {{ include "velero.secretName" . }}
```

Step 1: create a env file for the credentials
```
cat << EOF  > ./credentials-velero
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_TENANT_ID=${AZURE_TENANT_ID}
AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
EOF
```

Step 2: create a k8s secret
`kubectl create secret generic cloud-credentials --namespace "$VELERO_NAMESPACE" \
   --from-env-file=" ./credentials-velero"`

Step 3: restart the velero pod so that it will read the secret

Done :)

...But I would really prefer that the secret is handled in the deployment just like how the cli tool does it, 
```
# Snippet from the cli deployment, note that AZURE_CREDENTIALS_FILE does not require any weirdness
      spec:
        containers:
        - args:
          - server
          command:
          - /velero
          env:
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          image: gcr.io/heptio-images/velero:v1.0.0
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
          - containerPort: 8085
            name: metrics
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /plugins
            name: plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: velero
        serviceAccountName: velero
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            defaultMode: 420
            secretName: cloud-credentials
```
