### ISSUE TITLE
[stable/grafana] unable to configure dashboards in values file

### ISSUE THREAD

**Issue by previ** [helm/charts#15725]
I cannot define dashboard to be imported in grafana at install time.

**Description**: 
Configuring dashboard to be auto imported (by dashboard id) at install time, they are ignored.

Helm: 2.13.1 
Kubernetes: 1.13.5

**Which chart**: stable/grafana 3.5.11

**What happened**: dashboards configured are actually ignored.

**What you expected to happen**: dashboard configured to be impoterd to be actually imported.

**How to reproduce it** (as minimally and precisely as possible):
use the following lines in the values.yanl:
```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-cluster:
      gnetId: 7249
      datasource: Prometheus
```
**Anything else we need to know**:
