### ISSUE TITLE
[stable/cluster-autoscaler] Useless/empty secret created

### ISSUE THREAD

**Issue by yurrriq** [helm/charts#15814]
**Describe the bug**
https://github.com/helm/charts/pull/11978 introduces an unnecessary secret when, e.g. `cloudProvider` is `aws` and not both `awsAccessKeyID` and `awsSecretAccessKey` are set.

**What you expected to happen**:
No such secret.

**How to reproduce it** (as minimally and precisely as possible):
```yaml
cloudProvider: aws
awsAccessKeyID:
awsAccessKey:
```
