### ISSUE TITLE
[stable/external-dns] Version 2 adds undocumented regression for extraEnv

### ISSUE THREAD

**Issue by razor-x** [helm/charts#15816]
**Describe the bug**

The chart value `extraEnv` in v1 supported arrays of non-strings, in v2 this feature was removed without notice. Please see this PR for a complete history of why this feature was added: https://github.com/helm/charts/pull/8587

Ideally the maintainers would expedite and restore the original code without a new PR, however if requested I can re-implement this feature for v2 and submit a new PR. Please clarify what action should be taken.

**Which chart**:

stable/external-dns v2

**What happened**:

When using

```yaml
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: dns-secret
          key: AWS_ACCESS_KEY_ID
```

Updating from v1 to v2 gives

```
Error: render error in "system/charts/dns/templates/secret.yaml": template: system/charts/dns/templates/secret.yaml:37:26: executing "system/charts/dns/templates/secret.yaml" at <b64enc>: wrong type for value; expected string; got map[str
ing]interface {}       
```

**What you expected to happen**:

Not to get this error or have the README state clearly that in v2 this feature was intentionally removed.
