### ISSUE TITLE
[stable/mongodb] unable to access the service outside of cluster

### ISSUE THREAD

**Issue by runestonex** [helm/charts#15810]
**Describe the bug**
I was able to sucessfully deploy this service in my google cloud instance and can access it via cluster ip and endpoints. But while trying to access the service outside cluster when i need to set service ip using 
`export SERVICE_IP=$(kubectl get svc --namespace default mymongo-mongodb --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
`
i get 
>error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil

**Version of Helm and Kubernetes**:

helm version - v2.14.2
kubernates version - v1.15.0

**Which chart**:
I,am using stable/mongodb chart to deploy service.

**What happened**:

mongodb is only working via endpoint and cluster ip.
configuration i made for service are as follow
```
# Kubernetes service type
service:
  annotations: {}
  type: LoadBalancer
  # clusterIP: None
  port: 27017

  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort: 32007

  ## Specify the externalIP value ClusterIP service type.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#external-ips
  externalIPs: [102.226.201.198]

  ## Specify the loadBalancerIP value for LoadBalancer service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
  ##
  loadBalancerIP: 78.11.24.19/24

  ## Specify the loadBalancerSourceRanges value for LoadBalancer service types.
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  loadBalancerSourceRanges: [78.11.24.19/24,78.11.24.20/24]
```

**What you expected to happen**:

Able to access this service via robo3t installed in my local system.
