### ISSUE TITLE
[stable/airflow] Is Kubernetes executor available as a provision in the same charts 

### ISSUE THREAD

**Issue by nixonraphy** [helm/charts#15828]
**Is your feature request related to a problem? Please describe.**

The default executor in the helm charts is "Celery" . Is kubernetes executor also supported ? Or , Celery is the only executor available ,in which case the option can be removed from the charts  

**Describe the solution you'd like**

I saw a comment as to have a documentation regarding use of Kubeexecutor as well alongside Celery in these charts . Is it supported ? Are there any documentation regarding the same ?
https://github.com/helm/charts/pull/3959#issuecomment-403712897
**Describe alternatives you've considered**
I tried simply changing the executor to "Kubernetes" . However , that sent all airflow pods to a CrashLoopBackOff .

**Comment by nfillot** [comment]
@nixonraphy The kubernetes executor is not present within the image (see puckel/docker-airflow#285) so you should use a custom image with apache-airflow[kubernetes] subpackage 

You also need to customize some environment variables for DAGs storage and RBAC like 
```
airflow     
   config:
      AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflow-dags"
      AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
      AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "airflow"
```
