### ISSUE TITLE
[stable/prometheus-operator] disabling grafana's servicemonitor

### ISSUE THREAD

**Issue by mariogeorgievft** [helm/charts#15822]
**Describe the bug**
If you for instance want to use prometheus-operator but want to disable grafana in an umbrella chart the following happens:

Umbrella chart name : mychart
```
requirements.yaml -> 
dependencies:
  - name: prometheus-operator
    version: 5.15.0
    repository: https://kubernetes-charts.storage.googleapis.com  
```

```
values.yaml -> 

prometheus-operator:
  ..... values to configure in the prometheus-operator

```

First of all, if you try to do

```
prometheus-operator:
      grafana:
         enabled: false 
```

this does not work, because the yaml gets prefixed with prometheus-operator, ok this has a simple way to get over with:

```
grafana:
   enabled: false -> this gets propagated to the requirements.yaml fine disabling the chart
prometheus-operator:
      values to configure in prometheus operator

```
However when we disable the chart -> the servicemonitor, dashboards still get deployed. Even saying 
```

grafana:
   enabled: false 
   serviceMonitor:
       selfMonitor: false -> this does not work, still deploys the service monitors
```

**Version of Helm and Kubernetes**:

Helm version: 
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Kubernetes version:

kubernetes_build_info{buildDate="2019-02-28T20:26:10Z",compiler="gc",endpoint="https",gitCommit="d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7",gitTreeState="clean",gitVersion="v1.12.6-eks-d69f1b",goVersion="go1.10.8",instance="10.178.185.253:443",job="apiserver",major="1",minor="12+",namespace="default",platform="linux/amd64",service="kubernetes"}

**Which chart**:
prometheus-operator

**What happened**:

Umbrella chart having prometheus-operator as dependency does not propagate values.yaml correctly in my case for Grafana.

**What you expected to happen**:
Not deploy servicemonitors and dashboards.

**How to reproduce it** (as minimally and precisely as possible):
Create an umbrella chart with requirements.yaml having prometheus-operator as dependency, and try turning off grafana's servicemonitor and dashboards

**Anything else we need to know**:
