### ISSUE TITLE
[stable/sonarqube] sonarqube.properties are not applied

### ISSUE THREAD

**Issue by ricardompcarvalho** [helm/charts#15824]
**Describe the bug**
I fullfill my sonarqube.properties with these values and when i open my configurations in sonar the values don't appear.
![image](https://user-images.githubusercontent.com/27811451/61782307-be25f300-adfd-11e9-9056-f4e0fa358d60.png)

**Version of Helm and Kubernetes**:
```
Helm
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

```
```
Kubernetes
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
SONARQUBE

**What happened**:
Sonarqube.properties are not applied 

**How to reproduce it** (as minimally and precisely as possible):
```
image:
  repository: sonarqube
  tag: 7.7-community

securityContext:
  fsGroup: 999

service:
  name: sonarqube
  type: LoadBalancer

persistence:
  enabled: true
  annotations: {}
  accessMode: ReadWriteOnce
  size: 8Gi

plugins:
  install:
    - "https://binaries.sonarsource.com/Distribution/sonar-auth-saml-plugin/sonar-auth-saml-plugin-1.1.0.181.jar"  
    - "https://github.com/SonarSource/sonar-ldap/releases/download/2.2-RC3/sonar-ldap-plugin-2.2.0.601.jar"

sonarProperties:
  sonar.auth.saml.enabled: true
  sonar.auth.saml.applicationId: "Example 1"
  sonar.auth.saml.providerName: "Example 2"
```

**Anything else we need to know**:
Anything else you need to know please tell me
