### ISSUE TITLE
[stable/redis] Add ConfigMap for redis

### ISSUE THREAD

**Issue by xasor** [helm/charts#1583]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I need config map object for setting some parameters on redis.conf. Example:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redisconfig
data:
  redis-config: |
    notify-keyspace-events Egx
```

**Version of Helm and Kubernetes**: 2.5.0/1.6.6

**Which chart**: [stable/redis]
