### ISSUE TITLE
stable/velero - Azure deployment unable to get environment variables

### ISSUE THREAD

**Issue by johnburns320** [helm/charts#15915]
**Describe the bug**

Deployment on Azure uses an invalid environment variable configuration which fails to make the cloud-credentials secret available to the pod.

**Version of Helm and Kubernetes**:

Helm:
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/velero --version 2.1.1

**What happened**:
```
level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID
```

**What you expected to happen**:

Environment variables are loaded and velero continues normal functioning.

**How to reproduce it** (as minimally and precisely as possible):

1. Create text file with cloud-credentials variables (use any values):
```
AZURE_SUBSCRIPTION_ID=***
AZURE_TENANT_ID=***
AZURE_CLIENT_ID=***
AZURE_CLIENT_SECRET=***
AZURE_RESOURCE_GROUP=***
```
2. Run:
```
kubectl create secret generic cloud-credentials -n <namespace> --from-file=cloud=<text file name>
```
3. Edit values.yaml file according to your environment configuration.

4. Run:
```
helm install stable/velero --version 2.1.1 --namespace <namespace> -f <values.yaml path>
```

**Anything else we need to know**:

I've compared the deployment manifest created by installing velero directly from the command line.  It actually configures environment variables for the three major cloud providers linked to the same cloud-credentials secret volumeMount.

Example with relevant env, volumeMounts, and volumes specifications:
```
    spec:
      containers:
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        volumeMounts:
        - mountPath: /credentials
          name: cloud-credentials
      volumes:
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: cloud-credentials
```

I have a fork with a commit ready for a PR to correct this issue. It will create a provider-appropriate environment variable pointing to the /credentials/cloud path.
