### ISSUE TITLE
[stable/concourse] can't login using local user

### ISSUE THREAD

**Issue by dewnull** [helm/charts#16019]
**Describe the bug**
can't login using local user. clicking on login redirects to `http://127.0.0.1:8080/sky/issuer/auth?access_type=offline&client_id=skymarshal&redirect_uri ...`

**Version of Helm and Kubernetes**:
Helm Client: "v2.9.1",
Helm Server: "v2.14.2"
Kubernetes  v1.12.8
**Which chart**:
Concourse 8.2.1 

**What happened**:
Charts installs successfully but login cause redirect and fails. 

**What you expected to happen**:

**How to reproduce it** :
Here is a configuration I use to install concourse.

```yaml
concourse:
  web:
    externalUrl: ci-demo.domain.com
web:
  ingress:
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
      - ci-demo.domain.com
    tls:
      - secretName: concourse-web-tls
        hosts:
          - ci-demo.domain.com
```
**Anything else we need to know**:
