### ISSUE TITLE
[stable/wordpress] Connection with 'bn_wordpress' user is unsuccessful

### ISSUE THREAD

**Issue by RichardWeug** [helm/charts#16104]
**Describe the bug**
I was trying to get my wordpress production ready by changing to production values. My pod got in a crash loop because the user doesn't have access to mariadb.

**Version of Helm and Kubernetes**:
Helm version: 
Kubernetes version: 1.11.10-gke.5
Helm version: v2.14.1

**Which chart**:
[stable/wordpress]

**What happened**:
The mariadb pod starts successfully, but the wordpress pod can't connect to it, since the access to the database is denied. This causes a crash loop.

**What you expected to happen**:
I expect the pod to connect.

**How to reproduce it** (as minimally and precisely as possible):
Update an existing pod with production values.

I updated my values to the following:
```
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 5.2.2
  pullPolicy: IfNotPresent

wordpressUsername: username
wordpressPassword: password
wordpressEmail: mail@website.com
wordpressFirstName: FirstName
wordpressLastName: LastName
wordpressBlogName: Website
wordpressTablePrefix: wp_
wordpressSkipInstall: false
allowEmptyPassword: true
allowOverrideNone: true
customHTAccessCM:
replicaCount: 1

externalDatabase:
  host: localhost
  user: bn_wordpress
  password: ""
  database: bitnami_wordpress
  port: 3306

mariadb:
  enabled: true
  
  replication:
    enabled: false

  db:
    name: bitnami_wordpress
    user: bn_wordpress

  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi

service:
  type: NodePort
  port: 80
  httpsPort: 443
  
  nodePorts:
    http: ""
    https: ""
    
  externalTrafficPolicy: Local
  annotations: {}

healthcheckHttps: false

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

ingress:
  enabled: true
  certManager: true

  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'www.website.com' ) {
        rewrite ^ https://website.com$request_uri permanent;
      }

  hosts:
  - name: website.com
    path: /
  - name: www.website.com
    path: /

  tls:
  - hosts:
      - website.com
    secretName: website-tls

  secrets:

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  requests:
    memory: 512Mi
    cpu: 0.1

nodeSelector: {}
tolerations: []
affinity: {}

metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"

sidecars:
```
