### ISSUE TITLE
[stable/jenkins] How do I use agent.envVars to update JENKINS_URL

### ISSUE THREAD

**Issue by bassplay3r** [helm/charts#16118]
**Describe the bug**
Unable to to use agent.envVars

**Version of Helm and Kubernetes**:
Helm v2.13.1
K8s 1.14.1

**Which chart**:
stable/jenkins

**What happened**:
The JENKINS_URL var was not configured 

**What you expected to happen**:
Configure JENKINS_URL in the slave pod 

**How to reproduce it** (as minimally and precisely as possible):
```
agent:
   envVars:                                                                                                                                                                                                       
   - enVar:                                                                                                                                                                                                         
     - key: JENKINS_URL                                                                                                                                                                                               
       value: http://1.2.3.4:8080     
```    

**Anything else we need to know**:

**Comment by torstenwalter** [comment]
I think this variable is automatically injected by the [kubernetes plugin](https://github.com/jenkinsci/kubernetes-plugin). All you need to do is to configure the URL for that pkugin. Manage Jenkins - Configure System - Clouds - Kubernetes - Jenkins URL (No guarantee for the path I can't look at a running Jenkins at the moment).

**Comment by bassplay3r** [comment]
Yea I get that but I want to reference a var, with the external load balancer address, in messages so users can click on it but right now it uses a name that points to an internal address or that is not in DNS so the link in messages would be invalid.  When you view the var in the cloud config there is a deprecation warning to set vars in another area of the config but I'm not sure where.  Can you give me an example how set my own var using agent.envVars? I not able to find one in the docs

**Comment by torstenwalter** [comment]
Understood. So you like to inject Jenkins external URL as environment variable. That should be possible. I would try to use a different variable name for that as JENKINS_URL has a different meaning for the kubernetes plugin. https://github.com/jenkinsci/kubernetes-plugin#kubernetes-plugin-for-jenkins

**Comment by bassplay3r** [comment]
I have no problem using a different var name, I just not sure how to do it with agent envVars

The charts values.yaml has 
```
# You can define the volumes that you want to mount for this container
  # Allowed types are: ConfigMap, EmptyDir, HostPath, Nfs, Pod, Secret
  # Configure the attributes as they appear in the corresponding Java class for that type
  # https://github.com/jenkinsci/kubernetes-plugin/tree/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes
  # Pod-wide ennvironment, these vars are visible to any container in the slave pod
  envVars:
  # - name: PATH
  #   value: /usr/local/bin

```

But when I tried to do that it failed. Is this the correct way?

```
agent:
   envVars:                                                                                                                                                                                                       
   - enVar:                                                                                                                                                                                                         
     - key: JENKINS_EXTERNAL_URL                                                                                                                                                                                               
       value: http://1.2.3.4:8080

```
