### ISSUE TITLE
[stable/graylog] multiple tcp input with NodePort

### ISSUE THREAD

**Issue by hablijack** [helm/charts#16135]
**Describe the bug**
We can not define multiple tcp inputs with NodePort. Only one NodePort is possible because the template takes the NodePort-value outside of the Loop: https://github.com/helm/charts/blob/master/stable/graylog/templates/tcp-service.yaml#L27

What the template suggests: 
```  
input:
    tcp:
      service:
        type: NodePort
        nodePort: 31488
      ports:
        - name: gelf
          port: 31488
        - name: json
           port: 31489
```

What we want to define:
```  
input:
    tcp:
      service:
        type: NodePort
      ports:
        - name: gelf
          port: 31488
          nodePort: 31488
        - name: json
          port: 31489
          nodePort: 31489
```

**Version of Helm and Kubernetes**:
Helm: 2.13.1
Kubernetes: 1.14.3

**Which chart**:
stable/graylog

**What happened**:
We can not define multiple NodePort Inputs for Graylog (GELF and JSON) for different sources of Logfiles.

**What you expected to happen**:
We want to define it via HELM-values.yaml

**How to reproduce it** (as minimally and precisely as possible):
Put the snippet above into the values.yaml and deploy a graylog instance in K8s. You can not define multiple NodePort TCP inputs.

**Anything else we need to know**:
The Fix is very simple for my purpose: 
In https://github.com/helm/charts/blob/master/stable/graylog/templates/tcp-service.yaml#L27
```
spec:
  ports:
  {{- range .Values.graylog.input.tcp.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .port }}
      nodePort:  {{ .nodePort }}
  {{- end }}
```

But i don't know weather it works for different kind of input definitions like LoadBalancer, etc ...
