### ISSUE TITLE
[stable/jenkins] Agent not mounting secret as volume

### ISSUE THREAD

**Issue by thcp** [helm/charts#16143]
**Describe the bug**
I'm trying to mount my ssh keys on agent pod but nothing happens.

**Version of Helm and Kubernetes**:
Helm: v2.14.1
Kubernetes: v1.13.5

**Which chart**:
Jenkins

**What happened**:
no mounted volume with secrets are being made available

**What you expected to happen**:
public and private key being available under /home/jenkins/.ssh

**How to reproduce it** (as minimally and precisely as possible):

create your secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  namespace: jenkins
type: Opaque
data:
  id_rsa: your key | base64
  id_rsa.pub: your key | base64
```

agent values.yaml:
```
agent:
  enabled: true
  volumes:
    - type: Secret
      secretName: ssh-key
      mountPath: /home/jenkins/.ssh
```
**Anything else we need to know**:

WHen tested with this simple yaml file, it works:

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: jenkins
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: ssh-key-volume
      mountPath: "/tmp/test"
  restartPolicy: Always
  volumes:
  - name: ssh-key-volume
    secret:
      secretName: ssh-key
      defaultMode: 256   
```

![image](https://user-images.githubusercontent.com/31625914/62633455-0da30d80-b92c-11e9-8415-457aece7cb3e.png)
