### ISSUE TITLE
[stable/grafana] Multiple paths for host in Ingress

### ISSUE THREAD

**Issue by jasonmacdonald** [helm/charts#16173]
I'm trying to figure out how to accomplish SSL redirection as outlined [here](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/) using this Grafana chart. It seems that you cannot set multiple paths per host in the Ingress template. Would it be possible to add this feature instead of hard coding the paths to just a single path?

**Describe the solution you'd like**
I think an ideal scenario would be to allow adding additional paths to the main route using something like the following in the values.yml
```
hosts:
    - host: chart-example.local
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
```

I suppose another option would be to simply flag the Ingress as SSL redirect and add the necessary values behind the scenes.
