### ISSUE TITLE
[stable/prometheus] server, alertmanager and pushgateway return 404 not found when using ingress path

### ISSUE THREAD

**Issue by aroes** [helm/charts#16216]
**Describe the bug**
When configuring the ingress values, adding a path to the "ingress.hosts" values results in 404s

**Version of Helm and Kubernetes**:
Helm version:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/prometheus

**What happened**:
Using the values file below:

```
alertmanager:
  ingress:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      kubernetes.io/ingress.class: system
    hosts:
      - alerts.example.com/alertmanager
pushgateway:
  ingress:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      kubernetes.io/ingress.class: system
    hosts:
      - pushgateway.example.com
server:
  ingress:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      kubernetes.io/ingress.class: system
    hosts:
      - prometheus.example.com/server/
```

**What you expected to happen**:
Both cases should work (subdomain and path)
Currently 
a valid path returns 404 not found, 
invalid path returns 404 not found - default backend

**How to reproduce it** (as minimally and precisely as possible):
Install nginx controller for ingress.
helm install --name prometheus stable/prometheus -f prometheus-values.yaml

**Summary:** _Using the values file above, pushgateway.example.com will work, alerts.example.com/alertmanager and prometheus.example.com/server will return 404 not found._
