### ISSUE TITLE
[stable/wordpress] Ingress annotations should be an object not an array

### ISSUE THREAD

**Issue by markhilton** [helm/charts#16228]
**Which chart**: stable/wordpress

**Describe the bug**
Adding annotations to ingress as an array renders incorrect yaml. For example: 

```yaml
ingress: 
  annotations:
    kubernetes.io/ingress.class: "nginx"
```
produces helm warning:
`Merging destination map for chart 'wordpress'. The destination item 'annotations' is a table and ignoring the source 'annotations' as it has a non-table value of: <nil>`

If an array is used: 

```yaml
ingress: 
  annotations:
    - "kubernetes.io/ingress.class: nginx"
```

helm does not produce the warning, but rendered ingress yaml is incorrect and looks like this:

```yaml
metadata:
  annotations:
    "0": 'kubernetes.io/ingress.class: nginx'
```

**What you expected to happen**:
I believe ingress annotations should be an object, not an array.

**Comment by alemorcuq** [comment]
Hi, @markhilton.

I'm not able to reproduce this issue. Using the following settings in `values.yaml`:

```yaml
## Configure the ingress resource that allows you to access the
## WordPress installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations:
    kubernetes.io/ingress.class: nginx

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: wordpress.local
    path: /

  ## The tls configuration for the ingress
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ## tls:
  ## - hosts:
  ##     - wordpress.local
  ##   secretName: wordpress.local-tls

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: wordpress.local-tls
  #   key:
  #   certificate:
``` 

renders correctly:

```yaml
---
# Source: wordpress/templates/ingress.yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-wordpress
  labels:
    app: "release-name-wordpress"
    chart: "wordpress-7.1.0"
    release: "release-name"
    heritage: "Tiller"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: wordpress.local
    http:
      paths:
      - path: /
        backend:
          serviceName: "release-name-wordpress"
          servicePort: http
```

Could you give me some steps to get the same warning? Also, as far as I can see, we are not using annotations as an array anywhere. Could you please show where are annotations being treated as an array?

Regards,
Alejandro
