### ISSUE TITLE
[stable/spinnaker] combination of `env` and `customCerts` messes configuration

### ISSUE THREAD

**Issue by papanito** [helm/charts#16350]
**Describe the bug**

When using both `env` and `customCerts`  together the configuration is messed up

```
....
        volumeMounts:
        - name: kube-config
          mountPath: /opt/kube
        - name: additional-config-maps
          mountPath: /opt/halyard/additionalConfigMaps
        - name: halyard-home
          mountPath: /home/spinnaker
        - name: halyard-config
          mountPath: /opt/halyard/config
        - name: reg-secrets
          mountPath: /opt/registry/passwords
        env:
        - name: JAVA_OPTS
          value: -Dhttps.proxyHost=webproxy.sc.intra -Dhttps.proxyPort=9090 -Dhttp.proxyHost=webproxy.sc.intra
            -Dhttp.proxyPort=9090 -DnonProxyHosts="*.nop.sc.intra|*.sc.intra|localhost|127.0.0.1"
        
        - mountPath: /etc/ssl/certs/java/cacerts
          subPath: cacerts
          name: cacerts
...
```

**Version of Helm and Kubernetes**:

helm: 2.13.0

**Which chart**:

stable/spinnaker 1.14.0

**What happened**:

Configure the `values.yaml` file to use `env` and `customCerts`:

```
...
  env:
    - name: JAVA_OPTS
       value: -Dhttps.proxyHost=webproxy.sc.intra -Dhttps.proxyPort=9090 -Dhttp.proxyHost=webproxy.sc.intra -Dhttp.proxyPort=9090 -DnonProxyHosts="*.nop.sc.intra|*.sc.intra|localhost|127.0.0.1"

  customCerts:
    enabled: true
    secretName: sc-cacerts
...
```

Run `helm template`

```
helm template  --name=spinnaker --namespace=spinnaker -f values.yaml spinnaker-1.14.0.tgz
```

Check outcome

**What you expected to happen**:

Output yaml is properly structured

**How to reproduce it** (as minimally and precisely as possible):

see *What happened*

**Anything else we need to know**:

nope
