### ISSUE TITLE
[stable/airflow] change `max_connections = 100` in postgresql.conf

### ISSUE THREAD

**Issue by sirkubax** [helm/charts#16368]
Hi

I'd like to increase the `max_connections = 100` in postgresql pod.
Looking at some examples
https://github.com/helm/charts/issues/9699
following values should solve it:
```
airflow:
  postgresql:             
    postgresqlConfiguration:
      "sharedBuffers": "'1GB'"
      "maxConnections": 1000
      "listenAddresses": "'*'"
```
Yet the airflow chart not seem to have postgresql with `postgresqlConfiguration` is available.
As a plan B I've seen a suggestion to mount `postgresql.conf` file directly to `pgdata/postgresql.conf` folder - yet again - there is no respectful configuration in chart definition.

How one could change `max_connections` without replacing postgresql or changing airflow chart?

**Comment by alemorcuq** [comment]
Hi, @sirkubax.

If you take a look at the `values.yaml` file, you will see that PostgreSQL settings are declared in their own section, outside of the `airflow` settings:

**Comment by sirkubax** [comment]
Hi @alemorcuq 
I'm quite sure I've tried have it under other key as well...

In fact I've tried both ways:
```
airflow:                                                                        
  airflow:                                                                      
    image:                                                                      
      tag: 1.10.4                                                               
    extraConfigmapMounts:                                                       
      - name: extra-requirements                                                
        mountPath: /requirements.txt                                            
        configMap: airflow-requirements                                         
        readOnly: true                                                          
        subPath: requirements.txt                                               
                                                                                
  workers:                                                                      
    replicas: 2                                                                 
                                                                                
  persistence:                                                                  
    enabled: true                                                               
    accessMode: ReadWriteMany                                                   
    existingClaim: azurefile-airflow                                            
                                                                                
  redis:                                                                        
    usePassword: false                                                          
    password:                                                                   
                                                                                
  postgresql:                                                                   
    postgresqlConfiguration:                                                    
      "sharedBuffers": "'1GB'"                                                  
      "maxConnections": 1000                                                    
      "listenAddresses": "'*'"                                                  
                                                                                
postgresql:                                                                     
  postgresqlConfiguration:                                                      
    "sharedBuffers": "'1GB'"                                                    
    "maxConnections": 1000                                                      
    "listenAddresses": "'*'"                                                    
```

I wonder if I use proper chart...

```
helm install stable/airflow --set airflow.image.tag=1.10.4 --
```
or
```
dependencies:                
- name: airflow              
  version: "4.0.2"           
  repository: "@stable"      
  condtition: airflow.enabled
```
+ values
```
airflow:                                                                        
  airflow:                                                                      
    image:                                                                      
      tag: 1.10.4   ```

in my chart I see the postgresql 
```
dependencies:                                                  
- name: postgresql                                             
  version: 0.13.1                                              
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled                                
```
and in chart does not seem to use `postgresqlConfiguration` in any of it's templates...
`mychart/charts/airflow/charts/postgresql/templates/deployment.yaml`

To me it looks like airflow is using old postgresql chart...
Or am I wrong...
