### ISSUE TITLE
Prometheus chart healthcheck does not honor web.external-url

### ISSUE THREAD

**Issue by bradbeam** [helm/charts#1640]
Bug Report:

When defining a custom ingress rule based on paths[1], you'll need to specify `web.external-url`[2] as additional args. When this parameter is set, the readiness probe fails because `:9090/status` responds with a 404[3]. In this case, the readiness probe should honor the path defined by`web.external-url` or `web.route-prefix` so that Prometheus stays running. 

Kubernetes 1.7.2
Helm 2.5.1
Helm command run to reproduce:
```
helm install stable/prometheus  --set alertmanager.image.tag=v0.8.0 --set kubeStateMetrics.image.tag=v1.0.0-rc.1  --set nodeExporter.image.tag=v0.14.0 --set server.image.tag=v1.7.1 -f vars.yaml 
```

[1]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: default
  annotations:
spec:
  rules:
  - host: mydomain.com
    http:
      paths:
      - path: /prometheus
        backend:
          serviceName: sappy-chinchilla-prometheus-server
          servicePort: 80
```
[2]
vars.yaml
```
server:
  extraArgs:
    web.external-url: http://mydomain.com/prometheus
```
[3]
```
ubuntu@control-01:~$ curl 10.233.86.29:9090/status
404 page not found
ubuntu@control-01:~$ curl 10.233.86.29:9090
<a href="/prometheus">Found</a>.

ubuntu@control-01:~$ curl 10.233.86.29:9090/prometheus
<a href="/prometheus/">Moved Permanently</a>.

ubuntu@control-01:~$ curl 10.233.86.29:9090/prometheus/
<a href="/prometheus/graph">Found</a>.

ubuntu@control-01:~$ curl 10.233.86.29:9090/prometheus/status
<!DOCTYPE html>
<html lang="en">
...
```

**Comment by jwhitcraft** [comment]
I just ran into this problem as well and I don't believe that you can use a readiness probe with the chart when using the external-url param.  I came this conclusion because the pod never becomes ready, which means it's never actually allowed to be available in the service.

I'll do some more digging, but this does seem to be an issue.

**Comment by jwhitcraft** [comment]
@bradbeam i figured this out after digging around the prometheus source code.

You also need to add this cli option

```yaml
server:
  extraArgs:
    web.route-prefix: "/"
```
