### ISSUE TITLE
Access to SVC is not available，but ingress is ok

### ISSUE THREAD

**Issue by missops** [helm/charts#16448]
**Describe the bug**

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by hiningmeng** [comment]
my values.yaml  : 
```
image:
  repository: kong
  tag: 1.2
  pullPolicy: IfNotPresent
postgresql:
  enabled: false
env:
  database: postgres
  pg_user: postgres
  pg_database: kong
  pg_password: ------
  pg_host: postgre-postgresql-headless.databases.svc.cluster.local
  pg_port: 5432
admin:
  type: ClusterIP
  servicePort: 80
  containerPort: 8444
  useTLS: false
  ingress:
    enabled: true
    hosts: [kongadmin.hiningmeng.cn]
    annotations:
      kubernetes.io/ingress.class: traefik
    path: /
readinessProbe:
  httpGet:
    path: "/status"
    port: admin
    scheme: HTTP

livenessProbe:
  httpGet:
    path: "/status"
    port: admin
    scheme: HTTP
```
helm install -n kong --namespace=kong -f value.yaml  stable/kong


i can access to kongadmin.hiningmeng.cn,but kong-kong-admin.kong.svc.cluster.local is wrong, ping this svc host is ok .  why >
