### ISSUE TITLE
[stable/concourse] LetsEncrypt flags conflict with TLS flags

### ISSUE THREAD

**Issue by drlau** [helm/charts#16467]
**Describe the bug**
The existing LetsEncrypt flags directly conflict with the TLS flags. 

Start by setting `letsEncrypt: {enabled: true}`. The web pod will fail with the error:
 `	* must specify --tls-bind-port to use TLS`.

Add `tls: { enabled: true, bindPort: 443 }`, and this will fail at helm level:
`error calling required: secrets.webTlsCert is required because secrets.create is true and concourse.web.tls.enabled is true`.

Since I want helm to manage the secrets, setting `secrets.create: false` is not an option. So I set the following:
```
secrets:
  webTlsCert: "dummy cert"
  webTlsKey: "dummy key"
concourse:
  web:
    externalUrl: https://my-domain.com
...
    letsEncrypt: {enabled: true}
    tls: { enabled: true, bindPort: 443 }
```

After applying this, the web pod will fail with the error:
`* cannot specify --enable-lets-encrypt if --tls-cert or --tls-key are set`

My current workaround is to edit the web deployment after that last failed deploy with helm, and removing the environment variables `CONCOURSE_TLS_CERT` and `CONCOURSE_TLS_KEY`. After doing this, the web pod will deploy successfully and get its certificates from LetsEncrypt.
