### ISSUE TITLE
[stable/kong] Ingress.spec.tls incorrectly templated

### ISSUE THREAD

**Issue by aamielsan** [helm/charts#16461]
**Describe the bug**
- Release keeps failing on Ingress when trying to expose Kong's Admin using Ingress, and adding a TLS for the said Ingress.

**Version of Helm and Kubernetes**:
- Helm: v.2.12.3
- Kubernetes: v.1.13 & v.1.15

**Which chart**:
- stable/kong

**What happened**:
1. Run the install command:
    ```
    helm install stable/kong \
    --set admin.ingress.enabled=true \
    --set admin.ingress.tls="some-secret-tls"
    ```

2. Kong still has been released but also getting this error:
`Error: release bumptious-manta failed: Ingress in version "v1beta1" cannot be handled as a Ingress: v1beta1.Ingress.Spec: v1beta1.IngressSpec.TLS: []v1beta1.IngressTLS: decode slice: expect [ or n, but found ", error found in #10 byte of ...|ll,"tls":"some-secre|..., bigger context ...|namespace":"default"},"spec":{"rules":null,"tls":"some-secret-tls"}}
|...`

**What you expected to happen**:
- Expected it to successfully release Kong, and expose Kong Admin through Ingress.

**How to reproduce it** (as minimally and precisely as possible):
- Run:
    ```
    helm install stable/kong \
    --set admin.ingress.enabled=true \
    --set admin.ingress.tls="some-secret-tls"
    ```

**Anything else we need to know**:
- Running:
    ```
    helm install stable/kong \
    --set admin.ingress.enabled=true \
    --set admin.ingress.tls="some-secret-tls" \
    --dry-run \
    --debug
    ```

    Did show that the Ingress resource has been incorrectly templated:
    ```
    # Source: kong/templates/ingress-admin.yaml
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: belligerent-woodpecker-kong-admin
      labels:
        app: kong
        chart: "kong-0.16.0"
        release: "belligerent-woodpecker"
        heritage: "Tiller"
      annotations:
    spec:
      rules:
      tls:
        some-secret-tls
    ```

Thanks!

**Comment by rainest** [comment]
The Ingress TLS sections are currently mislabeled vis a vis what they actually do, and should be updated to support what they currently claim (simply providing a TLS secret name). The actual template currently expects a whole Ingress TLS section, e.g. something like this in values.yaml should work:

```
  ingress:
    # Enable/disable exposure using ingress.
    enabled: true
    # TLS secret name.
    tls:
    - hosts:
      - admin.kong.example
      secretName: example-kong-admin-tls
```
We'll work on a more elegant version that doesn't require laying that out by hand, but use the above format for existing releases of the chart.
