### ISSUE TITLE
[stable/external-dns] podSecurityContext on values.yaml does not update deployment.

### ISSUE THREAD

**Issue by vinay2107** [helm/charts#16478]
**Version of Helm and Kubernetes**:
helm v2.14.0
kubernetes v1.14.5

**Which chart**:
values-production.yaml (external-dns)

**What happened**:
Was unable to add runAsUser: 0 on podSecurityContext. Does not update pod's security context on deployment file, causing an issue(permission denied on a file).
securityContext: {} 

**What you expected to happen**:
The deployment get updated with security context at pod level
securityContext:
   runAsUser: 0

**How to reproduce it** (as minimally and precisely as possible):
Edit deployment manually, works fine
**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @vinay2107 

Could you share the **values.yaml** you're using?

As you can check on these links, the **securityContext** is set based on the **podSecurityContext** parameter:

- https://github.com/helm/charts/blob/master/stable/external-dns/templates/deployment.yaml#L26
- https://github.com/helm/charts/blob/master/stable/external-dns/values.yaml#L347

**Comment by vinay2107** [comment]
---
image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.14
  pullSecrets: []
  pullPolicy: IfNotPresent

provider: azure
azure:
  resourceGroup: blablabla

publishInternalServices: false
sources:
  - ingress

## Limit possible target zones by domain suffixes (optional)
domainFilters: blabla.blabla

## Adjust the interval for DNS updates
interval: "30s"

# Registry to use for ownership (txt or noop)
registry: "txt"

# When using the TXT registry, a name that identifies this instance of ExternalDNS
txtOwnerId: "blablal"

## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only )
policy: sync

# Verbosity of the logs (options: panic, debug, info, warn, error, fatal)
logLevel: info

# Create RBAC
rbac:
  create: true
  apiVersion: v1beta1
  
podSecurityContext:
  fsGroup: 0
  runAsUser: 0
  runAsNonRoot: false

**Comment by vinay2107** [comment]
---
image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.14
  pullSecrets: []
  pullPolicy: IfNotPresent

provider: azure
azure:
  resourceGroup: {{ cluster_resource_group }}

publishInternalServices: false
sources:
  - ingress

domainFilters: [{{ external_dns_domain_filter }}]

interval: "30s"

registry: "txt"

txtOwnerId: "ccdcentral"

policy: sync

logLevel: info

rbac:
  create: true
  apiVersion: v1beta1

podSecurityContext:
  fsGroup: 0
  runAsUser: 0
  runAsNonRoot: false

**Comment by vinay2107** [comment]
Hi,
Any update on this one ? (qa issue)

**Comment by juan131** [comment]
Hi @vinay2107 

What version of the `stable/external-dns` chart are you using? I was unable to reproduce the issue using the latest chart version (**2.6.0**)?

- My `values.yaml`:

```yaml
image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.14
  pullSecrets: []
  pullPolicy: IfNotPresent
provider: azure
azure:
  resourceGroup: blablabla
publishInternalServices: false
sources:
 - ingress
domainFilters:
 - example.com
interval: "30s"
registry: "txt"
txtOwnerId: "blabla"
policy: sync
logLevel: info
rbac:
  create: true
  apiVersion: v1beta1
podSecurityContext:
  fsGroup: 0
  runAsUser: 0
  runAsNonRoot: false
```

- Commands:

```
$ helm repo update && helm search stable/external-dns
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
NAME               	CHART VERSION	APP VERSION	DESCRIPTION
stable/external-dns	2.6.0        	0.5.16     	ExternalDNS is a Kubernetes addon that configures public ...
$ helm install stable/external-dns --name my-releaes -f values.yaml --dry-run --debug
...
# Source: external-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
...
    spec:
      securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
```

As you can see the `securityContext` is adapted based on the `podSecurityContext` parameter.
