### ISSUE TITLE
[incubator/vault] nil pointer evaluating when using Consul Agent without Consul Storage

### ISSUE THREAD

**Issue by Skaronator** [helm/charts#16543]
**Describe the bug**
Enabling the consulAgent without using consul as Vault Storage results in a nil pointer exception.

**Version of Helm and Kubernetes**:
Helm: v2.14.3
K8s: v1.13.8-eks-a977ba

**Which chart**: incubator/vault

**What happened**: The Vault Helm Chart expect that I use the Consul storage when enabling the Consul Agent. You may ask why would I do that? I want to use the Consul Secret Engine which requires a Consul Agent at a specific IP, ideally localhost.

**What you expected to happen**: It should not throw a nil pointer exception. My current workaround is to do a `consul.token: false` in my Vault Config.

```
    storage:
      dynamodb:
        ha_enabled: "true" # must be a string
        region: {{ .Environment.Values.aws_region }}
        table: {{ .Environment.Values.vault_dynamodb_id }}
      consul:
        token: false
```

**How to reproduce it** (as minimally and precisely as possible):

Enable Consul Agent:
```
consulAgent:
  join: true
```

Without using consul storage:
```
vault:
  dev: false
  config:
    ui: true
    storage:
      dynamodb:
        ha_enabled: "true"
        region: xxxx
        table: xxxx
```

**Anything else we need to know**:
Relevant code line:
https://github.com/helm/charts/blob/989e47ae6dbb0f73e5491b4bc9398e50d34fe1a1/incubator/vault/templates/deployment.yaml#L70-L73

Maybe it would make sense to be able to define the token separately in the consulAgent block and use storage.consul.token by default, if defined.
