### ISSUE TITLE
[stable/jenkins] agent not mounting secret as volume

### ISSUE THREAD

**Issue by mlaythe** [helm/charts#16576]
**Describe the bug**
I'm trying to mount my kubectl config file as a secret onto my jenkin slaves.

**Version of Helm and Kubernetes**:
Helm: v2.13.1
K8s: v1.14.0

**Which chart**:
Jenkins

**What happened**:
No secrets were found at the path specified.

**What you expected to happen**:
To find the mounted secrets.

**How to reproduce it** (as minimally and precisely as possible):
1. Create secret `kubectl create secret generic kubeconfig-secret --from-file=~/.kube/config`
2. Edit `jenkins-values.yaml`
```
agent:
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
    - type: Secret
      secretName: kubeconfig-secret
      mountPath: /var/myapp/mysecret
```
3. Deploy jenkins
4. Add to configuration on jenkins
![Image of jenkins config](https://i.ibb.co/bX2RGqG/Screen-Shot-2019-08-22-at-12-32-27-PM.png)
5. Update `Jenkinsfile` to check if file exists
![Image of jenkins config](https://i.ibb.co/Twxx2fX/Screen-Shot-2019-08-22-at-12-37-05-PM.png)
6. Error will be thrown saying no such file exists

**Anything else we need to know**:
