### ISSUE TITLE
[stable/prometheus-operator] No service created for new Prometheus object

### ISSUE THREAD

**Issue by inhabitech** [helm/charts#16581]
**Describe the bug**
I created a new Prometheus object after creating the chart. I do get pods with the name I gave the Prometheus object, but I am not getting a service object that points to my prometheus statefulset.

**Version of Helm and Kubernetes**:
Helm: 2.14.3 for both client and server
Kubernetes: 1.13.6

**Which chart**:
stable/prometheus-operator

**What happened**:

I got pods for the Prometheus object I asked for:

```
prometheus-service-prometheus-0                             3/3     Running   1          27m
prometheus-service-prometheus-1                             3/3     Running   1          27m
```
But I see no corresponding service for these pods in the same way I see a service for the default prometheus that is monitoring the Kubernetes cluster itself.

**What you expected to happen**:

I would expect a service to be created for my Prometheus object pods. I need this to create a Grafana datasource for my Prometheus object.

**How to reproduce it** (as minimally and precisely as possible):

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: service-prometheus
    prometheus: service-prometheus
  name: service-prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  logLevel: info
  paused: false
  replicas: 2
  retention: 2d
  routePrefix: /
  ruleSelector:
    matchLabels:
      prometheus: service-prometheus
      role: alert-rules
  serviceAccountName: monitoring-prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: serviceapp
      operator: Exists
```

**Anything else we need to know**:

I am not sure this is a misconfiguring of the helm chart on my part, an issue with the operator itself, or something with the Helm chart. If I need to create a service myself, I will, but it seems the operator should do that.
