### ISSUE TITLE
[stable/atlantis] defaultTFVersion doesn't seem to change anything

### ISSUE THREAD

**Issue by YesYouKenSpace** [helm/charts#16585]
**Describe the bug**
I tried setting the default terraform version. But the installation does not seem to reflect that. This is verified when I did an `atlantis plan` and got the following error
```bash
Error refreshing state: state snapshot was created by Terraform v0.12.6, which is newer than current v0.12.1; upgrade to Terraform v0.12.6 or greater to work with this state
```

Even though in the project repo, I already have `atlantis.yaml`:
```yaml
version: 3
automerge: true
projects:
- dir: production
  terraform_version: v0.12.6
  autoplan:
    enabled: false
- dir: staging
  terraform_version: v0.12.6
  autoplan:
    enabled: true
```

**Version of Helm and Kubernetes**:

**Which chart**:
`stable/atlantis:3.7.1`

**What happened**:
In atlantis pod:
```bash
bash-4.4$ terraform --version
Terraform v0.12.1

Your version of Terraform is out of date! The latest version
is 0.12.7. You can update by downloading from www.terraform.io/downloads.html
```

**What you expected to happen**:
Terraform version in atlantis pod to use `0.12.6`

**How to reproduce it** (as minimally and precisely as possible):
In `values.yaml`:
```yaml
...
## defaultTFVersion set the default terraform version to be used in atlantis server
defaultTFVersion: 0.12.6
...
```
`helm install`
`kubectl exec -it` the atlantis pod
`terraform --version`

**Anything else we need to know**:
Nothing.

**Comment by kennethtxytqw** [comment]
The issue resolved itself when I used a newer docker image.
```yaml
image:
  repository: runatlantis/atlantis
  tag: v0.8.3
  pullPolicy: IfNotPresent
```

instead of 
```yaml
image:
  repository: runatlantis/atlantis
  tag: v0.8.3
  pullPolicy: IfNotPresent
```
