### ISSUE TITLE
[stable/datadog] Support Custom log collection 

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/charts#16608]
We are trying to drop/ignore some logs so that datadog does not send them.

According to the [Datadog documentation](https://docs.datadoghq.com/agent/logs/?tab=tailexistingfiles#custom-log-collection), we can:

1. Create a new `<CUSTOM_LOG_SOURCE>.d/` folder in the `conf.d/` directory at the root of your Agent’s configuration directory.
2. Create a new `conf.yaml` file in this new folder.

I don't think this is possible in the current chart. I know we can set `datadog.confd.<filename>.yaml` but these files just end up in `/etc/datadog-agent/conf.d/`, NOT in `/etc/datadog-agent/conf.d/xxxx.d/conf.yaml`.

Is this correct?

Could I make a PR to perhaps add another init container in [here](https://github.com/helm/charts/blob/master/stable/datadog/templates/containers-init.yaml#L1) to support this type of configuration?

**Comment by max-rocket-internet** [comment]
FYI @mfpierre @jhohertz @CharlyF

**Comment by max-rocket-internet** [comment]
Any update, maintainers? @hkaj or @mfpierre or @xlucas or @clamoriniere

**Comment by NBParis** [comment]
Hello @max-rocket-internet 

Thanks for opening this issue. Just to make sure I understand what you are trying to achieve.

Currently you are using the Datadog Agent installed as a container and you are collecting logs with the `collect_all` variable.
Is that correct? If not, would you mind giving us a bit more information about your current setup?

Then from what you said, it seems that you are trying to avoid sending some logs. Would it be possible to let us know if you are trying to exclude logs from a subset of containers (for instance you do not care about the logs of a given image) or if you are trying to choose within containers which logs are sent (sending some of them but not all)?

Based on those, we likely have several options for you as most of the configuration can be done thanks to environment variables or pod annotations.

Thanks

**Comment by max-rocket-internet** [comment]
Hey @NBParis 

> Currently you are using the Datadog Agent installed as a container and you are collecting logs with the collect_all variable. Is that correct? 

Yes. Here's our chart values file:

```yaml
image:
  tag: 6.12.1

datadog:
  site: datadoghq.eu
  logsEnabled: true
  logsConfigContainerCollectAll: true
  env:
    - name: DD_ENABLE_PAYLOADS_EVENTS
      value: "false"
    - name: DD_ENABLE_PAYLOADS_SERIES
      value: "false"
    - name: DD_ENABLE_PAYLOADS_SERVICE_CHECKS
      value: "false"
    - name: DD_ENABLE_PAYLOADS_SKETCHES
      value: "false"
    - name: DD_PROCESS_AGENT_ENABLED
      value: "disabled"
  processAgentEnabled: false
kubeStateMetrics:
  enabled: false
```

I left out `datadog.tags` / `datadog.resources` / `datadog.podLabelsAsTags` / `daemonset.podLabels` as I think they aren't relevant.

> Would it be possible to let us know if you are trying to exclude logs from a subset of containers

Exactly this.

We want to exclude logs from our ingress controllers. They generate a huge volume and even though we don't index them, the volume costs us a lot. But we don't want to disable the log output from the ingress controllers themselves, just stop forwarding them on to Datadog.
