### ISSUE TITLE
[Filebeat stable/filebeat] Modules Don't Enable

### ISSUE THREAD

**Issue by chenchik** [helm/charts#16621]
**Describe the bug**
When trying to use the filebeat modules, they aren't enabled. 

**Version of Helm and Kubernetes**:
Helm
`Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}`
`Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}`

Kubernetes
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.19", GitCommit:"bebe882824db5431820e3d59851c8fb52cb41675", GitTreeState:"clean", BuildDate:"2019-07-26T00:09:47Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}`

**Which chart**:
stable/elastic-stack
stable/filebeat:7.0.1

**What happened**:
Cannot enable modules unless manually exec'ed into the pod.

**What you expected to happen**:
To be able to enable modules using helm values.

**How to reproduce it** (as minimally and precisely as possible):
Include the following in your values.yaml file

```
overrideConfig:
  filebeat.config:
    modules:
      enabled: true
      path: ${path.config}/modules.d/*.yml
      reload.enabled: true
```

**Anything else we need to know**:
I have tried to set this underneath `config` instead of `overrideConfig` (example below)

```
  config:
    filebeat.config:
      modules:
        enabled: true
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: true
```

Which resulted in the following behavior when exec'ed into the pod

```
sh-4.2# filebeat modules list
Error in modules manager: modules management requires 'filebeat.config.modules.path' setting
```
