### ISSUE TITLE
[stable/redis] metrics sidecars in master pod don't work

### ISSUE THREAD

**Issue by emrahcetiner** [helm/charts#16622]
**Describe the bug**
metrics sidecars in master pod don't work but in slave pod work great.
"server returned HTTP status 500 Internal Server Error" message shown on prometheus targets page.

redis services work properly.

**Version of Helm and Kubernetes**:
Helm: v2.14.2
Kubernetes: v1.13.7-gke.8

**Which chart**:
stable/redis

**What happened**:
metrics sidecar in master pod return HTTP 500 error.

**What you expected to happen**:
HTTP 200 response

**How to reproduce it** (as minimally and precisely as possible):
```yaml
  image:
    # tag: 5.0.5-debian-9-r104
    tag: 5.0.5-debian-9-r111
  cluster:
    enabled: true
    slaveCount: 2
  networkPolicy:
    enabled: true
  metrics:
    enabled: true
    image:
      # tag: 1.1.0-debian-9-r1
      tag: 1.1.0-debian-9-r6
```

**Anything else we need to know**:
i've tried both of versions:
- redis:5.0.5-debian-9-r104 & redis-exporter:1.1.0-debian-9-r1
- redis:5.0.5-debian-9-r111 & redis-exporter:1.1.0-debian-9-r6

![image](https://user-images.githubusercontent.com/6555469/63733374-d23b9500-c880-11e9-91e8-493bbb0697a5.png)
