### ISSUE TITLE
[stable/jenkins] Redirects HTTPS to HTTP

### ISSUE THREAD

**Issue by engineertdog** [helm/charts#16666]
**Describe the bug**
Jenkins deployed over SSL on port 443 causes most, but not all, links to redirect the user to an HTTP version of Jenkins, which does not exist (and also causes a reverse proxy error notification).

**Version of Helm and Kubernetes**:
Helm v2.14.3
Kubernetes v1.13

**Which chart**:
stable/jenkins

**What happened**:
When clicking a link on on https://jenkins.domain.com, the user gets redirected to http://jenkins.domain.com

**What you expected to happen**:
I expect the user to stay on an HTTPS version of the website.

**How to reproduce it** (as minimally and precisely as possible):
Using chart overrides, the following is the helm deployment values for this setup.
```
jenkins:
  clusterZone: "cluster.local"
  fullnameOverride: "jenkins"
  namespaceOverride: "jenkins"
  master:
    servicePort: 443
    jenkinsUrl: "jenkins.domain.com"
    jenkinsUrlProtocol: https
    adminPassword: iamrandom
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:accountid:certificate/arn"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```

**Anything else we need to know**:
In relation to #15672, "Jenkins URL" is specified in two places in the UI configuration. In one place, it is set to `https://jenkins.domain.com`, and under `Jenkins Location`, it is specified as `https://jenkins.domain.com/`. However, the configuration under `Jenkins Location`automatically adds the trailing `/` after saving without it.
