### ISSUE TITLE
stable/prometheus - fails with empty clusterrole ruleset

### ISSUE THREAD

**Issue by TheKangaroo** [helm/charts#16690]
**Describe the bug**
If your render prometheus charts without psp, the clusterroles for alertmanager and pushgateways end up without any rules like:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    mylabel: label
  name: just-a-random-name
rules:
```
instead we need to add an empty array like:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    mylabel: label
  name: just-a-random-name
rules:
  []
```

**Version of Helm and Kubernetes**:
helm v2.14.3
k8s 1.13.x

**Which chart**:
stable/prometheus

**What happened**:
```
error: error validating "STDIN": error validating data: ValidationError(ClusterRole): missing required field "rules" in io.k8s.api.rbac.v1beta1.ClusterRole; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
The ClusterRole should be applied successfully.

**How to reproduce it** (as minimally and precisely as possible):
deploy the chart without psp.

**Anything else we need to know**:
