### ISSUE TITLE
stable/rabbitmq node affinity conflict

### ISSUE THREAD

**Issue by srinivasrk** [helm/charts#16701]
**Describe the bug**
When creating rabbitmq with node affinity the volumes are not created to match the affinity

**Error:  `2 node(s) had volume node affinity conflict`**

**Version of Helm and Kubernetes**:
HELM version: 2.14.3
Kubernetes version: 1.12

**Which chart**:
Rabbitmq

**What happened**:
Pod is stuck in pending state, because the node did not have volume affinity

**What you expected to happen**:
Chart to be successfully installed

**How to reproduce it** (as minimally and precisely as possible):
add 
`nodeSelector:
  beta.kubernetes.io/instance-type: "m4.xlarge" `

To the config of rabbitmq chart

**Comment by andresbono** [comment]
Hi @srinivasrk, thanks for letting us know, we will investigate it.

**Comment by rtim75** [comment]
Same here. 
EKS cluster was overcrowded so we needed to scale up. New node have been created in eu-central-1c zone, but the volume created by rabbitmq-ha have node-affinity eu-central-1b which makes pod hang in pending state forever.

```
kubectl get pv -o yaml _pvc-12345_
...
nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - eu-central-1b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - eu-central-1
...
```
```
kubectl get node -o yaml  
...
  labels:
    ...
    failure-domain.beta.kubernetes.io/region: eu-central-1
    failure-domain.beta.kubernetes.io/zone: eu-central-1c
...
```
