### ISSUE TITLE
[stable/prometheus-operator] allow set the image of grafana and kube-state-metrics

### ISSUE THREAD

**Issue by ghost** [helm/charts#16710]
I set image.repository and image.tag of kubeStateMetrics, but not works, the pod also use the default "quay.io/coreos/kube-state-metrics"。

my yaml:
```
kubeStateMetrics:
  image:
    repository: private_repo/kube-state-metrics
    tag: v1.6.0
```
