### ISSUE TITLE
[stable/influxdb] incorrect value reference in backup-cronjob.yaml

### ISSUE THREAD

**Issue by glowka** [helm/charts#16717]
**Describe the bug**

Reference to non-existing field `.Values.image.repo` when if should be`Values.image.repository`
https://github.com/helm/charts/blob/c7f42545d734d06e7fc7ec7a5cac1e43cb21e26f/stable/influxdb/templates/backup-cronjob.yaml#L33

**Version of Helm and Kubernetes**:

helm: v2.13.1
kubernetes: v1.15.3

**Which chart**:

InfluxDB

**What happened**:

Generated CronJob included malformed reference to image `image: :1.7.6-alpine`

```
apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    ...
  spec:
    ...
    jobTemplate:
      ...
      spec:
        template:
          ...
          spec:
            ...
            initContainers:
            - args:
              - -c
              - |
                influxd backup -host telemetry-influxdb.default.svc:8088 -portable /backups/backup_$(date +%Y%m%d_%H%M%S)
              command:
              - /bin/sh
              image: :1.7.6-alpine
              imagePullPolicy: IfNotPresent
              name: influxdb-backup
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /backups
                name: backups
            ...
...
```

**What you expected to happen**:

Malformed line `image: :1.7.6-alpine` should be `image: influxdb:1.7.6-alpine`

**How to reproduce it** (as minimally and precisely as possible):

Run `helm upgrade influxdb-test  stable/influxdb --install --set backup.enabled=true`
