### ISSUE TITLE
[ incubator/aws-alb-ingress-controller] targets are in unhealthy state

### ISSUE THREAD

**Issue by polganesh** [helm/charts#16772]
**Describe the bug**
I am in process to implement AWS ALB for EKS cluster. i can see this helm chart (incubator/aws-alb-ingress-controller) create application load balancer but it is observed that target groups are in unhealthy state
**Version of Helm and Kubernetes**:
helm 2.14.3
k8s - 1.13

**Which chart**:
incubator/aws-alb-ingress-controller

**What happened**:
I am trying to setup prometheus and grafana with prometheus-operator chart. i am able to run prometheus-operator chart with nginx-classic load balancer but it is not working with incubator/aws-alb-ingress-controller

i can see target groups are in unhealthy state 

following is part of values.yaml file for prometheus-operator
```
grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: <my-password>
  service:
    type: NodePort
    port: 80
    targetPort: 80
  ingress:
    enabled: true  
# host is not actual here to avoid revealing name of it. 
    hosts: [grafana.example.com]
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/subnets: <comma seperated list of public subnet to run ALB>
      alb.ingress.kubernetes.io/success-codes: 200-499
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '120'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'      
  admin:
    existingSecret: grafana

```

**What you expected to happen**:
target group should be in healthy state.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
