### ISSUE TITLE
[stable/prometheus-operator] integration with AWS ALB ingress is not working 

### ISSUE THREAD

**Issue by polganesh** [helm/charts#16807]
**Describe the bug**
I am trying to use  prometheus-operator with incubator/aws-alb-ingress-controller.

aws-alb-ingress-controller work correctly and i can able to see targets are in healthy state with simple service and ingress.
reference i took is 
https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/

**Version of Helm and Kubernetes**:
helm version 2.14.3
k8s version 1.13

**Which chart**:
stable/prometheus-operator

**What happened**:
unable to see AWS target group in healthy state for grafana and prometheus created with prometheus-operator

```
grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: <password>
  service:
    type: NodePort
    port: 80
    targetPort: 80
  ingress:
    enabled: true  
    hosts: [<host>]
    path: "/*"
    
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
     
  admin:
    existingSecret: grafana

```

**What you expected to happen**:
unable to see target group in healthy state.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
