### ISSUE TITLE
[stable/grafana] Notifier provisioning not working as expected

### ISSUE THREAD

**Issue by sgops** [helm/charts#16810]
**Describe the bug**
I wanted to configure notification channel provisioning as part of my Helm chart deployment. Datasources with dedicated sidecar container worked without problems. I am using Rancher and the Grafana stable chart. 

According to how the notifiers part is used in configmap and values templates I configured the following value override:

Key:

`notifiers.notifiers\.yaml #note: needed to escape the "." to manage to keep the correct file name`

Value:  

```
notifiers:
  - name: test
    type: email
    uid: test
    org_id: 1
    is_default: true
    settings:
        addresses: test@example.com
```

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Kubernetes: 1.14.6 
Rancher: 2.2.8

**Which chart**:
grafana: 3.8.6

**What happened**:
The ConfigMap is created and also properly mapped. However, there are characters in the first line which results in a parsing error and prevent Grafana from starting.

The relevant ConfigMap part looks like this:
Key: 
`notifiers.yaml`

Value:
```
|-
  notifiers:
  - name: test
      type: email
      uid: test
      org_id: 1
      is_default: true
      settings:
        addresses: test@example.com
```
Grafana log says:

`t=2019-09-03T14:53:23+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Alert notification provisioning error: yaml: unmarshal errors:\n line 1: cannot unmarshal !!str notifie... into notifiers.notificationsAsConfigV0"`

**What you expected to happen**:
The ConfigMap value should look like this:

```
notifiers:
  - name: test
    type: email
    uid: test
    org_id: 1
    is_default: true
    settings:
      addresses: test@example.com
```
If I manually delete the "|-" in the first line and reindent the container starts and notification channel is provisioned in Grafana. However, that breaks the helm chart's update capability.

**How to reproduce it** (as minimally and precisely as possible):

- Use and override notifiers value
Key:

`notifiers.notifiers\.yaml`

Value:  

```
notifiers:
  - name: test
    type: email
    uid: test
    org_id: 1
    is_default: true
    settings:
      addresses: test@example.com
```
- Start helm deployment

**Anything else we need to know**:
Any ideas? Am I doing it wrong? 

Also: is a sidecar implementation for notifiers planned similiar to dashboards and datasources provisioning?
