### ISSUE TITLE
stable/spinnaker chart failing when i pass values.yaml

### ISSUE THREAD

**Issue by vignesh-v3** [helm/charts#16825]
Command to Install:
`helm install --name mytest stable/spinnaker --timeout 1600 -f values.yaml`

values.yaml
Everything is same in values.yaml except the below
```
kubeConfig:
  # Use this when you want to register arbitrary clusters with Spinnaker
  # Upload your ~/kube/.config to a secret
  enabled: true
  secretName: my-kubeconfig
  secretKey: config
  # List of contexts from the kubeconfig to make available to Spinnaker
  contexts:
  - admin@kubernetes
  deploymentContext: admin@kubernetes
```

> ubuntu@ip-10-0-128-5:~$ kubectl get secret | grep my-kubeconfig
> my-kubeconfig                              Opaque                                1      10h

**Tiller Logs:**

> [kube] 2019/09/03 19:01:16 creating 1 resource(s)
> [kube] 2019/09/03 19:01:16 Watching for changes to Job my-release-install-using-hal with timeout of 20m0s
> [kube] 2019/09/03 19:01:16 Add/Modify event for my-release-install-using-hal: ADDED
> [kube] 2019/09/03 19:01:16 my-release-install-using-hal: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
> [kube] 2019/09/03 19:01:16 Add/Modify event for my-release-install-using-hal: MODIFIED
> [kube] 2019/09/03 19:01:16 my-release-install-using-hal: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
> [kube] 2019/09/03 19:05:30 Add/Modify event for myrel-install-using-hal: MODIFIED
> [tiller] 2019/09/03 19:05:30 warning: Release myrel post-install spinnaker/templates/hooks/install-using-hal.yaml could not complete: Job failed: BackoffLimitExceeded
> [tiller] 2019/09/03 19:05:30 warning: Release "myrel" failed post-install: Job failed: BackoffLimitExceeded
> [storage] 2019/09/03 19:05:30 updating release "myrel.v1"
> [tiller] 2019/09/03 19:05:30 failed install perform step: Job failed: BackoffLimitExceeded
> [kube] 2019/09/03 19:11:42 Add/Modify event for my-release-install-using-hal: MODIFIED
> [tiller] 2019/09/03 19:11:42 warning: Release my-release post-install spinnaker/templates/hooks/install-using-hal.yaml could not complete: Job failed: BackoffLimitExceeded
> [tiller] 2019/09/03 19:11:42 warning: Release "my-release" failed post-install: Job failed: BackoffLimitExceeded
> [storage] 2019/09/03 19:11:42 updating release "my-release.v1"
> [tiller] 2019/09/03 19:11:42 failed install perform step: Job failed: BackoffLimitExceeded
