### ISSUE TITLE
[stable/velero] More intuitive Credentials management

### ISSUE THREAD

**Issue by DandyDeveloper** [helm/charts#16827]
**Is your feature request related to a problem? Please describe.**
Currently, the secret management for credentials, whether it be AWS, Azure etc. is cumbersome and difficult to automate effectively. 

In my case, we want to create a pipeline which fetches secrets from Vault API and sets those values in the chart, but the current mechanism in the chart won't allow for this: 

Ex:

```
  credentials:
    secretContents:
      cloud: |-
        [default]
        aws_access_key_id: <- Impossible to reference using --set 
        aws_secret_access_key: <- Impossible to reference using --set 
```

**Describe the solution you'd like**
It would be better to try and simplify the secret management by making it more rigid and based on the configuration provider in the secret templating.

E.G. Someone specifies AWS as a provider, then the secret template will map credentials in the expected AWS format using a series of conditions in the template. 

Same logic for Azure, as the credentials file format is different. 

**Describe alternatives you've considered**
For the time being, I'm having to overwrite these values in my chart using my own template, referencing my own values in the `values.yaml`. It's a workable solution.
