### ISSUE TITLE
[stable/redis-ha] Render error in HAProxy Deployment Template

### ISSUE THREAD

**Issue by frayer** [helm/charts#16869]
**Describe the bug**

I'm receiving the following error when enabling `haproxy.enable` and providing `haproxy.annotations` values at the same time.

```
Error: render error in "redis-ha/templates/redis-haproxy-deployment.yaml": template: redis-ha/templates/redis-haproxy-deployment.yaml:29:3: executing "redis-ha/templates/redis-haproxy-deployment.yaml" at <toYaml>: wrong number of args for toYaml: want 1 got 2
```

**Version of Helm and Kubernetes**:

Client: v2.14.3

**Which chart**: [stable/redis-ha v3.7.4](https://github.com/helm/charts/tree/master/stable/redis-ha)

**What happened**:

When running `helm install` or `helm template` with the configuration mentioned in the description, I'm receiving a Helm `render error`.

**What you expected to happen**:

The ability to apply annotations to the `haproxy` Deployment.

**How to reproduce it** (as minimally and precisely as possible):

In the `stable/redis-ha` directory

Adjust the `values.yaml` file to contain an `haproxy` section which has `haproxy.enabled=true` and at least one entry in `haproxy.annotations`.

***Example:***

```yaml
haproxy:
  enabled: true  # <--- Change from default
  replicas: 1
  image:
    repository: haproxy
    tag: 2.0.4
    pullPolicy: IfNotPresent
  annotations:
    sidecar.istio.io/inject: "false"  # <-- Change from default
  resources: {}
  ## Service type for HAProxy
  ##
  service:
    type: ClusterIP
    annotations: {}
  serviceAccount:
    create: true
  ## Prometheus metric exporter for HAProxy.
  ##
  exporter:
    image:
      repository: quay.io/prometheus/haproxy-exporter
      tag: v0.9.0
    enabled: false
    port: 9101
  init:
    resources: {}
```

In the `stable/redis-ha` directory, try to render the template locally to observe the render error:

` helm template -f values.yaml .`

**Anything else we need to know**:
