### ISSUE TITLE
[stable/postgresql] Pods fail to create

### ISSUE THREAD

**Issue by engineertdog** [helm/charts#16898]
**Describe the bug**
I attempted to deploy v6.3.4 of the stable postgresql chart with HA (replication) and ended up with a deployment that could not create the master pod nor the slave pod. The error messages from each pod are listed below, along with the override values.

**Version of Helm and Kubernetes**:
Helm v2.14.2
Kubernetes v1.13

**What you expected to happen**:
I expect all master pods and slave pods to be created for a HA deployment.

**How to reproduce it** (as minimally and precisely as possible):
- helm create chart_override_name
    - Delete default templates and values.
- helm fetch stable/postgresql
    - unzip stable chart
- Move postgresql chart into custom chart's `chart` folder.
- Use the override values provided below.

**Anything else we need to know**:
Master pod error:
`Error from server (BadRequest): a container name must be specified for pod app-db-postgresql-master-0, choose one of: [app-db-postgresql metrics] or one of the init containers: [init-chmod-data]`

Slave pod error:
`/entrypoint.sh: line 15: nENk: unbound variable`

Chart override
```
postgresql:
  postgresqlUsername: postgresql
  postgresqlPassword: xyz
  postgresqlDatabase: newdb
  replication:
    enabled: true
    slaveReplicas: 3
    synchronousCommit: "on"
    numSynchronousReplicas: 1
    applicationName: app-db
  metrics:
    enabled: true
```
