### ISSUE TITLE
[stable/minio] init with multiple bucket creation

### ISSUE THREAD

**Issue by obeyler** [helm/charts#16921]
**Describe the bug**
I try to install minio with multiple bucket 
only the first bucket is created
this is my value file:
```
      service:
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/path: '/minio/prometheus/metrics'
          prometheus.io/port: '9000'

      buckets:
      - name: registry
      - name: git-lfs
      - name: runner-cache
      - name: gitlab-uploads
      - name: gitlab-artifacts
      - name: gitlab-backups
      - name: gitlab-packages
      - name: tmp
      - name: gitlab-pseudo
      - name: gitlab-mr-diffs 
```
**Version of Helm and Kubernetes**:
helm version --short
Client: v2.14.0+g05811b8
Server: v2.14.0+g05811b8

kubectl version --short
Client Version: v1.14.1
Server Version: v1.14.1

**Which chart**:
helm chart minio version :   2.5.12

**What happened**:
only the first bucket is created 
![image](https://user-images.githubusercontent.com/23224162/64421199-4f48e480-d0a1-11e9-8048-4f49c62df349.png)

the job has this status :
```
 "status": {
    "conditions": [
      {
        "type": "Failed",
        "status": "True",
        "lastProbeTime": "2019-09-06T09:50:49Z",
        "lastTransitionTime": "2019-09-06T09:50:49Z",
        "reason": "BackoffLimitExceeded",
        "message": "Job has reached the specified backoff limit"
      }
    ],
```
**What you expected to happen**:
other bucket need to be created

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
this is the log of job:
````

Connecting to Minio server: http://minio:9000
Added `myminio` successfully.
sh: true: unknown operand
Bucket 'registry' already exists.
Setting policy of bucket 'registry' to ''.
Name:
  mc policy - manage anonymous access to buckets and objects
USAGE:
  mc policy [FLAGS] PERMISSION TARGET
  mc policy [FLAGS] FILE TARGET
  mc policy [FLAGS] TARGET
  mc policy list [FLAGS] TARGET
FLAGS:
  --recursive, -r               list recursively
  --config-dir value, -C value  path to configuration folder (default: "/root/.mc")
  --quiet, -q                   disable progress bar display
  --no-color                    disable color theme
  --json                        enable JSON formatted output
  --debug                       enable debug output
  --insecure                    disable SSL certificate verification
  --help, -h                    show help
  
PERMISSION:
  Allowed policies are: [none, download, upload, public].
FILE:
  A valid S3 policy JSON filepath.
EXAMPLES:
   1. Set bucket to "download" on Amazon S3 cloud storage.
      $ mc policy set download s3/burningman2011
   2. Set bucket to "public" on Amazon S3 cloud storage.
      $ mc policy set public s3/shared
   3. Set bucket to "upload" on Amazon S3 cloud storage.
      $ mc policy set upload s3/incoming
```

**Comment by obeyler** [comment]
It solves.
The bucket array need to contain policy and purge
```
      buckets:
      - name: registry
        policy: none
        purge: false

      - name: git-lfs
        policy: none
        purge: false

      - name: runner-cache
        policy: none
        purge: false

      - name: gitlab-uploads
        policy: none
        purge: false

      - name: gitlab-artifacts
        policy: none
        purge: false

      - name: gitlab-backups
        policy: none
        purge: false

      - name: gitlab-packages
        policy: none
        purge: false

      - name: tmp
        policy: none
        purge: false

      - name: gitlab-pseudo
        policy: none
        purge: false

      - name: gitlab-mr-diffs
        policy: none
        purge: false
```
