### ISSUE TITLE
[stable/drone] Issue while adding PVC to Agents

### ISSUE THREAD

**Issue by ficofer** [helm/charts#16932]
**Describe the bug**
I am editing values.yml the following way:

```
...
agent:
  env:
    DRONE_LOGS_DEBUG: "true"
    DRONE_DOCKER_CONFIG: /root/.docker/config.json

  replicas: 2

  annotations: {}

  volumes:
  - name: persistent-data
    persistentVolumeClaim:
      claimName: drone-agent-pvc
  - name: cache
    hostPath:
      path: /drone-cache
      type: Directory

  ## Volume mount into agent container
  volumeMounts:
  - name: persistent-data
    mountPath: ./build-cache
...
```

The pods for the agent are not getting the new volume attached neither mounted, not sure if I am doing something wrong.

The idea is to have a pvc mounted for pipelines that use something like this

```
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./build-cache
    volumes:
      - /tmp/cache:/cache
```

**Version of Helm and Kubernetes**:

Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

GKE

**Which chart**:

stable/drone

**What happened**:

PVC are not working nor mapped to agent pods

**What you expected to happen**:

Having agent pods with pvc mounted
