### ISSUE TITLE
[stable/cluster-autoscaler] support service account annotations

### ISSUE THREAD

**Issue by dcherman** [helm/charts#16944]
Can we consider adding support for service account annotations if `rbac.create` is `true`?  My use case is that recently, AWS released support for assuming IAM roles on service accounts via adding annotations

https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

My proposed API is:

```
rbac:
  serviceAccount:
    annotations:
      foo: bar
```

WDYT?
