### ISSUE TITLE
[stable/grafana] dashboards are not created

### ISSUE THREAD

**Issue by oke-py** [helm/charts#16941]
**Describe the bug**
Following [Import dashboards](https://github.com/helm/charts/tree/master/stable/grafana#import-dashboards), 4 dashboards are expected to be created.
However, json of only first 2 dashboards are created.

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/grafana

**What happened**:
`prometheus-stats` and `local-dashboard` are not created.

**What you expected to happen**:
`prometheus-stats` can be imported.

**How to reproduce it** (as minimally and precisely as possible):
values.yaml
```
dashboards:
  default:
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/2
      gnetId: 2
      revision: 2
      datasource: Prometheus
    local-dashboard:
      url: https://raw.githubusercontent.com/user/repository/master/dashboards/dashboard.json
```
install chart
```
helm install -f values.yaml --name grafana --namespace monitoring stable/grafana
```

**Anything else we need to know**:

**Comment by chdeliens** [comment]
Hi @oke-py, did you define the `default` dashboard provider in the `dashboardProviders` section?

If not, here's what works for me:

```
dashboardProviders:
    dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
              path: /var/lib/grafana/dashboards/default
```

Hope this helps.
