### ISSUE TITLE
[stable/spinnaker] Allow value interpolation in `additionalProfileConfigMaps`

### ISSUE THREAD

**Issue by afcastano** [helm/charts#16953]
**Is your feature request related to a problem? Please describe.**
At the moment there is no way to dynamically modify the `additionalProfileConfigMaps` attribute. We could allow templating here similar to `additionalInitScript`.

**Describe the solution you'd like**
It would be good to be able to use variables in the contents of the config map. In that way we could leverage the helm templating engine to dynamically modify the services configuration. 

My particular need is related to `orca-local.yml`. I am enabling sql persistence and unfortunately I can only obtain the database ip just before running helm.

If this gets implemented, I could do something like:
```yaml
      orca-local.yml: |-
        sql:
          enabled: true
          connectionPool:
            jdbcUrl: jdbc:mysql://{{ orca.sql_ip }}:3306/orca
            user: orca_service
            password: {{ orca.service_db_password }}
            connectionTimeout: 5000
            maxLifetime: 30000
            maxPoolSize: 50
```

And then pass the variables using `-set` when running helm.

**Describe alternatives you've considered**
At the moment I have to modify the `values.yml` file to replace the values.
