### ISSUE TITLE
[stable/ghost] Sqlite support

### ISSUE THREAD

**Issue by cychong47** [helm/charts#16989]
It looks like the current ghost Helm Chart assume that maridb as a backend db or external database.

**Is your feature request related to a problem? Please describe.**
Fail to deploy the ghost blog with sqlite db instead of mariadb

**Describe the solution you'd like**
ghost blog is deployed with sqlite for db 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by carrodher** [comment]
Hi, can you share with us the parameters (without sensitive data) you are using to connect to the external database? It should be possible to do it without issues, I want to check if there is a misconfiguration, some parameter missing or something like that.

**Comment by cychong47** [comment]
Hi, 
This is the values-minimal.yaml I have used.

```
ghostProtocol: http
ghostHost:acbd.com
ghostPort: 2368
ghostPath: /

ghostUsername: xyz@gmail.com

ghostEmail: xyz@gmail.com
ghostBlogTitle: Ghost Blog
allowEmptyPassword: "yes"

mariadb:
  enabled: false

persistence:
  enabled: true
  storageClass: manual
  accessMode: ReadWriteOnce
  size: 10Gi
  path: /var/lib/ghost/content
```

This is the output of helm install command
```
$ sudo helm install -f values-minimal.yaml stable/ghost
Error: render error in "ghost/templates/deployment.yaml": template: ghost/templates/deployment.yaml:54:27: executing "ghost/templates/deployment.yaml" at <.Values.externalDatabase.host>: nil pointer evaluating interface {}.host
```

Deployment.yaml line 54 is as follow. From this, I suspect sqlite is not supported and only mariadb or something equivalent(not file based such as sqlite) is supported 
Of course I have no issue at all when I deploy the ghost with manual - deployment, service with the kubectl command directly. 

```
50        - name: MARIADB_HOST
51        {{- if .Values.mariadb.enabled }}
52          value: {{ template "ghost.mariadb.fullname" . }}
53        {{- else }}
54          value: {{ .Values.externalDatabase.host | quote }}
55        {{- end }}
```

Thanks,
