### ISSUE TITLE
[stable/rabbitmq] using load-definition in extraConfiguration 

### ISSUE THREAD

**Issue by xetra11** [helm/charts#16982]
**Describe the bug**
To configure TTL and Dead Letter Exchange via Helm chart I added the following *secret* with load-definitions. The way I did that was the result of researching for the usage of a configuration with Helm.
Before I used the `load-definition` everything worked fine and the container ran successfully. When using `load-defintions` from a new secret and referencing it in the `values-dev.yml` the credentials are not accepted anymore.

**Version of Helm and Kubernetes**:
Helm v2.13.1
Kubernetes: 1.12.9-gke.15

**Which chart**:

```
name: company-components-rabbitmq
version: 0.1.0
home: https://bitbucket.org/company/configuration-google/src/master/
description: Basic components
keywords:
  - docker
sources:
  - https://bitbucket.org/company/configuration-google/src/master/
dependencies:
  - name: rabbitmq
    version: 5.5.0
    repository: "@stable"
```

**What happened**:
When using `helm` like this:
```
helm upgrade --install --namespace=dev company-components-rabbitmq-test -f ./helm-charts/components/rabbitmq/values-dev.yaml ./helm-charts/components/rabbitmq
```
The StateFul Set of RabbitMQ is being started. The Pod yields the first error that something went wrong. When looking at the Container Logs I read the following:
```
2019-09-09 12:00:58.546 [warning] <0.573.0> HTTP access denied: user 'test' - invalid credentials
```

This is the `Secret.yml`:
```
apiVersion: v1
kind: Secret
metadata:
    name: load-definition
type: Opaque
stringData:
    load_definition.json: |-
        {
          "vhosts": [
            { "name" : "/" }
          ],
          "policies": [
            {
                "vhost":"/",
                "name":"DLX",
                "pattern":".*",
                "apply-to":"queues",
                "definition":{"dead-letter-exchange":"dead_letter"},
                "priority":0
            }
          ]
        }
```
And there is the `values-dev.yml`:
```
rabbitmq:
  persistence:
    enabled: false
    #existingClaim: rabbitmq-volume-claim #commented because throws errors
  rabbitmq:
    username: test
    password: test123
    loadDefinition:
      enabled: true
      secretName: load-definition
    extraConfiguration:
      management.load_definitions = /app/load_definition.json
  nodeSelector:
    type: backend
```
The Credentials should be fine.
They are defined in a ConfigMap:

```
  RABBIT_MQ_USER: test
  RABBIT_MQ_PASSWORD: test123
```

The ConfigMap and the Secrets seem to be released successfully:
```
RESOURCES:
==> v1/ConfigMap
NAME                                  DATA  AGE
company-components-rabbitmq-test-config  2     2d22h
==> v1/Secret
NAME                           TYPE    DATA  AGE
load-definition                Opaque  1     2d20h
company-components-rabbitmq-test  Opaque  2     2d22h

```
Double Checking the ConfigMap shows me that username and password are as expected.
When checking the enviroment variables of the container however I see this:

Liveness probe:
```
exec
sh -c rabbitmq-api-check "http://test:$RABBITMQ_PASSWORD@127.0.0.1:23134/api/healthchecks/node" '{"status":"ok"}'
```

**What you expected to happen**:
I expect the container to run and have successfull liveness probing as before where I did not defined `load-definitions`

**How to reproduce it** (as minimally and precisely as possible):
Try to use my configurations mentioned here.
