### ISSUE TITLE
[stable/rabbitmq] load definition secret is not allowed to have a custom name

### ISSUE THREAD

**Issue by xetra11** [helm/charts#16990]
**Describe the bug**
This is the how to define `load-definition` in the `values.yaml`:

```
    loadDefinition:
      enabled: true
      secretName: load-definition
    extraConfiguration:
      management.load_definitions = /app/load_definition.json
```
When naming `secretName` to something like `myLoadDefinition` it is not working since the Chart is looking for a secrent named `load-definition`. Is this on purpose? Cause I was not aware through any documentation but found out the hard way looking for the error.

**Which chart**:
stable/rabbitmq
