### ISSUE TITLE
[stable/prometheus] alertmanager Readiness probe failed: HTTP probe failed with statuscode: 404 

### ISSUE THREAD

**Issue by amol2311** [helm/charts#16995]
**Describe the bug**

**Version of Helm and Kubernetes**:
v2.14.2

**Which chart**:
https://github.com/helm/charts/tree/master/stable/prometheus

**What happened**:
When I put baseURL in values.yaml and try to install alertmanager. pod is showing 
HTTP probe failed with statuscode: 404. I need use that external url to access alertmanager from email alert. (pod is running fine if I keep baseurl blank but in that case my "view in alertmanager " link is not working. )
**What you expected to happen**:Readiness probe failed: 
It should allow me to add baseURL and "View in alertmanager link should be accessible in email"

**How to reproduce it** (as minimally and precisely as possible):
Just execute helm template and deploy generated yaml files on kubernetes

**Anything else we need to know**:

**Comment by amol2311** [comment]
Anyone please help here

**Comment by jsc-it** [comment]
Hi @amol2311, try to set the path of the base url in `.Values.alertmanager.prefixURL` worked for me.

**Comment by ntorba** [comment]
> Hi @amol2311, try to set the path of the base url in `.Values.alertmanager.prefixURL` worked for me.

Hi @jsc-it, can you tell me what value exactly used here? Is it the slug? The entire url? I'm having similar troubles. Thanks!

**Comment by itdevelopmentapps** [comment]
I had the same issue but I only wanted to expose the server using the ingress:

```
server:
  persistentVolume:
    storageClass: "gp2"

  baseURL: "https://bla.domain.com/prometheus"
  prefixURL: "/prometheus"

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    extraLabels: {}

    hosts:
      - bla.domain.com/prometheus
```

Also important was that I had to update my grafana data source to this url: http://prometheus-server.prometheus.svc.cluster.local/prometheus

**Comment by lvthillo** [comment]
I had the same issue but I only wanted to expose the server using the ingress:

```
server:
  persistentVolume:
    storageClass: "gp2"

  baseURL: "https://bla.domain.com/prometheus"
  prefixURL: "/prometheus"

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    extraLabels: {}

    hosts:
      - bla.domain.com/prometheus
```

Also important was that I had to update my grafana data source to this url: http://prometheus-server.prometheus.svc.cluster.local/prometheus
