### ISSUE TITLE
[incubator/kafka] Using chart as a subchart uses the name of the parent chart deployment for external access

### ISSUE THREAD

**Issue by arrkaye** [helm/charts#17002]
**Describe the bug**
When distinct: false or true, domain: example.com, type: LoadBalancer, and "advertised.listeners":      EXTERNAL://kafka.example.com:31090, the chart uses the name of the helm deployment as the external access url

**Which chart**:
incubator/kafka

**What happened**:
It uses the values passed into helm --name <NAME> as the url. This is difficult when kafka is used as a subchart of our own chart.

**What you expected to happen**:
It should use kafka.example.com as the external-dns entry

**How to reproduce it** (as minimally and precisely as possible):

```
replicas: 3
external:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  dns:
    useInternal: false
    useExternal: true
  distinct: false
  servicePort: 19092
  firstListenerPort: 31090
  domain: example.com
 configurationOverrides:
  "confluent.support.metrics.enable": false  # Disables confluent metric submission
  "advertised.listeners": |-
    EXTERNAL://kafka.example.com:31090
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
 jmx:
  configMap:
    enabled: true
prometheus:
  jmx:
    enabled: true
  kafka:
    enabled: true
  operator:
    enabled: true
    serviceMonitor:
      # Namespace Prometheus is installed in
      namespace: infra
      selector:
        prometheus: kube-prometheus

```
