### ISSUE TITLE
[stable/mongodb] MongoDB custom configmap settings not working for replicaset

### ISSUE THREAD

**Issue by kwill4026** [helm/charts#17049]
**Describe the bug**:

I was able to set up TLS/SSL into the mongodb helm chart for secure communication between the mongod's and its servers by using self signed certs. I have a init script located in files/docker-entrypoint-initdb.d/ which creates the root CA that gets created in the master pod as well as the in the secondaries using the same CA. The second part of the script will then use that CA to generate server certs which will be unique for each pod that gets created. 
The next step is to enable to the mongod server to accept TLS settings via the configmap settings which in this case will be adding net.ssl.CAFile and net.ssl.PEMKeyfile. However when attempting to add this in the values.yaml file, the pod is unable to run and immediately enters a Error state.

**Version of Helm and Kubernetes**:
```
Helm Version:
 Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: 
```
stable/mongodb
```

**What happened**:
Running the default mongodb helm cart as a standalone (replicaSet.enabled=false) without modifying the configmap settings in the values.yaml file causes the pod to run fine with no issues and also allows me to connect to the mongo as the root user. 
```
NAME                                READY   STATUS    RESTARTS   AGE
pod/test-mongodb-585f9c459f-vcvpb   1/1     Running   0          70s
```
```
I have no name!@test-mongodb-585f9c459f-vcvpb:/$ mongo admin -u root -p $MONGODB_ROOT_PASSWORD 
MongoDB shell version v4.0.12
connecting to: mongodb://127.0.0.1:27017/admin?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("58624231-2786-4204-a11f-ad858bab62fb") }
MongoDB server version: 4.0.12

```

However using the same mongod conf settings in that previous working image to manually input into the configmap section of the values.yaml file utilizing the same standalone settings causes the image to recognize a custom mongodb.conf has been detected. And is able to complete the MongoDB setup however it restarts the server once and when attempting to connect to the mongo as a root user it fails. 

```
NAME                                READY   STATUS    RESTARTS   AGE
pod/test-mongodb-7f54c46c74-4fgx2   1/1     Running   1          93s
```
```
I have no name!@test-mongodb-7f54c46c74-4fgx2:/$ mongo admin -u root -p $MONGODB_ROOT_PASSWORD
MongoDB shell version v4.0.12
connecting to: mongodb://127.0.0.1:27017/admin?gssapiServiceName=mongodb
2019-09-10T15:26:36.182+0000 E QUERY    [js] Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:344:17
@(connect):2:6
exception: connect failed
I have no name!@test-mongodb-7f54c46c74-4fgx2:/$ 

```
This is the configmap I am using. Which is the exact same one as when I am running the mongodb chart with its default settings and I bash into the pod to view the mongodb.conf file.
```
configmap: 
   storage:
      dbPath: /bitnami/mongodb/data/db
      journal:
          enabled: true
      directoryPerDB: false
      systemLog:
          destination: file
          quiet: false
          logAppend: true
          logRotate: reopen
          path: /opt/bitnami/mongodb/logs/mongodb.log
          verbosity: 0
      net:
          port: 27017
          unixDomainSocket:
              enabled: true
              pathPrefix: /opt/bitnami/mongodb/tmp
          bindIpAll: true
      security: 
          authorized: enabled 
```

Now this time I enabled the replicaSet and run the same configuration type with me manually specifying the configmap settings in the values.yaml file. The pods this time instead of running at least, immediately crashes and doesnt complete the setup once it detects there is a custom mongod.conf file 
```
fmpinto@ip-10-114-23-236 mongodb]$ kubectl get all
NAME                           READY   STATUS             RESTARTS   AGE
pod/test-mongodb-arbiter-0     0/1     CrashLoopBackOff   4          2m2s
pod/test-mongodb-primary-0     0/1     CrashLoopBackOff   3          2m2s
pod/test-mongodb-secondary-0   0/1     Error              4          2m2s

[user@ip-10-114-23-236 mongodb]$ kubectl logs pod/test-mongodb-primary-0
 16:58:24.32 
 16:58:24.32 Welcome to the Bitnami mongodb container
 16:58:24.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 16:58:24.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 16:58:24.33 Send us your feedback at containers@bitnami.com
 16:58:24.33 
 16:58:24.33 INFO  ==> ** Starting MongoDB setup **
 16:58:24.34 INFO  ==> Validating settings in MONGODB_* env vars...
 16:58:24.34 INFO  ==> Initializing MongoDB...
 16:58:24.35 INFO  ==> Deploying MongoDB from scratch...
 16:58:24.35 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
```

**What you expected to happen**:
I expect to be able to specify custom configmap settings via the configmap section in the values.yaml file regardless if its a standalone or replicaset. Once the custom configmap is specified, I expect to be able to run the pods and be able to connect to the mongo.
I expect whatever settings I specify in the configmap section to create the pod thus I will be able to specify TLS/SSL settings in the configmap section to include
the net.ssl.CAFile and net.ssl.PEMKeyFile such as this: 
```
net:
          port: 27017
          ssl: 
             CAFile: /pathICreated/mongodb-ca.crt
             PEMKeyFile: /pathICreated/mongodb.pem
             mode: preferSSL
          unixDomainSocket:
              enabled: true
              pathPrefix: /opt/bitnami/mongodb/tmp
          bindIpAll: true
```
Alternatively the values.yaml file specifies a configmap section mongo conf settings as well as mongod and mongos Command-Line Options using the extra flags settings. Therefore when I attempt to specify TLS/SSL settings via the MongoDB additional command line flags in the values.yaml file, I expect it to take in those settings. However for some reason, in the values.yaml file when I have the configmap section set back to the default (configmap: []) and decide to specify parameters in the extra flags section, it is able to take parameters like "--wiredTigerCacheSizeGB=2" and "--port=27017" but once I specify other settings, especially TLS/SSL settings, it doesnt run the pod. I expect to be able to specify the following in the values.yaml file which will cause the mongod server to start up with TLS/SSL and then allow a client to connect to it since its TLS/SSL enabled. 
```
mongodbExtraFlags:
      - "--sslMode=preferSSL"
      - "--sslPEMKeyFile=/pathICreated/mongodb.pem"
      - "--sslCAFile=/pathICreated/mongodb-ca.crt"
mongodbClientExtraFlags: 
      - "--ssl"
      - "--sslPEMKeyFile=/pathICreated/mongodb.pem"
      - "--sslCAFile=/pathICreated/mongodb-ca.crt"
```

**How to reproduce it** (as minimally and precisely as possible):
Run the stable/mongodb chart with no changes to the configmap section as a standalone then attempt to do the same as a standalone but include your own configmap. 
Also do the same exact thing with the chart as a replicaset. 

When attempting to use command line options by utilizing the MONGODB_EXTRA_FLAGS and MONGODB_CLIENT_EXTRA_FLAGS section, include TLS/SSL mongo settings and watch the pods not load up because of this. 

**Anything else we need to know**:
As I stated I was able to create a root CA and the server certs for each pod but I am unable to start the mongo to create the replicaset to be TLS/SSL enabled. 
According to the bitnami/bitnami-docker-mongodb located here 
```
https://github.com/bitnami/bitnami-docker-mongodb
``` 
This container supports enabling SSL/TLS between nodes in the cluster, as well as between mongo clients and nodes, by setting the MONGODB_EXTRA_FLAGS and MONGODB_CLIENT_EXTRA_FLAGS environment variables or by specifying it in the mongo configmap settings.

**Comment by marcosbc** [comment]
Hi @kwill4026,

We've reproduced the issues with your configuration. In both cases there seem to be a mix of misconfigurations and bugs in the container:

- In the first case the "authorized" should be "authorization".

```
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
    systemLog:
      destination: file
      quiet: false
      logAppend: true
      logRotate: reopen
      path: /opt/bitnami/mongodb/logs/mongodb.log
      verbosity: 0
    net:
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
      bindIpAll: true
    security:
      authorized: enabled
```

  Meaning it would look like this:

```
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    bindIpAll: true
  security:
    authorization: enabled
```

- In the second case, you mentioned using the configuration file below, which has added the "keyfile" property:

```
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
  systemLog:
     destination: file
     logAppend: true
     path: /opt/bitnami/mongodb/logs/mongodb.log
  net:
    port: 27017
    bindIp: 0.0.0.0
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
  replication:
    replSetName: rs0
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter:
     enableLocalhostAuthBypass: false
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```

  Unless `/opt/bitnami/mongodb/conf/keyfile` was specifically mounted the option should be disabled:

```
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
  systemLog:
    destination: file
    logAppend: true
    path: /opt/bitnami/mongodb/logs/mongodb.log
  net:
    port: 27017
    bindIp: 0.0.0.0
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
  replication:
    replSetName: rs0
  processManagement:
    fork: false
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter:
    enableLocalhostAuthBypass: false
  security:
    authorization: enabled
#    keyFile: /opt/bitnami/mongodb/conf/keyfile
```

In summary this is the list of bugs we found:

- The container is stopped after a proper configuration was detected:

```
...
 10:30:22.72 INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
 10:30:23.60 INFO  ==> Creating users...
 10:30:23.61 INFO  ==> Creating root user...
 10:30:23.68 INFO  ==> Stopping MongoDB...
(container is stopped)
```

Apparently this happens because the process ends up defunct:

```
$ ps auxf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
...
1001          45  0.3  0.0      0     0 ?        Z    13:44   0:00 [mongod] <defunct>
```

The current logic executes `kill` so I tried other alternatives (such as `mongod --shutdown` and `db.shutdownServer()`), however both end up with the same result (defunct MongoDB process).

This only happens on K8s, normal docker-compose installs work fine. It was already reported here with a different solution so I think it is possible this is a MongoDB bug: https://github.com/docker-library/mongo/issues/71

- The `/opt/bitnami/mongodb/conf/keyfile` file is created after MongoDB is stopped. Note once this is fixed, **it is still needed to enable the options below in your `values.yaml`**:

```
diff --git a/stable/mongodb/values.yaml b/stable/mongodb/values.yaml
index f5fc4b2e1..6e37c7144 100644
--- a/stable/mongodb/values.yaml
+++ b/stable/mongodb/values.yaml
@@ -145,7 +145,7 @@ service:
 #
 replicaSet:
   ## Whether to create a MongoDB replica set for high availability or not
-  enabled: false
+  enabled: true
   useHostnames: true

   ## Name of the replica set
@@ -154,13 +154,13 @@ replicaSet:

   ## Key used for replica set authentication
   ##
-  # key: key
+  key: mykey123

   ## Number of replicas per each node type
   ##
```

We are still looking into both issues and will get back with any update.
