### ISSUE TITLE
[stable/concourse] main team ldap group

### ISSUE THREAD

**Issue by obeyler** [helm/charts#17048]
**Describe the bug**
the ldap group auth doesn't affect the group to the main team. If I connect with an user of the group witch shall be on main team, i've got a 400 http error.

```
concourse:
  web:
    auth:
       mainTeam:
         ldap:
           group:
           - "admin"
```
will create an env 
`CONCOURSE_MAIN_TEAM_LDAP_GROUP: [admin]`
despite this an user of group admin is not affected to main team. see the log:
```
"timestamp":"2019-09-10T15:12:48.247876614Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"performing ldap search ou=users,dc=orange,dc=com sub (\u0026(objectClass=organizationalPerson)(uid=obeyler))","session":"7"}}
{"timestamp":"2019-09-10T15:12:48.249825348Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"username \"obeyler\" mapped to entry uid=obeyler,ou=xxx,dc=xxxx,dc=com","session":"7"}}
{"timestamp":"2019-09-10T15:12:48.251998307Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"performing ldap search ou=xxxx,ou=xxxx,dc=xxxx,dc=com sub (\u0026(objectClass=groupOfUniqueNames)(uniqueMember=uid=obeyler,ou=users,dc=xxxxx,dc=com))","session":"7"}}
{"timestamp":"2019-09-10T15:12:48.269637066Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"ldap\", username=\"obeyler\", email=\"Olivier.Beyler@xxxxxx.com\", groups=[\"admin\"]","session":"7"}}
{"timestamp":"2019-09-10T15:12:48.493861054Z","level":"error","source":"atc","message":"atc.sky.callback.failed-to-issue-concourse-token","data":{"error":"user doesn't belong to any team","session":"6.501"}} 
```
note the **user doesn't belong to any team** even he belongs to admin group

If I connect with fly to the concourse and play this command:
```
fly -t main set-team -n main --ldap-group admin
setting team: main

role owner:
  users:
    none

  groups:
  - ldap:admin

apply team configuration? [yN]: y
team updated

```
after doing that I'm able to connect to the concourse

When I compare with the concourse installed by bosh (and it works fine with ldap admin group )
the env is different `[admin]` => `admin`

`CONCOURSE_MAIN_TEAM_LDAP_GROUP: admin`

I suppose it's the reason of this issue

**Which chart**: 
stable/concourse 8.2.3

**Comment by obeyler** [comment]
I see that
https://concourse-ci.org/ldap-auth.html#configuring-main-team-authorization
so the attribute should not be set
like:
```
concourse:
  web:
    auth:
       mainTeam:
         ldap:
           group:
           - "admin"
           - "toto"
```
but like this
```
concourse:
  web:
    auth:
       mainTeam:
         ldap:
           group: "admin,toto"
```
