### ISSUE TITLE
[stable/redis-ha] haproxy loadBalancerIP field

### ISSUE THREAD

**Issue by adsail** [helm/charts#17047]
**Is your feature request related to a problem? Please describe.**
I would like to be able to express a loadBalancerIP for the haproxy *iff* deploying haproxy as type LoadBalancer.

**Describe the solution you'd like**

Example: https://github.com/helm/charts/blob/master/stable/redis/templates/redis-with-sentinel-svc.yaml#L18

```
haproxy:
  enabled: true
  # Enable if you want a dedicated port in haproxy for redis-slaves
  readOnly:
    enabled: true
    port: 6380
  replicas: 1
  image:
    repository: haproxy
    tag: 2.0.4
    pullPolicy: IfNotPresent
  annotations: {}
  resources: {}
  ## Service type for HAProxy
  ##
  service:
    type: LoadBalancer
    loadBalancerIP: #.#.#.#
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

**Describe alternatives you've considered**
In theory, could export the yaml for the haproxy and redeploy with desired loadBalancerIP. 

**Additional context**
