### ISSUE TITLE
[stable/neo4j] Access leader node bolt port remotely

### ISSUE THREAD

**Issue by chrispage1** [helm/charts#17051]
Hi,

I've just setup the neo4j helm chart, and its great. My question is, I'm trying to expose the bolt port remotely but I only want to expose the leader so that it can be queried (read and write). When I've setup a nodeport previously, it iterates between the leader and followers so at times I can't query it.

Does anyone have experience in doing this? I'm deploying on a bare metal system and it will need to talk with other servers.

Thanks!

**Comment by chrispage1** [comment]
So to access the cluster remotely, I've created a NodePort service so I can remotely access bolt via port `30725`. However, when doing this, it's a gamble as to wherever we get connected to a leader or a follower - 

```
apiVersion: v1
kind: Service
metadata:
  name: pool1-neo4j-nodeport
  namespace: neo4j
spec:
  type: NodePort
  ports:
  - port: 7687
    nodePort: 30725
    protocol: TCP
  selector:
    app: neo4j
    component: core
    release: pool1
```

How would anyone usually go about ensuring only a connection to the current leader? Otherwise, I end up getting the following error - 

```
Neo.ClientError.Cluster.NotALeader: No write operations are allowed directly on this database. Writes must pass through the leader. The role of this server is: FOLLOWER
```
