### ISSUE TITLE
grafana pvc template not working as expected.

### ISSUE THREAD

**Issue by snoby** [helm/charts#1706]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```
**Which chart**:
```
stable/grafana
```

**What happened**:
I have a values file that i want to pass in my own persistent volume claim.  For some reason, the template in https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/pvc.yaml on the line 
```
{{- if not .Values.server.persistentVolume.existingClaim -}}
```
is not picking up where I have defined my existingClaim in my values.yaml file.
**What you expected to happen**:
I would have thought that the pvc template would have just accepted the claim I had already made.

**How to reproduce it** (as minimally and precisely as possible):
I use this command:
` helm install --namespace monitoring --name g2 -f values.yaml stable/grafana --debug --dry-run`
and the result for the pvc.yaml is:
```YAML
# Source: grafana/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  labels:
    app: g2-grafana
    chart: "grafana-0.2.0"
    component: "grafana"
    heritage: "Tiller"
    release: "g2"
  name: g2-grafana
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "6Gi"
---
```

**Anything else we need to know**:
My values.yaml file for persistentVolume looks like this:
```YAML
  # Persist data to a persitent volume
  persistentVolume:
    ## If true, Grafana will create a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true

    ## Grafana data Persistent Volume access modes
    ## Must match those of existing PV or dynamic provisioner
    ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    accessModes:
      - ReadWriteMany

    ## Grafana data Persistent Volume annotations
    ##
    annotations: {}

    ## Grafana data Persistent Volume existing claim name
    ## Requires server.persistentVolume.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: "grafana-pvc-01"

    ## Grafana data Persistent Volume size
    ## Default: 1Gi
    ##
    size: 6Gi

    ## Data Persistent Volume Storage Class
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    #storageClass:

    ## Subdirectory of data Persistent Volume to mount
    ## Useful if the volume's root directory is not empty
    ##
    subPath: "/"
```
