### ISSUE TITLE
[stable/jenkins] JCasC doesn't work if master.sidecars.configAutoReload.enabled is set to true

### ISSUE THREAD

**Issue by SUNIL23891YADAV** [helm/charts#17135]
**Describe the bug**
JCasC not loading up while enabling the sidecars.

**Version of Helm and Kubernetes**:
helm version 
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:56:40Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Jenkins

**What happened**:
While using values.yaml to enable JCasC.  When I set master.sidecars.configAutoReload.enabled : true. JCasC doesn't work. I am deploying it on AKS cluster.

**What you expected to happen**:
Expected to JCasC to work. Jenkins Server should have come up with welcome message.

**How to reproduce it** (as minimally and precisely as possible):

Run below command and use below values.yaml. 

```
helm install --name jenkins --namespace jenkins -f values.yaml stable/jenkins
```

```
master:
  componentName: "jenkins-master"
  image: "jenkins/jenkins"
  tag: "lts"
  adminUser:  admin
  adminPassword:  asdfg
  version: 0.0.1
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  servicePort: 8080
  serviceAnnotations : 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  targetPort : 8080
  slaveListenerPort : 50000
  loadBalancerIP: "10.114.121.90"
  serviceType: LoadBalancer

  installPlugins:
    - kubernetes:1.18.1
    - workflow-job:2.33
    - workflow-aggregator:2.6
    - credentials-binding:1.19
    - git:3.11.0
  
  JCasC:
    enabled: true
    PluginVersion: 1.27
    SupportPluginVersion: 1.18
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Price and Promotions Jenkins Server. This Jenkins is configured and managed 'as code'.   
       
  sidecars:
    configAutoReload:
      enabled: true
      image: shadwell/k8s-sidecar:0.0.2
      imagePullPolicy: IfNotPresent
      resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
     

agent:
  enabled: true
  image: $REPOSITORY.azure.io/jenkins-slave
  tag: latest
  alwaysPullImage: false
  podName: jenkins-slave
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

```

Output:

```

NAME:   jenkins
LAST DEPLOYED: Sun Sep 15 02:18:32 2019
NAMESPACE: jenkins
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                    DATA  AGE
jenkins                                 6     1s
jenkins-jenkins-config-welcome-message  1     1s
jenkins-tests                           1     1s

==> v1/Deployment
NAME     READY  UP-TO-DATE  AVAILABLE  AGE
jenkins  0/1    1           0          1s

==> v1/PersistentVolumeClaim
NAME     STATUS   VOLUME   CAPACITY  ACCESS MODES  STORAGECLASS  AGE
jenkins  Pending  default  1s

==> v1/Pod(related)
NAME                      READY  STATUS   RESTARTS  AGE
jenkins-6bc4ddc4d9-8jpp7  0/2    Pending  0         0s

==> v1/Role
NAME                     AGE
jenkins-casc-reload      1s
jenkins-schedule-agents  1s

==> v1/RoleBinding
NAME                      AGE
jenkins-schedule-agents   1s
jenkins-watch-configmaps  1s

==> v1/Secret
NAME     TYPE    DATA  AGE
jenkins  Opaque  3     1s

==> v1/Service
NAME           TYPE          CLUSTER-IP      EXTERNAL-IP  PORT(S)         AGE
jenkins        LoadBalancer  10.114.119.231  <pending>    8080:31100/TCP  1s
jenkins-agent  ClusterIP     10.114.119.234  <none>       50000/TCP       1s

==> v1/ServiceAccount
NAME     SECRETS  AGE
jenkins  1        1s


NOTES:
1. Get your 'admin' user password by running:
  printf $(kubectl get secret --namespace jenkins jenkins -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode);echo
2. Get the Jenkins URL to visit by running these commands in the same shell:
  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        You can watch the status of by running 'kubectl get svc --namespace jenkins -w jenkins'
  export SERVICE_IP=$(kubectl get svc --namespace jenkins jenkins --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  echo http://$SERVICE_IP:8080/login

3. Login with the password from step 1 and the username: admin

4. Use Jenkins Configuration as Code by specifying configScripts in your values.yaml file, see documentation: http:///configuration-as-code and examples: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos

For more information on running Jenkins on Kubernetes, visit:
https://cloud.google.com/solutions/jenkins-on-container-engine
For more information about Jenkins Configuration as Code, visit:
https://jenkins.io/projects/jcasc/

```

**Anything else we need to know**:

When I set master.sidecars.configAutoReload.enabled : false. JCasC  work as expected.
