### ISSUE TITLE
[stable/jenkins] agent.envVars doesn't support value from secret

### ISSUE THREAD

**Issue by acesir** [helm/charts#17186]
**Is your feature request related to a problem? Please describe.** 
agent.envVar does not support retrieving values from secrets

**Describe the solution you'd like**
Ability to use values from secret key references

**Describe alternatives you've considered**
1. Currently we need to terraform pull secret from kubernetes and pass in as a value as a parameter
2. Alter the config.xml and add the secret retrieval there

**Additional context**
We pull in AWS credentials and others into out agent pod's which we unfortunately cannot

Specifically setting the **agent** env var for pod in this manner does not seem to work:
```
agent:
  envVars:
    - name: key_id
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: key_id
```
