### ISSUE TITLE
[stable/wordpress] Ingress path issue

### ISSUE THREAD

**Issue by ernanirst** [helm/charts#17196]
**Describe the bug**
JS, CSS and blog links are broken, they don't reflect the path name I used to create the chart. I expected the base domain of the site to be `domain.com/blog` but instead it's `blog.domain.com`.

**Version of Helm and Kubernetes**:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**Which chart**:

`stable/wordpress`

**What happened**:

I successfully deployed the wordpress chart on `blog.domain.com` with the following values:
```
ingress:
  enabled: true
  annotations:
  - kubernetes.io/ingress.class: nginx
  hosts:
  - name: blog.domain.com
     path: /
  tls:
  - hosts:
    - blog.domain.com
    secretName: cert-manager-keys
wordpressUsername: admin
wordpressPassword: password
```
However, I wanted to deploy this wordpress on `domain.com/blog` so I changed the config to:
```
ingress:
  enabled: true
  annotations:
  - kubernetes.io/ingress.class: nginx
  hosts:
  - name: domain.com
     path: /blog
  tls:
  - hosts:
    - domain.com
    secretName: cert-manager-keys
wordpressUsername: admin
wordpressPassword: password
```

When I opened the site on the browser this is what I saw:
![Screen Shot 2019-09-17 at 15 36 00](https://user-images.githubusercontent.com/5594085/65069458-193d1780-d961-11e9-9893-e636f3719715.png)

**What you expected to happen**:

I expected the chart to include the path to the site root url, but it didn't. I also didn't find any other value that I could use to set the site's URL.

**How to reproduce it** (as minimally and precisely as possible):

Simply create a wordpress chart with a ingress path, e.g.:
```
ingress:
  enabled: true
  annotations:
  - kubernetes.io/ingress.class: nginx
  hosts:
  - name: domain.com
     path: /blog
  tls:
  - hosts:
    - domain.com
    secretName: cert-manager-keys
```

**Comment by juan131** [comment]
Hi @ernanirst 

As you mentioned running the WP blog in a subpath doesn't work very well. You can try to use custom NGINX rules to try to fix the wrong links but I don't think you'll be able to solve it. Sth like:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      subs_filter_types text/css text/html application/javascript application/x-javascript;
      subs_filter http(s)?://(www.)?domain.com http$1://$http_host/blog r;
    ...
```

**Comment by ernanirst** [comment]
@juan131 thanks for the comment. I tried these annottations you posted and they don't seem to work.

I'm still looking into other nginx annotations.

**Comment by MahajanTushar** [comment]
Can you please give it a try using below annotation -

 **nginx.ingress.kubernetes.io/rewrite-target: /$1**

If you are using latest version of nginx then you can try like this -
**host - domain.com
http:
        paths:
          - backend:
              serviceName: replace here
              servicePort: replace here
            path: /blog/(.*)**

This will make your URL to be domain.com/blog and but this ultimately gets re-written to blog.com and what ever you place after domain.com/blog/path gets replaced by domain.com/path.

**Comment by ernanirst** [comment]
@mahajantushar thanks for the suggestion.

This actually helped, the JS and CSS don't seem to be broke anymore. However, instead of the wordpress index page, I see the wordpress 404 page. 

I see that we're using the bitnami wordpress for this chart, do you think it might be worth to try the official wordpress container? Not sure if it will work with the chart though...too many different parameters I guess.

**Comment by MahajanTushar** [comment]
I can't comment on that part, but you got 404 because the URI path you are looking for doesn't exist.

Try placing any random string at place of blog such that after re-write, your URL changes to

domain.com from domain.com/something/ , now after domain.com/something/ try using /blog.

Maybe this helps

**Comment by holmesb** [comment]
@ernanirst What version of Kubernetes are you on?  If >=1.14, ingress `apiVersion:` is `networking.k8s.io/v1beta1`, not `extensions/v1beta1`

**Comment by dcardozoo** [comment]
Hi @ernanirst 

You could setup your ingress as follows:
```
....
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - backend:
          serviceName: wp-wordpress
          servicePort: http
        path: /
  - host: your-domain.com
    http:
      paths:
      - backend:
          serviceName: wp-wordpress
          servicePort: http
        path: /blog
....
```

Like this you can access both css/js (using / ) and the site on /blog. Like this you will be also able to reach your wp site on **your-domain.com**

If you want the site to be only accessible on **your-domain.com/blog** you can use the annotation:
nginx.ingress.kubernetes.io/rewrite-target: /$1

and modify the `/` path to `/(wp.*)` 

You may also have to change the Site URL and the Wordpress Address accordingly, otherwise some worpress links will still be pointing to your-domain.com intead of your-domain.com/blog.

Hope it helps!

**Comment by RobertoDonPedro** [comment]
> Hi @ernanirst
> 
> You could setup your ingress as follows:
> 
> ```
> ....
> spec:
>   rules:
>   - host: your-domain.com
>     http:
>       paths:
>       - backend:
>           serviceName: wp-wordpress
>           servicePort: http
>         path: /
>   - host: your-domain.com
>     http:
>       paths:
>       - backend:
>           serviceName: wp-wordpress
>           servicePort: http
>         path: /blog
> ....
> ```
> 
> Like this you can access both css/js (using / ) and the site on /blog. Like this you will be also able to reach your wp site on **your-domain.com**
> 
> If you want the site to be only accessible on **your-domain.com/blog** you can use the annotation:
> nginx.ingress.kubernetes.io/rewrite-target: /$1
> 
> and modify the `/` path to `/(wp.*)`
> 
> You may also have to change the Site URL and the Wordpress Address accordingly, otherwise some worpress links will still be pointing to your-domain.com intead of your-domain.com/blog.
> 
> Hope it helps!

`nginx.ingress.kubernetes.io/rewrite-target: /$1` works for the wp frontend, but it does not work for the wp-admin backend. 
In my case `http://your-domain.com/blog/wp-admin` always redirects to `http://your-domain.com/wp-admin` .
How can I achieve to reach the wp-admin at `http://your-domain.com/blog/wp-admin` ? 
Here is my current nginx-ingress:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: rewrite
  namespace: mynamespace                  
spec:
  rules:
  - http:
      paths:
      - path: /blog(/|$)(.*)
        backend:
          serviceName: blog-wordpress-svc
          servicePort: 80 
```
