### ISSUE TITLE
http_check using configMap not working as *.yaml files not copied properly.

### ISSUE THREAD

**Issue by AviNitSri** [helm/charts#17213]
**Describe the bug**
(all the file and folder referred below are inside datadog-agent )
If I wanted to have an http_check on one of my services in kubernates, As described in the documentation [datadog_doc](https://docs.datadoghq.com/agent/kubernetes/helm/?tab=linuxsnap#enabling-integrations-with-helm) http_check.yaml will be created in /conf.d and then http_check.yaml will be copied to /etc/datadog-agent/conf.d, so finally we will have a file http_check.yaml  inside /etc/datadog-agent/conf.d. But  There should be a file conf.yaml inside /etc/datadog-agent/conf.d/http_check.d as shown in conf.yaml.example inside /etc/datadog-agent/conf.d/http_check.d.

**Version of Helm and Kubernetes**:
Helm
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

kubernetes
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-7f15cc", GitCommit:"7f15ccb4e58f112866f7ddcfebf563f199558488", GitTreeState:"clean", BuildDate:"2019-08-19T17:46:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
name: datadog
repository: "@stable"
appVersion: 6.10.1
version: v1.35.0

**What happened**:
here is my http_check.yaml as shown  [datadog_doc](https://docs.datadoghq.com/agent/kubernetes/helm/?tab=linuxsnap#enabling-integrations-with-helm) 
```
datadog:
    confd:
      http_check.yaml: |-
        ad_identifiers:
          - kafka-connect-server
        init_config:
        instances:
          - name: "call-ai-cdc-connector-http-check"
            url: "http://kafka-connect.prod.svc.cluster.local:8083/connectors/call-ai-cdc-connector/status"
            timeout: 1
            content_match: ".+RUNNING.+"
            allow_redirects: true
```
I installed the datadog helm chart, and I cannot see the http_check in http.can_connect in datadog_sit=> monitoring => check summery.

**What you expected to happen**:
I expected to see some checks under http.can_connect inside datadog_sit=> monitoring => check summery.

**How to reproduce it** (as minimally and precisely as possible):
add this code into values.yaml of datadog helm chart
```
datadog:
    confd:
      http_check.yaml: |-
        ad_identifiers:
          - kafka-connect-server
        init_config:
        instances:
          - name: "call-ai-cdc-connector-http-check"
            url: "<service endpoint>"
            timeout: 1
            content_match: ".+RUNNING.+"
            allow_redirects: true
```

**Anything else we need to know**:
