### ISSUE TITLE
[stable/kong] Allow hosts to be optional for kong ingress resources

### ISSUE THREAD

**Issue by mfreebairn-r7** [helm/charts#17216]
Currently, if an ingress is enabled and the hosts array is empty you will get this yaml output:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-kong-admin
  labels:
    app: kong
    chart: "kong-0.18.0"
    release: "release-name"
    heritage: "Tiller"
  annotations:
spec:
  rules:
```

As hosts is optional (from the kubernetes docs : `An optional host. In this example, no host is specified, so the rule applies to all inbound HTTP traffic through the IP address specified. If a host is provided (for example, foo.bar.com), the rules apply to that host.` source: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules) and I do not use hosts, instead using an external-dns annotation to manage creating a dns record, I would like the option to create an ingress object without `hosts` like the following output:
``` 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-kong-admin
  labels:
    app: kong
    chart: "kong-0.18.0"
    release: "release-name"
    heritage: "Tiller"
  annotations:
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: release-name-kong-admin
              servicePort: 8444
```

I have a solution for this an will open a PR shortly to link to
