### ISSUE TITLE
rabbitmq-ha problem in prometheus alerts

### ISSUE THREAD

**Issue by arazalip** [helm/charts#17229]
Seems like there is an issue in rabbitmq-ha chart. The problem is here: https://github.com/helm/charts/blob/3b20d69cb48c7098eb646fdc7fcbb3fc5c60bdac/stable/rabbitmq-ha/templates/alerts.yaml#L63
I guess the indent there is not correct. I assume the right value for the indent should be 8. The template will render to something like this when you add labels for an alert:
```      
      labels:
        installed_by: release-name
        severity: critical
          product: some-product
          team: some-team
```

that will obviously fail to deploy.
