### ISSUE TITLE
Stop using the alpha StorageClass annotation

### ISSUE THREAD

**Issue by luxas** [helm/charts#1728]
**Version of Helm and Kubernetes**:
v2.5.0 & v1.7.0

**Which chart**:
Many of them

**What happened**:
I saw that the annotations that were used for deploying StorageClass looked like this:

```yaml
  annotations:
  {{- if .Values.persistence.apache.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.apache.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
```

**What you expected to happen**:
The alpha annotation should NOT be used anymore; it has been deprecated for a long time, and its functionality was removed in v1.7.

I'm not exactly sure about the version skew policy here but I think that at maximum, three releases should be supported at any given time. At present, that would mean v1.5.x, v1.6.x and v1.7.x, which means we can remove the alpha annotation.

Further, we should detect if the storage.k8s.io/v1 API is available (v1.6+), and use the `.spec.storageClassName` field on the PVC instead of an annotation.

Finally, when v1.8.x is released, we can drop v1.5 support with the beta annotation and use v1 functionality everywhere :tada:

**How to reproduce it** (as minimally and precisely as possible):
Just deploy virtually any chart using PVCs
