### ISSUE TITLE
[stable/metrics-server] ClusterRoles aren't right and metrics-server pod crashes?

### ISSUE THREAD

**Issue by gswallow** [helm/charts#17326]
Hi,

I just reapplied some helm charts that that include the the metrics-server chart, and then metrics-server pods crashed because the system:metrics-server ClusterRole didn't have enough permisisons.  Maybe I did something wrong, but adding permissions fixed it?

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  labels:
    app: metrics-server
    chart: metrics-server-2.8.5
    heritage: Tiller
    release: metrics-server
  name: system:metrics-server
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/stats
  - namespaces
  - configmaps # <---- this is new
  verbs:
  - get
  - list
  - watch
- apiGroups: # <------ all of this is new
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
  - list
  - get
  - watch
```

Kubernetes version: v1.13.10-eks-5ac0f1
Helm version: 2.13; tiller run on localhost
Chart: metrics-server v2.8.5
