### ISSUE TITLE
[stable/grafana] envFromSecret not passing token

### ISSUE THREAD

**Issue by tomerleib** [helm/charts#17363]
**Describe the bug**
I'm trying to pass Google client secret to Grafana using envFromSecret.
The grafana.ini section is:
```grafana.ini```
```
   auth.google:
      enabled: true
      client_id: xxxxxx.apps.googleusercontent.com
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      allow_sign_up: true
    server:
      domain: grafana.mydomain.com
      root_url: https://grafana.mydomain.com/
```

And I'm referencing the key with:
```
envFromSecret: grafana-auth
```

The secret itself is defined as simple as:
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
type: Opaque
data:
  GF_AUTH_GOOGLE_CLIENT_SECRET: XyX2345XyX==
```

**Version of Helm and Kubernetes**:
helm - v2.14.3
kubernetes - 1.14.6-eks

**Which chart**:
stable/prometheus-operator

**What happened**:
When attempting to log in with Google Auth, the token failed to pass and I'm getting the following error:
`error="oauth2: cannot fetch token: 401 Unauthorized\nResponse`

**What you expected to happen**:
When I provide the client_secret in hardcoded way, the authentication works.
I expect to pass the token through a secret instead of hardcoding it into the values file.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
