### ISSUE TITLE
[stable/prometheus] server.sidecarContainers not working

### ISSUE THREAD

**Issue by brunodomenici** [helm/charts#17386]
**Describe the bug**
I'm trying to configure a sidecar container in my deployment and it's not working.

**Version of Helm and Kubernetes**:
Helm: v2.14.1
Kubernetes: v1.14.6-gke.1

**Which chart**:
stable/prometheus

**What happened**:
Sidecar container weren't created.

**What you expected to happen**:
A sidecar container created. 

**How to reproduce it** (as minimally and precisely as possible):
My values.yaml:
```
server.sidecarContainers:
    containers:
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.5.2
        imagePullPolicy: IfNotPresent
        name: sidecar
```
I've tried also:
```
server.sidecarContainers:
    image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.5.2
    imagePullPolicy: IfNotPresent
    name: sidecar
```
But no luck.

Any ideas?

Thanks a lot!

**Comment by nervo** [comment]
```
server:

  ...

  sidecarContainers:
    - name: sidecar
      image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.5.2
      imagePullPolicy: IfNotPresent
```

'should do the trick :)
