### ISSUE TITLE
[stable/graylog] elasticsearch and tls

### ISSUE THREAD

**Issue by cubed-it** [helm/charts#17399]
Hey there,

I'm pretty new to kubernetes helm and so on. So please bear with me ;)

I would like to setup Graylog via Helm. Graylog and mongo is okay, but I have some issues connection to elasticsearch.

I have elastic running via https://github.com/elastic/cloud-on-k8s and this way it creates self signed certificates.
But I did not find a way to tell graylog to accept my selfsigned certificate. Can maybe anyone give me a hint what I could do here? Is there any way to inject it into the container? Or to disable verification?

```
ERROR   [Cluster] - Couldn't read cluster health for indices [graylog_*] (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) - {}
```
```
{"type": "server", "timestamp": "2019-09-24T13:01:07,276+0000", "level": "WARN", "component": "o.e.x.s.t.n.SecurityNetty4HttpServerTransport", "cluster.name": "elasticsink", "node.name": "elasticsink-es-kg2qzn9cvg", "cluster.uuid": "ejCgJfcdRxO-2iuFm-XyOA", "node.id": "1kL35DrPTn6-sqXr9dUELQ",  "message": "http client did not trust this server's certificate, closing connection Netty4HttpChannel{localAddress=0.0.0.0/0.0.0.0:9200, remoteAddress=/10.244.0.184:59704}"  }
```

Thanks for any help!

**Comment by BeryJu** [comment]
Hi, I'm deploying Graylog the same way with Elastic's Operator. To get this setup to work, I had to write a script like this:
```bash
#!/bin/bash

DOCKER_IMAGE="graylog/graylog:3.2"

echo "Step 1: Start a local container to copy the original cacerts file"
ID=$(docker create $DOCKER_IMAGE)
docker cp $ID:/usr/local/openjdk-8/lib/security/cacerts - | tar xvf - > cacerts
chmod 755 cacerts
docker rm -v $ID

echo "Step 2: Extract Elasticsearch HTTPS Certificate"
kubectl get secret -n elasticsearch graylog-es-cluster-es-http-certs-public -o go-template='{{index .data "tls.crt" | base64decode }}' > es.pem

echo "Step 3: Import Elasticsearch HTTPS Certificate into Keystore"
docker run -it --rm -v $(pwd):$(pwd) openjdk keytool -importcert -noprompt -keystore $(pwd)/cacerts -storepass changeit -alias elasticsearch-cert -file $(pwd)/es.pem

echo "Step 4: Create K8s ConfigMap from keystore file"
kubectl create configmap --namespace graylog graylog-keystore --from-file=cacerts

echo "Step 5: Cleanup"
rm -f es.pem cacerts
```

Which extracts the Elastic TLS Certificate, merges it into a Java Keystore and saves that as a ConfigMap. Afterwards I apply this Patch tot the Graylog StatefulSet:

```yaml
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: graylog-server
        volumeMounts:
        - mountPath: /usr/local/openjdk-8/lib/security/cacerts
          subPath: cacerts
          name: graylog-keystore
      volumes:
      - configMap:
          name: graylog-keystore
        name: graylog-keystore
```

Which mounts the modified Keystore in the Graylog container.
