### ISSUE TITLE
[stable/nextcloud] helm delete deletes half the PVCs

### ISSUE THREAD

**Issue by mrtndwrd** [helm/charts#17404]
When you install Nextcloud with persistence and Mariadb enabled, two PersistentVolumeClaims will be made: One for MariaDB, and one for nextcloud. 

When you then run `helm delete` or `helm delete --purge` the Nextcloud PVC will be deleted, but the MariaDB pvc will stay. 

If you re-install nextcloud with the same name, this will lead to problems, because your MariaDB already has an admin user, but the Nextcloud will always try to re-make that user.

To solve this issue, either make sure that the MariaDB *and* the Nextcloud PVC get deleted when you run `helm delete`, or that both PVCs stay. 

Another solution I tried, is adding this to the persistence values:

```yaml
    annotations:
      "helm.sh/resource-policy": keep
```

But then re-installing nextcloud fails because the helm chart tries to recreate the persistent volume that already exists.

To be complete, these are the relevant values from my `values.yaml` (the `requiredEnv` is a helmfile thing):

```yaml
  persistence:
    enabled: true
    size: 2Gi

  # Explicitly disable use of internal database
  internalDatabase:
    enabled: false

  # Enable and configure MariaDB chart
  mariadb:
    db:
      password: "{{ requiredEnv "NEXTCLOUD_MARIADB_PASSWORD" }}"
    enabled: true
    master:
      persistence:
        ## Enable PostgreSQL persistence using Persistent Volume Claims.
        enabled: true
        size: 512Mi
    replication:
      enabled: false
    rootUser:
      password: "{{ requiredEnv "NEXTCLOUD_MARIADB_ROOT_PASSWORD" }}"
  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120
```
