### ISSUE TITLE
[stable/jenkins] Redeploy Jenkins master on change of (definable) K8S ressource

### ISSUE THREAD

**Issue by uwehdaub** [helm/charts#17427]
**Is your feature request related to a problem? Please describe.**
We've created a customized helm chart based on this one to be used inside our company by different dev teams. Part of the customization is to have a list of team members inside the _values.yaml_ file. From this list we create a K8S configmap, which is evaluated via a _init-script_ at Jenkins start to set permissions inside Jenkins.

We now want to restart Jenkins, when the content of this configmap changes.

The helm chart already solves this problem for the _config.yaml_ (from `jenkins-master-deployment.yaml`):
```
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if .Values.master.podAnnotations }}
{{ toYaml .Values.master.podAnnotations | indent 8 }}
        {{- end }}
```
We currently only can add annotations _values_, but in our use case, we need to add an annotation template like:
```
jenkins:
  master:
    podAnnotations:
      'checksum/teammembers': '{{ include (print $.Template.BasePath "/teammembers.yaml") . | sha256sum }}'
```
**Describe the solution you'd like**
One possibility is to have an additional entry in _values.yaml_ like:
```
jenkins:
  master:
    podAnnotationsAsTemplate:
      'checksum/teammembers': '{{ include (print $.Template.BasePath "/teammembers.yaml") . | sha256sum }}'
```
which will evaluate the value with the _tpl_ template function as is already done here:
```
{{- if .Values.master.customInitContainers }}
{{ tpl (toYaml .Values.master.customInitContainers) . | indent 8 }}
{{- end }}
```
**Describe alternatives you've considered**
Another possibility is to list only the names of the yaml files, which contains the K8S ressources which should trigger a deployment of Jenkins.
This possibility is less generic, but more robust.
