### ISSUE TITLE
[stable/redis] Using redis as a subchart does not correctly apply the disableCommands

### ISSUE THREAD

**Issue by arrkaye** [helm/charts#17435]
Hi,
I'm using redis as a subchart to my own chart.
If I install the chart directly, it works just fine, but when I use as a subchart with the below config section, the FLUSHDB/ALL commands are still disabled.

```
redis:
  cluster:
    enabled: false
    slaveCount: 1
  usePassword: false
  exporter:
    enabled: true
  master:
    disableCommands: null
  slave:
    disableCommands: null
  configmap:
    notify-keyspace-events AKE
  networkPolicy:
    enabled: false
  sysctlImage:
    enabled: true
    command:
      - /bin/sh
      - -c
      - |-
        install_packages systemd
        sysctl -w net.core.somaxconn=10000
        echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
    mountHostSys: true
```

**Comment by juan131** [comment]
Hi @arrkaye 

Could you try with the **values.yaml** below?

```yaml
redis:
  ...
  master:
    disableCommands: []
  slave:
    disableCommands: []
  ...
```
