### ISSUE TITLE
[stable/redis] Slave Unable to Authenticate With Master When "existingSecret" is set

### ISSUE THREAD

**Issue by kylelee24** [helm/charts#17473]
**Describe the bug**

When deploying the `stable/redis` helm chart, the slave is unable to authenticate with master when `existingSecret` is set. The master node is running and I am able connect to the instance when port forwarding and also ran `ping` for good measure (returned `PONG`).

This is how I structured my secret:

```yaml
apiVersion: v1
data:
  redis-password: "ZmFrZXBhc3MK"
kind: Secret
metadata:
  labels:
    app: redis
  name: redis-secret
  namespace: dev
type: Opaque
```

I am fairly confident that it is correct as when I don't use `existingSecret` and set `password`, it creates a similar secret and the slave conencts to master successfully. I have also tried to specify the `existingSecretPasswordKey` to the default key of `redis-password` as well as `password` with no luck.

I even took a step further and compared the slave's pod yaml between the working setup with `password` and the not-working one with `existingSecret` and didn't really see any notable differences.

I can see that there was a commit 3 days ago with the description "[stable/redis] Add existingSecretPasswordKey setting for users (#16360)". Unsure if it is related. 

**Version of Helm and Kubernetes**:

Helm - 2.14.3
Kubernetes - 1.14.6 (EKS)

```bash
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/redis

**What happened**:

Slave unable to connect to master work when using `existingSecret`.

Error: `1:S 26 Sep 2019 20:17:28.977 # Unable to AUTH to MASTER: -ERR invalid pass`

**What you expected to happen**:

Slave connects to master

**How to reproduce it** (as minimally and precisely as possible):

- Create secret using yaml similar to below:

```yaml
apiVersion: v1
data:
  redis-password: "ZmFrZXBhc3MK"
kind: Secret
metadata:
  labels:
    app: redis
  name: redis-secret
  namespace: dev
type: Opaque
```

- Update `values*.yaml` file and set `existingSecret: redis-secret`.
- Deploy via helm.
- Review slave logs

**Anything else we need to know**:

N/A

**Comment by leeman24** [comment]
The above configuration does work when using `usePasswordFile: true` though which is a decent workaround for me at this time.

**Comment by alemorcuq** [comment]
Hi, @leeman24.

I believe the issue here is your encoded password. According to the [Kubernetes documentation](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#convert-your-secret-data-to-a-base-64-representation), the way to get the `base64` representation of your secret is to do:

```console
$ echo -n 'fakepass' | base64
ZmFrZXBhc3M=
```

Note that my `base64` string is different than yours `ZmFrZXBhc3MK`. I've created a secret using the same skeleton as yours, but with the "correct" `base64` representation and it is working for me:

```yaml
apiVersion: v1
data:
  redis-password: ZmFrZXBhc3M=
kind: Secret
metadata:
  labels:
    app: redis
  name: redis-secret
  namespace: dev
type: Opaque
```

I guess it is possible that the newline character that `echo` adds by default at the end is messing with something (thus the `-n` flag to avoid printing it). Give it a try a let me know how it goes.

Regards,
Alejandro
