### ISSUE TITLE
[stable/fluent-bit] indentation issue on extraEntries values

### ISSUE THREAD

**Issue by mlf4aiur** [helm/charts#17499]
**Describe the bug**

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Which chart**:

`stable/fluent-bit`

**What happened**:

fluent-bit pod keep crashing when set extraEntries values.

error logs:

```
Fluent Bit v1.2.2
Copyright (C) Treasure Data

[2019/09/27 21:36:00] [  Error] File fluent-bit-output.conf
[2019/09/27 21:36:00] [  Error] Error in line 19: Each key must have a value
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

reproduce  it with values.yaml file:
```
backend:
  type: es
  es:
    type: flb_type
    index: "foo"
    host: "foo.example.com"
    port: 443
    replace_dots: "On"
    time_key: "@timestamp"
    tls: "on"
    tls_verify: "on"
    logstash_prefix: "foo"

extraEntries:
  output: |-
    [OUTPUT]
        Name          forward
        Match         *
        Host          bar.example.com
        Port          514
        Retry_Limit   False
```

```
helm fetch stable/fluent-bit --untar --version 2.7.0
helm template -f values.yaml fluent-bit
```

fluent-bit-output.conf as following:
```
  fluent-bit-output.conf: |-

    [OUTPUT]
        Name  es
        Match *
        Host  foo.example.com
        Port  443
        Logstash_Format On
        Retry_Limit False
        Type  flb_type
        Time_Key @timestamp
        Replace_Dots On
        Logstash_Prefix foo


        tls on
        tls.verify on
        tls.debug 1

        [OUTPUT]
            Name          forward
            Match         *
            Host          bar.example.com
            Port          514
            Retry_Limit   False
```

**Anything else we need to know**:

The indentation of extraEntries seems to be wrong, it should be 4 for extraEntries values.
