### ISSUE TITLE
[stable/consul] readme does not match values.yaml

### ISSUE THREAD

**Issue by mozai** [helm/charts#17493]
**README.md does not match values.yaml**
values.yaml as of Aug 18th offers
```
    Gossip:
      Encrypt: true
      Create: true
    GossipKey: key
```

But README.md of Aug 18th describes

Parameter | Description | Default
-- | -- | --
EncryptGossip | Whether or not gossip is encrypted | true
GossipKey | Gossip-key to use by all members | nil

**Version of Helm and Kubernetes**:
irrelevant

**Which chart**:
stable/consul

**What happened**:
README.md does not match values.yaml

**What you expected to happen**:
README.md matches values.yaml

**How to reproduce it** (as minimally and precisely as possible):
Read README.md, then read values.yaml
