### ISSUE TITLE
[stable/graylog] No master node when graylog restarts and there is only one replica available

### ISSUE THREAD

**Issue by invidian** [helm/charts#17550]
**Describe the bug**

If there is only one replica of Graylog pod and this one gets restarted (so pod object is not being removed), then the master node becomes a coordinator and there is no master in the cluster. This is because master pod already exists.

Causing code: https://github.com/helm/charts/blob/master/stable/graylog/templates/configmap.yaml#L143.

**Which chart**:
stable/graylog

**What happened**:

When internal restart happens, cluster with one replica ends up without master.

**What you expected to happen**:

With single replica, this replica should always be registered as master.

**How to reproduce it** (as minimally and precisely as possible):

Deploy with following values:
```
graylog:
  image:
    repository: graylog/graylog:3.1.2-1
  replicas: 1
  input:
    udp:
      service:
        type: ClusterIP
      ports:
        - name: syslog
          port: 5410
  mongodb:
    uri: mongodb://mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.graylog.svc.cluster.local:27017/graylog?replicaSet=rs0
  elasticsearch:
    hosts: http://elasticsearch-client.graylog.svc.cluster.local:9200
  ingress:
    enabled: true
    hosts:
    - graylog.local
tags:
  install-mongodb: false
  install-elasticsearch: false
```

2. I'm not sure how to trigger a restart.

**Anything else we need to know**:

I think that may also happen when running with multiple replicas and master node gets restarted.
