### ISSUE TITLE
[stable/chart/drone] could not configure bitbucket server as a source control.

### ISSUE THREAD

**Issue by raviranjithkumar** [helm/charts#17570]
**Describe the bug**
To configure bitbucket server as source control, I dont see the required values defined in the values.yaml file and there is no entry in template for bitbucket server.

**Version of Helm and Kubernetes**:
Helm version: 2.14.2 K8's: 1.15

**Which chart**:
drone

**What happened**:
pods are not getting created since some values definition is missing

**What you expected to happen**:
It should create the drone server pod up and running

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by hnykda** [comment]
I think this is more generic - I am unable to setup gitlab as well nor haven't found any article or mention someone successfully doing that. I can do it with plain docker, but not with helm on k8s. The documentation and comments are quite confusing, I wasn't able to do it by myself.

I was able to make it work for github though. So I don't think I am that incompetent. But for github, there is at least example.

Could I maybe kindly ask @raunyoliveira-hotmart as the one of the last editors of values.yaml?

**Comment by raunyoliveira-hotmart** [comment]
@hnykda sorry for the late reply, I'm going to try both: bitbucket and gitlab and let you guys know if it works.

**Comment by Wilson13** [comment]
I encountered this issue too, the difference is I'm trying to set bitbucketCloud as the source control.

**Describe the bug**
A clear and concise description of what the bug is.

**Version of Helm and Kubernetes**:
Helm: v3.0.0
K8s: 1.16.2-do.0

**Which chart**:
stable/drone

**What happened**:
OAuth doesn't work.

**What you expected to happen**:
Bitbucket OAuth Confirm access to your account.

**How to reproduce it** (as minimally and precisely as possible):
Deploy stable/drone helm chart with following value.yml

```
sourceControl: 
  provider: bitbucketCloud
  github:
    clientID: xxxx
    clientSecretKey: clientSecret
    clientSecretValue: xxxx
  bitbucketCloud:
    clientID: xxxxx
    clientSecretKey: clientSecret
    clientSecretValue: xxxx
  server:
    host: xxxx
    protocol: http
```

**Anything else we need to know**:
If I change the source control to github, it works.

I have deployed another Drone Server using docker instead of helm chart, BitBucket OAuth works there.
