### ISSUE TITLE
[stable/gangway] trusted ca, existing configmap

### ISSUE THREAD

**Issue by figaw** [helm/charts#17578]
**Is your feature request related to a problem? Please describe.**
Currently we have to supply the trusted ca file when we're installing Gangway. It's making the assumption that the trusted ca file is available to the individual or machine installing the tool.

**Describe the solution you'd like**
Ability to provide the name of an already existing configmap, containing the `rootca.crt`

**Describe alternatives you've considered**
Templating `extraVolumes` and `extraVolumeMounts` in the deployment, but it seems like an overkill for this specific use.

**Additional context**

In the [oauth2-proxy](https://github.com/helm/charts/tree/master/stable/oauth2-proxy) we've solved it with the `extraVolumes` and `extraVolumeMounts`, a similar solution for Gangway would look like:

[`values.yaml`](https://github.com/helm/charts/blob/master/stable/oauth2-proxy/values.yaml)
```
gangway:
  cluster_ca_path: /path/to/rootca.crt

extraVolumes:
  - name: rootca-cert
    configmap:
      name: my-rootca-configmap

extraVolumeMounts:
  - mountPath: /path/to/
    name: rootca-cert
```

[`deployment.yaml`](https://github.com/helm/charts/blob/master/stable/oauth2-proxy/templates/deployment.yaml)
```
        volumeMounts:
...
{{- if ne (len .Values.extraVolumeMounts) 0 }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
...
{{- if ne (len .Values.extraVolumes) 0 }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
```
And documentation about creating a configmap, containing the file referenced in the `cluster_ca_path`. 

I don't know if there's a usecase for mounting more files into the Gangway pod, that would justify this solution?
