### ISSUE TITLE
[charts/incubator/haproxy-ingress/] Add possibility to mount secret to controller

### ISSUE THREAD

**Issue by admgolovin** [helm/charts#17650]
**Is your feature request related to a problem? Please describe.**

My task: Im using jenkins job that installing HAProxy charts to clusters according to environment. I needed to add  additional configuration to the HAProxy: ACL which checks that http request has the arg - "api Key" and it is equal certain key. If it is not, you will get 403 error. 

The problem: There is a very convenient way to add extra config through Values.yaml file:   
```
controller:
  config:
    config-frontend: |
      acl apiKey url_param(apiKey) "test-key"
      http-request deny if !apiKey
```
But if I do like this, my api-keys will be available in plain text in GitHub. 

**Describe the solution you'd like**

To generate a secret with api-keys and then mount it to the controller pod.
Secret could be created with `--from-env-file` option or just mounted, and then included as additional config by `haproxy -f` flag.

**Describe alternatives you've considered**

I have considered three ways:

1st To create a secret from api-keys before chart installation. Then to use secret data as environment variables for controller pod and refer to these variables in the in HAProxy config

2nd To create a Configmap: 
```
apiVersion: v1
data:
  config-frontend: "acl apiKey url_param(apiKey) 'test-key'\nhttp-request deny if !apiKey"
  healthz-port: "10253"
  stats-port: "1936"
kind: ConfigMap
metadata:
  labels:
    app: haproxy-ingress
  name: haproxy-ingress-controller
  namespace: haproxy
```
3d As I use Jenkins job to configure chart, I could pass additional config as git secret, reveal it in chart installation stage. Then include it to the Values.yaml file in controller.config section.

### Conclusion 
Second and third options has security disadvantages:

* Configmap content could be watched in cluster environment by anyone who can interact with Kubernetes cluster as Configmap store data in plain text.
* In this option, anyone who have access to the cluster, could see my API keys in the output of `helm get <chart-name>` command.

First option is more reliable from security point as sensitive info isn't store in cluster as plain text, and actually that is the way that I have done to solve this issue. But its not 100% secure as well, because I can see those Keys in the 
execution process output of Jenkins job and it also not  so convenient as just mount secret that was created with --from-env-file flag. 

That would be awesome if you will add this option to the chart.
