### ISSUE TITLE
[stable/sonarqube] pod annotation are not working. Please fix it

### ISSUE THREAD

**Issue by venomwaqar** [helm/charts#17711]
**Describe the bug**
Pod annotations are not getting set, seems like indention are little off [here](https://github.com/helm/charts/blob/f6fa8f77fecc52dcddaed28d961500dd0800a303/stable/sonarqube/templates/deployment.yaml#L27) or [here](https://github.com/helm/charts/blob/f6fa8f77fecc52dcddaed28d961500dd0800a303/stable/sonarqube/templates/deployment.yaml#L24).
Please fix it or let me know if there is a workaround

**Version of Helm and Kubernetes**:
Kubernetes: 1.13.6
Helm: 2.13.0

**Which chart**:
stable/sonarqube

```
affinity: {}
annotations:
  traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
customCerts:
  enabled: false
  secretName: my-cacerts
database:
  type: postgresql
deploymentStrategy: {}
extraEnv: {}
hostAliases: []
image:
  repository: sonarqube
  tag: 7.9.1-community
ingress:
  annotations: {}
  enabled: false
  hosts:
  - name: sonar.organization.com
    path: /
  tls: []
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  sonarWebContext: /
mysql:
  enabled: false
  mysqlDatabase: sonarqube_db
  mysqlPassword: StarGate22
  mysqlServer: ****
  mysqlUser: postgres
  service:
    port: '5432'
nodeSelector: {}
persistence:
  accessMode: ReadWriteMany
  annotations: {}
  enabled: true
  size: 1Gi
  storageClass: nfs-client
plugins:
  install:
  - https://github.com/SonarSource/SonarJS/releases/download/5.2.1.7778/sonar-javascript-plugin-5.2.1.7778.jar
  resources: {}
podLabels: {}
postgresql:
  enabled: false
  postgresDatabase: sonarqube_db
  postgresPassword: StarGate22
  postgresServer: ****
  postgresUser: postgres
  service:
    port: '5432'
readinessProbe:
  failureThreshold: 6
  initialDelaySeconds: 60
  periodSeconds: 30
  sonarWebContext: /
replicaCount: '1'
resources:
  limits:
    cpu: 1500m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi
securityContext:
  fsGroup: 999
  runAsUser: 999
service:
  annotations: {}
  externalPort: '9000'
  internalPort: '9000'
  labels: null
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  name: sonarqube
  type: ClusterIP
sonarProperties:
  sonar.forceAuthentication: true
tolerations: []
```
