### ISSUE TITLE
[stable/airflow] Help needed to debug the git clone at pod init

### ISSUE THREAD

**Issue by mdespriee** [helm/charts#17751]
**Describe the bug**
I can't make the git clone at init work (as described [here](https://github.com/helm/charts/tree/master/stable/airflow#use-init-container)).
All services start fine, but nothing is created into /usr/local/airflow/dags.
I'm quite new to k8s, and I don't find logs or anything to help me track down what happens. Help appreciated !

**Version of Helm and Kubernetes**:
via Rancher. Helm: v2.10.0-rancher11. 

**Which chart**:
airflow

**Conf**
```
airflow:
   [...]
  dags:
    git:
      url: git@github.com:xxxxx/airflow-dags.git
      ref: master
      secret: airflow-deploy-key
    initContainer:
      enabled: true
```
