### ISSUE TITLE
[stable/kong] inconsistent property name for configuring smtp password secret

### ISSUE THREAD

**Issue by rafaelgom3s** [helm/charts#17784]
**Describe the bug**

The expected property to configure smtp password secret, which is referenced [here](https://github.com/helm/charts/blob/master/stable/kong/templates/deployment.yaml#L139) seems inconsistent with the value declared in [values.yaml](https://github.com/helm/charts/blob/master/stable/kong/values.yaml#L252)

**Version of Helm and Kubernetes**:
Helm version:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
Kubernetes version: `v1.13.10-eks-5ac0f1`

**Which chart**:

`stable/kong` 0.19.1

**What happened**:
When running the following command:
> helm upgrade --install kong -f values.yml stable/kong

with the `values.yml` content in `enterprise.smtp` section:

```yaml
enterprise:
  auth:
      smtp_username: xxxxxxxxxxxx
      smtp_password_secret: kong-smtp-conf

```

we get the following error:

```
Error: release kong failed: Deployment.apps "kong-kong" is invalid: spec.template.spec.containers[0].env[18].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**What you expected to happen**:
Deployment done without errors.

**How to reproduce it** (as minimally and precisely as possible):
As described in the **What happened* * section.

**Anything else we need to know**:

Changing the `values.yml` content in `enterprise.smtp` section fixes the problem:

```yaml
enterprise:
  auth:
      smtp_username: xxxxxxxxxxxx
      smtp_password: kong-smtp-conf
```
