### ISSUE TITLE
[stable/jenkins] Jenkins JKS native ssl support

### ISSUE THREAD

**Issue by ehsandanesh** [helm/charts#17790]
**Is your feature request related to a problem? Please describe.**
Currently, there is no Jenkins JKS native SSL support in Jenkins helm chart. It would be better to be able to configure SSL directly on Jenkins beside the ingress and load balancer.

**Describe the solution you'd like**
Having some sections in value file like:
```yaml
master:
  httpsKeyStore:
       enable: true/false
       httpPort: 
       fileAddress: ""
       password: ""
       jenkinsKeyStore:
```
