### ISSUE TITLE
How is change ZooKeeprer replicas count?

### ISSUE THREAD

**Issue by ilya-shaydullin** [helm/charts#17824]
Hello! 

I changed Kafka broker replicas to 1 

```yaml
persistence:
  storageClass: "local-storage"
replicas: 1
```

but ZooKeeper was started to 3 replicas

![image](https://user-images.githubusercontent.com/2123117/66474080-c9162880-eaba-11e9-978c-050f742b9fe0.png)
