### ISSUE TITLE
[incubator/kafka] helm deploy is not creating partitions neither replications using values.yaml

### ISSUE THREAD

**Issue by Lufedi** [helm/charts#17842]
**Describe the bug**
I am using the following values.yaml file when running helm to create my kafka cluster, the topics are create correctly but they are not created with the replicationFactor neither the number of partitions specified in the values.yaml file

```
replicas: 3
topics: 
  - name: telemetry
    partitions: 3
    replicationFactor: 2
    reassignPartitions: true
    config: "retention.ms=14400000"
  - name: groups
    partitions: 3
    replicationFactor: 2
    reassignPartitions: true
    config: "retention.ms=14400000"
  - name: metrics
    partitions: 3
    replicationFactor: 2
    reassignPartitions: true
    config: "retention.ms=14400000"

```
helm version
Client: v2.14.0
Server: v2.14.0

**Which chart**:
Kafka

**What you expected to happen**:
Create the partitions and replicas distributed across the 3 brokers

Is something missing in my values.yaml file?

Example of how the topic is initialized with 1 partition and no replicas
![initializedTopicWrngWay](https://user-images.githubusercontent.com/2343465/66512885-82670500-ea9f-11e9-9e5b-082e72879131.PNG)
