### ISSUE TITLE
stable/nginx-ingress: In AKS, allow to assign static IP address from different resource group #14668

### ISSUE THREAD

**Issue by ankurkapoor** [helm/charts#17899]
Reporting the same issue [14668 ](https://github.com/helm/charts/issues/14668)again as i am still getting even after applying the parameter:

`helm install stable/nginx-ingress --namespace $namespaceName --set controller.replicaCount=2 `
--set controller.nodeSelector."beta\.kubernetes\.io/os"=linux `
--set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux `
--set controller.service.loadBalancerIP="$staticIngressIP" `
--set controller.service.annotations.service.beta.kubernetes.io/azure-load-balancer-resource-group="$staticIPRG"`

Error log below:
Error creating load balancer (will retry): failed to ensure load balancer for service development/whopping-buffoon-nginx-ingress-controller: user supplied IP Address XX.XXX.XX.XXX was not found in resource group XXXX_RESOURCE_GROUP

**Comment by florianrusch** [comment]
@ankurkapoor I've solved this issue for our setup:
You have to assign the role `Network Contributor`, with the scope of your resource group `$staticIPRG` to the k8s service principal.

**Comment by eskaufel** [comment]
@florianrusch I do not think this is due to permissions. I have the same problem with the correct role assigned.

**Comment by eskaufel** [comment]
I solved this by moving the values out in a separate file and using -f

`helm install stable/nginx-ingress --generate-name --namespace ingress-basic --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux -f variables.yaml`

variables.yaml
```
controller:
  replicaCount: NODE_COUNT
  nodeSelectory: 
    beta.kubernetes.io/os: linux
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: RESOURCE_GRP_NAME
    loadBalancerIP: IP_ADDR
```
