### ISSUE TITLE
incubator/jaeger - pod/jaeger-hotrod-66b66d68bf-72zjk is crashing off

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#17919]
Hi, 

When I am enabling the sample application hotrod in the incubator/jaeger then that pod is crashing and it is showing me the below error. Can anybody please help me in resolving this. 

pod/jaeger-elasticsearch-data-1                    1/1     Running            0          8m1s
pod/jaeger-elasticsearch-master-0                  1/1     Running            0          8m57s
pod/jaeger-elasticsearch-master-1                  1/1     Running            0          7m28s
pod/jaeger-elasticsearch-master-2                  1/1     Running            0          6m38s
pod/jaeger-hotrod-66b66d68bf-zxjl8                 0/1     CrashLoopBackOff   6          8m57s
pod/jaeger-query-596f47bb9f-6xnqg                  1/1     Running            5          8m57s

2019-10-12T05:35:47.469Z        INFO    cmd/all.go:28   Starting all services
2019-10-12T05:35:47.469Z        FATAL   log/logger.go:48        cannot parse Jaeger env vars    {"service": "frontend", "error": "cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://10.0.68.65:5775: strconv.ParseInt: parsing \"udp://10.0.68.65:5775\": invalid syntax", "errorVerbose": "strconv.ParseInt: parsing \"udp://10.0.68.65:5775\": invalid syntax\ncannot parse env var JAEGER_AGENT_PORT=udp://10.0.68.65:5775\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/config.reporterConfigFromEnv\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/config/config_env.go:189\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/config.FromEnv\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/config/config_env.go:86\ngithub.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing.Init\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing/init.go:33\ngithub.com/jaegertracing/jaeger/examples/hotrod/cmd.glob..func4\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/frontend.go:46\ngithub.com/jaegertracing/jaeger/examples/hotrod/cmd.glob..func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/all.go:32\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:826\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:914\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:864\ngithub.com/jaegertracing/jaeger/examples/hotrod/cmd.Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/root.go:58\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/main.go:11\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337\ncannot obtain reporter config from env\ngithub.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/config.FromEnv\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-client-go/config/config_env.go:89\ngithub.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing.Init\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing/init.go:33\ngithub.com/jaegertracing/jaeger/examples/hotrod/cmd.glob..func4\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/frontend.go:46\ngithub.com/jaegertracing/jaeger/examples/hotrod/cmd.glob..func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/all.go:32\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:826\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:914\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:864\ngithub.com/jaegertracing/jaeger/examples/hotrod/cmd.Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/root.go:58\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/main.go:11\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337"}
github.com/jaegertracing/jaeger/examples/hotrod/pkg/log.logger.Fatal
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/log/logger.go:48
github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing.Init
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/pkg/tracing/init.go:35
github.com/jaegertracing/jaeger/examples/hotrod/cmd.glob..func4
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/frontend.go:46
github.com/jaegertracing/jaeger/examples/hotrod/cmd.glob..func1
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/all.go:32
github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:826
github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:914
github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:864
github.com/jaegertracing/jaeger/examples/hotrod/cmd.Execute
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/cmd/root.go:58
main.main
        /home/travis/gopath/src/github.com/jaegertracing/jaeger/examples/hotrod/main.go:11
runtime.main
        /home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200

@dvonthenen @mikelorant @naseemkullah @pavelnikolov  Can you please help. In case any information is required please let me know. I am trying to run with the below command:

helm install incubator/jaeger  --name=jaeger --namespace=trace  --set provisionDataStore.cassandra=false  --set provisionDataStore.elasticsearch=true --set storage.type=elasticsearch --set hotrod.enabled=true

**Comment by pavelnikolov** [comment]
If you check carefully you will see that this value comes from: `.Values.hotrod.tracing.port` (you can override it). See here for details: https://github.com/helm/charts/blob/80f5d310e20868fa0900e64664cbffc625ab404e/incubator/jaeger/templates/hotrod-deploy.yaml#L36
I tried running the command that you provided (I ran the `template` instead of the `install` subcommand) and I get the expected result for hot-rod:
```
---
# Source: jaeger/templates/hotrod-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-hotrod
  labels:
    app.kubernetes.io/name: jaeger
    jaeger-infra: hotrod-deployment
    helm.sh/chart: jaeger-0.13.1
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: hotrod
      app.kubernetes.io/instance: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: hotrod
        app.kubernetes.io/instance: jaeger
    spec:
      serviceAccountName: jaeger-hotrod
      containers:
        - name: jaeger-hotrod
          image: jaegertracing/example-hotrod:1.13.1
          imagePullPolicy: Always
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
            - name: JAEGER_AGENT_PORT
              value: "6831"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
```

I am not able to reproduce this error...
