### ISSUE TITLE
[stable/prometheus-operator] grafana login specified in config not valid

### ISSUE THREAD

**Issue by tsturzl** [helm/charts#17915]
**Describe the bug**

I've set a password in the values file, using the password specified along with the `admin` user does not work as expected. I've verified the secret used by the deployment is populated with the correct password.

**Version of Helm and Kubernetes**:

Helm: 2.14.3 (client & server)
K8s: 1.11.9

**Which chart**:

stable/prometheus-operator

**What happened**:

Grafana login is telling me "Invalid Username or Password".

**What you expected to happen**:

Grafana login to succeed with the password I provided in my values file.

**How to reproduce it** (as minimally and precisely as possible):

Install prometheus operator, specify a customer adminPassword for grafana.

**Anything else we need to know**:

This is the values file I'm using:

```
coreDns:
  enabled: false

kubeDns:
  enabled: true

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 100m
        memory: 250Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

grafana:
  adminPassword: "REDACTED"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - grafana.example.com
    tls:
      - secretName: example-k8s-dns
        hosts:
          - "*.example.com"
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 10Gi
```
