### ISSUE TITLE
[stable/rabbitmq] RabbitMQ kubernetes operator - Is it interesting? If so, where should it be added?

### ISSUE THREAD

**Issue by arielb135** [helm/charts#17981]
Hi, i want to propose a rabbitMQ operator - but i'm not really sure where is the appropriate place (or if it's needed) to put it.
Maybe it should be proposed in the rabbitMQ repository?

**Is your feature request related to a problem? Please describe.**
Currently when we want to deploy a microservice that uses rabbitMQ - we have to either create an initContainer that uses the rabbitAPI to create those users / policies / virtual hosts / etc... or do it in definitions.json - which is hard to maintain.

Ideally, it makes sense like Prometheus operator to create a custom object per microservice deployment that will create the users per specific deployment.

**Describe the solution you'd like**
I've already implemented it (it will be in our production soon) - i would like to propose a Kuberentes Operator that handles a custom resource requests, and create / deletes / updates those rabbit resources in the deployment.
This means, same as PrometheusRule, we will create **RabbitConfig** with all the details, and upon deployment - the operator will create the rabbit resources for us.

The project is written in **python**, based on MetaController (https://metacontroller.app/) and pyrabbit2 (https://github.com/deslum/pyrabbit2)

Example of a RabbitConfig:
```
apiVersion: example.com/v1
kind: RabbitConfig
metadata:
  name: myrabbitconfig
  namespace: myNS
  annotations:
    rabbit-controller-class: "rabbitmq"
spec:
  vhost:
    name: /some_vhost
    create: true
  users: 
    - name: my_user
      passwordSecretRef:
        name: MySecret
        key: PASS
      tags:
      -  monitoring
      -  policymaker
      permissions:
        configure: "c.*"
        write: "w.*"
        read: "r.*"
  policies:   
    - name: test_policy
      parameters:
        pattern: "^test$"
        definition:
          federation-upstream-set: all
        apply-to: exchanges
        priority: 2
```
The operator will listen on those objects, and create them as necessary, if the object is deleted - the objects above will be deleted.

The parameters description is here:

Parameter | Description | Mandatory
------------ |------------ | ------------
annotations | rabbit-controller-class must have the value defined in the parent's controller, so it will be able to scrape this resource. | no, but will be ignored if not specified.
vhost | Holds virtual host parameters | yes
vhost.name | Name of virtual host, all objects will be created under this host name | yes
vhost.create | should create the vhost (if we want a new one) - note that if this resource is deleted, the vhost (and everything under it) will be deleted aswell | no
users | List of users to create | no
users.name | The username.Users with the same name of the admin user (rabbit's global admin) - will be fully skipped (with warning in log) | yes
users.password | Password of the user | yes if passwordHash is not specified
users.passwordHash | Hash of the password - as defined in here:https://stackoverflow.com/questions/41306350/how-to-generate-password-hash-for-rabbitmq-management-http-api<br><br>https://blog.sleeplessbeastie.eu/2019/08/28/how-to-generate-rabbitmq-password-hash/<br><br>If both passwordHash and password are specified, passwordHash is preferredThe algorithm to create password hash is here: https://blog.sleeplessbeastie.eu/2019/08/28/how-to-generate-rabbitmq-password-hash/ | yes if Password is not specified
users.passwordSecretRef | contains info about a secret in the same namespace, which will contain the password for the user.<br>apiVersion: v1<br> kind: Secret<br> metadata:<br>   name: myrabbitsecret<br>   namespace: ariel<br> type: Opaque<br> data:<br>   PASS: dGVzdGVy<br><br> To do so - add a ClusterRole that allows access to your secret, and label it with rbac.authorization.k8s.io/aggregate-to-rabbitcontroller: "true" (so the rabbit operator can read that secret). <br>Note, if you use this feature ,you must add also a "ClusterRole" so the rabbit operator can actually access the secret.apiVersion: <br><br>rbac.authorization.k8s.io/v1beta1<br> kind: ClusterRole<br> metadata:<br>   labels:<br>         rbac.authorization.k8s.io/aggregate-to-rabbitcontroller: "true"<br>	   name: aggregatesecret<br> rules:<br> - apiGroups: [""]<br>   resources: ["secrets"]<br>   resourceNames: ["myrabbitsecret"]<br>   verbs: ["get"]<br>This takes priority over regular password, but passwordHash is used over this if specified, so the priority is: hash → from secret → password | No
users.passwordSecretRef.name | Name of the secret to contain the password - from the above example it's "myrabbitsecret" | yes
users.passwordSecretRef.key | the key of the secret, in the above example it's "PASS", if not specified "Password" is used as key. | no
users.tags | list of tags to give the user, valid values:<br> https://www.rabbitmq.com/management.html#permissions<br>If the controller specified "removeAdminPrivilegesFromUsers = true" - "administrator" tags will be removed from the user, and user will be created with the rest of the tags | no
users.permissions | defines permission for the user on the vhost | no
users.permissions.configure | Permission pattern for configuration operations for this user in this vhost.<br>https://www.rabbitmq.com/access-control.html#authorisation | no
users.permissions.write | Permission pattern for write operations for this user in this vhost.<br>https://www.rabbitmq.com/access-control.html#authorisation | no
users.permissions.read | Permission pattern for read operations for this user in this vhost.<br>https://www.rabbitmq.com/access-control.html#authorisation | no
policies | List of policies for the specific vhost<br>https://www.rabbitmq.com/parameters.html#policies | no
policies.name | name of policy | yes
policies.parameters.pattern | a regular expression that matches one or more queue (exchange) names. Any regular expression can be used. | yes
policies.parameters.definition | a set of key/value pairs (think a JSON document) that will be injected into the map of optional arguments of the matching queues and exchanges.atleast one definition should exist.<br>https://www.rabbitmq.com/parameters.html#combining-policy-definitions | yes
policies.parameters.apply-to | apply to which object, valid values are only:exchangesqueuesalldefault is "all" | no
policies.parameters.priority | defines the policies' priority, default is 0 | no

The operator's parameters are as followed:

Parameter | Description | Default
------------ |------------ | ------------
controller.enabled | Enabling creation of custom resource "RabbitConfig" to create rabbitMQ administrative objects, Please deploy custom CRD under controller/crd/controller_crd.yaml | false
controller.RabbitClass | Support RabbitConfig objects with annotation of "rabbit-controller-class = this value, Annotate any RabbitConfig objects so this controller will catch them | carabbitmq
controller.resyncPeriod | In seconds, all RabbitConfigs objects with the relevant annotation (class) will be sent to the controller again, which will sync any changed parameters | 600
controller.removeAdminPrivilegesFromUsers | To increase security, as the config classes can create users, this can control if administrator users are allowed, or if not, the admin privilege will be removed, user will be created admin | true
controller.skipFollowingVhosts | To increase security, this is a comma seperated list of VHOST that should not be deleted in case a RabbitConfig specifies to create the vhost | \
controller.loglevel | Controller's log level (debug, info, warning, error)... https://www.loggly.com/ultimate-guide/python-logging-basics/ | warning
controller.replicas | Number of controller's replicas | 2
controller.image.pullPolicy | Controller image pull policy | Always if imagetag is latest, else IfNotPresent
controller.image.repository | Controller image repository | TBD
controller.image.tag | Controller container image tag | TBD
controller.image.resources | Resource Limits for controller | {}

**Few implementation notes:**

- / vhost by default cannot be deleted (as specified in controller's skipFollowingVhosts) - this protects a rogue object to change admin's permissions and even delete it upon object deletion from kubernetes

- admin user (defined in values.yaml) is used in the controller, if a rogue object tries to specify this user in its YAML, it will be skipped and a warning will be written to controller's logs
- If RabbitConfig's CRD is changed, it seems that metacontroller pod will require a restart (https://github.com/GoogleCloudPlatform/metacontroller/issues/181)
- If we're planning to delete RabbitConfig CRD and it's not deleted - we might need to manually update it's finalizer, more of this is here: https://blog.2vcps.io/2019/04/19/namespace-issues-when-removing-crd-operators/
- If the object name (user/policy etc..) is changed (for same deployment) - it will not change the name of the old object (if i change a username from a to b, then uploads the RabbitConfig, 'b' will be created, 'a' will not be deleted) - this can be fixed by some state handling which i wanted to avoid
- I haven't added a fully protection of admin users change - this can be added in the future.

**k8s RBAC permissions**
As the metacontroller project needs to access kubernetes objects, it has ClusterRole and ClusterRoleBinding (https://kubernetes.io/docs/reference/access-authn-authz/rbac/)

Those are an objects that define what can a service account do with kubernetes API.

The service account is then attached to the pod (through deployment) - and gives it the specified RBAC permissions to access the cluster.

To increase security, we removed the global cluster permissions that MetaController had, and set minimal RBAC permissions - only for the metacontroller's objects.

This means, that each new controller that is created, depends what it does (uses a new CRD, or handles pods / deployments / etc...) we need to add a RBAC permission to the metacontroller.

This is done through aggregated role (https://github.com/GoogleCloudPlatform/metacontroller/issues/81) - and per microservice.

In Rabbit, metacontroller needs to manage RabbitConfigs, so we added to rabbit's deployment the following RBAC rule:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-metacontroller: "true"
  name: rabbit-ctlaggr
rules:
- apiGroups:
  - example.com
  resources:
  - rabbitconfigs
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - update
  - watch
```
- In here, we allow a get/update/delete and watch on the new custom RabbitConfig
- the label "aggregate-to-metacontroller" is what attachs this to the metacontroller, thus, it will be added to the pod - letting metacontroller handle RabbitConfigs crds.

Because of that, the final rules configuration of metaconfig is:
```
rules:
- apiGroups:
  - example.com
  resources:
  - rabbitconfigs
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - update
  - watch
- apiGroups:
  - metacontroller.k8s.io
  resources:
  - controllerrevisions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metacontroller.k8s.io
  resources:
  - compositecontrollers
  - controllerrevisions
  - decoratorcontrollers
  verbs:
  - get
  - list
  - watch
```
- 2 of the metacontroller ones are defined in the metacontroller
- rabbit one was aggregated to the metacontroller using the label.

**RBAC permissions for "PasswordSecretRef"**

we don't want our rabbit controller to read secrets from all namespaces freely, that's why we used a similar technique of the role aggregation, and each microservice should attach a cluster role permission to read its secret, because the rabbit controller only uses "read namespaced secret" to get the password of the user:

https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#read_namespaced_secret

so, we gave an empty ClusterRole rbac to the rabbit controller, with the "rbac.authorization.k8s.io/aggregate-to-rabbitcontroller" label.

To allow it to read a specific microservice secret, it will need to add a role similar to this:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:    
    rbac.authorization.k8s.io/aggregate-to-rabbitcontroller: "true"	
  name: aggregatesecret
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["myrabbitsecret"]
  verbs: ["get"]
```

**Rabbitmq's values.yaml additions**
```
controller:
  ## This feature lets us create a "RabbitConfig" resource that will manage rabbitmq objects
  enabled: true

  ## administrative username/password to attach to the controller
  rabbitmqUsername: controlleradmin
  rabbitmqPassword: admin

  ## Service account to create, note that the name will be taken from parent rabbit's serviceaccount name with "-controller" suffix
  serviceAccount:
    create: true
  
  ## Add the role based access control so metacontroller would be able to listen on custom RabbitConfig objects
  rbac:
    create: true

  ## Name of the Rabbit config class to route through this controller
  ## Annotate each "RabbitConfig" resource with the "rabbit-controller-class" annotation so this controller will catch it.
  RabbitClass: rabbitmq
  
  ## Number of seconds to perform a full resync of all RabbitConfig objects (meaning - create / change configuration of any object handled)
  resyncPeriod: 600
  
  ## This protects the creation of administrative users, it will remove their tags.
  removeAdminPrivilegesFromUsers: true
  
  ## The following  is a comma seperated list of virtual host the controller should ignore (will not create or delete them if "create" was specified in the RabbitConfig object)
  skipFollowingVhosts: "/custom, /"

  ## Log level for the controller, "debug" for full info. https://www.loggly.com/ultimate-guide/python-logging-basics/
  loglevel: warning

  ## Number of replicas of the controller
  replicas: 1
  image:
  
    ## The docker image which contains python 3, pyrabbit2 (rabbitmq management API wrapper) and flask (python web service)
    repository: "abc/rabbit-python"
    tag: "2.2"
    pullPolicy: IfNotPresent

  ## Allow overriding of container resources
  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 5

  readinessProbe:
    initialDelaySeconds: 5
    failureThreshold: 6    
    timeoutSeconds: 5
    periodSeconds: 60

```

**Describe alternatives you've considered**
- Either in the service's init container - which exposes an admin user to the microservice (which is bad)
- Either in definition.json - which is hard to maintain

**I've incorporated it in rabbit's chart, but i'm not 100% sure if it should be there, or the metacontroller project should be a separate one, etc... Some comments are welcomed.**
