### ISSUE TITLE
[grafana] restartPolicy for the datasource isn't applied

### ISSUE THREAD

**Issue by jeff-knurek** [helm/charts#1803]
**Version of Helm and Kubernetes**:
* helm v2.6.0
* k8s: v1.7.3

**Which chart**:
stable/grafana: v0.4.3

**What happened**:
`restartPolicy` for the datasource isn't applied, which seems to cause a default to "Always" which is unsupported in GKE:
```
Error: release staging failed: Job.batch "staging-grafana-set-datasource" is invalid: [spec.template.spec.containers[0].image: Required value, spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: OnFailure, Never]
```

**How to reproduce it** (as minimally and precisely as possible):
`helm install -f values-grafana.yaml stable/grafana --version 0.4.3 --name staging --namespace test`
where values-grafana.yaml:
```
server:
  setDatasource:
    enabled: true
    datasource:
      name: prometheus
      type: prometheus
      url: "http://staging-prometheus-server.core.svc.cluster.local"
  restartPolicy: Never
```

**Anything else we need to know**:
`helm install -f ta-core/values-grafana.yaml stable/grafana --version 0.4.3 --name staging --namespace test --dry-run --debug`
```
---
# Source: grafana/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: staging-grafana
    chart: "grafana-0.4.3"
    component: "grafana"
    heritage: "Tiller"
    release: "staging"
  name: staging-grafana-set-datasource
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: staging-grafana
        component: "grafana"
        release: "staging"
    spec:
      containers:
      - name: staging-grafana-set-datasource
        image: ""
        env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: staging-grafana
              key: grafana-admin-user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: staging-grafana
              key: grafana-admin-password
        args:
          - "http://$(ADMIN_USER):$(ADMIN_PASSWORD)@staging-grafana:/api/datasources"
          - "--max-time"
          - "10"
          - "-H"
          - "Content-Type: application/json;charset=UTF-8"
          - "--data-binary"
          - "{\"name\":\"prometheus\",\"type\":\"prometheus\",\"url\":\"http://staging-prometheus-server.core.svc.cluster.local\",\"database\":\"\",\"jsonData\":{  },\"access\":\"\",\"isDefault\":}"
      restartPolicy:
```
