### ISSUE TITLE
[stable/redis] Incompatible types for equality comparison

### ISSUE THREAD

**Issue by sebnyberg** [helm/charts#18141]
After upgrading to Helm 2.15, the chart (v9.3.2) is throwing an error regarding the EQ operator at
https://github.com/helm/charts/blob/master/stable/redis/templates/redis-master-statefulset.yaml#L81

Error:

```
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison
```

To try it out, simply run:

```
helm install stable/redis
```

**Comment by nahid** [comment]
Same error:
`error calling eq: incompatible types for comparison`

**Comment by carrodher** [comment]
Hi, a new version of Helm was released yesterday (`2.15.1`). Among other fixes, it includes:
- Reverted changes introduced in https://github.com/helm/helm/pull/6010

Can you confirm if the issue is solved using the new Helm version?

**Comment by tomjohnburton** [comment]
Still unresolved unfortunately.

I ran the update
```
▶ helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

Followed by attempting to install
```
 helm install stable/redis --values values.yaml --name redis --namespace default                  
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing 
"redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison

```

**Comment by skotu-vida** [comment]
@tomjohnburton can you paste your values.yaml once

**Comment by skotu-vida** [comment]
@tomjohnburton can you paste your values.yaml once

**Comment by tomjohnburton** [comment]
Hangon! I just realised that I hadn't set the `securityContext` in both the `slave` and `master` configuration.

```
  ## Redis Master Pod Security Context
  ##
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
```
```
  # Redis slave pod Security Context
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
```
