### ISSUE TITLE
incubator/jaeger

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#18149]
Hi, 

I am deploying a sample deployment and service  for my application once i installed jaeger using incubator helm chart. Below is the sample configuration file that i am using to deploy my sample micro service. 

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: model
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: fintechmodel
        image: hitesh1907nayyar/fintech
        ports:
        - name: fintech
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-model
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

I am not able to see my service name in Jaeger UI once i hit the end point even though i get response. Will the configuration file to deploy the service and Pod require any change ?

@dvonthenen @mikelorant @naseemkullah @pavelnikolov - Your help will be really appreciated.

**Comment by naseemkullah** [comment]
Your app is instrumented with something like jaeger/opencensus/opentelemetry client library?

Then you need to point to the jaeger agent address to send the spans. E.g. if using jager daemonset:

```
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
````
