### ISSUE TITLE
[stable/sonarqube] issue Deploying SonarQube to Ingress on non root path (e.q. /sq). SQ web UI will not load, just spinning animation.

### ISSUE THREAD

**Issue by hectoralicea** [helm/charts#18158]
**Describe the bug**
Deploying SonarQube to Ingress on non root path (e.q. /sq) SQ web UI will not load, just spinning animation with invoking calls to /js uri rather than /sq/js
No errors found in log

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Kubernetes Version
1.14
Platform Version
eks.2

**Which chart**:
HELM_RELEASE_VERSION=2.3.0
HELM_CHART='stable/sonarqube'
SQ_CONTAINER_TAG=7.9.1-community

**What happened**:
Chart installed successfully using the following helm command
```
helm upgrade ${HELM_RELEASE_NAME} ${HELM_CHART} \
  --debug \
  --version ${HELM_RELEASE_VERSION} \
  --namespace ${K8S_NAMESPACE} \
  --wait \
  --recreate-pods \
  --reset-values \
  -f  updatedsqvalues.yaml
```

when I go to the site at /sq, sonarqube UI shows up but there is a spinning animation.  I ran to see which URL its trying to go to and its trying to pull up java script from the following URL.
/js/vendors-main.m.d184ed05.chunk.js
/js/main.m.df4d38dd.js

**What you expected to happen**:
JavaScript files to get "gotten" should be 
/sq/js/vendors-main.m.d184ed05.chunk.js
/sq/js/main.m.df4d38dd.js

**How to reproduce it** (as minimally and precisely as possible):
Following is the yaml file being submitted

```
replicaCount: 1
image:
  repository: sonarqube
  tag: 7.9.1-community
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
plugins:
  install:
     - "https://github.com/racodond/sonar-css-plugin/releases/download/4.18/sonar-css-plugin-4.18.jar"
     - "https://github.com/QualInsight/qualinsight-plugins-sonarqube-smell/releases/download/qualinsight-plugins-sonarqube-smell-4.0.0/qualinsight-sonarqube-smell-plugin-4.0.0.jar"
     - "https://repo1.maven.org/maven2/org/sonarsource/scm/git/sonar-scm-git-plugin/1.9.0.1725/sonar-scm-git-plugin-1.9.0.1725.jar"
     - "https://github.com/gabrie-allaigre/sonar-gitlab-plugin/releases/download/4.1.0-SNAPSHOT/sonar-gitlab-plugin-4.1.0-SNAPSHOT.jar"
     - "https://github.com/SonarSource/sonar-dotnet/releases/download/7.16.0.8981/sonar-csharp-plugin-7.16.0.8981.jar"
     - "https://repo1.maven.org/maven2/org/sonarsource/html/sonar-html-plugin/3.2.0.2082/sonar-html-plugin-3.2.0.2082.jar"
     - "https://github.com/SonarSource/SonarJS/releases/download/5.2.1.7778/sonar-javascript-plugin-5.2.1.7778.jar"
     - "https://repo1.maven.org/maven2/org/sonarsource/java/sonar-java-plugin/5.14.0.18788/sonar-java-plugin-5.14.0.18788.jar"
     - "https://repo1.maven.org/maven2/org/sonarsource/php/sonar-php-plugin/3.2.0.4868/sonar-php-plugin-3.2.0.4868.jar"
     - "https://repo1.maven.org/maven2/org/sonarsource/python/sonar-python-plugin/1.14.1.3143/sonar-python-plugin-1.14.1.3143.jar"
     - "https://repo1.maven.org/maven2/org/sonarsource/slang/sonar-scala-plugin/1.5.0.315/sonar-scala-plugin-1.5.0.315.jar"
     - "https://repo1.maven.org/maven2/org/sonarsource/typescript/sonar-typescript-plugin/1.9.0.3766/sonar-typescript-plugin-1.9.0.3766.jar"
sonarWebContext: /sq/
ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: compliance-ingress-test
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - path: /sq(/|$)(.*)
```

**Anything else we need to know**:
