### ISSUE TITLE
[stable/grafana] Datasources configmaps are not added automatically to grafana (needs grafana pod recreation)

### ISSUE THREAD

**Issue by clausa20** [helm/charts#18165]
When I add following datasource configmap with 
```
sidecar:
  datasources:
      enabled: true
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafanadatasource
  labels:
     grafana_datasource: "1"
data:
  prometheus.yaml: |-
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheuslb.mynamespace.svc.skydns.local:9090
      isDefault: false
      version: 1
      editable: true
```

datasource is not added automatically to grafana, I need to delete grafana pod so it is regenerated and then so the datasource is recognized by grafana.
