### ISSUE TITLE
MySQL Chart doesn't load values.yaml

### ISSUE THREAD

**Issue by davidassetowl** [helm/charts#1816]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
Helm: v2.5.0
Kubernetes: v1.7.0

**Which chart**:
MySQL

**What happened**:
Running this command:
`helm install --name my-release -f values.yaml stable/mysql` doesn't load values.yaml

**What you expected to happen**:
Custom MySQL Configuration + Username + Password loaded

**How to reproduce it** (as minimally and precisely as possible):
Edit values.yaml
Uncomment some parameters (e.g Username /Password / Configurationfiles) 
Run `helm install --name my-release -f values.yaml stable/mysql`

**Anything else we need to know**:
No configmap is generated. Password is autogenerated (because values.yaml is not taken)
setting parameter using --set works fine

**Comment by prydonius** [comment]
@davidassetowl I wasn't able to repro this, can I see your values file?

**Comment by davidassetowl** [comment]
```
## mysql image version
## ref: https://hub.docker.com/r/library/mysql/tags/
##
image: "mysql"
imageTag: "5.7.15"

## Specify password for root user
##
## Default: random 10 character string
mysqlRootPassword: roottesting

## Create a database user
##
mysqlUser: testuser
mysqlPassword: usertesting

## Allow unauthenticated access, uncomment to enable
##
# mysqlAllowEmptyPassword: true

## Create a database
##
mysqlDatabase: db-test

## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
##
imagePullPolicy: IfNotPresent

## Persist data to a persitent volume
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

# Custom mysql configuration files used to override default mysql settings
configurationFiles:
  mysql_custom.cnf: |-
    [server]
    # Allow us to upload large files
    max_allowed_packet = 100M
    innodb_log_file_size = 900M

    # Ensure 'STRICT_TRANS_TABLES' is in list, and 'ONLY_FULL_GROUP_BY' _not_ in list
    sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

    # Database should always be in UTC
    default_time_zone = '+00:00'

    # Allow us to have non-nullable timestamp fields without defaulting to current date
    explicit_defaults_for_timestamp = true

    # Full UTF-8 support
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
```

then, running

`helm install --name db-test -f values.yaml stable/mysql`

and verifying if the file is present by ssh'ing the pod

```
root@db-test-mysql-2100103926-ln2bk:/# ls /etc/mysql/conf.d/
mysql.cnf
```
