### ISSUE TITLE
[stable/kubernetes-dashboard] ingress enabling from --set parameter can't be validated

### ISSUE THREAD

**Issue by dmitryzykov** [helm/charts#1828]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT
 

**Version of Helm and Kubernetes**: Helm 2.2.2, Kubernetes 1.6

**Which chart**: stable/kubernetes-dashboard

**What happened**: 
In this chart ingress is disabled by default, when I'm trying to enable it from cli I got an error:
```
helm install --set ingress.enabled=True,ingress.hosts[0]=dashboard.kubernetes,ingress.annotations[0]="kubernetes.io/ingress.class: nginx" stable/kubernetes-dashboard
Error: release silly-dragonfly failed: Ingress.extensions "silly-dragonfly-kubernetes-dashboard" is invalid: spec: Invalid value: []extensions.IngressRule(nil): either `backend` or `rules` must be specified

```
**What you expected to happen**:
Chart should be installed with enabled ingress

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --set ingress.enabled=True,ingress.hosts[0]=dashboard.kubernetes,ingress.annotations[0]="kubernetes.io/ingress.class: nginx" stable/kubernetes-dashboard
```

**Anything else we need to know**:
I think it's somehow related to https://github.com/kubernetes/charts/issues/1539
In default `values.yaml` ingress.hosts section is commented. 
When I created custom `values.yaml` with uncommented values this chart was installed correctly. 
```yaml
ingress:
  enabled: enable

  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - dashboard.kubernetes
```
```
[root@test1 dashboard]# helm install stable/kubernetes-dashboard -f /root/.helm/dashboard/values.yaml
NAME:   plucking-prawn
LAST DEPLOYED: Wed Aug 23 16:27:16 2017
NAMESPACE: default
STATUS: DEPLOYED
```

**Comment by gyliu513** [comment]
@dmizyk I think this is not related to #1539, you can set `ingress.hosts=[dashboard.kubernetes]`, it should works.

#1539 can cause some issues if someone want to read key value from values.yaml. As the key are commented, then we cannot read the key from values.yaml.

**Comment by dmitryzykov** [comment]
@gyliu513 Thank you for your response.
I have tried what you suggested, but I got this error:
```
helm install --set ingress.enabled=True,ingress.hosts=[dashboard.kubernetes] stable/kubernetes-dashboard
Error: render error in "kubernetes-dashboard/templates/NOTES.txt": template: kubernetes-dashboard/templates/NOTES.txt:7:17: executing "kubernetes-dashboard/templates/NOTES.txt" at <.Values.ingress.host...>: range can't iterate over [dashboard.kubernetes]
```

**Comment by gyliu513** [comment]
Yes, I also tried with `--set ingress.enabled=True,ingress.hosts=[dashboard.kubernetes]` and seems does not work, not sure what is wrong with the format of the list here.

Does anyone from @kubernetes/helm-maintainers know how to set a list value when `helm install`? Thanks.

**Comment by gyliu513** [comment]
@dmizyk this command works well, please run in your env to see if it works.

```
root@k8s001:~/go/src/github.com/gyliu513/charts# helm install --set ingress.enabled=True,ingress.hosts[0]=dashboard.kubernetes,ingress.annotations[0]="kubernetes.io/ingress.class: nginx" stable/kubernetes-dashboard --debug --dry-run
[debug] Created tunnel using local port: '33236'

[debug] SERVER: "localhost:33236"

[debug] Original chart version: ""
[debug] CHART PATH: /root/go/src/github.com/gyliu513/charts/stable/kubernetes-dashboard

NAME:   brawny-wolf
REVISION: 1
RELEASED: Tue Aug 29 21:04:55 2017
CHART: kubernetes-dashboard-0.2.0
USER-SUPPLIED VALUES:
ingress:
  annotations:
  - 'kubernetes.io/ingress.class: nginx'
  enabled: true
  hosts:
  - dashboard.kubernetes

COMPUTED VALUES:
httpPort: 80
image: gcr.io/google_containers/kubernetes-dashboard-amd64
imagePullPolicy: IfNotPresent
imageTag: v1.6.3
ingress:
  annotations:
  - 'kubernetes.io/ingress.class: nginx'
  enabled: true
  hosts:
  - dashboard.kubernetes
nodeSelector: {}
rbac:
  create: false
  serviceAccountName: default
resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi
serviceType: ClusterIP

HOOKS:
MANIFEST:

---
# Source: kubernetes-dashboard/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: brawny-wolf-kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"
    release: "brawny-wolf"
    chart: "kubernetes-dashboard-0.2.0"
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: kubernetes-dashboard
    release: "brawny-wolf"
---
# Source: kubernetes-dashboard/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brawny-wolf-kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"
    release: "brawny-wolf"
    chart: "kubernetes-dashboard-0.2.0"
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
        heritage: "Tiller"
        release: "brawny-wolf"
        chart: "kubernetes-dashboard-0.2.0"
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: "default"
      nodeSelector:
          {}

      containers:
      - name: main
        image: "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi

        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
---
# Source: kubernetes-dashboard/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    0: "kubernetes.io/ingress.class: nginx"
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"
    release: "brawny-wolf"
    chart: "kubernetes-dashboard-0.2.0"
  name: brawny-wolf-kubernetes-dashboard
spec:
  rules:
    - host: dashboard.kubernetes
      http:
        paths:
          - path: /
            backend:
              serviceName: brawny-wolf-kubernetes-dashboard
              servicePort: 80
```

**Comment by dmitryzykov** [comment]
In `--dry-run` mode it doesn't show me errors either.
```
helm install --set ingress.enabled=True,ingress.hosts[0]=dashboard.kubernetes,ingress.annotations[0]="kubernetes.io/i
ngress.class: nginx" stable/kubernetes-dashboard --debug --dry-run
Created tunnel using local port: '39898'
SERVER: "localhost:39898"
Fetched stable/kubernetes-dashboard to kubernetes-dashboard-0.2.0.tgz
CHART PATH: /kubernetes-dashboard-0.2.0.tgz
NAME:   errant-gopher
REVISION: 1
RELEASED: Tue Aug 29 15:14:03 2017
CHART: kubernetes-dashboard-0.2.0
USER-SUPPLIED VALUES:
ingress:
  annotations[0]: 'kubernetes.io/ingress.class: nginx'
  enabled: true
  hosts[0]: dashboard.kubernetes

COMPUTED VALUES:
httpPort: 80
image: gcr.io/google_containers/kubernetes-dashboard-amd64
imagePullPolicy: IfNotPresent
imageTag: v1.6.3
ingress:
  annotations[0]: 'kubernetes.io/ingress.class: nginx'
  enabled: true
  hosts[0]: dashboard.kubernetes
nodeSelector: {}
rbac:
  create: false
  serviceAccountName: default
resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi
serviceType: ClusterIP   

HOOKS:
MANIFEST:

---
# Source: kubernetes-dashboard/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: errant-gopher-kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"   
    release: "errant-gopher"
    chart: "kubernetes-dashboard-0.2.0"
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: kubernetes-dashboard
    release: "errant-gopher"

---
# Source: kubernetes-dashboard/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: errant-gopher-kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"   
    release: "errant-gopher"
    chart: "kubernetes-dashboard-0.2.0"
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1  
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
        heritage: "Tiller"
        release: "errant-gopher"
        chart: "kubernetes-dashboard-0.2.0"
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: "default"
      nodeSelector:
          {}

      containers:
      - name: main
        image: "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi 
          requests:
            cpu: 100m
            memory: 50Mi 

        livenessProbe:   
          failureThreshold: 3
          httpGet:
            path: /
            port: 9090   
            scheme: HTTP 
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP  

---
# Source: kubernetes-dashboard/templates/ingress.yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"   
    release: "errant-gopher"
    chart: "kubernetes-dashboard-0.2.0"
  name: errant-gopher-kubernetes-dashboard
spec:
  rules:
```
but when I run it in normal mode error the same:
```
helm install --set ingress.enabled=True,ingress.hosts[0]=dashboard.kubernetes,ingress.annotations[0]="kubernetes.io/ingress.class: nginx" stable/kubernetes-dashboard --debug
Created tunnel using local port: '43412'
SERVER: "localhost:43412"
Fetched stable/kubernetes-dashboard to kubernetes-dashboard-0.2.0.tgz
CHART PATH: /kubernetes-dashboard-0.2.0.tgz
Error: release illocutionary-clam failed: Ingress.extensions "illocutionary-clam-kubernetes-dashboard" is invalid: spec: Invalid value: []extensions.IngressRule(nil): either `backend` or `rules` must be specified
```

**Comment by gyliu513** [comment]
My env is working well..

```
root@k8s001:~/go/src/github.com/gyliu513/charts# helm install --set ingress.enabled=True,ingress.hosts[0]=dashboard.kubernetes,ingress.annotations[0]="kubernetes.io/i
> ngress.class: nginx" stable/kubernetes-dashboard
NAME:   wrinkled-mole
LAST DEPLOYED: Tue Aug 29 23:34:09 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                                CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
wrinkled-mole-kubernetes-dashboard  10.254.170.201  <none>       80/TCP   0s

==> v1beta1/Deployment
NAME                                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
wrinkled-mole-kubernetes-dashboard  1        1        1           0          0s

==> v1beta1/Ingress
NAME                                HOSTS                 ADDRESS  PORTS  AGE
wrinkled-mole-kubernetes-dashboard  dashboard.kubernetes  80       0s


NOTES:
*********************************************************************************
*** PLEASE BE PATIENT: kubernetes-dashboard may take a few minutes to install ***
*********************************************************************************
From outside the cluster, the server URL(s) are:
     http://dashboard.kubernetes
```

```
root@k8s001:~/go/src/github.com/gyliu513/charts# helm install --set ingress.enabled=True,ingress.hosts[0]=dashboard.kubernetes,ingress.annotations[0]="kubernetes.io/ingress.class: nginx" stable/kubernetes-dashboard --debug
[debug] Created tunnel using local port: '33347'

[debug] SERVER: "localhost:33347"

[debug] Original chart version: ""
[debug] CHART PATH: /root/go/src/github.com/gyliu513/charts/stable/kubernetes-dashboard

NAME:   coy-saola
REVISION: 1
RELEASED: Tue Aug 29 23:36:38 2017
CHART: kubernetes-dashboard-0.2.0
USER-SUPPLIED VALUES:
ingress:
  annotations:
  - 'kubernetes.io/ingress.class: nginx'
  enabled: true
  hosts:
  - dashboard.kubernetes

COMPUTED VALUES:
httpPort: 80
image: gcr.io/google_containers/kubernetes-dashboard-amd64
imagePullPolicy: IfNotPresent
imageTag: v1.6.3
ingress:
  annotations:
  - 'kubernetes.io/ingress.class: nginx'
  enabled: true
  hosts:
  - dashboard.kubernetes
nodeSelector: {}
rbac:
  create: false
  serviceAccountName: default
resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi
serviceType: ClusterIP

HOOKS:
MANIFEST:

---
# Source: kubernetes-dashboard/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: coy-saola-kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"
    release: "coy-saola"
    chart: "kubernetes-dashboard-0.2.0"
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: kubernetes-dashboard
    release: "coy-saola"
---
# Source: kubernetes-dashboard/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coy-saola-kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"
    release: "coy-saola"
    chart: "kubernetes-dashboard-0.2.0"
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
        heritage: "Tiller"
        release: "coy-saola"
        chart: "kubernetes-dashboard-0.2.0"
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: "default"
      nodeSelector:
          {}

      containers:
      - name: main
        image: "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi

        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
---
# Source: kubernetes-dashboard/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    0: "kubernetes.io/ingress.class: nginx"
  labels:
    app: kubernetes-dashboard
    heritage: "Tiller"
    release: "coy-saola"
    chart: "kubernetes-dashboard-0.2.0"
  name: coy-saola-kubernetes-dashboard
spec:
  rules:
    - host: dashboard.kubernetes
      http:
        paths:
          - path: /
            backend:
              serviceName: coy-saola-kubernetes-dashboard
              servicePort: 80
LAST DEPLOYED: Tue Aug 29 23:36:38 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME                            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
coy-saola-kubernetes-dashboard  1        1        1           0          0s

==> v1beta1/Ingress
NAME                            HOSTS                 ADDRESS  PORTS  AGE
coy-saola-kubernetes-dashboard  dashboard.kubernetes  80       0s

==> v1/Service
NAME                            CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
coy-saola-kubernetes-dashboard  10.254.103.145  <none>       80/TCP   0s


NOTES:
*********************************************************************************
*** PLEASE BE PATIENT: kubernetes-dashboard may take a few minutes to install ***
*********************************************************************************
From outside the cluster, the server URL(s) are:
     http://dashboard.kubernetes
```

**Comment by gyliu513** [comment]
The only difference for us is the helm and kubernetes version.

```
root@k8s001:~/go/src/github.com/gyliu513/charts# helm version
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
root@k8s001:~/go/src/github.com/gyliu513/charts# kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.2134+38053c3e4486e6", GitCommit:"38053c3e4486e6a7fafd00b2784a1e67e0357f45", GitTreeState:"clean", BuildDate:"2017-08-18T08:01:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.2134+38053c3e4486e6", GitCommit:"38053c3e4486e6a7fafd00b2784a1e67e0357f45", GitTreeState:"clean", BuildDate:"2017-08-18T08:01:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Can you please try the version as above?

**Comment by dmitryzykov** [comment]
I have reinstalled helm manually to 2.6.0 and now it works well. (my previous helm was installed by kubespray installer) 
Thank you for help.

**Comment by gregbkr** [comment]
Hello, I was following your discussion, even if closed, maybe you guys will know the answer:

I got mainchart `app` and subchart `api` 

I overide api ingress var in the mainchart `app`, in file values.yaml:
```
api:
  ingress:
    hosts:
      - api.mine.gdev.local
```

In my deploy I want to use only the first row of the array:
```
         env:
            - name: REACT_APP_API_URL
              value: http://{{- range .Values.api.ingress.hosts }}{{ . }}{{- end }}
```
It seems a bit dirty like this, if I happen to have more than 1 line in array, value REACT_APP_API_URL will be messed up.

I would love  something like (but doesn't work): `value: http://{{ .Values.api.ingress.hosts[0] }}` or `value: http://{{ index "Values" "api" "ingress" "hosts[0]" }}`

Thank you for your help. 
Greg.
