### ISSUE TITLE
[stable/mongodb] Primary/Secondary Affinity

### ISSUE THREAD

**Issue by SudoBrendan** [helm/charts#18351]
**Is your feature request related to a problem? Please describe.**
Scheduling Primary and Secondary MongoDB nodes with the same affinity rules (.Values.affinity) increases the likelihood of complete MongoDB cluster outages (e.g. all Pods in both StatefulSets are scheduled to the same k8s node and that node blows up - StatefulSets by design do not reschedule Pods if a node goes down, so this means the MongoDB instance will be down until manual intervention is taken).

**Describe the solution you'd like**
Values.yml should support independent affinity rules for Primary (.Values.affinityPrimary) and Secondary (.Values.affinitySecondary) nodes, in a similar way that the Arbiter (.Values.affinityArbiter) is granted such a status.

**Other Solutions**
By default, Primary nodes should be given anti-affinity for Secondary nodes, and Secondary nodes should be given anti-affinity to Primary nodes.

I believe either of these solutions will work for most users of this chart, but I'm partial to giving teams the freedom to choose (option 1). Both alternatives increase the robustness of the MongoDB Cluster and prevent scheduling of the entire cluster to a particular k8s node.

Thoughts?

**Comment by SudoBrendan** [comment]
A workaround is creating an anti-affinity using a label shared between Primary and Secondary nodes - `release`:

```
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: release
            operator: In
            values:
            - mongodb-test
        topologyKey: "kubernetes.io/hostname"
```
