### ISSUE TITLE
[stable/spinnaker] spinnaker deployment is failing on Kubernetes 1.16

### ISSUE THREAD

**Issue by skotu-vida** [helm/charts#18460]
**Describe the bug**
Looks like the versions of minio and redis charts are old and those version do no support but the latest stable versions for both the charts support the changes of apiversion for deployments and statefulsets.

**Version of Helm and Kubernetes**:
```
root@ip-10-10-10-100#helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```
```
root@ip-10-10-10-100#kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
spinnaker chart

**What happened**:
getting the below validation error when trying to install spinnaker chart

```
helm install --name spinnaker stable/spinnaker

Error: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
```

**What you expected to happen**:
helm should get deploy a default setup of spinnaker

**How to reproduce it** (as minimally and precisely as possible):
run command `helm install --name spinnaker stable/spinnaker` on Kubernetes v1.16

**Anything else we need to know**:

**Comment by ramonskie** [comment]
you can solve this localy with the following
update requirements.yml with
```
dependencies:
- name: redis
  version: 9.4.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: minio
  version: 2.5.17
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
```
run ` helm dependency update`
than run the following in the spinnaker chart dir
`helm install --name spinnaker --namespace spinnaker . --timeout 600`
