### ISSUE TITLE
[haproxy-ingress/incubator] controller service targetPorts cannot be overwritten 

### ISSUE THREAD

**Issue by kalilou** [helm/charts#18462]
Hello, 

We are using haproxy-ingress in all our EKS cluster in AWS. We've actually replaced nginx-ingress by haroxy-ingress. And stumbled into an issue, we cannot overwrite the https targetPort to use http which we have been doing in nginx-ingress. Basically we are using AWS ELB as the haproxy-ingress controller service which handle the SSL termination. Is there is way to provide in the controller service manifest the targetPorts as parameter that way can use the http targetPort for the https port.

Current port section in the manifest:
```yaml
ports:
  {{- if .Values.controller.enableStaticPorts }}
  {{- range .Values.controller.service.httpPorts }}
    - name: "{{ .port }}-http"
      port: {{ .port }}
      protocol: TCP
      targetPort: http
      {{- if (not (empty .nodePort)) }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
  {{- range .Values.controller.service.httpsPorts }}
    - name: "{{ .port }}-https"
      port: {{ .port }}
      protocol: TCP
      targetPort:https
      {{- if (not (empty .nodePort)) }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
```

**Describe the solution you'd like**

values.yaml (controller.service) 

```yaml
httpPorts:
   - port: 80
     tagetPort: http
httpsPorts:
    - port: 443
      tagetPort: http
``` 
controller-service.yaml

```yaml
 ports:
  {{- if .Values.controller.enableStaticPorts }}
  {{- range .Values.controller.service.httpPorts }}
    - name: "{{ .port }}-http"
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      {{- if (not (empty .nodePort)) }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
  {{- range .Values.controller.service.httpsPorts }}
    - name: "{{ .port }}-https"
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      {{- if (not (empty .nodePort)) }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
```
