### ISSUE TITLE
[stable/etcd-operator] Chart does not respect nodeSelector

### ISSUE THREAD

**Issue by larsskj** [helm/charts#18477]
I'm trying to create an etcd cluster in a protected environment. 

It's running in AWS on a cluster created using KOPS. I have created an instance group just for etcd to ensure that no other applications are running on these nodes.

When I install the chart, I use the following _values.yaml_ file:

```
# Default values for etcd-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

## Install Default RBAC roles and bindings
rbac:
  create: true
  apiVersion: v1

## Service account name and whether to create it
serviceAccount:
  create: true
  name:

# Select what to deploy
deployments:
  etcdOperator: true
  # one time deployment, delete once completed,
  # Ref: https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/backup-operator.md
  backupOperator: true
  # one time deployment, delete once completed
  # Ref: https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/restore-operator.md
  restoreOperator: true

# creates custom resources, not all required,
# you could use `helm template --values <values.yaml> --name release_name ... `
# and create the resources yourself to deploy on your cluster later
customResources:
  createEtcdClusterCRD: false
  createBackupCRD: false
  createRestoreCRD: false

# etcdOperator
etcdOperator:
  name: etcd-operator
  replicaCount: 1
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.9.4
    pullPolicy: Always
  resources:
    cpu: 100m
    memory: 128Mi
  ## Node labels for etcd-operator pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector:
    kops.k8s.io/instancegroup: etcd
  tolerations:
  - key: dedicated
    operator: Equal
    value: etcd
    effect: NoSchedule
  ## additional command arguments go here; will be translated to `--key=value` form
  ## e.g., analytics: true
  commandArgs: {}
  ## Configurable health checks against the /readyz endpoint that etcd-operator exposes
  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
# backup spec
backupOperator:
  name: etcd-backup-operator
  replicaCount: 1
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.9.4
    pullPolicy: Always
  resources:
    cpu: 100m
    memory: 128Mi
  spec:
    storageType: S3
    s3:
      s3Bucket:
      awsSecret:
  ## Node labels for etcd pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector:
    kops.k8s.io/instancegroup: etcd
  ## additional command arguments go here; will be translated to `--key=value` form
  ## e.g., analytics: true
  commandArgs: {}
  securityContext: {}
  tolerations:
  - key: dedicated
    operator: Equal
    value: etcd
    effect: NoSchedule

# restore spec
restoreOperator:
  name: etcd-restore-operator
  replicaCount: 1
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.9.4
    pullPolicy: Always
  port: 19999
  resources:
    cpu: 100m
    memory: 128Mi
  spec:
    s3:
      # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
      # e.g: "etcd-snapshot-bucket/v1/default/example-etcd-cluster/3.2.10_0000000000000001_etcd.backup"
      path:
      awsSecret:
  ## Node labels for etcd pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector:
    kops.k8s.io/instancegroup: etcd
  ## additional command arguments go here; will be translated to `--key=value` form
  ## e.g., analytics: true
  commandArgs: {}
  securityContext: {}
  tolerations:
  - key: dedicated
    operator: Equal
    value: etcd
    effect: NoSchedule

## etcd-cluster specific values
etcdCluster:
  name: etcd-cluster
  size: 3
  version: 3.2.25
  image:
    repository: quay.io/coreos/etcd
    tag: v3.2.25
    pullPolicy: Always
  enableTLS: false
  # TLS configs
  tls:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls
  ## etcd cluster pod specific values
  ## Ref: https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-members-cluster-with-resource-requirement
  pod:
    ## Antiaffinity for etcd pod assignment
    ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    antiAffinity: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    ## Node labels for etcd pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    nodeSelector:
      kops.k8s.io/instancegroup: etcd
    securityContext: {}
    tolerations:
    - key: dedicated
      operator: Equal
      value: etcd
      effect: NoSchedule
```

As can be seen, we have four pod types: _etcdOperator_, _backupOperator_, _restoreOperator_, and _etcdCluster_. I have set the values for _nodeSelector_ as well as _tolerations_. The first three pod types follow these settings and the pods are created in the reserved nodes.

But the cluster itself, the actual etcd nodes, does not respect these settings and are created on other nodes as if the parameters wasn't set at all.

Have I done anything wrong - or does the chart not work correctly?

BTW: In the _values.yaml_ file included with the chart, the _etcdOperator_ has a setting for nodeSelector - but not for tolerations. I tried adding it anyway - and it works! But it should be included in the sample _values.yaml_, I'd suggest.

My Helm version is 2.13.1 running on Kubernetes cluster version 1.11.9.
