### ISSUE TITLE
[stable/sentry] How does one set config.configYml

### ISSUE THREAD

**Issue by ThaDaVos** [helm/charts#18483]
Not really a bug/issue, more like a question:

How does one, when using an answers file, pass along the configYml?

I tried the following:
```yaml
config.configYml: |
  ---
  system.admin-email: 'support@muntz.nl'
```

But this causes the Sentry-workers to crash and halts the deployment of the chart
