### ISSUE TITLE
[stable/postgresql] ServiceMonitor is not scrapped

### ISSUE THREAD

**Issue by asyd** [helm/charts#18511]
I'm trying to get postgresql metrics out of the box using stable/postgresql chart.

Helm version: 2.4.12
Kubernetes: 1.15.4
Chart version: postgresql-6.5.5 (app version: 11.5.0)

Here my `values.yml`:

```
metrics:
  enabled: true
  service: 
    type: ClusterIP
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
  serviceMonitor:
    enabled: true
    namespace: opencsi

postgresqlUsername: postgres

persistence:
  size: 5Gi

postgresqlDatabase: xxx
```

After install chart with `helm install --tiller-namespace opencsi --namespace opencsi stable/postgresql -f helm/postgresql.yml --name postgresql`  I have following endpoints, services:

```
$ kubectl get svc -n opencsi | grep postgres
postgresql                   ClusterIP      10.43.153.166   <none>        5432/TCP                      10m
postgresql-headless          ClusterIP      None            <none>        5432/TCP                      10m
postgresql-metrics           ClusterIP      10.43.228.64    <none>        9187/TCP                      10m

$ kubectl get endpoints -n opencsi | grep postgre
postgresql                   10.42.1.84:5432                 9m52s
postgresql-headless          10.42.1.84:5432                 9m52s
postgresql-metrics           10.42.1.84:9187                 9m52s
```

And the following `ServiceMonitor`:

```
$ kubectl get servicemonitors.monitoring.coreos.com -n opencsi postgresql -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2019-11-01T15:32:21Z"
  generation: 1
  labels:
    app: postgresql
    chart: postgresql-6.5.5
    heritage: Tiller
    release: postgresql
  name: postgresql
  namespace: opencsi
  resourceVersion: "5651147"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/opencsi/servicemonitors/postgresql
  uid: 6a020240-51b3-40a2-ad29-baf09a5376bb
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - opencsi
  selector:
    matchLabels:
      app: postgresql
      release: postgresql
```

However, when I look at `http://prometheus/service-discovery` there is no entry for postgresql (it doesn't appears in `kubectl -n monitoring get secret prometheus-prometheus-operator-prometheus -ojson | jq -r '.data["prometheus.yaml.gz"]' | base64 -d | gunzip` as well)

Note while chart prometheus-operator is running in another namespace, I have some ServiceMonitoring in `opencsi` namespace that are working, so I doubt it's a permission issue. 

But just in case, here the definition of `tiller` `ServiceAccount` and its privileges:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: opencsi
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: opencsi
rules:
- apiGroups: ["", "batch", "extensions", "apps", "monitoring.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: opencsi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller
  namespace: opencsi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-manager
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: opencsi
```

Any ideas are welcome! And thanks for your job

**Comment by juan131** [comment]
Hi @asyd 

According to your **values.yaml**:

```yaml
  serviceMonitor:
    enabled: true
    namespace: opencsi
```

Your Prometheus operator is running at `opencsi` namespace. If that's not the case, then you need to install the chart setting that parameter according to the namespace where the Prometheus operator is running.
