### ISSUE TITLE
[stable/postgresql] Create user through init script fails when database is also specified through helm parameters.

### ISSUE THREAD

**Issue by codemasterover9000** [helm/charts#18543]
**Describe the bug**
We just upgraded from helm chart 2.7.10 to 6.5.5.

If you want to enable metrics you need to specify a database through the helm properties "postgresql.postgresqlUsername/Password/Database" .
But then the create user statements in init scripts seem to fail. This used to work before. 

Using the following configuration

```
postgresql:
  postgresqlUsername: metrics
  postgresqlPassword: metrics
  postgresqlDatabase: metrics
```

We get a user "metrics" which has the following rights:

create databases: true
create login roles: false

With the following initscript:

```
CREATE USER test WITH PASSWORD 'test';
CREATE DATABASE test;
GRANT ALL PRIVILEGES ON DATABASE test TO test;
```

I do get a database "test" owned by user "metrics". The user "test" is not created. 
It seems like the init scripts is executed under user privileges of user "metrics". 
In the previous version the postgres user owned the database created through the initscript.

When not specifying a database though helm properties and disabling metrics the init scripts work as expected.

**Version of Helm and Kubernetes**:
Helm: v2.15.1
Kubernetes: 1.16

**Which chart**:
stable/postgresql: 6.5.5

**What happened**:
Failed to create users through init script

**What you expected to happen**:
User created as specified in init script

**How to reproduce it** (as minimally and precisely as possible):
See description

**Comment by javsalgar** [comment]
Hi,

We would need to take a look to that. However, are you able to do so if you do NOT specify these values?

```
postgresql:
  postgresqlUsername: metrics
  postgresqlPassword: metrics
  postgresqlDatabase: metrics
```

That way you should be able to access using the postgres user and create the databases and users.
