### ISSUE TITLE
[stable/mariadb] as `my chart` dependency issue with existing PVC

### ISSUE THREAD

**Issue by Mariyo** [helm/charts#18622]
**Describe the bug**
When I use **stable/mariadb** as dependency of my chart called `mychart`, I am not able to set existing PVC.

**Version of Helm and Kubernetes**:

**helm version**
Client:&version.Version{SemVer:"v2.15.1",GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server:&version.Version{SemVer:"v2.15.1",GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2",GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b",GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc",Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16",GitVersion:"v1.16.2",GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b",GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:  stable/mariadb

**What happened**:
New PVC created: `data-mychart-mariadb-master-0`

**What you expected to happen**:
Instead of new PVC created existing PVC `mychart-mariadb-pvc` will be used

**How to reproduce it** (as minimally and precisely as possible):

- `helm create mychart && cd mychart`
- add mariadb to `requirements.yaml`
  ```
  dependencies:
      -   name: mariadb
          version: 6.12.0 # helm search
          repository: "https://kubernetes-charts.storage.googleapis.com/"
  ```
- `helm dep update`
- `kubectl apply -f volume.yaml`
  ```
  apiVersion: v1
  kind: PersistentVolume
  metadata:
      name: mychart-pv
      labels:
          storage: local
  spec:
      capacity:
          storage: 1Gi
      accessModes:
          - ReadWriteOnce
      local:
          path: /var/mychart/data
      nodeAffinity:
          required:
              nodeSelectorTerms:
                  -   matchExpressions:
                          -   key: kubernetes.io/hostname
                              operator: In
                              values:
                                  - example-node
  
  ---
  
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
      name: mychart-mariadb-pvc
  spec:
      accessModes:
          - ReadWriteOnce
      resources:
          requests:
              storage: 1Gi
      selector:
          matchLabels:
              storage: local
  ```
- `helm package .`

```shell script
helm upgrade mychart mychart-0.1.0.tgz \
  --set mariadb.rootUser.password="root_password" \
  --set mariadb.db.password="my_password" \
  --set mariadb.replication.enabled=false \
  --set master.persistence.existingClaim="mychart-mariadb-pvc" \
  --namespace="mychart" \
  --force \
  --install
```

**Results:**

- `kubectl describe pvc -n default`
  ```
  Name:          mychart-mariadb-pvc
  Namespace:     default
  StorageClass:  
  Status:        Bound
  Volume:        mychart-pv
  Labels:        <none>
  Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                   {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mychart-mariadb-pvc","namespace":"default"},"spec":...
                 pv.kubernetes.io/bind-completed: yes
                 pv.kubernetes.io/bound-by-controller: yes
  Finalizers:    [kubernetes.io/pvc-protection]
  Capacity:      1Gi
  Access Modes:  RWO
  VolumeMode:    Filesystem
  Mounted By:    <none>
  Events:        <none>
  ```
- `kubectl describe pvc -n mychart`
  ```
  Name:          data-mychart-mariadb-0
  Namespace:     mychart
  StorageClass:  
  Status:        Pending
  Volume:        
  Labels:        app=mariadb
                 component=master
                 heritage=Tiller
                 release=mychart
  Annotations:   <none>
  Finalizers:    [kubernetes.io/pvc-protection]
  Capacity:      
  Access Modes:  
  VolumeMode:    Filesystem
  Mounted By:    mychart-mariadb-0
  Events:
    Type    Reason         Age               From                         Message
    ----    ------         ----              ----                         -------
    Normal  FailedBinding  9s (x2 over 11s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  ```
