### ISSUE TITLE
[stable/grafana] grafana redirects to localhost 

### ISSUE THREAD

**Issue by Sanjanare** [helm/charts#18643]
Hi...
I have added generic-auth to the grafana. 

```
grafana-tool:
  enabled: true
  grafana.ini:
    auth.generic_oauth:
      name: keycloak
      enabled: true
      client_id: grafana
      client_secret: *****
      scopes: openid profile email
      auth_url: *********
      token_url: *******
      allow_sign_up: true 
```
i am trying to hit this url https://grafana.test.com, it successfully shows a keycloak login page, after successful logging it re-directs to localhost instead of the url above
```
http://localhost:3000/login/generic_oauth?state=yh8cWxDMUhlBkDOH_yb3iapr4k24tn3pH8P534X-6DM%3D&session_state=8bbd51f9-8d21-4232-895a-d5bf360c4ef3&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..ld4TeVlvtHBWNuB0p4L3sA.klKujQ60UsaW7YEknput3-jP4OtvntLCtWqZZOy4ixWQCgdjKCq2b7JPusEE1pebNhOVfTaAbxEtwuMY4J69KgkrlDnezRta-oyXffR2KNiCvUpBqI0lwOmaymvWmkLH99V_CdnTEVQpU2EPtedCJfYWVuEap8aZpWzRRkJoq7FG2C0KMMj3k7YD9na5vf9kdPjHIsSmKRtGQg7c_gYLk2pZ_Nfl9Hkm0QAgkRSg6HhiObV6vqHTqHTGRzsAoy64.ofKfkWT2Yd8qEZFU61mdHw.
```
am i missing anything ?
