### ISSUE TITLE
[stable/chart/grafana] How to define data source as elasticsearch type

### ISSUE THREAD

**Issue by idobry** [helm/charts#18759]
Hey,
I'm trying to configure ElasticSearch as datasource and pass it to grafana's chart value file, so far I did:
```
      - name: ElasticsearchMonitor
        access: proxy
        basicAuth: false
        editable: false
        jsonData:
          tlsSkipVerify: true
        orgId: 1
        type: elasticsearch
        url: http://mydomain:9200
        version: 1
```
When I'm trying to test it I'm getting a popup window to enter creds following by error.
When I configure this as a data source manually(in grafana ui) it's working as it should.
Can someone please share his config for this?
thanks
