### ISSUE TITLE
charts/stable/nextcloud/values.yaml results in YAML parse error on nextcloud/templates/ingress.yaml: error unmarshaling JSON: while decoding JSON:

### ISSUE THREAD

**Issue by cjohn001** [helm/charts#18751]
Hello,
I was trying to work with the next cloud chart. There is a part in which annotions to an ingress controller can be configured. If I comment in the following part in line 55-58

```
  #  tls:
  #    - secretName: nextcloud-tls
  #      hosts:
  #        - nextcloud.kube.home
```

I get the following error:

Error: YAML parse error on nextcloud/templates/ingress.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field .annotations of type string

When I look at the helm --debug output this results in:

```
    tls:
    - hosts:
      - nextcloud.kube.home
      secretName: nextcloud-tls
```

Can someone provide a hint here how I can work around this issue?

I assume the relevant part should not be part of the annotation but rather part of the ingress? 
i.e.
ingress.annotation: 
...
ingress.tls:

If I configure it it at least can be executed. But it is not clear to me if this also results in the suggested behavior.
...

**Comment by toxuin** [comment]
Here's what I have set for mine and it seems to parse fine. I had weird parsing errors too, figured it's because it expects the `0` to be a string.

```yml
ingress:
  enabled: true
  annotations:
    "nginx.ingress.kubernetes.io/proxy-body-size": "0"
  tls:
    - hosts:
        - nextcloud.example.com
```
