### ISSUE TITLE
[stable/wordpress] nfs timeouts upgrading plugins

### ISSUE THREAD

**Issue by masterkain** [helm/charts#18766]
hello,

so I have this classic persistence:

```
    persistence:
      enabled: true
      size: 20Gi
      accessMode: ReadWriteMany
      storageClass: efs
```

EFS (NFS), but I have issues with upgrading plugins from the UI, especially big ones, such as updraft and jetpack.

When an upgrade is attempted the browser will wait until the connection drops, then plugin results always half installed, crashing the instance due to files not found.

in my nginx ingress I put some test values:

```
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
```

but I suspect I also need to tweak php timeouts, is there any way to do that via helm yet?
