### ISSUE TITLE
[stable/traefik] elb health check fails when mixed protocols on backend ports

### ISSUE THREAD

**Issue by sortigoza** [helm/charts#18777]
**Describe the bug**

If Trefik is configured with SSL enabled we need to add `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https` for propper mapping `HTTPS -> HTTPS`. additionally, the HTTP port will always be set, needing mapping `HTTP -> HTTP`.

Since the default behavior of kubernetes is to use the first port for the Health Check it will pick the HTTP port (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L3913) but SSL will be used as the protocol thus failing the HealthCheck.

**Version of Helm and Kubernetes**:

kubernetes
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

helm
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Which chart**:
chart: stable/traefik
version: 1.79.0

**What happened**:

ELB health check fails, it is using SSL instead of TCP (or it is not using the SSL port).

**What you expected to happen**:

ELB health check is healthy, using correct protocol (or it is using the SSL port)

**How to reproduce it** (as minimally and precisely as possible):

Deploy the chart in an AWS k8s cluster using these values:

```
ssl:
  enabled: true
  enforced: true
  insecureSkipVerify: true

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "a-cert-arn-here"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```

**Anything else we need to know**:

If the order of the ports in the service resource is changed it works:
```
- https
- http
```
instead of 
```
- http
- https
```

Having ssl enabled is nice and required in some cases to have e2e encryption and make the enforced option work.
