### ISSUE TITLE
stable/prometheus disable scapes

### ISSUE THREAD

**Issue by acarsercan** [helm/charts#18788]
Hi,

Like prometheus operator helm chart, can we allow the user to disable all scapes?

Currently I can only disable
```
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    pushgateway:
      enabled: false
```
can we incude 
```
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
````

Regards
