### ISSUE TITLE
[stable/grafana] not able to set notifiers via values.yaml

### ISSUE THREAD

**Issue by omnipresent07** [helm/charts#18780]
**Describe the bug**

I am trying to set the `notifiers` via `values.yaml` but unable to do so. When I use the `values.yaml` below, the `grafana` pod doesn't come up. This happens only when the `notifiers` key is present. 

below is the values.yaml that I'm using

```
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host : ""
      from_address: ""
      skip_verify: "true"
  notifiers:
    - name: "email-notifier"
      type: "email"
      uid: "email1"
      org_id: "My_Org:"
      is_default: true
      settings:
        addresses: "myemail@test.com"
```

**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
```

**Which chart**:

stable/prometheus-operator

**What happened**:

I run the command below:

```
helm upgrade --install prometheus stable/prometheus-operator --set kubeEtcd.enabled=true,kubeControllerManager.enabled=true,kubeScheduler.enabled=true,prometheusOperator.createCustomResource=true,grafana.smtp.existingSecret=smtp-secret -f values.yaml --namespace monitoring
```

**What you expected to happen**:

I expected grafana to be up with the notifications present in the `values.yaml `file

**How to reproduce it** (as minimally and precisely as possible):

Run the above helm command with the above values.yaml

**Anything else we need to know**:
