### ISSUE TITLE
[stable/grafana] datasource failing when setting password during deployment

### ISSUE THREAD

**Issue by iting07** [helm/charts#18796]
**Describe the bug**
Data source failing when trying to set Azure Monitor clientSecret (password) during deployment. I have added an Azure Monitor datasource via the values file and tested deployment by hard coding the password (clientSecret) which works correctly. 
When I leave clientSecret empty in the values.yaml file and try setting it during deployment 
`--set datasources.datasources.yaml.datasources[0].secureJsonData="password"` 
the Azure Monitor data source fails with an "unexpected error".
The Client Secret is showing as "configured" though.
![image](https://user-images.githubusercontent.com/29113353/68642265-b2536d80-0561-11ea-80ee-770edaa8af70.png)

**Version of Helm and Kubernetes**:
Helm v3.0.0-rc.3
Kubernetes v1.14.6

**Which chart**:
Grafana

**What happened**:
When going into the Azure Monitor data source, an "unexpected error" is shown.
![image](https://user-images.githubusercontent.com/29113353/68641723-d0b86980-055f-11ea-9dc2-78808e2df0ad.png)
Cannot see a list of Default Subscriptions in the data source.
![image](https://user-images.githubusercontent.com/29113353/68641741-dca42b80-055f-11ea-89db-12d5837034bc.png)
When testing the data source, the error is "1. Azure Monitor: Cannot connect to Azure Monitor REST API. 2. Azure Log Analytics: Cannot connect to Azure Log Analytics REST API."
![image](https://user-images.githubusercontent.com/29113353/68641669-b5e5f500-055f-11ea-9935-9630ba99d305.png)

**What you expected to happen**:
Be able to see Default Subscriptions within the data source.
![image](https://user-images.githubusercontent.com/29113353/68642122-1c1f4780-0561-11ea-9449-30cb82326f74.png)
Be able to test the data source successfully.
![image](https://user-images.githubusercontent.com/29113353/68642062-de222380-0560-11ea-8bdc-b2b7883c9fe6.png)

**How to reproduce it**:
Within the values.yaml file Azure Monitor data source added
```yaml
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Azure Monitor
      type: grafana-azure-monitor-datasource
      url: /api/datasources/proxy/2
      access: proxy
      isDefault: true
      jsonData:
        cloudName: azuremonitor
        subscriptionId: <removed>
        tenantId: <removed>
        clientId: <removed>
        logAnalyticsDefaultWorkspace: grafana-workspace
        azureLogAnalyticsSameAs: true
        keepCookies: []
      secureJsonData:
        clientSecret: ""
      editable: false
```
Using Helm 3
`helm install grafana --set datasources.datasources.yaml.datasources[0].secureJsonData="password" stable/grafana -f values.yaml`
