### ISSUE TITLE
[jenkins] is there a way to persist jenkins data without a PVC?

### ISSUE THREAD

**Issue by pswenson** [helm/charts#1879]
**Is this a request for help?**:

is there a way to configure the jenkins chart to store data in a host volume rather than a persistent volume claim?  We use openstack w/o persistent vol claim support.

**Version of Helm and Kubernetes**:

1.5.6k8s, 2.5.0helm

**Which chart**:

jenkins

**Comment by fabiormoura** [comment]
Hi @pswenson,

You need to create a `PersistentVolume` with `hostPath` and `storageClassName` separately and let the Jenkins chart create the PVC for you. Hope the example below helps you out.

### Create a PersistentVolume with a storageClassName and hostPath before deploying the Jenkins chart
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
spec:
  storageClassName: jenkins-pv
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/k8s_volume/jenkins_home"
```

### Deploy the Jenkins chart with these overrides

```yaml
Persistence:
  Enabled: true
  # Use the same storage class defined in the PersistentVolume 
  StorageClass: jenkins-pv
  Size: 8Gi
```

**Comment by pswenson** [comment]
Thanks.  I tried deploying this:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
spec:
  selector:
      jenkins: master
  storageClassName: jenkins-pv
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/jenkins"
```

but get this error:

``` 
kubectl create -f ./jenkins-pv.yaml
error: error validating "./jenkins-pv.yaml": error validating data: [found invalid field selector for v1.PersistentVolumeSpec, found invalid field storageClassName for v1.PersistentVolumeSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

I'm reading up on persistent volumes and storage class names but most doc assumes AWS or GCE.

**Comment by pswenson** [comment]
I just removed the `storageClassName` and `selector` like
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
spec:
#  selector:
#      jenkins: master
#  storageClassName: jenkins-pv
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/jenkins"
```

the PV was created... now seeing if I can actually get it to work with the chart...
