### ISSUE TITLE
[stable/jenkins] PodLabel missing

### ISSUE THREAD

**Issue by petterl** [helm/charts#18804]
**Describe the bug**
When networkPolicy.enables is true pods cannot reach master.

**Version of Helm and Kubernetes**:
kube: v1.15.5
helm: v2.14.1

**Which chart**:
jenkins

**What happened**:
When networkPolicy.enables is true a NetworkPolicy is created with podSelector 
"jenkins/{{ .Release.Name }}-{{ .Values.agent.componentName }}": "true"
But new pods created only have the label "Jenkins": "slave" set. This means new pod cannot reach the master.

**What you expected to happen**:
the current label that the podtemplate gets seams to be default value, so we need to set the correct label in the podtemplate in config.xml or or the podSelector fort the NetworkPolicy needs to be updated.

Eg add this to config.yaml
``` yaml
      <readTimeout>0</readTimeout>
+      <podLabels>
+        <org.csanchez.jenkins.plugins.kubernetes.PodLabel>
+          <key>jenkins/{{ .Release.Name }}-{{ .Values.agent.componentName }}</key>
+          <value>true</value>
+        </org.csanchez.jenkins.plugins.kubernetes.PodLabel>
+      </podLabels>
      <usageRestricted>false</usageRestricted>
      <maxRequestsPerHost>32</maxRequestsPerHost>
```

I don't know what the reasoning has been here since I do not understand how to get it to work currently.

**How to reproduce it** (as minimally and precisely as possible):
Set networkPolicy.enabled to true and try building with a default template-

**Anything else we need to know**:
While updating a possibility to open for external agents would be nice. 

like the value:
``` yaml
  networkPolicy:
    agentFrom:
      - ipBlock:
          cidr: 192.168.6.32/32
      - ipBlock:
          cidr: 192.168.6.181/32
```
With addition to the jenkins-master-networkpolicy.yaml

``` yaml
{{- if .Values.jenkins.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ .Values.jenkins.networkPolicy.apiVersion }}
metadata:
  name: "{{ .Release.Name }}-{{ .Values.jenkins.master.componentName }}-agents"
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.jenkins.master.componentName }}"
spec:
  podSelector:
    matchLabels:
      "app.kubernetes.io/component": "{{ .Values.jenkins.master.componentName }}"
      "app.kubernetes.io/instance": "{{ .Release.Name }}"
  ingress:
    # Allow inbound connections from external slaves
    - from:
{{- if .Values.jenkins.networkPolicy.agentFrom  }}
{{ toYaml .Values.jenkins.networkPolicy.agentFrom | indent 6 }}
{{- end }}
      ports:
      - port: {{ .Values.jenkins.master.slaveListenerPort }}
{{- end }}
```
