### ISSUE TITLE
[stable/prometheus-operator] Ability to configure namespace

### ISSUE THREAD

**Issue by arruzk** [helm/charts#18837]
I would like to create a chart which will depend on `prometheus-operator` and I want to install prometheus in a separate namespace.
```yaml
dependencies:
  - name: prometheus-operator
    version: "7.2.0"
    repository: "@stable"
```
Currently it's not possible to specify different namespace for prometheus (`namespace: {{ $.Release.Namespace }}`).

Is it a better way than fork the chart and change it to something like `namespace: {{ .Values.global.prometheusNamespace }}`?
