### ISSUE TITLE
stable/mongodb Error: release mongodb failed: Ingress.extensions "mongodb" is invalid

### ISSUE THREAD

**Issue by ksingh7** [helm/charts#18860]
**Describe the bug**
```
Error: release mongodb failed: Ingress.extensions "mongodb" is invalid: spec.rules[0].host: Invalid value: "map[name:mongodb.local path:/]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Version of Helm and Kubernetes**:
```
helm version --tiller-namespace amq-streams
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/mongodb

**What happened**:

While installing stable/mongodb with ingress.enabled = true , encountering the following error message

Error: release mongodb failed: Ingress.extensions "mongodb" is invalid: spec.rules[0].host: Invalid value: "map[name:mongodb.local path:/]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**What you expected to happen**:
As per the documentation, mongodb service should be installed and must be exposed (after setting up nginx-ingress

**How to reproduce it** (as minimally and precisely as possible):
`` values.yaml ``

```
mongodbRootPassword: admin
mongodbUsername: admin
mongodbPassword: admin
mongodbDatabase: twitter_stream
service.name: mongodb
persistence.storageClass: gp2
persistence.size: 1G
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - name: mongodb.local
    path: '/'
```

```
helm install --name mongodb -f values.yaml  stable/mongodb --tiller-namespace amq-streams
```

**Full Debug Log **
```
$ helm install --name mongodb -f values_mongodb.yaml  stable/mongodb --tiller-namespace amq-streams --debug
[debug] Created tunnel using local port: '58185'

[debug] SERVER: "127.0.0.1:58185"

[debug] Original chart version: ""
[debug] Fetched stable/mongodb to /Users/karasing/.helm/cache/archive/mongodb-5.16.1.tgz

[debug] CHART PATH: /Users/karasing/.helm/cache/archive/mongodb-5.16.1.tgz

Error: release mongodb failed: Ingress.extensions "mongodb" is invalid: spec.rules[0].host: Invalid value: "map[name:mongodb.local path:/]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
$
```
