### ISSUE TITLE
[stable/stolon] PR 17036 introduces a bug in postgres config

### ISSUE THREAD

**Issue by raqqun** [helm/charts#18884]
**Describe the bug**

Latest 1.4.0 stable/stolon version introduces a bug in the postgres config. The ssl parameter gets a "null" string value but postgres expects a Boolean. 

The problem came from the `create-cluster-job` and `update-cluster-spec-job` manifests. 

The other, rather bizarre, think was that the keeper pods didn't restart at all, they just kept crashing with the log below. 

**Version of Helm and Kubernetes**:
Helm: 2.x
Kubernetes: 1.14.x

**Which chart**:
stable/stolon

**What happened**:

```
2019-11-14T13:46:38.197Z	INFO	postgresql/postgresql.go:307	starting database
2019-11-14 13:46:38.208 UTC [13834] LOG:  parameter "ssl" requires a Boolean value
2019-11-14 13:46:38.208 UTC [13834] FATAL:  configuration file "/stolon-data/postgres/stolon-temp-postgresql.conf" contains errors
2019-11-14T13:46:38.398Z	ERROR	cmd/keeper.go:1083	failed to start instance	{"error": "postgres exited unexpectedly"}
2019-11-14T13:46:40.274Z	ERROR	cmd/keeper.go:641	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

helm install stable/stolon

**Anything else we need to know**:

**Comment by raqqun** [comment]
Just for info i was able to make it work by changing the `pgParameters` of `create-cluster-job` and `update-cluster-spec-job`  the PR author made a mistake on this two files.

**Comment by zbikmarc** [comment]
This affects us too however we are not setting `pgParameters` at all and error is exactly same.

**Comment by zbikmarc** [comment]
`/stolon-data/postgres/stolon-temp-postgresql.conf` generated by fairly standard/default `values.yaml`

```
include 'postgresql.conf'
ssl_ca_file = 'null'
ssl_key_file = ''
hot_standby = 'on'
ssl_cert_file = ''
ssl = ''
wal_keep_segments = '8'
wal_level = 'replica'
unix_socket_directories = '/tmp'
listen_addresses = '127.0.0.1,10.42.5.43'
port = '5432'
max_replication_slots = '20'
max_wal_senders = '47'
synchronous_standby_names = ''
```

**Comment by zbikmarc** [comment]
[This comment](https://github.com/helm/charts/pull/17036/files#r336731544 ) (conversation under `stable/stolon/templates/hooks/update-cluster-spec-job.yaml `)  mentions root cause of this issue.  
Problem is that exactly same piece of code is used for create and update step. As a result we are ending with: 
```json
'{ "initMode": "new", "pgParameters": {"ssl":null,"ssl_ca_file":"null","ssl_cert_file":null,"ssl_key_file":null}  }'
```
 what renders config posted by me above.

**Comment by zbikmarc** [comment]
Looks like this line is problematic:
https://github.com/helm/charts/blob/master/stable/stolon/templates/hooks/update-cluster-spec-job.yaml#L45

To be exact this part of code:
```
'{ {{- range $key, $value := .Values.clusterSpec }} {{ $key | quote }}: {{ if typeIs "string" $value }} {{ $value | quote }} {{ else }} {{ $value }} {{ end }}, {{- end }} {{ if .Values.tls.enabled }}"pgParameters": {{- $pgParameters := .Values.pgParameters -}}{{ $all := set $pgParameters "ssl" "on" }}{{ $all := set $all "ssl_cert_file" "/certs/serverCrt.crt" }} {{ $all := set $all "ssl_key_file" "/certs/serverKey.key" }}{{ $all := set $all "ssl_ca_file" "/certs/rootCa.crt" }}{{ toJson $all }} {{ else }}"pgParameters": {{- $pgParameters := .Values.pgParameters -}}{{ $all := set $pgParameters "ssl" "false" }}{{ $all := set $all "ssl_cert_file" nil }} {{ $all := set $all "ssl_key_file" nil }}{{ $all := set $all "ssl_ca_file" nil }}{{ toJson $all }}{{ end}}}'
```
is evaluated despite `.Values.tls.enabled` is set to `false`. Due to this we have
```
map[ssl:<nil> ssl_ca_file:null ssl_cert_file:<nil> ssl_key_file:<nil>]
```
What is more interesting, removing `if... else` from one file is not enough as this overwrites it anyway.
Really problematic part is: `ssl:<nil>`.

I am creating PR to hotfix this but it should be probably done in better way.

**Comment by zbikmarc** [comment]
Looks like `$pgParameters := .Values.pgParameters` is working not on copy of variable but on pointer to it. As a result when changes to `$pgParameters` are done they affect also ` .Values.pgParameters`

Debug steps:
1. Edit either `update-cluster-spec-job.yaml` or `create-cluster-job.yaml` file
2. Add those two lines at beginning of file
```
{{ $temporary := .Values.pgParameters }}
temporary_var: {{ $temporary | toJson }}
```
3. Add this line at the end of file
```
temporary_var: {{ $temporary | toJson }}
```
4. Execute `helm template` on stolon template
5. Result you will see (for `update-cluster-spec-job.yaml` file):
```yaml
---
# Source: stolon/templates/hooks/update-cluster-spec-job.yaml

temporary_var: {}

apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-stolon-update-cluster-spec
  labels:
    app: stolon
    chart: stolon-1.4.1
    release: release-name
    heritage: Tiller
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: release-name-stolon
        release: release-name
    spec:
      restartPolicy: OnFailure
      serviceAccountName: release-name-stolon
      containers:
        - name: release-name-stolon-update-cluster-spec
          image: "sorintlab/stolon:v0.13.0-pg10"
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/stolonctl"]
          args:
            - update
            - --cluster-name=release-name-stolon
            - --store-backend=kubernetes
            - --kube-resource-kind=configmap
            - -p
            - '{ "pgParameters": {"ssl":"off","ssl_ca_file":null,"ssl_cert_file":null,"ssl_key_file":null}}'

temporary_var: {"ssl":"off","ssl_ca_file":null,"ssl_cert_file":null,"ssl_key_file":null}
```

Even more interesting thing is that when exact same change will be applied to both mentioned files, first print for `create-cluster-job.yaml` will be 
```
temporary_var: {"ssl":"off","ssl_ca_file":null,"ssl_cert_file":null,"ssl_key_file":null}
```
instead of:
``` 
temporary_var: {}
```
