### ISSUE TITLE
[stable/sonarqube] Default plugins are not installed

### ISSUE THREAD

**Issue by fungiboletus** [helm/charts#18947]
Looks like running `helm install stable/sonarqube` without any custom value will install sonarqube without the default plugins.

**Comment by fungiboletus** [comment]
Removing the following in `deployment.yaml` fixes the problem:

```yaml
            - mountPath: /opt/sonarqube/extensions/plugins
              name: sonarqube
              subPath: plugins
```

It works if you don't care about installing custom plugins.
