### ISSUE TITLE
[stable/graylog] Deprecated API version for Kubernetes 1.16

### ISSUE THREAD

**Issue by CaptainKrby** [helm/charts#18997]
Hello, I recently updated the kubernetes cluster (1.16) which hosted Graylog and during a redeploy one day later I was confronted with this error:

`Failed to install app graylog. Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"] `

I suspect the mongo and elasticsearch charts that still have deprecated fields (apps/v1beta1).
Could you update the Graylog chart to link them with the version that supports kubernetes 1.16 ?

Thanks

**Comment by juliohm1978** [comment]
I'm having the same problem. Using helm3 with chart version 1.5.0.

A `helm diff` puts the blame on the mongodb replicaset.

```diff
default, graylog-mongodb-replicaset, StatefulSet (apps) has been added:
+ # Source: graylog/charts/mongodb-replicaset/templates/mongodb-statefulset.yaml
+ apiVersion: apps/v1beta2
```

I do, however, have the chart configured to NOT install elasticsearch or mongo.

```yaml
tags:
  # If true, this chart will install Elasticsearch from requirement dependencies
  install-elasticsearch: false
  # If true, this chart will install MongoDB replicaset from requirement dependencies
  install-mongodb: false
```
That seems to have no effect.
