### ISSUE TITLE
[stable/postgresql] make chart work on ARM / RPi

### ISSUE THREAD

**Issue by soapergem** [helm/charts#19132]
**Is your feature request related to a problem? Please describe.**
I have a K8S cluster running on some Raspberry Pis; I want to run Postgres but the chart for Postgres doesn't work on ARM architectures.

**Describe the solution you'd like**
There are other stable charts that offer options for running on ARM architectures, e.g. nfs-client-provisioner lets you set the `image.repository` variable to a different image that ends in a `-arm` suffix, and then things work.

**Additional context**
It seems there are some Postgres Docker images out there built for ARM; however the Postgres chart uses some derivative images by Bitnami. And apparently Bitnami didn't make any derivatives for ARM.

**Comment by carrodher** [comment]
Hi, in the short term there are no plans from Bitnami to support ARM architectures in the images. But one thing is the chart and other the images. 
From chart version 4.0.0, it is possible to use this chart with the Docker Official PostgreSQL image. Besides specifying the new Docker repository and tag, it is important to modify the PostgreSQL data directory and volume mount point. Basically, the PostgreSQL data dir cannot be the mount point directly, it has to be a subdirectory.
```
helm install --name postgres \
             --set image.repository=postgres \
             --set image.tag=10.6 \
             --set postgresqlDataDir=/data/pgdata \
             --set persistence.mountPath=/data/ \
             stable/postgresql
```
Using above installation parameters you can override the image repository `bitnami/postgresql` by `postgres` and the Bitnami tag `11.6.0-debian-9-r0` by the Docker Inc. one `11.6`.

It seems there are a Docker Inc. Postgres image that supports ARM: https://hub.docker.com/r/arm64v8/postgres; you can try using this image with the above parameters. Please, take into account that this configuration was not tested in our side so feel free to create PRs or whatever is needed to make this chart compatible with this ARM image if needed.

**Comment by soapergem** [comment]
Looking at the chart, it seems there's also an init-container running `bitnami/minideb` which is not compatible with ARM machines. Are there similar ready-made alternatives to that?

**Comment by carrodher** [comment]
Those are the [commands that this container execute](https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml#L85): `mkdir`, `chmod`, `find` and `xargs`; any image with these packages is valid. We used _minideb_ because it is released on a daily basis to avoid CVEs and it is light, but you can use other options just using: `--set volumePermissions.image.repository` and `--set volumePermissions.image.repository.tag`

**Comment by soapergem** [comment]
Awesome, I got it to work. Thanks for your help. In addition to running it on a Raspberry Pi cluster, I'm also using a NAS file share for persistent storage. I'm using another stable chart (nfs-client-provisioner) to make that work. I'm going to leave my configuration YAML here for anyone else who might be wondering how to make it all work:

```
image:
  repository: arm32v7/postgres
  tag: 11.6

persistence:
  mountPath: /data
  size: 20Gi
  storageClass: nfs-client

postgresqlDataDir: /data/pgdata

volumePermissions:
  image:
    repository: arm32v7/alpine
    tag: "3.10"

securityContext:
  fsGroup: 999
  runAsUser: 999

livenessProbe:
  initialDelaySeconds: 300

readinessProbe:
  initialDelaySeconds: 300
```
