### ISSUE TITLE
[stable/prometheus-operator] Prometheus and Grafana periodically restart and loose data

### ISSUE THREAD

**Issue by Alirun** [helm/charts#19153]
**Describe the bug**
Prometheus and Grafana periodically restart and loose all collected data and configuration

Once in approximately 10-20 days prometheus and grafana restart and I see no dashboard, data and notification channels.
Basically I loose all the monitoring settings I have.

I already solved Grafana dashboard problem by adding it as ConfigMap and labelling it, so Grafana picks is up on restarts, but still my main notification channel is not configured to "wake up" after restarts and I loose it.

Also I loose all collected data. Tried to fix it with setting `prometheus` and `alertmanager` persistent disk, did not help.

I think I'm doing something wrong. Could you please point me If I miss something in persistence configuration?

Thank you!

**Current setup**
***ConfigMap***
ConfigMap with dashboard for Grafana

***Persistence***
I have set up `values.yaml` as so:
Persistent disk for prometheus
```
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate: ...
```

Persistent disk for alertmanager
```
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate: ...
```

**Version of Helm and Kubernetes**:
Helm: v2.15.0
Kubernetes Client: v1.14.8
Kubernetes Server: v1.13.11-gke.14

**Which chart**:
stable/prometheus-operator

**Comment by vsliouniaev** [comment]
Here's a sample working config - your configuration may have different values but this is the correct config for the helm chart - see the configuration here: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L1608-L1615
```
  prometheus:
    prometheusSpec:      
      retentionSize: "325GB"
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: standard-disk
            resources:
              requests:
                storage: 500Gi
```

**Comment by Alirun** [comment]
@vsliouniaev Thank you, for your response

This is my config on `prometheus` storage
```
storageSpec:
      volumeClaimTemplate:
        spec:
          volumeName: pv-prometheus-0
          accessModes: ["ReadWriteOnce"]
          storageClassName: standard
          resources:
            requests:
              storage: 20Gi
```
I think I loose old data because I have `retention` set to default 10 days. It's ok than.

My config for `alertmanager` storage is
```
storage:
      volumeClaimTemplate:
        spec:
          # Name of the PV you created beforehand
          volumeName: pv-alertmanager-0
          accessModes: ["ReadWriteOnce"]
          # StorageClass should match your existing PV's storage class
          storageClassName: standard
          resources:
            requests:
              # Size below should match your existing PV's size
              storage: 20Gi
```

I guess it has nothing to do with Grafana notification channel? Because my main problem is I loose Grafana notification channel, so I'm not informed about alerts happened in Grafana.
