### ISSUE TITLE
Prometheus-Operator Prometheus CRD storage 

### ISSUE THREAD

**Issue by cyperplex** [helm/charts#19162]
Hi Ive created a Prometheus server via the Prometheus object created by the CRD included with the Prometheus chart.

There is no persistent storage being created with the instance, Ive tried the following
  storageSpec :
    storage: 10Gi

But it doesn't work, i can see in my Prometheus Server spun up in the monitoring namespace has a storage volume attached as per the following values set when installing the Prometheus operator chart

    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

My issue is around the Prometheus server Ive created in a username space using the operator Prometheus extension, there is no storage assigned to it as its losing data when its restarted.

**Comment by vsliouniaev** [comment]
Here's a sample working config - your configuration may have different values but this is the correct config for the helm chart - see the configuration here: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L1608-L1615
```
  prometheus:
    prometheusSpec:      
      retentionSize: "325GB"
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: standard-disk
            resources:
              requests:
                storage: 500Gi
```
