### ISSUE TITLE
[charts/stable/nginx-ingress] fullnameOverride not resulting in expected name

### ISSUE THREAD

**Issue by Office-Manager** [helm/charts#19163]
**Describe the bug**
Deploying nginx-ingress version 0.30.0 with the following
```

nginx-ingress:
  nameOverride: name-override
  fullnameOverride: fullname-override
  imagePullSecrets:
    - name: registry
  rbac:
    create: true
  serviceAccount:
    create: true
  controller:
    name: controller
```
When running helm diff to check what the deployed outcome would be I am getting this 

```

 # Source: project-charts/charts/nginx-ingress/templates/controller-deployment.yaml
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   labels:
     app: name-override
     chart: nginx-ingress-0.30.0
     component: "controller"
     heritage: Tiller
     release: project-release-chart
   name: project-release-chart-name-override-controller
 spec:
   replicas: 2
   revisionHistoryLimit: 10
   strategy:
     {}
     
   minReadySeconds: 0
   template:
     metadata:
       labels:
         app: name-override
         component: "controller"
         release: project-release-chart
```

My understanding of the _helpers.tpl would be that from this block of code 
```

{{- define "nginx-ingress.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

If the fullnameOverride was passed in that the release-name section would never be reached in the code.
but it appears as though it's getting the `nameOverride` but not the `fullnameOverride`

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
charts/stable/nginx-ingress

**What happened**:

The name of the application deployed is not recognising the fullnameOverride and deploying the release syntax name instead which is troublesome 
`   name: project-release-chart-name-override-controller`
**What you expected to happen**:
Expected fullnameOverride to be used as the name
`   name: fullname-override-controller`

**How to reproduce it** (as minimally and precisely as possible):
Easiest way to reproduce 

requirements.yaml
```
dependencies:
- name: nginx-ingress
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "~0.30.0"
```

values.yaml
```
nginx-ingress:
  nameOverride: name-override
  fullnameOverride: fullname-override
```

`helm dep up`
`helm template .`

**Anything else we need to know**:
