### ISSUE TITLE
[stable/newrelic-infrastructure] Unable to set more than one pod labels

### ISSUE THREAD

**Issue by enver** [helm/charts#19210]
**Describe the bug**
Setting more than one label in podLabels generates invalid daemonset spec due to wrong indentation.

**Version of Helm and Kubernetes**:
Any

**Which chart**:
stable/newrelic-infrastructure

**What happened**:
I've added 2 labels to values.yaml file:
```
newrelic-infrastructure:
  podLables:
    foo: bar
    baz: qux
```

and generated spec looks like this:
```
  template:
    metadata:
      labels:
        app: newrelic-infrastructure
        release: release-name
        foo: bar
baz: qux
```

**What you expected to happen**:
Generated spec should look like:
```
  template:
    metadata:
      labels:
        app: newrelic-infrastructure
        release: release-name
        foo: bar
        baz: qux
```

**How to reproduce it** (as minimally and precisely as possible):
Add 2 or more labels to podLabels and try to install chart, see above.

**Anything else we need to know**:
Indent function is missing on this line: https://github.com/helm/charts/blob/c5653815e38714d953827a2a7f96ee44c5341389/stable/newrelic-infrastructure/templates/daemonset.yaml#L24
