### ISSUE TITLE
[stable/grafana] User invitation email provides URL localhost:3000

### ISSUE THREAD

**Issue by latituder** [helm/charts#19220]
I have ingress enabled.
When using email to invite new grafana user, the email contains localhost:3000;

tried to add:
server:
    # protocol: http
    http_port: 80
    domain: [my ingress address]

the pod cannot startup, because:
"Server shutdown" logger=server reason="listen tcp 0.0.0.0:80: bind: permission denied"

check the Grafana doc, suggest to run below command, but cannot find a place in values.yaml to inject a command before grafana startup.
sudo setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server

so:
- is there a way, to run a command in container shell, before grafana service start?
or
- is there a way, to customize the user invitation email URL?

**Comment by daixiang0** [comment]
The doc is https://grafana.com/docs/installation/configuration/#http-port.
It need sudo to run cmd in container but grafana run as grafana user.
You can do below change to support this:
```
securityContext:
  runAsUser: 0 
  fsGroup: 0

command:
- "setcap"
- "'cap_net_bind_service=+ep'"
- "/usr/sbin/grafana-server &&"
- "sh"
- "/run.sh" 
```
