### ISSUE TITLE
[stable/rabbitmq-ha] Has problem with prometheus

### ISSUE THREAD

**Issue by korjavin** [helm/charts#19286]
**Describe the bug**
helm install returns:
```
Error: validation failed: [unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

**Version of Helm and Kubernetes**:
```
helm
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```
```
kubectl
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.17", GitCommit:"27b48e2b4c9535d185ec945c6a513537e4d116cf", GitTreeState:"clean", BuildDate:"2019-10-21T20:10:26Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:

stable/rabbitmq-ha
**What happened**:
Failed to install

**What you expected to happen**:

I expected to have chart installed

**How to reproduce it** (as minimally and precisely as possible):
values.yaml:
```
## Prometheus Plugin                                                                           
## Ref: https://www.rabbitmq.com/prometheus.html                                               
rabbitmqPrometheusPlugin:                                                                      
  enabled: true                                                                                
                                                                                               
  ## metrics port, overrides configuration:                                                    
  ## prometheus.tcp.port                                                                       
  port: 15692                                                                                  
                                                                                               
  ## metrics path, overrides configuration:                                                    
  ## prometheus.path                                                                           
  path: /metrics                                                                               
                                                                                               
                                                               
#                                                                                              
## Kubernetes Cluster Domain                                                                   
clusterDomain: my.domain
                                                                                               
prometheus:                                                                                    
  ## Configures Prometheus Exporter to expose and scrape stats.                                
  exporter:                                                                                    
    enabled: true                                                                              
    env: {}                                                                                    
    image:                                                                                     
      repository: kbudde/rabbitmq-exporter                                                     
      tag: v0.29.0                                                                             
      pullPolicy: IfNotPresent                                                                 
                                                                                               
    ## Port Prometheus scrapes for metrics                                                     
    port: 9090                                                                                 
                                                                                               
  ## Prometheus is using Operator.  Setting to true will create Operator specific resources like ServiceMonitors and Alerts
  operator:
    ## Are you using Prometheus Operator? [Blog Post](https://coreos.com/blog/the-prometheus-operator.html)
    enabled: true

    
    serviceMonitor:                                                                            
      ## Interval at which Prometheus scrapes RabbitMQ Exporter                                
      interval: 10s        
```
