### ISSUE TITLE
[stable/kubernetes-dashboard] with ALB ingress authentication error

### ISSUE THREAD

**Issue by babysnakes** [helm/charts#19301]
**Describe the bug**

Error authenticating to dashboard when connecting through ALB ingress.

**Version of Helm and Kubernetes**:
Helm: 3
kubectl: 1.14
EKS: 
  - kubernetes 1.14
  - eks.3

**Which chart**:
stable/kubernetes-dashboard

**What happened**:

I installed `stable/kubernetes-dashboard` using the following command:

```sh
helm install kubernetes-dashboard stable/kubernetes-dashboard \
    -f dashboard-values.yaml \
    --version 1.10.1 \
    -n kube-system
```

dashboard-values.yaml looks like this:
```yaml
---
enableInsecureLogin: true
rbac:
  # FIX: DANGEROUS, remove once you learn more about authentication
  clusterAdminRole: true
service:
  type: NodePort
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
  hosts:
    - dashboard.mydomain
  paths:
    - /
    - /*
...
```

If I use the *port-forward* way of connecting I can easily authenticate (regardless of admin permissions or not). If however I try to access via http://dashboard.mydomain/ I can't authenticate, It just stays on the login page. In the js console I see:

```
Possibly unhandled rejection: {"data":"MSG_LOGIN_UNAUTHORIZED_ERROR\n","status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/v1/rbac/status","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Unauthorized","xhrStatus":"complete","resource":{}}
```

**What you expected to happen**:

I should be able to authenticate

**How to reproduce it** (as minimally and precisely as possible):

probably follow the steps above in an EKS environment configured for ALB and DNS (sample instructions for enabling ALB are [here](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html?shortFooter=true)).

**Anything else we need to know**:

Note that this is internal ALB (if it matters in any way).
