### ISSUE TITLE
[stable/traefik] Adding dashboard mandates ingress

### ISSUE THREAD

**Issue by dioguerra** [helm/charts#19326]
Setting dashboard.enable=true automatically creates an ingress manifest.

```yaml
dashboard:
  enabled: true
  # domain: "traefik.example.com"
  serviceType: ClusterIP
  service: {}
  ingress: {}
```

```
dtomasgu@dguerra-IT-CM:~/Documents/repositories/charts$ ka get ingress
NAMESPACE     NAME                          HOSTS    ADDRESS   PORTS   AGE
kube-system   prometheus-operator-grafana   stuff      80      17h
kube-system   traefik-dashboard             *          80      5m30s
```

If i want to have an internal dashboard i don't want an ingress to be created and expose it outside.
I should have a dashboard.ingress.enabled
