### ISSUE TITLE
[stable/kong] Log messages not written into files specified

### ISSUE THREAD

**Issue by will-beta** [helm/charts#19361]
**Describe the bug**

**Version of Helm and Kubernetes**:
`helm3` and `kubernetes1.14.8`

**Which chart**:
`stable/kong`

**What happened**:
With the configurations below specified, log messages like `I1204 01:54:34.753660 1 controller.go:135] successfully synced configuration to Kong` still shows up on `stderr`。
```yaml
env:
  database: "off"
  nginx_worker_processes: "1"
  proxy_access_log: /usr/local/kong/logs/proxy_access.log
  admin_access_log: /usr/local/kong/logs/admin_access.log
  admin_gui_access_log: /usr/local/kong/logs/admin_gui_access.log
  portal_api_access_log: /usr/local/kong/logs/portal_api_access.log
  proxy_error_log: /usr/local/kong/logs/proxy_error.log
  admin_error_log: /usr/local/kong/logs/admin_error.log
  admin_gui_error_log: /usr/local/kong/logs/admin_gui_error.log
  portal_api_error_log: /usr/local/kong/logs/portal_api_error.log
```

**What you expected to happen**:
Log messages like `I1204 01:54:34.753660 1 controller.go:135] successfully synced configuration to Kong` can also be able to specified to write into a file.
Additionally, I would be very appreciated if I could specify volumes on my own, so I could clean all these log files by a unified solution.

**Comment by hbagdi** [comment]
The env section you are specifying is for the `kong` or `proxy` container.
You should upgrade to a new chart version and then use `ingressController.env` section to control the output location for the `ingress-controller` pod.

**Comment by vivianforzj** [comment]
I modify the values.yaml as:

```
env:
  database: "off"
  nginx_worker_processes: "1"
  proxy_access_log: /usr/local/kong/logs/proxy_access.log
  admin_access_log: /usr/local/kong/logs/admin_access.log
  admin_gui_access_log: /usr/local/kong/logs/admin_gui_access.log
  portal_api_access_log: /usr/local/kong/logs/portal_api_access.log
  proxy_error_log: /usr/local/kong/logs/proxy_error.log
  admin_error_log: /usr/local/kong/logs/admin_error.log
  admin_gui_error_log: /usr/local/kong/logs/admin_gui_error.log
  portal_api_error_log: /usr/local/kong/logs/portal_api_error.log

ingressController:
  enabled: true
  image:
    repository: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller
    tag: 0.7.0

  # Specify Kong Ingress Controller configuration via environment variables
  env:
    proxy_access_log: /usr/local/kong/logs/proxy_access.log
    admin_access_log: /usr/local/kong/logs/admin_access.log
    admin_gui_access_log: /usr/local/kong/logs/admin_gui_access.log
    portal_api_access_log: /usr/local/kong/logs/portal_api_access.log
    proxy_error_log: /usr/local/kong/logs/proxy_error.log
    admin_error_log: /usr/local/kong/logs/admin_error.log
    admin_gui_error_log: /usr/local/kong/logs/admin_gui_error.log
    portal_api_error_log: /usr/local/kong/logs/portal_api_error.log

```

And in the kong pod, for container kong, it has corresponding log files, but container ingress-controller still has no such log files. 

I described the pod, and found that container ingress-controller has enviroments as:

```
    Environment:
      POD_NAME:                          r-kong-kong-7f8c477646-fd4qr (v1:metadata.name)
      POD_NAMESPACE:                     default (v1:metadata.namespace)
      CONTROLLER_ADMIN_ACCESS_LOG:       /usr/local/kong/logs/admin_access.log
      CONTROLLER_ADMIN_ERROR_LOG:        /usr/local/kong/logs/admin_error.log
      CONTROLLER_ADMIN_GUI_ACCESS_LOG:   /usr/local/kong/logs/admin_gui_access.log
      CONTROLLER_ADMIN_GUI_ERROR_LOG:    /usr/local/kong/logs/admin_gui_error.log
      CONTROLLER_PORTAL_API_ACCESS_LOG:  /usr/local/kong/logs/portal_api_access.log
      CONTROLLER_PORTAL_API_ERROR_LOG:   /usr/local/kong/logs/portal_api_error.log
      CONTROLLER_PROXY_ACCESS_LOG:       /usr/local/kong/logs/proxy_access.log
      CONTROLLER_PROXY_ERROR_LOG:        /usr/local/kong/logs/proxy_error.log
```

It seems that these environments do not take effect.  Kong chart version: kong-0.31.2. Am I using a right kong chart version? Or something is wrong with my env settings? Thank you @hbagdi

**Comment by vivianforzj** [comment]
@hbagdi I modify the ingressController env settings as followings:

```
ingressController:
  enabled: true
  image:
    repository: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller
    tag: 0.7.0

  # Specify Kong Ingress Controller configuration via environment variables
  env:
    LOG_DIR: /var/log/ingress_controller
    LOGTOSTDERR: false
    ALSOLOGTOSTDERR: false
    STDERRTHRESHOLD: "2"
    V: 0
```

and when I descirbed the kong pod, I saw the following env for ingress-controller container:
```
    Environment:
      POD_NAME:                    r-kong-kong-5444b7fdc4-h7ksw (v1:metadata.name)
      POD_NAMESPACE:               default (v1:metadata.namespace)
      CONTROLLER_ALSOLOGTOSTDERR:  false
      CONTROLLER_LOGTOSTDERR:      false
      CONTROLLER_LOG_DIR:          /var/log/ingress_controller
      CONTROLLER_STDERRTHRESHOLD:  2
      CONTROLLER_V:                0
```

but the logs are still writen to stdout rather than to file. Is something wrong with the current settings? Thank you.
