### ISSUE TITLE
stable/datadog dedicated containers needs more clarification

### ISSUE THREAD

**Issue by matt-canty-dragon** [helm/charts#19373]
**Describe the bug**
Unclear on how to use dedicated containers, and where user may fail.

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
stable/datadog

**What happened**:
After setting [`daemonset.useDedicatedContainers: true`](https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L512) the settings I added to [daemonset.customAgentConfig](https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L690) no longer worked.

**What you expected to happen**:
Set `useDedicatedContainers: true` and everything would carry on, as normal, but across multiple containers.

**How to reproduce it**
Set `useDedicatedContainers: true` and add some custom log processing rule:
```
daemonset:
  customAgentConfig:
    logs_config:
      processing_rules:
        - type: mask_sequences
          name: test
          pattern: (customer\W)\d+
          replace_placeholder: "[customer ID masked]"
```

**Anything else we need to know**:
After investigation I realise that it is due to the [`datadog-yaml`](https://github.com/helm/charts/blob/master/stable/datadog/templates/container-agents.yaml#L194-L198) mount which is available on the _all-in-one-container_ version does not have a respective mount for individual containers - [see here no mount of datadog yaml](https://github.com/helm/charts/blob/master/stable/datadog/templates/container-trace-agent.yaml#L24-L26).

It was not clear to me that dedicated containers would stop the custom agent config being used.

This makes sense now, but I think it should be made clear [here](https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L508-L510) _or_ there should be a way of declaring a datadog.yaml config _per container_. 

My resolution now is to revert and use one big container, so that I may continue to make use of the easier-to-read syntax of YAML to configure my agent.
