### ISSUE TITLE
[stable/drone] BitBucket Cloud as source control provider doesn't work.

### ISSUE THREAD

**Issue by Wilson13** [helm/charts#19392]
**Describe the bug**
BitBucket Cloud as source control provider doesn't work.

**Version of Helm and Kubernetes**:
Helm: v3.0.0
K8s: 1.16.2-do.0

**Which chart**:
stable/drone

**What happened**:
OAuth doesn't work.

**What you expected to happen**:
Bitbucket OAuth asking to grant access.

**How to reproduce it** (as minimally and precisely as possible):
Deploy stable/drone helm chart with following value.yml

```
sourceControl: 
  provider: bitbucketCloud
  github:
    clientID: xxxx
    clientSecretKey: clientSecret
    clientSecretValue: xxxx
  bitbucketCloud:
    clientID: xxxxx
    clientSecretKey: clientSecret
    clientSecretValue: xxxx
  server:
    host: xxxx
    protocol: http
```

**Anything else we need to know**:
If I change the source control to github, it works.

I have deployed another Drone Server using docker instead of helm chart, Bitbucket OAuth works there.
