### ISSUE TITLE
This dashboard cannot be saved from Grafana's UI since it has been provisioned from another source.

### ISSUE THREAD

**Issue by zhouying370481** [helm/charts#19390]
Hi，I'am  using helm install prometheus-operator，it works well. but when i  make changes to a provisioned dashboard. When you click Save, Grafana has errors: 
```
This dashboard cannot be saved from Grafana's UI since it has been provisioned from another source. Copy the JSON or save it to a file below. Then you can update your dashboard in corresponding provisioning source.
See documentation for more information about provisioning.
File path: k8s-resources-cluster.json
```
I follow Grafana documenttation :  allowUiUpdates is configured to ture.
this is config file:

```
apiVersion: v1
data:
  provider.yaml: |-
    apiVersion: 1
    providers:
    - name: 'sidecarProvider'
      orgId: 1
      folder: ''
      type: file
      editable: true
      allowUiUpdates: true
      disableDeletion: true
      options:
        path: /tmp/dashboards
kind: ConfigMap
```
how to fixed it .tks
