### ISSUE TITLE
stable/sematext-agent/OWNERS has random github users as approvers

### ISSUE THREAD

**Issue by fejta** [helm/charts#19410]
Please ensure that the people in OWNERS files are repo collaborators and/or org members:
https://github.com/hakman/charts/blob/4bf26601862700c2da25a82a2ee5aa6f7a2c0edf/stable/sematext-agent/OWNERS#L1-L3

Reviewers and approvers need to be at least repo collaborators so prow can assign them people to PRs and issues.

```yaml
{
 insertId: "hhiw19fbvqc7l"  
 jsonPayload: {
  author: "hakman"   
  component: "hook"   
  error: "could not request a PR review from the following user(s): megastef."   
  event-GUID: "80a28080-1774-11ea-9338-91e06ef29c1c"   
  event-type: "pull_request"   
  file: "prow/hook/events.go:182"   
  func: "k8s.io/test-infra/prow/hook.(*Server).handlePullRequestEvent.func1"   
  level: "error"   
  msg: "Error handling PullRequestEvent."   
  org: "helm"   
  plugin: "blunderbuss"   
  pr: 19406   
  repo: "charts"   
  url: "https://github.com/helm/charts/pull/19406"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-12-05T15:32:59.571687172Z"  
 resource: {
  labels: {…}   
  type: "container"   
 }
 severity: "ERROR"  
 timestamp: "2019-12-05T15:32:55Z"  
}
```

ref https://github.com/helm/charts/pull/19406
