### ISSUE TITLE
hazelcast has non-collaborators in OWNERS

### ISSUE THREAD

**Issue by fejta** [helm/charts#19442]
ref #19403 

```yaml
 jsonPayload: {
  author: "devOpsHelm"   
  component: "hook"   
  error: "could not request a PR review from the following user(s): googlielmo, mesutcelik."   
  event-GUID: "e9d2c580-176d-11ea-9bdc-a75c937b9b3e"   
  event-type: "pull_request"   
  file: "prow/hook/events.go:182"   
  func: "k8s.io/test-infra/prow/hook.(*Server).handlePullRequestEvent.func1"   
  level: "error"   
  msg: "Error handling PullRequestEvent."   
  org: "helm"   
  plugin: "blunderbuss"   
  pr: 19403   
  repo: "charts"   
  url: "https://github.com/helm/charts/pull/19403"   
 }
```
/assign @mattfarina @viglesiasce @prydonius
