### ISSUE TITLE
[stable/jenkins] External ELB is not created

### ISSUE THREAD

**Issue by t5unamie** [helm/charts#19455]
**Describe the bug**
Running the following helm chart command

helm install master stable/jenkins -f jenkins-values.yaml --debug

The Chart does not create an ELB.

Content
```
master:
  ingress:
    enabled: true
    apiVersion: extensions/v1beta1
    hostName: jenkins.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
```

Down this output. with no errors.
```
1. Get your 'admin' user password by running:
  printf $(kubectl get secret --namespace default master-jenkins -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode);echo
2. Visit http://jenkins.example.com
3. Login with the password from step 1 and the username: admin
```
System is generating but not applying this service.
```
# Source: jenkins/templates/jenkins-master-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-1.9.8"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "master"
    "app.kubernetes.io/component": "jenkins-master"
  annotations:
    kubernetes.io/ingress.class: nginx
  name: master-jenkins
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: master-jenkins
          servicePort: 8080
    host: "jenkins.example.com"
```
as shown by the output below.
```
kubectl get all
NAME                                  READY   STATUS    RESTARTS   AGE
pod/master-jenkins-5784cf6bbb-96cpn   1/1     Running   0          8m58s

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/kubernetes             ClusterIP   172.20.0.1      <none>        443/TCP     68m
service/master-jenkins         ClusterIP   172.20.121.65   <none>        8080/TCP    8m58s
service/master-jenkins-agent   ClusterIP   172.20.79.77    <none>        50000/TCP   8m58s

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/master-jenkins   1/1     1            1           8m59s

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/master-jenkins-5784cf6bbb   1         1         1       8m59s
```
**Version of Helm and Kubernetes**:
```
helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
```
Kubernetes version
1.14
```
**Which chart**:
```
jenkins-1.9.8.tgz
```
**What happened**:

No ELB service created. Internal ELB and pod is created and access/working

**What you expected to happen**:

for an external ELB to created. As stated in the READme. however it looks like by default 

master.ingress.enabled is set to false. even when created it does not correctly create the load balancer.

**How to reproduce it** (as minimally and precisely as possible):
run
```
helm install master stable/jenkins -f jenkins-values.yaml --debug
```
with the  value provided at the top.

**Anything else we need to know**:
