### ISSUE TITLE
[stable/nginx-ingress] proxy support for octavia loadbalancer v2 (openstack)

### ISSUE THREAD

**Issue by Isakgicu** [helm/charts#19465]
Hi,

When installing nginx-ingress with helm, it does provision a loadbalancer but
pools protocol are TCP, it seems that annotation loadbalancer.openstack.org/proxy-protocol: "true"
is not working.
I have tried to install nginx-ingress controller with following values.yml variables:

 

> helm install --name nginx-ingress \
>       stable/nginx-ingress --namespace nginx-ingress \
>       --set rbac.create=true -f values.yml

values.yml :

```
controller:
    publishService:
        enabled: true
    config:
        use-forward-headers: "true"
        compute-full-forward-for: "true"
        use-proxy-protocol: "true"
    service:
        annotations:
          loadbalancer.openstack.org/proxy-protocol: "true"
```

I am using kubernetes 1.15.6 on a openstack train release cloud platform. Kubernetes cluster
has been provisioned with rancher-server. Loadbalancer provider is Octavia V2, the problem
is that after nginx-ingress creates the loadbalancer, I have to manually recreate pools
with PROXY protocol as they are provisioned with TCP, after that everything is working perfect.

Is it possible to make this future work automatically?
Thanks in advance.
