### ISSUE TITLE
[stable/mongodb] Authentication failed with root password

### ISSUE THREAD

**Issue by modassarrana** [helm/charts#19484]
I have installed mongodb without replica set & set root password as well as custom user 
```
## MongoDB admin password
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
mongodbRootPassword: admin123

## MongoDB custom user and database
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
##
mongodbUsername: my-user
mongodbPassword: my-password
mongodbDatabase: my-database
```

Tried authentication for root user & it failed.
> use admin
switched to db admin
> db.auth('root','admin123')
Error: Authentication failed.
0

Authentication worked for custom user (my-user)
> db.auth('my-user','my-password')
1

Troubleshooting -> Secrets are getting created with the values set as part of values.yaml
```
kubectl get secret --namespace default my-release-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode
admin123
```
mongodb Pods are in running state 
```
[mongodb]# kubectl get pod
NAME                                  READY   STATUS    RESTARTS   AGE
my-release-mongodb-6b7c6d989b-fdbvp   1/1     Running   0          79m
```

mongodb nodePort service is in running state
```
[mongodb]# kubectl get svc | grep mongo
my-release-mongodb                  NodePort       10.233.5.204    <none>                                                27017:30000/TCP 
```

**Comment by alemorcuq** [comment]
Hi, @modassarrana.

I'm not able to reproduce your issue. I'm using this `values.yaml` file:

```
$ cat values.yaml
## MongoDB admin password
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
mongodbRootPassword: admin123

## MongoDB custom user and database
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
##
mongodbUsername: user
mongodbPassword: password123
mongodbDatabase: database
```

Then I install the chart with the following command:

```
$ helm install stable/mongodb --namespace amoreno-mng --name mongo -f values.yaml
```

Run a client as instructed in the NOTES.txt file:

```
$ kubectl run --namespace amoreno-mng mongo-mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host mongo-mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

If you don't see a command prompt, try pressing enter.

>
>
> use admin
switched to db admin
> db.auth('root', 'admin123')
1
```

Can you share the full command you are using to install the chart and the options you are changing from default?

Regards,
Alejandro

**Comment by durduliu2009** [comment]
Hello,

Do you have attached persistent volume ? If yes please remove it and recreate the cluster. I had same issue and it seems that an old password remained in that storage so when db was starting it would load that password from storage not the new one that I've provided in the configuration file.

**Comment by modassarrana** [comment]
Yes i have attached persistent volume. I have created a local storage , persistent volume before installing mongodb chart. As you have mentioned , it could be an issue. I have uninstalled the chart & deleted PV . Re-create pv & installed again. Its the same issue. Please find the persistent volume & storage class below thati am using :
``` pv.yaml
------------
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-vol
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/mongodb"

cat sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

Enabled persistenccy in values.yaml
```
persistence:
  enabled: true
  accessModes:
    -  ReadWriteOnce
  size: 8Gi
```

**Comment by modassarrana** [comment]
Even set storage class as local in values.yaml
```
 mountPath: /bitnami/mongodb
 storageClass: "local"
```

**Comment by modassarrana** [comment]
Hi @alemorcuq ,
Command to install mongodb chart
helm install --name my-release -f values.yaml stable/mongodb

Values that i have changed are 
```
volumePermissions:
  enabled: true
usePassword: true
# existingSecret: name-of-existing-secret

## MongoDB admin password
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
mongodbRootPassword: admin123

## MongoDB custom user and database
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
##
mongodbUsername: my-user
mongodbPassword: my-password
mongodbDatabase: my-database

service:
  ## Specify an explicit service name.
  # name: svc-mongo
  ## Provide any additional annotations which may be required.
  ## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
  annotations: {}
  type: NodePort
  # clusterIP: None
  port: 27017

  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  nodePort: 30000

persistence:
  enabled: true
  accessModes:
    -  ReadWriteOnce
  size: 8Gi
  storageClass: "local"
```

I have shared persistent volume & storage class that i have created in my earlier comment as well.

mongodb root password ->
```
[root@svpod mongodb]#  export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-release-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
[root@svpod mongodb]# echo $MONGODB_ROOT_PASSWORD
admin123
```
command to test the connectivity with root user 
```
[root@svpod mongodb]# kubectl run --namespace default my-release-mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host my-release-mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

MongoDB shell version v4.0.13
connecting to: mongodb://my-release-mongodb:27017/admin?authSource=admin&gssapiServiceName=mongodb
2019-12-12T02:35:31.410+0000 E QUERY    [js] Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:344:17
@(connect):2:6
exception: connect failed
pod "my-release-mongodb-client" deleted
```

As i have mentioned , its working fine with custom user i.e. my-user , my-password
pod default/my-release-mongodb-client terminated (Error)
