### ISSUE TITLE
[stable/airflow] Issue with git clone and sync

### ISSUE THREAD

**Issue by zdmytriv** [helm/charts#19509]
**Describe the bug**
When used with github git clone and sync fails because of the error related to known hosts.

```
Cloning into '/dags'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5S98.
Are you sure you want to continue connecting (yes/no)? 
```

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

**Which chart**:
stable/airflow

**What happened**:
these pods are crash looping
- `scheduler`
- `web`
- `worker`

when this configuration is set
```
dags:
  git:
    url: git@github.com:myorg/myrepo.git
    ref: master
    secret: "gh-secret"
    repoHost: "github.com"
    privateKeyName: "github-pk"
    gitSync:
      enabled: true
      refreshTime: 60
  initContainer:
    enabled: true
    installRequirements: false
```

**What you expected to happen**:
They should not crash loop

**How to reproduce it** (as minimally and precisely as possible):
- Create private repo on github
- Add that ^ config into values.yaml
- Install chart

**Anything else we need to know**:
