### ISSUE TITLE
[stable/prometheus] CrashLoopBackoff on adding additionalScrapeConfigs

### ISSUE THREAD

**Issue by omnipresent07** [helm/charts#19531]
**Describe the bug**
We added `additionalScrapeConfigs` into our `values.yaml` such as below. However, when we try to install the chart we get CrashLoopBackogg. When we remove `additionalScrapeConfigs` the prometheus pods come up without issues. 

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'our-job-name'
      scrape_interval: 15s
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - default
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_name]
          action: keep   
          regex: 'our-pod-name'  
```

**Version of Helm and Kubernetes**:

```
➜  ~ helm version
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
```

**Which chart**:

`stable/prometheus-operator `

**What happened**:

When using `additionalScrapeConfigs` the prometheus pods do not come up and are stuck in CrashLoopBackOff. However, removing `additionalScrapeConfigs` works. 

We install prometheus with the command below:

```
helm upgrade --install prometheus stable/prometheus-operator 
--set kubeEtcd.enabled=false \
--set kubeControllerManager.enabled=false \
--set kubeScheduler.enabled=false \
--set prometheusOperator.createCustomResource=true \
--set grafana.smtp.existingSecret=smtp-secret \
--set kubelet.serviceMonitor.https=true \
--set kubelet.enabled=true \
-f values.yaml --namespace monitoring
```

This is contained in our values.yaml for `additionalScrapeConfigs`

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'our-job-name'
      scrape_interval: 15s
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - default
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_name]
          action: keep   
          regex: 'our-pod-name'  
```

**What you expected to happen**:

We expected prometheus operator pods to come up when for us to see the newly added `additionalScrapeConfigs` in `/targets`

**Anything else we need to know**:
