### ISSUE TITLE
[stable/percona-xtradb-cluster] metricsExporter: failed reading ini file: open /home/.my.cnf: no such file or directory

### ISSUE THREAD

**Issue by Basster** [helm/charts#19553]
**Describe the bug**
when enabling the metricsExporter, it refuses to start.

**Version of Helm and Kubernetes**:
Helm:
```bash
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

k8s:
```json
{
"major": "1",
"minor": "14+",
"gitVersion": "v1.14.8-gke.17",
"gitCommit": "188432a69210ca32cafded81b4dd1c063720cac0",
"gitTreeState": "clean",
"buildDate": "2019-11-13T20:47:11Z",
"goVersion": "go1.12.11b4",
"compiler": "gc",
"platform": "linux/amd64"
}
```

**Which chart**:

stable/percona-xtradb-cluster:1.0.3

**What happened**:

I provide a simple custom-values.yaml

```yaml
percona-xtradb-cluster:
  mysqlRootPassword: ****
  mysqlUser: user
  mysqlPassword: ***
  mysqlDatabase: database
  xtraBackupPassword: ****
  replicas: 1
  persistence:
    enabled: true
    size: "10Gi"
  image:
    tag: "5.7.19"
  metricsExporter:
    enabled: true
```
database and logs container starting properly, metrics container fails with

```bash
time="2019-12-12T09:04:52Z" level=info msg="Starting mysqld_exporter (version=0.12.1, branch=HEAD, revision=48667bf7c3b438b5e93b259f3d17b70a7c9aff96)" source="mysqld_exporter.go:257"
time="2019-12-12T09:04:52Z" level=info msg="Build context (go=go1.12.7, user=root@0b3e56a7bc0a, date=20190729-12:35:58)" source="mysqld_exporter.go:258"
time="2019-12-12T09:04:52Z" level=fatal msg="failed reading ini file: open /home/.my.cnf: no such file or directory" source="mysqld_exporter.go:264"
```

**What you expected to happen**:

metrics container starting

**How to reproduce it** (as minimally and precisely as possible):

Happpens everytime I set `metricsExporter.enabled: true`.

**Anything else we need to know**:

As far as I can see the `metrics` container misses `volumeMounts` to the config files, on the `statefulset.yaml`?
