### ISSUE TITLE
[stable/prometheus-operator] unable to scrap kubelet on managed Kubernetes cluster on IBM.

### ISSUE THREAD

**Issue by aliartiza75** [helm/charts#19550]
**Describe the bug**
Unable to scrap kubelet metrics of managed Kubernetes cluster on IBM. Kubelet runs as a system service on the cluster nodes. 

**Version of Helm and Kubernetes**:

Kubernetes version: v1.13.12+IKS
Helm version:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**Which chart**:
Prometheus operator

**What happened**:
I have a managed kubernetes cluster on IBM and I am trying to monitor the cluster using Prometheus operator. But the problem that I am currently facing is that the kubelet service is running as a system service on nodes instead of a k8s pod. So, currently, I am not able to scrape its metrics.

On openshift cluster the kubelet also run as a system service on nodes and they provide a feature to deploy monitoring during cluster deployment. In the monitoring stack, they were able to scrap the kubelet. So, using their method I tried following things:

1. I created an endpoint:

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kubelet
  name: kubelet
  namespace: kube-system
subsets:
- addresses:
  - ip: X.X.X.X
    targetRef:
      kind: Node
      name: X.X.X.X
  - ip: X.X.X.X
    targetRef:
      kind: Node
      name: X.X.X.X
  - ip: X.X.X.X
    targetRef:
      kind: Node
      name: X.X.X.X
  - ip: X.X.X.X
    targetRef:
      kind: Node
      name: X.X.X.X
  - ip: X.X.X.X
    targetRef:
      kind: Node
      name: X.X.X.X
  ports:
  - name: https-metrics
    port: 10255
    protocol: TCP
  - name: cadvisor
    port: 4194
    protocol: TCP
  - name: https-metrics
    port: 10250
    protocol: TCP
```

2. I create a service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kubelet
  name: kubelet
  namespace: kube-system
spec:
  clusterIP: None

  ports:
  - name: https-metrics
    port: 10255
    protocol: TCP
    targetPort: 10255

  - name: cadvisor
    port: 4194
    protocol: TCP
    targetPort: 4194

  - name: http-metrics
    port: 10250
    protocol: TCP
    targetPort: 10250
  type: ClusterIP
```

3. I created a service monitor for Prometheus using Prometheus operator's helm manifest:
```yaml
      additionalServiceMonitors:
        - endpoints:
          - interval: 20s
            path: /metrics
            port: https-metrics
            scheme: https
          jobLabel: k8s-app
          name: monitoring-kubelet
          tlsConfig:
            insecureSkipVerify: true
          namespaceSelector:
            matchNames:
              - kube-system
          selector:
            matchLabels:
              k8s-app: kubelet

        - endpoints:
          - interval: 20s
            path: /metrics
            port: http-metrics
            scheme: http
          jobLabel: k8s-app
          name: monitoring-kubelet-2
          tlsConfig:
            insecureSkipVerify: true
          namespaceSelector:
            matchNames:
              - kube-system
          selector:
            matchLabels:
              k8s-app: kubelet
```

I am getting the following error for both service monitoris:

1.  `monitoring-kubelet-2` service monitor:

```bash
Get https://X.X.X.X:10250/metrics: x509: certificate signed by unknown authority
```
and 

2. `monitoring-kubelet` service monitor:

```bash
Get http://X.X.X.X:10250/metrics: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```
This error is valid as I am trying to call make a call on https endpoint using http protocol.

I have tried to provide bearer token but no luck i have the following secrets in namespace where Prometheus is deployed:

```
alertmanager
default-token-8cwjx
prometheus-prometheus
alertmanager-config
alertmanager-token-x4rs6
monitoring-po-grafana
monitoring-po-grafana-test-token-27nrh
monitoring-po-grafana-token-xcpht
monitoring-po-kube-state-metrics-token-s9pr7
monitoring-po-prometheus-node-exporter-token-sjdkl
monitoring-token-45862
prometheus-token-2jcw8
```

Am i missing something, thanks in advance.

**What you expected to happen**:
Prometheus should scrap the kubelet. 

**How to reproduce it** (as minimally and precisely as possible):
Deploy a managed K8s cluster on IBM and deploy the Prometheus operator and try to scrap the kubelet. 

**Anything else we need to know**:
NIL
