### ISSUE TITLE
[coredns] listen tcp :8080: bind: address already in use - unable to specify single health plugin while having multiple zones

### ISSUE THREAD

**Issue by rhollins** [helm/charts#19604]
I have an error when specifying more than one zone due to the fact that health plugin can be only used once for the same port per zone.
Meantime I need health plugin as otherwise, pod will not start.

I wonder how to configure values.yaml to have 2 zones defined but health plugin specified only for one of those.

Error:

Loading...listen tcp :8080: bind: address already in use

my values.yaml:

```
servers:
- zones:
  - zone: sbox.example.org
    scheme: dns://
    use_tcp: false  

  - zone: dev.example.org
    scheme: dns://
    use_tcp: false  

  port: 53
  plugins:
  - name: cache
    parameters: 30
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready    
  # - name: errors
  # Required to query kubernetes API for data
  # - name: kubernetes
  #   parameters: cluster.local
  # - name: loadbalance
  #   parameters: round_robin
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  # - name: prometheus
  #   parameters: 0.0.0.0:9153
  # - name: forward
  #   parameters: . /etc/resolv.conf
  - name: etcd
    parameters: sbox.example.org
    configBlock: |-
      stubzones
      path /skydns
      endpoint http://10.2.3.242:2379
  - name: etcd      
    parameters: dev.example.org
    configBlock: |-
      stubzones
      path /skydns
      endpoint http://10.2.7.97:2379
```

corefile:

```
dns://sbox.example.org dns://dev.example.org:53 {
    cache 30
    health
    ready
    etcd sbox.example.org {
        stubzones
        path /skydns
        endpoint http://10.2.3.242:2379
    }
    etcd dev.example.org {
        stubzones
        path /skydns
        endpoint http://10.2.7.97:2379
    }
}
```
