### ISSUE TITLE
[stable/minio] pod anti-affinity doesn't work because it applies to post install job

### ISSUE THREAD

**Issue by Naitreey** [helm/charts#19632]
**Describe the bug**
When deploying minio chart in distributed mode, I try to enforce a pod anti-affinity to make sure one pod per k8s worker node, with the following:
```yaml
    affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                      matchLabels:
                          app: minio-c1
                          release: <release-name>
```

This makes it fail to schedule for one of the pods generated by `statefulset.yaml`, because the pod anti-affinity constraint is applied also to the pod generated by `post-install-create-bucket-job.yaml`.

**Version of Helm and Kubernetes**:
helm:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: stable/minio

**What happened**: One of the stateful set pod failed to schedule, showing `pending` state. When `kubectl describe pods <pending-pod>`, it contains the following events:
```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  87s (x4 over 2m49s)  default-scheduler  0/5 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 4 node(s) didn't find available persistent volumes to bind.
```

And because one pod failed to schedule, `make-bucket-job` failed eventually.

**What you expected to happen**:
Pods are scheduled successfully and post install job is run successfully.

**How to reproduce it** (as minimally and precisely as possible):
```sh
helm install -f minio.values.local.yaml minio-test stable/minio
```
with local `values.yaml` as following:

```yaml
image:
    tag: RELEASE.2019-10-12T01-39-57Z
mcImage:
    tag: RELEASE.2019-10-09T22-54-57Z
mode: distributed
replicas: 5
drivesPerNode: 2
persistence:
    storageClass: sc-local
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                  matchLabels:
                      app: minio
                      release: minio-test
buckets:
    - name: bucket-name
      policy: none
      purge: false
```
The values above assumes there's a 5 node k8s cluster.
