### ISSUE TITLE
[sonatype-nexus] how to use sub path

### ISSUE THREAD

**Issue by Hokwang** [helm/charts#19667]
Hello.

I want to use sub path like my-company.com/nexus

But I can't find how to do that.

Here's my vaule.yaml
```
statefulset:
  enabled: true

nexus:
  imageName: sonatype/nexus3
  imageTag: 3.20.0
  service:
    type: ClusterIP

nexusProxy:
  enabled: false

persistence:
  enabled: false

ingress:
  enabled: true
  path: /nexus-stage
  annotations:
    kubernetes.io/ingress.class: "nginx"
  tls:
    secretName: ingress-tls
  rules:
  - host: <my-company.com>
    http:
      paths:
      - backend:
          serviceName: sonatype-nexus-service
          servicePort: 8081
        path: /nexus-stage

service:
  enabled: true
  ports:
  - name: sonatype-nexus-service
    targetPort: 8081
    port: 8081
```

I don't want docker-registry so it turned off.

In this case, I can access my-company.com/nexus
but here's problem.
![image](https://user-images.githubusercontent.com/1247030/71062630-55755380-21ae-11ea-9fd1-bf8550b3ea24.png)

![image](https://user-images.githubusercontent.com/1247030/71062839-d2a0c880-21ae-11ea-96db-8dd2e9eeef57.png)

nexus does not recgonize sub path.

I find out nexus has the feature enabling this,
```
env:
  - name: NEXUS_CONTEXT
    value: nexus-stage
```
but when I use this config, pod does not running, restart continuously.

I tried rewrite option in ingress annotation but it did not work.

How can I this?

**Version of Helm and Kubernetes**: helm v.3.0.1 and k8s 1.16.4
**Which chart**: stable/sonatype-nexus

Thanks,
