### ISSUE TITLE
[stable/logstash] setting nodePort does not seem to work for Logstash chart

### ISSUE THREAD

**Issue by christidis** [helm/charts#19702]
**Describe the bug**
setting a fixed `nodePort` in `values.yaml` does not seem to work.

**Version of Helm and Kubernetes**:

**Which chart**:
`stable/logstash`

**What happened**:
setting a fixed `nodePort` in `values.yaml` does not seem be reflected in the `svc`.
A random port is being used instead.
Note: `nodeport` option is supported according to the `README` file

**What you expected to happen**:
Setting a fixed `nodePort` in `values.yaml` should be applied in the `svc`. 

**How to reproduce it** (as minimally and precisely as possible):
Reproduce with this config
```
  service:
    type: NodePort
    nodePort: 30830
    # Set this to local, to preserve client source ip.  Default stripes out the source ip
    # externalTrafficPolicy: Local
    annotations: {}
```

**Anything else we need to know**:
This bug is related but closed due to inactivity: https://github.com/helm/charts/issues/12001
According to this bug report, the placement of the `nodePort` configuration at the bottom of the service is wrong.
