### ISSUE TITLE
[stable/drone] switch to kube-runner

### ISSUE THREAD

**Issue by pauvos** [helm/charts#19717]
**Is your feature request related to a problem? Please describe.**
It seems that `DRONE_KUBERNETES_ENABLED` is deprecated in favor of the new `drone/drone-runner-kube` Image ([kube-runner.docs.drone.io](https://kube-runner.docs.drone.io/)).

**Describe the solution you'd like**

Let's use kube-runners instead of the (legacy) drone/controller.

Should have:
* Deployment for `drone/drone-runner-kube:latest`
* ServiceAccount (`$releasename-runner-kube`), Role and RoleBinding

https://kube-runner.docs.drone.io/installation/installation/#step-3-install

Nice to have:
* ServiceAccount (`$releasename-runner-kube-builder`), Role and Rolebinding
* Support for multiple different runners
* Ingress for the new [runner dashboard](https://kube-runner.docs.drone.io/installation/configuration/dashboard/)

Probably out of scope:
* restrictive PodSecurityPolicies attached to ServiceAccounts that allow/forbid privileged builds

Configuration could look like this:

```yaml
# values.yml

# breaking change:
# sets the server's DRONE_KUBERNETES_ENABLED variable to false
# but starts kube-runner Deployments instead
server:
  kubernetes: true

runner:
  kubernetes:
  - name: team1
    namespace: drone-runner-kube
    serviceAccount: drone-runner-kube
    replicas: 2
    affinity: ...
    resources: ...
    ui:
      enabled: true # creates a Service for the runner dashboard
      username: admin
      password: password123 # or:
      secret: drone-runner-kube-dashboard # requires a secret containing username and password
      ingress: # creates Ingress
        enabled: true
        annotations: ...
        hosts: ...
    extraEnvVars:
      # https://kube-runner.docs.drone.io/installation/reference/
      DRONE_NAMESPACE_DEFAULT: drone-builds-team1
      DRONE_NAMESPACE_RULES: drone-builds-team1:team1/*
      DRONE_SERVICEACCOUNT_DEFAULT: drone-runner-kube-builder
  - name: team2
  ...
  ```

**Describe alternatives you've considered**

Treat kube-runner as agent:

```yaml
# values.yml

agent:
  replicas: 2

image:
  agent:
    repository: docker.io/drone/drone-runner-kube
    tag: latest

server:
  kubernetes: false
```

Contra:
* Agent template requires changes and becomes really complicated
* You have to set `kubernetes` to `false` for this to work which looks strange for a "cloud native" setup with kube-runners
* Maybe people still depend on agents

**Additional context**
