### ISSUE TITLE
[stable/prometheus-operator] PVC not mounted after prometheus restart

### ISSUE THREAD

**Issue by mikemowgli** [helm/charts#19762]
**Describe the bug**
After the prometheus pod is restarted, the PVC is not mounted, resulting in the queries.active file being unavailable

**Version of Helm and Kubernetes**:
Helm 3.0.0
Kubernetes 1.11 (OpenShift)

**Which chart**:
stable/prometheus-operator 8.3.3

**What happened**:

The chart was deployed successfully, prometheus was working properly. But if Kubernetes has to restart the pod, this error is yielded:
```
caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
--
  | panic: Unable to create mmap-ed active query log
```
After debugging the pod (preventing it to fail instantly by changing the command and args so I have a shell running), I noticed the PVC was not mounted, and as a result, the `/prometheus` direcotry belongs to root and is empty.
The events do not show that a volume cannot be attached. But they don't show either that a volume was attached.

**What you expected to happen**:

PVC is mounted after restart

**How to reproduce it**:

deploy the chart with persistent volumes for prometheus data, restart the pod

**Anything else we need to know**:
The only workaround I found was to manually delete the PVC, then run helm upgrade.

Here's an extract of my values file:
```
prometheus:
  enabled: true
  prometheusSpec:
    nodeSelector:
      node-role.kubernetes.io/infra: "true"
    replicas: 2
    walCompression: true
    retentionSize: 5.7GiB
    secrets:
    - etcd-client-cert
    securityContext:
      fsGroup: 1000120000
      runAsUser: 1000120000
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 6Gi
```

I must admit I am not sure how the chart would be responsible for this, but as I see nothing wrong with other PVCs nor with my Storage Class, I may get some help here...
