### ISSUE TITLE
[stable/cluster-autoscaler] oidc serviceAccounts breaking chart

### ISSUE THREAD

**Issue by apenney** [helm/charts#19784]
Hi,

I'm writing to look for design advice before I wrangle a PR to solve the issue I'm facing.  I'm using EKS to build my cluster, and as part of that I'm using eksctl to create iam roles that map to ServiceAccounts.

If you haven't seen this you define:

```
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    attachPolicy: # inline policy can be defined along with `attachPolicyARNs`
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:Term
```

eksctl uses this to create:

1) An IAM role
2) An IAM profile
3) A trust relationship to the oidc-provider that uses a StringEqual to match 'cluster-autoscaler' in the above example as the ServiceAccount name.

This is all very well, but then to use the cluster-autoscaler chart I run into problems when I need to set `rbac.create=true`.  This fails because it then makes a new serviceAccount that fails the StringsEqual, even if I set appropriate annotations in the SA to point to the IAM role.

I tried overriding fullname but then the chart fails altogether as the ServiceAccount exists (made by eksctl).

My options are:

1) Modify the chart to look if rbac.serviceAccountName is set and skip the creation if rbac.create is true and the AccountName is provided.
2) Create iam roles/profiles/trust completely separate from eksctl (terraform, I suppose)
3) Something else!

Is there a preference on which way to develop this?  It seems like the easiest path is to simply skip the creation of a serviceaccount if a name is given, and then just create the rest of the bindings to that existing SA if rbac.create=true is set.
