### ISSUE TITLE
[stable/prometheus-operator] exporters scrapeTimeout

### ISSUE THREAD

**Issue by wiseelf** [helm/charts#19845]
Hello!
There is exists a possibility to change scrape_interval.
For example for kubelet:
```
  enabled: true
  namespace: kube-system

  serviceMonitor:
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: "60s"
```
The same settings can be applied to the global variable.
But there is no way to set scrape_timeout for exporters(except node-exporter) or change the global scrape_timeout variable.

templates/node-exporter/servicemonitor.yaml:
```
    {{- if .Values.nodeExporter.serviceMonitor.interval }}
    interval: {{ .Values.nodeExporter.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.nodeExporter.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.nodeExporter.serviceMonitor.scrapeTimeout }}
    {{- end }}
```
Please add support to other exporters.
