### ISSUE TITLE
[incubator/common] `common.util.merge` can't merge `containers:` additions

### ISSUE THREAD

**Issue by guice** [helm/charts#19855]
**Describe the bug**
I want to add custom sidecar containers on top of the predefined `common.deployment`, but it's only overwriting, not merging the `containers:` array.

**Version of Helm and Kubernetes**: Helm 3.0.2, k8s: n/a

**Which chart**: incubator/common

**What happened**: `spec.template.spec.containers:` is overwritten.

**What you expected to happen**: `spec.template.spec.containers:` is merged with parent.

**How to reproduce it** (as minimally and precisely as possible):
Use sample chart: 
```yaml
{{- template "common.deployment" (list . "sample-service.fpm.deployment") -}}
{{- define "sample-service.fpm.deployment" -}}
## Define overrides for your Deployment resource here, e.g. to add a Redis sidecar
spec:
  template:
    spec:
      containers:
        - name: redis
          image: "redis:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              protocol: TCP
              name: redis
{{- end -}}
```

**Anything else we need to know**: I understand the root of this may be that's just how `merge` works. I wonder if there's some way to look for arrays and append them? I don't know the template language well enough to know if that's even possible.

Any alternative options?
