### ISSUE TITLE
[stable/postgresql] doc: structure of existingSecret

### ISSUE THREAD

**Issue by shaunc** [helm/charts#19888]
**Describe the bug**

The chart documentation does not specify the structure of `existingSecret`. I need to specify a password for postgres and for user database. How can I do it with the secret?

**Version of Helm and Kubernetes**:

na

**Which chart**:

stable/postgresql

**What happened**:

n.a

**What you expected to happen**:

n.a.

**How to reproduce it** (as minimally and precisely as possible):

n.a.

**Anything else we need to know**:

**Comment by dani8art** [comment]
Hi @shaunc, thank you so much for your feedback. 

The secret structure is the following

```
data:
  # PostgreSQL admin password (used when `postgresqlUsername` is not `postgres`)
  postgresql-postgres-password:..
  # PostgreSQL admin password (overrides postgresqlPassword)
  postgresql-password: ...
  # Replication user password (overrides replication.password)
  postgresql-replication-password: ...
  # Used to authenticate on LDAP
  postgresql-ldap-password: ...
```

Please, check if it works for you. 
Regards.
