### ISSUE TITLE
[stable/redis-ha] multiple instances mixed

### ISSUE THREAD

**Issue by landorg** [helm/charts#19895]
**Describe the bug**
We are facing an issue that sometimes on failover it happens that two different redis-ha instances in our cluster get mixed up. In the error state the sentinel.conf contains 5 known-replica's instead of 2. The extra ips are service ips from another redis-ha instance. The two instances then keep doing constant failover.
```
# Generated by CONFIG REWRITE
port 26379
sentinel known-replica mymaster 10.43.187.155 6379
sentinel known-replica mymaster 10.43.142.48 6379
sentinel known-replica mymaster 10.43.135.17 6379
sentinel known-replica mymaster 10.43.104.22 6379
sentinel known-replica mymaster 10.43.238.110 6379
sentinel known-sentinel mymaster 10.43.241.204 26379 668a476cb44c37c25cb0bbc2eb2575639a68cb39
sentinel known-sentinel mymaster 10.43.142.48 26379 c8d086fa037106a0fab1d504c358ac6f3f726aa6
```
I am suspecting the `masterGroupName` to be the reason for the issue.
Does it have to be different if we have multiple instances?

**Version of Helm and Kubernetes**:
Kubernetes Version: v1.14.8
Helm: 2.16

**Which chart**:
redis-ha

**What happened**:
constant failover

**What you expected to happen**:
single failover

**How to reproduce it** (as minimally and precisely as possible):
no idea. we are unfortunately unable to reproduce the issue.

**Anything else we need to know**:
values instance A:
```yaml
---
  tag: "5-alpine"
  auth: "enabled"
  existingSecret: "cs-redis-cache"
  redis: 
    config: 
      appendonly: "no"
      save: ""
  nodeSelector:
    deploy/cs-databases: "true"
```
values instance B:
```yaml
---
  tag: "5-alpine"
  auth: "enabled"
  existingSecret: "cs-redis-persistent"
  redis: 
    config: 
      appendonly: "yes"
      save: "60 1000"
  nodeSelector:
    deploy/cs-databases: "true"
```
