### ISSUE TITLE
[stable/Prometheus] Ingress Authentication

### ISSUE THREAD

**Issue by matt-lethargic** [helm/charts#19905]
**Describe the bug**
I'm exposing Prometheus Server so that I can use the federation endpoint. What I'd like is the ability to secure that endpoint in some way. Either the chart doesn't enable this or I do not have the skills do configure this. I'm currently supplying a `values.yaml` files to the helm upgrade command, there doesn't seem to be an option for adding authentication to this unless I used nginx annotations, but looking at the nginx documentation this requires a secret to be added. I'd like to use Basic Auth. Is there a way to add a secret along with upgrading/installing this chart in one command or something?

**Version of Helm and Kubernetes**:
kubectl client: 1.17.0
kubectl server 1.15.5
Helm 2.14.0

**Which chart**:
stable/prometheus

**What happened**:
I get the prometheus endpoint exposed, but it has no security

**What you expected to happen**:
A way to add security

**How to reproduce it** (as minimally and precisely as possible):
```
ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - some.host.com
```

**Anything else we need to know**:
Nope
