### ISSUE TITLE
stable/rabbitmq-ha nodePort value is not applied when service.type is NodePort

### ISSUE THREAD

**Issue by javajon** [helm/charts#19919]
**Describe the bug**

The nodePort port value does not get applied to svc.yaml when the service.type is set to "NodePort".

I read the template for svc.yaml and it appears correct but I believe there might be some syntax sugar in the template that is causing it to not work.  There is a free, full working example where you can replicate the problem. See below.

**Version of Helm and Kubernetes**:

Happens with Helm V2, and continues with V3.  The scenario below uses Helm V3 and K8s 1.14.

**Which chart**:

stable/rabbitmq-ha

**What happened**:

In the example scenario below it has the following rabbit-values.yaml contents.

```
replicas: 3

service:
  type: NodePort 
  nodePort: 31000

rabbitmqUsername: guest
rabbitmqPassword: guest
```

and if you run 

`helm install foo-rabbit stable/rabbitmq-ha --namespace rabbit --dry-run --debug -f rabbit-values.yaml`

then you will see the Service declaration does have the service type set to NodePort, but the port value and line for `nodePort: 31000` is unexpectedly missing.

**What you expected to happen**:

Expected to see in the `kind: Service` declaration a line for `nodePort: 31000`.

**How to reproduce it** (as minimally and precisely as possible):

Run the Katacoda here: https://katacoda.com/javajon/courses/kubernetes-applications/rabbitmq. The rabbit-values.yaml file has the overridden default values.

**Anything else we need to know**:

Suppose there is a slight error in the chart templating logic that I can't see.

**Comment by schwing** [comment]
Is this possibly a mixup between the rabbitmq and rabbitmq-ha charts? The config you provided and the template filename svc.yaml matches the rabbitmq chart.

For the rabbitmq-ha chart, the config you provided would be:
```
replicaCount: 3

service:
  type: NodePort
  amqpNodePort: 31000

rabbitmqUsername: guest
rabbitmqPassword: guest
```
