### ISSUE TITLE
[stable/grafana] Dashboard import via url not working if datasource is set

### ISSUE THREAD

**Issue by jbrmg** [helm/charts#19973]
I am trying to import a dashboard from the official Grafana repository via
```
  dashboards:
    default:
      kubernetes-overview:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
```

The dashboard is not imported correctly as the template renders a `|` directly at the end of the URL (e.g. ` https://grafana.com/api/dashboards/6417/revisions/1/download|`. This is caused by a missing space in this line:
https://github.com/helm/charts/blob/12088766a9cbb5fafc61e643df3b8c41814dfae8/stable/grafana/templates/configmap.yaml#L67

The template should be adjusted to add the missing space.

**Comment by pecastro** [comment]
I also don't see the dashboard being imported but the above explanation is not the reason why.
That bit of code handles the download and munging of the data into the disk and I do see it there in the container under `/var/lib/grafana/dashboards/default/foo.json`

Something else is missing ...

**Comment by pecastro** [comment]
You also need:

```
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
```
