### ISSUE TITLE
stable/chart/mongodb no matches for kind ServiceMonitor

### ISSUE THREAD

**Issue by STollenaar** [helm/charts#19988]
**Describe the bug**

When trying to enable serviceMonitoring for the mongodb chart it returns the no matches for kind ServiceMonitor even though things like Prometheus, Loki, etc. are installed. We mainly use terraform apply, but seems to be singled out to the helm install as well.

**Version of Helm and Kubernetes**:
Kubernetes V1.15.0,
Helm V2.15.1

**Which chart**:
stable/mongodb v7.2.10

**What happened**:
install of the chart fails due to it not finding any matches

**What you expected to happen**:
the install of the chart to be completed without any issues

**How to reproduce it** (as minimally and precisely as possible):
run `helm install stable/mongodb --version 7.2.10 -f values.yaml --dry-run --debug` , with prometheus, loki, etc. already installed.

**Anything else we need to know**:
this is the values.yaml I used to do this
`metrics:
    enabled: true
    livenessProbe:
        enabled: true
    readinessProbe:
        enabled: true
    serviceMonitor:
        enabled: true #switching this to false works, but true doesn't
mongodbDatabase: someDB
mongodbPassword: somePassword
mongodbRootPassword: somePassword
mongodbUsername: someUsername
replicaSet:
    enabled: false
    replicas:
        arbiter: 1
        secondary: 1`

**Comment by carrodher** [comment]
As the indentation of the _values.yaml_ matters, in order to reproduce your issue, can you confirm if the _values.yaml_ you are using is the following?
```yaml
metrics:
  enabled: true
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  serviceMonitor:
    enabled: true #switching this to false works, but true doesn't
mongodbDatabase: someDB
mongodbPassword: somePassword
mongodbRootPassword: somePassword
mongodbUsername: someUsername
replicaSet:
  enabled: false
  replicas:
    arbiter: 1
    secondary: 1
```

In the same way, can you copy/paste the exact error you are obtaining? `kubectl logs`, `kubectl describe` or the error after `helm install` would be convenient to reproduce the issue.
