### ISSUE TITLE
[stable/rabbitmq-ha] Failed to Unzip Plugin

### ISSUE THREAD

**Issue by austince** [helm/charts#19995]
**Describe the bug**

**Version of Helm and Kubernetes**:

kube: 1.14
helm: 2.14

**Which chart**:

rabbitmq-ha

**What happened**:

When upgrading the chart (and also fresh installing after a `helm del --purge`), the last node fails to boot, seemingly failing to unzip the management plugin. We have configured a 3 node RMQ cluster with 8gb persistent EBS volumes. Force booting also does not solve this problem.

Error details here:
<details>
<code>
2020-01-09 19:09:35.261 [error] <0.8.0> Could not unzip plugin archive '/opt/rabbitmq/plugins/rabbitmq_management_agent-3.8.0.ez': enospc
2020-01-09 19:09:35.269 [error] <0.8.0> 
Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 465
    rabbit:'-boot/0-fun-0-'/0 line 311
    rabbit:load_all_apps/0 line 335
    rabbit_plugins:prepare_plugins/1 line 332
    rabbit_plugins:'-prepare_plugins/1-lc$^0/1-0-'/2 line 332
    rabbit_plugins:prepare_plugin/2 line 530
throw:{failed_to_unzip_plugin,rabbitmq_management_agent,
                              "/opt/rabbitmq/plugins/rabbitmq_management_agent-3.8.0.ez",
                              enospc}
Log file(s) (may contain more information):
   <stdout>

BOOT FAILED
===========

Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 465
    rabbit:'-boot/0-fun-0-'/0 line 311
    rabbit:load_all_apps/0 line 335
    rabbit_plugins:prepare_plugins/1 line 332
    rabbit_plugins:'-prepare_plugins/1-lc$^0/1-0-'/2 line 332
    rabbit_plugins:prepare_plugin/2 line 530
throw:{failed_to_unzip_plugin,rabbitmq_management_agent,
                              "/opt/rabbitmq/plugins/rabbitmq_management_agent-3.8.0.ez",
                              enospc}
Log file(s) (may contain more information):
   <stdout>

{"init terminating in do_boot",{failed_to_unzip_plugin,rabbitmq_management_agent,"/opt/rabbitmq/plugins/rabbitmq_management_agent-3.8.0.ez",enospc}}
init terminating in do_boot ({failed_to_unzip_plugin,rabbitmq_management_agent,/opt/rabbitmq/plugins/rabbitmq_management_agent-3.8.0.ez,enospc})

Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
</code>
</details>

**What you expected to happen**:

All nodes to have booted.

**How to reproduce it** (as minimally and precisely as possible):

Apply the chart with these values:

```yaml
rabbitmq-ha:
  # forceBoot: true
  exporter:
    enabled: true

  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: standard

  rabbitmqMemoryHighWatermark: 3GB

  replicaCount: 3  # default
  rabbitmqUsername: "guest"
  rabbitmqPassword: "guest"

  managementUsername: "management"
  managementPassword: "management"
  
  podAntiAffinity: soft
  podAntiAffinityTopologyKey: "failure-domain.beta.kubernetes.io/zone"

  definitions:
    policies: |-
        {
          "name": "ha-quorum",
          "pattern": ".*",
          "vhost": "/",
          "definition": {
            "ha-mode": "exactly",
            "ha-params": 2,
            "ha-sync-mode": "automatic",
            "ha-sync-batch-size": 1
          }
        }
```

**Anything else we need to know**:

We performed this upgrade on another cluster without any troubles. Please let me know any more information that I can provide.
