### ISSUE TITLE
[stable/influxdb] Broken statefulset template indentation

### ISSUE THREAD

**Issue by bastienbc** [helm/charts#20013]
Hi,

I wanted to give another try to influxdb, and I wanted to actually launch influxdb container in specific nodes of my cluster. So I set tolerations and nodeSelector and helm told be that something was wrong with the statefulset.yaml.

So I check with debug and dry-run and sure any configuration in the tolerations, or nodeSelector part results in a broken yaml:

```
      tolerations:
              - effect: NoSchedule
          key: special
          operator: Equal
          value: taint
```

So I check the last commit (fe8fb27138cf90b2d7facf7654d3fa977c3d87d4) in the statefulset.yaml template and the code has been badly reindented.
Surely an automated tool that was thinking for the best XD.

Could it be possible to do a hot fix to just rollback the indentation?
