### ISSUE TITLE
[stable/nextcloud] Installation with mariadb enabled fails with `cannot create directory '/bitnami/mariadb/data': Permission denied`

### ISSUE THREAD

**Issue by papanito** [helm/charts#20024]
**Describe the bug**
Installing nextcloud using mariadb fails cause the mariadb pods complain with

```bash
 10:55:50.59 
 10:55:50.60 Welcome to the Bitnami mariadb container
 10:55:50.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
 10:55:50.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
 10:55:50.60 Send us your feedback at containers@bitnami.com
 10:55:50.60 
 10:55:50.60 INFO  ==> ** Starting MariaDB setup **
 10:55:50.64 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
 10:55:50.64 INFO  ==> Initializing mariadb database
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
```

**Version of Helm and Kubernetes**:

- Kubertentes: `1.16`
- Helm: `3.0`

**Which chart**:

`nextcloud-1.9.1`

**What happened**:

I install `nexcloud` unsing `mariadb` as follows

```
helm install nextcloud stable/nextcloud -f nextcloud.values.yml -n nextcloud
```
but the slaves to not come up, apparently cause the `mariadb-slave` and `mariadb-master` doe not come up due to the error for `mkdir`. I have `securityContext` defined to match the user/group from nextcloud. Here the essential part of my `values.yaml`

```
nextcloud:
  host: nc.xxxx.dev
  username: xxxx
  password: REDACTED
  update: 0
  datadir: /var/www/html/data
  tableprefix:

internalDatabase:
  enabled: false
  name: nextcloud

externalDatabase:
  enabled: false

mariadb:
  enabled: true

  securityContext:
    fsGroup: 82
    runAsUser: 33

  db:
    name: nextcloud
    user: nextcloud
    password: xxx

  persistence:
    enabled: false
    accessMode: ReadWriteMany
    size: 8Gi

  master:
    persistence:
      accessModes: 
        - ReadWriteMany
  slave:
    persistence:
      accessModes:
        - ReadWriteMany
```

**What you expected to happen**:

All three containers `nextcloud`, `mariadb-server` and `mariadb-slave` successfully start up

**How to reproduce it** (as minimally and precisely as possible):

See above

**Anything else we need to know**:

N/A

**Comment by papanito** [comment]
Ok, as mentioned in the docu

> You can enable this `initContainer` by setting `volumePermissions.enabled` to `true`.

Maybe extend the example file [`values-mariadb.yaml`](https://github.com/helm/charts/blob/master/stable/nextcloud/values-mariadb.yaml) to show also persistent storage?

```yaml
mariadb:
  enabled: true

  securityContext:
    fsGroup: 82
    runAsUser: 33

  db:
    name: nextcloud
    user: nextcloud
    password: xxx

  persistence:
    enabled: false
    accessMode: ReadWriteMany
    size: 8Gi

  master:
    persistence:
      accessModes: 
        - ReadWriteMany
  slave:
    persistence:
      accessModes:
        - ReadWriteMany
```
