### ISSUE TITLE
Fix apiVersion of stable/zeppelin chart with k8s 1.17.0

### ISSUE THREAD

**Issue by schmichri** [helm/charts#20057]
With K8s v1.17.0 the stable/zeppelin chart is not working anymore 

Versions to reproduce 

```

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

```

Error during `helm install`: 

````

$ helm install testzeppelin2 stable/zeppelin --debug
install.go:149: [debug] Original chart version: ""
install.go:166: [debug] CHART PATH: /Users/chris/Library/Caches/helm/repository/zeppelin-1.1.0.tgz

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
helm.go:76: [debug] unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
	/private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/pkg/action/install.go:231
main.runInstall
	/private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/cmd/helm/install.go:214
main.newInstallCmd.func1
	/private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/cmd/helm/install.go:116
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20191220-82547-1gmzo4a/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20191220-82547-1gmzo4a/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20191220-82547-1gmzo4a/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/asm_amd64.s:1357


````

The Problem is in `deployment.yaml` Fixed version looks for me including the mandatory `selector` spec and the updated `apiVersion: apps/v1`

````


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
    app: {{ template "zeppelin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "zeppelin.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "zeppelin.name" . }}
        release: {{ .Release.Name }}

....


````
