### ISSUE TITLE
[stable/prometheus] Monitoring a Specific Namespace

### ISSUE THREAD

**Issue by stevebail** [helm/charts#20052]
The Prometheus Helm chart is currently designed to provide cluster-wide monitoring across all namespaces using a cluster role. In certain use cases, it is not possible to create a cluster-reader role or is not desirable to monitor the entire cluster. 

Has anyone considered providing additional value(s), variable(s) or configurable parameter(s) in the helm chart giving the installer an option to setup the Prometheus server for monitoring resources running in a specific namespace?

For instance, the Prometheus instance is deployed in a namespace A but is configured to only monitor resources in namespace B using a (reader) role and role binding deployed in such namespace B. Alternatively the Prometheus instance and the monitored resources are in the same namespace.

**Comment by dkarnutsch** [comment]
`kube-state-metrics` can be limited to a namespace by setting `prometheus.kubeStateMetrics.args.namespace` See:  https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md and https://github.com/kubernetes/kube-state-metrics#limited-privileges-environment.

Assuming you are using service discovery for handling the scrape targets you can specify the namespace as well:
```
    - job_name: 'custom-kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
             - test-namespace
```
