### ISSUE TITLE
[stable/prometheus-operator] no metrics from etcd

### ISSUE THREAD

**Issue by SergeSpinoza** [helm/charts#20107]
**Describe the bug**
After install prometheus-operator via helm I have no metrics from etcd. If I check in Prometheus WEB gui -> Status -> Targets: I see `monitoring/prometheus-cluster-monitor-kube-etcd/0 (0/0 up)`

**Version of Helm and Kubernetes**:
Kubernetes 1.16.3 (BareMetal)
Helm 3.0.0

**Which chart**:
prometheus-operator-8.2.4

**How to reproduce it** (as minimally and precisely as possible):
```
helm upgrade --install --namespace monitoring prometheus-cluster-monitoring stable/prometheus-operator
```

**Anything else we need to know**:
Etcd situated on 3 master nodes of kubernetes. 
Kubernetes installed via kubespray.

**Comment by SergeSpinoza** [comment]
I fix it. Problem was when install k8s via kubespray, because Etcd listen only 127.0.0.1. 

For fix it - you need to add lines to file `kubespray/roles/etcd/templates/etcd.env.j2`: 

 ```
# Metrics
ETCD_LISTEN_METRICS_URLS=http://0.0.0.0:2381
```

and then, add lines to values.yaml of prometheus-operator: 

```
kubeEtcd:
  endpoints:
    - 192.168.136.15
    - 192.168.136.16
    - 192.168.136.17
  serviceMonitor:
    insecureSkipVerify: true
    scheme: http
  service: 
    port: 2381
    targetPort: 2381
```
where 192.168.136.15-17 it's ip adresses of etcd nodes.
