### ISSUE TITLE
[stable/nats] Incompatible with helm3

### ISSUE THREAD

**Issue by qiuyuzhou** [helm/charts#20156]
Because the content generated by `toYaml` in helm3 is less one line break then in helm2.

https://github.com/helm/charts/blob/1dad189536e38f0cac50b08812c7e9108497acf1/stable/nats/templates/statefulset.yaml#L147-L148

The  character `-` in line 147 makes below result in helm3. So we should remove it.
```
     - name: metrics
        image: docker.io/bitnami/nats-exporter:0.6.0-debian-9-r71
        imagePullPolicy: "IfNotPresent"
        args:
          - -connz
          - -routez
          - -subz
          - -varz- "http://localhost:8222"
```
