### ISSUE TITLE
[stable/jenkins] Unable to render appropriately cron job template file

### ISSUE THREAD

**Issue by pkaramol** [helm/charts#20167]
**Describe the bug**
A template file is not render appropriately and `helm` installation fails

**Version of Helm and Kubernetes**:

```
▶ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

▶ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc",
Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-gke.8", GitCommit:"39fe6cf6b77a3a0f620bd89db92f5133be67aa91", GitTreeState:"clean", BuildDate:"2019-11-07T19:14:31Z", GoVersion:"go1.12.11b4", Comp
iler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/jenkins`

**What happened**:

Installation fails as follows:

```
▶ helm upgrade --install --tls  my-jenkins -f jenkins-values.yaml stable/jenkins
Release "my-jenkins" does not exist. Installing it now.
Error: render error in "jenkins/templates/jenkins-backup-cronjob.yaml": template: jenkins/templates/jenkins-backup-cronjob.yaml:57:25: executing "jenkins/templates/jenkins-backup-cronjob.yaml" at <$value.awsaccesskey>: ca
n't evaluate field awsaccesskey in type interface {}
```
Here is the `values.yaml` section related to backups:

```yaml
backup:
  # Backup must use RBAC
  # So by enabling backup you are enabling RBAC specific for backup
  enabled: true
  # Used for label app.kubernetes.io/component
  componentName: "jenkins-backup"
  # Schedule to run jobs. Must be in cron time format
  # Ref: https://crontab.guru/
  schedule: "0 2 * * *"
  labels: {}
  annotations: {}
    # Example for authorization to AWS S3 using kube2iam
    # Can also be done using environment variables
    # iam.amazonaws.com/role: "jenkins"
  image:
    repository: "maorfr/kube-tasks"
    tag: "0.2.0"
  # Additional arguments for kube-tasks
  # Ref: https://github.com/maorfr/kube-tasks#simple-backup
  extraArgs: []
  # Add existingSecret for AWS credentials
  existingSecret:
    gcpcredentials: credentials.json
  ## Example for using an existing secret
   # jenkinsaws:
  ## Use this key for AWS access key ID
    # awsaccesskey: false
  ## Use this key for AWS secret access key
    # awssecretkey: false
  # Add additional environment variables
   # jenkinsgcp:
  ## Use this key for GCP credentials
  env: []
  # Example environment variable required for AWS credentials chain
  # - name: "AWS_REGION"
  #   value: "us-east-1"
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  # Destination to store the backup artifacts
  # Supported cloud storage services: AWS S3, Minio S3, Azure Blob Storage, Google Cloud Storage
  # Additional support can added. Visit this repository for details
  # Ref: https://github.com/maorfr/skbn
  destination: "s3://jenkins-data/backup"
checkDeprecation: true

```
**What you expected to happen**:
 Install the helm chart
