### ISSUE TITLE
[stable/grafana]  ES Datasources not working when created from Configmaps

### ISSUE THREAD

**Issue by fivezerosix** [helm/charts#20179]
**Describe the bug**
We are using the Datasource and Dashboard Sidecar providers. We are able to succesfully create both the dasboard and the datasource from Configmaps. However, for some reason the dashboard is unable to read data from the datasource. 

This is the error the we see when loading dashboard: 

![error2](https://user-images.githubusercontent.com/33496047/72452981-06f2af00-3784-11ea-9c04-3475c674c8b9.PNG)

The issue reads (for Google purposes): 

```
Templating init failed


{"err":{"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://127.0.0.1:80//_msearch","data":"{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"my-index*\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"timestamp\":{\"gte\":\"1578499293320\",\"lte\":\"1579104093320\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}}]}},\"aggs\":{\"1\":{\"terms\":{\"field\":\"timestamp\",\"size\":500,\"order\":{\"_key\":\"asc\"}}}}}\n","retry":0,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"","xhrStatus":"error"},"cancelled":true}
```

We can workaround this issue by simply replacing the datasource loaded from the configmap for the exact samedatasource created manually in the UI. We cannot see any difference between the Configmap and the manually created datasource.

![error2](https://user-images.githubusercontent.com/33496047/72456452-51772a00-378a-11ea-9727-48650bd01801.PNG)

**Version of Helm and Kubernetes**:
 Kubernetes v1.13.5
 Helm: v2.14.1

**Which chart**:
Chart: grafana-4.2.0 
App Version: 6.5.0  

**How to reproduce it** (as minimally and precisely as possible):

- Apply the datasource.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: datasource-1
data:
  datasource-1.yaml: |-
    apiVersion: 1
    datasources:
    - name: datasource-1
      type: elasticsearch
      url:  http://127.0.0.1:80/
      database: my-index*
      jsonData:
        timeField: "timestamp"
        esVersion: 70
```

- Apply the dashboard.yaml
```
apiVersion: v1
data:
  dashboard-1.json: |
    {
      ...
      "panels": [
        {
          ...
          "datasource": "datasource-1",
        }
      ...
      "timezone": "",
      "title": "Dashboard",
      "uid": "123456789",
      "version": 1
    }
kind: ConfigMap
metadata:
  name: dashboard-1
  labels:
    grafana_dashboard: "1"
```

The relevant section of the `values.yaml` has this configuration enabled for both Datasources and Dashboards
```
  ...
  dashboards:
    enabled: true
    SCProvider: true
    label: grafana_dashboard
    folder: /tmp/dashboards
    defaultFolderName: null
    searchNamespace: null
    provider:
      name: sidecarProvider
      orgid: 1
      folder: ''
      type: file
      disableDelete: false
  datasources:
    enabled: true
    label: grafana_datasource
    searchNamespace: null

```
Apply the chart `helm install --name grafana -f values.yaml stable/grafana`
