### ISSUE TITLE
[stable/prometheus-operator] serviceMonitorSelector selects only prometheus-operator ServiceMonitors

### ISSUE THREAD

**Issue by jtyers** [helm/charts#20180]
I've just deployed `stable/prometheus-operator` from scratch. I then deployed `stable/prometheus-pushgateway` with this configuration, so that a ServiceMonitor is created:

```
serviceMonitor:
  enabled: true
```

The bug is that Prometheus does not pick up the ServiceMonitor for pushgateway, even though it is created in kubernetes (and all of this is in the same namespace).

Digging deeper I find this:

```
$ kubectl get prometheuses prometheus-operator-prometheus -o jsonpath='{ .spec.serviceMonitorSelector }'
map[matchLabels:map[release:prometheus-operator]]
```

...showing that Prometheus is wired to only discover ServiceMonitors with the `release: prometheus-operator` label by default. Not sure of the original design but I believe this is incorrect?

I think there is a second bug, which is that this cannot be fixed via the chart configuration. If I create the chart with this configuration:

```
prometheus:
  prometheusSpec:
    # default is 'release: prometheus-operator' which means
    # our other helm chart SMs will be excluded
    serviceMonitorSelector: {}
```

..I get the same resulting configuration in Prometheus.

If I add `release: prometheus-operator` to my ServiceMonitor, Prometheus sees it and begins scraping. However that isn't wise as I assume the `release` label is used by Helm to identify resources created by a particular chart.

**Version of Helm and Kubernetes**:
Helm: `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Kubernetes: `v1.13.11-gke.14`
