### ISSUE TITLE
[stable/spinnaker] Bug with kubectl 1.16+

### ISSUE THREAD

**Issue by zdevi** [helm/charts#20207]
Can't install spinnaker's helm release on kubectl v1.16+ 

> helm install --name spinnaker  stable/spinnaker --namespace spinnaker
> Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

kubectl v1.16.4
helm v2.16.1

Reproduce :
Try to install spinnaker stable chart on K8S 1.16+

**Comment by denniss17** [comment]
Duplicate to https://github.com/helm/charts/issues/20191.

It seems to be a problem in dependencies of this chart. Both the `minio` and `redis` dependencies use the old api.

**Comment by denniss17** [comment]
I cloned this repo and updated `stable/spinnaker/requirements.yaml` to:

```
dependencies:
- name: redis
  version: 10.3.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: minio
  version: 5.0.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
```

Then I did `helm dependency update`  and `helm install spinnaker . --namespace spinnaker --timeout 600s`.

It is currently installing, I hope this will work

**Comment by denniss17** [comment]
Nope. That didnt work. The installer is running but fails with:

```


- Apply deployment

Failure

- Deploy spin-clouddriver

Failure

- Deploy spin-front50

Failure

- Deploy spin-orca

Failure

- Deploy spin-deck

Failure

- Deploy spin-echo

Failure

- Deploy spin-gate

Failure

- Deploy spin-igor

Failure

- Deploy spin-rosco

Failure

Problems in Global:

! ERROR Failed to deploy manifest:

apiVersion: apps/v1beta2

kind: Deployment

metadata:

name: spin-clouddriver

namespace: spinnaker

annotations: {moniker.spinnaker.io/application: '"spin"',

moniker.spinnaker.io/cluster: '"clouddriver"'}

labels: {app: spin, cluster: spin-clouddriver, app.kubernetes.io/name:

clouddriver,

app.kubernetes.io/managed-by: halyard, app.kubernetes.io/part-of: spinnaker,

app.kubernetes.io/version: 1.16.1}

spec:

replicas: 1

selector:

matchLabels: {app: spin, cluster: spin-clouddriver}

template:

metadata:

annotations: {}

labels: {app: spin, cluster: spin-clouddriver, app.kubernetes.io/name:

clouddriver,

app.kubernetes.io/managed-by: halyard, app.kubernetes.io/part-of: spinnaker,

app.kubernetes.io/version: 1.16.1}

spec:

containers:

- name: clouddriver

image: gcr.io/spinnaker-marketplace/clouddriver:6.3.0-20190904130744

ports:

- {containerPort: 7002}

readinessProbe:

exec:

command: [wget, --no-check-certificate, --spider, -q,

'http://localhost:7002/health']

initialDelaySeconds: null

livenessProbe: null

securityContext: null

volumeMounts:

- {name: spin-clouddriver-files-1659378238, mountPath: /opt/spinnaker/config}

lifecycle: {}

env:

- {name: JAVA_OPTS, value: '-XX:+UnlockExperimentalVMOptions

-XX:+UseCGroupMemoryLimitForHeap

-XX:MaxRAMFraction=2'}

- {name: SPRING_PROFILES_ACTIVE, value: local}

resources:

requests: {}

limits: {}

imagePullSecrets: []

terminationGracePeriodSeconds: 720

affinity: {podAntiAffinity: null, podAffinity: null, nodeAffinity: null}

tolerations: []

volumes:

- name: spin-clouddriver-files-1659378238

secret: {secretName: spin-clouddriver-files-1659378238}

error: unable to recognize "STDIN": no matches for kind "Deployment" in version

"apps/v1beta2"

- Failed to deploy Spinnaker.
```

**Comment by denniss17** [comment]
In my second attempt I updated the versions in `values.yaml` to the latest versions:

```
halyard:
  spinnakerVersion: 1.17.6
  image:
    repository: gcr.io/spinnaker-marketplace/halyard
    tag: 1.29.0
    pullSecrets: []
...
```

It seems to be working now
