### ISSUE TITLE
[stable/external-dns] Azure private dns failed to refresh the token

### ISSUE THREAD

**Issue by IbraheemAlSaady** [helm/charts#20212]
I'm using azure private DNS and I'm trying to make external DNS work with it. But it's failing to get the token

```yml
provider: azure-private-dns

azure:
  resourceGroup:
  tenantId:
  subscriptionId:
  aadClientId:
  aadClientSecret:
```

Of course its filled with values. But I'm getting this error:

`Failed to refresh the Token for request to https://management.azure.com/subscriptions//resourceGroups//providers/Microsoft.Network/privateDnsZones?api-version=2018-09-01`

The subscription id and the resource group are not being picked up.

These are my chart info: 

```terraform
image = "bitnami/external-dns"
tag = "0.5.18"
chart_version = "2.14.3"
```

Am I missing something?

Cheers!
