### ISSUE TITLE
[stable/grafana] Notification Channel through values.yaml config not working

### ISSUE THREAD

**Issue by zomarg** [helm/charts#20218]
**Describe the bug**

We are trying to provision a slack Notification Channels through configuration.
I tried to set basic notification channels configuration using `values.yaml` but one field in settings (which is a secret) through `--set` when releasing it with Helm.

The interesting part that if you hardcode the url (part of settings) inside the `values.yaml` it works perfectly.

When you try to set it using `--set`, Grafana fails with exception: "Alert validation error: Could not find url property in settings"

_values.yaml file:_

```
grafana:
    enabled: true
    notifiers: 
      notifiers.yaml:
        notifiers:
        - name: slack-notifier
          type: slack
          uid: slack
          org_id: 1
          is_default: true
          settings:
            url:
```

```
helm install --name my-release stable/grafana grafana.notifiers.notifiers\.yaml.notifiers[0].settings.url=xxxSlackHookUrlxx
```

**Version of Helm and Kubernetes**:

_helm version_
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

_kubectl version_
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
- prometheus-operator
- grafana

**What happened**:

_Grafana fails to start with the following logs_

```
t=2020-01-17T15:35:44+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Alert notification provisioning error: Alert validation error: Could not find url property in settings"
```

**What you expected to happen**:
Grafana notification channel gets created with the right url

**How to reproduce it** (as minimally and precisely as possible):
helm install --name my-release stable/grafana --set grafana.notifiers.notifiers\.yaml.notifiers[0].settings.url=xxx

Values.yaml content:

```
grafana:
    enabled: true
    notifiers: 
      notifiers.yaml:
        notifiers:
        - name: slack-notifier
          type: slack
          uid: slack
          org_id: 1
          is_default: true
          settings:
            url:
```

**Anything else we need to know**:
