### ISSUE TITLE
stable/consul uiIngresspath typo

### ISSUE THREAD

**Issue by no1melman** [helm/charts#20210]
**Describe the bug**
This line 

https://github.com/helm/charts/blob/9eecded9d243e981bd78a2b72cbd9e419af9766c/stable/consul/templates/consul-ingress.yaml#L31

shows I think a typo?

Should it not be:

```
    path: {{ .Values.uiIngress.path }}
```

**Version of Helm and Kubernetes**:
Kubernetes 1.10.3
Helm 2

**Which chart**:
Consul

**Comment by no1melman** [comment]
**Also** when you run the code with a uiIngress.path it doesn't work:

```
 executing "consul/templates/consul-ingress.yaml" at <.Values.uiIngress.path>: can't evaluate field Values in type interface {}
```
Which is from what I reckon is that the path is not in the right place in the yaml:

https://github.com/helm/charts/blob/9eecded9d243e981bd78a2b72cbd9e419af9766c/stable/consul/templates/consul-ingress.yaml#L26-L32

If I change that to this:

```
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
```

It works perfectly....
