### ISSUE TITLE
[stable/jenkins] Wrong volume permissions error for non-root user (Helm chart v1.9.16)

### ISSUE THREAD

**Issue by aryak007** [helm/charts#20243]
**Describe the bug**
We're trying to run `Jenkins` with a `non-root` user. My `values.yaml` looks like this :

```
master:
  image: hcr.io/jenkins/jenkins
  tag: lts-alpine
  # JavaOpts Xms should match requests Xmx should be 50% of limits to allow for space for off heap storage
  # This is NOT a hard and fast rule but seems like overall guidence
  # https://developers.redhat.com/blog/2017/03/14/java-inside-docker/
  javaOpts: '-XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -Xms512m -Xmx1g -Dhudson.plugins.active_directory.ActiveDirectorySecurityRealm.forceLdaps=true -Dhudson.model.DirectoryBrowserSupport.CSP='
  resources:
    requests:
      cpu: "50m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
  usePodSecurityContext: true
  runAsUser: 1000
  fsGroup: 1000
  serviceType: ClusterIP
  slaveListenerServiceType: NodePort
  slaveListenerPort: 32001
  containerEnv:
    - name: JENKINS_SLAVE_AGENT_PORT
      value: "32001"
```
But there's a permission issue while creating the `/var/jenkins_home/copy_reference_file.log` file. The **error log** is:
```
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
```

**Version of Helm and Kubernetes**:
Helm version - v2.14.3
K8s Client - v1.15.3
K8s Server - v1.13.5

**Which chart**:
stable/jenkins

**What happened**:
Cannot run Jenkins as a `non-root` user.

**What you expected to happen**:
From the `documentation` [here](https://github.com/helm/charts/tree/master/stable/jenkins), with `runAsUser` and `fsGroup` set, this should have worked **but it didn't**. 

**How to reproduce it** (as minimally and precisely as possible):
Just running the helm chart with the above values should be sufficient to replicate. 

**Anything else we need to know**:
We tried running  `InitContainers` and changing the permission of the volume to a user with `uid` 1000 but it didn't work. This approach is mentioned in this issue here and the OP was able to solve it with the `initContainer` approach - https://github.com/helm/charts/issues/15453 

Here's the `InitContainers` declaration:
```
  InitContainers:
  - name: volume-mount-permission
    image: busybox
    command: ["/bin/chown", "-R", "1000:1000", "/var/jenkins_home"]
    volumeMounts:
      - name: "jenkins-home"
        mountPath: "/var/jenkins_home"
    usePodSecurityContext: true
    runAsUser: 0
    fsGroup: 0
```
