### ISSUE TITLE
[stable/spinnaker] Missing Line Feed after dockerRegistry password-file

### ISSUE THREAD

**Issue by mlapish** [helm/charts#20277]
**Describe the bug**

Code introduced in spinnaker chart version 1.23.1 for docker registry, results in no linefeed at end of password-file resulting in failed step.

https://github.com/helm/charts/commit/7cb80611b962946fe1bd0142fac41e96457f52ab#diff-af1256557bb91bed861ac163fdf85152

    CREDS+="--username {{ $registry.username }}"
    {{ if $registry.passwordCommand -}}
    CREDS+=" --password-command {{ $registry.passwordCommand | quote }}"
    {{- else -}}
    CREDS+=" --password-file /opt/registry/passwords/{{ $registry.name }}"
    {{- end -}}
    {{ if $registry.email -}}	    {{ if $registry.email -}}
    CREDS+=" --email {{ $registry.email }}"	   
    {{- end -}}

**Version of Helm and Kubernetes**:
1.23.1 - gke 1.14.8

**Which chart**:
stable/spinnaker

**What happened**:
command ends up like
hal --daemon-endpoint http://cd-spinnaker-halyard:8064 config provider docker-registry account edit gcr --address https://gcr.io --username _json_key --password-file /opt/registry/passwords/gcrCRED+- --email 1234@5678.com

**What you expected to happen**:
should be:
hal --daemon-endpoint http://cd-spinnaker-halyard:8064 config provider docker-registry account edit gcr --address https://gcr.io --username _json_key --password-file /opt/registry/passwords/gcr --email 1234@5678.com

**How to reproduce it** (as minimally and precisely as possible):
It's visible in haliyard-config configmap after running chart install or upgrade

**Anything else we need to know**:

**Comment by rrijkse** [comment]
I am having the same issue and I ended up working around it by creating a script and mounting this using an `additionalConfigMaps` and mounting it on the `clouddriver` machine as well.

```
halyard:
  additionalConfigMaps:
    create: false
    name:
      aws-ecr-script
  additionalServiceSettings:
    clouddriver.yml:
        volumes:
        - id: aws-ecr-script
          type: configMap
          mountPath: /opt/halyard/additionalConfigMaps
```
