### ISSUE TITLE
[postgresql] extraEnv and supporting ConfigMaps

### ISSUE THREAD

**Issue by hetsch** [helm/charts#20285]
**Is your feature request related to a problem? Please describe.**
Currently the chart supports passing extra environment variables as key/value pairs to the container . As far as I could read in the docs and source this should be done via `extraEnv` ( https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml#L132). It would save me some repetition in explicitly declaring all the environment variables again which are allready declared in a `ConfigMap`.

**Describe the solution you'd like**
What I would need, is using enviroment variables that are stored in a `ConfigMap` or `Secret`. Some charts, e.g. selenium, support doing this. Maybe it would be of value for postgres chart.

```
extraEnvs:
- name: FOO
    valueFrom:
        configMapRef:
            key: FOO
            name: config-resource
- name: BAR
    valueFrom:
        secretKeyRef:
            key: BAR
            name: secret-resource
```

Thank you for your help!

**Comment by alemorcuq** [comment]
Hi, @hetsch.

I think I don't fully understand what you are saying. As far as I can tell, the Selenium's `extraEnvs` is exactly the same as this chart's `extraEnv`. You should be able to use `extraEnv` to load variables from Config Maps or Secrets:

```yaml
extraEnv:
- name: FOO
    valueFrom:
        configMapRef:
            key: FOO
            name: config-resource
- name: BAR
    valueFrom:
        secretKeyRef:
            key: BAR
            name: secret-resource
```
