### ISSUE TITLE
[stable/prometheus-blackbox-exporter] Multiple ServiceMonitor rules rewrite each other

### ISSUE THREAD

**Issue by j-sokol** [helm/charts#20398]
**Describe the bug**
When multiple targets (i.e. value in `serviceMonitor.targets[]`) are entered in `values.yaml`, only the last entry is deployed to Kubernetes and monitored via Prometheus, as only last `ServiceMonitor` CRD is deployed.

**Version of Helm and Kubernetes**:
Helm v3.0.0
Kubernetes 1.15

**Which chart**:
stable/prometheus-blackbox-exporter

**What happened**:
When multiple targets (i.e. value in `serviceMonitor.targets[]`) are entered in `values.yaml`, only the last entry is deployed to Kubernetes and monitored via Prometheus, as only last `ServiceMonitor` CRD is deployed.

**What you expected to happen**:
All targets should be monitored/CRD deployed for all of them.

**How to reproduce it** (as minimally and precisely as possible):
Use this configuration in `values.yaml`:
```
...
serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: true

  # Default values that will be used for all ServiceMonitors created by `targets`

  defaults:
    labels: {}
    interval: 60s
    scrapeTimeout: 60s
    module: http_2xx

  targets:
   - name: entry1                    
     url: 'https://example1.com/'  
   - name: entry2                 
     url: 'https://example.com/'  
```
