### ISSUE TITLE
[stable/pgadmin] error parsing yml when use tolerations

### ISSUE THREAD

**Issue by mfbrj** [helm/charts#20496]
**Describe the bug**
The deploy fails when there are `tolerations` config.

**Version of Helm and Kubernetes**:
Kubernetes: 1.17.2

**Which chart**: stable/pgadmin

**What happened**: Deployment fails with this error message if there are tolerations configuration on answers.yml:
```Failed to install app pgadmin. Error: YAML parse error on pgadmin/templates/deployment.yaml: error converting YAML to JSON: yaml: line 88: did not find expected '-' indicator```

**What you expected to happen**: Successful deployment.

**How to reproduce it** (as minimally and precisely as possible):
Uses this values:
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
  hosts:
    - host: pgadmin.tre-pa.jus.br
      paths:
        - /

  tls:
    - secretName: asterisco-tre-pa
      hosts:
        - pgadmin.tre-pa.jus.br

env:
  email: fbeltrao@tre-pa.jus.br
  password: SuperSecret

persistenceVolume:
  enabled: true
  storageClass: "-"
  existingClaim: "pgadmin"
  
tolerations:
- key: "persistence"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
```

**Anything else we need to know**:

**Comment by rowanruseler** [comment]
@fredbeltrao I think you made a naming mistake, `persistenceVolume:` should be `persistentVolume:`. Apologies, I adjusted the name with the latest adjustment.

**Comment by fredbeltrao** [comment]
I tried these values:
```
---
replicaCount: 1
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
  hosts:
  - host: pgadmin.tre-pa.jus.br
    paths:
      - /
  tls:
    - secretName: asterisco-tre-pa
      hosts:
        - pgadmin.tre-pa.jus.br
env:
  email: fbeltrao@tre-pa.jus.br
  password: SuperSecret
  
persistentVolume:
  enabled: true
  size: 1Gi
  storageClass: "-"
  existingClaim: "pgadmin"
  
tolerations:
- key: "persistent"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
```
And get the same error:
`Failed to install app pgadmin. Error: UPGRADE FAILED: YAML parse error on pgadmin/templates/deployment.yaml: error converting YAML to JSON: yaml: line 88: did not find expected '-' indicator`
