### ISSUE TITLE
[stable/fluent-bit] Add custom files to existing configmap

### ISSUE THREAD

**Issue by kalioz** [helm/charts#20535]
**Is your feature request related to a problem? Please describe.**
Fluent-bit can use custom lua scripts to parse logs, and those scripts need to be loaded on the pods. In order to load them, we can only use another configmap with the `extraVolume` field, which separate the lua script from the helm chart.

**Describe the solution you'd like**
Have an additional field where we could specify files as text :
```yaml
extraConfigFiles:
  file_1.lua: |
    -- filecontent
  file2.yaml: |
    ## 
```

Additionaly, this would enable people using preprocessors like helmfile to totally externalise their customs script from the values.yaml file.

**Describe alternatives you've considered**
Use an external configmap.
