### ISSUE TITLE
[stable/prometheus-adapter] unable to add custom rules using --set-file

### ISSUE THREAD

**Issue by sathyav82** [helm/charts#20557]
**Describe the bug**
helm install my-release stable/prometheus-adapter --set-file rules.custom=customrules.yaml doesnt work
an extraneous "|" (pipe symbol) is added to the start of the new rules in the configmap resource and this causes the (prometheus adapter) pod to NOT start up.

**Version of Helm and Kubernetes**:
Helm Version:"v3.0.2"

Kubernetes Version: "1.14.9" (on EKS - Platform:"linux/amd64")

**Which chart**:
[stable/prometheus-adapter] version 2.0.1

**What happened**:
an extraneous "|" (pipe symbol) is added to the start of the new rules in the configmap resource and this causes the (prometheus adapter) pod to NOT start up.

**What you expected to happen**:
the extraneous "|" should not be added in the configmap resource and the prometheus adapter pod should startup.

**How to reproduce it** (as minimally and precisely as possible):
```
- seriesQuery: "mytest_tasks_per_minute"
  seriesFilters: []
  resources:
    overrides:
      kubernetes_namespace:
        resource: namespace
      kubernetes_pod_name:
        resource: pod
  name:
    matches: "mytest_tasks_per_minute"
    as: ""
  metricsQuery: <<.Series>>{<<.LabelMatchers>>,container_name!="POD"}
```
store the above rule in a customrules.yaml and install the helm chart as:
helm install my-release stable/prometheus-adapter --set-file rules.custom=customrules.yaml

**Anything else we need to know**:
changing the templates/custom-metrics-configmap.yaml file to the below works for me

{{- if .Values.rules.custom }}
{{ tpl .Values.rules.custom . | indent 4 }}
{{- end -}}
