### ISSUE TITLE
[stable/prometheus-operator] Adding an authentication proxy for Alert Manager

### ISSUE THREAD

**Issue by anaclaudiar** [helm/charts#20565]
**Describe the bug**
On values.yaml I can see we have containers[] on AlertManager to allow injecting additional containers, to add an authentication proxy to an Alertmanager pod. This is a great feature, except that the targetPort is hardcoded to 9093 on the service, so I can't point the service to the port of my authentication proxy.
On this file: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/alertmanager/service.yaml , line 40, it would be necessary to read the targetPort from values.yaml, the same that is done for Promethes service here: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/service.yaml

I'm considering this a bug because I can't add an authentication proxy with this targetPort hardcoded.

**Version of Helm and Kubernetes**:
Helm 2.14.3
Kubernetes 1.14.7

**Which chart**:
prometheus-operator

**What happened**:
 I can't add an authentication proxy to alert manager with the targetPort hardcoded on the service.

**What you expected to happen**:
I expect the targetPort to be read from values.yaml.

**How to reproduce it** (as minimally and precisely as possible):
On alertmanager (inside values.yaml), add an ingress:
```
alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    hosts:
      - ${alertManager.host}
    tls:
      - secretName: alertmanager-tls
        hosts:
          - ${alertManager.host}
  service:
    port: 3000
    targetPort: 3000
```
Then on alertmanagerSpec:

```
  alertmanagerSpec:
    containers:  
      - name: keycloak-gatekeeper
        args:
        - --discovery-url=XYZ
        - --client-id=id
        - --client-secret=secret
        - --listen=0.0.0.0:3000
        - --redirection-url=https://${alertManager.host}
        - --upstream-url=https://0.0.0.0:9093
        - --resources=uri=/*
        image: quay.io/keycloak/keycloak-gatekeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
```

I can see the ingress is working, but once I go to the url of alertmanager.host, I'm not redirected to keycloak, the alert manager is open to the internet.
