### ISSUE TITLE
[stable/grafana] CrashLoopBackOff when specifying dashboard in values.yaml

### ISSUE THREAD

**Issue by wilinger** [helm/charts#20703]
**Describe the bug**
Pod status shows CrashLoopBackOff when I specify dashboards in values.yaml.

**Version of Helm and Kubernetes**:
Client Version: v1.17.2
Server Version: v1.17.2
v3.0.3+gac925eb

```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
```
```
Init Containers:
  init-chown-data:
    Container ID:  containerd://96054118bdbabb655747feafbd16f4413f8d5277b21be1ad52376654282305a7
    Image:         busybox:1.30
    Image ID:      docker.io/library/busybox@sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d
    Port:          <none>
    Host Port:     <none>
    Command:
      chown
      -R
      472:472
      /var/lib/grafana
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 12 Feb 2020 06:27:39 +0000
      Finished:     Wed, 12 Feb 2020 06:27:39 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/grafana from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from grafana-token-xfd57 (ro)
  download-dashboards:
    Container ID:  containerd://dd55faa552cbe05acbbd3dfd0dcd3d79b010df497058da2bb8d4aee620d79b7f
    Image:         appropriate/curl:latest
    Image ID:      docker.io/appropriate/curl@sha256:c8bf5bbec6397465a247c2bb3e589bb77e4f62ff88a027175ecb2d9e4f12c9d7
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      mkdir -p /var/lib/grafana/dashboards/default && /bin/sh /etc/grafana/download_dashboards.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 12 Feb 2020 06:28:32 +0000
      Finished:     Wed, 12 Feb 2020 06:28:32 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 12 Feb 2020 06:28:01 +0000
      Finished:     Wed, 12 Feb 2020 06:28:01 +0000
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /etc/grafana/download_dashboards.sh from config (rw,path="download_dashboards.sh")
      /var/lib/grafana from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from grafana-token-xfd57 (ro)
```

When I comment out everything under dashboards, it'll deploy but logs showing:

```
t=2020-02-12T06:46:30+0000 lvl=eror msg="Cannot read directory" logger=provisioning.dashboard type=file name=default error="stat /var/lib/grafana/dashboards/default: no such file or directory"
t=2020-02-12T06:46:30+0000 lvl=eror msg="Failed to read content of symlinked path" logger=provisioning.dashboard type=file name=default path=/var/lib/grafana/dashboards/default error="lstat /var/lib/grafana/dashboards: no such file or directory"
```

When deployed, I ran kubectl exec -i -t grafana-c678b8d7c-sqttr bash to explore, I do not see the folder /var/lib/grafana/dashboards created.
