### ISSUE TITLE
[influxdb] incorrect toleration indentations

### ISSUE THREAD

**Issue by ArgTang** [helm/charts#20709]
**Describe the bug**

Enabling toleration in values file:
```yaml
tolerations:
- key: "key"
  operator: "Equal|Exists"
  value: "value"
  effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"
```
results in this render:
```yaml
    spec:
      tolerations:
              - effect: NoSchedule|PreferNoSchedule|NoExecute(1.6 only)
          key: key
          operator: Equal|Exists
          value: value
```

In Helm3 (3.0.3) this fails to deploy.

Solutions change `statefulset.yaml` line 44-46:
```yaml
# fix alternative1:
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }} # move this line to start of file
      {{- end }}
# fix alternative2:
      {{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }} # keep template indentation, but change to use nindent
      {{- end }}
```

**Comment by ArgTang** [comment]
@jackzampolin @Aisuko

**Comment by june9666** [comment]
and also affinity

```
spec:
      affinity:
              nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
```
