### ISSUE TITLE
[stable/airflow] git sync is broken if shared pvc is used which already has dags 

### ISSUE THREAD

**Issue by appunni-m** [helm/charts#20722]
I am using shared pvc for dags and I feel like there is no need to run multiple side cars for each worker, scheduler and web . I would suggest incase of shared pvc run only one of them as I have seen them erroring out due to all of them trying to clone at same time. Also another case is when initContainer is set to false  they go into an infinite loop of error saying dag is not empty.

I guess it has to do with not checking if dag is already there or not, but a condition in the script I saw which checks if initContainer is not enabled then it always default to clone first irrespective of status of the dag folder. Isn't there no better way to git sync the clone or pull ?

May be get fetch {{branch}} && git reset --hard {{branch}} is better option , before that check if .git folder already exists, if not clone

**Comment by appunni-dishq** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-git-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow-git-sync
  template:
    metadata:
      labels:
        name: airflow-git-sync
    spec:
      volumes:
      - name: markdown
        persistentVolumeClaim:
          claimName: airflow-dags
      - name: git-secrets
        secret:
          secretName: airflow-secrets
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.3
        volumeMounts:
        - name: markdown
          mountPath: /tmp/git
        - name: git-secrets
          mountPath: /etc/git-secrets
        env:
        - name: GIT_SYNC_REPO
          value: git@github.com:username/repo.git
        - name: GIT_SYNC_DEST
          value: git-sync
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SSH_KNOWN_HOSTS_FILE
          value: /etc/git-secrets/known_hosts
        - name: GIT_SSH_KEY_FILE
          value: /etc/git-secrets/id_rsa
        resources:
          limits:
            memory: 20Mi
            cpu: 150m
          requests:
            memory: 15Mi
            cpu: 80m
```

I disabled the existing gitSync and and initContainer . Setup an NFS volume using stable/nfs-server-provisioner and created a persistentVolumeClaim called airflow-dags with ReadWriteMany accessMode.

And used the above yaml config to create my own gitSync which works perfectly.
