### ISSUE TITLE
[stable/pgadmin] Blank dashboard graphics

### ISSUE THREAD

**Issue by mfbrj** [helm/charts#20721]
**Describe the bug**
Dashboard graphics are blank since pgadmin 4.17, as far as I know. Pehaps this is a image issue.

**Version of Helm and Kubernetes**:
Kubernetes: v1.17.2

**Which chart**:
Chart: stable/pgadmin Template version 1.1.5
pgadmin: 4.18

**What happened**:
Database dashboard graphics are displayed blank like that:
![](http://i.imgur.com/Re3W6kZ.png)

**What you expected to happen**:
Database dashboard graphics should be displayed nice.

**How to reproduce it** (as minimally and precisely as possible):

1. Install the chart with these values:
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
  hosts:
    - host: pgadmin.tre-pa.jus.br
      paths:
        - /

  tls:
    - secretName: asterisco-tre-pa
      hosts:
        - pgadmin.tre-pa.jus.br

env:
  email: fbeltrao@tre-pa.jus.br
  password: SuperSecret

persistentVolume:
  enabled: true
  storageClass: "-"
  existingClaim: "pgadmin"
```
2. Add a server with a working database
3. Click on a database e goes to dashboard
4. See the blank graphics

**Anything else we need to know**:
As far as I remember, it worked fine until pgadmin 4.15
