### ISSUE TITLE
[stable/influxdb] Influxdb set auth job fails

### ISSUE THREAD

**Issue by jishminor** [helm/charts#20741]
**Describe the bug**
Default user not created successfully with Kubernetes Job

**Version of Helm and Kubernetes**:
Helm: 2.16.1
Kubernetes: 1.17
Kubernetes Client: 1.11

**Which chart**:
stable/influxdb

**What happened**:
When specifying to create a default admin user in the helm chart along with http auth enabled, the job that spawns to send a curl request to influxdb to create the admin user with password, fails, with error:
```bash
{"error":"unable to parse authentication credentials"}
```

When using the influx client with the expected username and password, no queries are able to be made, citing authorization issues.

**What you expected to happen**:
Successful creation of default user (admin) with random 10 digit string for password

**How to reproduce it** (as minimally and precisely as possible):
Here is my values.yaml:
```
persistence:
  enabled: true
  storageClass: "local-path"
  size: 4Gi

config:
  http:
    auth_enabled: true
  opentsdb:
    enabled: true
    bind_address: 4242
    database: opentsdb
    retention_policy: autogen
    consistency_level: one
    tls_enabled: false
    certificate: /etc/ssl/influxdb.pem
    batch_size: 1000
    batch_pending: 5
    batch_timeout: 1s
    log_point_errors: true

setDefaultUser:
  enabled: true

initScripts:
  enabled: true
  scripts:
    init.iql: |+
      CREATE DATABASE "testdb"
```

**Anything else we need to know**:
I am using k3s as opposed to k8s.
I've tried only using the influxdb default image and 1.7.9.
