### ISSUE TITLE
[stable/prometheus-operator] grafana.ingress.paths parameter does not exist

### ISSUE THREAD

**Issue by slikk66** [helm/charts#20740]
We're setting this up on AWS EKS for:

prometheus we have:
````
prometheus:
  ingress:
    paths:
      - "/*"
````

And alertmanager we have:
````
alertmanager:
  ingress:
    paths:
      - "/*"
````

But this option does not exist for `grafana.ingress` so we can't set it up properly.

Seems like a bug!
