### ISSUE TITLE
[stable/spinnaker] Truncating newline after password-file (and password-command) triggers error

### ISSUE THREAD

**Issue by dpkirchner** [helm/charts#20772]
**Describe the bug**

Adding a docker registry results in an error when the hal install script runs.

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.8", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T00:50:57Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

`stable/spinnaker`

**What happened**:

```
Problems in Global:
! ERROR No account with name "gcr" was found
? Check if this account was defined in another provider, or create
  a new one
- Failed to get account gcr for provider dockerRegistry.
+ PROVIDER_COMMAND=add
+ CREDS=
+ CREDS+='--username _json_key'
+ CREDS+=' --password-file /opt/registry/passwords/gcrCREDS+= --email sa@project.iam.gserviceaccount.com'
+ hal --daemon-endpoint http://cd-spinnaker-halyard:8064 config provider docker-registry account add gcr --address https://gcr.io --username _json_key --password-file /opt/registry/passwords/gcrCREDS+= --email sa@project.iam.gserviceaccount.com
+ Get current deployment
  Success
- Add the gcr account
  Failure
Problems in default.provider.dockerRegistry.gcr:

! ERROR Cannot find provided path:
  /opt/registry/passwords/gcrCREDS+= (No such file or directory).:
  /opt/registry/passwords/gcrCREDS+= (No such file or directory).
```

**What you expected to happen**:

I expected it the installer to successfully use the specified registry.

**How to reproduce it** (as minimally and precisely as possible):

Install the chart with a values.yaml that specifies a docker registry:

```
  dockerRegistries:
  - name: dockerhub
    address: index.docker.io
    repositories:
      - library/alpine
      - library/ubuntu
      - library/centos
      - library/nginx
  - name: gcr
    address: https://gcr.io
    username: _json_key
    password: <insert json here>
    email: sa@project.iam.gserviceaccount.com
```

**Anything else we need to know**:

I believe the error is here:

https://github.com/helm/charts/blob/master/stable/spinnaker/templates/configmap/halyard-config.yaml#L109

Removing the trailing `-` from the template resolves the issue for me, but I haven't tested it thoroughly.
