### ISSUE TITLE
[stable/prometheus-operator] SecurityContext issues, pods failing to start

### ISSUE THREAD

**Issue by marshallford** [helm/charts#20793]
**Describe the bug**

SecurityContext for various pods appear to be configured incorrectly.

**Version of Helm and Kubernetes**:

Helm: `3.0.3`
Kubernetes: `1.17.0`

**Which chart**:

`stable/prometheus-operator`

**What happened**:

```
❯ k get pods -n prometheus                                                            
NAME                                                      READY   STATUS                       RESTARTS   AGE
prometheus-operator-prometheus-node-exporter-lcd94        1/1     Running                      0          4m40s
prometheus-operator-kube-state-metrics-8467c5bdbc-jhbgd   1/2     CreateContainerConfigError   0          4m40s
prometheus-operator-operator-657dd478c4-v89jn             2/2     Running                      0          4m40s
alertmanager-prometheus-operator-alertmanager-0           1/3     CreateContainerConfigError   0          4m31s
prometheus-operator-grafana-76b444d584-9sszn              2/2     Running                      0          4m40s
prometheus-prometheus-operator-prometheus-0               1/4     CreateContainerConfigError   0          4m21s

```

```
  - image: quay.io/coreos/kube-state-metrics:v1.9.3
    imageID: ""
    lastState: {}
    name: kube-state-metrics
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: container has runAsNonRoot and image has non-numeric user (nobody),
          cannot verify user is non-root
        reason: CreateContainerConfigError
```

```
  - image: quay.io/prometheus/alertmanager:v0.20.0
    imageID: ""
    lastState: {}
    name: alertmanager
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: container has runAsNonRoot and image has non-numeric user (nobody),
          cannot verify user is non-root
        reason: CreateContainerConfigError
  - image: quay.io/coreos/configmap-reload:v0.0.1
    imageID: ""
    lastState: {}
    name: config-reloader
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: container has runAsNonRoot and image will run as root
        reason: CreateContainerConfigError
```

**What you expected to happen**:

Containers come up.

**How to reproduce it** (as minimally and precisely as possible):

values.yaml:

```
defaultRules:
    create: false

global:
    rbac:
    create: true
    pspEnabled: true

alertmanager:
    enabled: true
    podDisruptionBudget:
    enabled: true

    ingress:
    enabled: false

    serviceMonitor:
    selfMonitor: true

grafana:
    enabled: true

    rbac:
    pspEnabled: true

    defaultDashboardsEnabled: false

    admin:
    existingSecret: grafana-admin

    ingress:
    enabled: false

    persistence:
    enabled: true

    sidecar:
    dashboards:
        enabled: false
    datasources:
        enabled: true
        defaultDatasourceEnabled: true

    serviceMonitor:
    selfMonitor: true

kubeApiServer:
    enabled: true

kubelet:
    enabled: true

kubeControllerManager:
    enabled: false

coreDns:
    enabled: true

kubeDns:
    enabled: false

kubeEtcd:
    enabled: false

kubeScheduler:
    enabled: false

kubeProxy:
    enabled: false

kubeStateMetrics:
    enabled: true

kube-state-metrics:
    rbac:
    create: true
    podSecurityPolicy:
    enabled: true

nodeExporter:
    enabled: true

prometheus-node-exporter:
    rbac:
    pspEnabled: true

prometheusOperator:
    enabled: true

    manageCrds: true

    tlsProxy:
    enabled: false

    admissionWebhooks:
    failurePolicy: Fail
    enabled: true
    patch:
        enabled: false

    createCustomResource: true
    cleanupCustomResource: false

    kubeletService:
    enabled: true
    namespace: kube-system

    serviceMonitor:
    selfMonitor: true

prometheus:
    enabled: true

    servicePerReplica:
    enabled: false

    podDisruptionBudget:
    enabled: true

    ingress:
    enabled: false

    ingressPerReplica:
    enabled: false

    serviceMonitor:
    selfMonitor: true

    prometheusSpec:
    storageSpec:
        volumeClaimTemplate:
        spec:
            accessModes: ["ReadWriteOnce"]
            resources:
            requests:
                storage: 50Gi
```

**Anything else we need to know**:
