### ISSUE TITLE
stable/prometheus-rabbitmq-exporter add openshift support

### ISSUE THREAD

**Issue by mikee** [helm/charts#20797]
When deploying this chart on openshift - the security context runAsUser prevents deployment unless you allow the anyuid scc.

An easy pattern is available from other charts (check the elastic exporter chart)

Add a value for toggling the security context block
```yaml
securityContext:
  #False for openshift
  enabled: false
```
and for the deployment.yaml template add an if block
```yaml
{{ toYaml .Values.resources | indent 12 }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10002
            {{- end }}
    {{- with .Values.nodeSelector }}
```
