### ISSUE TITLE
[stable/prometheus-operator] All data was deleted after cluster upgrade

### ISSUE THREAD

**Issue by NadavkOptimalQ** [helm/charts#20790]
**Describe the bug**
I have a cluster running on azure (aks). Yesterday I upgraded the cluster from version 1.13.11 to 1.14.8 and then again to 1.15.7.
I upgraded the control plane twice and then the nodes twice.
After the upgrade all the data I had on grafana and prometheus was deleted.
The PV still exists and the PVC still exists.

**Version of Helm and Kubernetes**:
helm version:
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

kubernetes version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes

**Which chart**:
stable/prometheus-operator

**What happened**:
I upgraded the cluster and all the prometheus operator data was deleted

**What you expected to happen**:
To still have the data since I set it to use a persistent volume

**How to reproduce it** (as minimally and precisely as possible):
1. Create cluster
2. Create some graphs in grafana and collect some metrics data
3. Upgrade the cluster

**Anything else we need to know**:
values I used for the helm chart:
```
prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    enableAdminAPI: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
```
