### ISSUE TITLE
[stable/kubernetes-dashboard] Chart not yet compatible with version 2.0.x of dashboard

### ISSUE THREAD

**Issue by papanito** [helm/charts#20803]
**Describe the bug**

When deploying the `kubernetes-dashboard` to a dedicated namespace, the container does not start and fails with

```
2020/02/17 07:40:15 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:dashboard:dashboard-kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "kube-system"
```

**Version of Helm and Kubernetes**:

`helm`: `3.0.1`
`kubernetes`: `1.17.2`

**Which chart**:

`stable/kubernetes-dashboard`

**What happened**:

Container does not start and fails with

```
2020/02/17 07:40:15 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:dashboard:dashboard-kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0003833a0)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x3b4
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc00053ae00)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:494 +0xc7
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc00053ae00)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:462 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:543
main.main()
	/home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x212
```

**What you expected to happen**:

Pod starts without errors

**How to reproduce it** (as minimally and precisely as possible):

1. Create `values.dashboard.yml`
    ```
    image:
    repository: kubernetesui/dashboard
    tag: v2.0.0-rc5
    pullPolicy: IfNotPresent
    pullSecrets: []

    rbac:
    create: true
    clusterAdminRole: false
    clusterReadOnlyRole: true

    serviceAccount:
    create: true
    name:
    ```
1. Install helm chart

    ```
    helm install dashboard stable/kubernetes-dashboard --namespace dashboard -f values.dashboard.yml
    ```

**Anything else we need to know**:

It seems it does not matter what is the value for `clusterReadOnlyRole` as I tried both `true` and `false`.
Also deploying it into `kube-system` does not help.

May be related to #15118 and #9776

**Comment by papanito** [comment]
Resources: 

```
kubectl -n dashboard get role,clusterrole,rolebinding | grep dashb
role.rbac.authorization.k8s.io/dashboard-kubernetes-dashboard   85m
clusterrole.rbac.authorization.k8s.io/dashboard-kubernetes-dashboard-readonly                                85m
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard                                                   44d
```

```
kubectl -n dashboard describe role dashboard-kubernetes-dashboard
Name:         dashboard-kubernetes-dashboard
Labels:       app=kubernetes-dashboard
              chart=kubernetes-dashboard-1.10.1
              heritage=Helm
              release=dashboard
Annotations:  <none>
PolicyRule:
  Resources       Non-Resource URLs  Resource Names                     Verbs
  ---------       -----------------  --------------                     -----
  configmaps      []                 []                                 [create]
  secrets         []                 []                                 [create]
  secrets         []                 [dashboard-kubernetes-dashboard]   [get update delete]
  secrets         []                 [kubernetes-dashboard-key-holder]  [get update delete]
  configmaps      []                 [kubernetes-dashboard-settings]    [get update]
  services/proxy  []                 [heapster]                         [get]
  services/proxy  []                 [http:heapster:]                   [get]
  services/proxy  []                 [https:heapster:]                  [get]
  services        []                 [heapster]                         [proxy]
```

**Comment by papanito** [comment]
kind/bug

**Comment by papanito** [comment]
If I change the role accordingly i.e.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "kubernetes-dashboard.name" . }}
    chart: {{ template "kubernetes-dashboard.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ template "kubernetes-dashboard.fullname" . }}-readonly"
  namespace: {{ .Release.Namespace }}
rules:
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - kubernetes-dashboard-key-holder
      - {{ template "kubernetes-dashboard.fullname" . }}
      - kubernetes-dashboard-csrf
    verbs:
      - get
      - update
      - delete
```

The error is different

```
2020/02/17 17:17:06 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" not found

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc000530b00)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x3b4
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc0002b8100)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:494 +0xc7
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc0002b8100)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:462 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:543
main.main()
	/home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x212
```

The helm chart itself does not seem to create any `csrf` at least I don't find a reference
