### ISSUE TITLE
[stable/phpmyadmin] unnecessary rewrite-target ingress annotation

### ISSUE THREAD

**Issue by runningman84** [helm/charts#20814]
**Describe the bug**
The chart always creates an annotation for a rewrite-target. From my point of view these annotations should be optional. Because since helm3 you cannot delete / overwrite them with null. Our setup using traefik is therefore broken. 

**Version of Helm and Kubernetes**:
helm 3.1
kubernetes 1.14

**Which chart**:
stable/phpmyadmin

**What happened**:
All requests (like css) get rewritten to /.

**What you expected to happen**:
Do not change any requests.

**How to reproduce it** (as minimally and precisely as possible):
Install the phpmyadmin chart and enable traefik ingress

**Anything else we need to know**:
It looks like nginx and traefik work different in this usecase:
https://github.com/containous/traefik/issues/5185

@carrodher maybe you can take a look into that.

**Comment by juan131** [comment]
Hi @runningman84 

These are the default annotations (taken from [values.yaml](https://github.com/helm/charts/blob/master/stable/phpmyadmin/values.yaml)):

```yaml
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
```

You can rewrite them by overwriting the `ingress.annotations` parameter, but it's true you'll obtain some warning from Helm3. E.g. using a custom `values.yaml` as shown below:

```console
$ cat > values.yaml <<'EOF'
ingress:
  enabled: true
  annotations: null
EOF
$ helm template phpmyadmin stable/phpmyadmin -f values.yaml -s templates/ingress.yaml
coalesce.go:196: warning: cannot overwrite table with non table for annotations (map[ingress.kubernetes.io/rewrite-target:/ nginx.ingress.kubernetes.io/rewrite-target:/])
coalesce.go:196: warning: cannot overwrite table with non table for annotations (map[ingress.kubernetes.io/rewrite-target:/ nginx.ingress.kubernetes.io/rewrite-target:/])
---
# Source: phpmyadmin/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  ...
  annotations:
spec:
  ...
```

However, it's just a warning. It shouldn't block you to install the chart.

**Comment by runningman84** [comment]
The problem is that we need additional annotations for https redirect and so on.

Using flux/helm-operator it was not possible to deploy a setup like this:
```
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        ingress.kubernetes.io/rewrite-target: null
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        ingress.kubernetes.io/auth-response-headers: X-Id-Token,X-Access-Token,Authorization
        ingress.kubernetes.io/auth-type: forward
```
