### ISSUE TITLE
[stable/prometheus-operator] How to setup saml for Grafana?

### ISSUE THREAD

**Issue by pgronkiewicz** [helm/charts#20820]
Is this a request for help?: Yes

Version of Helm and Kubernetes:
helm: v3.0.2
kubernetes: v1.15.9

Which chart: [stable/prometheus-operator]

Hi, what is the correct way to enable SAML auth for Grafana? 

I have tried for now to configure env variables, as per Grafana [documentation](https://grafana.com/docs/grafana/latest/auth/saml/) in values.yaml:

```
grafana:
  enabled: true

  env:
    GF_AUTH_SAML_ENABLED: true
    GF_AUTH_SAML_CERTIFICATE: "<base64 certificate>"
    GF_AUTH_SAML_PRIVATE_KEY: "<base64 private key>"
    GF_AUTH_SAML_IDP_METADATA: "<base64 xml metadata>"
```

I can see that those variables get into the Grafana pod and configuration gets replaced. But when I enter into grafana url, it does not redirect me to Google for SAML auth, but instead uses the default built-in admin user.

How can I setup Grafana for using SAML through the prometheus operator properly?
