### ISSUE TITLE
[stable/metallb] Add defining priorityClassName to pods

### ISSUE THREAD

**Issue by acceptMyPR** [helm/charts#20840]
**Is your feature request related to a problem? Please describe.**
Please add ability to define priorityClassName in pods of deployment metallb-controller and daemonset metallb-speaker in values.yaml.
I want it, because if there is insufficient hardware resources at node and if where is not priorityClassName in metallb pod higher whan other services like my apps,  kubernetes can evict metallb pods before evict another non system pods.

**Describe the solution you'd like**
For example, this lines in templates can be added
in controller.yaml
```
{{- if .Values.controller.priorityClassName }}
      priorityClassName: "{{ .Values.controller.priorityClassName }}"
```
in speaker.yaml
```
{{- if .Values.speaker.priorityClassName }}
      priorityClassName: "{{ .Values.controller.priorityClassName }}"
```
and  in values.yaml:
```
controller:
  priorityClassName: "customCriticalClass"
speaker:
  priorityClassName: "customCriticalClass"
```
