### ISSUE TITLE
[stable/traefik] jaeger tracing error in TOML

### ISSUE THREAD

**Issue by Atharex** [helm/charts#20868]
**Describe the bug**
When I want to enable jaeger tracing in the traefik helm chart, the values get incorrectly passed into the chart and break the deployment.

I use the following segment to enable jaeger
```
tracing:
  enabled: true
  serviceName: traefik
  backend: jaeger #choices are jaeger, zipkin, datadog
  jaeger:
    localAgentHostPort: "127.0.0.1:6831"
    samplingServerURL: "http://localhost:5778/sampling"
    samplingType: const
    samplingParam: 1.0
```

And after the deployment I get a CrashLoopBackOff because of a faulty config:

`2020/02/19 09:05:15 Error reading TOML config file /config/traefik.toml : toml: cannot load TOML value of type int64 into a Go float`

The generated TOML looks like this:
```
apiVersion: v1
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    InsecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
      [entryPoints.traefik]
      address = ":8080"
      [entryPoints.prometheus]
      address = ":9100"
    [ping]
    entryPoint = "http"
    [kubernetes]
    [traefikLog]
      format = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
    [metrics]
      [metrics.prometheus]
        entryPoint = "prometheus"
    [tracing]
      backend = "jaeger"
      serviceName = "traefik"
      [tracing.jaeger]
        localAgentHostPort = "127.0.0.1:6831"
        samplingType = "const"
        samplingParam = 1
```

So it seems to me somewhere along the way the float gets converted to int and injected into the toml, which breaks the config. If I manually` kubectl edit cm` and set the `samplingParam` from 1 to 1.0, the deployment starts working.

This conversion should be fixed in the helm chart

**Which chart**:
stable/traefik
