### ISSUE TITLE
problem with ingrass nginx Grafana , If you're seeing this Grafana has failed to load its application files 

### ISSUE THREAD

**Issue by waelghaith** [helm/charts#20880]
I have this message 
```
If you're seeing this Grafana has failed to load its application files 

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help
```
ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  creationTimestamp: "2020-02-19T09:44:24Z"
  generation: 14
  labels:
    app: grafana
    chart: grafana-4.3.2
    heritage: Helm
    release: monitor
  name: monitor-grafana
  namespace: monitoring
  
spec:
  rules:
  - host: ****.com
    http:
      paths:
      - backend:
          serviceName: monitor-grafana
          servicePort: 3000
        path: /grafana/?(.*)
status:
  loadBalancer: {}
```

with :
```

grafana.ini: 
     [server]
         root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

```
where is the problem?!
