### ISSUE TITLE
[stable/postgresql] data directory "/bitnami/postgresql/data" has invalid permissions

### ISSUE THREAD

**Issue by acim** [helm/charts#20923]
**Describe the bug**
After upgrade from 8.3.4 to 8.4.0 pod is crashing with message:

```
postgresql 12:46:44.18 INFO  ==> ** Starting PostgreSQL **
2020-02-21 12:46:44.204 GMT [1] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
2020-02-21 12:46:44.204 GMT [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```

**Version of Helm and Kubernetes**:

Helm 3.1.1
Kubernetes 1.17.3

**Which chart**:

stable/postgresql 8.4.0

**What happened**:

Crash.

**What you expected to happen**:

Run.

**How to reproduce it** (as minimally and precisely as possible):

Just upgrade from 8.3.4 to 8.4.0.

**Anything else we need to know**:

Init container init-chmod-data seems to be removed and it seems it is still needed.

**Comment by jim-barber-he** [comment]
I just hit this myself.
The default for `volumePermissions.enabled` changed from `true` to `false`.
Setting it to `true` should get things going again.

**Comment by jim-barber-he** [comment]
It was broken by this change I think.
https://github.com/helm/charts/pull/20910

**Comment by javsalgar** [comment]
Hi,

Good to know that it was just enabling the volumePermissions container. As stated in the PR, this is not compatible with all platforms that's why we're setting it to false by default. Do not hesitate to open a new ticket if you find any other issue.

**Comment by acim** [comment]
I tried volumePersmissions=enabled, but it still doesn't work with the same error:

```
postgresql 10:48:52.27 INFO  ==> ** Starting PostgreSQL **
2020-02-24 10:48:52.305 GMT [1] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
2020-02-24 10:48:52.305 GMT [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```
The difference between 8.3.4 and 8.4.0 with this flag are really minor:
```
  # Source: postgresql/templates/statefulset.yaml
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: postgresql-postgresql
    labels:
      app: postgresql
-     chart: postgresql-8.3.4
+     chart: postgresql-8.4.0
      release: "postgresql"
      heritage: "Helm"
  spec:
    serviceName: postgresql-headless
    replicas: 1
    updateStrategy:
      type: RollingUpdate
    selector:
      matchLabels:
        app: postgresql
        release: "postgresql"
        role: master
    template:
      metadata:
        name: postgresql
        labels:
          app: postgresql
-         chart: postgresql-8.3.4
+         chart: postgresql-8.4.0
          release: "postgresql"
          heritage: "Helm"
          role: master
      spec:      
        securityContext:
          fsGroup: 1001
        initContainers:
          - name: init-chmod-data
            image: docker.io/bitnami/minideb:buster
            imagePullPolicy: "Always"
            resources:
              requests:
                cpu: 250m
                memory: 256Mi
            command:
              - /bin/sh
              - -cx
              - |
-               echo "current user id: `id`"
+               
                mkdir -p /bitnami/postgresql/data
                chmod 700 /bitnami/postgresql/data
                find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
                  xargs chown -R 1001:1001
                chmod -R 777 /dev/shm
            securityContext:
              runAsUser: 0
            volumeMounts:
+             
              - name: data
                mountPath: /bitnami/postgresql
                subPath: 
              - name: dshm
                mountPath: /dev/shm
        containers:
          - name: postgresql
            image: docker.io/bitnami/postgresql:11.7.0-debian-10-r0
            imagePullPolicy: "IfNotPresent"
            resources:
              requests:
                cpu: 250m
                memory: 256Mi
            securityContext:
              runAsUser: 1001
            env:
              - name: BITNAMI_DEBUG
                value: "false"
              - name: POSTGRESQL_PORT_NUMBER
                value: "5432"
              - name: POSTGRESQL_VOLUME_DIR
                value: "/bitnami/postgresql"
              - name: PGDATA
                value: "/bitnami/postgresql/data"
              - name: POSTGRES_USER
                value: "postgres"
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgresql-password
              - name: POSTGRESQL_ENABLE_LDAP
                value: "no"
            ports:
              - name: tcp-postgresql
                containerPort: 5432
            livenessProbe:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 6
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - -e
                  - |
                    exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
                    [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 6
            volumeMounts:
              - name: dshm
                mountPath: /dev/shm
              - name: data
                mountPath: /bitnami/postgresql
                subPath: 
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 1Gi
    volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: "10Gi"
```
And I don't see why this would affect the problem. There must be something else.

**Comment by acim** [comment]
It worked, but I had to uninstall the chart first and then install again. It seems this init is not executed on each start.

**Comment by jim-barber-he** [comment]
FYI, for us, we have a pretty vanilla install of Kubernetes provisioned into an AWS environment using Kops.
I would have thought that would be a reasonably common scenario, so not sure why it broke for us.

**Comment by kuisathaverat** [comment]
it happens from time to time when we run `helm upgrade` without changes, when it happens we uninstall the helm chart and install it again, it is an old issue thing recurrent and unresolved https://github.com/bitnami/charts/issues/1649

**Comment by T1loc** [comment]
Same here. With this values : 

```
---
image:
  tag: 10.6.0
persistence:
  size: 8Gi
postgresqlPassword: {{ secrets.postgresql.POSTGRES_PASSWORD }}
volumePermissions:
  enabled: true
```

Running : 
  ```
 kubectl exec -it postgresql-postgresql-0 -- chmod 700 /bitnami/postgresql -R 
```
As a temporary fix...
