### ISSUE TITLE
[stable/pgadmin] How to run ingress sub path

### ISSUE THREAD

**Issue by Hokwang** [helm/charts#21046]
Hello.

I want to use pgadmin with http://my.company.com/pgadmin URL.

But I think there's some problem in here.

my value file is here.
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: my.company.com
      paths: 
        - /pgadmin(/|$)(.*)
  tls:
    - secretName: ingress-tls
      hosts:
        - my.company.com

env:
  email: admin@company.com
  password: 1qaz2wsx

persistentVolume:
  enabled: true
  storageClass: "nfs-client-stage"
```

when I access my.company.com/pgadmin, URL moved to my.company.com/login?next=%2F
and 404 error.

How can I use sub path? Is it possible?

**Comment by Hokwang** [comment]
@rowanruseler can you help me?

**Comment by Hokwang** [comment]
@dpage can you help me?

**Comment by Hokwang** [comment]
figure it out self.

```
service:
  port: 443

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Script-Name /pgadmin-stage;
  hosts:
    - host: my.company.net
      paths: 
        - /pgadmin-stage
  tls:
    - secretName: ingress-tls
      hosts:
        - my.company.net
```
