### ISSUE TITLE
[stable/airflow] airflow is not reading secret of a private github repo

### ISSUE THREAD

**Issue by ahmedspiir** [helm/charts#21057]
I'm trying to Add my private git reop to airflow
I ran this command
```bash
kubectl create secret generic my-git-secret --from-file=key=./id_rsa --from-file=known_hosts=./known_hosts --from-file=key.pub=./id_rsa.pub
```
And my YAML Look like this:
```yaml
    git:
      ##
      ## url to clone the git repository
      url: https://github.com/myorg/airflow-dags
      ##
      ## branch name, tag or sha1 to reset to
      ref: master
      ## pre-created secret with key, key.pub and known_hosts file for private repos
      secret: "my-git-secret"
      ## The host of the repo so for example if a github repo put github.com (Only need if using ssh not https git sync)
      repoHost: "github.com"
      ## The name of the private key in your git sync secret (Only need if using ssh not https git sync)
      privateKeyName: "key"
      gitSync:
        ## Turns on the side car container
        enabled: true
        ## Image for the side car container
        image:
          ## docker-airflow image
          repository: alpine/git
          ## image tag
          tag: 1.0.7
          ## Image pull policy
          ## values: Always or IfNotPresent
          pullPolicy: IfNotPresent
        ## The amount of time in seconds to git pull dags
        refreshTime: 60
    initContainer:
      ## Fetch the source code when the pods starts
      enabled: true
      ## Image for the init container (any image with git will do)
      image:
        ## docker-airflow image
        repository: alpine/git
        ## image tag
        tag: 1.0.7
        ## Image pull policy
        ## values: Always or IfNotPresent
        pullPolicy: IfNotPresent
      ## install requirements.txt dependencies automatically
      installRequirements: true

```
I'm getting a message from `git-sync` and `git-clone` pods writing
```
Cloning into '/dags'...
fatal: could not read Username for 'https://github.com': No such device or address
```
I checked the secret and it's there. So what i'm doing wrong here?
