### ISSUE TITLE
[stable/mongodb] Helm template failure 

### ISSUE THREAD

**Issue by kauphylover** [helm/charts#21082]
**Describe the bug**
I'm trying to install the mongodb chart with extraVolumes and extraVolumeMounts also configured using the following values.yaml file:
```
extraVolumes: |
  — name: mongodb-vol-secrets
    secret:
      secretName: mongodb-secrets
extraVolumeMounts: |
  - name: mongodb-vol-secrets
    mountPath: '/secrets'
    readOnly: true

```
**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Kubernetes version: 1.15.5

**Which chart**:
stable/mongodb

**What happened**:
$ helm template -f values.yml stable/mongodb --debug
install.go:158: [debug] Original chart version: ""
install.go:175: [debug] CHART PATH: /Users/amallela/Library/Caches/helm/repository/mongodb-7.8.6.tgz

Error: YAML parse error on mongodb/templates/deployment-standalone.yaml: error converting YAML to JSON: yaml: line 76: did not find expected key
helm.go:75: [debug] error converting YAML to JSON: yaml: line 76: did not find expected key
YAML parse error on mongodb/templates/deployment-standalone.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/private/tmp/helm-20200221-95404-1668hu8/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/private/tmp/helm-20200221-95404-1668hu8/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/private/tmp/helm-20200221-95404-1668hu8/src/helm.sh/helm/pkg/action/install.go:489
helm.sh/helm/v3/pkg/action.(*Install).Run
	/private/tmp/helm-20200221-95404-1668hu8/src/helm.sh/helm/pkg/action/install.go:230
main.runInstall
	/private/tmp/helm-20200221-95404-1668hu8/src/helm.sh/helm/cmd/helm/install.go:223
main.newTemplateCmd.func1
	/private/tmp/helm-20200221-95404-1668hu8/src/helm.sh/helm/cmd/helm/template.go:66
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20200221-95404-1668hu8/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20200221-95404-1668hu8/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20200221-95404-1668hu8/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/private/tmp/helm-20200221-95404-1668hu8/src/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
	/usr/local/Cellar/go/1.13.8/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.8/libexec/src/runtime/asm_amd64.s:1357

**What you expected to happen**:
My expectation was for the extraVolumes and extraVolumeMounts to get configured as part of the mongodb manifests

**How to reproduce it** (as minimally and precisely as possible):
```
$ cat <<EOF > values.yaml
extraVolumes: |
  - name: mongodb-vol-secrets
    secret:
      secretName: mongodb-secrets
extraVolumeMounts: |
  - name: mongodb-vol-secrets
    mountPath: '/secrets'
    readOnly: true
EOF

$ helm template -f values.yaml stable/mongodb --debug

```
**Anything else we need to know**:
I couldnt find an official example for how to configure extraVolumes and extraVolumeMounts. That could have been helpful.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. This is what I had in values.yaml and it worked without issues

```
extraVolumes:
  -  name: mongodb-vol-secrets
     secret:
       secretName: mongodb-secrets


## Array to add extra mounts (normally used with extraVolumes)
##
extraVolumeMounts:
  - name: mongodb-vol-secrets
    mountPath: '/secrets'
    readOnly: true
```

Could you check this is the exact format you are using? I think that the `|` that you are using is causing the problem.
