### ISSUE TITLE
[stable/rabbitmq-ha] Better support for community plugins

### ISSUE THREAD

**Issue by jlmurphysa** [helm/charts#21091]
Hi,

I'm using a single community plugin in my application and was surprised to find the chart offered no easy way to enable it.

I wanted to discuss new options to download additional files into the plugins directory before rabbitmq tries to enable them. 
I imagine it's quite a common use case, and it's quite inconvenient to have to extend the base image just to do this.

**Describe the solution you'd like**
Possibly a new `value`:
```
extraPluginFiles: ["https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez"]
``` 
Then you can just enable it as normal in the `extraPlugins` list.

**Describe alternatives you've considered**
I'm currently doing the following:
1. extending the `rabbitmq:3.8.0-alpine` image like this:
```
FROM rabbitmq:3.8.0-alpine
COPY ./rabbitmq_delayed_message_exchange-3.8.0.ez /opt/rabbitmq/plugins/
```
2. Pushing the new image to my own docker registry
3. Overriding the following values in the chart:
```
  image:
    repository: <my-registry>/rabbitmq-ha
    tag: 1
    pullSecrets: ["gcp-registry-secret"]
```

From the lack of information regarding this issue, it's very likely I've missed an easier solution (like mounting it in somehow with an initContainer).
If that's the case, I'd appreciate somebody enlightening me on the matter.

**Comment by DaveOHenry** [comment]
Storing the file into a Configmap and mapping it to a volume works fine:

values.yaml
```yaml
extraVolumeMounts: 
  - name: plugins
    readOnly: true
    mountPath: /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-20171201-3.7.x.ez
    subPath: rabbitmq_delayed_message_exchange-20171201-3.7.x.ez
extraVolumes: 
  - name: plugins
    configMap:
      name: myrabbit-rabbitmq-extra
extraPlugins: rabbitmq_delayed_message_exchange,
```

An extra Configmap / template is needed, too. This should go into the "templates" folder.
rabbitmq-extra-files-cfg.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rabbitmq-ha.fullname" . }}-rabbitmq-extra
  namespace: {{ .Release.Namespace }}
  labels:
    app: myrabbit
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
binaryData:
  rabbitmq_delayed_message_exchange-20171201-3.7.x.ez: {{ .Files.Get "files/rabbitmq_delayed_message_exchange-20171201-3.7.x.ez" | b64enc }}
```

And of course the file should be placed in the correct folder under the chart root folder.

Keep in mind that Helm has certain limitations when it comes to adding files. A chart "should" in general be under 1MB.
