### ISSUE TITLE
[external-dns] Using CloudFlare with cloudflare.secretName containing cloudflare_api_key does not work

### ISSUE THREAD

**Issue by nielsvz** [helm/charts#21147]
**Describe the bug**
When installing the external-dns chart with the CloudFlare provider and an API key in a custom `secretName` the resulting Pod fails with `CreateContainerConfigError`.

**Version of Helm and Kubernetes**:
Helm v3.1.1
Kubernetes v1.17

**Which chart**:
External-DNS 2.19.1

**What happened**:
Installing External-DNS with the following values results in the output below.

Values:
```yaml
cloudflare:
  email: dns@my-domain.com
  secretName: cloudflare-apikey
```

Output from `kubectl describe pod`:
`Warning  Failed     14s (x6 over 53s)  kubelet, minikube  Error: couldn't find key cloudflare_api_token in Secret system-external-dns/cloudflare-apikey`

**What you expected to happen**:
The External-DNS Pod should use the API key when providing both `cloudflare.email` and `cloudflare.secretName`.

**How to reproduce it** (as minimally and precisely as possible):
1. `kubectl create ns external-dns`
2. `kubectl -n external-dns create secret generic cloudflare-apikey --from-literal=cloudflare_api_token=CHANGEMEPLEASE`
3. Install the Helm chart with the values below in a `custom-values.yaml`: `helm install external-dns stable/external-dns --namespace external-dns --values custom-values.yaml`

`custom-values.yaml`:
```yaml
sources: ['ingress']
provider: cloudflare
cloudflare:
  email: dns@my-domain.com
  secretName: cloudflare-apikey
  proxied: false
```

4. Check the environment values in the external-dns Pod and find the following:
```yaml
- name: CF_API_TOKEN
    valueFrom:
    secretKeyRef:
        name: cloudflare-apikey
        key: cloudflare_api_token
```
