### ISSUE TITLE
stable/prometheus-snmp-exporter

### ISSUE THREAD

**Issue by k7faq** [helm/charts#21163]
Please help me understand what I did wrong trying to implement the stable chart. Following is what I had to change in order to get a deployed configmap.

**Describe the bug**
{{- if .Values.config }} is not properly detecting the values populated.

I had to modify the templates/configmap.yml disabling the if statement and the data field to:

```
data:
  snmp.yaml: |
{{ .Values.config | indent 4 }}
```

Following is an Example Config used in values.yml

```
config: |
  global:
    scrape_interval: 10s
    evaluation_interval: 10s
  scrape_configs:
  - job_name: 'snmp'
    metrics_path: /snmp
    static_configs:
    - targets:
      - 10.0.0.243  # SNMP device - add your IPs here
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter.
```

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ k version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus-snmp-exporter/templates/configmap.yml

**What happened**:
Error: template: prometheus-snmp-exporter/templates/configmap.yaml:14:27: executing "prometheus-snmp-exporter/templates/configmap.yaml" at <2>: wrong type for value; expected string; got map[string]interface {}

Helm failed to create Configmap.

**What you expected to happen**: [ After modifying files as noted above ]

```
NAME: snmp02
LAST DEPLOYED: Sun Mar  1 21:30:04 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
See https://github.com/prometheus/snmp_exporter/ for how to configure Prometheus and the SNMP Exporter.
````

**How to reproduce it** (as minimally and precisely as possible):

```
helm install snmp02 -f ./prometheus-snmp-exporter/values.yaml stable/prometheus-snmp-exporter
```

**Anything else we need to know**:

**Comment by jfcgaspar** [comment]
@k7faq I could be wrong, but isn't `config` supposed to be the configurations for the OIDs and metrics definition of what you wish to collect via snmp ?

Anyway, I'm encountering the same issue as reported. I had to make the following changes to configmap.yml to make it work.

```
{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-snmp-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-snmp-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-snmp-exporter.chart" . }}
data:
  snmp.yaml: |
{{ toYaml .Values.config | default "{}" | indent 4 }}
{{- end }}
```

/reopen
