### ISSUE TITLE
[stable/external-dns] Support Azure MSI with AAD-Pod-Identity

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/charts#21221]
**Is your feature request related to a problem? Please describe.**
When deploying external-dns on Azure, the MSI mode for authentication can be configured with [AAD-Pod-Identity](https://github.com/Azure/aad-pod-identity/).

**Describe the solution you'd like**
I'd like to be able to use a pre-existing AAD-Pod-Identity deployment to configure Azure credentials using MSI.

See https://github.com/Azure/application-gateway-kubernetes-ingress/blob/b18d1c7e5c403e5ee7ff303dedfc242a8c4839d3/helm/ingress-azure/templates/aadpodidbinding.yaml and https://github.com/Azure/application-gateway-kubernetes-ingress/blob/b18d1c7e5c403e5ee7ff303dedfc242a8c4839d3/helm/ingress-azure/templates/aadpodidentity.yaml for an example of a helm chart depending on AAD-Pod-Identity.

**Describe alternatives you've considered**
Currently I manually deploy AzureIdentity and AzureIdentityBindings before creating the external-dns helm release. I'd like it to be integrated in the helm chart.

**Additional context**
See also https://github.com/kubernetes-sigs/external-dns/issues/1456

What I did to make it work:
- created 2 new k8s resources:
```yaml
# Please see https://github.com/Azure/aad-pod-identity for more information
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: external-dns
spec:
  type: 0
  ResourceID: ${ResourceID}
  ClientID: ${ClientID}

---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: external-dns
spec:
  AzureIdentity: external-dns
  Selector: external-dns
```

- use these values for azure config:
```yaml
azure:
  resourceGroup: "${resourceGroup}"
  tenantId: "${tenantId}"
  subscriptionId: "${subscriptionId}"
  useManagedIdentityExtension: true
podLabels:
  aadpodidbinding: external-dns
```
