### ISSUE TITLE
[stable/prometheus-pushgateway] has hard-coded path for ingress

### ISSUE THREAD

**Issue by joesteffee** [helm/charts#21224]
Using v 1.1.0

The spec for pushgateway has a hard-coded path as "/":

```
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}   
```

which means using an ingress controller such as ALB will not work properly. ALB requires the path be set to "/*" and not "/".

The / should be set to whatever ingress path is, for example like what is in grafana:

```
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
{{ if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
```
