### ISSUE TITLE
[stable/fluent-bit, stable/fluentd] Move source to a new charts repo

### ISSUE THREAD

**Issue by naseemkullah** [helm/charts#21235]
Hello,

@scottrigby and I are in the process of preparing these charts [new home](https://github.com/fluent/helm-charts).

Are you all on board and would like to continue maintaining the charts? Please let us know :)

fluent-bit:
@kfox1111
@hectorj2f
@Towmeykaw

fluentd:
@rendhalver
@miouge1
@hectorj2f

**Comment by Miouge1** [comment]
@naseemkullah sounds good.

One of the nice things that the [helm/charts](https://github.com/helm/charts) repo provides is the CI (`helm lint`, DCO checker, version bump checker, E2E tests etc...).  Do you have plans for some automated CI in the new repo?

**Comment by naseemkullah** [comment]
> @naseemkullah sounds good.

>  Do you have plans for some automated CI in the new repo?

Indeed we do! We will be using the latest and greatest in github actions for our CI. See https://github.com/helm/charts-repo-actions-demo/ for an example of what we'll be doing.

**Comment by Towmeykaw** [comment]
@naseemkullah 👍

**Comment by naseemkullah** [comment]
@rendhalver @kfox1111 @hectorj2f Please advise as to wether or not you are on board with this! If so you will be retained as maintainers. :) Cheers.

**Comment by naseemkullah** [comment]
Hey @Miouge1 it seems like the fluentd chart doesnt use an official fluentd image, im not sure we could move it as is, if there were a chart that basically packaged https://github.com/fluent/fluentd-kubernetes-daemonset that could probably work.

**Comment by naseemkullah** [comment]
Hello @Towmeykaw @kfox1111 @hectorj2f ,

The config values + templating is really unwieldy, if we could achieve something simpler and more flexible (without having to bubble up all possible config options) but in a breaking manner, i think this would be good to do during the moving of the chart. thoughts? Or should we address this like any breaking PR either here or post-move?

**Comment by naseemkullah** [comment]
https://github.com/fluent/helm-charts/tree/master/charts/fluent-bit#breaking-changes-ahead

**Comment by naseemkullah** [comment]
I'm thinking something along the lines of:


values file:
```yaml
config:
  ## Ref: https://docs.fluentbit.io/manual/service
  service:
    Flush: 1
    Daemon: Off
    Log_Level:  info
    Parsers_File: parsers.conf
    Parsers_File: parsers_custom.conf
    HTTP_Server:  On
    HTTP_Listen:  0.0.0.0
    HTTP_Port:    2020

  ## Ref: https://docs.fluentbit.io/manual/input
  inputs:
    - Name: tail
      Path: /var/log/containers/*.log
      Parser: docker
      Tag: kube.*
    - Name: systemd
      Tag: host.*
      Systemd_Filter: _SYSTEMD_UNIT=kubelet.service

  ## Ref: https://docs.fluentbit.io/manual/filter
  filters:
    - Name: kubernetes
      Match: kube.*
      Merge_Log: On
      K8S-Logging.Parser:  On
      K8S-Logging.Exclude: On

  ## Ref: https://docs.fluentbit.io/manual/output
  outputs:
    - Name: es
      Match: "*"
      Host: elasticsearch-master.logging.svc
      Logstash_Format: On

  ## Ref: https://docs.fluentbit.io/manual/parser
  customParsers:
    - Name: docker_no_time
      Format: json
      Time_Keep: Off
      Time_Key: time
      Time_Format: "%Y-%m-%dT%H:%M:%S.%L"
```

confgmap:

```
  custom-parsers.conf: |
    {{- range $parser := .Values.config.customParsers }}
    [PARSER]
      {{- range $key, $value := index $parser }}
        {{ $key }} = {{ $value }}
      {{- end }}
    {{- end }}

  fluent-bit.conf: |
    [SERVICE]
      {{- range $key, $value := index .Values.config.service }}
        {{ $key }} = {{ $value }}
      {{- end }}

    {{- range $input := .Values.config.inputs }}
    [INPUT]
      {{- range $key, $value := index $input }}
        {{ $key }} = {{ $value }}
      {{- end }}
    {{- end }}

    {{- range $filter := .Values.config.filters }}
    [FILTER]
      {{- range $key, $value := index $filter }}
        {{ $key }} = {{ $value }}
      {{- end }}
    {{- end }}

    {{- range $output := .Values.config.outputs }}
    [OUTPUT]
      {{- range $key, $value := index $output }}
        {{ $key }} = {{ $value }}
      {{- end }}
    {{- end }}
```

It will make the chart way cleaner, mind you if people want to mount secrets and such, they will have to provide that as extraSecrets/extraVolumes and what not. That's to say no more logic based on `if backend.foo.bar` ....thoughts @kfox1111 @hectorj2f @Towmeykaw ?
