### ISSUE TITLE
[stable/postgresql] volumePermissions.securityContext.runAsUser: "auto" is not integer

### ISSUE THREAD

**Issue by tctovsli** [helm/charts#21295]
**Describe the bug**
According to values.yaml and README.md, a special value of "auto" can be used to the key volumePermissions.securityContext.runAsUser. When installing/upgrading with helm3, it won't validate the value:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.initContainers[0].securityContext.runAsUser): invalid type for io.k8s.api.core.v1.SecurityContext.runAsUser: got "string", expected "integer"`

**Version of Helm and Kubernetes**:
Helm version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Kubernetes version: 
openshift v3.11.161
kubernetes v1.11.0+d4cacc0

**Which chart**:
stable/postgresql

**What happened**:
Validation failed.

**What you expected to happen**:
The value "auto" should be accepted.

**How to reproduce it** (as minimally and precisely as possible):
`helm install postgres stable/postgresql --set volumePermissions.securityContext.runAsUser="auto"` I guess.

**Anything else we need to know**:
This occured during installation of the chart codecentric/keycloak with postgresql as a dependency.

**Comment by miguelaeh** [comment]
Hi @tctovsli ,
If that didn't work for you I recommend you to disable the `securityContext`. In that way the `runAsUser` will be the random user set by Openshift and the `fsGroup` will be configured for that user automatically.

**Comment by josro** [comment]
Auto

**Comment by tctovsli** [comment]
> Hi @tctovsli ,
> If that didn't work for you I recommend you to disable the `securityContext`. In that way the `runAsUser` will be the random user set by Openshift and the `fsGroup` will be configured for that user automatically.

Thanks. Turning off `volumePermissions.enabled` resolved it for me. I would still recommend updating README.md and comments or something regarding this.

**Comment by tctovsli** [comment]
Hmm, it seems like it wasn't solved just yet.
After deleting the pod, when the new pod appears it gives an error:
```FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```
I have the following set in values.yaml:
```postgresql:
  persistence:
    enabled: true
  postgresqlDatabase: keycloak
  postgresqlPassword: ""
  postgresqlUsername: keycloak
  securityContext:
    enabled: true
  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: 1001
```

**Comment by miguelaeh** [comment]
Hi @tctovsli ,
I guess that could be because the new pod is not running with the same user as the killed one.
Could you check that?

**Comment by tctovsli** [comment]
@miguelaeh The pod has been set to run with `runAsUser: 1001`.
When I check out the owner of the files from the node, it is owned by `1001880000`.
Not sure why.

**Comment by tctovsli** [comment]
OK, so now I deleted the PV and reinstalled from the helm chart.
The owner of the `/bitnami/postgresql/data` seems to be UID 1001 (I checked this from the kubernetes node that has the PV mounted).
But as the error indicates, the permissions are wrong:
```
# stat data
  File: ‘data’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 840h/2112d      Inode: 67          Links: 19
Access: (2760/drwxrwS---)  Uid: ( 1001/ username)   Gid: ( 1001/usergroup)
Context: system_u:object_r:container_file_t:s0:c37,c43
Access: 2020-03-09 12:13:10.031961391 +0100
Modify: 2020-03-09 12:11:22.941359605 +0100
Change: 2020-03-09 12:13:09.620989131 +0100
 Birth: -
```

**Comment by miguelaeh** [comment]
Hi @tctovsli ,
> The pod has been set to run with runAsUser: 1001.
When I check out the owner of the files from the node, it is owned by 1001880000.

That is how OpenShift works. It by default uses a random user and group. Disabling the `securityContext` it should try to set the random user and the `fsGroup` correctly for that user.
You should not be setting the `runAsUser` to `1001`, setting that Openshift will not modify the user, while if you don't set it, Openshift will set the correct one and the correct `fsGroup`

**Comment by tctovsli** [comment]
OK, so how should I fix this then? If I just remove the values from value.yaml, they will fall back to the defaults.
This is my current setup, which seems to be OK with regards to UID allocation, but the permissions on the data-folder seems to be wrong when the pod is restarted:
```
postgresql:
  persistence:
    enabled: true
  securityContext:                                                                                                                                                                 
    enabled: true                                                                                                                                                                  
    fsGroup: 1001                                                                                                                                                                  
    runAsUser: 1001                                                                                                                                                                
  volumePermissions:                                                                                                                                                               
    enabled: false                                                                                                                                                                 
    securityContext:                                                                                                                                                               
      runAsUser: 1001                                                                                                                                                              
```

**Comment by tctovsli** [comment]
Seems like I hit the same as this guy: #20923

When I enable `volumePermissions` (without any `securityContext` defined), I get an error from the StatefulSet that it is outside the constraint.
When I disable `volumePermissions`, and delete the postgresql-pod, I get an error that the permissions are wrong.

Not sure if it is configuration or a bug. Any tips?

**Comment by yaroslavkasatikov** [comment]
Hi guys,

I have faced to the same today and solved it with this:

```
 volumePermissions:
    enabled: true
    securityContext:
      runAsUser: Null
```
