### ISSUE TITLE
[stable/redmine] Unable to specify TLS configuration

### ISSUE THREAD

**Issue by scristalli** [helm/charts#21302]
**Describe the bug**
I try to specify a custom configuration for TLS certificates following the README, but I get an error when installing the chart:
`"Error: UPGRADE FAILED: template: redmine/templates/tls-secrets.yaml:7:14: executing \"redmine/templates/tls-secrets.yaml\" at <include \"redmine.labels\" .>: error calling include: template: redmine/templates/_helpers.tpl:6:18: executing \"redmine.name\" at <.Chart.Name>: nil pointer evaluating interface {}.Name"`

**Version of Helm and Kubernetes**:
Helm 3.1.1

**Which chart**:
Redmine

**Anything else we need to know**:
The values I specified:
```
redmine:
  secrets:
    tls:
      name: my-secret-name
      certificate: tls.crt
      key: tls.key
```

Is it possible that this is related to https://github.com/helm/helm/issues/3684?
