### ISSUE TITLE
[stable/redis] Slave not working with Persistence

### ISSUE THREAD

**Issue by bframke** [helm/charts#21329]
**Describe the bug**
When trying to deploy a Redis Slave with Persistence it does not work correctly and tells me this:
`Can't chdir to '/mnt/redis': No such file or directory`
The directory exists and has the correct fsGroup.

In the description of the statefulset for the slave the mount is missing. In the master it is like this `/mnt/redis from redis-data (rw,path="master")`

It is also crashing, when Persistence is disabled.

**Version of Helm and Kubernetes**:
Latest stable version

**Which chart**:
stable/redis

**What happened**:
Slave crashes when using Persistence.
`Can't chdir to '/mnt/redis': No such file or directory`

**What you expected to happen**:
It works

**How to reproduce it** (as minimally and precisely as possible):
Try to deploy the latest stable release with persistence for slave
Example from the values.yaml
```
persistence:
    enabled: true
    path: /mnt/redis
    subPath: "slave"
    storageClass: "filesystem"
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    matchLabels: {}
    matchExpressions: {}
```

**Anything else we need to know**:
-
