### ISSUE TITLE
[stable/prometheus-operator] wrong metrics for cpu limit in workload on k8s > 1.15

### ISSUE THREAD

**Issue by rjshrjndrn** [helm/charts#21341]
**Describe the bug**
```
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
```

![image](https://user-images.githubusercontent.com/2563385/76227805-dab85380-6245-11ea-9052-c686e76d7fb4.png)

**Version of Helm and Kubernetes**:
❮ helm version --short
v3.1.1+gafe7058

❯ helm ls -n default
NAME            NAMESPACE       REVISION        UPDATED                                STATUS   CHART                           APP VERSION
prometheus      default         1               2020-03-09 20:48:42.034971834 +0530 ISTdeployed prometheus-operator-8.11.1      0.36.0

❮ kubectl version --short
Client Version: v1.16.0
Server Version: v1.16.2-k3s.1

**Which chart**:
stable/prometheus-operator

**What you expected to happen**:
Show correct CPU limit

**How to reproduce it** (as minimally and precisely as possible):
helm install prometheus stable/prometheus-operator

> This chart is working fine in kubernetes version 1.14.5  
❮ k version --short
Client Version: v1.16.0
Server Version: v1.14.5-k3s.1
