### ISSUE TITLE
stable/chart/fluentd not having option for multiple ports 

### ISSUE THREAD

**Issue by bkannadassan** [helm/charts#21377]
```
  ports:
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
    - name: "fluentd-fwd-port"
      port: 24224
      targetPort: 24224
      protocol: TCP
```
Why multiple ports option not giving here ?. I see the same given in daemonset, I am adding one additional for me here but anyways I can change the helm as well. But would like to know any reason behind the same..

rgds
Balaji Kamal Kannadassan
