### ISSUE TITLE
[stable/redis-ha] Redis password with special characters can break haproxy config

### ISSUE THREAD

**Issue by MRostanski** [helm/charts#21449]
**Bug description**
When redisPassword is set up with special characters, for example `#`, the configuration for haproxy is faulty.

**Version of Helm and Kubernetes**:

Helm: 3.1.1

Kubernetes: 1.13.12-gke.25

**Which chart**:

stable/redis-ha

**What happened**:

We have deployed `stable/redis-ha` with values:

```yaml
auth: enable
redisPassword: <REDACTED_PASSWORD_WITH_#_CHARACTER INSIDE> 
haproxy:
  enabled: true
```

Haproxy service has no active backend and drops connections.

**What you expected to happen**:

The Redis cluster is deployed with addidtional haproxy service that directs requests to master only.

**How to reproduce it** (as minimally and precisely as possible):

Deploy stable/redis with values as above. Create password with $, &, # characters in it.

**Anything else we need to know**:

Happy helming!
