### ISSUE TITLE
[stable/oauth2-proxy] Support https redirect with AWS ALB Ingress Controller

### ISSUE THREAD

**Issue by KIVagant** [helm/charts#21484]
**Is your feature request related to a problem? Please describe.**

The oauth2-proxy supports http-to-https redirect but this feature requires the TLS termination to be done on the proxy side. If it is implemeted on a balancer side, like AWS ALB, the `-force-https` cli argument won't work with this chart. Because the pod will never start (liveness probes will return:

```
Liveness probe failed: Get http://10.56.17.57:4180/ping: failed to parse Location header ":443": parse :443: missing protocol scheme
```

But to do the redirect on the ALB side, using [ALB Ingress Controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller), a specific [setting must be added](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/) to the Ingress definition:

```yaml
    - http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
```

In this chart it is already possible to define all necessary `.Values.ingress.annotations` for the ingress. But it is not possible to add the additional `backend` section to the paths (and any other path settings for other use cases).

**Describe the solution you'd like**

Support `ssl-redirect` service name as the ingress backend to do the http-to-https redirect with AWS ALB Ingress Controller:

```yaml
# ingress.yaml
# ...
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect # the new backend should appear here somehow
              servicePort: use-annotation
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
...
```
