### ISSUE TITLE
[stable/prometheus-operator] <$prometheusRule.additionalLabels>: can't evaluate field additionalLabels in type interface {}

### ISSUE THREAD

**Issue by lyz-code** [helm/charts#21496]
**Describe the bug**
Unable to add `PrometheusRule`s with `additionalPrometheusRulesMap`.

**Version of Helm and Kubernetes**:
```bash
helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
```yaml
- name: prometheus-operator
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 8.10.0
```

**What happened**:

Helm diff gave the following error:

```
  Error: render error in "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml": template: prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml:15:26: executing "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" at <$prometheusRule.additionalLabels>: can't evaluate field additionalLabels in type interface {}
```

**What you expected to happen**:

Add the rule.

**How to reproduce it** (as minimally and precisely as possible):

Add the following rule:

```yaml
additionalPrometheusRulesMap:
  groups:
    - name: alert-rules
      rules:
        - alert: BlackboxProbeFailed
          expr: probe_success == 0
          for: 5m
          labels:
            severity: error
          annotations:
            summary: "Blackbox probe failed (instance {{ $labels.instance }})"
            description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

Run `helm diff`.

**Anything else we need to know**:

I've checked the [PrometheusRule spec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusrulespec) and all the `api.md` and found no key `additionalLabels` specified in the [additionalPrometheusRules.yaml](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml#L15) template.

As I'm using a private EKS cluster I had to disable the `admissionWebhooks`.

**Comment by lyz-code** [comment]
It was a syntax error:

```
additionalPrometheusRulesMap:
  - groups:
      - name: alert-rules
        rules:
          - alert: BlackboxProbeFailed
            expr: probe_success == 0
            for: 5m
            labels:
              severity: error
            annotations:
              summary: "Blackbox probe failed (instance {{ $labels.target }})"
              description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

Worked, It would be nice though to have an example in the `values.yaml` as right now it has the soon to be deprecated `additionalPrometheusRules` example.
