### ISSUE TITLE
[stable/datadog] Live Container monitoring doesn't work helm chart v2

### ISSUE THREAD

**Issue by bubalush** [helm/charts#21495]
**Describe the bug**
After update to helm chart v2 Live Container monitoring (via UI) doesn't work anymore. Infrastructure - Containers (Datadog UI). I tried to use datadog agent image tag 7.17.0, 7.17.1, 7.18.0

**Version of Helm and Kubernetes**:
AWS EKS 1.14.9
Helm 2.14

**Which chart**:
stable/datadog v2.0.6/7

**How to reproduce it** (as minimally and precisely as possible):
Use the following values:
```yaml
agents:
  image:
    tag: 7.18.0
  volumes:
    - hostPath:
        path: /var/log/journal
      name: kubelet-logs
    - name: empty-dir
      emptyDir: {}
  volumeMounts:
    - name: kubelet-logs
      mountPath: /var/log/journal
      readOnly: true
    # https://docs.datadoghq.com/agent/faq/kubernetes-state-cluster-check/
    - name: empty-dir
      mountPath: /etc/datadog-agent/conf.d/kubernetes_state.d
      readOnly: true
    - name: empty-dir
      mountPath: /etc/datadog-agent/conf.d/cri.d
      readOnly: true
    - name: empty-dir
      mountPath: /etc/datadog-agent/conf.d/redisdb.d
      readOnly: true
  useHostPort: true
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists
      effect: NoExecute
    - operator: Exists
      effect: NoSchedule
  containers:
    agent:
      resources:
      limits:
        cpu: 200m
        memory: 256Mi
    traceAgent:
      resources:
      limits:
        cpu: 200m
        memory: 256Mi

datadog:
  collectEvents: true
  leaderElection: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
  clusterChecks:
    enabled: true
  kubeStateMetricsEnabled: true
  acExclude: "image:datadog/agent.*"
  podLabelsAsTags:
    "*": "%%label%%"
  dogstatsd:
    nonLocalTraffic: true
    useHostPort: true
  env:
    - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
      value: "true"
  confd:
    disk.yaml: |-
      init_config:
      instances:
        - use_mount: false
          file_system_blacklist:
            - autofs
            - /proc/sys/fs/binfmt_misc
            - /host/proc/sys/fs/binfmt_misc
    kubelet.yaml: |-
      logs:
        - type: journald
          path: /var/log/journal/
          include_units:
            - kubelet.service
            - docker.service
    nginx_ingress_controller.yaml: |-
      ad_identifiers:
        - nginx-ingress-controller
      init_config:
      instances:
        - prometheus_url: http://%%host%%:10254/metrics
    kubernetes_state.yaml: ""
    redisdb.yaml: ""
    cri.yaml: ""

clusterAgent:
  enabled: true
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi

clusterChecksRunner:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi

```

**Anything else we need to know**:
All other features work as expected (logs, traces, events, statsd, checks)

**Comment by clamoriniere** [comment]
Hi @bubalush 

Thanks for opening this issue. I think your are missing only on parameter in your `values.yaml`:
```yaml
datadog:
  processAgent:
    enabled: true
    processCollection: true
``` 

doc here: https://github.com/helm/charts/blob/1635fc38a696cfcebb4f07ddd28dce4674550238/stable/datadog/values.yaml#L286

Else everything look fine, and I'm happy to know that you are using most of our features :) 

let me know if it solve your issue.

Regards
Cedric

**Comment by bubalush** [comment]
@clamoriniere Thanks, it works. But I want to have backward compatibility with the previous version: there was an option to disable processCollection, but still have all other Live Containers metrics.
![image](https://user-images.githubusercontent.com/29120218/76969027-e3daac00-693a-11ea-8343-c2fce09c485e.png)

**Comment by clamoriniere** [comment]
Sure so in that case you can configure the process agent with the following configuration:

```yaml
datadog:
  processAgent:
    enabled: true
    processCollection: false
```
