### ISSUE TITLE
kubernets Prometheus -  error while running "VolumeBinding" filter plugin": pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by dragan-vucanovic-devtech** [helm/charts#21501]
I'm running Kubernets on CentOS 8 VM and trying to install Prometheus using helm

custom-values.yaml:

```
 # Define persistent storage for Prometheus (PVC)
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          volumeName: prometheus-storage
          accessModes: ["ReadWriteOnce"]
          storageClassName: prometheus
          resources:
            requests:
              storage: 5Gi
```

storage.yaml:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:

  name: prometheus
  namespace: monitoring
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: True


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage
  namespace: monitoring
spec:
  storageClassName: prometheus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus/"
    type: DirectoryOrCreate
```

`helm install prometheus stable/prometheus-operator --namespace monitoring -f custom-values.yaml`

prometheus-prometheus-oper-prometheus-0 nod is in Pending state

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  76s (x8 over 9m49s)  default-scheduler  error while running "VolumeBinding" filter plugin for pod "prometheus-prometheus-prometheus-oper-prometheus-0": pod has unbound immediate PersistentVolumeClaims
```

```
 kubectl describe pvc -n monitoring
Name:          prometheus-prometheus-prometheus-oper-prometheus-db-prometheus-prometheus-prometheus-oper-prometheus-0
Namespace:     monitoring
StorageClass:  prometheus
Status:        Pending
Volume:        prometheus-storage
Labels:        app=prometheus
               prometheus=prometheus-prometheus-oper-prometheus
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      0
Access Modes:
VolumeMode:    Filesystem
Mounted By:    prometheus-prometheus-prometheus-oper-prometheus-0
Events:        <none>




-----------------------------------


PV:

Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    prometheus
Status:          Pending
Claim:           default/data-sysdigcloud-mysql-cluster-0
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        5Gi
Node Affinity:   <none>
Message:
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/prometheus/
    HostPathType:  DirectoryOrCreate
Events:            <none>


```
