### ISSUE TITLE
[stable/prometheus-operator] wrong pod cpu metrics, if you've sidecard 

### ISSUE THREAD

**Issue by rjshrjndrn** [helm/charts#21536]
> update: This only happens, when I ran istio1.5 in the cluster.  
But the namespace doesn't have istio enabled

**Describe the bug**

created a deployment with sidecar(both container with 1G ad 1vCpu limit), and gave load to 1st container. But `Kubernetes / Compute Resources / Pod` dashboard shows wrong data 

**Version of Helm and Kubernetes**:

```
❮ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}

❮ k version 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
```
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION

prometheus-operator             monitoring      1               2020-03-19 20:58:44.166518629 +0530 IST deployed        prometheus-operator-8.12.3              0.37.0
```

**How to reproduce it** (as minimally and precisely as possible):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: tcpdump
        image: corfr/tcpdump
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        command:
          - /bin/sleep
          - infinity
      - name: name
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits: 
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 80
```
```
kubectl exec -it nginx-5c8f869fd4-ghlhc -c name bash
# apt update
# apt install stress-ng
# stress-ng --cpu 4 --io 2 --vm 1 --vm-bytes 1G --timeout 10m
```
## Actual metrics
![image](https://user-images.githubusercontent.com/2563385/77085602-93407d00-6a26-11ea-984d-bdc379d4e966.png)

## Mertics from grafana
![image](https://user-images.githubusercontent.com/2563385/77085645-a18e9900-6a26-11ea-936a-6c10e5ec7f41.png)
