### ISSUE TITLE
[stable/prometheus-operator] grafana dashboards that imported from values show error: Annotation Query Failed Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by zagr0** [helm/charts#21541]
**Describe the bug**
when import dashboards defined in values.yaml they imported and show error message related to annotation datasource (its set to CloudWatch):
![image](https://user-images.githubusercontent.com/19431669/77098936-d1846f00-6a1b-11ea-99f1-0e3567b3d4cd.png)

when the same dashboard imported manually with UI there is no such error shown, its imported with annotation datasourse "-- Grafana --"

values.yaml used:
```
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: CloudWatch
          type: cloudwatch
          access: proxy
          withCredentials: false
          jsonData:
            assumeRoleArn: "arn:aws:iam::XXXXXXXX:role/grafana-datasource-role"
            authType: "arn"
            defaultRegion: "eu-north-1"
          isDefault: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      aws-ec2:
        gnetId: 11265
        revision: 2
        datasource: CloudWatch
```

**Version of Helm and Kubernetes**:
helm v3.1.0
kubernetes v1.15.10

**Which chart**:
stable/prometheus-operator 8.11.0

**What you expected to happen**:
Expect to have dashboards imported from values.yaml with annotation datasourse "-- Grafana --", like its happens in manual UI import

**How to reproduce it** (as minimally and precisely as possible):
install helm chart with grafana values.yaml in description
