### ISSUE TITLE
[stable/datadog] chart v2 doesn't checksum of ClusterAgent configMap

### ISSUE THREAD

**Issue by bubalush** [helm/charts#21622]
**Describe the bug**
ClusterAgent pods aren't restarted if `confd` has been changed.

**What you expected to happen**:
Restart ClusterAgent pods to reload configuration when config has been changed.

**How to reproduce it** (as minimally and precisely as possible):
```
clusterAgent:
  confd:
    http_check.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - min_collection_interval: 86400
          name: Example com
          url: https://example.com/
          days_warning: 30
          days_critical: 7
          tags:
            - env:prod
```
