### ISSUE TITLE
[stable/datadog] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by anthony-pastor** [helm/charts#21651]
We observed datadog-agent pod crashing randomly with this error message:

```
panic: runtime error: invalid memory address or nil pointer dereference
--
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2ae25a8]goroutine 430056 [running]:
github.com/DataDog/datadog-agent/pkg/logs/decoder.NewDecoderWithEndLineMatcher(0x0, 0x3aac500, 0xc001d5b330, 0x3aac540, 0xc001d5b340, 0xc00420dc80)
/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/decoder/decoder.go:70 +0x68
github.com/DataDog/datadog-agent/pkg/logs/input/docker.InitializeDecoder(...)
/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/input/docker/matcher.go:17
github.com/DataDog/datadog-agent/pkg/logs/input/docker.NewTailer(0xc00065dee0, 0xc002433a49, 0x40, 0x0, 0xc000156d20, 0xc000640ba0, 0x0)
/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/input/docker/tailer.go:64 +0xbc
github.com/DataDog/datadog-agent/pkg/logs/input/docker.(*Launcher).restartTailer(0xc0006b4990, 0xc002433a49, 0x40)
/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/input/docker/launcher.go:255 +0x156
created by github.com/DataDog/datadog-agent/pkg/logs/input/docker.(*Launcher).run
/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/input/docker/launcher.go:153 +0x3ab
```

Our env is:

- Datadog Chart: 2.0.14

- Platform: Google Kubernetes Engine cluster, version: 1.15.8-gke.3

- Chart values: 

```
datadog:
  dogstatsd:
    useSocketVolume: true
  collectEvents: true
  leaderElection: true
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
  tags:
    - environment:preview
clusterAgent:
  enabled: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
agents:
  podAnnotations:
    sidecar.istio.io/inject: "false"
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "20%"
  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 512Mi
```
