### ISSUE TITLE
[stable/prometheus-operator] add root path reference when using multy ingresses

### ISSUE THREAD

**Issue by dioguerra** [helm/charts#21655]
when using prometheus-operator we can create ingress for the various components:
* prometheus
* grafana
* alertmanager

One way of accessing all of them without crashing we can use different subdomain.
But in my case i want to use one unique domain mydomain.something.com and redirect using the proxy by path

For that i can use the values.yaml path: /grafana specification...

However, i also need to set up the prefix added by the proxy redirect on the grafana. One way of doing this is editing the grafana.ini file to have the following:

`
 [server]
    domain = mydomain.something.com
    root_url = http://mydomain.something.com/grafana
`

Shouldnt be there a way that this is automatically set up in the args or init file when launching grafana?

I am using the traefik proxy, this is my grafana section configuration

``` yaml
grafana:
  #enabled: ${ENABLE_GRAFANA}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  adminPassword: ${ADMIN_PASSWD}
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: ${MONITORING_INGRESS_ENABLED}
    ## Annotations for Grafana Ingress
    ##
    annotations:
      kubernetes.io/ingress.class: ${INGRESS_CONTROLLER}
      traefik.ingress.kubernetes.io/frontend-entry-points: http
      traefik.ingress.kubernetes.io/protocol: http
      #TODO: CREATE SWITCH FOR NGINX
      # kubernetes.io/tls-acme: "true"
    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    hosts:
    - ${CLUSTER_ROOT_DOMAIN_NAME}
    ## Path for grafana ingress
    path: /grafana/?(.*)
    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls: []
    # - secretName: grafana-general-tls
    #   hosts:
    #   - grafana.example.com
```

**Comment by mateustanaka** [comment]
@MrD2 Did you solve that? I also would like to override root_url by prometheus/operator to be able to generate a invite link of grafana for new users instead of localhost:3000

**Comment by mateustanaka** [comment]
@MrD2 You can override the root_url on prometheus-operator, just set the property on values.yaml file like this:


```
grafana:
  enabled: true
  namespaceOverride: “”
  
  grafana.ini:
    server:
      root_url: https://youyhost.com/
```
