### ISSUE TITLE
[stable/datadog] Event Collection with DaemonSet doesn't work helm chart v2

### ISSUE THREAD

**Issue by guitarrapc** [helm/charts#21680]
**Describe the bug**

After update to helm chart v2 Event Collection with DaemonSet doesn't work anymore. Infrastructure - Containers (Datadog UI). I tried to use datadog agent image tag 7.17.1, 7.18.0, 7.18.1

**Version of Helm and Kubernetes**:

AWS EKS 1.14.8
Helm 2.16.2

**Which chart**:

stable/datadog v2.1.1

**What happened**:

kubernetes event not collected to Datadog.

**What you expected to happen**:

kubernetes event collected to Datadog.

**How to reproduce it** (as minimally and precisely as possible):
Use the following values.

```yaml
datadog:
  apiKeyExistingSecret: datadog-secret
  kubeStateMetricsEnabled: true
  clusterChecks:
    enabled: false
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
  collectEvents: true
  leaderElection: true
  logs:
    enabled: true
    containerCollectAll: true
  logsEnabled: true
  logsConfigContainerCollectAll: true
  apm:
    enabled: false
    port: 8126
  confd:
    disk.yaml: |-
      init_config:
      instances:
        - use_mount: false
          excluded_filesystems:
            - autofs
            - /proc/sys/fs/binfmt_misc
            - /host/proc/sys/fs/binfmt_misc
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enabled: false
    debugPort: 0
    enableConntrack: true
    seccomp: localhost/system-probe
    seccompRoot: /var/lib/kubelet/seccomp
    bpfDebug: false
    apparmor: unconfined

clusterAgent:
  enabled: false
  image:
    repository: datadog/cluster-agent
    tag: 1.5.2
    pullPolicy: IfNotPresent
  token: ""
  replicas: 1
  rbac:
    create: true
    serviceAccountName: default
  metricsProvider:
    enabled: false
    wpaController: false
    service:
      type: ClusterIP
      port: 443
  healthPort: 8080
  livenessProbe:
    httpGet:
      port: 5000
      path: /metrics
      scheme: HTTP
  readinessProbe:
    httpGet:
      port: 5000
      path: /metrics
      scheme: HTTP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
kubeStateMetrics:
  enabled: true

agents:
  enabled: true
  image:
    repository: datadog/agent
    tag: "7"
    pullPolicy: IfNotPresent
  rbac:
    create: true
    serviceAccountName: default
  containers:
    agent:
      resources: {}
      livenessProbe:
        httpGet:
          path: /health
          port: 5555
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
    processAgent:
      resources: {}
    traceAgent:
      resources: {}
      livenessProbe:
        tcpSocket:
          port: 8126
        initialDelaySeconds: 15
        periodSeconds: 15
        timeoutSeconds: 5
    systemProbe:
      resources: {}
    initContainers:
      resources: {}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "10%"

clusterChecksRunner:
  enabled: false
  image:
    repository: datadog/agent
    tag: "7"
    pullPolicy: IfNotPresent
  createPodDisruptionBudget: false
  rbac:
    create: true
    dedicated: false
clusterChecksRunner.replicas set to 2.
  replicas: 2
  resources: {}

affinity
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

kube-state-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
    name:
```

**Anything else we need to know**:

* All other features work as expected (logs, traces, statsd, checks)
* event will be sent if I enable clusterAgent.

```yaml
clusterAgent:
  enabled: false
```
