### ISSUE TITLE
[stable/prometheus] extraScrapeConfigs are not added

### ISSUE THREAD

**Issue by javib51** [helm/charts#21686]
**Describe the bug**
The extra configs provided to the chart are not propagated to server scrape configs

**Version of Helm and Kubernetes**: 
helm: 3.1.2
k8s: v1.15.10-eks-bac369

**Which chart**: prometheus

**What happened**:
I am trying to configure a scrape configuration for one of my services. So, I use `extraScrapeConfigs` but when I create it, these extra scrape configs are not propagated to the server config.

this is the values.yml:
```
serviceAccounts:
  server:
    create: false
    name: user-x-sa
alertmanager:
  enabled: false
pushgateway:
  enabled: false
networkPolicy:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
server:
  retention: '1d'
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: NodePort
extraScrapeConfigs: |
  - job_name: <my-service>
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - <my-service>.<namespace>.svc.cluster.local:8080
```
**What you expected to happen**:
I expected the scrape config to be propagated to the server.

**How to reproduce it** (as minimally and precisely as possible):
install the chart on a k8s cluster with the values.yml. Whenever its created, check `http://<your-prometheus-server>/config` to see if it was added to the config.

**Anything else we need to know**:
