### ISSUE TITLE
[stable/prometheus-operator]  manifest_sorter.go:192: info: skipping unknown hook: "crd-install" Alertmanager

### ISSUE THREAD

**Issue by rchenzheng** [helm/charts#21690]
**Describe the bug**
Deployment of prometheus-operator fails deployment due to unknown kind Alertmanager, Prometheus and PrometheusRule on monitoring.coreos.com/v1

**Version of Helm and Kubernetes**:

helm 3.1.2 and Kubernetes v1.15.9-gke.26

**Which chart**:

Stable release of prometheus-operator version 8.12.3

**What happened**:
Deployment of chart fails

```
  manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
  manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
  manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
  manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
  manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
  Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
```

**What you expected to happen**:

Successfully deploy 

**How to reproduce it** (as minimally and precisely as possible):
Deploy the operator using helm3 with the following config and chart version 8.12.3

```
alertmanager:
  alertmanagerSpec:
    replicas: 3
    podAntiAffinity: soft
    priorityClassName: monitoring

    routePrefix: /alertmanager

    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
        selector: {}

prometheusOperator:
  cleanupCustomResource: true
  configReloaderCpu: 300m
  tlsProxy:
    enabled: false
  admissionWebhooks:
    enabled: false
```

**Anything else we need to know**:

I've tried with and without helmfile v0.106.3 with helm-diff 3.1.1
