### ISSUE TITLE
stable/airflow  S3 connection is not working

### ISSUE THREAD

**Issue by Sureya** [helm/charts#21697]
**Describe the bug**

I use puckel/airflow 1.10.9 and use helm stable/airflow for deploying airflow into minikube cluster. I have **charts/airflow.yaml** file to set up my configuration and use the following command to deploy helm chart for airflow.

```bash 
$ cd charts
$ helm install airflow  -f airflow.yaml stable/airflow
```

Everything works fine and I am able to load my DAG into the airflow, except when I run the DAG it executes successfully but the logs are inaccessible. Raised this error in [StackOverflow question](https://stackoverflow.com/questions/60935008/airflow-doesnt-recognise-my-s3-connection-setting/) still no luck. 

So far I have tried all the approaches mentioned in the following links 

- https://stackoverflow.com/questions/59671864/uri-format-for-creating-an-airflow-s3-connection-via-environment-variables
- https://stackoverflow.com/questions/60199159/airflow-fails-to-write-logs-to-s3-v1-10-9
- https://stackoverflow.com/questions/55526759/airflow-1-10-2-not-writing-logs-to-s3
- https://stackoverflow.com/questions/50222860/airflow-wont-write-logs-to-s3

**Version of Helm and Kubernetes**:
```bash
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

kubernetes-version=v1.15.0
```

**Which chart**:
stable/airflow

**What happened**:
Expected to see my logs in S3

**What you expected to happen**:
Saw the following error
```
*** Log file does not exist: /usr/local/airflow/logs/example_python_operator/print_the_context/2020-03-30T16:02:41.521194+00:00/1.log
*** Fetching from: http://examplepythonoperatorprintthecontext-5b01d602e9d2482193d933e7d2:8793/log/example_python_operator/print_the_context/2020-03-30T16:02:41.521194+00:00/1.log
*** Failed to fetch log file from worker. HTTPConnectionPool(host='examplepythonoperatorprintthecontext-5b01d602e9d2482193d933e7d2', port=8793): Max retries exceeded with url: /log/example_python_operator/print_the_context/2020-03-30T16:02:41.521194+00:00/1.log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd00688a650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**How to reproduce it** (as minimally and precisely as possible):
Use the airflow.yaml provided below with stable/airflow helm chart to reproduce this

**Anything else we need to know**:
This is the value of my airflow.yaml with my latest try

```yaml
airflow:
  image:
     repository: airflow-docker-local
     tag: 1

  executor: Kubernetes

  service:
    type: LoadBalancer

  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__LOGGING_CONFIG_CLASS: logging_config.LOGGING_CONFIG
    AIRFLOW__CORE__LOGGING_LEVEL: INFO
    AIRFLOW__CORE__TASK_LOG_READER: s3.task
    AIRFLOW__CORE__FERNET_KEY: XYZ
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:airflow@airflow-postgresql:5432/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:airflow@airflow-postgresql:5432/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:airflow@airflow-redis-master:6379/0
    AIRFLOW__CORE__LOAD_EXAMPLES: False

    # S3 Logging
    AIRFLOW__CORE__REMOTE_LOGGING: True
    AIRFLOW__CORE__REMOTE_LOG_CONN_ID: aws_s3
    AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: s3://BUCKET-NAME/logs
    AIRFLOW__CORE__ENCRYPT_S3_LOGS: False
    AIRFLOW_CONN_AWS_S3: s3://XXX:XXX@S3

    # Worker Pod Configuration
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__LOGGING_CONFIG_CLASS: logging_config.LOGGING_CONFIG
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__LOGGING_LEVEL: INFO
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__TASK_LOG_READER: s3.task
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOGGING: True
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOG_CONN_ID: aws_s3
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: s3://BUCKET-NAME/logs
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__ENCRYPT_S3_LOGS: False
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW_CONN_AWS_S3: s3://XXX:XXX@S3


    # End of S3 Logging
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: True
    AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC: 30
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: airflow-docker-local
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 1
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: Never
    AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: airflow
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow
    AIRFLOW__KUBERNETES__NAMESPACE: airflow
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: True
    AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: '{\"_request_timeout\":[60, 60]}'

persistence:
  enabled: true
  existingClaim: ''
  accessMode: ReadWriteOnce
  size: 5Gi

logsPersistence:
  enabled: false

workers:
  enabled: true

postgresql:
  enabled: true

redis:
  enabled: true
```

**Comment by alisabraverman-anaplan** [comment]
@Sureya how did you solve this?

**Comment by Sureya** [comment]
> @Sureya how did you solve this?

@alisabraverman-anaplan : I was able to solve it with this SO answer [here](https://stackoverflow.com/questions/60935008/airflow-doesnt-recognise-my-s3-connection-setting)

I have a working version of the code in my repo storing logs in PV, if you are interested you can find it [here](https://github.com/Sureya/airflow_k8s_executor)

**Comment by ndlygaSyr** [comment]
Has anyone else got this actually working. I cannot get it to work here is my yaml file (Lots of stuff removed for only logging config left)
```
airflow:
  image:
    repository: apache/airflow
    tag: 1.10.10-python3.6
    pullPolicy: IfNotPresent
  executor: KubernetesExecutor
  config:
    AIRFLOW__CORE__LOGGING_LEVEL: "DEBUG"
    AIRFLOW__CORE__SECURE_MODE: "True"
    AIRFLOW__CORE__REMOTE_LOGGING: "True"
    AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://airflow/logs"
    AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "minio_backup_2"
    AIRFLOW__CORE__ENCRYPT_S3_LOGS: "False"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.10-python3.6"
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOGGING: "True"
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://airflow/logs"
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "minio_backup_2"
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__ENCRYPT_S3_LOGS: "False"
  extraPipPackages:
    - "airflow-exporter==1.3.0"
    - "apache-airflow[kubernetes]"
    - "apache-airflow[s3]"
workers:
  enabled: false
flower:
  enabled: false
scheduler:
  connections:
    - id: minio_backup_2
      type: aws
      extra: |
          {
            "aws_access_key_id": "XXX",
            "aws_secret_access_key": "XXX",
            "host": "https://mino-server",
            "region_name":"us-east-1"
          }
logs:
  path: /opt/airflow/logs
  persistence:
    enabled: false
```

We have a mino setup that uses the same api as S3. And this will no work, in the logs there is:

```
{logging_config.py:59} DEBUG - Unable to load custom logging, using default config instead
```

Any help would be greatly appreciated! Thanks!
