### ISSUE TITLE
[stable/mongodb-replicaset] warning: skipped value for global: Not a table.

### ISSUE THREAD

**Issue by connorearl** [helm/charts#21732]
**Describe the bug**
When packaging a chart using mongodb-replicaset as a subchart, the following warning is thrown:
`coalesce.go:165: warning: skipped value for global: Not a table.`

This occurs only on 3.14.1, not on 3.14.0

**Version of Helm and Kubernetes**:
Helm: 3.0.1
Kubernetes 1.16

**Which chart**:
mongodb-replicaset

**How to reproduce it** (as minimally and precisely as possible):
`helm package` will throw the warning. Below are the values I modified
```yaml
mongodb-replicaset:
  image:
    tag: 
  persistentVolume:
    storageClass: 
    size: 
  podAnnotations:
    backup.velero.io/backup-volumes: datadir
  extraLabels:
    label1:
    label2:
  auth:
    enabled: 
    existingAdminSecret: 
    existingKeySecret: 
  resources:
    limits:
      cpu: 
      memory: 
    requests:
      cpu: 
      memory: 
```
