### ISSUE TITLE
[stable/spinnaker] Gate service won't run due to deprecated object security.basic.enabled

### ISSUE THREAD

**Issue by rstuberg-ib** [helm/charts#21734]
**Describe the bug**
Chart version: spinnaker-1.23.3
hal version: 1.33
spinnaker version: 1.19.3

Gate gets stuck in the unready state. (Don't mind the restart that's me debugging)
spin-gate-58f987c5d4-rgms8                 0/1     Running     1          45m
spin-gate-58f987c5d4-ttr4f                 0/1     Running     0          45m

$ kubectl exec -ti spin-gate-58f987c5d4-rgms8 bash -n spinnaker
bash-5.0$ netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      1/java

DEBUG: starting gate from shows ->

2020-04-02 19:47:25.475 ERROR 78 --- [           main] o.s.b.c.p.m.PropertiesMigrationListener  :
The use of configuration keys that are no longer supported was found in the environment:

Property source 'applicationConfig: [file:/opt/spinnaker/config/gate.yml]':
	Key: security.basic.enabled
		Line: 17
		Reason: The security auto-configuration is no longer customizable.

Please refer to the migration guide or reference guide for potential alternatives.

**Version of Helm and Kubernetes**:
Helm Version 2.14
k8s v1.16.3
**Which chart**:
stable/spinnaker

**What happened**:
Gate doesn't run.

**What you expected to happen**:
Gate to run.

**How to reproduce it** (as minimally and precisely as possible):

Running on aurora sql and external redis. 
Here are the relevant configs for gate.

```
additionalServiceSettings:
    gate.yml:
      scheme: http
...
additionalConfigMaps:
    create: true
    data:
      config.src: |-
        GATE_URL="https://dns.com" # URL to access your gate
        DECK_URL="https://dns.com" # Url to access your deck
...
additionalProfileConfigMaps:
    create: true
    data:
      spinnaker-local.yaml: |-
        logging:
          level:
            root: DEBUG
            com:
              netflix:
                spinnaker: DEBUG
              retrofit: TRACE
      gate-local.yml: |-
        server:
          port: 9001
        default:
          apiPort: 8085
          legacyServerPort: 8084
```
**Anything else we need to know**:
This might be a physical spinnaker issue. Seeing that it looks like the problem is stemming from spring 2.0.
https://stackoverflow.com/questions/49717573/property-security-basic-enabled-is-deprecated-the-security-auto-configuration
