### ISSUE TITLE
[stable/spinnaker] Gate service won't run due to deprecated object security.basic.enabled

### ISSUE THREAD

**Issue by rstuberg-ib** [helm/charts#21735]
**Describe the bug**
Chart version: spinnaker-1.23.3
hal version: 1.33
spinnaker version: 1.19.3

Gate gets stuck in the unready state. (Don't mind the restart that's me debugging)
spin-gate-58f987c5d4-rgms8                 0/1     Running     1          45m
spin-gate-58f987c5d4-ttr4f                 0/1     Running     0          45m

$ kubectl exec -ti spin-gate-58f987c5d4-rgms8 bash -n spinnaker
bash-5.0$ netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      1/java

DEBUG: starting gate from shows ->

2020-04-02 19:47:25.475 ERROR 78 --- [           main] o.s.b.c.p.m.PropertiesMigrationListener  :
The use of configuration keys that are no longer supported was found in the environment:

Property source 'applicationConfig: [file:/opt/spinnaker/config/gate.yml]':
	Key: security.basic.enabled
		Line: 17
		Reason: The security auto-configuration is no longer customizable.

Please refer to the migration guide or reference guide for potential alternatives.

**Version of Helm and Kubernetes**:
Helm Version 2.14
k8s v1.16.3
**Which chart**:
stable/spinnaker

**What happened**:
Gate doesn't run.

**What you expected to happen**:
Gate to run.

**How to reproduce it** (as minimally and precisely as possible):

Running on aurora sql and external redis. 
Here are the relevant configs for gate.

```
additionalServiceSettings:
    gate.yml:
      scheme: http
...
additionalConfigMaps:
    create: true
    data:
      config.src: |-
        GATE_URL="https://dns.com" # URL to access your gate
        DECK_URL="https://dns.com" # Url to access your deck
...
additionalProfileConfigMaps:
    create: true
    data:
      spinnaker-local.yaml: |-
        logging:
          level:
            root: DEBUG
            com:
              netflix:
                spinnaker: DEBUG
              retrofit: TRACE
      gate-local.yml: |-
        server:
          port: 9001
        default:
          apiPort: 8085
          legacyServerPort: 8084
```
**Anything else we need to know**:
This might be a physical spinnaker issue. Seeing that it looks like the problem is stemming from spring 2.0.
https://stackoverflow.com/questions/49717573/property-security-basic-enabled-is-deprecated-the-security-auto-configuration

**Comment by rstuberg-ib** [comment]
I have also tried adding the following to additionalServiceSettings

```
gate.yml:
      healthEndpoint: /health
      scheme: http
      port: 8084
```

Forgot to also mention these likely relate to this:
https://github.com/spinnaker/spinnaker/issues/4576
https://github.com/spinnaker/spinnaker/issues/2533

**Comment by rstuberg-ib** [comment]
Looks like this is because I only enabled x509 authn?

I cannot change the file on the container since it is mounted RO.
```
security:
  basic:
    enabled: true
  user: {}
cors: {}
x509:
  enabled: true
```

**Comment by rstuberg-ib** [comment]
I think the security.basic.enabled is benign. I found some github issue were it is there for the monitoring daemon.

Found the issue. Ripped out the Legacy stuff without SSL to get it to work. Now, to get ssl to work...

Changed the config to:
`gate-local.yml: |-
        server:
          port: 8084
`

With:
`
additionalServiceSettings:
    gate.yml:
      healthEndpoint: /health
      scheme: http
`

**Comment by rafalparadowski** [comment]
Hi!
Could you please elaborate on how you solved this issue? 
I added
```
healthEndpoint: /health
scheme: http
port: 8084
```
to `/etc/spinnaker/.hal/default/service-settings/gate.yml` (which I believe is an equivalent of  section `additionalServiceSettings` in `values.yml`). Didn't work, so I guess I need to "Rip out the Legacy stuff without SSL", but I dunno what does it mean.
Cheers!

**Comment by rstuberg-ib** [comment]
When we were using x509 in an older version ~1.12 or ~1.15 we had used the following values:

```
additionalProfileConfigMaps
gate-local.yml: |-
        server:
          port: 9001
        default:
          apiPort: 8085
          legacyServerPort: 8084```

the new setting would be -> 

```
gate-local.yml: |-
        server:
         port: 8084
```

For the gate.yml side what you have is correct.

The legacyServerPort and apiPort are the two ports to use TLS and non TLS connections for gate if you need to force x509 auth for api calls and such.

https://github.com/spinnaker/spinnaker/issues/2533 is one of the references for this.
