### ISSUE TITLE
[stable/external-dns] Unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by evgmoskalenko** [helm/charts#21745]
**Describe the bug**

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Version of Helm and Kubernetes**:

* **Helm:** v3.1.2, GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"
* **AWS Kubernetes version:** 1.15

**Which chart**:

* stable/external-dns and stable/prometheus-operator charts

**What happened**:

I have a pipeline in which "helm chart extenral-dns" install first, then "helm chart prometheus-operator", but in the settings of "extenral-dns" chart there is a CustomResourceDefinition (ServiceMonitor), which is set only after installing the "prometheus-operator" chart

```
metrics:
  enabled: true
  ## Metrics exporter pod Annotation and Labels
  ##
  # podAnnotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "7979"

  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    enabled: true
```

For some reason, on AWS Kubernetes version 1.14, such an error cannot be reproduced, the pipeline goes through and the chart - "extenral-dns" is installed, even if "prometheus-operator" is not installed yet.

On AWS Kubernetes version 1.15, I get this error - Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

In fact, it’s not very convenient to first install the "prometheus-operator" and then "extendral-dns", because I need DNS names for the Prometheus service as well

It’s also not very convenient to install a resource in the pipeline - "kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.37/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml" before installing "external-dns", because servicemonitors resource is versioned, and it’s necessary to remember that after updating the "prometheus-operator" charts, I need to check the changes in "monitoring.coreos.com_servicemonitors.yaml"

**What you expected to happen**:

I expected that an "external-dns" chart with enabled serviceMonitor will be installed

```
metrics:
  enabled: true
  ## Metrics exporter pod Annotation and Labels
  ##
  # podAnnotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "7979"

  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    enabled: true
```

And then the pipeline will install the "prometheus-operator" chart and other charts with resources serviceMonitor.
