### ISSUE TITLE
[stable/prometheus-postgres-exporter] support DATA_SOURCE_NAME

### ISSUE THREAD

**Issue by wasfree** [helm/charts#21798]
**Problem Describe**
[postgres_exporter](https://github.com/wrouesnel/postgres_exporter) allows to configure postgres uri in two different formats `DATA_SOURCE_NAME` (postgresql://login:password@hostname:port/dbname) or `DATA_SOURCE_URI` which exclusively accepts the raw URI without a username and password component so also requires `DATA_SOURCE_USER` and `DATA_SOURCE_PASS` to be set. So in my opinion `DATA_SOURCE_NAME` has a much more common format. In my use-case it would require to script around `DATA_SOURCE_URI` to split user/pass/hostname and configure `stable/prometheus-postgres-exporter` helm chart. 

Another benefit is that `DATA_SOURCE_NAME` also allows to configure **multiple** PostgreSQL databases with same postgres_exporter instance, which is not possible with `DATA_SOURCE_URI` . Unfortunately this is not very well documented but here is a link to [PR/Merge](https://github.com/wrouesnel/postgres_exporter/pull/215).

**Describe the solution you'd like**
So my solution would look like this:
```
config:
  datasourceSecret: {}
    # Specifies if datasource should be sourced from secret value in format: postgresql://login:password@hostname:port/dbname?sslmode=disable
    # Multiple Postgres databases can be configured by comma separated postgres connection strings
    # Secret name
    #  name:
    # Connection string key inside secret
    #  key:
  datasource:
    # Specify one of both datasourceSecret or datasource
    host:
    user: postgres
    # Only one of password and passwordSecret can be specified
    password: somepassword
    # Specify passwordSecret if DB password is stored in secret.
    passwordSecret: {}
    # Secret name
    #  name:
    # Password key inside secret
    #  key:
```
