### ISSUE TITLE
[stable/prometheus-operator] pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by shibumi** [helm/charts#21820]
**Describe the bug**
I try to deploy the `stable/prometheus-operator` chart to a minikube  cluster for testing.
Everything starts as expected, except the prometheus container with the specified PV.

**Version of Helm and Kubernetes**:
Helm:
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"dirty", GoVersion:"go1.14.1"}

minikube version: v1.9.0
commit: 48fefd43444d2f8852f527c78f0141b377b1e42a

kubectl:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"2020-02-29T16:37:45Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/prometheus

**What happened**:

The prometheus container is hanging in a CrashLoopBackOff state:
```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  <unknown>          default-scheduler  running "VolumeBinding" filter plugin for pod "prometheus-joking-joker-prometheus-op-prometheus-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         <unknown>          default-scheduler  Successfully assigned monitoring/prometheus-joking-joker-prometheus-op-prometheus-0 to minikube
  Warning  FailedScheduling  <unknown>          default-scheduler  running "VolumeBinding" filter plugin for pod "prometheus-joking-joker-prometheus-op-prometheus-0": pod has unbound immediate PersistentVolumeClaims
```

I can't explain this.. when I look into minikube via `minikube ssh` I see an empty `prometheus-db` directory in `/mnt/sda1/data`.

**What you expected to happen**:

I expected the prometheus-operator to use this empty directory and start up correctly.

**How to reproduce it** (as minimally and precisely as possible):

First I created the necessary namespace `monitoring` on a fresh cluster:
`kubectl create namespace monitoring`

This is my persistent volume:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-prometheus-operator-1586196970-prometheus-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5G
  hostPath:
    path: "/data/"
```

Applied via `kubectl apply -f pv.yml`

This is my values.yml:
```
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          volumeName: pvc-prometheus-operator-1586196970-prometheus-0
          accessModes: ["ReadWriteOnce"]
          storageClassName: manual
          resources:
            requests:
              storage: 5G
```

applied via `helm install joking-joker stable/prometheus-operator --namespace=monitoring -f values.yml`

`kubectl describe pv` output:
```
Name:            pvc-prometheus-operator-1586196970-prometheus-0
Labels:          <none>
Annotations:     kubectl.kubernetes.io/last-applied-configuration:
                   {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"pvc-prometheus-operator-1586196970-prometheus-0"},"spec"...
                 pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    manual
Status:          Bound
Claim:           monitoring/prometheus-joking-joker-prometheus-op-prometheus-db-prometheus-joking-joker-prometheus-op-prometheus-0
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        5G
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /data/
    HostPathType:  
Events:            <none>
```
`kubectl describe pvc -n monitoring` output:
```
Name:          prometheus-joking-joker-prometheus-op-prometheus-db-prometheus-joking-joker-prometheus-op-prometheus-0
Namespace:     monitoring
StorageClass:  manual
Status:        Bound
Volume:        pvc-prometheus-operator-1586196970-prometheus-0
Labels:        app=prometheus
               prometheus=joking-joker-prometheus-op-prometheus
Annotations:   pv.kubernetes.io/bind-completed: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5G
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    prometheus-joking-joker-prometheus-op-prometheus-0
Events:        <none>
```

**Anything else we need to know**:

I have tried to use the standard storageclass too and I tried creating a storage class.. everything with the same result.
