### ISSUE TITLE
[stable/prometheus] incompatible default scrape_configs with prefixURL

### ISSUE THREAD

**Issue by tchiotludo** [helm/charts#21841]
Right now, the scrape config is hardcoded : 
```yaml
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
```
I use a `prefixURL` in order to work behind a reverse proxy, the scape url must be changed to `localhost:9090{prefixURL}`
That lead to scrape error : server returned HTTP status 404 Not Found
And if you have a global alert on `up`, alert will be raise without any way to handle it (except silence the error to all dev null receiver.

I have the feeling that this PR can be a real solution : https://github.com/helm/charts/pull/3328
