### ISSUE TITLE
Traefik - Can't get correct certificate from Let's Encrypt / ACME

### ISSUE THREAD

**Issue by bezelga** [helm/charts#2185]
This is a Request for help.

**Version of Helm and Kubernetes**:

kubernetes: 1.7.5

helm: v2.6.1

**Which chart**:

Traefik

**What happened**:

Can't get the certificate correctly, it generates a *.example.com 

**What you expected to happen**:
Generates a correct certificate

**How to reproduce it** (as minimally and precisely as possible):

helm init
helm install --name traefik stable/traefik 

I created an app-ingress.yml inside templates folder:

```
{{- if .Values.ink.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ink
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.ink.ssl }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ink.domain }}
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 80
  {{- if .Values.ink.ssl }}
  tls:
  - secretName: traefik-traefik-default-cert
    hosts:
      - {{ .Values.ink.domain }}
  {{- end }}
{{- end }}
```

values.yml (relevant parts):

```
acme:
  enabled: true
  email: my@email.com
  staging: false
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

ink:
  enabled: true
  domain: my.domain.io
  ssl: true
```
