### ISSUE TITLE
[stable/chartmuseum] Can't Use IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by IronCore864** [helm/charts#21872]
**Describe the bug**
When using AWS S3 as storage and IAM Roles for Service Accounts permission grant, the pod can't access S3.

**Version of Helm and Kubernetes**:
helm: v3.1.0-rc.2
k8s: v1.15.10-eks-bac369

**Which chart**:
stable/chartmuseum

**What happened**:
IAM role for OIDC is used, as described here:
https://github.com/helm/charts/tree/master/stable/chartmuseum#permissions-grant-with-iam-roles-for-service-accounts
IAM roles are setup properly according to AWS official doc here:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
The pod can't access S3

**What you expected to happen**:
Pod start successfully

**How to reproduce it** (as minimally and precisely as possible):
`custom.yaml`:

```
env:
  open:
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: my-s3-bucket
    STORAGE_AMAZON_PREFIX:
    STORAGE_AMAZON_REGION: us-east-1
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{aws account ID}:role/{assumed role name}"
```

```
helm install --name my-chartmuseum -f custom.yaml stable/chartmuseum
```

Then get log from the pod:

```
{"L":"ERROR","T":"2020-04-10T17:30:55.217Z","M":"AccessDenied: Access Denied\n\tstatus code: 403, request id: 75E89525E157AC2E, host id: TDTl6aHMTAY8Zs+PgQSiYVkS0NtisS+89oZ+t6aQLlQaC4go0/0oGhbFreZ1EphnZ7ekm0Vr+FE=","repo":""}
2020-04-10 17:30:55.217240 I | AccessDenied: Access Denied
	status code: 403, request id: 75E89525E157AC2E, host id: TDTl6aHMTAY8Zs+PgQSiYVkS0NtisS+89oZ+t6aQLlQaC4go0/0oGhbFreZ1EphnZ7ekm0Vr+FE=
```

**Anything else we need to know**:

I'm pretty sure the service account with IAM role already works because I tried to use the same SA for another pod with awscli and tried to access S3 and it was successful.
