### ISSUE TITLE
[stable/airflow] PostgreSQL variables not modified in airflow.cfg

### ISSUE THREAD

**Issue by opendatakraken** [helm/charts#21909]
**Describe the bug**
In my custom values.yaml I have the following:
```yaml
airflow:
  executor: Local
  config:
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://my_user:my_pwd@my_host/my_db

postgresql:
  enabled: false
  postgresHost: my_host
  postgresqlUsername: my_user
  postgresqlPassword: my_pwd
  postgresqlDatabase: my_db
```

The pod doesn't start because of the error:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  PAM authentication failed for user "postgres"
```

cat airflow.cfg on the pod shows an unmodified airflow.cfg
**Version of Helm and Kubernetes**:
Helm: 2.16.5
Kubernetes: 1.7.0

**Which chart**:
stable/airflow

**What happened**:
The airflow pod try to connect to the postgresql db with the user postgres and not the given user

**What you expected to happen**:
Airflow-pod connect to the given PostgreSQL database using the given username/password
airflow.cfg looks unmodified

**How to reproduce it** (as minimally and precisely as possible):
use your own postgresql parameters in values.yaml and deploy the chart

**Anything else we need to know**:

**Comment by javsalgar** [comment]
Hi,

If I'm not mistaken, these environment variables would substitute what it's available in airflow.cfg. Note that it shows an authentication error, so it is connecting to your host, am I wrong?

From https://airflow.apache.org/docs/stable/howto/set-config.html:

```
The universal order of precedence for all configuration options is as follows:

set as an environment variable

set as a command environment variable

set in airflow.cfg

command in airflow.cfg

Airflow’s built in defaults
```

**Comment by opendatakraken** [comment]
Hi,

yes, it's an own PostgreSQL. If I bash into the pod. and run the following:
echo $AIRFLOW__CORE__SQL_ALCHEMY_CONN
I get the correct value set in values.yaml:
`postgresql+psycopg2://my_user:my_pwd@my_host/my_db`
So it looks like Airflow is not using this variable.

**Comment by opendatakraken** [comment]
I have also the following issue.
If I set
```yaml
postgresql:
  enabled: false
```
I get the logs:
```
Thu Apr 16 09:23:57 UTC 2020 - waiting for Postgres... 1/20
Thu Apr 16 09:24:02 UTC 2020 - waiting for Postgres... 2/20
Thu Apr 16 09:24:07 UTC 2020 - waiting for Postgres... 3/20
```
Why should the AirFlow Pod wait for PostgreSQL if it is disabled ????

On the other hand, if I set:
```yaml
postgresql:
  enabled: false
  postgresHost: my_host
  postgresqlUsername: my_user
  postgresqlPassword: my_password
  postgresqlDatabase: my_db
```
I get the error message:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  PAM authentication failed for user "postgres"
```
Does it mean that it tries to create the PostgreSQL database and user using the postgres admin user?
Again, with `enabled: false` it shouldn't try to create any postgresql!
