### ISSUE TITLE
[stable/datadog] incorrect indentation in cluster-agent-deployment.yaml

### ISSUE THREAD

**Issue by PeteE** [helm/charts#21921]
**Describe the bug**
In https://github.com/helm/charts/blob/master/stable/datadog/templates/cluster-agent-deployment.yaml#L185 the indentation is set to 10 but should be 8.

**Version of Helm and Kubernetes**:
```
❯ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/datadog

**What happened**:
```
Error: YAML parse error on datadog/templates/cluster-agent-deployment.yaml: error converting YAML to JSON: yaml: line 132: did not find expected key
```

**What you expected to happen**:
Template renders correctly. 

**How to reproduce it** (as minimally and precisely as possible):
1) Create values.yaml:
```
clusterAgent:
  enabled: true
  confd:
    mysql.yaml: |-
      cluster_check: "true"
      instances:
        - server: foo
          port: 3306
          user: datadog
          pass: 'foo'
  volumes:
    - name: secrets
      secret:
        secretName: somesecret
  volumeMounts:
    - name: secrets
      mountPath: /etc/secret-volume
      readOnly: true
```
2) Attempt to install:
```
❯ helm install --dry-run --debug mydatadog  stable/datadog -f values.yaml
Error: YAML parse error on datadog/templates/cluster-agent-deployment.yaml: error converting YAML to JSON: yaml: line 97: did not find expected key
helm.go:75: [debug] error converting YAML to JSON: yaml: line 97: did not find expected key
YAML parse error on datadog/templates/cluster-agent-deployment.yaml
```

**Anything else we need to know**:
