### ISSUE TITLE
[stable/grafana] use grafana-image-render

### ISSUE THREAD

**Issue by jinleileiking** [helm/charts#21959]
By default, does not use `grafana-image-renderer`

We need a solution for this. https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md 

is a way for this.

But this docker needs a helm chart, and there is another question:

How can this pod (grafana-image-render pod) communicate with grafana pod?

**Comment by rust84** [comment]
I created my own helm chart for this. It would be great if the operator could be updated to allow us to deploy the image through the chart. For example:

    renderImage:
      enabled: true
      repository: grafana/grafana-image-renderer
      tag: 1.0.7

Setting environment variables works for now:

    grafana:
      env:
        GF_EXPLORE_ENABLED: true
        GF_RENDERING_SERVER_URL: http://grafana-image-renderer:8081/render
        GF_RENDERING_CALLBACK_URL: http://prometheus-operator-grafana/
        GF_LOG_FILTERS: rendering:debug

**Comment by jinleileiking** [comment]
@rust84 Can you give the link?

**Comment by bentatham** [comment]
Now that Grafana 7.0 removed build in image rendering, this seems even more important to move forward, so we can do it within our existing helm-based deployments.

**Comment by languitar** [comment]
In case someone else is stumbling across this and needs a quickfix with the current chart:

```
    extraContainers: |
      - name: renderer
        image: grafana/grafana-image-renderer:latest

    env:
      GF_RENDERING_SERVER_URL: http://localhost:8081/render
      GF_RENDERING_CALLBACK_URL: http://localhost:3000/

```
