### ISSUE TITLE
[stable/airflow] can't use kubernetes executor

### ISSUE THREAD

**Issue by random1st** [helm/charts#21978]
**Describe the bug**
Can't use Kubernetes executor  - inexisting config section is required 

**Version of Helm and Kubernetes**:
helm 3.1.2
k8s 1.14 (EKS)

**Which chart**:
stable/airflow

**What happened**:
Install chart with custom values. Config works properly with CeleryExecutor, but after change to KubernetesExecutor there was an error from scheduler:
```airflow.exceptions.AirflowConfigException: In kubernetes mode the following must be set in the kubernetes config section: dags_volume_claim or dags_volume_host or dags_in_image or git_repo and git_branch and git_dags_folder_mount_point```

**What you expected to happen**:
Airflow starts to create tasks as kubernetes pods

**How to reproduce it** (as minimally and precisely as possible):
  - install helm chart with executor as KubernetesExecutor

**Anything else we need to know**:
 - docker image of airflow does not contain kubernetes python package. It should be installed via requirements or manually in pod

**Comment by PierreC1024** [comment]
If you want to use k8s executor with this chart, you have to: 

* use a docker image with airflow kubernetes extra features ([example](https://hub.docker.com/r/pcc1488/docker-airflow-kubernetes-executor)) 

* fill some mandatory kubernetes configurations in [airflow.cfg](https://github.com/apache/airflow/blob/master/airflow/config_templates/default_airflow.cfg#L797), this is a basic example to deploy the chart:
```yaml
airflow:
  image:
    repository: pcc1488/docker-airflow-kubernetes-executor
    tag: latest
  executor: Kubernetes
  config:
    AIRFLOW__CORE__FERNET_KEY: 'R3r6tZ9h4M12cIshn1FSwskYd1-9_Y_S4E6hvNruAAI='
    # Kubernetes Configuration
    AIRFLOW__KUBERNETES__NAMESPACE: default # Or Set when you deploy with helm
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: pcc1488/docker-airflow-kubernetes-executor
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: latest
    AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__FERNET_KEY: 'R3r6tZ9h4M12cIshn1FSwskYd1-9_Y_S4E6hvNruAAI='
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: 'True'

# No need for kubernetes executor
workers:
  enabled: false
redis:
  enabled: false
flower:
  enabled: false
```

In kubernetes executor mode, you have to define how the dags are recovered. You could choose to put dags in the docker image (like in the example),  create a git sync or used a volume claim.
