### ISSUE TITLE
[incubator/gogs] allow to configure liveness settings

### ISSUE THREAD

**Issue by tarioch** [helm/charts#22049]
**Is your feature request related to a problem? Please describe.**
Gogs restarts quite often in my cluster as the liveness check of the chart are quite aggressive.

**Describe the solution you'd like**
It would be great if it were possible to tune/adjust the liveness settings

**Comment by hzliangbin** [comment]
@tarioch it's not that offen to adjust liveness or readiness settings.  try to config periodSeconds to reduce frequency of  liveness probe.

```
          livenessProbe:
            initialDelaySeconds: 180
            periodSeconds: 60
            httpGet:
              {{- if .Values.service.gogs.serviceRequireSignInView }}
              path: /user/login
              {{- else }}
              path: /
              {{- end }}
              port: 3000
```
Hope it helps
