### ISSUE TITLE
Jenkins: How to pass SSH keys for pulling private repositories as secretVolume ?

### ISSUE THREAD

**Issue by chhetripradeep** [helm/charts#2209]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.6.1
Kubernetes: 1.7.2

**Which chart**:
Jenkins

**What happened**:
I am trying to mount ssh keys to access private repositories inside agent containers using SecretVolume.

When specifying like this
```
Agent:
  volumes:
    - type: Secret
      secretName: ssh-key
      mountPath: /home/jenkins/.ssh
```
All the files like `id_rsa` and `id_rsa.pub` gets mounted as 0777 as symbolic links. 

Cloning private repositories fail because it expects the permission of `id_rsa` to be `0400`.

**What you expected to happen**:
I would like to specify the permissions of mountpoint.

**How to reproduce it** (as minimally and precisely as possible):
Simply use jenkins chart with `Agent.volumes` specified

**Anything else we need to know**:
