### ISSUE TITLE
[stable/minio] MinIO is failing to start using default values

### ISSUE THREAD

**Issue by xaviersierra** [helm/charts#22107]
**Describe the bug**

I'm trying to install MinIO on kubernetes, by just running the command:
``` bash
helm install minio stable/minio
```
But, the MinIO pod is failing with the message:
``` bash
 You are running an older version of MinIO released 4 weeks ago 
 Update: https://docs.min.io/docs/deploy-minio-on-kubernetes 
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Use 'sudo chown <your-username> /export && sudo chmod u+rxw /export' to provide sufficient permissions.
```
This is the output of the persistent volume claims: 
``` bash
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM           STORAGECLASS   REASON   AGE
pvc-7c1e22a3-1ac8-4bc9-8878-3da118e69806   10Gi       RWO            Delete           Bound    default/minio   standard                17m
```
And the output of the persistent volumes: 
``` bash
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM           STORAGECLASS   REASON   AGE
pvc-7c1e22a3-1ac8-4bc9-8878-3da118e69806   10Gi       RWO            Delete           Bound    default/minio   standard                17m
``` 
**Version of Helm and Kubernetes**: 
helm: 3.1.1
k8s: 1.16.3

**Which chart**: 5.0.23

**What happened**:
The helm installation reports a successful installation, nonetheless MinIO doesn't start

**What you expected to happen**:
After a short period of time, MinIO should start with no errors. 

**How to reproduce it** (as minimally and precisely as possible):
 Create a new k8s cluster. 
run the command: 
``` bash
helm install minio stable/minio
```

**Comment by mattboardman** [comment]
Having a similar issue. 

PV:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub-1
```

I was using this for testing purposes so I was able to get around for now by disabling persistence but I'm not sure if this error will occur in production on a cloud provider. Do you mind if I ask how/where you are deploying your cluster?
