### ISSUE TITLE
[stable/sentry] Ingress extraPaths

### ISSUE THREAD

**Issue by evgmoskalenko** [helm/charts#22105]
**Which chart**:

* stable/sentry

**Is your feature request related to a problem? Please describe.**

Hello, I would like to be able to add an extra path for ingress to the chart.

Extra paths to prepend to every host configuration. This is useful when working with annotation-based services.

This helps manage to route the paths using ingress controllers. For example - alb-ingress-controller and chart ingress settings:

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/ip-address-type: "ipv4"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # Redirect rules - actions.ssl-redirect
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```

and ingress path settings:

```
ingress:
  enabled: true
  ...
  labels: {}
  hosts:
    - name: sentry.local
  extraPaths:
    - path: /*
      backend:
        serviceName: ssl-redirect
        servicePort: use-annotation
    - path: /*
      backend:
        serviceName: sentry
        servicePort: 80
```

In this case, all requests from port 80 will be redirected to 443 port.
