### ISSUE TITLE
[prometheus-operator] KubeAPIDown

### ISSUE THREAD

**Issue by JavierSegui** [helm/charts#22127]
**Describe the bug**
I can't manage to configure the KubeAPI scraper to work.

**Version of Helm and Kubernetes**:
```
Helm: version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
Kubernetes: 1.16.7
```

**Which chart**:
prometheus-operator

**What happened**:
I can't properly configure kubeApiServer with kops defaults. I've had similar issues with the scheduler and kubelet but it got solved by replacing `component` to `k8s-app` in the selector.

**What you expected to happen**:
Prometheus find kubeapiserver

**How to reproduce it** (as minimally and precisely as possible):
Using a kops installation, install prometheus-operator helm chart. Go to the prometheus operator dashboard and under /alerts, see how the following alert fires:

```
alert: KubeAPIDown
expr: absent(up{job="apiserver"}
  == 1)
for: 15m
labels:
  severity: critical
annotations:
  message: KubeAPI has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapidown
```

**Anything else we need to know**:

`kubectl describe pod kube-apiserver-ip-XXX` returns

```
Name:                 kube-apiserver-ip-XXXXXX.eu-west-1.compute.internal
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 ip-XXXXXX.eu-west-1.compute.internal/XXXXXX
Start Time:           Sat, 25 Apr 2020 12:12:27 +0100
Labels:               k8s-app=kube-apiserver
Annotations:          dns.alpha.kubernetes.io/external: XXXXX
                      dns.alpha.kubernetes.io/internal: XXXXX
                      kubernetes.io/config.hash: XXXXX
                      kubernetes.io/config.mirror: XXXXX
                      kubernetes.io/config.seen: 2020-04-25T11:12:27.260741031Z
                      kubernetes.io/config.source: file
                      scheduler.alpha.kubernetes.io/critical-pod:
Status:               Running
IP:                   XXXXX
Containers:
  kube-apiserver:
    Container ID:  docker://768a318a867f26addff59363b336361e07e6e4dcb9820e7c77d8308197fffb45
    Image:         k8s.gcr.io/kube-apiserver:v1.16.7
    Image ID:      docker-pullable://k8s.gcr.io/kube-apiserver@sha256:de25187dc8092f3c2f5ec214cbb8f099591c09ac0d69f8f1d3415c180d3b37a0
    Ports:         443/TCP, 8080/TCP
    Host Ports:    443/TCP, 8080/TCP
...
```

and the config values i'm using for kubeApiServer is

```
kubeApiServer:
  enabled: true
  tlsConfig:
    serverName: kubernetes
    insecureSkipVerify: false
  relabelings: []
  serviceMonitor:
    interval: ""
    jobLabel: component
    selector:
      matchLabels:
        k8s-app: kube-apiserver
#        component: apiserver
#        provider: kubernetes
    metricRelabelings: []
```
