### ISSUE TITLE
[stable/gocd] Incorrect permission of ~/.ssh/id_rsa

### ISSUE THREAD

**Issue by vikas027** [helm/charts#22120]
**Describe the bug**
Permissions of `~/.ssh/id_rsa` are not correct
```bash
bash-5.0$ ls -l ~/.ssh/
total 8
-rw-rw----    1 go       root          1679 Apr 24 18:39 id_rsa
-rw-rw----    1 go       root          1181 Apr 24 19:55 known_hosts
bash-5.0$
```

**Version of Helm and Kubernetes**:
Helm: 3.2.0
Kubernetes: 1.17.4

**Which chart**:
stable/gocd

**What happened**:
![2020-04-25_06-32-58](https://user-images.githubusercontent.com/6998650/80254499-a2b68400-86be-11ea-9205-358c608dcc72.png)

**What you expected to happen**:
I should be able to Test connection successfully

**How to reproduce it** (as minimally and precisely as possible):
- Create a secret
```
kubectl create secret generic gocd-server-ssh \
--from-file=id_rsa=ssh/id_rsa \
--from-file=known_hosts=ssh/known_hosts \
--namespace=gocd
```
- set the corresponding values
```
security:
  ssh:
    enabled: true
    secretName: gocd-server-ssh
```
More details are [here](https://www.gocd.org/2019/05/14/installing-configuring-gocd-gke-using-helm/).

**Anything else we need to know**:
The current workaround is to fix the permissions in the deployment
```
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - chmod 0600 /home/go/.ssh/id_rsa
              - "&&"
              - /preconfigure_server.sh
```
