### ISSUE TITLE
[stable/nginx-ingress] Wrong defaults for TLS version and ciphers

### ISSUE THREAD

**Issue by cemsbr** [helm/charts#22166]
**Describe the bug**
Only TLSv1.2 with 2 ciphers are enabled. However, there are many more default values for nginx ingress according to [its docs](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#configuration-options).

**Version of Helm and Kubernetes**:
- Helm 3.2.0
- Kubernetes v1.14.10 server, 1.18.2 client

**Which chart**:
stable/nginx-ingress-1.36.3

**What happened**:
Output of `sslscan domain.com`:
```
(...)
  Supported Server Cipher(s):
Preferred TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
(...)
```

**What you expected to happen**:
- TLS enabled: TLSv1.2, TLSv1.3
- Ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

**How to reproduce it** (as minimally and precisely as possible):
Install the chart and run a tool like sslscan to list TLS versions and ciphers available.

Note: I used a file with values for helm to add `use-proxy-protocol: "true"` in nginx's configmap.

**Anything else we need to know**:

**Comment by cemsbr** [comment]
I added the default values to the configmap and removed linkerd injection, but the result is the same:
```yaml
apiVersion: v1
kind: ConfigMap
data:
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  use-proxy-protocol: "true"
(...)
```

**Comment by cemsbr** [comment]
Solved. No need to specify `ssl-ciphers` and `ssl-protocols`, but only `ssl-dh-param`.

**Comment by ericsuhong** [comment]
@cemsbr Can you please tell us the exact configMap you used to solve this issue?

**Comment by cemsbr** [comment]
Sure. The relevant part of the chart values I use is:
```yaml
controller:
  config:
    ssl-dh-param: "default/nginx-ssl-dh-param"
```
And `default/nginx-ssl-dh-param` is the following secret:
```yaml
apiVersion: v1
kind: Secret
data:
  dhparam.pem: "output, without newlines, of: openssl dhparam 4096 2> /dev/null | base64"
metadata:
  name: nginx-ssl-dh-param
```

The configmap is then generated by the chart.
