### ISSUE TITLE
[stable/mongodb-replicaset] Conflict inbound listener error when istio is enabled

### ISSUE THREAD

**Issue by oba11** [helm/charts#22209]
**Describe the bug**
If the mongodb-replicaset chart is deployed within istio service mesh, pilot throws an error of `conflicting inbound listeners`. This is because two services with the same selector definition are used in the [helm chart](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset/templates) 

**Version of Helm and Kubernetes**:
Helm: [> 3.6.4](https://github.com/helm/charts/pull/9495)
Kubernetes: 1.15.11

**Which chart**:
stable/mongodb-replicaset

**How to reproduce it** (as minimally and precisely as possible):
- Install istio on the cluster
```
curl -L https://istio.io/downloadIstio | sh -
cd istio-1.5.2
export PATH=$PWD/bin:$PATH
istioctl manifest apply
```
- Label the default namespace for auto-injection of sidecar
```
kubectl label namespace default istio-injection=enabled
```
- Install mongodb-replicaset chart
```
helm install mongodb-replicaset stable/mongodb-replicaset
kubectl -n istio-system logs $(kubectl -n istio-system get po -l app=istiod -o jsonpath={.items[].metadata.name}) | grep -A 20 "Push Status"
```

Error
```
Push Status: {
    "pilot_conflict_inbound_listener": {
        "mongodb-replicaset-0.default": {
            "proxy": "mongodb-replicaset-0.default",
            "message": "Conflicting inbound listener:fe80::5ce0:2aff:febf:5a7d:27017. existing: mongodb-replicaset-client.default.svc.cluster.local, incoming: mongodb-replicaset.default.svc.cluster.local"
        }
    }
}
```

**Anything else we need to know**:

Making the creation of the [client service](https://github.com/steven-sheehy/charts/blob/master/stable/mongodb-replicaset/templates/mongodb-service-client.yaml) optional should resolve this

**Comment by herrberk** [comment]
Indeed, the client service should be optional since I've seen this issue with Istio as well. The workaround was creating a ServiceEntry for the main service in case anyone stumbles upon this.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongodb-stateful-service-entry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ printf "*.mongodb-replicaset.%s.svc.cluster.local" .Release.Namespace | quote }}
  location: MESH_INTERNAL
  ports:
  - number: {{ index .Values "mongodb-replicaset" "port" }}
    name: mongodb
    protocol: TCP
  resolution: NONE
```
