### ISSUE TITLE
[stable/grafana] Helm upgrade fails if Grafana anonymous access is configured

### ISSUE THREAD

**Issue by kjozsa** [helm/charts#22220]
I'm deploying `stable/helm` with the following values.yml:
```
grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin
```
It works perfectly, but the next `helm upgrade` fails with this message:
```
Error: UPGRADE FAILED: template: grafana/templates/secret.yaml:1:58: executing "grafana/templates/secret.yaml" at <.Values.env.GF_SECURITY_ADMIN_PASSWORD__FILE>: can't evaluate field GF_SECURITY_ADMIN_PASSWORD__FILE in type interface {}
```
I assume the chart simply needs to get prepared for this case.
