### ISSUE TITLE
[cluster-autoscaler] No way to define cluster-autoscaler-priority-expander config map for priority expander

### ISSUE THREAD

**Issue by AmitThakkar** [helm/charts#22269]
Cluster autoscaler supports expanders https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders.

And helm chart also supports to select them with `extraArgs.expander` parameter. But in case of priority expander, **cluster-autoscaler-priority-expander** config map must be defined. But there is no way to define the **cluster-autoscaler-priority-expander**.

**Comment by AmitThakkar** [comment]
`expanderPriorities` added for defining the `cluster-autoscaler-priority-expander` ConfigMap.

**Comment by briananstett** [comment]
@AmitThakkar Could you provide an example on how I could set `expanderPriorities` using `helm --set`? I'm getting yaml parsing issues. 

I'm trying to get this configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10: 
      - onDemand
    50: 
      - spot
```
