### ISSUE TITLE
[stable/prometheus-operator] prometheus volumeClaimTemplate not working

### ISSUE THREAD

**Issue by Jojoooo1** [helm/charts#22265]
**Describe the bug**
PersistentVolume manifest 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/mnt/data"
```
Prometheus chart value:
```
prometheus:
  prometheusSpec:
    retention: "15d"
    resources: {} # limit
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: manual
          volumeName: prometheus-pv
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
            storage: 10Mi
```

Also tried with selector & matchLabels

**Version of Helm and Kubernetes**:
kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

helm version: 
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Which chart**:
stable/prometheus-operator

**What you expected to happen**:
Prometheus should create a PVC to match the PV
