### ISSUE TITLE
[stable/jenkins] Add Startup Probe

### ISSUE THREAD

**Issue by fl-max** [helm/charts#22279]
I am currently running into an issue where on startup, Jenkins indexes all my pipelines (branches, tags, PRs) which takes a long time. During this period, without setting an extremely high `master.healthProbeReadinessInitialDelay` & `master.healthProbeLivenessInitialDelay`, the Jenkins deployment will simply go into a restart loop.

One way of helping to mitigate this issue is to add a [Startup Probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes) to the Jenkins deployment. Startup Probes were introduced in K8s `v1.16` so it should have a version check. Example:

```yaml
# jenkins-master-deployment.yaml
...
{{- if .Values.master.healthProbes }}
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
          startupProbe:
            httpGet:
              path: "{{ default "" .Values.master.jenkinsUriPrefix }}/login"
              port: http
            initialDelaySeconds: {{ .Values.master.healthProbeStartupInitialDelay }}
            periodSeconds: {{ .Values.master.healthProbeStartupPeriodSeconds }}
            timeoutSeconds: {{ .Values.master.healthProbesStartupTimeout }}
            failureThreshold: {{ .Values.master.healthProbeStartupFailureThreshold }}
{{- end }}
          livenessProbe:
...
```

**Is your feature request related to a problem? Please describe.**
See above

**Describe the solution you'd like**
Add a startupProbe so that the Readiness and Liveness probes can kick in sooner, and thus allow the Service endpoint to become available. This avoids unnecessary static wait times when using long `initialDelaySeconds`.

**Describe alternatives you've considered**
Set long `initialDelaySeconds` for Readiness and Liveness probes

**Additional context**

P.S.: If anyone else has run into the long indexing issue at startup, would love to hear how you fixed/mitigated it.
