### ISSUE TITLE
MongoDB arbiter poddisruption budget never allows drain

### ISSUE THREAD

**Issue by paulgmiller** [helm/charts#22287]
**Describe the bug**
Because mongodb's default replica count and minavailable for arbiter are both 1 creating a pod that can never be evicted. 

https://github.com/helm/charts/blob/master/stable/mongodb/templates/poddisruptionbudget-arbiter-rs.yaml
https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml
```
replicas:
    secondary: 1
    arbiter: 1

  ## Pod Disruption Budget
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  pdb:
    enabled: true
    minAvailable:
      primary: 1
      secondary: 1
      arbiter: 1
```

**Version of Helm and Kubernetes**:
Anything that supports PDBs?

**Which chart**:
mongodb

**What happened**:
We upgrade clusters by draining nodes 1 by 1. However nodes with the arbiter would hang. 

**What you expected to happen**:
Have minavailable < replicas. 

**How to reproduce it** (as minimally and precisely as possible):
Apply the chart with default values. Try and drain the node that gets the arbiter. It should timeout. 

**Anything else we need to know**:
