### ISSUE TITLE
[stable/datadog] Conf.d does not template postgresql configuration

### ISSUE THREAD

**Issue by rchenzheng** [helm/charts#22284]
**Describe the bug**

When trying to configure postgresql integration with the agent, it creates a file within conf.d instead of the right integration within conf.d/postgres.d

**Version of Helm and Kubernetes**:

Helm v2.13.1 and Kubernetes v1.15.11-gke.5

**Which chart**:

datadog/stable v1.39.8

**What happened**:

I've defined the following values for postgres.d integration but the configuration does not get created or gets created in the wrong folder

https://docs.datadoghq.com/integrations/postgres/

```
datadog:
  confd:
    postgres.d: |-
      init_config:
      instances:
        - host: mydb.database.svc
          port: 5432
          username: datadog
          password: password1
         ssl: prefer
```

Also tried

```
datadog:
  confd:
    postgresql.yaml: |-
      init_config:
      instances:
        - host: mydb.database.svc
          port: 5432
          username: datadog
          password: password1
         ssl: prefer
```

**What you expected to happen**:

This should've created a configuration within /etc/datadog-agent/conf.d/postgres.d/ in the agent for the the data to be sent to datadog postgres integration

**How to reproduce it** (as minimally and precisely as possible):

Define the sample configuration above as a value to the chart

**Anything else we need to know**: no
