### ISSUE TITLE
[stable/traefik] enable tls communication with kv provider for storeconfig-job

### ISSUE THREAD

**Issue by ghost** [helm/charts#22317]
**Access certificates in store config job for secure transmission**
Store config job fails when trying to store to a kv provider that only accepts tls communication. Even when tls is enabled like such in the chart : 
```yaml
  consul:
    endpoint: consul-server:8501
    watch: true
    prefix: traefik
    tls:
      ca: "/etc/ssl/ca.crt"
      cert: "/etc/ssl/tls.crt"
      key: "/etc/ssl/tls.key"
```

It returns a connection refused error. 

**Poposed solution**
I suggest the storeconfig-job also takes `extraVolumeMounts` and `extraVolumes` parameters. This way it will be able to access certificates in the job pod and store config in a secured way to kv store. 

The volumeMounts section would be modified as such

```yaml
volumeMounts:
          {{- if .Values.extraVolumeMounts }}{{ toYaml .Values.extraVolumeMounts | trim | nindent 10 }}{{ end }}
          - mountPath: /config
            name: config
          - mountPath: /acme
            name: acme
```
and volumes : 
```yaml
      volumes:
      {{- if .Values.extraVolumes  }}{{ toYaml .Values.extraVolumes | trim | nindent 6 }}{{ end }}
      - name: config
        configMap:
          name: {{ template "traefik.fullname" . }}
```

**Alternatives  considered**
 I have considered attaching a proxy to the containers at runtime but it also need modifications in storeconfig-job.yaml in annotations and it is less generic than the proposed solution. 

**Additional context**
I have tested this implementation in Kubernetes cluster running a TLS + ACL secured Consul Cluster
