### ISSUE TITLE
[stable/grafana] How to configure gitlab oauth ?

### ISSUE THREAD

**Issue by charlspjohn** [helm/charts#22314]
could somebody tell how to configure gitlab oauth with existing grafana values file ?
I could see options to configure github oauth, but no gitlab oauth. Please help

**Comment by r0bobo** [comment]
I used a combination of `gitlab.ini` modifications and environment variables based on the [Grafana Docs](https://grafana.com/docs/grafana/latest/auth/github/).

```yaml
# values.yaml

envFromSecret: grafana-oidc-gitlab
grafana.ini:
  auth.gitlab:
    enabled: true
    scopes: api
    auth_url: https://your-gitlab-url/oauth/authorize
    token_url: https://your-gitlab-url/oauth/token
    api_url: https://your-gitlab-url/api/v4
```

And the `grafana-oidc-gitlab` secret contains these environment variables:
```bash
GF_AUTH_GITLAB_CLIENT_ID=****
GF_AUTH_GITLAB_CLIENT_SECRET=****
```
