### ISSUE TITLE
agent not able to ship logs in Fedora release 31 using jourald driver

### ISSUE THREAD

**Issue by codeaprendiz** [helm/charts#22344]
**Describe the bug**
datadog agent not able to ship logs in Fedora release 31 using jourald driver
**Version of Helm and Kubernetes**:
- Helm
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

- Kubernetes
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

We are using typhoon kubernetes

**Which chart**:
helm install datadog-release datadog-2.2.10 -f dev-values.yaml

**What happened**:
```bash
    docker
    ------
      Instance ID: docker [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/docker.d/conf.yaml.default
      Total Runs: 2
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-05-11 20:20:00.000000 UTC
      Last Successful Execution Date : Never
      Error: temporary failure in dockerutil, will retry later: try delay not elapsed yet
      No traceback
      Warning: Error initialising check: temporary failure in dockerutil, will retry later: try delay not elapsed yet

  kube-system/kube-proxy-4tbkv/kube-proxy
  ---------------------------------------
    Type: file
    Path: /var/log/pods/kube-system_kube-proxy-4tbkv_3c78aafd-6b4d-4861-aeab-a7de7d7fc837/kube-proxy/*.log
    Status: Error: could not find any file matching pattern /var/log/pods/kube-system_kube-proxy-4tbkv_3c78aafd-6b4d-4861-aeab-a7de7d7fc837/kube-proxy/*.log, check that all its subdirectories are executable
      0 files tailed out of 0 files matching

  journald
  --------
    Type: journald
    IncludeUnits: docker.service, sshd.service
    Status: Error: failed to open journal in directory "/var/log/journal/": 13

  default/datadog-release-8zlz2/init-config
  -----------------------------------------
    Type: file
    Path: /var/log/pods/default_datadog-release-8zlz2_fc38f9ec-db40-4b81-941b-a5d22713118c/init-config/*.log
    Status: Error: could not find any file matching pattern /var/log/pods/default_datadog-release-8zlz2_fc38f9ec-db40-4b81-941b-a5d22713118c/init-config/*.log, check that all its subdirectories are executable
      0 files tailed out of 0 files matching
```

The values.yaml code snippet
```yaml
datadog:
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  env:
    - name: DD_KUBELET_TLS_VERIFY
      value: "false"
    - name: DD_APM_NON_LOCAL_TRAFFIC
      value: "true"
    - name: DD_LEADER_ELECTION
      value: "true"
    - name: DD_COLLECT_KUBERNETES_EVENTS
      value: "true"

  confd:
    journald.yaml: |-
      logs:
        - type: journald
          path: /var/log/journal/
          include_units:
            - docker.service
            - sshd.service

agents:
  volumes:
    - hostPath:
        path: /var/log/journal
      name: journald
    ## @param volumeMounts - list of objects - optional
    ## Specify additional volumes to mount in the cluster-agent container

  volumeMounts:
    - name: journald
      mountPath: /var/log/journal
      readOnly: true
```

**What you expected to happen**:
Logs should automatically start shipping

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I can see the logs folder inside the worker node
```bash
[root@ip-172-28-20-40 ec29ba320fc99b68d47367f1a5175abd]# pwd
/var/log/journal/ec29ba320fc99b68d47367f1a5175abd
[root@ip-172-28-20-40 ec29ba320fc99b68d47367f1a5175abd]# ls -ltrh
total 1.4G
-rwxr-xr-x+ 1 root systemd-journal  96M May  9 09:27 system@3fc46b75b77e4faa82a9cb098eee8669-0000000000000001-0005a52a1c90df5f.journal
-rwxr-xr-x+ 1 root systemd-journal  96M May  9 23:06 system@3fc46b75b77e4faa82a9cb098eee8669-00000000000168fc-0005a533b8cca214.journal
```

Inside the pod they somehow do not have permission
```bash
$ kubectl exec -it datadog-release-vhcjz bash
root@datadog-release-vhcjz:/# cd /var/log
root@datadog-release-vhcjz:/var/log# ls
apt  btmp  datadog  dpkg.log  faillog  journal	lastlog  pods  wtmp
root@datadog-release-vhcjz:/var/log# cd journal/
root@datadog-release-vhcjz:/var/log/journal# ls
ls: cannot open directory '.': Permission denied
root@datadog-release-vhcjz:/var/log/journal# ls
ls: cannot open directory '.': Permission denied
root@datadog-release-vhcjz:/var/log/journal# cd ..
root@datadog-release-vhcjz:/var/log# cd pods
root@datadog-release-vhcjz:/var/log/pods# ls
ls: cannot open directory '.': Permission denied
```

I have provided permission to both on `pods` and `journal` folder recursively.
