### ISSUE TITLE
[stable/prometheus-operator] How to create storage provisioning automatically 

### ISSUE THREAD

**Issue by vrathore18** [helm/charts#22358]
In my current setup, I created efs volumn then pv, pvc, sc manually and then using the created sc(ie. k8s-utils-efs-provisioner-sc) in value.yaml.

```
prometheus:
   prometheusSpec:
     storageSpec:
       volumeClaimTemplate:
         spec:
           storageClassName: k8s-utils-efs-provisioner-sc
           accessModes: ["ReadWriteOnce"]
           resources:
             requests:
               storage: 10Gi
```

But I think prometheus-operator can automatically do the provision for me as I am using AWS. Could you guy help me to do so. I am not able to figure out what could be the values in need to modify
