### ISSUE TITLE
[stable/prometheus-operator] Alertmanager does not receive alerts from Grafana

### ISSUE THREAD

**Issue by mordowiciel** [helm/charts#22395]
**Describe the bug**
Grafana sends the Alertmanager notification for created alert, but the alert is not received by Alertmanager. The other alerts coming from Prometheus are received.

**Version of Helm and Kubernetes**:

**Helm**: 
- {Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Kubernetes**:
- Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
- Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
 
**Which chart**:
stable/prometheus-operator

**What happened**:
I've tried to set up the alert for Cloudwatch datasource. I've created the Prometheus Alertmanager notification channel by Grafana UI, and then assigned that channel to my alert. In the Grafana logs I can see that the alert was successfully sent, but according to Alertmanager log, such alert is never received. The other alerts pushed from Prometheus are delivered without a problem.

**What you expected to happen**:
To see the alert issued by Grafana in Alertmanager console.

**How to reproduce it** (as minimally and precisely as possible):
- Create notification channel with type Prometheus Alertmanager by Grafana UI.
- Assign the notification channel to the chosen firing alert.
- Check the Grafana logs to see the alert was sent successfully.
- Check the Alertmanager logs to see that such alert wasn't delivered.

**Anything else we need to know**:
Below you can find the Helm values configurations for chosen components.

**Alertmanager**:
```
alertmanager:
  enabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
      - alertmanager.test.com
  config:
      global:
        smtp_smarthost: mail.test.com:25
        smtp_from: test@test.com
        smtp_require_tls: false
      receivers:
      - name: 'grafana-test'
        email_configs:
          - to: test@test.com
      - name: "null"
      route:
        receiver: grafana-test
  alertmanagerSpec:
    logLevel: debug
```
**Grafana**:
```
grafana:
    grafana.ini:
      log:
        level: debug
    extraContainers: |
        - image: ubuntu:bionic
          name: fsfreeze
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: storage
              readOnly: false
          command:
            - "/bin/bash"
            - "-c"
            - "sleep infinity"
    image:
      pullPolicy: Always
    adminPassword: admin
    sidecar:
      imagePullPolicy: Always
      datasources:
        enabled: true
        defaultDatasourceEnabled: false
      dashboards:
        enabled: true
        provider:
          allowUiUpdates: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'Downloaded AWS Dashboards'
            orgId: 1
            folder: 'AWS'
            type: file
            disableDeletion: true
            editable: true
            options:
              path: /var/lib/grafana/dashboards/aws-downloaded-dashboards
    dashboards:
      aws-downloaded-dashboards:
        rds:
          gnetId: 707
          datasource: Cloudwatch
        s3:
          gnetId: 575
          datasource: Cloudwatch
        lambda:
          gnetId: 593
          datasource: Cloudwatch
        api-gateway:
          gnetId: 1516
          datasource: Cloudwatch
        classic-lb:
          gnetId: 644
          datasource: Cloudwatch
        application-lb:
          gnetId: 650
          datasource: Cloudwatch
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      hosts:
        - grafana.test.com
    persistence:
      enabled: true
      type: pvc
      size: 10Gi
      storageClassName: monitoring
      accessModes: ["ReadWriteOnce"]
```

**Grafana Cloudwatch Datasource:**
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-cloudwatch
  labels:
     grafana_datasource: "1"
type: Opaque
stringData:
    cloudwatch.yaml: |-
      apiVersion: 1
      datasources:
      - name: Cloudwatch
        type: cloudwatch
        jsonData:
          authType: arn
          assumeRoleArn: arn:aws:iam::xxx:role/xxx
          defaultRegion: "eu-west-1"
```

**Grafana logs**
```
t=2020-05-14T11:37:01+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Successful Request Latency alert" id=1
t=2020-05-14T11:37:01+0000 lvl=dbug msg="Should notify" logger=alerting.notifier.prometheus-alertmanager ruleId=1 state=alerting previousState=alerting
t=2020-05-14T11:37:01+0000 lvl=dbug msg="Sending notification" logger=alerting.notifier type=prometheus-alertmanager uid=0n977cRMk isDefault=false
t=2020-05-14T11:37:01+0000 lvl=info msg="Sending Alertmanager alert" logger=alerting.notifier.prometheus-alertmanager ruleId=1 notification=alertmanager
t=2020-05-14T11:37:01+0000 lvl=dbug msg="Sending webhook" logger=notifications url=http://alertmanager.test.com//api/v1/alerts http method=POST
t=2020-05-14T11:37:01+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=167.976 alertId=1 name="Successful Request Latency alert" firing=true attemptID=1
```

**Alertmanager logs:**
```
level=info ts=2020-05-14T10:46:12.328Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
level=info ts=2020-05-14T10:46:12.328Z caller=main.go:232 build_context="(go=go1.13.5, user=root@00c3106655f8, date=20191211-14:13:14)"
level=debug ts=2020-05-14T10:46:12.334Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc:9094
level=debug ts=2020-05-14T10:46:12.334Z caller=delegate.go:230 component=cluster received=NotifyJoin node=01E89CNBKEDN2PX1ASEJQQ86BH addr=100.64.22.93:9094
level=debug ts=2020-05-14T10:46:12.346Z caller=cluster.go:306 component=cluster memberlist="2020/05/14 10:46:12 [WARN] memberlist: Failed to resolve alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc on 10.100.0.10:53: no such host\n"
level=warn ts=2020-05-14T10:46:12.346Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc on 10.100.0.10:53: no such host\n\n"
level=info ts=2020-05-14T10:46:12.346Z caller=cluster.go:230 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2020-05-14T10:46:12.346Z caller=main.go:322 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring.svc on 10.100.0.10:53: no such host\n\n"
level=info ts=2020-05-14T10:46:12.349Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=debug ts=2020-05-14T10:46:12.401Z caller=main.go:370 externalURL=http://alertmanager.test.com
level=info ts=2020-05-14T10:46:12.401Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2020-05-14T10:46:12.402Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=debug ts=2020-05-14T10:46:12.405Z caller=main.go:480 routePrefix=/
level=info ts=2020-05-14T10:46:12.406Z caller=main.go:497 msg=Listening address=:9093
level=info ts=2020-05-14T10:46:14.349Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000128687s
level=debug ts=2020-05-14T10:46:16.349Z caller=cluster.go:645 component=cluster msg="gossip looks settled" elapsed=4.000433939s
level=debug ts=2020-05-14T10:46:18.349Z caller=cluster.go:645 component=cluster msg="gossip looks settled" elapsed=6.000641418s
level=debug ts=2020-05-14T10:46:20.349Z caller=cluster.go:645 component=cluster msg="gossip looks settled" elapsed=8.000841217s
level=info ts=2020-05-14T10:46:22.350Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.001042604s
(...)
level=debug ts=2020-05-14T11:31:32.976Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeControllerManagerDown[843da4a][active]
level=debug ts=2020-05-14T11:31:32.984Z caller=dispatch.go:465 component=dispatcher aggrGroup={}:{} msg=flushing alerts="[KubeControllerManagerDown[843da4a][active] KubeSchedulerDown[e26ea36][active]]"
level=debug ts=2020-05-14T11:31:33.970Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=PrometheusRuleFailures[20f1e85][active]
level=debug ts=2020-05-14T11:31:33.973Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}:{job=\"prometheus-operator-prometheus\"}" msg=flushing alerts=[PrometheusRuleFailures[20f1e85][active]]
level=debug ts=2020-05-14T11:31:37.030Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeSchedulerDown[e26ea36][active]
level=debug ts=2020-05-14T11:31:45.478Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}:{job=\"kube-proxy\"}" msg=flushing alerts=[TargetDown[d0690c0][active]]
level=debug ts=2020-05-14T11:31:45.478Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[d0690c0][active]
level=debug ts=2020-05-14T11:31:45.478Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[ec4b427][active]
level=debug ts=2020-05-14T11:31:45.479Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}:{job=\"ec2_sd\"}" msg=flushing alerts=[TargetDown[ec4b427][active]]
level=debug ts=2020-05-14T11:32:15.475Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=Watchdog[3ab1c4d][active]
level=debug ts=2020-05-14T11:33:02.976Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeControllerManagerDown[843da4a][active]
level=debug ts=2020-05-14T11:33:03.970Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=PrometheusRuleFailures[20f1e85][active]
level=debug ts=2020-05-14T11:33:07.030Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeSchedulerDown[e26ea36][active]
level=debug ts=2020-05-14T11:33:15.476Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[d0690c0][active]
level=debug ts=2020-05-14T11:33:15.476Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[ec4b427][active]
level=debug ts=2020-05-14T11:33:45.475Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=Watchdog[3ab1c4d][active]
level=debug ts=2020-05-14T11:34:32.977Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeControllerManagerDown[843da4a][active]
level=debug ts=2020-05-14T11:34:33.970Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=PrometheusRuleFailures[20f1e85][active]
level=debug ts=2020-05-14T11:34:37.030Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeSchedulerDown[e26ea36][active]
level=debug ts=2020-05-14T11:34:45.475Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[d0690c0][active]
level=debug ts=2020-05-14T11:34:45.476Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[ec4b427][active]
level=debug ts=2020-05-14T11:35:15.476Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=Watchdog[3ab1c4d][active]
level=debug ts=2020-05-14T11:35:45.476Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}/{alertname=\"Watchdog\"}:{}" msg=flushing alerts=[Watchdog[3ab1c4d][active]]
level=debug ts=2020-05-14T11:36:02.976Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeControllerManagerDown[843da4a][active]
level=debug ts=2020-05-14T11:36:03.970Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=PrometheusRuleFailures[20f1e85][active]
level=debug ts=2020-05-14T11:36:07.030Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeSchedulerDown[e26ea36][active]
level=debug ts=2020-05-14T11:36:15.475Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[d0690c0][active]
level=debug ts=2020-05-14T11:36:15.475Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[ec4b427][active]
level=debug ts=2020-05-14T11:36:32.984Z caller=dispatch.go:465 component=dispatcher aggrGroup={}:{} msg=flushing alerts="[KubeControllerManagerDown[843da4a][active] KubeSchedulerDown[e26ea36][active]]"
level=debug ts=2020-05-14T11:36:33.973Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}:{job=\"prometheus-operator-prometheus\"}" msg=flushing alerts=[PrometheusRuleFailures[20f1e85][active]]
level=debug ts=2020-05-14T11:36:45.475Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=Watchdog[3ab1c4d][active]
level=debug ts=2020-05-14T11:36:45.478Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}:{job=\"kube-proxy\"}" msg=flushing alerts=[TargetDown[d0690c0][active]]
level=debug ts=2020-05-14T11:36:45.481Z caller=dispatch.go:465 component=dispatcher aggrGroup="{}:{job=\"ec2_sd\"}" msg=flushing alerts=[TargetDown[ec4b427][active]]
level=debug ts=2020-05-14T11:37:32.976Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeControllerManagerDown[843da4a][active]
level=debug ts=2020-05-14T11:37:33.970Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=PrometheusRuleFailures[20f1e85][active]
level=debug ts=2020-05-14T11:37:37.030Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=KubeSchedulerDown[e26ea36][active]
level=debug ts=2020-05-14T11:37:45.476Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[d0690c0][active]
level=debug ts=2020-05-14T11:37:45.476Z caller=dispatch.go:135 component=dispatcher msg="Received alert" alert=TargetDown[ec4b427][active]
```
**Notification channel setup:**
![grafana-alertmanager](https://user-images.githubusercontent.com/22351298/81930877-79b44f80-95e9-11ea-8e56-a368255adfb0.PNG)

**Assigning notification channel to alert:**
![grafana-alertmanager-notification](https://user-images.githubusercontent.com/22351298/81930889-7de06d00-95e9-11ea-9341-26b64b5c72a7.PNG)
