### ISSUE TITLE
[stable/grafana] Dashboad file is empty when use file option

### ISSUE THREAD

**Issue by leandroandrade87** [helm/charts#22464]
**Describe the bug**
When use the file option in dashboard, the json file in Grafana is empty, the only option than i could use was the RAW_JSON.

Worktree:

helm/helmfile-grafana.yaml
```
- name: grafana
  namespace: grafana
  chart: stable/grafana
  version: 5.0.25
  labels:
    app: xxx
  values:
  - "helmfiles/grafana/{{ requiredEnv "EKS_ENV" }}/values.yaml"
```
values.yaml
```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

      
dashboards:
  default:
    spring-batch:
      file: helm/dashboard-grafana/spring-batch.json
```

helm/helmfiles/grafana/production/dashboards/spring-batch.json

**Version of Helm and Kubernetes**:

```
sh-4.2$ helm version
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

```
sh-4.2$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:
```
- name: grafana
  namespace: grafana
  chart: stable/grafana
  version: 5.0.25
```

**What happened**:
This error:
`grafana t=2020-05-20T17:12:15+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=default file=/var/lib/grafana/dashboards/default/spring-batch.json error=EOF`

**What you expected to happen**:
The dashboard works.

**Comment by cabrinha** [comment]
Same issue here.

**Comment by dbrennand** [comment]
I also ran into the same issue and resulted in using the sidecar/configmap dashboard option instead.

**Comment by token97** [comment]
Same issue for me. Is someone finaly solved this ?

**Comment by austince** [comment]
Not stale, still broken!

**Comment by alexon1234** [comment]
Same issue

```
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        elasticsearch:
          file: dashboards/elasticsearch.json
```

When I do `cat /var/lib/grafana/dashboards/default/elasticsearch.json` and is empty
