### ISSUE TITLE
[stable/grafana] Allow storing grafana.ini as a secret

### ISSUE THREAD

**Issue by mraszplewicz** [helm/charts#22473]
**Is your feature request related to a problem? Please describe.**
Grafana.ini is currently stored as a configmap value. I have to configure auth.generic_oauth with client_id and client_secret and also I would like to configure external database connection with password authentication. Storing it in configmap is not the best idea...

**Describe the solution you'd like**
Be able to use existing secret as a grafana.ini source.

**Describe alternatives you've considered**
Alternatively you can provide separate options to configure database connection and auth.generic_oauth.

**Additional context**
https://github.com/helm/charts/issues/22175 can be related

**Comment by jaystile** [comment]
I concur. My deployment of grafana requires the use of a couple of secrets and passwords for oauth and datasources. Since everything is routed through the grafana.ini, I am looking for a good way to obfuscate those values.

**Comment by s-spindler** [comment]
We are facing the same issue here. We need to configure a `client_secret` and would prefer if it wouldn't show up in the clear...

**Comment by xUnholy** [comment]
This stale bot is absolutely useless...

As mentioned in my other issue #22175 it's important that I can use kubernetes secrets to store these secrets and not require to have them in my values for helm to render. `existingSecret` is already a function that is supported in the helm chart itself. EG. 
```
admin:
  existingSecret: 'grafana-admin-creds'
   userKey: admin-user
   passwordKey: admin-password
```

Something a long these lines would suffice and be a much better solution.

**Comment by xUnholy** [comment]
@davidkarlsen @mrueg @GMartinez-Sisti Sorry for tagging you all out of an act of desperation, as it appears creating an issue may not be tracked/monitored in this monolithic repo with ease.

Is this something on the current roadmap?

**Comment by GMartinez-Sisti** [comment]
I'm not a maintainer but I think I can help. 

Looks like there is already a way to perform this in a secure fashion without the need to change this chart or use environment variables for secrets.

1. Grafana config supports [file providers](https://grafana.com/docs/grafana/latest/administration/configuration/#file-provider) for specific values:
> file reads a file from the filesystem. It trims whitespace from the beginning and the end of files. The database password in the following example would be replaced by the content of the /etc/secrets/gf_sql_password file:

>[database]
password = $__file{/etc/secrets/gf_sql_password}

2. Use the feature `extraSecretMounts` (Additional grafana server secret mounts) to mount your secrets, and go from there.

You just need to check where the `extraSecretMounts` will be available to specify them in `grafana.ini`.

**Comment by xUnholy** [comment]
@GMartinez-Sisti thanks for the swift response!

That is indeed one way, I'm trying to get my head around how that looks, would you be able to provide an example if it's not too much effort? 

Ideally, the `existingSecret` functionality would be the simplest model considering it's already used in a lot of spots already, but if your method works then that is good enough!

**Comment by GMartinez-Sisti** [comment]
Using an example for oauth, you could do something like this:

grafana.ini:
```yaml
grafana.ini:
  [auth.generic_oauth]
  enabled = true
  client_id = $__file{/etc/secrets/auth_generic_oauth/client_id}
  client_secret = $__file{/etc/secrets/auth_generic_oauth/client_secret}
```

Existing secret, or created along with helm:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: auth_generic_oauth_secret
type: Opaque
stringData:
  client_id: <value>
  client_secret: <value>
```

Config for extraSecretMounts
```yaml
- extraSecretMounts:
  - name: auth_generic_oauth_secret_mount
     secretName: auth_generic_oauth_secret
     defaultMode: 0440
     mountPath: /etc/secrets/auth_generic_oauth
     readOnly: true
```

This should work (famous last words™), note that I wasn't able to deploy to test, but according to the chart these are the required configurations.

Please let me know if it worked, and I might send a PR to add this to the README.
