### ISSUE TITLE
[stable/prometheus-operator] empty selectors overridden with default

### ISSUE THREAD

**Issue by riptl** [helm/charts#22490]
**Describe the bug**

When specifying a Prometheus like so, a wrong Prometheus resource gets generated.
Notice the empty `serviceMonitorSelector`.

*The bug is applicable to similar other selectors too!*

Input: `values.yaml`

```yaml
prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorNamespaceSelector:
      matchLabels:
        has-metrics: "yes"
    serviceMonitorSelector: {}
```

Output: `Prometheus`

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-operator-prometheus
  namespace: monitoring
  ...
spec:
  serviceMonitorNamespaceSelector:
    matchLabels:
      has-metrics: "yes"
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-operator
  ...
```

**Version of Helm and Kubernetes**:

```
$ helm version

version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.11", GitCommit:"fd078e6ed95d359cb2c9ca6561754806718c1c98", GitTreeState:"clean", BuildDate:"2020-04-13T20:10:31Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/prometheus-operator 8.13.8

**What happened**:

The template checks for a falsy `serviceMonitorNamespaceSelector` value.
However, it should explicitly check for nil.

https://github.com/helm/charts/blob/6db305208a4893de0f62438bff65ea94f328976c/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L98

**What you expected to happen**:

The Prometheus-Operator README describes the `serviceMonitorSelector` as such:

> If {}, select all ServiceMonitors

Because the specified selector is not nil, but an empty object, I expected the generated Prometheus to look like this:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-operator-prometheus
  namespace: monitoring
  ...
spec:
  serviceMonitorNamespaceSelector:
    matchLabels:
      has-metrics: "yes"
  serviceMonitorSelector: {}
  ...
```

**How to reproduce it** (as minimally and precisely as possible):

- Install a Prometheus Operator with the Helm values as shown in the top-most listing.
- Print the generated Prometheus spec `kubectl get prometheus -oyaml`

**Anything else we need to know**:

A workaround is to set `serviceMonitorSelectorNilUsesHelmValues: false` and similar.

Following values will generate the expected Prometheus spec.

```yaml
prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorNamespaceSelector:
      matchLabels:
        has-metrics: "yes"
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
```
