### ISSUE TITLE
[stable/grafana] Specifying `restartPolicy` clause for `extraContainers` raises ValidationError

### ISSUE THREAD

**Issue by rsaffi** [helm/charts#22507]
**Describe the bug**
I'm relying on an extra container for applying predefined customizations to Grafana (updating home dashboard, switching theme to light), and those have to be done with `curl` calls to Grafana's API. 
I am bringing up an extra container to run a bash script that does that. The problem is that it's an ephemeral container that has to run only once every time the `grafana` chart is installed/upgraded, cleanly exiting right after. For accomplishing that, I wanted to specify `restartPolicy: Never` to the container definition under `extraContainers`, but when doing so, I run into an error.

**Version of Helm and Kubernetes**:

- Helm:

```
$ helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.14.2"}
```

- Kubernetes:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-04-23T22:11:11Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/grafana`

**What happened**:

```
$ helm upgrade grafana-development stable/grafana -f grafana-helm.yaml -n development
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[1]): unknown field "restartPolicy" in io.k8s.api.core.v1.Container
```

**What you expected to happen**:

I would expect that the extra container would be created with the `restartPolicy` as defined on its spec.
Without this, the ephemeral container that I want to spin up will keep on restarting, causing the pod to have `CrashLoopBackOff` status.

**How to reproduce it** (as minimally and precisely as possible):

Have an `extraContainers` definition on `values.yaml` that includes a `restartPolicy`.

This is the one I'm using and that triggered the error listed above:

```
extraContainers: |
  - name: grafana-configurator
    image: everpeace/curl-jq
    command: [ "/bin/bash","-vfx","/grafana-configurator.sh" ]
    restartPolicy: Never
    volumeMounts:
    - name: grafana-configurator-script-volume
      mountPath: /grafana-configurator.sh
      subPath: grafana-configurator.sh

extraContainerVolumes:
  - name: grafana-configurator-script-volume
    configMap:
      name: grafana-configurator-script
      items:
      - key: grafana-configurator.sh
        path: grafana-configurator.sh
```

It works as expected without the `restartPolicy` clause on the container's spec.

**Anything else we need to know**:
