### ISSUE TITLE
[stable/rabbitmq-ha] chmod: /var/lib/rabbitmq/.erlang.cookie: Operation not permitted on AKS azurefile

### ISSUE THREAD

**Issue by lucaghersi** [helm/charts#22551]
**Describe the bug**
Impossible to start rabbitmq-ha on Azure AKS; every configuration leads one way or another to this message: chmod: /var/lib/rabbitmq/.erlang.cookie: Operation not permitted

**Version of Helm and Kubernetes**:
Helm 3.2.1 / Kubernetes v1.16.7

**Which chart**:
rabbitmq-ha

**What happened**:
I filled the values.yaml charts and I applied the template but no matter what choice I made for the persistentVolume I always have the same result.

**What you expected to happen**:
RabbitMQ pod to start successfully

**How to reproduce it** (as minimally and precisely as possible):
Set the following values in the values.yaml file:

```
## Data Persistency
persistentVolume:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: managed-premium
  ## selector can be used to match an existing PersistentVolume
  selector: {}
  name: data
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  annotations: {}
  labels: {}
```

```
initContainer:
  enabled: true
  securityContext:
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  chownFiles: false
```

and leave the global securityContent section as it is.

**Anything else we need to know**:
I basically started with azurefiles setting first the uid and gid to zero, then I created a completely customized version of the storage class, like this:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbit-shared-disk
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=100
- gid=101
parameters:
  skuName: Premium_LRS
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

The init container works and set everything as it is supposed to be, but then the rabbitmq crashed in the init phase as the chmod cannot be applied - even if the pod runs with the same UID and GID as the file system.
After a number of tries, I moved to a managed disk as I thought - maybe it's a problem with azure files share - and still I got the same exact result.

Here you can see an extract of the actual pod template with the securityContext and the initContainer configuration:

```
spec:
      terminationGracePeriodSeconds: 10
      securityContext:
          fsGroup: 101
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 100
      serviceAccountName: dev-rabbitmq-ha
      initContainers:
        - name: bootstrap
          image: busybox:1.30.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          command: ['sh']
          args:
          - "-c"
          - |
            set -ex
            cp /configmap/* /etc/rabbitmq
            echo "${RABBITMQ_ERLANG_COOKIE}" > /var/lib/rabbitmq/.erlang.cookie
            chown -R 100:101 /var/lib/rabbitmq/
            chown -R 100:101 /etc/rabbitmq
          env:
```

**Comment by chrisvfabio** [comment]
I'm having the same issue with AKS and azurefile storage class. Are there any workarounds for this issue?

**Comment by ntx-ben** [comment]
I managed to get it working in AKS v1.18.10 with Azure Disks using this resource. The key here is both `spec.container.securityContext` and `spec.securityContext` where I specified `fsGroup`, `runAsUser`, `runAsGroup`:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    <REDACTED>
    role: master
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      <REDACTED>
  serviceName: rabbitmq
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "15692"
        prometheus.io/scrape: "true"
      labels:
        <REDACTED>
    spec:
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_SERVICE_NAME
          value: rabbitmq
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_NODENAME
          value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).rabbitmq.svc.cluster.local
        - name: K8S_HOSTNAME_SUFFIX
          value: .$(K8S_SERVICE_NAME).rabbitmq.svc.cluster.local
        - name: RABBITMQ_ERLANG_COOKIE
          value: <REDACTED>
        image: rabbitmq:3.8.4-management-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - ping
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        name: rabbitmq
        ports:
        - containerPort: 15672
          name: management
          protocol: TCP
        - containerPort: 15674
          name: web-stomp
          protocol: TCP
        - containerPort: 15675
          name: web-mqtt
          protocol: TCP
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - status
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 100
          runAsGroup: 101
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
        - mountPath: /etc/rabbitmq/enabled_plugins
          name: config
          subPath: enabled_plugins
        - mountPath: /etc/rabbitmq/rabbitmq.conf
          name: config
          subPath: rabbitmq.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: rabbitmq
        name: config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        <REDACTED>
      name: rabbitmq-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: default
```
