### ISSUE TITLE
[stable/prometheus-operator] prometheus-prometheus-oper-admission-create doesn't use the fqdn k8s master api adress on azure

### ISSUE THREAD

**Issue by Doubleth1nk** [helm/charts#22569]
**Deploy helm chart won't work**

**Version of Helm and Kubernetes**:
k8s: 1.16.9
helm terraform provider

**Which chart**:
stable/prometheus-operator 8.13.7

**What happened**:
Doesn't deploy

**What you expected to happen**:
That is deploys

**How to reproduce it** (as minimally and precisely as possible):
We had our yaml config like this:
```
prometheus:
  prometheusSpec:
    apiserverConfig:
      host: "${kubernetes_api_host}"
```
But this intermediate container doesn't use that apiserverConfig value. 
It is still the internal k8s masternode ip adress.

Is this config not being used by that intermediate container?
