### ISSUE TITLE
[stable/grafana] Datasources option creates a directory, instead of a yaml file

### ISSUE THREAD

**Issue by uhthomas** [helm/charts#22596]
**Describe the bug**
Pods fail to start when specifying datasources in the stable/grafana.

**Version of Helm and Kubernetes**:

```
Helm3 (helm-operator v1.0.2)
Kubernetes v1.17.5
```

**Which chart**: 

stable/grafana v5.0.26

**What happened**:

Pods fail to start when specifying datasources. The logs show:

```
t=2020-05-29T18:43:46+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: read /etc/grafana/provisioning/datasources/datasources.yaml: is a directory"
```

See Grafana Helm release:

```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 5.0.26
  values:
    image:
      tag: 7.0.1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
```

**What you expected to happen**:

The pods should start normally.

**How to reproduce it** (as minimally and precisely as possible):

Apply the helm-release to a k8s cluster and the pods should go into CrashLoopBackOff.

**Comment by uhthomas** [comment]
Just realised the syntax is actually:
```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 5.0.26
  values:
    image:
      tag: 7.0.1
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki:3100
```

A strange error for that sort of thing, but it's working. Thank you for your time 😄
