### ISSUE TITLE
stable/graylog - SSL offloading on Ingress controller - issue with configuration

### ISSUE THREAD

**Issue by zerowebcorp** [helm/charts#22606]
I have Traefik as ingress controller and I have configured the SSL offloading in Traefik. 

```
helm upgrade --install --namespace $NAMESPACE  graylog stable/graylog \
  --set tags.install-mongodb=false\
  --set tags.install-elasticsearch=false\
  --set graylog.mongodb.uri=mongodb://mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.$NAMESPACE.svc.cluster.local:27017/graylog?replicaSet=rs0 \
  --set graylog.elasticsearch.hosts=http://elasticsearch-client.$NAMESPACE.svc.cluster.local:9200 \
  --set graylog.externalUri="https://graylog.mywebsite.cloud" \
  --set graylog.input.udp.service.type="LoadBalancer" \
  --set graylog.input.udp.ports[0].name="gelf-udp" \
  --set graylog.input.udp.ports[0].port="30010" \
  --set graylog.input.udp.ports[0].nodePort="30010" \
  -f graylog.yaml
```

graylog.yaml

```
graylog:
  metadataLabels:
  image:
    repository: "graylog/graylog:3.3"
    pullPolicy: "IfNotPresent"
  replicas: 2
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: "10Gi"
  service:
    annotations:
    type: ClusterIP
    port: 9000
#  input:
#    udp:
#      service:
#        type: LoadBalancer
#      ports:
#        - name: gelf-udp
#          port: 30010
#          nodePort: 30010
#    tcp:
#      service:
#        type: NodePort
#      ports:
#        - name: gelf-tcp
#          port: 30011
#          nodePort: 30011

  ##
  ingress:
    enabled: false
  resources:
    limits:
      cpu: "1"
    requests:
      cpu: "100m"
      memory: "1Gi"

  ## Set Graylog Java heapsize. If this value empty, chart will allocate heapsize using `-XX:+UseCGroupMemoryLimitForHeap`
  ## ref: https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits
  ##
  # heapSize: "1024g"

  ## Additional graylog config which is defined on `graylog.conf`.
  ## You can find a complete list of graylog config from http://docs.graylog.org/en/3.0/pages/configuration/server.conf.html
  ## Graylog config is written in Java properites format. Make sure you write it correctly.
  ##
  # config: |
  #   elasticsearch_connect_timeout = 10s
  #   elasticsearch_socket_timeout = 60s
  #   elasticsearch_idle_timeout = -1s

  journal:
    deleteBeforeStart: true

  ## Additional server files will be deployed to /etc/graylog/server
  ## For example, you can put server certificates or authorized clients certificates here
  ##
  serverFiles:
     web-ssl.key: |
     web-ssl.cert: |

```
I have tls disabled in graylog.yaml
I pass the external URL

  --set graylog.externalUri="https://graylog.mywebsite.cloud" \

However, when helm chart creates the configmap, it creates the URL as 

http://https://graylog.mywebsite.cloud

and saved to the graylog.conf
This is causing graylog to not load.

How can I configure this so that SSL offloading is done elsewhere?
