### ISSUE TITLE
[stable/chart/openldap] Persistent store with existingClaim shows CreateContainerConfigError

### ISSUE THREAD

**Issue by rajsenthil** [helm/charts#22611]
**Version of Helm and Kubernetes**:
helm version: 
`version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
`
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment:**
minikube: version: v1.11.0
driver: kvm2
OS: Ubuntu 20.04
image: osixia/openldap-1.2.4

**Describe the bug**
I am trying to install openldap with the [values](https://github.com/rajsenthil/files/blob/master/share/opanldap-values.yaml) of persistent enabled true and assigned the [existing claim openldap](https://github.com/rajsenthil/files/blob/master/share/opanldap-values.yaml#L86). The claim is already created as 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/user/storage/openldap/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
Using helm install after the persistent volume claims are created and verified, I am getting **CreateContainerConfigError**
The reason seems to be related to the existing claims and see 
`Warning  Failed     0s (x3 over 15s)  kubelet, minikube  Error: stat /home/senthil/git/kubernetes-microservices/openldap/data: no such file or directory` (full description [here](https://github.com/rajsenthil/files/blob/master/share/pod-ldap-description.txt))

Please let me know what is wrong here. The error message pointing that no such file or directory (i.e /home/senthil/git/kubernetes-microservices/openldap/data) is where I have the ldap config data created earlier with imported users in it. I want to use the same files for the next openldap as well. Also the passwords used for admin and config were same in both the cases.

**Which chart**:
openldap

**What happened**:

Failing with **CreateContainerConfigError** 

**What you expected to happen**:
Use the existing claim with the new installation.

**How to reproduce it** (as minimally and precisely as possible):
persistent store file used is [here ](https://github.com/rajsenthil/files/blob/master/share/openldap-storage.yaml)
custom values used is [here](https://github.com/rajsenthil/files/blob/master/share/opanldap-values.yaml) 
Helm command is 
`helm install openldap --namespace dev -f /home/user/files/openldap-values.yaml /home/user/git/charts/stable/openldap/
`
**Anything else we need to know**:
It works using the [chart values](https://github.com/helm/charts/blob/master/stable/openldap/values.yaml) as it is without any existing claim.
