### ISSUE TITLE
[stable/nextcloud] nextcloud fails to become Ready when using external mysql database

### ISSUE THREAD

**Issue by rwlove** [helm/charts#22624]
**Describe the bug**
With an external mysql database and an associated service, nextcloud never becomes Ready. I can access the database with the credentials provided to nextcloud, but nextcloud just hangs with no relevant log information.

**Version of Helm and Kubernetes**:
Helm: v3.2.1
Kubernetes: v1.18.3

**Which chart**:
stable/nextcloud

**What happened**:
nextcloud does not become Ready

**What you expected to happen**:
nextcloud connects to the external database and becomes Ready

**How to reproduce it** (as minimally and precisely as possible):
```
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2                                                                                                              
kind: Deployment
metadata:
  name: mysql
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage                                                                                                                                          
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: nextcloud
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nextcloud-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: nextcloud
spec:
  ports:
  - name: dbport
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
```

From values.yaml
```
...
##
## External database configuration
##
externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: mysql

  ## Database host
  host: mysql-service

  ## Database user
  user: nextcloud

  ## Database password
  password: password

  ## Database name
  database: nextcloud

  ## Use a existing secret
  existingSecret:
    enabled: false
    # secretName: nameofsecret
    # usernameKey: username
    # passwordKey: password
...
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: false
...
```

I can connect to the database from the 'mysql-service' and I can see that the 'nextcloud' user with password 'password' has all of the grants.

```
➜  kubernetes git:(master) ✗ kubectl run -n nextcloud -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql-service -u nextcloud -D nextcloud -ppassword

If you don't see a command prompt, try pressing enter.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| nextcloud          |
+--------------------+
2 rows in set (0.01 sec)

mysql> use nextcloud;
Database changed
mysql> show tables;
Empty set (0.00 sec)

mysql> SHOW GRANTS FOR 'nextcloud'@'%';
+-----------------------------------------------------------------------+
| Grants for nextcloud@%                                                |
+-----------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'nextcloud'@'%' IDENTIFIED BY PASSWORD <secret> |
| GRANT ALL PRIVILEGES ON `nextcloud`.* TO 'nextcloud'@'%'              |
+-----------------------------------------------------------------------+
2 rows in set (0.00 sec)
```

Nextcloud never becomes Ready and it provides no clues as to what the problem is.

```
➜  kubernetes git:(master) ✗ kubectl -n nextcloud get pods                       
NAME                         READY   STATUS    RESTARTS   AGE
mysql-b49d8486c-nh6hv        1/1     Running   0          14h
nextcloud-75d85cc794-rbjsj   0/1     Running   204        14h
➜  kubernetes git:(master) ✗ kubectl -n nextcloud logs nextcloud-75d85cc794-rbjsj
Initializing nextcloud 17.0.0.9 ...
```

**Anything else we need to know**:

Is there a way to turn on debug logging? I wish I could get more information about what nextcloud is doing.
