### ISSUE TITLE
[stable/prometheus-pushgateway] serviceMonitor.additionalLabels wrong indentation in template

### ISSUE THREAD

**Issue by zagr0** [helm/charts#22623]
**Describe the bug**
if you try to set in values servicemonitor's additional labels for prometheus they are not added
```
serviceMonitor:
  enabled: true
  additionalLabels:
    add_to: prometheus
```
works if value contains wrong indentation
```
serviceMonitor:
  enabled: true
  additionalLabels:
      add_to: prometheus
``` 

**Version of Helm and Kubernetes**:
helm v3.1.2
k8s 1.15.10

**Which chart**:
stable/prometheus-pushgateway 1.4.0

**What happened**:
labels are not added

**What you expected to happen**:
expect to have labels set for servicemonitor

**How to reproduce it** (as minimally and precisely as possible):
install chart with values:
```
serviceMonitor:
  enabled: true
  additionalLabels:
    add_to: prometheus
```
