### ISSUE TITLE
[stable/airflow] initContainers / Git-sync with K8sExecutor: dag_id not found

### ISSUE THREAD

**Issue by marclamberti** [helm/charts#22637]
**Describe the bug**
When either the initContainer parameter or Git-sync parameter is set to true, the repo with the DAGs is well cloned but not in the worker pods.

**Version of Helm and Kubernetes**:
Helm 3
Kubernetes 1.16

**Which chart**:
stable/airflow

**What happened**:
`airflow.exceptions.AirflowException: dag_id could not be found: parallel_dag. Either the dag did not exist or it failed to parse`
In the pod executing the task and the folder /dags is empty

**What you expected to happen**:
The folder shouldn't be empty

**How to reproduce it** (as minimally and precisely as possible):

```
values:
    dags:
        git:
            url: "https://github.com/marclamberti/airflow-dags"
            ref: "master"
        initContainer:
            enabled: true

```
**Anything else we need to know**:
Not yet tested, but I think the following env vars should be set as well:
  AIRFLOW__KUBERNETES__GIT_REPO: "{{ .Values.dags.git.url }}"
  AIRFLOW__KUBERNETES__GIT_BRANCH: "{{ .Values.dags.git.ref }}"
  AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "{{ .Values.dags.path }}"
when initContainer or GitSync is actived

@thesuperzapper keep you in touch :)
