### ISSUE TITLE
[stable/airflow] install-requirements.sh not running with installRequirements true

### ISSUE THREAD

**Issue by alexbegg** [helm/charts#22656]
**Describe the bug**
The script `install-requirements.sh` won't run during pod startup with "dags: installRequirements: true" and using git-sync. The packages in `dags/requirements.txt` do not get installed.

**Version of Helm and Kubernetes**:
Helm: 3.2.1
Kubernetes: 1.15.7

**Which chart**:
stable/airflow: 7.1.1

**What happened**:
The script install-requirements.sh won't run during pod startup. The packages in `dags/requirements.txt` is not installed even after restarting the pods multiple times.

I exec'd into the scheduler container and did `cat dags/requirements.txt` and I do see my list of requirements.

I checked the logs of the pods and it shows `*** installing requirements...` immediately followed by `*** installing global extra pip packages...`, meaning nothing was printed when install-requirements.sh ran (which seems to me that it never ran), but installRequirements is defiantly true because `*** installing requirements...` did print.

**What you expected to happen**:
When the pods start the packages listed in `dags/requirements.txt` should be installed

**How to reproduce it** (as minimally and precisely as possible):

1. Have a git repo with a requirements.txt file (can contain any package such as `azure-keyvault==1.1.0`)
2. Set the values in values.yaml:
    - "dags: installRequirements: true"
    - the values for the git sidecar in "dags: git" using a SSH key
    - "dags: gitSync: enabled: true"
3. Install the stable/airflow Helm chart using the values.yaml file with the above values
4. After the pods start the package "azure-keyvault" won't be installed

**Anything else we need to know**:
The dags values I am using is
```
dags:
  installRequirements: true
  git:
    url: ssh://git@bitbucket.org/CurrencyCap/currencyairflowdags.git
    ref: master
    repoHost: bitbucket.org
    secret: airflow-git-keys
    privateKeyName: currencyairflowdags_access_key
    gitSync:
      enabled: true
      refreshTime: 60
```
The dags folder does have the requirements.txt after the pod starts, so the git-sync is working fine

If I exec into the container and run `/home/airflow/scripts/install-requirements.sh` manually it does install the packages from my `dags/requirements.txt` file (so the script is fine), but if I delete the pods and they get recreated then the packages are not installed.

I think `&& /home/airflow/scripts/install-requirements.sh`is not working in the entrypoint args
