### ISSUE TITLE
[stable/jenkins] Backup issue with serviceaccount and IAM roles

### ISSUE THREAD

**Issue by KrzesloSzatan** [helm/charts#22670]
Im deploying jenkins with terraform on AWS using jenkins-values.yaml and while i am enabling the backup 

```
backup:
  enabled: true
  componentName: "backup"
  schedule: "38 13 * * *"
  annotations: {}
  image:
    repository: "maorfr/kube-tasks"
    tag: "0.2.0"
  extraArgs: []
  existingSecret: {}
  env:
  - name: "AWS_REGION"
    value: "eu-central-1"
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  destination: "s3://xxx"
```
the template creates a serviceaccount jenkins-backup which then is used by the cronjob in created pods to do the backup as intended. I would like to attach a IAM role to it using the annotation as in AWS [doc](https://docs.amazonaws.cn/en_us/eks/latest/userguide/create-service-account-iam-policy-and-role.html) BUT, the problem is that i actually cannot add any annotation to this account using the template (i can do it only by using the kubectl annotate sa.... ) because there is no possible option to annotate this account in the yaml file. This annotations should then be converted "automagically" via some webhook on AWS (didnt get into details at that to cyte how this works) to proper envs for the pod

AWS_ROLE_ARN
arn:aws:iam::11111111111:role/xxxxxxxx
AWS_WEB_IDENTITY_TOKEN_FILE
/var/run/secrets/eks.amazonaws.com/serviceaccount/token

 I tried to set the annotations to the backup part like that 

```
backup:
  enabled: true
  componentName: "backup"
  schedule: "38 13 * * *"
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::11111111111:role/xxxxxxxx
  image:
    repository: "maorfr/kube-tasks"
    tag: "0.2.0"
```
BUT as i have checked in the dashboard pod gets only the part "eks.amazonaws.com/role-arn:" and the rest is ommited but while i click on the edit button in the dashboard in the pod section it shows the annotation propelry but while there is a number for the tennant ID it marks the annotation with ' ' so it looks like that 

eks.amazonaws.com/role-arn: 'arn:aws:iam::11111111111:role/xxxxxxxx'

while when i change it to whatever but without the tennant id 1111111111111 it doesnt set ' ' and i can see the whole annotation in the dashboard (but not the proper one so the envs are missing). 

It works properly when i add this annotation to the jenkins-backup serviceaccount manualy using kubectl. Then it attaches proper envs to the pod BUT there is still an issue with access rights

```
WebIdentityErr: unable to read file at /var/run/secrets/eks.amazonaws.com/serviceaccount/token
caused by: open /var/run/secrets/eks.amazonaws.com/serviceaccount/token: permission denied
```

This can be fixed by editing pod and adding to the pod manually via kubectl. 

```
securityContext:
  fsGroup: 65534
```

To sum it up:
I cant add annotation to serviceaccount "jenkins-backup" created by the default backup template from yaml that should pass on the vars to the pod created by cronjob for the iam role to be used to send the backup to the bucket and i have to set fsGroup: 65534 manualy on the pod for the serviceaccount to be able to read the token. 

If I set the annotation to the jenkins-backup serviceaccount and add the fsGroup: 65534 to the pod's securitycontext manualy via kubect the backup works fine. 

Can you please point me if there is something im doing wrong or it shouldnt work like that or what is wrong ?
 
**Which chart**:
stable/jenkins

Is there anything id should mention more ? Im still learning so sry if i dint mention something crucial.
