### ISSUE TITLE
[stable/prometheus-postgres-exporter] Allow multiple instances

### ISSUE THREAD

**Issue by bueti** [helm/charts#22714]
**Is your feature request related to a problem? Please describe.**
Related to PR #21804. I would like to be able to configure multiple instances without using Kubernetes Secrets. 
I am using [helm-secrets](https://github.com/zendesk/helm-secrets) for secrets handling. Combined with a KMS this is a cleaner and more secure way of handling sensitive data than using Kubernetes Secrets.
 

**Describe the solution you'd like**
Add a configuration parameter `datasources`:

```yaml
config:
  datasources:
    - host: <host1>
      port: <port1>
      user: <user1>
      password: <password1>
      database: <database1>
    - host: <host2>
      port: <port2>
      user: <user2>
      password: <password2>
      database: <database2>
    - ...
```
This configuration then would be translated into the postgres connections string: `postgresql://<user1>:<password1>@<host1>:<port1>/<database1>?sslmode=disable,<user2>:<password2>@<host2>:<port2>/<database2>?sslmode=disable`

This would enable users to use their method of choice to encrypt the login information.

**Describe alternatives you've considered**
Another possible way would be to adjust the existing `datasource` configuration but that would break backwards compatibility.

**Additional context**
n/a
