### ISSUE TITLE
[stable/datadog] Set DATADOG_HOST automatically

### ISSUE THREAD

**Issue by PSanetra** [helm/charts#22723]
When setting up the Cluster Agent external metric server it is necessary to define `DATADOG_HOST` if you are using an EU account.

I think this environment variable should default to `https://api.{{ .Values.datadog.site }}`.

See https://docs.datadoghq.com/agent/cluster_agent/external_metrics/#custom-metrics-server and https://github.com/zorkian/go-datadog-api/blob/9e2c892691035a7685a16d5839910cfc54e42fb6/client.go#L55

**Comment by BitProcessor** [comment]
Still needed:

```
    clusterAgent:
      env:
      - name: DATADOG_HOST
        value: "https://app.datadoghq.eu" 
      enabled: true
      metricsProvider:
        enabled: true
```
