### ISSUE TITLE
[stable/jenkins] Not clear how to separate JCasC config from Helm config

### ISSUE THREAD

**Issue by codiophile** [helm/charts#22721]
**Describe the bug**
I'm trying to figure out how to separate the JCasC config from the helm configuration. Having the config inline in values.yaml doesn't seem ideal. I tried:

```
master:
  containerEnv:
    - name: CASC_JENKINS_CONFIG
      value: "https://url.to/jcasc.yaml"
```

But that doesn't get applied. I suppose it might be conflicting with the default config or something. There is the configAutoReload functionality, but it doesn't seem to have anything to do with loading the configuration from an external source.

**Version of Helm and Kubernetes**:
2.0.1 (not really relevant though)

**Which chart**:
stable/jenkins

**What happened**:
External config wasn't applied.

**What you expected to happen**:
External config would be applied.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else we need to know**:
Not really.
