### ISSUE TITLE
[incubator/druid] The private config is overwrite by default env values

### ISSUE THREAD

**Issue by camelus0211** [helm/charts#22778]
**Describe the bug**
The private config is overwrite by default env values.
[https://github.com/helm/charts/blob/master/incubator/druid/values.yaml](url)
```
configVars:
  DRUID_XMX: 4g
  DRUID_XMS: 2g

broker:
  config:
    JAVA_OPTS: "-Xms2G -Xmx2G -XX:MaxDirectMemorySize=8g"
```
![image](https://user-images.githubusercontent.com/44798441/84566043-853d9680-ada0-11ea-8fae-da374cafbe89.png)

[https://github.com/apache/druid/blob/master/distribution/docker/druid.sh](url)
```
if [ -n "$DRUID_XMX" ]; then setJavaKey ${SERVICE} -Xmx -Xmx${DRUID_XMX}; fi
if [ -n "$DRUID_XMS" ]; then setJavaKey ${SERVICE} -Xms -Xms${DRUID_XMS}; fi
if [ -n "$DRUID_MAXNEWSIZE" ]; then setJavaKey ${SERVICE} -XX:MaxNewSize -XX:MaxNewSize=${DRUID_MAXNEWSIZE}; fi
if [ -n "$DRUID_NEWSIZE" ]; then setJavaKey ${SERVICE} -XX:NewSize -XX:MaxNewSize=${DRUID_NEWSIZE}; fi
if [ -n "$DRUID_MAXDIRECTMEMORYSIZE" ]; then setJavaKey ${SERVICE} -XX:MaxDirectMemorySize -XX:MaxDirectMemorySize=${DRUID_MAXDIRECTMEMORYSIZE}; fi

JAVA_OPTS="$JAVA_OPTS $(cat $SERVICE_CONF_DIR/jvm.config | xargs)"
```

I will PR soon to fix this issue.
