### ISSUE TITLE
stable/datadog Update commands to use Helm 3

### ISSUE THREAD

**Issue by alexandrafren** [helm/charts#22803]
The commands to upgrade helm after making changes to the datadog-values.yaml do not work correctly when using Helm 3 due to --recreate-pods being deprecated. There are 7 references to --recreate-pods in regards to updating the helm chart: https://github.com/helm/charts/tree/master/stable/datadog

For example:
`helm upgrade -f datadog-values.yaml <RELEASE_NAME> stable/datadog --recreate-pods`

returns

`Flag --recreate-pods has been deprecated, functionality will no longer be updated. Consult the documentation for other methods to recreate pods`

The Helm documentation seems to suggest updating the annotation for the pods to reference the sha256sum function: https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

```
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
[...]
```

Since Helm 2 will be fully deprecated in November 2020, an update here seems relevant.
