### ISSUE TITLE
[stable/jenkins] Allow editing serverUrl in the Kubernetes plugin configuration 

### ISSUE THREAD

**Issue by tiagomistral** [helm/charts#22813]
Currently, it is not possible to pass the serverUrl parameter during the configuration / installation of the helm chart.

On file _helpers.tpl:123
`serverUrl: "https://kubernetes.default"`

The expected behavior is that there is a parameter that allows editing this value during installation, such as the parameter jenkinsUrl or jenkinsTunnel.

**Comment by drewripa** [comment]
You need to disable default config usage and define this URL in JCasC. That's how I managed t to work:
```
master:
      componentName: jenkins-demo-1-master
      tag: "2.240"
      imagePullPolicy: IfNotPresent
      admin:
        existingSecret: test-secret
      jenkinsUriPrefix: /jenkins/demo1
      slaveJenkinsUrl: https://myurl/jenkins/demo1    
      slaveListenerServiceType: "LoadBalancer" 
      JCasC:
        enabled: true         
        defaultConfig: false
        configScripts:
          jenkins-configuration: |-
            jenkins:
              systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
              numExecutors: 5
              securityRealm:
                local:
                  allowsSignup: false
                  users:
                  - id: ${ADMIN_USER}
                    password: ${ADMIN_PASSWORD}
              authorizationStrategy:
                loggedInUsersCanDoAnything:
                  allowAnonymousRead: false
            unclassified:
              location:
                url: https://myurl/jenkins/demo1         
      sidecars:
        configAutoReload:
          enabled: true 
      ingress:
          enabled: true
          tls:
          - secretName: jenkins-demo-1-cert
          path: /jenkins/demo1
```

**Comment by tiagomistral** [comment]
Thanks for your answer @drewripa.

An workaround is allways welcome but I still think this parameter should be added to the configuration of chart.

My workaround does not disable the default configuration, it basically create a working cloud configuration by side to the not configurable one.

`master:
  jenkinsUrl: https://myurl/jenkins/demo1    #This parameter isn't referenced on chart
  serviceType: NodePort
  nodePort: 30000
# slaveJenkinsUrl: https://myurl/jenkins/demo1  # issue https://github.com/helm/charts/issues/22708
  slaveJenkinsTunnel: https://mytunnel/jenkins/demo1  
  JCasC:
    enabled: true
    configScripts:
      clouds: |
        jenkins:
          clouds:
          - kubernetes:
              serverUrl: https://mycluster
              jenkinsUrl: https://myurl/jenkins/demo1  
              jenkinsTunnel: https://mytunnel/jenkins/demo1  
              maxRequestsPerHost: 32
              name: "working-kubernetes"
              podLabels:
              - key: "jenkins/jenkins-jenkins-slave"
                value: "true"
              templates:
              - containers:
                - args: "^$${computer.jnlpmac} ^$${computer.name}"
                  envVars:
                  - containerEnvVar:
                      key: "JENKINS_URL"
                      value: https://myurl/jenkins/demo1  
                  image: "jenkins/jnlp-slave:3.27-1"
                  name: "jnlp"
                  resourceLimitCpu: "512m"
                  resourceLimitMemory: "512Mi"
                  resourceRequestCpu: "512m"
                  resourceRequestMemory: "512Mi"
                  workingDir: "/home/jenkins"
                label: "jenkins-jenkins-slave "
                name: "default"
                nodeUsageMode: NORMAL
                podRetention: "never"
                serviceAccount: "default"
                yamlMergeStrategy: "override"`

**Comment by torstenwalter** [comment]
The value is actually configured:

```
unclassified:
  location:
    adminAddress: {{ default "" .Values.master.jenkinsAdminEmail }}
    url: {{ template "jenkins.url" . }}
{{- end -}}
```
https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L159-L163


And here is the template for it:
```
{{/*
Returns the Jenkins URL
*/}}
{{- define "jenkins.url" -}}
{{- if .Values.master.jenkinsUrl }}
  {{- .Values.master.jenkinsUrl }}
{{- else }}
  {{- if .Values.master.ingress.hostName }}
    {{- if .Values.master.ingress.tls }}
      {{- default "https" .Values.master.jenkinsUrlProtocol }}://{{ .Values.master.ingress.hostName }}{{ default "" .Values.master.jenkinsUriPrefix }}
    {{- else }}
      {{- default "http" .Values.master.jenkinsUrlProtocol }}://{{ .Values.master.ingress.hostName }}{{ default "" .Values.master.jenkinsUriPrefix }}
    {{- end }}
  {{- else }}
      {{- default "http" .Values.master.jenkinsUrlProtocol }}://{{ template "jenkins.fullname" . }}:{{.Values.master.servicePort}}{{ default "" .Values.master.jenkinsUriPrefix }}
  {{- end}}
{{- end}}
{{- end -}}
```
https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L159-L163
