### ISSUE TITLE
[stable/airflow] Kubernetes executor problems with Redis/affinity

### ISSUE THREAD

**Issue by KIRY4** [helm/charts#22843]
**Describe the bug**

**Version of Helm and Kubernetes**:
AKS 1.16.7

**Which chart**:
stable/airflow

**What happened**:
When I disable Redis using:
redis:
  enabled: false

I got following error:
Error: Deployment.apps "airflow-web" is invalid: spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

So I can't disable Redis. Looks like it disable block for Redis chart but not disable external Redis.

**What you expected to happen**:
I want to use Kubernetes executor. Disable Redis and use nodeaffinity.

**How to reproduce it** (as minimally and precisely as possible):
set following in values yaml and try to deploy chart
redis:
  enabled: false

**Anything else we need to know**:

**Comment by thesuperzapper** [comment]
Why are you disabling Redis, it is required for `CeleryExecutor`, so if you don't use the embedded one, you must use the external one.

If you are using `KubernetesExecutor` the Redis configs will be disabled.

**Comment by KIRY4** [comment]
@thesuperzapper I'm using KubernetesExecutor and when I disable Redis (according tips in values.yaml) helm crashing during deploy.

**I got following error:**
Error: Deployment.apps "airflow-web" is invalid: spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(.a-z0-9?)*')

**Comment by thesuperzapper** [comment]
@KIRY4 make sure you set `airflow.executor` to `KubernetesExecutor` and don't set it under `airflow.config`

**Comment by KIRY4** [comment]
@thesuperzapper Here my values.yaml I'm stable helm chart. If I disable Redis deployment crushes.
```
airflow:
  ## configs for the docker image of the web/scheduler/worker
  ##
  image:
    repository: apache/airflow
    tag: 1.10.10-python3.6
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""
  executor: KubernetesExecutor

  config:
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.10-python3.6"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "IfNotPresent"
      AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "10"
      # AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflowdags-pvc"
      AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflowlogs-pvc"
      AIRFLOW__KUBERNETES__GIT_REPO: "git@git.my.repo.com"
      AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
      AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
      AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
      AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-gitsync"
      AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
      AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
      AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "airflow"

  extraEnv: # <--------- For some reason these two variables not worked for me from main config (I believe that it should work from main config part above. Check content of ConfigMap below)
    - name: AIRFLOW__KUBERNETES__TOLERATIONS
      valueFrom:
        configMapKeyRef:
          name: airflow-configmap
          key: k8spodstolerations
    - name: AIRFLOW__KUBERNETES__AFFINITY
      valueFrom:
        configMapKeyRef:
          name: airflow-configmap
          key: k8spodsaffinity

scheduler:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - tools

  tolerations:
  - key: "type"
    operator: "Equal"
    value: "tools"
    effect: "NoSchedule"

web:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - tools

  tolerations:
  - key: "type"
    operator: "Equal"
    value: "tools"
    effect: "NoSchedule"

logs:
  path: /opt/airflow/logs
  persistence:
    enabled: true
    existingClaim: airflowlogs-pvc
    accessMode: ReadWriteMany
    size: 10Gi

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: false
    existingClaim: airflowdags-pvc
    accessMode: ReadWriteMany
    size: 10Gi

  git:
    url: "git@git.myrepo.git"
    ref: master
    secret: "airflow-gitsync"
    sshKeyscan: true
    privateKeyName: id_rsa
    repoHost: "git@git.my.repo.com"
    repoPort: 22
    gitSync:
      enabled: true
      resources: {}
      image:
        repository: alpine/git
        tag: latest
        pullPolicy: Always
      refreshTime: 60
  initContainer:
    enabled: true
    resources: {}
    image:
      repository: alpine/git
      tag: latest
      pullPolicy: Always
    mountPath: "/opt/airflow/dags"
    syncSubPath: ""

ingress:
  enabled: true
  web:
    annotations:
      kubernetes.io/ingress.class: nginx
    path: ""
    host: myhost.com
    tls:
      enabled: false

rbac:
  create: true

serviceAccount:
  create: true
  name: airflow

postgresql:
  enabled: true
  postgresqlDatabase: dbname
  postgresqlUsername: dbuser
  postgresqlPassword: dbuserpwd
  persistence:
    enabled: true
    storageClass: "default"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

redis:
  enabled: true # < ---------- Should be false but chart crashing during deployment. So I was forced to stay with true.

workers:
  enabled: false

flower:
  enabled: false
```
