### ISSUE TITLE
[stable/nginx-ingress] replace default backend with an ssl backend service

### ISSUE THREAD

**Issue by soumeng09** [helm/charts#22872]
**Describe the bug**
I am running stable/nginx-ingress chart version 1.36.2
We have a specific scenario where we want any incoming request whose hostname does not match any existing ingress (which goes to default backend) - to go to a custom ssl backend service and return the certificate from that backend.

The controller is deployed with default backend enabled and setup to return ingress fake cert with default backend.

I understand I can override the default backend to point to a custom backend service, but how do I tell ingress controller to use ssl-passthrough with that custom catch-all backend?

As an alternative, I tried creating a catch-all ingress rule with ssl-passthrough enabled - 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: double-hop-proxy-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: main-nonprod-proxy
          servicePort: 443
        path: /
```

**Version of Helm and Kubernetes**:
Helm 2.14.3
Kubernetes 1.14.8

**Which chart**: stable/nginx-ingress (v1.36.2)

**What happened**:
The catch-all ingress rule named "double-hop-proxy-ingress" returns the content from backend service "main-nonprod-proxy" correctly.
But, the cert from main-nonprod-proxy is not returned, instead controller returns fake ingress cert.

**What you expected to happen**:
The catch-all ingress rule named "double-hop-proxy-ingress" should return the content AND THE CERTIFICATE from backend service "main-nonprod-proxy"

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy stable/nginx-ingress helm chart with default backend
2. Run a kubernetes workload with its own certificate (for our case, we created the service "main-nonprod-proxy"pointing to the ingress controller in another cluster - which in turn returns its own cert )
3. Create the catch-all ingress rule as mentioned in description.
4. Hit an URL that should go to default backend (any hostname that is not configured via an ingress rule)

**Anything else we need to know**:
