### ISSUE TITLE
[stable/nginx-ingress] Missing ingressClass in case of internal load balancer.

### ISSUE THREAD

**Issue by PrzemyslawSwiderski** [helm/charts#22878]
**Describe the bug**

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

I think there is some description missing in https://github.com/helm/charts/tree/master/stable/nginx-ingress#additional-internal-load-balancer section.
How should be annotated Ingress resources in case of internal nginx-controller?
Will it be: `kubernetes.io/ingress.class: nginx-internal` ?

**Comment by venkatalolla** [comment]
It is totally up to you on what you want the ingress class name should be, there is no specific pattern in how the ingress class. But no two ingress controllers should have the same class name that will mess up the ingresses allocation.

**Comment by PrzemyslawSwiderski** [comment]
What do You mean that is up to me? How, can I set internal ingress controller's class name? I can not find information about this in documentation...

**Comment by venkatalolla** [comment]
I mean an ingress class name can be set to a value that is unique for every ingress controller, in this case you have to change the `controller.ingressClass` to a different value every time you deploy an ingress controller. 

I see your point that the explanation about changing the class name is missing in the documentation of the Helm chart for the [additional-internal-load-balancer](https://github.com/helm/charts/tree/master/stable/nginx-ingress#additional-internal-load-balancer). I can create a PR and add the content on how to use unique values for the controller.ingressClass key when using multiple ingresses.

**Comment by PrzemyslawSwiderski** [comment]
Could You clarify this by some example?

Lets assume I installed Nginx Ingress Controller with the following values:
`controller.service.internal.enabled=true` and some cloud specific `controller.service.internal.annotations`.
After reading docs, I expect that two load balancers will be created.

For example, I have two Ingress resources, for two separate services:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservicea
  annotations:
    kubernetes.io/ingress.class: ?????
spec:
  rules:
  - host: myservicea.foo.org
    http:
      paths:
      - path: /
        backend:
          serviceName: myservicea
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myserviceb
  annotations:
    kubernetes.io/ingress.class: ?????
spec:
  rules:
  - host: myserviceb.foo.org
    http:
      paths:
      - path: /
        backend:
          serviceName: myserviceb
          servicePort: 80
```
First one should be external and the second one should be internal. 
What should be done to provide that they will be connected by Nginx Ingress Controller to a two different load balancers?

**Comment by venkatalolla** [comment]
As you pointed out in the above example, you have created two Nginx ingress controllers one is external and the other is internal. While creating these ingress controller, you need pass  a value for the `controller.ingressClass` key, by default it is set to `nginx` value. But if you decide you want to name those specific to your use case, you can add something similar to the following,

* For external ingress controller `controller.ingressClass=external-nginx`
* For Internal ingress controller `controller.ingressClass=internal-nginx` (You also need to add these values for internal ingress controller `controller.service.internal.enabled=true` and some cloud specific `controller.service.internal.annotations`)

Now create the external and internal ingress controllers with `helm upgrade --install  <external/internal>-ingress-controller stable/nginx-ingress <values>...` command

Lets talk about the ingress resources itself, as we created the ingress controllers with different class names, annotate the ingress resource, external ingress to `kubernetes.io/ingress.class: external-nginx` and internal ingress to `kubernetes.io/ingress.class: internal-nginx`

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservicea
  annotations:
    kubernetes.io/ingress.class: external-nginx
spec:
  rules:
  - host: myservicea.foo.org
    http:
      paths:
      - path: /
        backend:
          serviceName: myservicea
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myserviceb
  annotations:
    kubernetes.io/ingress.class: internal-nginx
spec:
  rules:
  - host: myserviceb.foo.org
    http:
      paths:
      - path: /
        backend:
          serviceName: myserviceb
          servicePort: 80
```

In the above code snippet, `ingress-myservicea` connects to the external Nginx ingress controller and the `ingress-myserviceb` connects to the internal Nginx ingress controller.

Let me know if you have any questions, Thanks!!
