### ISSUE TITLE
[stable/prometheus-operator] node_filesystem_*_bytes on /var/lib/docker partition with / device

### ISSUE THREAD

**Issue by wu105** [helm/charts#22905]
**Describe the bug**
The node_filesystem_..._bytes (... is size, free, available) metrics reported by node-exporter are on the node partition /var/lib/docker and is always reported with mountpoint as / and the device of the / partition.  The mountpoint is debatable but the device would be wrong if /var/lib/docker has its own partition.  See https://github.com/prometheus/node_exporter/issues/1754 for more details.

**Version of Helm and Kubernetes**:
Irrelevant.

**Which chart**:
stable/prometheus-operator-5.5.1

**What happened**:
See description above.

**What you expected to happen**:
We would like to see the device reported correctly out of box.
Node exporter has its share of the problem and may help to improve the overall situation.
It may help with documentation and support for configuring node exporter on host partitions to be monitored and explain the metrics collected.

**How to reproduce it** (as minimally and precisely as possible):
Deploy prometheus on a cluster with some nodes have /var/lib/docker on a non-root partition and check the node_filesystem_..._bytes metrics' device label.

**Anything else we need to know**:

**Comment by tuxknight** [comment]
default value in this chart didn't mount rootfs to node-exporter, you could add this to values.yaml

```
extraArgs:
  - "--path.rootfs=/host/root"

extraHostVolumeMounts:
  - name: root
    hostPath: /
    mountPath: /host/root
    readOnly: true
    mountPropagation: HostToContainer
```
