### ISSUE TITLE
[stable/grafana] Unable to set Grafana Env Var

### ISSUE THREAD

**Issue by andrew-pickin-epi** [helm/charts#22903]
Attempting to create an entry fro a Grafana environment variable causes an error:

```
    grafana:
      enabled: true
      env:
        - name: GF_FOO
          value: bar
```
Results in:

`ts=2020-06-22T17:28:02.984996473Z caller=release.go:292 component=release release=prometheus-operator targetNamespace=monitoring resource=monitoring:helmrelease/prometheus-operator helmVersion=v3 error="upgrade failed: template: prometheus-operator/charts/grafana/templates/secret.yaml:1:58: executing \"prometheus-operator/charts/grafana/templates/secret.yaml\" at <.Values.env.GF_SECURITY_ADMIN_PASSWORD__FILE>: can't evaluate field GF_SECURITY_ADMIN_PASSWORD__FILE in type interface {}" action=upgrade`

The same is true fro setting by SecretKeyRef, including setting the GF_SECURITY_ADMIN_PASSWORD__FILE  variable itself.

**Comment by tahsinrahman** [comment]
i'm also facing the same issue

**Comment by aramhakobyan** [comment]
+1

**Comment by tahsinrahman** [comment]
i found the solution, actually `env` expects an object, not an array, so you need to do `--set grafana.env.key1=value1 --set grafana.env.key2=value2` or, 

```yaml
grafana:
  enabled: true
  env:
    key1: value1
    key2: value2
```

**Comment by gldraphael** [comment]
FWIW this also happens in the `stable/grafana` chart. Here's my values:

```yaml
grafana.ini:
  database:
    type: mysql
    name: grafana
    ssl_mode: skip-verify
    host: mysql-host-goes-here
    user: mysql-user-goes-here
    password: ${GF_DATABASE_PASSWORD} # This *shouldn't* be required, but adding it doesn't help either
    # password: the-secret-password   # This works, but we don't want to hard code secrets!
    ca_cert_path: "/etc/ssl/certs/ca-certificates.crt"
env:
  - name: GF_DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: grafana-db
        key: secret
```

Grafana should ideally read the `GF_DATABASE_PASSWORD` environment variable if it exists. The OP is trying to do the same by setting `GF_FOO`. In my case, we have a setup that automatically pulls secret-env variables from a vault and that setup doesn't work with grafana since the chart expects me to hardcode the secret.
