### ISSUE TITLE
[stable/jenkins] Jenkins config (Jenkins URL, security realm such as roles) not saved and doesn't persist

### ISSUE THREAD

**Issue by hasakura12** [helm/charts#22917]
**Describe the bug**
Jenkins config (Manage Jenkins > Configuration System) for JENKINS URL, as well as Security realm (Manage Jenkins > Global Security Configuration) are not being saved.

**Version of Helm and Kubernetes**:
```
Jenkins 2.235.1

 $ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
Jenkins

**What happened**:
Jenkins config such as JENKINS_URL and authentication (enabling role based strategy and creating/assigning roles to Jenkins users) get saved (?) for about 30 minutes or so, but after a while those settings are gone, even if Jenkins container hasn't stopped nor restarted.

Therefore, logging in as a Jenkins user after the setting stop persisting fails.
Therefore, sending Bitbucket status notification after build fails because it needs JENKINS_URL to be set properly. 

**What you expected to happen**:
Configs should persist.

**How to reproduce it** (as minimally and precisely as possible):

I mount EFS to EKS worker nodes using userdata script at `/mnt/efs`.

Then manually create K8s PV and PVC.
```
kubectl apply -f pv.yaml
kubectl apply -f pvc.yaml
```

pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: jenkins
spec:
  capacity:
    storage: 10Gi # this doesn't matter for EFS
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxx:/jenkins # make sure this is the correct EFS file systme ID. Can specify subpath (if EFS is mounted at /mnt/efs, and you want to specify subpath /mnt/efs/jenkins, just specify /jenkins, not /mnt/efs/jenkins). Ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/volume_path/README.md
```

pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 8Gi
```

Then install Jenkins with helm
```
helm install jenkins stable/jenkins -n jenkins -f overrides.yaml
```

Where `overrides.yaml` would look like this
```
master:
  deploymentLabels:
    app: jenkins  # needed for istio
    version: 2.0.0  # needed for istio
  serviceLabels:
    app: jenkins  # needed for istio
    version: 2.0.0  # needed for istio
  podLabels:
    app: jenkins  # needed for istio
    version: 2.0.0  # needed for istio

serviceAccount:
  name: jenkins
  # for Jenkins pod to assume IAM role (IRSA)
  annotations: 
    eks.amazonaws.com/role-arn: "arn:aws:iam::xxxxxxxxx:role/EKSJenkinsRole"

persistence:
  existingClaim: jenkins-claim # efs csi driver doesn't support dynamic provisioning, so pv and pvc needs to be precreated. Ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver
  # storageClass: efs # use EFS storageclass. If the storage class is set to null or left undefined (persistence.storageClass=), the default provisioner is used (gp2 on AWS, standard on GKE, AWS & OpenStack).
  size: 8Gi
```

I sshed into EKS worker nodes and gave jenkins folder `777` permissions
```
cd /mnt/efs/jenkins
sudo chmod -R 777 *
```

After a while, jenkins `config.xml` value for jenkins URL defaults back
```
[ec2-user@ip-10-1-xxx-xxx jenkins]$ cat config.xml | grep -i  url
                  <key>JENKINS_URL</key>
      <serverUrl>https://kubernetes.default</serverUrl>
      <jenkinsUrl>http://jenkins:8080</jenkinsUrl>
```

**Anything else we need to know**:

The [Jenkins chart] (https://github.com/helm/charts/tree/master/stable/jenkins) says 
> Configuration as Code new default
Configuration is done via Jenkins Configuration as Code Plugin by default. That means that changes in values which result in a configuration change are always applied. In contrast the XML configuration was only applied during the first start and never altered.
❗❗❗ Attention: This also means if you manually altered configuration then this will most likely be reset to what was configured by default. It also applies to securityRealm and authorizationStrategy as they are also configured using configuration as code. ❗❗❗

So how do I persist changes made from Console for securityRealm, authorizationStrategy, and Jenkins URL?
Or how can I configure them using Configuration as Code?

**Comment by rbrcurtis** [comment]
I am having this same issue in EKS with a completely boilerplate setup.

**Comment by torstenwalter** [comment]
If you are using the version > 2.0.0 of this chart then those entries are managed via https://github.com/jenkinsci/configuration-as-code-plugin. So your settings will be overriden by whatever is configured via the Configuration is Code. If you want to make the change permanent then you need to do it via code.

The template for configuration as code can be found here https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L70-L251

There you can also see which values can be configured via `values.yaml`. For everything which is not part of that template you can pass in your own configuration via `master.JCasC.configScripts`

**Comment by schlueter** [comment]
I'm can configure the jenkins instance with CasC, but not if `namespaceOverride` is set to anything other than `default`. That doesn't appear to be the case with this "minimal reproduction" (maybe that's copied), but I will be trying to track down my issue.

For me the issue is reproducible with these values on docker for desktop:
```yaml
namespaceOverride: anything-but-default
master:
  serviceType: LoadBalancer
  servicePort: 80
  jenkinsUrl: "http://jenkins.local"
  additionalPlugins:
    - github-oauth
    - matrix-auth
    - matrix-project
    - authorize-project
  JCasC:
    configScripts:
      access-control: |
        security:
          queueItemAuthenticator:
            authenticators:
              - global:
                  strategy: "triggeringUsersAuthorizationStrategy"
    securityRealm: |-
      github:
        githubWebUri: "https://github.com"
        githubApiUri: "https://api.github.com"
        clientID: XXXXXXXXXXXX
        clientSecret: XXXXXXXXXXXXXXXXXXXXX
        oauthScopes: "read:org,user:email"
    authorizationStrategy: |-
      globalMatrix:
        permissions:
          - "Overall/Administer:schlueter"
          - "Overall/Read:schlueter"
```
If `namespaceOveride` is anything else the /var/jenkins_home/casc_configs directory will be empty.
