### ISSUE TITLE
stable/jenkins - K8s Plugin Configuration Empty

### ISSUE THREAD

**Issue by delphe** [helm/charts#22926]
**Describe the bug**
Kubernetes configuration settings are not getting applied. 

**Version of Helm and Kubernetes**:
Version >= 2

**Which chart**:
stable/jenkins

**What happened**:
This is causing the error "A container name must be specified for pod" when Jenkins jobs are trying to run on K8s.

**What you expected to happen**:
Kubernetes configuration settings to automatically be loaded based on the kubernetes environment Jenkins is running on.

**How to reproduce it** (as minimally and precisely as possible):
Create a PVC. Example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
```
Use Helm 3 & the command `helm upgrade --install --values values.yml jenkins stable/jenkins` with the following values.yml:
```
master:
  image: "jenkins/jenkins"
  tag: "2.199-alpine" # Using a tag like "lts" or "latest" will upgrade jenkins upon crash when the tag is updated.  It is recommended to use a specific verison instead.
  adminUser: admin
  # AdminPassword: <defaults to random>
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"

  serviceType: ClusterIP # ClusterIP is required to use the ingress controller.  Do not modify.
  installPlugins:
    - kubernetes:1.20.0
  ingress:
    enabled: true
    hostName: my-super-cool-jenkins-server.com
    annotations:
      kubernetes.io/ingress.class: "default"
    tls:
    - hosts:
      - my-super-cool-jenkins-server.com

agent:
  enabled: true
  image: jenkins/jnlp-slave
  alwaysPullImage: false # Set to "true" if using a tag like "latest" that tracks changing versions
  resources:
    requests:
      cpu: "0.5"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

persistence:
  enabled: true
  existingClaim: "jenkins-storage"

rbac:
  create: false

serviceAccount:
  create: false
```

**Anything else we need to know**:
The same values.yml works fine if I use an older helm chart such as 1.27.0. Example command used: 
`helm upgrade --install --values values.yml jenkins stable/jenkins --version "1.27.0"`
