### ISSUE TITLE
[stable/airflow] Kubernetes executor opt/airflow/logs: read-only file system

### ISSUE THREAD

**Issue by KIRY4** [helm/charts#22938]
**Describe the bug**
I want to use Kubernetes executor with git-clone+git-sync and store logs on Azure file share mounted as PVC. git-clone+git-sync are works perfect at least for web and scheduler pods. Few days ago I started with Azure file share mounted as PVC for dags and logs and everything worked perfect. But after that we decide to switch to git-clone+git-sync for DAGs. Just for test I'm scheduled DAG from examples (see example of code in the end).

**I got following error when describe pods which spawned by dags:**

**kubectl describe pod examplebashoperatorgitsyncalsorunthis-2d3c82be383b4d5584632ae8eecde59d -n airflow**

Error: failed to start container "base": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/33266625-a953-4035-a6c8-9a377124f7e4/volumes/kubernetes.io~empty-dir/airflow-logs\\\" to rootfs \\\"/var/lib/docker/overlay2/ec813df5c12fd902033a85229cfcfa059bab227bd2ef502ab1fce676e666269f/merged\\\" at \\\"/var/lib/docker/overlay2/ec813df5c12fd902033a85229cfcfa059bab227bd2ef502ab1fce676e666269f/merged/opt/airflow/logs\\\" caused \\\"mkdir /var/lib/docker/overlay2/ec813df5c12fd902033a85229cfcfa059bab227bd2ef502ab1fce676e666269f/merged/opt/airflow/logs: read-only file system\\\"\"": unknown

**Version of Helm and Kubernetes**:
Helm 3
AKS 1.16.7

**Which chart**:
stable/airflow

**What happened**:
Pods which are spawned by DAG (or KubernetesExecutor) are hangs in ContainerCannotRun status. Logs are empty. If I describe pod I got error mentioned above.

**What you expected to happen**:
I want to schedule DAG's using KubernetesExecutor, sync and clone dags using gitsync+gitclone and store all logs on Azure file share. Or at least resolve this error.

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart with my values.yaml and schedule DAG from examples.

**Anything else we need to know**:
It doesn't matter disable or enable persistence for logs with existingClaim defined. Also there is no difference commented or uncommented this line in config AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflowdags-pvc". In any case I got mentioned error. If I disable git-sync and git-clone and switch back to existingClaim to logs and dags (with azure file share under the hood, everything is working perfectly).

**My values.yaml**
```yml
airflow:
  ## configs for the docker image of the web/scheduler/worker
  ##
  image:
    repository: apache/airflow
    tag: 1.10.10-python3.6
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""
  executor: KubernetesExecutor

  config:
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.10-python3.6"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "IfNotPresent"
      AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "10"
      #AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflowlogs-pvc"
      AIRFLOW__KUBERNETES__GIT_REPO: "git@git.myrepo/airflow.git"
      AIRFLOW__KUBERNETES__GIT_BRANCH: "dags"
      #AIRFLOW__KUBERNETES__GIT_SUBPATH: "/dags"
      AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow"
      AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-gitsync"
      AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
      AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
  
  extraEnv:
    - name: AIRFLOW__KUBERNETES__TOLERATIONS
      valueFrom:
        configMapKeyRef:
          name: airflow-cm
          key: k8spodstolerations
    - name: AIRFLOW__KUBERNETES__AFFINITY
      valueFrom:
        configMapKeyRef:
          name: airflow-cm
          key: k8spodsaffinity

scheduler:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - tool
  
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "tool"
    effect: "NoSchedule"

web:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - tool

  tolerations:
  - key: "type"
    operator: "Equal"
    value: "tool"
    effect: "NoSchedule"

logs:
  path: /opt/airflow/logs
  persistence:
    enabled: false
    existingClaim: airflowlogs-pvc
    accessMode: ReadWriteMany
    size: 10Gi

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: false
    existingClaim: airflowdags-pvc
    accessMode: ReadWriteMany
    size: 10Gi

  ## configs for the DAG git repository & sync container
  ##
  git:
    url: "git@git.myrepo/airflow.git"
    ref: dags
    secret: "airflow-gitsync"
    sshKeyscan: true
    privateKeyName: id_rsa
    repoHost: "myrepohost"
    repoPort: 22
    gitSync:
      enabled: true
      resources: {}
      image:
        repository: alpine/git
        tag: latest
        pullPolicy: Always
      refreshTime: 60
  initContainer:
    enabled: true
    resources: {}
    image:
      repository: alpine/git
      tag: latest
      pullPolicy: Always
    mountPath: "/opt/airflow"
    syncSubPath: ""

ingress:
  enabled: true
  web:
    annotations: 
      kubernetes.io/ingress.class: nginx
    path: ""
    host: airflow.bla.bla.bla.bla.com
    tls:
      enabled: false

rbac:
  create: true

serviceAccount:
  create: true

postgresql:
  enabled: true
  postgresqlDatabase: mydb
  postgresqlUsername: myuser
  postgresqlPassword: mypassword
  persistence:
    enabled: true
    storageClass: "default"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

redis:
  enabled: true # I know that it should be false with KubernetesExecutor but it cause helm upgrade --install crash. BTW it is another issue.

workers:
  enabled: false

flower:
  enabled: false
```
**DAG from examples:**

```
"""Example DAG demonstrating the usage of the BashOperator."""

from datetime import timedelta

from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.operators.dummy_operator import DummyOperator
from airflow.utils.dates import days_ago

args = {
    'owner': 'airflow',
    'start_date': days_ago(2),
}

dag = DAG(
    dag_id='example_bash_operator_gitsync',
    default_args=args,
    schedule_interval='0 0 * * *',
    dagrun_timeout=timedelta(minutes=60),
    tags=['example']
)

run_this_last = DummyOperator(
    task_id='run_this_last',
    dag=dag,
)

# [START howto_operator_bash]
run_this = BashOperator(
    task_id='run_after_loop',
    bash_command='echo 1',
    dag=dag,
)
# [END howto_operator_bash]

run_this >> run_this_last

for i in range(3):
    task = BashOperator(
        task_id='runme_' + str(i),
        bash_command='echo "{{ task_instance_key_str }}" && sleep 1',
        dag=dag,
    )
    task >> run_this

# [START howto_operator_bash_template]
also_run_this = BashOperator(
    task_id='also_run_this',
    bash_command='echo "run_id={{ run_id }} | dag_run={{ dag_run }}"',
    dag=dag,
)
# [END howto_operator_bash_template]
also_run_this >> run_this_last

if __name__ == "__main__":
    dag.cli()
```

**Comment by chris-vest** [comment]
You cannot mount on `/opt/airflow`, you need to use something else like `/opt/airflow/dags` or `/dags`/. Make sure you update:

```
            AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/dags"
            AIRFLOW__KUBERNETES__DAGS_VOLUME_MOUNT_POINT: "/dags"
            AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"```
```

And:

`dags.path: "/dags"`

You don't have to use `/dags`, that's just what I'm using. Hope that helps.

**Comment by KIRY4** [comment]
@chris-vest First of all thank you for your help Chris. Everything working as I want due to your advice. Git-clone/git-sync work without issues and clone/sync DAG's in /opt/airflow/dags folder inside Web/Scheduler pods. Also DAG's are succesfully cloned I think into /opt/airflow/dags/repo folder inside worker pod which are spawned by KuberneteExecutor. Also logs from Web/Scheduller/Worker pods are successfully written on PVC with Azure File Share under the hood. Here is part of my values.yaml:
```yml
config:
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflowlogs-pvc"
    AIRFLOW__KUBERNETES__GIT_REPO: "git@git.myrepo/airflow-dags.git"
    AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
    AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
    AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-gitsync"

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: false
    existingClaim: airflowdags-pvc
    accessMode: ReadWriteMany
    size: 10Gi

  git:
    url: "git@git.myrepo/airflow-dags.git"
    ref: master
    secret: "airflow-gitsync"
    sshKeyscan: true
    privateKeyName: id_rsa
    repoHost: "git.mgmt.ocp.bawag.com"
    repoPort: 22
    gitSync:
      enabled: true
      resources: {}
      image:
        repository: alpine/git
        tag: latest
        pullPolicy: Always
      refreshTime: 60
  initContainer:
    enabled: true
    resources: {}
    image:
      repository: alpine/git
      tag: latest
      pullPolicy: Always
    mountPath: "/opt/airflow/dags"
    syncSubPath: ""
```

@chris-vest Can I ask you few more questions? Maybe you already faced with something like that. It is possible to avoid somehow cloning of whole repo. Is it possible to have for example dags/ folder in repo and clone only content of this folder. For now I forced to create separate repo (only for storing DAG's) instead of having subfolder with dags in repo where I have everything which required to deploy airflow via helm (I mean values.yaml, k8s manifests with secrets and PVC's, etc...). And even with separate repo git-clone/git-sync cloning .git. README, etc....
