### ISSUE TITLE
[stable/airflow] Question: How to configure Option 2a -- Single PVC for DAGs & Logs ?

### ISSUE THREAD

**Issue by Minyus** [helm/charts#22930]
I'm trying to configure [Option 2a -- Single PVC for DAGs & Logs](https://github.com/helm/charts/tree/master/stable/airflow#option-2a----single-pvc-for-dags--logs) , but "Configure airflow.extraVolume and airflow.extraVolumeMount to put a volume at /opt/airflow/efs" does not sound clear to me. 

Can anyone modify the the following `values.yaml` to configure Option 2a ?

```yaml
###################################
# Airflow - Common Configs
###################################
airflow:
  extraVolumeMounts:
    - name: synchronised-efs
      mountPath: /opt/airflow/efs
  extraVolumes:
    - name: synchronised-efs
      emptyDir: {}

###################################
# Airflow - Logs Configs
###################################
logs:
  path: /opt/airflow/efs/logs 
  persistence:
    enabled: false

###################################
# Airflow - DAGs Configs
###################################
dags:
  path: /opt/airflow/efs/dags
  doNotPickle: false
  installRequirements: false
  persistence:
    enabled: false
```
