### ISSUE TITLE
[stable/prometheus-operator] servicemonitor/prometheus-operator-kubelet missing tls config on /metrics/resource/v1alpha1

### ISSUE THREAD

**Issue by teochenglim** [helm/charts#22972]
**Describe the bug**

This is maybe an upstream issue because of jsonnet.
The newly added servicemonitor object for kubelet on path /metrics/resource/v1alpha1 missing "token" and "tlsConfig"

1. Current setting when render

$ kubectl edit servicemonitor/prometheus-operator-kubelet -n monitoring

```yaml
  - path: /metrics/resource/v1alpha1
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
```

2. Correct settings

```yaml
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token  # this line is missing
    honorLabels: true  # this line is missing
    path: /metrics/resource/v1alpha1
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig: # this line is missing
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  # this line is missing
      insecureSkipVerify: true  # this line is missing
```

**Version of Helm and Kubernetes**:
latest Docker on Mac

**Which chart**:
[stable/prometheus-operator]

**What happened**:
Prometheus failed to scarp new "/metrics/resource/v1alpha1" endpoint

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

```shell
helm install prometheus-operator stable/prometheus-operator --namespace monitoring

```

**Anything else we need to know**:

I can't find the config, so i report bug than do a pull request.
