### ISSUE TITLE
[stable/weave-scope] Support for Security Context in weave containers

### ISSUE THREAD

**Issue by blame19** [helm/charts#23008]
**Is your feature request related to a problem? Please describe.**
As part of Kubernetes' best practices, I'd like to set Security Context values in all the containers deployed on my infrastructure. As of now, the charts in weave-scope lack this capability.
Namely, the missing values would be:

```
spec:  
  containers:  
  # ...  
  securityContext:  
    readOnlyRootFilesystem: true  
    runAsNonRoot: true
```

**Describe the solution you'd like**
An easy solution would be hard coding the aforementioned values in the yamls. We could have some security options to turn those features on and off from the value.yaml file via helm.

**Describe alternatives you've considered**
At the moment the only alternative to set up probes would be manually patching the deployments after helm install, which isn't the best practice devops-wise, and unfeasible for automated solutions on a wide array of clusters.
