### ISSUE TITLE
[stable/prometheus-operator] adding additionalPrometheusRulesMap results in Helm error

### ISSUE THREAD

**Issue by LukeBalizetPatriot** [helm/charts#23057]
**Describe the bug**
When added to `values.yaml`, `additionalPrometheusRulesMap` does not allow `stable/prometheues` to upgrade/install

**Version of Helm and Kubernetes**:
```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`stable/prometheus-operator`

**What happened**:
Adding to the `additionalPrometheusRulesMap` map results in the following error:
```
Error: UPGRADE FAILED: template: prometheus-operator/templates/_helpers.tpl:88:16: executing "prometheus-operator.namespace" at <.Values.namespaceOverride>: nil pointer evaluating interface {}.namespaceOverride
```

**What you expected to happen**:
For the Helm release to update/install successfully and add the additional Prometheus rules

**How to reproduce it** (as minimally and precisely as possible):
This is my current configuration in `values.yaml`
```
# values.yaml

additionalPrometheusRulesMap:
  blackbox-exporter:
    groups:
      - name: blackbox-exporter
        rules:
          - alert: Non2xxStatus
            expr: (probe_success != 0) + on(instance) (probe_http_status_code)
            for: 1m
            labels:
              severity: critical
            annotations:
              message: "{{ $labels.instance }} is returning a {{ $value }} status code"
```
No matter what I add to `additionalPrometheusRulesMap`,  I still receive the same error

**Anything else we need to know**:
The release works without `additionalPrometheusRulesMap`, but will not work with it
