### ISSUE TITLE
How to pass rules using additionalPrometheusRulesMap to prometheus-operator?

### ISSUE THREAD

**Issue by davejhahn** [helm/charts#23082]
I am trying to add additional rules, e.g. for Redis, Kafka, etc... using the value additionalPrometheusRulesMap.   I'm confused about what exactly this should be.  

I am assuming it is a ConfigMap name that contains the rules, however if this is the case, I cannot format it properly, always resulting in "range can't iterate over ...", which may just be that I'm misunderstanding how this should work.

If I use a file passed in with this to helm for values, this works:

```additionalPrometheusRulesMap:
  kafka-rules:
    groups:
      - name: kafka-rules
        rules:
          - alert: KafkaTopicsReplicas
            expr: sum(kafka_topic_partition_in_sync_replica) by (topic) < 3
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Kafka topics replicas (instance {{ $labels.instance }})"
              description: "Kafka topic in-sync partition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

But, as I mentioned, I want to use the additionalPrometheusRulesMap value and pass in with --set.  This is primarily because of how I am automating this across different environments--I don't want to have to maintain files for common variables I use within Azure DevOps but pass in with --set.

So my question, if this is a ConfigMap, how should be formatted?  If it is not a ConfigMap, how do I specify the content?

**Which chart**:
prometheus-operator

**What happened**:
Created a config map, specified the ConfigMap name, and I get "range can't iterate over monitoring-rules" when I use --set additionalPrometheusRulesMap=<configMapName>, which may be that it just isn't able to find it, not sure.  I can't find any example anywhere with how to use additionalPrometheusRulesMap.
 
This is the ConfigMap that I created:

``````
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-rules
  namespace: monitoring
data:
  additionalPrometheusRulesMap: |
    kafka-rules:
      groups:
        - name: kafka-rules
          rules:
            - alert: KafkaTopicsReplicas
              expr: sum(kafka_topic_partition_in_sync_replica) by (topic) < 3
              for: 5m
              labels:
                severity: critical
              annotations:
                summary: "Kafka topics replicas (instance {{ $labels.instance }})"
                description: "Kafka topic in-sync partition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
``````

**What you expected to happen**:
Load the rules.   I'm sure I'm missing something here.....

**Comment by erinishimoticha** [comment]
I would love to know how you got this working, or what you used instead.

**Comment by avinashpancham** [comment]
@erinishimoticha adding this to your `values.yaml` should work.
```yaml
additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: ruleset_1
        rules:
          - alert: PrometheusJobMissing
            expr: absent(up{job="prometheus"})
            for: 0m
            labels:
              severity: warning
            annotations:
              summary: Prometheus job missing (instance {{ $labels.instance }})
              description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          - alert: PrometheusTargetMissing
            expr: up == 0
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: Prometheus target missing (instance {{ $labels.instance }})
              description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - name: ruleset_2
        rules:
          - alert: PrometheusAllTargetsMissing
            expr: count by (job) (up) == 0
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: Prometheus all targets missing (instance {{ $labels.instance }})
              description: "A Prometheus job does not have living target anymore.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```
