### ISSUE TITLE
[stable/rabbitmq-ha] Deprecated health check spam

### ISSUE THREAD

**Issue by somelinuxguy** [helm/charts#23083]
**Is your feature request related to a problem? Please describe.**

As soon as the helm chart is deployed, the containers begin spamming this message:

2020-07-06 17:58:56.797 [warning] <0.13613.0> rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.

2020-07-06 17:59:01.808 [warning] <0.13626.0> rabbitmqctl node_health_check and its HTTP API counterpart are DEPRECATED. See https://www.rabbitmq.com/monitoring.html#health-checks for replacement options.

**Describe the solution you'd like**
Reading the link in the message, there appears to be other ways to perform health-checks. Can this chart be updated to perform one of them, thus eliminating this message? There appears to be no config for me to specify a health check.

**Describe alternatives you've considered**
Turning off logging. Not super helpful because it avoids the spam but then I don't know if  there is a legit issue.

**Additional context**
This is just a vanilla deploy of the helm chart on to a pretty vanilla cluster at amazon I use for a lab to experiment and research. I just noticed this and wanted to bring it to your attention.

**Comment by xlanor** [comment]
+. This is also spamming on my end every 5 seconds.

https://github.com/bitnami/bitnami-docker-rabbitmq/issues/122 may be a good reference

**Comment by sguidos** [comment]
+1 - Do not want to disable logging, but a warning every 5 seconds is excessive, thanks.

**Comment by Cna59** [comment]
You can changes the check livenessProve && readinessProbe if you want to remove this "spam" warning message.

```
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            failureThreshold: 6
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
```

**Comment by ArgTang** [comment]
We have change it to this:
```
 livenessProbe:
    exec:
      command: ["rabbitmq-diagnostics", "check_running"]
  readinessProbe:
    exec:
      command: ["rabbitmq-diagnostics", "check_local_alarms"]
```
