### ISSUE TITLE
[stable/prometheus-operator] grafana claiming alertmanager PV

### ISSUE THREAD

**Issue by armanos** [helm/charts#23096]
**Describe the bug**
Persistent storage management appears to be malfunctioning on both upgrade and clean install of prometheus-operator. Before installing the helm chart, I create the persistent volumes in kubernetes using the following manifest (with some minor redactions):
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: staging-prometheus
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: XXX.efs.XXX.amazonaws.com
    path: "/"
  storageClassName: aws-efs
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: staging-alertmanager
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: XXX.efs.XXX.amazonaws.com
    path: "/"
  storageClassName: aws-efs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: staging-grafana
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: XXX.efs.XXX.amazonaws.com
    path: "/"
  storageClassName: aws-efs
---
```

These persistent volumes are then called in values.yaml:
```
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          volumeName: staging-alertmanager
          storageClassName: aws-efs
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
```
```
grafana:
  persistence:
    enabled: true
    type: pvc
    storageClassName: aws-efs
    volumeName: staging-grafana
    accessModes: ["ReadWriteOnce"]
    size: 50Gi
```
```
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          volumeName: staging-prometheus
          storageClassName: aws-efs
          volumeMode: Filesystem
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
```

**Version of Helm and Kubernetes**:
Helm 3.2.4
EKS 1.16

**Which chart**:
prometheus-operator 8.15.11

**What happened**:
grafana claims the persistent volume that is to be associated with alertmanager or prometheus:
```
NAME                                                                   STATUS    VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS   AGE
alertmanager-test-alertmanager-db-alertmanager-test-alertmanager-0   Pending   staging-alertmanager   0                         aws-efs        8m34s
prometheus-grafana                                                     Bound     staging-alertmanager   50Gi       RWO            aws-efs        8m40s
prometheus-test-prometheus-db-prometheus-test-prometheus-0           Bound     staging-prometheus     100Gi      RWO            aws-efs        8m24s
```
The above shows that grafana has claimed the alert manager persistent volume, which prevents alertmanager from properly creating a claim and more or less breaks the entire deployment.

**What you expected to happen**:
grafana to claim the persistent storage I am directing it to use

**How to reproduce it** (as minimally and precisely as possible):
install using latest values.yaml

**Anything else we need to know**:
After uninstalling and manually deleting the PVCs (grafana manages to delete its PVC, perhaps part of the issue?) the persistent volumes are left in the following state:
```
staging-alertmanager                       50Gi       RWO            Retain           Released    monitoring/prometheus-grafana                                             aws-efs                 43m
staging-grafana                            50Gi       RWO            Retain           Available                                                                             aws-efs                 43m
staging-prometheus                         100Gi      RWO            Retain           Released    monitoring/prometheus-test-prometheus-db-prometheus-test-prometheus-0   aws-efs                 43m
```
the grafana volume is never used, the alertmanager volume is being claimed by grafana
