### ISSUE TITLE
airflow chart, getting portforward problems in the webserver

### ISSUE THREAD

**Issue by deltawi** [helm/charts#23118]
**Describe the bug**
When I deploy the airflow app in Kubernetes (minikube or Kind) I get this error all the time when I run the webserver and I do the portforward: 
`E0708 16:13:42.769394   51449 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:8080->[::1]:56960: write tcp6 [::1]:8080->[::1]:56960: write: broken pipe
E0708 16:14:43.427643   51449 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured`

**Version of Helm and Kubernetes**:
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**helm version**
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Which chart**:
https://github.com/helm/charts/tree/master/stable/airflow

**What happened**:
I executed 

`helm install "airflowscaled" stable/airflow --namespace "airflowsp" `
```
kubectl -n airflowsp get pods
NAME                                       READY   STATUS    RESTARTS   AGE
airflowscaled-flower-85c98dcb98-7bd6l      1/1     Running   0          125m
airflowscaled-postgresql-0                 1/1     Running   0          125m
airflowscaled-redis-master-0               1/1     Running   0          125m
airflowscaled-scheduler-59df48d47f-97vbx   1/1     Running   1          125m
airflowscaled-web-5dd98b779f-v99dx         1/1     Running   4          125m
airflowscaled-worker-0                     1/1     Running   0          125m
```

`kubectl -n airflowsp port-forward airflowscaled-web-5dd98b779f-v99dx 8080:8080`

I can see the dashboard, but I am unable to fetch status of tasks and it works once or twice to get details of dags and then stops working after few clicks. When I got into the terminal I saw the timeout errors as described in bug section.

**What you expected to happen**:
I was expecting the airflow web app to run normally and fetch latest status of dags.

**Comment by thesuperzapper** [comment]
@deltawi Do you have a custom `values.yaml`?

What do you mean by "I am unable to fetch status of tasks and it works once or twice to get details of dags and then stops working after few clicks."?

**Comment by deltawi** [comment]
Hi @thesuperzapper, I mean by that: when I go in the user interface, after few clicks, the dashboard stops working properly (it keeps loading in the browser without any change in the page). At a random frequency I keep getting the of port-forward as stated above. 

For you first comment, yes I do have a custom values.yaml 
I made the following changes: 
```
airflow:
   config:
       AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
       AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "60"
       AIRFLOW__CORE__LOGGING_LEVEL: "DEBUG"
       AIRFLOW__CORE__PARALLELISM: 4
       AIRFLOW__CORE__DAG_CONCURRENCY: 4
       AIRFLOW__CORE__MAX_ACTIVE_RUNS: 2
       AIRFLOW__SCHEDULER__MAX_THREADS: 4
```
```
web:
  resources:
    requests:
      cpu: "1000m"
      memory: "512Mi"

  ## the number of web Pods to run
  ##
  replicas: 2
```

```
workers:
  ## if the airflow workers StatefulSet should be deployed
  ##
  enabled: true

  ## resource requests/limits for the airflow worker Pods
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
  ## the number of workers Pods to run
  replicas: 1
  ## configs for the HorizontalPodAutoscaler of the worker Pods
  autoscaling:
    enabled: true
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
```

Everything is deployed in local using Kind, I have a Macbook pro (12 CPU, 16GB Memory)
