### ISSUE TITLE
[stable/prometheus-blackbox-exporter] Add url and module labels to servicemonitor

### ISSUE THREAD

**Issue by lyz-code** [helm/charts#23120]
I want to generate a blackbox exporter probe endpoint for the alerts. Something similar to https://blackbox.myserver.com/probe?target=prometheus.io&module=http_2xx&debug=true, so it's easy to debug why an endpoint stopped working.

I'm unable to build that url in my PrometheusRules with the existent target labels, therefore the need of the additional labels.

I've thought of adding the following snippet to the ServiceMonitor template:

```yaml
    relabelings:
    - sourceLabels:
      - __param_target
      targetLabel: url
    - sourceLabels:
      - __param_module
      targetLabel: module
```

The `target` label doesn't work for me because the blackbox target name not always match the url.

If you agree on the solution, I'll be glad to do the PR.

Cheers
