### ISSUE TITLE
stable/prometheus-node-exporter - pods memory usage value duplication

### ISSUE THREAD

**Issue by maozza** [helm/charts#23131]
**Describe the bug**

grafana dashboard, `Kubernetes / Compute Resources / Namespace (Pods)` shows wrong memory usage

`container_memory_working_set_bytes{}` metric values are doubled, the real memory usage for Pod is doubled on grafana, it shows the wrong value (duplicated) for memory usage from the value I see on `kubectl top pod`.
query: `sum(container_memory_working_set_bytes{cluster="$cluster", namespace="$namespace", container!=""}) by (pod)`

**Version of Helm and Kubernetes**:
```
helm3 version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus-node-exporter

**What happened**:

looking at the Prometheus target configuration I see two of the same endpoints for each kublet 
for example, on target "monitoring/prometheus-prometheus-oper-kubelet/0"
there are two endpoints (https://172.25.37.170:10250/metrics) for the same node, one with label `service="prometheus-prometheus-oper-kubelet"` and the second with label `service="prometheus-operator-kubelet"`

**What you expected to happen**:
for example, when querying Prometheus UI for  `container_memory_working_set_bytes{cluster="", namespace="monitoring", container!="",pod="alertmanager-prometheus-prometheus-oper-alertmanager-0"}` 
there are two matrix with exactlliy the same value:
```
container_memory_working_set_bytes{container="alertmanager",endpoint="https-metrics",id="/kubepods/burstable/podb82b08c3-9cce-4a4f-ae79-3321e72a1618/983a8e1d0df3c78ac0e5d97db1c61c94585dd10aa66d225f966d2a123ed4ad84",image="sha256:0881eb8f169f5556a292b4e2c01d683172b12830a62a9225a98a8e206bb734f0",instance="172.25.37.170:10250",job="kubelet",metrics_path="/metrics/cadvisor",name="k8s_alertmanager_alertmanager-prometheus-prometheus-oper-alertmanager-0_monitoring_b82b08c3-9cce-4a4f-ae79-3321e72a1618_0",namespace="monitoring",node="ip-172-25-37-170.ec2.internal",pod="alertmanager-prometheus-prometheus-oper-alertmanager-0",service="prometheus-operator-kubelet"}	9220096

container_memory_working_set_bytes{container="alertmanager",endpoint="https-metrics",id="/kubepods/burstable/podb82b08c3-9cce-4a4f-ae79-3321e72a1618/983a8e1d0df3c78ac0e5d97db1c61c94585dd10aa66d225f966d2a123ed4ad84",image="sha256:0881eb8f169f5556a292b4e2c01d683172b12830a62a9225a98a8e206bb734f0",instance="172.25.37.170:10250",job="kubelet",metrics_path="/metrics/cadvisor",name="k8s_alertmanager_alertmanager-prometheus-prometheus-oper-alertmanager-0_monitoring_b82b08c3-9cce-4a4f-ae79-3321e72a1618_0",namespace="monitoring",node="ip-172-25-37-170.ec2.internal",pod="alertmanager-prometheus-prometheus-oper-alertmanager-0",service="prometheus-prometheus-oper-kubelet"} | 9220096
```
I expected to see only one

**How to reproduce it** (as minimally and precisely as possible):
```
helm3 upgrade --install prometheus ./prometheus-operator --values values.yaml
```
```
helm ls
prometheus              monitoring      1               2020-07-09 08:54:32.594433115 +0300 IDT deployed        prometheus-operator-8.15.6      0.38.1 
```

```
helm get values prometheus
USER-SUPPLIED VALUES:
additionalPrometheusRules: []
alertmanager:
  alertmanagerSpec:
    additionalPeers: []
    affinity: {}
    configMaps: []
    containers: []
    externalUrl: null
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.20.0
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    nodeSelector: {}
    paused: false
    podAntiAffinity: ""
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    podMetadata: {}
    portName: web
    priorityClassName: ""
    replicas: 1
    resources: {}
    retention: 120h
    routePrefix: /
    secrets: []
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    storage: {}
    tolerations: []
    useExistingSecret: false
  apiVersion: v2
  config:
    global:
      resolve_timeout: 1m
    receivers:
    - name: "null"
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
      - match:
          alertname: Watchdog
        receiver: "null"
  enabled: true
  ingress:
    annotations: {}
    enabled: false
    hosts: []
    labels: {}
    paths: []
    tls: []
  ingressPerReplica:
    annotations: {}
    enabled: false
    hostDomain: ""
    hostPrefix: ""
    labels: {}
    paths: []
    tlsSecretName: ""
    tlsSecretPerReplica:
      enabled: false
      prefix: alertmanager
  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: 1
  secret:
    annotations: {}
  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    labels: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: 30903
    port: 9093
    targetPort: 9093
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  serviceMonitor:
    interval: 45s
    metricRelabelings: []
    relabelings: []
    selfMonitor: false
  servicePerReplica:
    annotations: {}
    enabled: false
    loadBalancerSourceRanges: []
    nodePort: 30904
    port: 9093
    targetPort: 9093
    type: ClusterIP
  templateFiles: {}
  tplConfig: false
commonLabels: {}
coreDns:
  enabled: true
  service:
    port: 9153
    targetPort: 9153
  serviceMonitor:
    interval: 45s
    metricRelabelings: []
    relabelings: []
defaultRules:
  annotations: {}
  appNamespacesTarget: .*
  create: true
  labels: {}
  rules:
    alertmanager: true
    etcd: true
    general: true
    k8s: true
    kubeApiserver: true
    kubeApiserverError: true
    kubeApiserverSlos: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubeScheduler: true
    kubernetesAbsent: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    network: true
    node: true
    prometheus: true
    prometheusOperator: true
    time: true
  runbookUrl: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#
fullnameOverride: ""
global:
  imagePullSecrets: []
  rbac:
    create: true
    pspAnnotations: {}
    pspEnabled: true
grafana:
  additionalDataSources: []
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  enabled: true
  extraConfigmapMounts: []
  ingress:
    annotations: {}
    enabled: false
    hosts: []
    labels: {}
    path: /
    tls: []
  namespaceOverride: ""
  service:
    portName: service
  serviceMonitor:
    interval: 45s
    metricRelabelings: []
    relabelings: []
    selfMonitor: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      annotations: {}
      createPrometheusReplicasDatasources: false
      defaultDatasourceEnabled: true
      enabled: true
      label: grafana_datasource
kube-state-metrics:
  namespaceOverride: ""
  podSecurityPolicy:
    enabled: true
  rbac:
    create: true
kubeApiServer:
  enabled: true
  relabelings: []
  serviceMonitor:
    interval: 45s
    jobLabel: component
    metricRelabelings: []
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
  tlsConfig:
    insecureSkipVerify: false
    serverName: kubernetes
kubeControllerManager:
  enabled: false
  endpoints: []
  service:
    port: 10252
    targetPort: 10252
  serviceMonitor:
    https: false
    insecureSkipVerify: null
    interval: 45s
    metricRelabelings: []
    relabelings: []
    serverName: null
kubeDns:
  enabled: false
  service:
    dnsmasq:
      port: 10054
      targetPort: 10054
    skydns:
      port: 10055
      targetPort: 10055
  serviceMonitor:
    dnsmasqMetricRelabelings: []
    dnsmasqRelabelings: []
    interval: ""
    metricRelabelings: []
    relabelings: []
kubeEtcd:
  enabled: false
  endpoints: []
  service:
    port: 2379
    targetPort: 2379
  serviceMonitor:
    caFile: ""
    certFile: ""
    insecureSkipVerify: false
    interval: 45s
    keyFile: ""
    metricRelabelings: []
    relabelings: []
    scheme: http
    serverName: ""
kubeProxy:
  enabled: false
  endpoints: []
  service:
    port: 10249
    targetPort: 10249
  serviceMonitor:
    https: false
    interval: 45s
    metricRelabelings: []
    relabelings: []
kubeScheduler:
  enabled: false
  endpoints: []
  service:
    port: 10251
    targetPort: 10251
  serviceMonitor:
    https: false
    insecureSkipVerify: null
    interval: ""
    metricRelabelings: []
    relabelings: []
    serverName: null
kubeStateMetrics:
  enabled: true
  serviceMonitor:
    interval: 45s
    metricRelabelings: []
    relabelings: []
kubeTargetVersionOverride: ""
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    cAdvisor: true
    cAdvisorMetricRelabelings:
    - action: drop
      regex: container_([a-z_]+);
      replacement: $1
      separator: ;
      sourceLabels:
      - __name__
      - image
    - action: drop
      regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
      replacement: $1
      separator: ;
      sourceLabels:
      - __name__
    cAdvisorRelabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    https: true
    interval: 45s
    metricRelabelings:
    - action: drop
      regex: container_([a-z_]+);
      replacement: $1
      separator: ;
      sourceLabels:
      - __name__
      - image
    - action: drop
      regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
      replacement: $1
      separator: ;
      sourceLabels:
      - __name__
    probes: true
    probesMetricRelabelings:
    - action: drop
      regex: container_([a-z_]+);
      replacement: $1
      separator: ;
      sourceLabels:
      - __name__
      - image
    - action: drop
      regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
      replacement: $1
      separator: ;
      sourceLabels:
      - __name__
    probesRelabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    resource: false
    resourcePath: /metrics/resource/v1alpha1
    resourceRelabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
nameOverride: ""
namespaceOverride: ""
nodeExporter:
  enabled: true
  jobLabel: jobLabel
  serviceMonitor:
    interval: 45s
    metricRelabelings:
    - action: drop
      regex: ^node_mountstats_nfs_(event|operations|transport)_.+
      replacement: $1
      separator: ;
      sourceLabels:
      - __name__
    relabelings: []
    scrapeTimeout: ""
prometheus:
  additionalPodMonitors: []
  additionalServiceMonitors: []
  annotations: {}
  enabled: true
  ingress:
    annotations: {}
    enabled: false
    hosts: []
    labels: {}
    paths: []
    tls: []
  ingressPerReplica:
    annotations: {}
    enabled: false
    hostDomain: ""
    hostPrefix: ""
    labels: {}
    paths: []
    tlsSecretName: ""
    tlsSecretPerReplica:
      enabled: false
      prefix: prometheus
  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: 1
  podSecurityPolicy:
    allowedCapabilities: []
  prometheusSpec:
    additionalAlertManagerConfigs: []
    additionalAlertRelabelConfigs: []
    additionalPrometheusSecretsAnnotations: {}
    additionalScrapeConfigs: []
    additionalScrapeConfigsExternal: false
    affinity: {}
    alertingEndpoints: []
    apiserverConfig: {}
    configMaps: []
    containers: []
    disableCompaction: false
    enableAdminAPI: false
    evaluationInterval: ""
    externalLabels: {}
    externalUrl: ""
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.18.1
    initContainers: []
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    nodeSelector: {}
    paused: false
    podAntiAffinity: ""
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    podMetadata: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: true
    portName: web
    priorityClassName: ""
    prometheusExternalLabelName: ""
    prometheusExternalLabelNameClear: false
    query: {}
    remoteRead: []
    remoteWrite: []
    remoteWriteDashboards: false
    replicaExternalLabelName: ""
    replicaExternalLabelNameClear: false
    replicas: 1
    resources: {}
    retention: 10d
    retentionSize: ""
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: true
    scrapeInterval: ""
    secrets: []
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: true
    storageSpec: {}
    thanos: {}
    tolerations: []
    volumeMounts: []
    volumes: []
    walCompression: false
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    clusterIP: ""
    externalIPs: []
    labels: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: 30090
    port: 9090
    sessionAffinity: ""
    targetPort: 9090
    type: LoadBalancer
  serviceAccount:
    create: true
    name: ""
  serviceMonitor:
    bearerTokenFile: null
    interval: 45s
    metricRelabelings: []
    relabelings: []
    scheme: ""
    selfMonitor: false
    tlsConfig: {}
  servicePerReplica:
    annotations: {}
    enabled: false
    loadBalancerSourceRanges: []
    nodePort: 30091
    port: 9090
    targetPort: 9090
    type: ClusterIP
prometheus-node-exporter:
  extraArgs:
  - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
  - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
  namespaceOverride: ""
  podLabels:
    jobLabel: node-exporter
prometheusOperator:
  admissionWebhooks:
    enabled: true
    failurePolicy: Fail
    patch:
      affinity: {}
      enabled: true
      image:
        pullPolicy: IfNotPresent
        repository: jettech/kube-webhook-certgen
        tag: v1.2.1
      nodeSelector: {}
      podAnnotations: {}
      priorityClassName: ""
      resources: {}
      tolerations: []
  affinity: {}
  cleanupCustomResource: false
  configReloaderCpu: 100m
  configReloaderMemory: 25Mi
  configmapReloadImage:
    repository: quay.io/coreos/configmap-reload
    tag: v0.0.1
  createCustomResource: false
  denyNamespaces: []
  enabled: true
  hostNetwork: false
  hyperkubeImage:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/hyperkube
    tag: v1.12.1
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/coreos/prometheus-operator
    tag: v0.38.1
  kubeletService:
    enabled: true
    namespace: kube-system
  manageCrds: true
  namespaces: {}
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  prometheusConfigReloaderImage:
    repository: quay.io/coreos/prometheus-config-reloader
    tag: v0.38.1
  resources: {}
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  service:
    additionalPorts: []
    annotations: {}
    clusterIP: ""
    externalIPs: []
    labels: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: 30080
    nodePortTls: 30443
    type: ClusterIP
  serviceAccount:
    create: true
    name: ""
  serviceMonitor:
    interval: ""
    metricRelabelings: []
    relabelings: []
    selfMonitor: false
  tlsProxy:
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: squareup/ghostunnel
      tag: v1.5.2
    resources: {}
  tolerations: []

```
**Anything else we need to know**:

I assume that all values got doubled, I only point to this specific metric as example
