### ISSUE TITLE
[stable/fluent-bit] Some indices seem to be created with future dates?

### ISSUE THREAD

**Issue by boxcee** [helm/charts#23178]
**Describe the bug**
It appears that some ES indices created by fluent-bit are created with a future date.
```
curl http://localhost:9200/_cat/indices/*?v&s=creation.date.string&h=h,s,i,id,p,r,dc,dd,ss

health status index                     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   logstash-2062-01-23       j_-Vtq_jTk6IRQb8MuIQ9g   5   1         12            0    495.7kb        247.8kb
yellow open   logstash-2042-01-23       yEWe8246Twm6tgUal4UK7Q   5   1          2            0     74.3kb         37.3kb
green  open   logstash-2020-07-03       n1taoZ0xQL-AAHemZJT-7w   5   1  230168473            0    275.9gb        136.8gb
green  open   logstash-2020-07-09       OuLE21_hR3qDk2e8RDlRUg   5   1   99193449            0    117.1gb         59.2gb
green  open   logstash-2020-07-01       RaILsYIcTeSWlNkVSz7egw   5   1  139963431            0    156.2gb         77.2gb
green  open   logstash-2020-07-10       SmHnWjSVS8KqaoeG09nGjQ   5   1  132806731            0    161.6gb         81.8gb
green  open   logstash-2062-01-22       fmsdbjZDTJu-yKUfM0vBrA   5   1         19            0    661.8kb        330.9kb
green  open   logstash-2020-07-07       8FL20l5xTe6CG0zKbWchoA   5   1   79029556            0     89.7gb         45.2gb
green  open   logstash-2020-07-11       a-34AIv1ToKS0c36zEZpTg   5   1   91391173            0    101.5gb         51.4gb
green  open   logstash-2020-07-13       cccrueV3RP-k3PGVvsRd6g   5   1   30849105            0     31.6gb         16.1gb
yellow open   logstash-2020-07-14       nT7-ukPNRP-wsrjiqZOXxQ   5   1    5689066            0      5.7gb          3.2gb
green  open   logstash-2020-07-12       OLbNWP8KRdSEMM9va1HFpg   5   1   47986573            0     53.9gb         27.6gb
yellow open   logstash-2062-01-24       V5g-BIzvTnyywGLWek_KiA   5   1         12            0    290.8kb          186kb
green  open   logstash-2020-07-06       jz80AXfJR4KTlXtK2QXp7Q   5   1   91071300            0     96.7gb         48.8gb
green  open   logstash-2020-07-08       YhbIs_lPTuG8XlaPjP63gg   5   1  212440058            0    192.1gb         97.9gb
green  open   logstash-2020-07-04       P4VtoflaTeeStBNfa4hl9A   5   1   47076844            0       53gb         26.3gb
green  open   logstash-2020-07-02       5G606isHQ_WKjzZt_orf6Q   5   1  332882231            0    333.4gb        165.4gb
green  open   logstash-2020-07-05       i01Fml_VRXyYWGsaMDon5Q   5   1   42308677            0     50.5gb         25.3gb
green  open   logstash-2042-01-22       VPy_cb4kRgCV-oRq08xbIA   5   1         33            0      1.2mb        662.7kb
```
See indices with year `2042` and `2062`.

**Version of Helm and Kubernetes**:
Helm v3.2.1
Kubernetes v1.16.9-gke.6

**Which chart**:
stable/fluent-bit

**What happened**:
We are using the fluent-bit chart to write to ES for logging purposes. We have a Cronjob running to clean based on index date created, but in some cases the indices have future dates.

**What you expected to happen**:
No future dates in indices.

**How to reproduce it** (as minimally and precisely as possible):
```
values.yaml

# When enabled, fluent-bit will keep track of tailing offsets across pod restarts.
trackOffsets: true

backend:
  es:
    # host needs to be in line with the helmsman yaml naming for the elastic installation
    host: "logging-elasticsearch"
    index: logstash
    logstash_prefix: logstash
    logstash_dateformat: '%Y-%m-%d'
    time_key: '@fluent_timestamp'
  retry_limit: 5
  type: es

metrics:
  enabled: true
  service:
    annotations:
      monitoring: fluent-bit
      prometheus: kube-prometheus
  serviceMonitor:
    enabled: true
    additionalLabels:
      prometheus: kube-prometheus

input:
  tail:
    parser: cri

# Sections order matters.
rawConfig: |-
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf

  [FILTER]
      Name      parser
      Match     kube.*
      Key_Name  message
      Parser    json

  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf

rbac:
  create: true
```
