### ISSUE TITLE
stable/openvpn - easyrsa: Permission denied

### ISSUE THREAD

**Issue by ben-crowhurst** [helm/charts#23187]
**Describe the bug**
Performing a `helm install` produces `./easyrsa: Permission denied` errors.

**Version of Helm and Kubernetes**:
**Helm**: version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
**MiniKube**: minikube version: v1.11.0/commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
**Ubuntu**: 20.04 LTS

**Which chart**:
stable/openvpn

**What happened**:
$ kubectl logs vpn-portal-openvpn-56746679db-p47q8
/etc/openvpn/setup/setup-certs.sh: line 10: ./easyrsa: Permission denied
/etc/openvpn/setup/setup-certs.sh: line 11: ./easyrsa: Permission denied
/etc/openvpn/setup/setup-certs.sh: line 12: ./easyrsa: Permission denied
/etc/openvpn/setup/setup-certs.sh: line 13: ./easyrsa: Permission denied
Options error: --dh fails with '/etc/openvpn/certs/pki/dh.pem': No such file or directory
Options error: --ca fails with '/etc/openvpn/certs/pki/ca.crt': No such file or directory
Options error: --cert fails with '/etc/openvpn/certs/pki/issued/server.crt': No such file or directory
Options error: --key fails with '/etc/openvpn/certs/pki/private/server.key': No such file or directory
Options error: Please correct these errors.
Use --help for more information.

**What you expected to happen**:
Default certs to be generated.

**How to reproduce it** (as minimally and precisely as possible):
`helm install vpn-portal stable/openvpn`

**Anything else we need to know**:

**Comment by ben-crowhurst** [comment]
I've noticed the docker image being used in this chart is over 3 years old, is this chart dead?
![Screenshot_2020-07-16 jfelten openvpn-docker Tags - Docker Hub](https://user-images.githubusercontent.com/3715287/87597443-28355780-c735-11ea-85fe-fc146c349e78.png)

**Comment by ben-crowhurst** [comment]
Entering an interactive terminal in the container shows the correct permissions.
``` bash
bcrowhurst@HP-Z420-Workstation:~$ docker run -it jfelten/openvpn-docker /bin/sh
/ # find / -name easyrsa -print
/usr/share/easy-rsa/easyrsa
/ # ls -lh /usr/share/easy-rsa/
total 56
-rwxr-xr-x    1 root     root       34.1K Oct 26  2015 easyrsa
-rw-r--r--    1 root     root        4.5K Oct 26  2015 openssl-1.0.cnf
-rw-r--r--    1 root     root        7.9K Oct 26  2015 vars.example
drwxr-sr-x    2 root     root        4.0K Apr 18  2017 x509-types
/ # cd /usr/share/easy-rsa/
/usr/share/easy-rsa # ./easyrsa init-pki

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /usr/share/easy-rsa/pki

/usr/share/easy-rsa # 
```

**Comment by ben-crowhurst** [comment]
setup-certs.sh
``` bash
1:    #!/bin/bash
2:    EASY_RSA_LOC="/etc/openvpn/certs"
3:    cd $EASY_RSA_LOC
4:    SERVER_CERT="${EASY_RSA_LOC}/pki/issued/server.crt"
5:    if [ -e "$SERVER_CERT" ]
6:    then
7:      echo "found existing certs - reusing"
8:    else
9:      cp -R /usr/share/easy-rsa/* $EASY_RSA_LOC
10:    ./easyrsa init-pki
11:    echo "ca\n" | ./easyrsa build-ca nopass
12:    ./easyrsa build-server-full server nopass
13:    ./easyrsa gen-dh
14:    fi
```

**Comment by ben-crowhurst** [comment]
Ok so this appears to be a mix of user error and poor documentation regarding stable/openvpn setup.
```

persistence:
  enabled: false
  # subPath: openvpn
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## openvpn data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 2M
```
