### ISSUE TITLE
[stable/prometheus-operator] Default Backend config in ingress

### ISSUE THREAD

**Issue by karthikm83** [helm/charts#23202]
It would be nice to be able to configure default backend for all ingress objects in stable/prometheus-operator chart. 

For example, below ingress config is not possible with current ingress templates.

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  backend:
    serviceName: my-products
    servicePort: 60001
```
