### ISSUE TITLE
[stable/prometheus-operator] AlertManager Secret Already Exists During Install

### ISSUE THREAD

**Issue by antoinne85** [helm/charts#23238]
**Describe the bug**
A fresh install executed with `helm upgrade monitoring --wait --install --atomic --namespace monitoring`  
Fails with the error `Error: release monitoring failed: secrets "alertmanager-monitoring-prometheus-oper-alertmanager" already exists`

**Version of Helm and Kubernetes**:
Helm 2.14.1  
Kubernetes 1.15.12

**Which chart**:
`stable/prometheus-operator`

**What happened**:
The chart failed to install.

**What you expected to happen**:
The chart installed successfully.

**How to reproduce it** (as minimally and precisely as possible):
Setup a chart using the information provided here (`requirements.yaml`, `values.yaml`) and execute the provided `helm install` command.

**Anything else we need to know**:
prometheus-operator is being installed as a dependency of an internal chart. `requirements.yaml` looks like...
```yaml
dependencies:
  - name: prometheus-operator
    version: 8.13.8
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: prometheus-adapter
    version: 1.3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
```

Relevant portion of `values.yaml` looks like...
```
prometheus-operator:
  logLevel: all
  prometheus:
    prometheusSpec:
      externalUrl: http://127.0.0.1:8001/api/v1/namespaces/monitoring/services/prometheus-operated:9090/proxy
      serviceMonitorNamespaceSelector:
        any: true
      serviceMonitorSelector:
        monitor: true
  rbac:
      create: false
      pspEnabled: false
  grafana:
    grafana.ini:
      server:
        root_url: http://127.0.0.1:8001/api/v1/namespaces/monitoring/services/monitoring-grafana:80/proxy
    rbac:
      create: false
      pspEnabled: false
  global:
    rbac:
      create: false
      pspEnabled: false
  kube-state-metrics:
    rbac:
      create: false
      pspEnabled: false
    podSecurityPolicy:
      enabled: false
  prometheus-node-exporter:
    rbac:
      create: false
      pspEnabled: false
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    tlsProxy:
      enabled: false
```
