### ISSUE TITLE
[jetstack/cert-manager] upercase HTTP_PROXY env is not working properly

### ISSUE THREAD

**Issue by edxi** [helm/charts#23254]
**Describe the bug**
Containers behind proxy. Container can work with **lowercase** http_proxy.  But in jetstack/cert-manager chart, template/deployment.yaml, the env values are all **upercase**.

**Version of Helm and Kubernetes**:
helm v3,  k8s 1.18.3, docker ce 19.03.12

**Which chart**:
jetstack/cert-manager

**What happened**:
pod cannot access internet ( cannot request acme cert)

**What you expected to happen**:
Add lowercase env like below:
```yaml
{{- if .Values.http_proxy }}
- name: http_proxy
  value: {{ .Values.http_proxy }}
{{- end }}
{{- if .Values.https_proxy }}
- name: https_proxy
  value: {{ .Values.https_proxy }}
{{- end }}
{{- if .Values.no_proxy }}
- name: no_proxy
  value: {{ .Values.no_proxy }}
{{- end }}
```

**How to reproduce it** (as minimally and precisely as possible):
I tested by run a busybox.
set env with upercase HTTP_PROXY, wget is failed. lowercase is working.

**Anything else we need to know**:
maybe this issue is based on OS. My host is centos 7.

**Comment by edxi** [comment]
it could be solved by extraEnv
```yaml
extraEnv:
- name: http_proxy
  value: "http://x.x.x.x"
- name: https_proxy
  value: "http://x.x.x.x"
- name: no_proxy
  value: "127.0.0.1"
```
