### ISSUE TITLE
[stable/spinnaker] Specific namespaces for each context

### ISSUE THREAD

**Issue by qvistgaard** [helm/charts#23300]
**Describe the bug**
When adding multiple contexts, the same namespaces are added for each context. I think we need should expand the `context` list to allow more account specific settings. (implemented  with PR #22862)

Adding more fields to the context list is a breaking change, however I think it needs to be addressed. I would love to create a PR to change this but since this is a breaking change i would love to have a talk about how we solve this.

I would most likely change
```
kubeConfig:
  contexts:
  - my-context
```
to something like this:
```
kubeConfig:
  contexts:
  - name: my-context
    namespaces:
    - ns1
```
