### ISSUE TITLE
[stable/airflow] git-clone fails with gitlab deploy ssh keys

### ISSUE THREAD

**Issue by gitaferber2** [helm/charts#23324]
Hey,

I'm trying to git-sync my remote and private gitlab repo but I get an error from the git-clone container-

```
# gitlab.XX.com:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
# gitlab.XX.com:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
# gitlab.XX.com:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
# gitlab.XX.com:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
# gitlab.XX.com:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
Cloning into '/dags'...
Warning: Permanently added the ECDSA host key for IP address 'XX' to the list of known hosts.
Load key "/root/.ssh/id_rsa": invalid format
git@gitlab.XX.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
 
I created ssh deploy keys on gitlab and generated a public and private k8s secrets from it.
This is the helm config 'm using-

```
dags:
  ## the airflow dags folder
  path: /dags
  ## install any Python `requirements.txt` at the root of `dags.path` automatically
  installRequirements: true
  ## configs for the git-clone container
  initContainer:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "64Mi"
  # configs for the DAG git repository & sync container
  git:
    # url of the git repository
    url: "git@gitlab.XX.com:ZZ/YY.git"
    # the branch which we clone
    ref: master
    secret: airflow-gitlab-secrets
    privateKeyName: id_rsa
    repoHost: "gitlab.XX.com"
    repoPort: 22
    sshKeyscan: true
    gitSync:
      enabled: true
      refreshTime: 60
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
```

Any ideas?
