### ISSUE TITLE
[postgresql] using postgre image due to no ARM support

### ISSUE THREAD

**Issue by m-jayson** [helm/charts#23365]
Describe *in detail* the feature/behavior/change you'd like to see.
I have a simillar problem stated in this request [19132](https://github.com/helm/charts/issues/19132). Except that I'm using microk8s for my raspberry pi cluster

**Is your feature request related to a problem? Please describe.**
As I understand, bitnami has no support for ARM as of the moment so i ended up using the postgre image available in docker hub.

**Additional context**
I tried to use the provided configuration 

```
image:
  repository: postgres
  tag: 11.6

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  mountPath: /data
  size: 8Gi
  #storageClass: nfs-client

service:
  type: NodePort
  port: 5432
  annotations: {}
  
postgresqlDataDir: /var/lib/postgresql/data

volumePermissions:
  image:
    repository: alpine
    tag: "3.10"

securityContext:
  fsGroup: 999
  runAsUser: 999

livenessProbe:
  initialDelaySeconds: 300

readinessProbe:
  initialDelaySeconds: 300
```

However, it seems it dosen't work on multiple devices like master and slave. Just want to ask for your advice for a better approach in doing such as i'm using an image compatible with ARM.

also this ```bitnami/pgpool`` seems dosen't support arm as well. Would like to check if there is any alternative to this.
