### ISSUE TITLE
[jenkins/stable] Need a way of using an internal LB with helm install

### ISSUE THREAD

**Issue by trey2001** [helm/charts#23387]
I have a corporate install i'm working on in an EKS cluster and I can't use something like alb-ingress because it is a private cluster also using private subnets with nat gateways. Is there a way to expose the jenkins service to an application internal load balancer in AWS?

**Comment by hectoralicea** [comment]
Add serviceAnnotations like what I have below to your myvalues.yaml parameter you pass.  Mine are specific to azure AKS.  If you google you can find the annotations you need to EKS.   There are several to get your ALB to work as you wish.
```
master:
  useSecurity: true
  serviceType: LoadBalancer
  servicePort: 80
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  serviceAnnotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-dns-label-name: jenkins
```
