### ISSUE TITLE
[incubator/druid] router ingress not deployed

### ISSUE THREAD

**Issue by leinad87** [helm/charts#23396]
**Describe the bug**
It is not possible to deploy router's ingress on Druid chart. `values.yaml` is prepared to do it but has no effect.

**Which chart**:
Incubator/druid

**What happened**:
Druid router's ingress is not deployed when it is configured with the values. Is `ingress.yaml` at `/helm/charts/tree/master/incubator/druid/templates/router` missing?

**What you expected to happen**:

**How to reproduce it**:
Deploy chart with router ingress enabled. On config file:
```yaml
router:
  enabled: true
  ingress:
    enabled: true
    path: /
    hosts:
      - druid.mydomain.com
```
