### ISSUE TITLE
[stable/jenkins] Helm Chart ignores Authorization Strategy - Keeps setting up as 'Anyone can do anything '

### ISSUE THREAD

**Issue by hectoralicea** [helm/charts#23417]

**Comment by torstenwalter** [comment]
@hectoralicea That's just what you specified:

```
  JCasC:
      enabled: true
      defaultConfig: true
      authorizationStrategy: loggedInUsersCanDoAnything
```
