### ISSUE TITLE
[stable/percona] Access denied for user 'mysql'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by emreberber** [helm/charts#23456]
👍  **Solution:** 

**1.** Pull **stable/percona** chart in your local.

```sh
$ helm pull stable/percona
```

**2.** Then extract the file and edit **deployment.yaml**
```sh
$ tar -xzf percona-1.2.1.tgz 
$ vi percona/templates/deployment.yaml
```
**3.** Change **livenessProbe** and **readinessProbe** lines like below it
```
        livenessProbe:
          exec:
            command: 
            {{- if .Values.mysqlAllowEmptyPassword }}
            - mysqladmin
            - ping
            {{- else }}
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            {{- end }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: 
            {{- if .Values.mysqlAllowEmptyPassword }}
            - mysqladmin
            - ping
            {{- else }}
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            {{- end }}
```
4. Run
```sh
$ cd percona && helm install <chart name> . -n <namespace>
```
