### ISSUE TITLE
[stable/airflow] DAG mountPath is wrong when using git-sync

### ISSUE THREAD

**Issue by Overbryd** [helm/charts#23548]
When using the following combination, and a repository that hosts dags in a sub-folder (instead of the root folder) the user ends up in a configuration dead-lock.

```yaml
dags:
  path: /opt/airflow/repo/dags
  persistence:
    enabled: false
  initContainer:
    mountPath: /opt/airflow/repo
  git:
    # ... snip
    gitSync:
      enabled: true   
```

1. The environment variable `AIRFLOW__CORE__DAGS_FOLDER` is set by `.Values.dags.path` (https://github.com/helm/charts/blob/master/stable/airflow/templates/configmap-env.yaml#L63)

2. The mountPath of the `git-sync` container is set by `.Values.dags.initContainer.mountPath` (https://github.com/helm/charts/blob/master/stable/airflow/templates/deployments-web.yaml#L132)

3. The mountPath of the `airflow-web`  / `airflow-scheduler` container is set by `.Values.dags.path`, which is wrong. (https://github.com/helm/charts/blob/master/stable/airflow/templates/deployments-web.yaml#L174)

    The `mountPath` of the `airflow-web` and `airflow-scheduler` container should be set by the same value as the `git-sync` container. `.Values.dags.initContainer.mountPath`.
