### ISSUE TITLE
[stable/kafka-manager] Run as non root

### ISSUE THREAD

**Issue by alicekop** [helm/charts#23546]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to run kafka-manager as a non-root. 
It makes the chart unusable in cases with strict security policy that forbids running containers as root.

**Describe the solution you'd like**
Add possibility in helm chart to run kafka-manager container as a different user.
Allow to pass securityContext values: 
```
securityContext:
    runAsUser: 1000
    fsGroup: 2000
    runAsGroup: 3000
```

**Additional context**
There was already an issue like that reported but was closed due to inactivity. Original issue: https://github.com/helm/charts/issues/16987
