### ISSUE TITLE
[stable/jenkins] Why does ldap configuration have to be a multiline string instead of yaml?

### ISSUE THREAD

**Issue by rbjorklin** [helm/charts#23550]
**Describe the bug**
Configuration has to be provided as a multiline string instead of yaml?

**Version of Helm and Kubernetes**:
```
❯ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
```
helm show chart stable/jenkins
apiVersion: v1
appVersion: lts
description: Open source continuous integration server. It supports multiple SCM tools
  including CVS, Subversion and Git. It can execute Apache Ant and Apache Maven-based
  projects as well as arbitrary scripts.
home: https://jenkins.io/
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
maintainers:
- email: lachlan.evenson@microsoft.com
  name: lachie83
- email: viglesias@google.com
  name: viglesiasce
- email: maor.friedman@redhat.com
  name: maorfr
- email: mail@torstenwalter.de
  name: torstenwalter
- email: garridomota@gmail.com
  name: mogaal
- email: wmcdona89@gmail.com
  name: wmcdona89
name: jenkins
sources:
- https://github.com/jenkinsci/jenkins
- https://github.com/jenkinsci/docker-jnlp-slave
- https://github.com/maorfr/kube-tasks
- https://github.com/jenkinsci/configuration-as-code-plugin
version: 2.5.0
```

**What happened**:
I had to provide the ldap configuration as a multiline string.
```
securityRealm: |-
  ldap:
    configurations:
      - server: "ldap://ldap.example.org"
        rootDN: "dc=example,dc=org"
        groupMembershipStrategy:
          fromUserRecord:
            attributeName: "memberOf"
```

**What you expected to happen**:
I expected to provide the configuration as yaml as per the [upstream example](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/ldap).

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
