### ISSUE TITLE
[stable/prometheus-operator] kube-scheduler & kube-controller-manager enabled https x509: certificate signed by unknown authority error

### ISSUE THREAD

**Issue by qiang93** [helm/charts#23581]
prometheus-operator helm chart version: 9.3.1
change default values.yaml :
```
kubeScheduler:
    enabled: true
    service:
      port: 10259
      targetPort: 10259
    serviceMonitor:
      https: true
      insecureSkipVerify: false
      serverName: 127.0.0.1

kubeControllerManager:
    enabled: true  
    service:
      port: 10257
      targetPort: 10257
    serviceMonitor:
      https: true
      insecureSkipVerify: false
      serverName: 127.0.0.1
```
![image](https://user-images.githubusercontent.com/26239197/90712782-5975ea00-e2d6-11ea-8d8c-d93cea30dc92.png)
