### ISSUE TITLE
[stable/airflow] Track changes of requirements.txt file

### ISSUE THREAD

**Issue by valouille** [helm/charts#23606]
Hello,

I'm using the current config with the chart and it's working great at pod creation, the DAGs are synced and the requirements are installed from the requirements.txt file.

```
dags:
  installRequirements: true
  initContainer:
    enabled: true
  git:
    gitSync:
      enabled: true
```

In the current setup, any change to the requirements.txt file in my DAGs GIT repo requires me to delete pods so that they are recreated and install the new dependencies.
What I would like to do now is making the file automatically re-read at change or every now and then, so that I don't need to delete pods.
Is there any way to achieve this ?

Thanks,
Valérian
