### ISSUE TITLE
[stable/grafana] Support templating in `env` values

### ISSUE THREAD

**Issue by drc-agasser** [helm/charts#23635]
It would be helpful if values for environment variables via `env` could include template syntax. For example:
```yaml
grafana:
  env:
    GF_RENDERING_SERVER_URL: "http://{{ .Release.Name}}-renderer:8081/render"
    GF_RENDERING_CALLBACK_URL: "http://{{ .Release.Name}}-grafana/"
```

**Is your feature request related to a problem? Please describe.**
Yes, when using values like above the {{ .Release.Name }} is not replaced with the release name. Because of this, I cannot dynamically configure the rendering server and callback URL. The user of my chart has to edit these values manually for my chart to work.

**Describe the solution you'd like**
If the [pod template](https://github.com/helm/charts/blob/master/stable/grafana/templates/_pod.tpl#L332) used the `tpl` function, the values would be resolved in the pod yaml.
```yaml
{{- range $key, $value := .Values.env }}
      - name: "{{ tpl $key . }}"
        value: "{{ tpl $value . }}"
{{- end }}
```
