### ISSUE TITLE
stable/prometheus-operator Grafana has no persistent storage in templates

### ISSUE THREAD

**Issue by pentago** [helm/charts#23655]
While checking the values file, I noticed that Grafana doesn't have persistent volume storage option like 
Prometheus and AlertManager do via specs section like this below:

```
  prometheusSpec:
    storageSpec:
       volumeClaimTemplate:
         spec:
           storageClassName: nfs
           accessModes: ["ReadWriteOnce"]
           resources:
             requests:
               storage: 50Gi
```

Is that by design or it's simply an oversight because the official Grafana chart provides such functionality?
