### ISSUE TITLE
[incubator/kafka]: Wrong Notes section for connecting kafka, after successful installation

### ISSUE THREAD

**Issue by PatelRudra** [helm/charts#23690]
**Describe the bug**

After successful installation of Kafka through HELM Chart. The NOTES.txt is displaying following message.

```
You can connect to Kafka by running a simple pod in the K8s cluster like this with a configuration like this:

  apiVersion: v1
  kind: Pod
  metadata:
    name: testclient
    namespace: default
  spec:
    containers:
    - name: kafka
      image: confluentinc/cp-kafka:5.0.1
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"

Once you have the testclient pod above running, you can list all kafka
topics with:

  kubectl -n default exec testclient -- ./bin/kafka-topics.sh --zookeeper <zookeeper FQDN>:2181 --list
.............
.............
```
So after creating a pod with the aforesaid pod yaml template and, when I have executed  `kubectl -n default exec testclient -- ./bin/kafka-topics.sh --zookeeper <zookeeper FQDN>:2181 --list` command to list the topics then it showed me an below error.

_OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"./bin/kafka-topics.sh\": stat ./bin/kafka-topics.sh: no such file or directory": unknown
command terminated with exit code 126_

**Which chart**:

Kafka 
Helm Chart Version: 0.21.2
App Version: 5.0.1

**What happened**:
So I have started debugging the above issue. And I have exec into the testclient pod. And I spotted that there is no kafka-topics.sh file in "/bin" directory.

After that I have referred the [https://github.com/helm/charts/tree/master/incubator/kafka#connecting-to-kafka-from-inside-kubernetes](url). 

There in I have spotted a different image for the testclient. And after creating a pod with this image. I have executed `kubectl -n default exec testclient -- ./bin/kafka-topics.sh --zookeeper <zookeeper FQDN>:2181 --list` and all started working, I was able to see topics. 

Furthermore, I was able to see the kafka-topics.sh script inside "/opt/kafka/bin"

**What you expected to happen**:

I want you to alter the NOTES.txt with appropriate image name which is defined in [https://github.com/helm/charts/tree/master/incubator/kafka#connecting-to-kafka-from-inside-kubernetes](url). 

**How to reproduce it** (as minimally and precisely as possible):

Just pull the Kafka Chart and install and then follow the steps mentioned on your screen(which are produced by NOTES.txt), make sure kafka pod is in running state.
