### ISSUE TITLE
[stable/prometheus] Unable to override subchart kube-state-metrics using values.yaml

### ISSUE THREAD

**Issue by devsharma1979** [helm/charts#23709]
**Describe the bug**
Need to override the image value for  subchart kube-state-metrics using prometheus values.yaml, unable to override image.repository and image.tag value of subchart kube-state-metrics.  Values get overridden using --set command.

**Version of Helm and Kubernetes**:
Helm version: "v3.2.0"
Kubernetes: 
   server version - Major:"1", Minor:"17+" 
   client version - Major:"1", Minor:"18"

**Which chart**:
kube-state-metrics sub chart of promethues

**What happened**:
Overridden values mentioned in the prometheus values should take effect and  image should be pulled from configured repository

**How to reproduce it** (as minimally and precisely as possible):
Add following value in promethues value.yaml  and deploy promethues, check the image used by kube-state-metrics, it still use the default values configured in kube-state-metrics values.yaml -

```
kubeStateMetrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ##
  enabled: true
  ## kube-state-metrics sub-chart configurable values
  ## Please see https://github.com/helm/charts/tree/master/stable/kube-state-metrics
  ##
  kube-state-metrics:
    image:
      repository: custom-image-repositry
      tag: v1.9.7
```

**Anything else we need to know**:

**Comment by naseemkullah** [comment]
Please try:

```yaml
kubeStateMetrics:
  enabled: true
  image:
    repository: custom-image-repositry
    tag: v1.9.7
```

**Comment by naseemkullah** [comment]
Also this chart has moved to https://github.com/prometheus-community/helm-charts/tree/main/charts

**Comment by devsharma1979** [comment]
> Please try:
> 
> ```yaml
> kubeStateMetrics:
>   enabled: true
>   image:
>     repository: custom-image-repositry
>     tag: v1.9.7
> ```

I had tried this but even this did not work.

**Comment by devsharma1979** [comment]
> Also this chart has moved to https://github.com/prometheus-community/helm-charts/tree/main/charts

Thanks for sharing this, should I change the title for better community reach?

**Comment by naseemkullah** [comment]
Ah, this is confusing since the chart name is in kebab-case and the value to enable it is in camelCase but please try:

```yaml
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  image:
    repository: custom-image-repositry
    tag: v1.9.7
```
