### ISSUE TITLE
[stable/airflow] airflow and redis disagree on the name of the existingSecretKey option

### ISSUE THREAD

**Issue by n-oden** [helm/charts#23719]
**Describe the bug**

The stable/airflow chart uses the `.Values.redis.existingSecret` and `.Values.redis.existingSecretKey` options to configure the redis chart to pull the redis password from an existing secret.

However, the redis chart itself expects the options to be `.Values.existingSecret` and *`.Values.existingSecretPasswordKey`.  If you set the two options that the airflow values.yaml file suggests, the key name in the redis chart will be configured as its default, which is `redis-password`.

**Version of Helm and Kubernetes**:

Helm: v3.3.1
Kubernetes: 1.16.13-gke.400

**Which chart**:

stable/airflow

**What happened**:

The redis-master pod failed to start, because it was looking for a secret key value that did not exist.

**What you expected to happen**:

I expected that setting `Values.redis.existingSecretKey` would work. :)

**How to reproduce it** (as minimally and precisely as possible):

Launch the stable/airflow chart with redis configured to use a secret for its password and a non-default key name in the secret, e.g.:

```
redis:
  enabled: true
  password: ""
  existingSecret: "airflow-secrets"
  existingSecretKey: "AIRFLOW_REDIS_PASSWORD"
```

**Anything else we need to know**:

You can work around this by setting _both_ `existingSecretKey` _and_ `existingSecretPasswordKey` -- the former is consumed by the airflow chart, and the latter is consumed by the redis chart, e.g.:

```
redis:
  enabled: true
  password: ""
  existingSecret: "airflow-secrets"
  existingSecretKey: "AIRFLOW_REDIS_PASSWORD"
  existingSecretPasswordKey: "AIRFLOW_REDIS_PASSWORD"
```
