### ISSUE TITLE
[stable/airflow] extraEnvs aren't passed to the pods (KubernetesExecutor)

### ISSUE THREAD

**Issue by gpodevijn** [helm/charts#23730]
I would like to define Airflow's variables from Kubernetes secrets. I created a new secret and added `AIRFLOW_VAR_TEST_SECRET_VAR` to `airflow.extraEnv`. However, this environment variable isn't passed to the pods that execute the operators (I'm using the KubernetesExecutor).

Here's the section of the `values.yaml` file:
```yaml
  extraEnv: 
    - name: AIRFLOW_VAR_TEST_SECRET_VAR
      valueFrom:
        secretKeyRef:
          name: airflow-var-encrypted-test
          key: password
```

The `AIRFLOW_VAR_TEST_SECRET_VAR` exists in the scheduler and in the webui and I can print (echo) it when I connect to the scheduler pod:

```sh
$ kubectl describe pod airflow-scheduler-7bffb59ff9-9wbsd |grep AIRFLOW_VAR_TEST_SECRET_VAR
AIRFLOW_VAR_TEST_SECRET_VAR:  <set to the key 'password' in secret 'airflow-var-encrypted-test'>     Optional: false
AIRFLOW_VAR_TEST_SECRET_VAR:  <set to the key 'password' in secret 'airflow-var-encrypted-test'>     Optional: false
```

I run a PythonOperator that tries to read the variable:

```python
dag = DAG(
    dag_id="example",
    schedule_interval="0 0 * * *",
)

def print_context(ds, **kwargs):
    logging.info("Airflow  secret variable password: {}".format(os.getenv("AIRFLOW_VAR_TEST_SECRET_VAR")))
    logging.info("Airflow  secret variable password: {}".format(Variable.get("test_secret_var")))

with dag: 
    pythonOp = PythonOperator(task_id='pythonOp', provide_context=True, python_callable=print_context)
```

It fails with the following message:
```sh
[2020-09-09 11:33:20,667] {test_dag.py:47} INFO - Airflow  secret variable password: None
(...)
KeyError: 'Variable test_secret_var does not exist'
```

The variable is indeed not present in the pod:

```sh
$ kubectl describe pod examplepythonop-c9481348e8d44801a5e91c756b246ece 
Environment Variables from:
      airflow-env  ConfigMap  Optional: false
    Environment:
      AIRFLOW__CORE__DAGS_FOLDER:       /opt/airflow/dags/repo/
      AIRFLOW__CORE__EXECUTOR:          LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:  postgresql+psycopg2://postgres:airflow@airflow-postgresql:5432/airflow
```

How can I pass extra Airflow variables to the pods that execute the operators?

Thank you.

**Comment by gpodevijn** [comment]
This wasn't a chart issue but a missing `AIRFLOW__KUBERNETES_ENVIRONMENT` variable. We can therefore close the issue.

For reference, and as described in the [documentation](https://airflow.apache.org/docs/stable/configurations-ref.html#kubernetes-environment-variables), in order for the pods to have access to the environment variables, we have to set the variables in the `kubernetes_environment_variables` section. These variables can be set as follows in the `extraEnv` section:

```yaml
  extraEnv: 
    - name: AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW_VAR_TEST_SECRET_VAR
      valueFrom:
        secretKeyRef:
          name: airflow-var-encrypted-test
          key: password          
```

The variable `AIRFLOW_VAR_TEST_SECRET_VAR` will be passed to the worker pods and can be retrieved programmatically by calling `Variable.get("test_secret_var")`
