### ISSUE TITLE
[stable/redis-ha]: error: a container name must be specified for pod redis-ha-server-0, choose one of: [redis sentinel] or one of the init containers: [config-init]

### ISSUE THREAD

**Issue by zzguang520** [helm/charts#23768]
**Describe the bug**
Used helm3 install redis-ha:
```
kubectl apply -f redis-ha-pv.yaml -n redis

helm install redis-ha stable/redis-ha --namespace=redis \
   --set persistentVolume.storageClass=redis-storage \
   --set redisPassword=zaq12wsx 
```
cat redis-ha-pv.yaml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redis-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-ha-server-0
spec:
  accessModes: 
  - ReadWriteOnce
  storageClassName: redis-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-ha-server-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: redis-storage
  hostPath:
    path: /data/redis-ha
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-ha-server-1
spec:
  accessModes: 
  - ReadWriteOnce
  storageClassName: redis-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-ha-server-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: redis-storage
  hostPath:
    path: /data/redis-ha
```
**Version of Helm and Kubernetes**:
```
[root@master redis]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
[root@master redis]# helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Which chart**:
helm repo add stable https://kubernetes-charts.storage.googleapis.com/

**What happened**:
pod logs show error info:
```
[root@master redis]# kubectl get pod -n redis
NAME                     READY   STATUS                  RESTARTS   AGE
redis-ha-server-0        0/2     Init:CrashLoopBackOff   6          9m25s
[root@master redis]# kubectl logs redis-ha-server-0 -n redis
error: a container name must be specified for pod redis-ha-server-0, choose one of: [redis sentinel] or one of the init containers: [config-init]

```

**What you expected to happen**:
normal running

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
