### ISSUE TITLE
[stable/gangway] Allow mounting env vars containing secrets

### ISSUE THREAD

**Issue by ghost** [helm/charts#23785]
**Is your feature request related to a problem? Please describe.**

Currently, it is not possible in the helm chart to configure env vars to be pulled from secrets. This is helpful when we want to mount `clientId` and `clientSecret` from secrets, instead of hardcoding it into the the values file. 

(https://github.com/helm/charts/blob/master/stable/gangway/templates/deployment.yaml#L48)
```
env
{{- range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: {{ $v }}
{{- end }}
```
A values file like the following, breaks - 
```
- name: GANGWAY_AUDIENCE
  valueFrom:
    secretKeyRef:
      name: gangway-secret
      key: client_id 
```
**Describe the solution you'd like**
Instead, we can mount the envs as so
```
env:
{{ toYaml .Values.env | indent 8}}

```
