### ISSUE TITLE
[stable/prometheus-operator] range can't iterate over DNS name

### ISSUE THREAD

**Issue by flenoir** [helm/charts#23809]
**Describe the bug**

Using terraform, i try to install Prometheus-operator on my kubernetes cluster. 

Once i launch the "Terraform apply" command, i get an error

 like below

`Error: template: prometheus-operator/charts/grafana/templates/ingress.yaml:33:19: executing "prometheus-operator/charts/grafana/templates/ingress.yaml" at <.Values.ingress.hosts>: range can't iterate over grafana.eolementhe.cloud`

**Version of Helm and Kubernetes**:

Kubernetes 1.18.8
Helm v3.2.4

**Which chart**:
 stable/prometheus-operator

**What happened**:

getting error

`Error: template: prometheus-operator/charts/grafana/templates/ingress.yaml:33:19: executing "prometheus-operator/charts/grafana/templates/ingress.yaml" at <.Values.ingress.hosts>: range can't iterate over grafana.eolementhe.cloud`

![prometheus_error](https://user-images.githubusercontent.com/3592378/94159923-6745fe80-fe84-11ea-8d29-5e645f064ea5.JPG)

**What you expected to happen**:

  Compete installation of Prometheus-operator on my kubernetes cluster

**How to reproduce it** (as minimally and precisely as possible):

I'm using a prometheus.tf file below 

```
resource "helm_release" "prometheus-operator" {
  name      = var.helm_chart_name
  chart     = "stable/prometheus-operator"
  version   = var.helm_chart_version
  namespace = var.helm_chart_namespace
  values = [
    templatefile("${path.module}/template/operator_values.tpl", {
      helm_chart_version                              = var.helm_chart_version
      helm_chart_name                                 = var.helm_chart_name
      helm_chart_namespace                            = var.helm_chart_namespace
      defaultRules_create                             = var.defaultRules_create
      defaultRules_general                            = var.defaultRules_general
      defaultRules_PrometheusOperator                 = var.defaultRules_PrometheusOperator
      defaultRules_alertmanager                       = var.defaultRules_alertmanager
      defaultRules_etcd                               = var.defaultRules_etcd
      defaultRules_k8s                                = var.defaultRules_k8s
      defaultRules_kubeApiserver                      = var.defaultRules_kubeApiserver
      defaultRules_kubeApiserverError                 = var.defaultRules_kubeApiserverError
      defaultRules_kubeApiserverSlos                  = var.defaultRules_kubeApiserverSlos
      defaultRules_kubePrometheusNodeAlerting         = var.defaultRules_kubePrometheusNodeAlerting
      defaultRules_kubePrometheusNodeRecording        = var.defaultRules_kubePrometheusNodeRecording
      defaultRules_kubeScheduler                      = var.defaultRules_kubeScheduler
      defaultRules_kubernetesAbsent                   = var.defaultRules_kubernetesAbsent
      defaultRules_kubernetesApps                     = var.defaultRules_kubernetesApps
      defaultRules_kubernetesResources                = var.defaultRules_kubernetesResources
      defaultRules_kubernetesStorage                  = var.defaultRules_kubernetesStorage
      defaultRules_kubernetesSystem                   = var.defaultRules_kubernetesSystem
      defaultRules_network                            = var.defaultRules_network
      defaultRules_node                               = var.defaultRules_node
      defaultRules_prometheus                         = var.defaultRules_prometheus
      defaultRules_time                               = var.defaultRules_time
      prometheusOperator_manageCrds                   = var.prometheusOperator_manageCrds
      prometheusOperator_image_tag                    = var.prometheusOperator_image_tag
      prometheus_prometheusSpec_image_tag             = var.prometheus_prometheusSpec_image_tag
      prometheus_prometheusSpec_replicas              = var.prometheus_prometheusSpec_replicas
      prometheus_prometheusSpec_ruleNamespaceSelector = var.prometheus_prometheusSpec_ruleNamespaceSelector
      prometheus_service_type                         = var.prometheus_service_type
      alertmanagerSpec_image_tag                      = var.alertmanagerSpec_image_tag
      alertmanager_service_type                       = var.alertmanager_service_type
      grafana_adminPassword                           = var.grafana_adminPassword
      grafana_image_tag                               = var.grafana_image_tag
      grafana_service_type                            = var.grafana_service_type
      grafana_service_port                            = var.grafana_service_port
    })
  ]
  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.metadata.name"
    value = "prometheus_volume_claim"
  }
  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.metadata.namespace"
    value = "kube-system"
  }
  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.volumeName"
    value = local.eolementhe.kubernetes.persistent_volume.prometheus_db
  }
  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName"
    value = "azurefile"
  }
  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.accessModes[0]"
    value = "ReadWriteMany"
  }
  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage"
    value = "10Gi"
  }
  set {
    name  = "grafana.persistence.enable"
    value = true
  }
  set {
    name  = "grafana.persistence.type"
    value = "pvc"
  }
  set {
    name  = "grafana.persistence.size"
    value = "10Gi"
  }
  set {
    name  = "grafana.persistence.storageClassName"
    value = "azurefile"
  }
  set {
    name  = "grafana.persistence.volumeName"
    value = local.eolementhe.kubernetes.persistent_volume.prometheus_db
  }
  set {
    name  = "grafana.persistence.accessModes[0]"
    value = "ReadWriteMany"
  }
  set {
    name  = "alertmanager.enabled"
    value = true
  }
  set {
    name  = "alertmanager.ingress.enabled"
    value = true
  }
  set {
    name  = "alertmanager.ingress.hosts"
    value = "alertmanager.eolementhe.cloud"
  }
  set {
    name  = "prometheus.enabled"
    value = true
  }
  set {
    name  = "prometheus.ingress.enabled"
    value = true
  }
  set {
    name  = "prometheus.ingress.hosts"
    value = "prometheus.eolementhe.cloud"
  }
  set {
    name  = "grafana.enabled"
    value = true
  }
  set {
    name  = "grafana.ingress.enabled"
    value = true
  }
  set {
    name  = "grafana.ingress.hosts"
    value = "grafana.eolementhe.cloud"
  }
}
```
 and variables in a variable.tf file

```
#################################
# Prometheus Operator variables #
#################################

# Helm Chart
variable "helm_chart_version" {
  description = "Helm chart version"
  default     = "9.3.0"
}
variable "helm_chart_name" {
  description = "Helm chart name"
  default     = "prometheus-operator"
}
variable "helm_chart_namespace" {
  description = "Kubernetes namespace to deploy"
  default     = "monitoring"
}
variable "skip_crds" {
  default = false
}
variable "create_namespace" {
  default = true
}
# General values
variable "defaultRules_general" {
  default = true
}
variable "defaultRules_create" {
  description = "Create default rules for monitoring the cluster"
  default     = true
}
variable "defaultRules_PrometheusOperator" {
  default = true
}
variable "defaultRules_alertmanager" {
  default = true
}
variable "defaultRules_etcd" {
  default = false
}
variable "defaultRules_k8s" {
  default = true
}
variable "defaultRules_kubeApiserver" {
  default = true
}
variable "defaultRules_kubeApiserverError" {
  default = true
}
variable "defaultRules_kubeApiserverSlos" {
  default = true
}
variable "defaultRules_kubePrometheusNodeAlerting" {
  default = true
}
variable "defaultRules_kubePrometheusNodeRecording" {
  default = true
}
variable "defaultRules_kubeScheduler" {
  default = true
}
variable "defaultRules_kubernetesAbsent" {
  default = true
}
variable "defaultRules_kubernetesApps" {
  default = true
}
variable "defaultRules_kubernetesResources" {
  default = true
}
variable "defaultRules_kubernetesStorage" {
  default = true
}
variable "defaultRules_kubernetesSystem" {
  default = true
}
variable "defaultRules_network" {
  default = true
}
variable "defaultRules_node" {
  default = true
}
variable "defaultRules_prometheus" {
  default = true
}
variable "defaultRules_time" {
  default = true
}
# Prometheus-Operator - Values
variable "prometheusOperator_manageCrds" {
  default = true
}
variable "prometheusOperator_image_tag" {
  default = "v0.38.1"
}
# Prometheus - Values
variable "prometheus_prometheusSpec_image_tag" {
  description = "Tag of Prometheus container image to be deployed."
  default     = "v2.18.1"
}
variable "prometheus_prometheusSpec_replicas" {
  description = "Number of instances to deploy for a Prometheus deployment."
  default     = "1"
}
variable "prometheus_prometheusSpec_ruleNamespaceSelector" {
  description = "Namespaces to be selected for PrometheusRules discovery."
  default     = true
}
variable "prometheus_service_type" {
  description = "Prometheus Service type"
  default     = "ClusterIP"
}
variable "alertmanagerSpec_image_tag" {
  description = "Tag of Alertmanager container image to be deployed."
  default     = "v0.20.0"
}
variable "alertmanager_service_type" {
  description = "Alertmanager Service type"
  default     = "ClusterIP"
}
variable "grafana_adminPassword" {
  description = "Admin password to log into the grafana UI  "
  default     = "passw0rd"
}
variable "grafana_image_tag" {
  description = "Image tag. (Must be >= 5.0.0)"
  default     = "7.0.3"
}
variable "grafana_service_type" {
  description = "Kubernetes service type"
  default     = "ClusterIP"
}
variable "grafana_service_port" {
  description = "Kubernetes port where service is exposed"
  default     = "3000"
}
############################
```

I also use an "operator_values.tpl" file

```
# General rules
defaultRules:
    create: ${defaultRules_create}
    rules:
        general: ${defaultRules_general}
        PrometheusOperator: ${defaultRules_PrometheusOperator}
        alertmanager: ${defaultRules_alertmanager}
        etcd: ${defaultRules_etcd}
        k8s: ${defaultRules_k8s}
        kubeApiserver: ${defaultRules_kubeApiserver}
        kubeApiserverError: ${defaultRules_kubeApiserverError}
        kubeApiserverSlos: ${defaultRules_kubeApiserverSlos}
        kubePrometheusNodeAlerting: ${defaultRules_kubePrometheusNodeAlerting}
        kubePrometheusNodeRecording: ${defaultRules_kubePrometheusNodeRecording}
        kubeScheduler: ${defaultRules_kubeScheduler}
        kubernetesAbsent: ${defaultRules_kubernetesAbsent}
        kubernetesApps: ${defaultRules_kubernetesApps}
        kubernetesResources: ${defaultRules_kubernetesResources}
        kubernetesStorage: ${defaultRules_kubernetesStorage}
        kubernetesSystem: ${defaultRules_kubernetesSystem}
        network: ${defaultRules_network}
        node: ${defaultRules_node}
        prometheus: ${defaultRules_prometheus}
        time: ${defaultRules_time}
# Prometheus-Operator
prometheusOperator:
    manageCrds: ${prometheusOperator_manageCrds}
    image:
        tag: ${prometheusOperator_image_tag}
# Prometheus
prometheus:
    prometheusSpec:
        image:
            tag: ${prometheus_prometheusSpec_image_tag}
        replicas: ${prometheus_prometheusSpec_replicas}
        rule:
            NamespaceSelector:
                any: ${prometheus_prometheusSpec_ruleNamespaceSelector}
    service:
        type: ${prometheus_service_type}
# Alertmanager
alertmanager:
    alertmanagerSpec:
        image:
            tag: ${alertmanagerSpec_image_tag}
    service:
        type: ${alertmanager_service_type}
# Grafana
grafana:
    service:
        port: ${grafana_service_port}
        type: ${grafana_service_type}
    adminPassword: ${grafana_adminPassword}
    image:
        tag: ${grafana_image_tag}


```

**Anything else we need to know**:

I thought it was related to a search for an array, but only strings can be provided.
