### ISSUE TITLE
[stable/airflow] Execute a command after updating the repository with git-sync sidecar

### ISSUE THREAD

**Issue by german1608** [helm/charts#23869]
Hi,

The operators on our airflow DAGs are configurable via a JSON file. Since it's quite big, we plan to use [Dhall](http://dhall-lang.org/) or any other config generator/validator tool, but a downside that we're having is that we need to commit both the `.json` files that our DAGs read to generate the operators, and the `.dhall` files used to generate these JSON files.

In this moment we are keeping track of the JSON files in the repository, which is redundant, and it would confuse new-members on the project in order to write config since almost everyone would expect to edit the JSON files, not the Dhall files.

This feature request is for allowing to inject a post-update hook (or to manually execute a command right after `git clean ...`) in the git-sync sidecar container.

**Is your feature request related to a problem? Please describe.**
Problem is described above

**Describe the solution you'd like**

I'm thinking of a new value, say `dags.git.gitSync.postUpdateScript` that includes an command that will be inserted in the `git-sync.sh` configmap:

```yaml
dags:
  git:
    gitSync:
      enabled: true
      postUpdateScript: ./generate-config.sh
```

...or supplying a list of scripts:
```yaml
dags:
  git:
    gitSync:
      enabled: true
      postUpdateScripts:
        - command1
        - command2
```

**Describe alternatives you've considered**

In the current state of the chart, the only solution I'm thinking of is to create a "mock" repository that will contain the dags with the JSON file, and a "real" repository that users will contribute to, which will run CI/CD to push the latest changes to the mock repository. The chart values will refer to this "mock" repository, but I don't like this approach too much.

**Additional context**
N/A
