### ISSUE TITLE
stable/airflow Not connecting external PostgreSQL database

### ISSUE THREAD

**Issue by jordi-crespo** [helm/charts#23880]
I am deploying airflow in Kubernetes with this chart: https://github.com/helm/charts/tree/master/stable/airflow and I am using:

 -AKS Kubernetes version: 1.16.13
- PostgreSQL hosted in Azure Database for PostgreSQL version: 10

If I use the PostgreSQL database sub chart it works perfectly.

I modify the values.yml to connect to the external PostgreSQL database:

```yml
externalDatabase:
  ## the type of external database: {mysql,postgres}
  ##
  type: postgres

  ## the host of the external database
  ##
  host: <SERVER>

  ## the port of the external database
  ##
  port: 5432

  ## the database/scheme to use within the the external database
  ##
  database: airflow

  ## the user of the external database
  ##
  user: <USER>

  ## the name of a pre-created secret containing the external database password
  ##
  passwordSecret: "secretname"

  ## the key within `externalDatabase.passwordSecret` containing the password string
  ##
  passwordSecretKey: "secretkey"

  ## the connection properties for external database, e.g. "?sslmode=require"
  properties: ""
```
When I deploy it the scheduler and webserver pods fail. I have checked the connection string and using it manually works fine
