### ISSUE TITLE
[stable/vsphere-cpi] not overriding nodeSelector and tolerations

### ISSUE THREAD

**Issue by wbagdon** [helm/charts#23957]
**Describe the bug**
Setting the `values.yaml` file to set the tolerations and selectors to match what an RKE cluster would expect is impossible from helm currently as it is not possible to override from the `value.yaml` file

**Version of Helm and Kubernetes**:
Helm v3.3.4
Kubernetes v1.19.3

**Which chart**:
stable/vsphere-cpi

**What happened**:
nodeSelector and tolerations were appended to existing nodeSelector and tolerations from the chart

**What you expected to happen**:
nodeSelector and tolerations should override the existing nodeSelector and tolerations from the chart as per the comments:
https://github.com/helm/charts/blob/master/stable/vsphere-cpi/values.yaml#L71:L74

**How to reproduce it** (as minimally and precisely as possible):
helm install -f Values.yaml vsphere-cpi stable/vsphere-cpi -n kube-system

`Values.yaml`
```yaml
daemonset:
  nodeSelector:
    node-role.kubernetes.io/controlplane: "true"
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/controlplane
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/etcd
    value: "true"
    effect: NoExecute
```

**Anything else we need to know**:
The template `daemonset.yaml` should be updated to include logic to actually override the defaults e.g.:
```yaml
      nodeSelector:
      {{- if .Values.daemonset.nodeSelector }}
      {{- toYaml .Values.daemonset.nodeSelector | nindent 8 }}
      {{- else }}
        node-role.kubernetes.io/master: ""
      {{- end }}
      tolerations:
      {{- if .Values.daemonset.tolerations }}
      {{- toYaml .Values.daemonset.tolerations | nindent 6 }}
      {{- else }}
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        effect: NoSchedule
        operator: Exists
      {{- end }}
```
