### ISSUE TITLE
stable/ipfs /data/ipfs/config configMap

### ISSUE THREAD

**Issue by travnewmatic** [helm/charts#23970]
maybe create a configMap for /data/ipfs/config

`k cp -n ipfs ipfs-ipfs-0:/data/ipfs/config config`

`k create configmap -n ipfs config --from-file=config`

i've made some tweaks to the statefulset:
```
        volumeMounts:
        - mountPath: /data/ipfs/config
          name: config
          subPath: config
        - mountPath: /data/ipfs
          name: ipfs-storage
```
```
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config
            path: config
          name: config
        name: config
```

is this a good idea?
