### ISSUE TITLE
charts/stable/nfs-server-provisioner/    xfs project quotas

### ISSUE THREAD

**Issue by Daxcor69** [helm/charts#24028]
I would like to implement xfs file system with project quotas. I know I have to create the storage class to do that. I have.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: do-block-storage-xfs-prjquota
provisioner: dobs.csi.digitalocean.com
parameters:
  fsType: xfs
reclaimPolicy: Delete
mountOptions:
  - prjquota
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

Now the question is how to I tell this helm chart (the nfs server) I want to use xfs project quotas on pvcs that are created on this PV?

I found one reference to a directive {enable-xfs-quota: true} for this chart, but I don't see it in your documentation.  Can you please let me know if this is available and how to do this.

thank you.
