### ISSUE TITLE
[incubator/rundeck] storage value could not be read.

### ISSUE THREAD

**Issue by b0nete** [helm/charts#24039]
Hi, i'm trying to configure a test job in rundeck using a previous load key in Key Storage under keys/test path, but when i try run my job created in a "Permission" named project i get the next message:

`Option key-test is required, but storage value from "keys/test" could not be read.`

I have only the admin:admin user configured now.

I'm using chart version rundeck-0.3.4 and postgresql database without PVC storage.

This is my ACL.

```
description: Admin project level access control. Applies to resources within a specific project.
context:
  project: 'Permission' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [create] # allow create jobs
    - equals:
        kind: node
      allow: [read,create,update,refresh] # allow refresh node sources
    - equals:
        kind: event
      allow: [read,create] # allow read/create events
  adhoc:
    - allow: [read,run,runAs,kill,killAs] # allow running/killing adhoc jobs
  job:
    - allow: [create,read,update,delete,run,runAs,kill,killAs] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read,run] # allow read/run for nodes
by:
  group: admin
  username: admin
---

description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [create] # allow create of projects
    - equals:
        kind: system
      allow: [read,enable_executions,disable_executions,admin] # allow read of system info, enable/disable all executions
    - equals:
        kind: system_acl
      allow: [read,create,update,delete,admin] # allow modifying system ACL files
    - equals:
        kind: user
      allow: [admin] # allow modify user profiles
  project:
    - match:
        name: 'Permission'
      allow: [read,import,export,configure,delete,admin] # allow full access of all projects or use 'admin'
  project_acl:
    - match:
        name: 'Permission'
      allow: [read,create,update,delete,admin] # allow modifying project-specific ACL files
  storage:
    - match:
        path: 'keys/test'
      allow: [read,create,update,delete] # allow access for /keys/* storage content

by:
  group: admin
  username: admin
```

I hope your help, thanks!

PD: Which is the way for create a user in a realm.properties file?; i can change in jaas.configuration "org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule" but when my pod die loose the config.
