### ISSUE TITLE
Incorrect urls in index.yaml

### ISSUE THREAD

**Issue by aidandj** [helm/charts#24426]
The latest versions of a bunch of packages got their url's set incorrectly in the latest index.yaml it appears. Here is a snippet from envoy.

```
  envoy:
  - apiVersion: v1
    appVersion: 1.11.2
    created: "2020-11-14T08:06:25.572456-05:00"
    deprecated: true
    description: DEPRECATED Envoy is an open source edge and service proxy, designed
      for cloud-native applications.
    digest: ead0f7f54431bc2d87a8e9db194152d2e894d812bdc74f50db4b5cb72c0e9994
    home: https://www.envoyproxy.io/
    icon: https://avatars0.githubusercontent.com/u/30125649
    keywords:
    - envoy
    - proxy
    name: envoy
    sources:
    - https://github.com/envoyproxy/envoy
    urls:
    - https://charts.helm.sh/stable/envoy-1.9.4.tgz
    version: 1.9.4
  - apiVersion: v1
    appVersion: 1.11.2
    created: "2020-11-09T22:26:48.97254153Z"
    description: Envoy is an open source edge and service proxy, designed for cloud-native
      applications.
    digest: 0bfae367b02970b9b46aa6f1b3d1bbb0167cda53979479ca28867e9bcee46292
    home: https://www.envoyproxy.io/
    icon: https://avatars0.githubusercontent.com/u/30125649
    keywords:
    - envoy
    - proxy
    maintainers:
    - email: josdotso@cisco.com
      name: josdotso
    - email: ykuoka@gmail.com
      name: mumoshu
    name: envoy
    sources:
    - https://github.com/envoyproxy/envoy
    urls:
    - https://charts.helm.sh/stable/packages/envoy-1.9.3.tgz
```

See how `1.9.3` was set to https://charts.helm.sh/stable/**packages**/envoy-1.9.3.tgz, while 1.9.4 did not?

https://charts.helm.sh/stable/packages/envoy-1.9.3.tgz is a functional url, so is https://charts.helm.sh/stable/packages/envoy-1.9.4.tgz. But index.yaml is incorrect.

**Comment by artificial-aidan** [comment]
Looks like some of them were fixed in https://github.com/helm/charts/pull/24424. But not all

**Comment by sayresVT** [comment]
This appears to be an issue with version `1.0.4` of the `aws-alb-ingress-controller` in the incubator repo as well.
```
  aws-alb-ingress-controller:
  - apiVersion: v1
    appVersion: v1.1.8
    created: "2020-11-14T07:58:40.972294-05:00"
    deprecated: true
    description: DEPRECATED A Helm chart for AWS ALB Ingress Controller
    digest: 9da0e2f9f6264a1d1e17377d209ac3049d3c28c31ceca199361fd407c7199879
    home: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
    keywords:
    - aws
    - ingress
    name: aws-alb-ingress-controller
    sources:
    - https://github.com/kubernetes-sigs/aws-alb-ingress-controller
    urls:
    - https://charts.helm.sh/incubator/aws-alb-ingress-controller-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v1
    appVersion: v1.1.8
    created: "2020-11-09T07:05:38.990163183Z"
    description: A Helm chart for AWS ALB Ingress Controller
    digest: e8ef8ac4e6fd51ed6b2aaf3d6a0cda55b1b9005cd8bc9ae4743cb87126f78027
    home: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
    keywords:
    - aws
    - ingress
    maintainers:
    - email: kraig.amador@ticketmaster.com
      name: bigkraig
    - email: yyyng@amazon.com
      name: M00nF1sh
    name: aws-alb-ingress-controller
    sources:
    - https://github.com/kubernetes-sigs/aws-alb-ingress-controller
    urls:
    - https://charts.helm.sh/incubator/packages/aws-alb-ingress-controller-1.0.3.tgz
    version: 1.0.3
```
The URL for `1.0.4` appears to be valid once `/packages/` is included: https://charts.helm.sh/incubator/packages/aws-alb-ingress-controller-1.0.4.tgz
