### ISSUE TITLE
[stable/elastalert] Add timezone configuration parameter for aggregated alert

### ISSUE THREAD

**Issue by remoteexception** [helm/charts#24435]
**Is your feature request related to a problem? Please describe.**
I want to be able to set the time zone for aggregated alerts. We run our ElastAlert-Container with a specific timezone (TZ=Europe/Berlin):
```
elastalert:
  image:
    repository: digiregistry.azurecr.io/jertel/elastalert-docker
  ...
  ...
  optEnv:
  - name: TZ
    value: Europe/Berlin
```

I also tried it this way:
```
elastalert:
  image:
    repository: digiregistry.azurecr.io/jertel/elastalert-docker
  ...
  ...
  optEnv:
  - name: SET_CONTAINER_TIMEZONE
    value: 'True'
  - name: CONTAINER_TIMEZONE
    value: Europe/Berlin
```
Both works. When I exec into the ElastAlert container and enter `printenv | grep TZ` it prints `TZ=Europe/Berlin`. Or in the 2nd case, `printenv` prints `SET_CONTAINER_TIMEZONE=True` and `CONTAINER_TIMEZONE=Europe/Berlin`, which is recognized by ElastAlert.

The rule is configured as follows:
```
  rules:
    import-warnings: |-
      name: Import Warnings
      aggregation:
        schedule: '2 7 * * *'
        ...
```

I expect the rule to trigger at 7:02 am local time (Europe/Berlin). That is, it should trigger at 5:02 UTC in DST or else at 6:02 UTC. However, the trigger appears to be ignoring the specified time zone and fires at 7:02 UTC.

**Describe the solution you'd like**
It would be great if ElastAlert interpreted the schedule time in the timezone that is set via the TZ environment variable.

**Describe alternatives you've considered**
A variable `timezone` in the rule would be fine too.
