### ISSUE TITLE
[stable/rocketchat] Multipod Rocketchat keeps reloading URL 

### ISSUE THREAD

**Issue by alb-dev** [helm/charts#24437]
**Describe the bug**
Currtently i try to deploy Rocketchat for our Company. We are swtichting from a Standaloneserver to helm based deployment. Everything works perfektly as long as i only scale the app to one pod of rocketchat. As soon as i try to add more pods of rocketchat itself the url keeps reloading. 

**Version of Helm and Kubernetes**:
Kubernetes 1.19.3 with metallb and kubernetes-ingress (nginx). 

**Which chart**:

stable/rocketchat

**What happened**:

We restored our database from our existing rocketchat installation and scaled it up to 5 pods. As soon as second pod comes online the sites keeps reloading infinetly.  In the Logs come up with invalid user for rocketchat. 

I would think it hast either something to do with ldap aus auth service or with the ingress not actually create a sticky session.

**What you expected to happen**:

Scaling up pods without enduser noticing anything. 

**How to reproduce it** (as minimally and precisely as possible):

Create a helm rocketchat deployment with ms active directory as auth service. 

**Anything else we need to know**:

my values.yaml 
###############################################################

```
image:
  repository: docker.io/rocketchat/rocket.chat
  tag: 3.9.0
  pullPolicy: IfNotPresent


host: rocketchat.intern.my-domain.de

replicaCount: 1
minAvailable: 1

smtp:
  enabled: true
  username:
  password:
  host: mailrelay.my-cluster-.lan
  port: 25


extraEnv:  

podAntiAffinity: ""

podAntiAffinityTopologyKey: kubernetes.io/hostname

affinity: {}

externalMongodbUrl:  mongodb://rocketchat:rocketchattest@rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.my-cluster-prod.local:27017/rocketchat
externalMongodbOplogUrl:  mongodb://root:rocketchattest@rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.my-cluster-prod.local:27017/local?replicaSet=rs0&authSource=admin


mongodb:
  enabled: true

  mongodbRootPassword: rocketchattest

  mongodbUsername: rocketchat
  mongodbPassword: rocketchattest
  mongodbDatabase: rocketchat

  replicaSet:
    enabled: true
    replicas:
      secondary: 1
      arbiter: 1
    pdb:
      minAvailable:
        secondary: 1
        arbiter: 1



  persistence:
    enabled: true
    storageClass: "nfs-sc"
    accessMode: ReadWriteOnce
    size: 8Gi


persistence:
  enabled: true

  storageClass: "nfs-sc"
  accessMode: ReadWriteOnce
  size: 8Gi


securityContext:
  enabled: true
  runAsUser: 1100
  fsGroup: 1100

serviceAccount:
  create: true

  name:

ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
     nginx.ingress.kubernetes.io/affinity: "cookie"
  path: /
  tls:
   - secretName: intern.my-domain.de
     hosts:
      - rocketchat.intern.my-domain.de

service:
  annotations: {}

  labels: {}
  
  type: ClusterIP

  port: 80


podLabels: {}


podAnnotations: {}


livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

```
