### ISSUE TITLE
Notifications configuration section is not working properly for Grafana helm chart

### ISSUE THREAD

**Issue by cbiphuk** [helm/charts#24510]
**Describe the bug**
I'm having issues configuring notifiers with values.yaml config file.

Right now notifiers section looks like this:
```
  notifiers:
    notifiers.yaml:
      - name: PagerDuty
        type: pagerduty
        uid: pagerduty1
        org_id: 1
        is_default: true
        send_reminder: true
        frequency: 1h
        disable_resolve_message: false
        settings:
          autoResolve: true
        secure_settings:
          integrationKey: '${pagerduty["integration_key"]}'
```

but when I'm trying to start the helm chart I'm getting errors on grafana container startup

`service init failed: Alert notification provisioning error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into notifiers.notificationsAsConfigV0`

**Version of Helm and Kubernetes**:
Kubernetes 1.18
Helm  3.6.2

**Which chart**:

https://github.com/grafana/helm-charts

**What happened**:
grafana container failed with error:

`service init failed: Alert notification provisioning error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into notifiers.notificationsAsConfigV0`

**What you expected to happen**:

Grafana should successfully started and I expected to find Pagerduty in Notifications section

**How to reproduce it** (as minimally and precisely as possible):

add to values.yaml
```
  notifiers:
    notifiers.yaml:
      - name: PagerDuty
        type: pagerduty
        uid: pagerduty1
        org_id: 1
        is_default: true
        send_reminder: true
        frequency: 1h
        disable_resolve_message: false
        settings:
          autoResolve: true
        secure_settings:
          integrationKey: '${pagerduty["integration_key"]}'
```

**Anything else we need to know**:

**Comment by frebn** [comment]
Hi I found this issue after having a similar problem but found out after the notifiers section is just missconfigured.

See here for configuration: https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md#sidecar-for-notifiers

In short: Remove the line `notifiers.yaml:`

**Comment by frebn** [comment]
If you are storing the the configuration in a cm/secret the syntax is:

```
notifiers.yaml: |-
  notifiers:
    - name: slack
      [...]
```
