### ISSUE TITLE
Permission Problem ( Pgadmin4 )

### ISSUE THREAD

**Issue by baturorkun** [helm/charts#24512]
hello,
I am writing helm to install pgadmin4 on RKE and used StatefulSet, but I have the problem that " ERROR : Failed to create the directory /var/lib/pgadmin/sessions".  I solved this problem on Openshift.

```
securityContext:
        fsGroup: 5050
        runAsGroup: 5050
        runAsUser: 5050
```

I  got an error about "fsGroup" field and removed it. But these lines did not solve my problem. And I added some parameters to my helm one-liner command like below.

```
--set volumePermissions.enabled=true 
--set volumePermissions.securityContext.runAsUser=5050
```

Nothing did solve the permission problem.

What can I do?

thanks
