### ISSUE TITLE
[stable/kube-lego] Error `put services kube-lego-nginx`

### ISSUE THREAD

**Issue by trobert2** [helm/charts#2458]
**Version of Helm and Kubernetes**:
kubernetes version: 1.7.5
helm version: 2.6.1

**Which chart**:
stable/kube-lego

**What happened**:
Error from pod:
```
time="2017-10-11T08:46:14Z" level=error msg="User \"system:serviceaccount:lego:encrypt-kube-lego\" cannot update services in the namespace \"lego\". (put services kube-lego-nginx)" context=provider provider=nginx
```

**What you expected to happen**:
have permissions to edit it's own service. I expect that the `put` verb is missing from the clusterrole definition.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install stable/kube-lego --name encrypt -f values.yaml --namespace lego
```
Where contents of the `values.yaml` are:
```
config:
  LEGO_EMAIL: mail@ourcompany.com
  LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
image:
  tag: canary
rbac:
  create: true
```

Then apply any ingress definition that is supposed to work with **lego**:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: chartmuseum
  name: chartmuseum
  namespace: 'internal-namespace-name'
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - chartmuseum.company.com
    secretName: chartmuseum-ingress-secret
  rules:
  - host: chartmuseum.company.com
    http:
      paths:
      - backend:
          serviceName: chartmuseum
          servicePort: 8080
        path: /
```

**Comment by trobert2** [comment]
I am using:
```
apiVersion: v1
description: Automatically requests certificates from Let's Encrypt
engine: gotpl
keywords:
- kube-lego
- letsencrypt
maintainers:
- email: jack.zampolin@gmail.com
  name: Jack Zampolin
- email: mgoodness@gmail.com
  name: Michael Goodness
name: kube-lego
sources:
- https://github.com/jetstack/kube-lego/tree/master/examples/nginx
version: 0.1.11
```

I see that version `version: 0.1.12` is available with an updated `ClusterRole`. was it released yet? I can't seem to be able to fetch it.

EDIT: it was released. Trying with that version after:
```
helm repo update
helm fetch stable/kube-lego --debug --version 0.1.12
```

yields the same error:
```
time="2017-10-11T09:26:13Z" level=error msg="User \"system:serviceaccount:lego:encrypt-kube-lego\" cannot update services in the namespace \"lego\". (put services kube-lego-nginx)" context=provider provider=nginx
```

The `ClusterRole` has been updated to the latest one.
