### ISSUE TITLE
Helpers can generate invalid names

### ISSUE THREAD

**Issue by krancour** [helm/charts#246]
Helpers such as the following are used frequently throughout this repository:

https://github.com/kubernetes/charts/blob/master/stable/wordpress/templates/_helpers.tpl#L9-L16

```
{{/*
Create a default fully qualified app name.
We truncate at 24 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 24 -}}
{{- end -}}
```

Note that depending on the value (length, really) of the `.Release.Name` and the chart name (or overridden chart name), it's quite possible that when truncated to 24 characters, the concatentation of those two values _ends_ in a `-`. (This can be on account of `-`'s occurring within the release name or chart name as well as the `-` that joins those two.) When this happens, the resulting value is invalid as a name for k8s resources.

I've seen this happen as recently as today.

**Comment by prydonius** [comment]
Sounds like this is coming up again because Helm removed the 14 char limit on release names and charts in here haven't been updated to increase the truncation. See https://github.com/kubernetes/charts/issues/233

**Comment by gorozcoh** [comment]
Using **trimSuffix** sprig function works for me:

```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes
 name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "master.fullname" -}}
{{- printf "%s-%s" .Release.Name "master-" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

Produces:
```
---
# Source: */master-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: newbie-flee-master
spec:
  accessModes:
    -"ReadWriteMany"
  resources:
    requests:
      storage: "400M"
  selector:
    matchLabels:
      name: newbie-flee-master
---
```
