### ISSUE TITLE
mongodb chart not able to run

### ISSUE THREAD

**Issue by zhiminwen** [helm/charts#2488]
**Is this a request for help?**:
---
Yes. Validate mongo chart is working
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Version of Helm and Kubernetes**:
Helm: 2.5
K8: 1.7.3

**Which chart**:
mongodb

**What happened**:
When deployed the chart, the pod failed. logs showing the message as
```
kubectl logs -f voting-tapir-mongodb-2498257007-psvsd

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '2008' not found
```

**What you expected to happen**:
Pods running

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --set image=bitnami/mongodb:3.4.9-r1,mongodbRootPassword=password,mongodbDatabase=my-db,serviceType=NodePort stable/mongodb
```

**Anything else we need to know**:

**Comment by jtgans** [comment]
I, too, have run into this problem. Logs from my installation:

```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com
nami    INFO  Initializing mongodb
Error executing 'postInstallation': User '2010' not found 
```

**Comment by jtgans** [comment]
Changing to a non-persistent backend fixed the issue, but now I don't have persistent data storage for mongo.

**Comment by zhiminwen** [comment]
I think this was due to the GlusterFS would assign a random gid > 2000.  I fixed this by putting a init container to own back the file system to root.

**Comment by jtgans** [comment]
Sorry, what do you mean by "GlusterFS would assign a random gid >2000", @zhiminwen?

Do you have the in it container available publicly so others can see what you did to resolve this?

**Comment by zhiminwen** [comment]
My fix is to add the following to the deployment file.
```
      initContainers:
        - name: init-myservice
          image: busybox
          command: ["sh", "-c", "chown root:root /bitnami /bitnami/mongodb"]
          volumeMounts:
            - name: data
              mountPath: /bitnami/mongodb

```
