### ISSUE TITLE
stable/sonarqube - stops right after start

### ISSUE THREAD

**Issue by maddocnc** [helm/charts#2574]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Version of Helm and Kubernetes**:
 helm version                                                                                                                                                                             
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}

kubectl version                                                                                                                                                                          maddocnc@MadBookPro
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-10-05T00:41:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:

stable/sonarqube

**What happened**:
all started, pv/pvc bound, sonarqube main pod gives error:
```
Readiness probe failed: Get http://10.244.0.112:9000/: dial tcp 10.244.0.112:9000: getsockopt: connection refused
Error syncing pod
```

**What you expected to happen**:
main pod started, 9000 port - opened.

**How to reproduce it** (as minimally and precisely as possible):

helm install sonarqube
bare metal node. HostPath volumes.

values.yaml as follows:
```
# Default values for sonarqube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: sonarqube
  tag: 6.5
service:
  name: sonarqube
  type: ClusterIP  #I don't have elb, so ingress controller in daemon set mode.
  externalPort: 9000
  internalPort: 9000
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - sq.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
  # Secrets must be manually created in the namespace.
    - secretName: sonarqube-tls
      hosts:
        - sq.example.com
resources:
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 100m
   memory: 512Mi
  requests:
   cpu: 100m
   memory: 512Mi
persistence:
  enabled: true
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "standart"
  useExisting: false
  accessMode: ReadWriteOnce
  dataVolumeSize: 8Gi
  confVolumeSize: 1Gi
  extensionsVolumeSize: 3Gi

## Configuration values for the postgresql dependency
## ref: https://github.com/kubernetes/charts/blob/master/stable/postgressql/README.md
##
postgresql:
  postgresUser: "sonarUser"
  postgresPassword: "someextreamlysafepassword"
  postgresDatabase: "sonarDB"
```

**Anything else we need to know**:

There was an warning in pod logs about non existing sonar.properties, so I copied default docker-sonarqube sonar.properties and wrapper.conf there. in /opt/sonarqube/logs/ there is only es and sonar logs, no web.log.
combined pod logs(the same log was with empty /conf/):

```
2017.10.24 08:14:52 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2017.10.24 08:14:53 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[es]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djna.nosys=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/opt/sonarqube/temp -cp ./lib/common/*:./lib/search/* org.sonar.search.SearchServer /opt/sonarqube/temp/sq-process5610396422498883836properties
2017.10.24 08:14:57 INFO  es[][o.s.p.ProcessEntryPoint] Starting es
2017.10.24 08:14:58 INFO  es[][o.s.s.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2017.10.24 08:15:00 INFO  es[][o.elasticsearch.node] [sonarqube] version[2.4.4], pid[25], build[fcbb46d/2017-01-03T11:33:16Z]
2017.10.24 08:15:00 INFO  es[][o.elasticsearch.node] [sonarqube] initializing ...
2017.10.24 08:15:00 INFO  es[][o.e.plugins] [sonarqube] modules [], plugins [], sites []
2017.10.24 08:15:00 INFO  es[][o.elasticsearch.env] [sonarqube] using [1] data paths, mounts [[/opt/sonarqube/data (/dev/md2)]], net usable_space [627.1gb], net total_space [1.7tb], spins? [possibly], types [ext4]
2017.10.24 08:15:00 INFO  es[][o.elasticsearch.env] [sonarqube] heap size [989.8mb], compressed ordinary object pointers [true]
2017.10.24 08:15:08 INFO  app[][o.s.a.SchedulerImpl] Stopping SonarQube
2017.10.24 08:15:08 INFO  es[][o.s.p.StopWatcher] Stopping process
```
