### ISSUE TITLE
Enabling prometheus/datadog on traefic causes container to crash

### ISSUE THREAD

**Issue by shadycuz** [helm/charts#2663]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

1.8.1

**Which chart**:
```
NAME                    REVISION        UPDATED                         STATUS          CHART           NAMESPACE
sanguine-butterfly      3               Sat Nov  4 21:11:19 2017        DEPLOYED        traefik-1.13.0  kube-system
```

**What happened**:
Pod wont start
```
2017/11/04 21:06:42 Error reading TOML config file /config/traefik.toml : Near line 22 (last key parsed 'web.metrics.prometheus'): expected a top-level item to end with a newline, comment, or EOF, but got ',' instead
```

**What you expected to happen**:
Container to come up and ingress controller to work.

**How to reproduce it** (as minimally and precisely as possible):
My values.yaml
```
metrics:
  prometheus:
    enabled: true
    buckets: 0.1,0.3,1.2,5
  datadog:
    enabled: false
    # address: "localhost:8125"
    # pushInterval: 30s
  statsd:
    enabled: false
    # address: "localhost:8125"
    # pushInterval: 30s
```

**Anything else we need to know**:

**Comment by ghost** [comment]
Same issue on 1.7.4

Without Prometheus everything works fine.

**Comment by cknowles** [comment]
Similar problems with the datadog and statsd additions, it's because the config values are not quoted in the [config map](https://github.com/kubernetes/charts/blob/32adf58e00c5ea781b2fc90ee2ed79d0724c7b6d/stable/traefik/templates/configmap.yaml#L92), introduced in https://github.com/kubernetes/charts/pull/1622.

Workaround is to specify a value including quotes:
```
metrics:
  prometheus:
    enabled: true
    buckets: "[0.1,0.3,1.2,5.0]"
  datadog:
    enabled: true
    address: "\"localhost:8125\""
```

**Comment by ghost** [comment]
Thanks @c-knowles. I'll give that a go.

Spins up fine if I edit the configmap traefik.toml file and changed the metrics section to:
```
[web.metrics.prometheus]
  Buckets = [0.1,0.3,1.2,5.0]
```

**Comment by ghost** [comment]
@c-knowles the quotes cause it to be treated as a string while Traefik requires a slice.

I ended up creating a value.yaml like this:
```
loadBalancerIP: <myLBIP>
ssl:
  enabled: true
acme:
  enabled: true
  email: <myEmail>
  staging: false
metrics:
  prometheus:
    enabled: true
    buckets: "[0.1,0.3,1.2,5.0]"
```

Make sure you change the 5 to a float by adding the .0 or the pod throws an error.
