### ISSUE TITLE
[stable/redis-ha] redis-ha has no option for legacy access, e.g through a single IP address.

### ISSUE THREAD

**Issue by poor-bob** [helm/charts#2809]
**Is this a request for help?**:

No, kind of? 
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request
---

When I setup redis-ha on my cluster manually, I had a requirement that a client should connect to the proper master with each request via a single IP address as it did not directly support redis-sentinel.

[from redis-sentinel docs](https://redis.io/topics/sentinel),

> Fundamental things to know about Sentinel before deploying
...

> You need Sentinel support in your clients. Popular client libraries have Sentinel support, but not all.

 Due to how the redis-sentinels work, they expose this master node IP via API call. 
[from redis-sentinel docs](https://redis.io/topics/sentinel),
> Obtaining  the address of the current master
...
> 127.0.0.1:5000> SENTINEL get-master-addr-by-name mymaster
> 1) "127.0.0.1"
> 2) "6379"

As far as I know, php-fpm caching is not configured to use redis via the redis-sentinels, but rather a single IP address, e.g a service. Directly routing a Kubernetes service to a master redis pod would break the HA provided by the sentinels.

To get around this, I setup a reverse-proxy from a Go [redis-reverse-proxy](https://github.com/enriclluelles/redis-sentinel-proxy), and the [Docker image](https://github.com/flaccid/docker-redis-sentinel-proxy) therein. Is this of use to the community?

Quick kube example (I'd be willing to convert to Chart best practices, with Deployment instead of RC)

> redis-sentinel-proxy-controller.yaml

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel-proxy
spec:
  replicas: 3
  selector:
    redis-sentinel-proxy: "true"
  template:
    metadata:
      labels:
        name: redis-sentinel-proxy
        redis-sentinel-proxy: "true"
        role: sentinel-proxy
    spec:
      containers:
      - name: sentinel-proxy 
        image: us.gcr.io/.../redis-sentinel-proxy:v1.1
        resources:
          requests:
            cpu: 2m
            memory: 52Mi
        ports:
          - containerPort: 6379
```

> redis-sentinel-proxy-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel-proxy
    role: service
  name: redis-sentinel-proxy
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    redis-sentinel-proxy: "true"
```

How I use the redis-sentinel-proxy building the php  Dockerimage for caching:
```
 FROM php:7.1.7-fpm-alpine

...

#install redis
  RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/${PHPREDIS_VERSION}.tar.gz \
  && mkdir -p /usr/src/php/ext/ \
  && tar xfz /tmp/redis.tar.gz -C /usr/src/php/ext/ \
  && mv /usr/src/php/ext/* /usr/src/php/ext/redis \
  && rm -r /tmp/redis.tar.gz \
  && docker-php-ext-install redis \
  && docker-php-source delete

  #config sessions to store in redis
  RUN { \
      echo 'session.save_handler = redis'; \
      echo 'session.save_path = tcp://redis-sentinel-proxy.default.svc.cluster.local:6379'; \
  } >> /usr/local/etc/php/conf.d/docker-php-ext-redis.ini

```
