### ISSUE TITLE
incubator/drone // can't connect to DRONE_SERVER (grpc)

### ISSUE THREAD

**Issue by steffenmllr** [helm/charts#2837]
Following up on this [problem](https://github.com/kubernetes/charts/pull/2614#issuecomment-346389730) as instructed by @christian-roggia 

Drone hangs after receiving the build as seen in the screenshot. Judging from the logs of the Agent it has Problems with the `grpc` connection. `transport: Error while dialing dial tcp 10.3.16.197:9000: getsockopt: connection refused"; Reconnecting to {drone-drone:9000 <nil>`

![image](https://user-images.githubusercontent.com/449563/33148055-9bd2f720-cfca-11e7-883d-ab87a94f1010.png)

### System Info
* `Helm v2.7.2`
* `k8n v1.8.3` installed via `1.7.9-tectonic.1`
*  `coreos Stable: 1520.8.0`
* `German Azure Cloud`

### Config
Installed via: `helm install --name drone -f drone.yml incubator/drone`
```yaml
appVersion: "0.8.1"
image:
  repository: "docker.io/drone/drone"
  tag: "0.8.1"
  pullPolicy: "IfNotPresent"

agentImage:
  repository: "docker.io/drone/agent"
  tag: "0.8.1"
  pullPolicy: "IfNotPresent"

service:
  httpPort: 80
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "tectonic"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: 100m
  
  hosts:
    - drone.myserver.com

  tls:
    - secretName: drone-tls
      hosts:
        - drone.myserver.com

server:
  host: "https://drone.myserver.com"
  env:
    DRONE_DEBUG: "true"
    DRONE_DATABASE_DRIVER: "sqlite3"
    DRONE_DATABASE_DATASOURCE: "drone.sqlite"
    DRONE_GITHUB_SKIP_VERIFY: "true"
    DRONE_PROVIDER: "github"
    DRONE_OPEN: "false"
    DRONE_GITHUB: "true"
    DRONE_ORGS: "mllrsohn"
    DRONE_ADMIN: "steffenmllr"
    DRONE_GITHUB_CLIENT: "XXXX"
    DRONE_GITHUB_SECRET: "XXXX"

  resources:
    requests:
      memory: 32Mi
      cpu: 40m
    limits:
      memory: 2Gi
      cpu: 1

agent:
  env:
    DRONE_DEBUG: "true"
  resources:
    requests:
      memory: 32Mi
      cpu: 40m
    limits:
      memory: 2Gi
      cpu: 1
```

### UI Log
```
git init
+ Initialized empty Git repository in /drone/src/github.com/steffenmllr/docker-env-debug/.git/
+ git remote add origin https://github.com/steffenmllr/docker-env-debug.git
+ git fetch --no-tags origin +refs/heads/master:
fatal: unable to access 'https://github.com/steffenmllr/docker-env-debug.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
exit status 128
```

## drone-drone-agent log
```
{"time":"2017-11-22T20:17:10Z","level":"debug","message":"request next execution"}
INFO: 2017/11/22 20:17:10 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 10.3.16.197:9000: getsockopt: connection refused"; Reconnecting to {drone-drone:9000 <nil>}
INFO: 2017/11/22 20:17:11 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 10.3.16.197:9000: getsockopt: connection refused"; Reconnecting to {drone-drone:9000 <nil>}
{"time":"2017-11-22T20:20:58Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"received execution"}
{"time":"2017-11-22T20:20:58Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"listen for cancel signal"}
{"time":"2017-11-22T20:20:59Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":0,"exited":false,"message":"update step status"}
{"time":"2017-11-22T20:20:59Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":0,"exited":false,"message":"update step status complete"}
{"time":"2017-11-22T20:21:08Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream opened"}
{"time":"2017-11-22T20:21:58Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"pipeline lease renewed"}
{"time":"2017-11-22T20:22:58Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"pipeline lease renewed"}
{"time":"2017-11-22T20:23:58Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"pipeline lease renewed"}
{"time":"2017-11-22T20:24:10Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream copied"}
{"time":"2017-11-22T20:24:10Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream uploading"}
{"time":"2017-11-22T20:24:10Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream upload complete"}
{"time":"2017-11-22T20:24:10Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream closed"}
{"time":"2017-11-22T20:24:11Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":1,"exited":true,"message":"update step status"}
{"time":"2017-11-22T20:24:11Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":1,"exited":true,"message":"update step status complete"}
{"time":"2017-11-22T20:24:11Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","error":"","exit_code":1,"message":"pipeline complete"}
{"time":"2017-11-22T20:24:11Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"uploading logs"}
{"time":"2017-11-22T20:24:11Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"uploading logs complete"}
{"time":"2017-11-22T20:24:11Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","error":"","exit_code":1,"message":"updating pipeline status"}
{"time":"2017-11-22T20:24:11Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"stop listening for cancel signal"}
{"time":"2017-11-22T20:24:12Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"updating pipeline status complete"}
{"time":"2017-11-22T20:24:12Z","level":"debug","message":"request next execution"}
{"time":"2017-11-22T20:24:12Z","level":"debug","repo":"steffenmllr/docker-env-debug","build":"1","id":"1","message":"pipeline done"}
```

## drone-drone-dind log
```
time="2017-11-22T20:17:10.309347752Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found" 
time="2017-11-22T20:17:10.309729866Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]" 
time="2017-11-22T20:17:10.310782206Z" level=info msg="libcontainerd: new containerd process, pid: 20" 
time="2017-11-22T20:17:11.419693429Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2017-11-22T20:17:11.420631664Z" level=info msg="Loading containers: start." 
time="2017-11-22T20:17:11.421815109Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1" 
time="2017-11-22T20:17:11.422580837Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T20:17:11.423303665Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T20:17:11.615526914Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2017-11-22T20:17:11.714168335Z" level=info msg="Loading containers: done." 
time="2017-11-22T20:17:11.719926352Z" level=info msg="Daemon has completed initialization" 
time="2017-11-22T20:17:11.719994754Z" level=info msg="Docker daemon" commit=89658be graphdriver=overlay version=17.05.0-ce 
time="2017-11-22T20:17:11.727266729Z" level=info msg="API listen on [::]:2375" 
time="2017-11-22T20:17:11.727289730Z" level=info msg="API listen on /var/run/docker.sock" 
time="2017-11-22T20:21:08Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T20:21:08Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T20:24:10.759482758Z" level=error msg="Error closing logger: invalid argument" 
time="2017-11-22T20:24:11.289418872Z" level=error msg="Handler for POST /v1.26/containers/0_6799379795694111078_clone/kill returned error: Cannot kill container 0_6799379795694111078_clone: Container 18e4282fd8dd9631733ec6c641b0a77928b89c81e50f464c4c7bcb18511e207c is not running" 
```
