### ISSUE TITLE
Neo4j UI doesn't connect to server

### ISSUE THREAD

**Issue by rmackenzie85** [helm/charts#2862]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**: 
Helm: v2.7.0
Kubernetes (client): 1.7.6
Kubernetes (server): 1.7.7

**Which chart**:
stable/neo4j

**What happened**:
After running the chart and exposing neo4j via a headless service, the web UI hangs on attempting to connect to the server. It never responds to my attempt to authenticate.

**What you expected to happen**:
After running `:server connect` in the web UI and putting in my default credentials, then clicking to log in, I would expect it to either authenticate me or indicate an authentication failure.

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/neo4j

I used the following headless service for a loadbalancer:
```
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-lb
  labels:
    app: neo4j-lb
spec:
  ports:
    - port: 7474
      name: web
    - port: 7473
      name: web-ssl
    - port: 7687
      name: bolt
  type: LoadBalancer
  selector:
    app: neo4j
```
kubectl create -f lb-neo4j.yaml

**Anything else we need to know**:
I'm running this on microsoft azure container service. I believe they have hooks in place that make the loadbalancer deployment just work. I'm not sure if this will work on minikube.

Having the UI available is important for us for debugging and testing. We don't really know of an alternative except the cypher shell which is not nearly as friendly to use.
Thanks!
