### ISSUE TITLE
[stable/jenkins] not creating ingress controller

### ISSUE THREAD

**Issue by jtslear** [helm/charts#3012]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Version of Helm and Kubernetes**:
```
helm
Client: "v2.7.2"
Server: "v2.7.2"
kubernetes
Client Version: "v1.8.4"
Server Version: "v1.8.2-gke.0"
```

**Which chart**: stable/jenkins

**What happened**: an ingress controller failed to create

**What you expected to happen**: an ingress controller to be created

**How to reproduce it** (as minimally and precisely as possible):
1. Values file is created with hopefully the correct information
1. Appropriate secret is installed into kubernetes containing the necessary TLS certificates for the ingress controller
1. helm install

**Anything else we need to know**:
My values file:
```yaml
---

Master:
  ServiceType: ClusterIP
  Hostname: jenkins.example.com
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.allow-http: "false"
    TLS:
      - secretName: jenkins-ingress-ssl
        hosts:
          - 'jenkins.example.com'
rbac:
  install: true
```

My Secret:
```
k describe secret jenkins-ingress-ssl
Name:         jenkins-ingress-ssl
Namespace:    default
Labels:       <none>
Annotations:  creationDate=Dec 12 17:50:51 2017 GMT
              expireDate=Dec 10 17:50:51 2027 GMT

Type:  Opaque

Data
====
tls.crt:  1224 bytes
tls.key:  1704 bytes
```

helm install dry-run and debug:
[https://gist.github.com/jtslear/9e2b5135415de2f456d90b8b0708ea20](https://gist.github.com/jtslear/9e2b5135415de2f456d90b8b0708ea20)
