### ISSUE TITLE
[stable/docker-registry] Docker pull issue from a Helm chart

### ISSUE THREAD

**Issue by yaumeg** [helm/charts#3173]
**Is this a request for help?**:yes

---

BUG REPORT

**Version of Helm and Kubernetes**:
Helm Client & Server: v2.7.2
kubectl: v1.9.0
Kubernetes: v1.8.3

**Which chart**:
stable/docker-registry

**What happened**:
Deployment is successful and registry is up and working well when applying port-forwarding :
`kubectl port-forward $POD_NAME 8080:5000`
My concern comes when I try to use the private registry within a Helm chart : I can't figure a way to make the image pull work. What is the correct syntax for the image tag in values.yaml ?
Something like that doesn't work, which seems logic because of port-forwarding not implemented : 
`image: localhost:8080/image:latest`

**What you expected to happen**:
Use within a helm chart a private registry deployed with the helm chart docker-registry.

**How to reproduce it** (as minimally and precisely as possible):

- helm install stable/docker-registry

- create a helm chart based on a docker image stored in private registry

**Anything else we need to know**:

@rendhalver, any ideas? Thanks.

**Comment by mattfarina** [comment]
cc: @jpds

**Comment by rendhalver** [comment]
We enabled ingress in our setup and it works as expected.
We also set it up with a tls cert for the domain.

Something like this as your values override:
```
tlsSecretName: "docker-registry.example.com"
ingress:
  enabled: true
  hosts:
    - "docker-registry.example.com"
  tls:
    - hosts:
      - docker-registry.example.com
      secretName: docker-registry.example.com.tls
```
