### ISSUE TITLE
Grafana: Annotating with "prometheus.io/scrape" doesnt work

### ISSUE THREAD

**Issue by ekampf** [helm/charts#3201]
**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

**Which chart**:
stable/grafana

**What happened**:
When specifying annotations I get the error: `Error: UPGRADE FAILED: unrecognized type: string`

Example annotations in values.yaml:
```
server:
  ## Grafana Pod annotations:
  ##
  annotations:
    prometheus.io/scrape: "true"
```

The problem is that the chart code removes the double-quotes characters so the resulting deployment file is:
```
      annotations:
        checksum/config: ...
        checksum/dashboards-config: ...
        prometheus.io/scrape: true
```
instead of:
```
      annotations:
        checksum/config: ...
        checksum/dashboards-config: ...
        prometheus.io/scrape: "true"
```

**Comment by mattfarina** [comment]
@ekampf can you try this instead?

```yaml
server:
  annotations:
    prometheus.io/scrape: "\"true\""
```
