### ISSUE TITLE
[stable/pachyderm] Missing braces in pachd_secret.yaml

### ISSUE THREAD

**Issue by kminehart** [helm/charts#3277]
**BUG REPORT**:

**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Which chart**:

`stable/pachyderm`

**What happened**:

When `google` is selected as the credential in `values.yaml`, and you try to install `stable/pacyhderm`, you get this error:

```
Error: YAML parse error on pachyderm/templates/pachd_secret.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key
```

**What you expected to happen**:

I expected it to install if everything else was 👌 

**How to reproduce it** (as minimally and precisely as possible):
```
$ helm install --name pachyderm --namespace pachyderm --set credentials=google stable/pachyderm                                                       1 ↵
Error: YAML parse error on pachyderm/templates/pachd_secret.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key
```

**Anything else we need to know**:

It looks like there are some missing braces in `templates/pachd_secret.yaml`. I didn't do much poking around, is this because these different credential types are not supported yet?

https://github.com/kubernetes/charts/blob/master/stable/pachyderm/templates/pachd_secret.yaml

```
---
apiVersion: v1
kind: Secret
metadata:
  name: pachyderm-storage-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    suite: pachyderm
data:
  {{- if eq .Values.credentials "s3" }}
  minio-id: {{ .Values.s3.accessKey | b64enc | quote }}
  minio-secret: {{ .Values.s3.secretKey | b64enc | quote  }}
  minio-bucket: {{ .Values.s3.bucketName | b64enc | quote }}
  minio-endpoint: {{ .Values.s3.endpoint | b64enc | quote }}
  minio-secure: {{ .Values.s3.secure | b64enc | quote }}
  minio-signature: {{ .Values.s3.signature | b64enc | quote }}
  {{- else if eq .Values.credentials "google" }}
  google-bucket: { .Values.google.bucketName | b64enc | quote }}
  {{- else if eq .Values.credentials "amazon" }}
  amazon-bucket: { .Values.amazon.bucketName | b64enc | quote }}
  amazon-distribution: { .Values.amazon.distribution | b64enc | quote }}
  amazon-id: { .Values.amazon.id | b64enc | quote }}
  amazon-region: { .Values.amazon.region | b64enc | quote }}
  amazon-secret: { .Values.amazon.secret | b64enc | quote }}
  amazon-token: { .Values.amazon.token | b64enc | quote }}
  {{- else if eq .Values.credentials "microsoft" }}
  microsoft-container: { .Values.microsoft.container | b64enc | quote }}
  microsoft-id: { .Values.microsoft.id | b64enc | quote }}
  microsoft-secret: { .Values.microsoft.secret | b64enc | quote }}
{{- end }}
```
