### ISSUE TITLE
[stable/nginx-ingress] Error: UPGRADE FAILED: error validating "" for versions v0.8.15 and above.

### ISSUE THREAD

**Issue by munai-das** [helm/charts#3323]
**Is this a request for help?**: No. it is a bug report

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**: Helm v2.61, K8s v1.6.7

**Which chart**: stable/nginx-ingress version 0.8.15 and above

**What happened**:  

> Error: UPGRADE FAILED: error validating "": error validating data: found invalid field revisionHistoryLimit for v1beta1.DaemonSetSpec

**What you expected to happen**:
> Release "nginx-ingress" has been upgraded. Happy Helming!

**How to reproduce it** (as minimally and precisely as possible):
I have the values.yml file and command I ran.

**Command**
```
➜  nginx-ingress git:(master) helm upgrade nginx-ingress stable/nginx-ingress --version 0.8.23  -f values.yaml --dry-run --debug
[debug] Created tunnel using local port: '51871'

[debug] SERVER: "localhost:51871"

[debug] Fetched stable/nginx-ingress to /Users/user/.helm/cache/archive/nginx-ingress-0.8.23.tgz

Error: UPGRADE FAILED: error validating "": error validating data: found invalid field revisionHistoryLimit for v1beta1.DaemonSetSpec
```

**Values.yml**
```
controller:
  ingressClass: "nginx"
  config: {enable-underscores-in-headers: "true"}
  defaultBackendService: ""
  extraArgs:
    default-ssl-certificate: containerhosting/ingress-wildcard-cert
    enable-ssl-passthrough: "true"
  hostNetwork: false
  image:
    pullPolicy: IfNotPresent
    repository: gcr.io/google_containers/nginx-ingress-controller
    tag: 0.9.0-beta.15
  kind: DaemonSet
  name: controller
  nodeSelector: {}
  podAnnotations: {}
  publishService:
    enabled: false
    pathOverride: ""
  replicaCount: 1
  resources: {}
  scope:
    enabled: false
    namespace: ""
  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePorts:
      http: 32080
      https: 32443
    targetPorts:
      http: 80
      https: 443
    type: NodePort
  stats:
    enabled: true
    service:
      annotations: {}
      clusterIP: ""
      externalIPs: []
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      servicePort: 18080
      type: ClusterIP
defaultBackend:
  enabled: true
  extraArgs: {}
  image:
    pullPolicy: IfNotPresent
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.2"
  name: default-backend
  nodeSelector: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 80
    type: ClusterIP
statsExporter:
  endpoint: /metrics
  extraArgs: {}
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/cy-play/vts-nginx-exporter
    tag: v0.0.3
  metricsNamespace: nginx
  name: stats-exporter
  resources: {}
  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 9913
    type: ClusterIP
  statusPage: http://localhost:18080/nginx_status/format/json
tcp: {}
udp: {}
```

**Anything else we need to know**:  We happen to have two k8s clusters. The same works on K8s v1.7.5.
