### ISSUE TITLE
Error: release sonatype-nexus failed: Service in version "v1" cannot be handled as a Service / port: null

### ISSUE THREAD

**Issue by feffi** [helm/charts#3360]
**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
`stable/sonatype-nexus`

**What happened**:
The current Chart will result in a failure if the docker feature is enabled without adding/enabling a port. The default value of the port isn't set so the resulting template will show `port: null`.

**What you expected to happen**:
The default port should be set, regardless of the enablement of the docker feature.

**How to reproduce it** (as minimally and precisely as possible):
```
my_values.yml
service:
  type: ClusterIP

docker:
  enabled: true
```

```
helm upgrade --debug --install sonatype-nexus --namespace default -f my_values.yml stable/sonatype-nexus
```
Results in:
```
[debug] Created tunnel using local port: '59534'

[debug] SERVER: "127.0.0.1:59534"

[debug] Fetched stable/sonatype-nexus to /Users/feffi/.helm/cache/archive/sonatype-nexus-0.1.6.tgz

Release "sonatype-nexus" does not exist. Installing it now.
[debug] CHART PATH: /Users/feffi/.helm/cache/archive/sonatype-nexus-0.1.6.tgz

Error: release sonatype-nexus failed: Service in version "v1" cannot be handled as a Service: v1.Service: Spec: v1.ServiceSpec: Ports: []v1.ServicePort: v1.ServicePort: Port: readUint32: unexpected character: �, parsing 316 ...","port":n... at {"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"sonatype-nexus","chart":"sonatype-nexus-0.1.6","heritage":"Tiller","release":"sonatype-nexus"},"name":"sonatype-nexus-sonatype-nexus","namespace":"default"},"spec":{"ports":[{"name":"nexus","port":8081,"protocol":"TCP"},{"name":"nexus-docker","port":null,"protocol":"TCP"}],"selector":{"app":"sonatype-nexus","release":"sonatype-nexus"},"type":"ClusterIP"}}
```
**Anything else we need to know**:
A pull request for fixing this issue has been made: #3359

**Comment by manishroy171o** [comment]
Hello Team,
I am facing issue while configuring docker private registry,

values.yaml
------------------------
service:
  name: nexus
  type: ClusterIP
  externalPort: 8081
  internalPort: 8081

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - sonatypenexus.example.com

docker:
  enabled: true 
  port: 5000
  host: sonatypenexusxyz.example.com

it is getting deployed perfectly but not able to push and pull images from 5000 port getting Unauthorized Access 401. 

after login to to console manually i have created a docker hosted registry where "http 5000" port i have given.

Kindly help on htis issue.

Thanks

**Comment by chezbut** [comment]
I am having this issue with my own chart as well. So far I have no way to know what line it is complaining about or what is missing a port specification. Will have to look further in my chart and test by trial and error.

**Comment by chezbut** [comment]
so, it was able to deploy after I specified an externalHTTPSPort: and internalHTTPSPort: under service:  - even though there is no https service on this, and it is a backend service only, nevertheless I had to add it in order to get helm to stop failing with the error "Service in version "v1" cannot be handled as a Service / port: null"  (a different chart, not the Sonatype chart - but the same issue).

**Comment by morvencao** [comment]
@manishroy171o   issue in my env.

When I push image to my private docker registry built by return sonatype-nexus chart, 
got the return `default backend - 404`

Sonatype-nexus installed by:
```
helm install --name nexus --set image.repository=clearent/nexus,image.tag=3.6.0-02,ingress.enabled=true,ingress.hosts[0]=nexus.example.com,ingress.annotations[0]="kubernetes.io/ingress.class: nginx",docker.enabled=true,docker.port=5509,docker.host=docker.example.com,persistence.enabled=true,persistence.storageClass=local-storage stable/sonatype-nexus
```

I create `hosted docker private repository` and everything seems OK including logging on the docker repository. 
When I try to push image to the docker repository, just got:
```
The push refers to repository [docker.example.com/alpine]
d39d92664027: Preparing
error parsing HTTP 404 response body: invalid character 'd' looking for beginning of value: "default backend - 404"
```

The ingress yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: sonatype-nexus
    chart: sonatype-nexus-0.1.6
    heritage: Tiller
    release: nexus
  name: nexus-sonatype-nexus
  namespace: default
spec:
  rules:
  - host: docker.example.com
    http:
      paths:
      - backend:
          serviceName: nexus-sonatype-nexus
          servicePort: 5509
        path: /
  - host: nexus.example.com
    http:
      paths:
      - backend:
          serviceName: nexus-sonatype-nexus
          servicePort: 8081
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 9.111.255.44
```

While the everything on `nexus.example.com` is OK, but the docker registry `docker.example.com` keep return 404 from ingress nginx logs.

**Comment by maciaszczykm** [comment]
@morvencao ?

**Comment by morvencao** [comment]
When I push image to my private docker registry built by return sonatype-nexus chart, 
got the return `default backend - 404`

Sonatype-nexus installed by:
```
helm install --name nexus --set image.repository=clearent/nexus,image.tag=3.6.0-02,ingress.enabled=true,ingress.hosts[0]=nexus.example.com,ingress.annotations[0]="kubernetes.io/ingress.class: nginx",docker.enabled=true,docker.port=5509,docker.host=docker.example.com,persistence.enabled=true,persistence.storageClass=local-storage stable/sonatype-nexus
```

I create `hosted docker private repository` and everything seems OK including logging on the docker repository. 
When I try to push image to the docker repository, just got:
```
The push refers to repository [docker.example.com/alpine]
d39d92664027: Preparing
error parsing HTTP 404 response body: invalid character 'd' looking for beginning of value: "default backend - 404"
```

The ingress yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: sonatype-nexus
    chart: sonatype-nexus-0.1.6
    heritage: Tiller
    release: nexus
  name: nexus-sonatype-nexus
  namespace: default
spec:
  rules:
  - host: docker.example.com
    http:
      paths:
      - backend:
          serviceName: nexus-sonatype-nexus
          servicePort: 5509
        path: /
  - host: nexus.example.com
    http:
      paths:
      - backend:
          serviceName: nexus-sonatype-nexus
          servicePort: 8081
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 9.111.255.44
```

While the everything on `nexus.example.com` is OK, but the docker registry `docker.example.com` keep return 404 from ingress nginx logs.
