### ISSUE TITLE
[stable/etcd-operator] backup operator segfault

### ISSUE THREAD

**Issue by alassek** [helm/charts#3478]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Kubernetes: 1.8.6-gke.0

```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Which chart**:

stable/etcd-operator

**What happened**:

`E0129 19:44:07.945455       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory ad
dress or nil pointer dereference)`

[full stacktrace](https://gist.github.com/alassek/301b8a6f9d887695ca76534fcc0350b1)

**What you expected to happen**:

Backup Operator should create a backup

**How to reproduce it** (as minimally and precisely as possible):

```
gcloud container clusters create [cluster name] --cluster-version=1.8.6-gke.0
kubectl create clusterrolebinding [name] --clutserrole=cluster-admin --user=[email]
kubectl create namespace example
kubectl create serviceaccount tiller --namespace=kube-system
kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller

kubectl create serviceaccount example-etcd-operator --namespace=example
kubectl create serviceaccount example-etcd-backup --namespace=example
```

[service account RBAC rules](https://gist.github.com/alassek/9c6593f3d91c884faa2a24cc0db201f0)

```
helm install stable/etcd-operator -f values.yaml --namespace=example --name=etcd-example
```

```
# values.yaml
rbac:
  create: false
  apiVersion: v1beta1
  etcdOperatorServiceAccountName: example-etcd-operator
  backupOperatorServiceAccountName: example-etcd-backup

deployments:
  etcdOperator: true
  backupOperator: true

customResources:
  createEtcdClusterCRD: true
  createBackupCRD: true
  createRestoreCRD: false

etcdOperator:
  name: etcd-operator
  replicaCount: 1
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.8.3
    pullPolicy: Always
  resources:
    cpu: 100m
    memory: 128Mi
  ## Node labels for etcd-operator pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
  ## additional command arguments go here; will be translated to `--key=value` form
  ## e.g., analytics: true
  commandArgs: {}

backupOperator:
  name: etcd-backup-operator
  replicaCount: 1
  image:
    repository: quay.io/coreos/etcd-operator
    tag: v0.8.3
    pullPolicy: Always
  resources:
    cpu: 100m
    memory: 128Mi
  spec:
    storageType: S3
    s3:
      s3Bucket: flywheel-vault-backup
      awsSecret: aws
  ## Node labels for etcd pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
  ## additional command arguments go here; will be translated to `--key=value` form
  ## e.g., analytics: true
  commandArgs: {}

etcdCluster:
  name: vault-etcd-cluster
  size: 3
  version: 3.2.10
  image:
    repository: quay.io/coreos/etcd
    tag: v3.2.10
    pullPolicy: Always
  enableTLS: false
  # TLS configs
  tls:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls
  ## etcd cluster pod specific values
  ## Ref: https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-members-cluster-with-resource-requirement
  pod:
    ## Antiaffinity for etcd pod assignment
    ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    antiAffinity: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    ## Node labels for etcd pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    nodeSelector: {}
```

**Anything else we need to know**:

`v0.7.2` is the last version I am able to get working. Every version from `v0.8.0` onward has this problem.
