### ISSUE TITLE
[incubator/kafka] expensive readiness check

### ISSUE THREAD

**Issue by convoi** [helm/charts#3697]
the readiness check uses a lot of cpu. an idle kafka pod uses about 150mCPU. if i remove the readiness check it goes down to 5mCPU.
the yolean kafka setup does not use the expensive java processes but instead just uses the tcp check.
can we do it without?
agreeably the 150mCPU on a real kafka production system under load is not that much, but for dev/test environments or on aws t2 instances this can really hurt!

**Comment by t-d-d** [comment]
Does this make sense:
```
        livenessProbe:
          exec:
            command:
              - sh
              - -ec
              - /usr/bin/jps | /bin/grep -q SupportedKafka
        readinessProbe:
          tcpSocket:
            port: 9092
```
@convoi Do you want test how that loads the system?

See also https://github.com/kubernetes/charts/issues/2682
