### ISSUE TITLE
[incubator/kafka] Install fails when `service-registry.enabled` is set to `true`

### ISSUE THREAD

**Issue by pdlug** [helm/charts#3729]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.8.1, kubernetes 1.9.1

**Which chart**: incubator/kafka

**What happened**: Setting `service-registry.enabled` to `true` causes `helm install` to fail, appears to be due to two service definitions with the same name (see below)

**What you expected to happen**: Kafka to start with a schema registry instance

**How to reproduce it** (as minimally and precisely as possible):

```bash
$ helm install --name my-kafka --namespace kafka --set global.namespace=kafka -f my-kafka.yml incubator/kafka
Error: release my-kafka failed: services "my-kafka-zookeeper" already exists
```

`my-values.yml`:

```yaml
---
replicas: 1
schema-registry:
  enabled: true
```

Changing the enabled from true to false results in a successful run.

**Anything else we need to know**:

This appears to be because there are two service named "my-kafka-zookeeper" being defined (see below).

Debugging w/ `--dry-run --debug` you can see that there are two `Service` definitions named `my-kafka-zookeeper` in the generated YAML.

```bash
helm install --dry-run --debug --name my-kafka --namespace kafka --set global.namespace=kafka -f my-kafka.yml incubator/kafka
```
First service definition:

```yaml
---
# Source: kafka/charts/schema-registry/charts/kafka/charts/zookeeper/templates/service-clients.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-kafka-zookeeper
  labels:
    app: "zookeeper"
    chart: "zookeeper-0.3.1"
    release: "my-kafka"
    heritage: "Tiller"
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: "zookeeper"
    release: "my-kafka"
```

Duplicate service definition:

```yaml
---
# Source: kafka/charts/zookeeper/templates/service-clients.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-kafka-zookeeper
  labels:
    app: "zookeeper"
    chart: "zookeeper-0.4.4"
    release: "my-kafka"
    heritage: "Tiller"
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: "zookeeper"
    release: "my-kafka"

```
