### ISSUE TITLE
Grafana could not set secret values in a safe way

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [helm/charts#3739]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature

**Version of Helm and Kubernetes**: Any

**Which chart**: Grafana

**What happened**: Actually the chart allows only to set secret values by inserting them in the `grafana.ini` value (that will go in the ConfigMap) or setting them in `extraEnv` value (that will go in cleartext as env vars).

**What you expected to happen**: I Expect to be able to configure secret values using Kubernetes Secrets

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by ebabani** [comment]
This is fixed by https://github.com/kubernetes/charts/pull/3965

You can set env variables from secrets with extraEnv now.

```
  extraEnv:
  - name: GF_AUTH_GITHUB_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: grafana-secret
        key: GF_AUTH_GITHUB_CLIENT_ID
```
