### ISSUE TITLE
mongodb-replicaset fails with auth enabled

### ISSUE THREAD

**Issue by rjain15** [helm/charts#3745]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a BUG

**Version of Helm and Kubernetes**:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

```
```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```
**Which chart**:
mongodb-replicaset

**What happened**:
`              Error: render error in "mongodb-replicaset/templates/mongodb-keyfile-secret.yaml": template: mongodb-replicaset/templates/mongodb-keyfile-secret.yaml:13:33: executing "mongodb-replicaset/templates/mongodb-keyfile-secret.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0`

**What you expected to happen**:

auth to work

**How to reproduce it** (as minimally and precisely as possible):

```
auth:
  enabled: true
  # adminUser: admin
  # adminPassword: paasword
  # key: keycontent
  # existingKeySecret:
  # existingAdminSecret:

```
**Anything else we need to know**:

The documentation on how to enable auth is also sparse, so if we can be more explicit for new users, what is expected in key. I specified existingKeySecret and which I have on my k8s cluster, and it worked. So I am not very sure from the documentation what is expected. Similarly what is the entry for the key file in the configmap section. 

```
# Entries for the MongoDB config file
configmap:
  storage:
    dbPath: /data/db
  net:
    port: 27017
    # Uncomment for TLS support
    # ssl:
    #   mode: requireSSL
    #   CAFile: /ca/tls.crt
    #   PEMKeyFile: /work-dir/mongo.pem
  replication:
    replSetName: rs0
  # Uncomment for TLS support or keyfile access control without TLS
  # security:
  #   authorization: enabled
  #   keyFile: /keydir/key.txt

```
