### ISSUE TITLE
stable/nginx-ingress gives CrashLoopBackOff when installing with vaules.yaml file

### ISSUE THREAD

**Issue by pkelleratwork** [helm/charts#3767]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug 

**Version of Helm and Kubernetes**:
K8s version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}

**Which chart**:
stable/nginx-ingress

**What happened**:
nginx-ingress-controller pod fails to start when deployed using values.yaml file. 

```
NAME                                                   READY     STATUS             RESTARTS   AGE
front-nginx-ingress-controller-6c968cfc54-tvszl        0/1       CrashLoopBackOff   3          1m
```

```
> $ kubectl logs front-nginx-ingress-controller-6c968cfc54-tvszl -n=kube-system
> -------------------------------------------------------------------------------
> NGINX Ingress controller
> unknown flag: --nginx-configmap
> Usage of :
>   Release:    0.10.2
>   Build:      git-fd7253a
>   Repository: https://github.com/kubernetes/ingress-nginx
> -------------------------------------------------------------------------------
```

**What you expected to happen**:
should start pod

**How to reproduce it** (as minimally and precisely as possible):
1.  copy values.yaml, make no changes
2.  $ helm install stable/nginx-ingress --name front -f values.yaml --namespace kube-system

**Anything else we need to know**:

**Comment by kwtalley** [comment]
from what i just saw, the chart has the wrong args for nginx. it's using '--nginx-configmap' when the correct arg is '--configmap'. i just edited the deployment in kubernetes and it fixed it.

**Comment by tuananh** [comment]
@kwtalley this works.

is there a PR for this already?

**Comment by tuananh** [comment]
@egeland could you please take a look at this?

**Comment by kwtalley** [comment]
@tuananh I hadn't created one but i'd be happy to if you'd like

**Comment by egeland** [comment]
Must be a bug in this code:
```
  {{- if (semverCompare ">=0.9.0-beta.1" .Values.controller.image.tag) }}
    - --configmap={{ .Release.Namespace }}/{{ template "nginx-ingress.controller.fullname" . }}
  {{- else }}
    - --nginx-configmap={{ .Release.Namespace }}/{{ template "nginx-ingress.controller.fullname" . }}
  {{- end }}
```

I'm guessing that the `semverCompar` doesn't consider `0.11.0` to be `">=0.9.0-beta.1"`...

**Comment by kwtalley** [comment]
that's the conclusion i came to as well, which is frustratingly common with version string comparison/parsing (likely is comparing 9 to 1 or it could be the 'beta' part). i haven't done a lot with testing helm charts so i need to look that up and see if there's a better way to do the comparison. reason being as i don't want to just EOL any support for <0.9.0-beta.1. thoughts?

**Comment by tuananh** [comment]
yeah, i checked that as well but it seems the code looks correct to me.

**Comment by egeland** [comment]
We can add an additional conditional for `>= 0.9.0` which should, in theory, cover the rest of the versions after the beta...?

**Comment by tuananh** [comment]
will it break for `v0.9.0`? from what i thought, the change was introduced in 0.9.0-beta?

**Comment by egeland** [comment]
Doesn't the `-beta` mean that it's a candidate of the number?

So `0.9.0` is based off the final `0.9.0-beta.x`?

**Comment by unguiculus** [comment]
I use the chart without any problems. Just did a `helm template`. The result is correct.

```
        - name: nginx-ingress-controller
          image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - /nginx-ingress-controller
            - --default-backend-service=default/RELEASE-NAME-nginx-ingress-default-backend
            - --election-id=ingress-controller-leader
            - --ingress-class=nginx
            - --configmap=default/RELEASE-NAME-nginx-ingress-controller
```

**Comment by unguiculus** [comment]
cc @mattfarina

**Comment by ivan4th** [comment]
@unguiculus indeed helm template gives me this when I clone the charts repo locally and run template there:
```
$ helm template nginx-ingress --name ing -f ../../../nginx-ingress-conf.yaml
...
      containers:
        - name: nginx-ingress-controller
          image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - /nginx-ingress-controller
            - --default-backend-service=default/ing-nginx-ingress-default-backend
            - --election-id=ingress-controller-leader
            - --ingress-class=nginx
            - --configmap=default/ing-nginx-ingress-controller
...
```

But 'helm install' for the same chart still gives invalid yaml:
```
$ helm install stable/nginx-ingress --name ing -f nginx-ingress-conf.yaml --debug --dry-run
...
      containers:
        - name: nginx-ingress-controller
          image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - /nginx-ingress-controller
            - --default-backend-service=default/ing-nginx-ingress-default-backend
            - --nginx-configmap=default/ing-nginx-ingress-controller
...
```

**Comment by ivan4th** [comment]
Curiously enough if I package the chart locally, the problem doesn't happen:
```
$ helm package nginx-ingress
$ helm install ./nginx-ingress --name ing -f ../../../nginx-ingress-conf.yaml --debug --dry-run
...
      containers:
        - name: nginx-ingress-controller
          image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - /nginx-ingress-controller
            - --default-backend-service=default/ing-nginx-ingress-default-backend
            - --election-id=ingress-controller-leader
            - --ingress-class=nginx
            - --configmap=default/ing-nginx-ingress-controller
...
```

**Comment by oivindoh** [comment]
helm fetch stable/nginx-ingress --untar
helm template ./nginx-ingress -f ./values-nginx-ingress.yaml

->

```
    spec:
      containers:
        - name: nginx-ingress-controller
          image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - /nginx-ingress-controller
            - --default-backend-service=default/RELEASE-NAME-nginx-ingress-default-backend
            - --nginx-configmap=default/RELEASE-NAME-nginx-ingress-controller
          env:
```

Getting the same behaviour with template as with helm upgrade/install. `controller.tag` = "0.11.0"

Inspecing the actual downloaded chart, however, I see this in the deployment:
```
          {{- if and (contains "0.9" .Values.controller.image.tag) .Values.controller.publishService.enabled }}
            - --publish-service={{ template "nginx-ingress.controller.publishServicePath" . }}
          {{- end }}
          {{- if (contains "0.9" .Values.controller.image.tag) }}
            - --election-id={{ .Values.controller.electionID }}
          {{- end }}
          {{- if (contains "0.9" .Values.controller.image.tag) }}
            - --ingress-class={{ .Values.controller.ingressClass }}
          {{- end }}
          {{- if (contains "0.9" .Values.controller.image.tag) }}
            - --configmap={{ .Release.Namespace }}/{{ template "nginx-ingress.controller.fullname" . }}
          {{- else }}
            - --nginx-configmap={{ .Release.Namespace }}/{{ template "nginx-ingress.controller.fullname" . }}
          {{- end }}
```

The chart version fetched by helm is 0.8.22. Editing to match the semverCompare usage found in master makes the deployments work properly.

Looks like we just need the current code to be released @egeland
