### ISSUE TITLE
nginx doesn't discover service when spec rules are added.

### ISSUE THREAD

**Issue by abelgana** [helm/charts#3862]
Hi Folks,
I am wondering if someone is using ngix-controller. For some reason I am getting
```
master-01 vagrant # kubectl describe ing nginx-demo-ingress
Name:             nginx-demo-ingress
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *
        /nginxdemo   nginxservice:80 (<none>)
Annotations:
  rewrite-target:  /
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  11s   nginx-ingress-controller  Ingress default/nginx-demo-ingress
```
which means my nginx controller has not been able to see my service. Have you ever encountered this problem?

The problem only happens when I have the following config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-demo-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nginxdemo
        backend:
          serviceName: nginxservice
          servicePort: 80 
```

because this configuration works:
``` 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-demo-ingress
spec:
  backend:
    serviceName: nginxservice
    servicePort: 80 
```

```
 master-01 vagrant # kubectl describe ing nginx-demo-ingress
Name:             nginx-demo-ingress
Namespace:        default
Address:
Default backend:  nginxservice:80 (10.233.107.14:80,10.233.107.15:80,10.233.107.16:80)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     nginxservice:80 (10.233.107.14:80,10.233.107.15:80,10.233.107.16:80)
Annotations:
Events:
  Type    Reason  Age              From                      Message
  ----    ------  ----             ----                      -------
  Normal  CREATE  4m               nginx-ingress-controller  Ingress default/nginx-demo-ingress
  Normal  UPDATE  2s (x2 over 4m)  nginx-ingress-controller  Ingress default/nginx-demo-ingress
```
