### ISSUE TITLE
RabbitMQ HA Chart Persistence Issue

### ISSUE THREAD

**Issue by iherbmatt** [helm/charts#3914]
**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

**Which chart**:
rabbitmq-ha

**What happened**:
When I generate a cluster it works well, with the exception of persistence. RabbitMQ, if I'm not mistaken, requires the hostname to be equivalent in order for Mnesia to retrieve the appropriate data and restore it to the RabbitMQ server. Unfortunately, when the hostname is rabbit@[POD IP], and the IP is constantly changing, if a RabbitMQ pod belonging to the statefulset were to be restarted, it will start with 0 data. As a result, queue data is lost upon startup. Upon inspection of the pod's mnesia folder I found 3 different sets of folders (one for each restart).

**What you expected to happen**:
I expected that queue data in each pod is persisted to the same place for mnesia to read from, but it's not.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster, once up and running, restart one of the pods and you'll notice it will get a new IP and in the mnesia folder (/var/lib/rabbitmq/mnesia) will show multiple folders for each new rabbit@[POD IP] that is generated upon pod deletion/creation.

**Anything else we need to know**:
Is there a way that we can use actual hostnames without IPs? This will lead to each successive start being stored in the same mnesia folder for restoring purposes (if needed). I've tried to change it to using metadata.name but that breaks the clustering autodiscovery (even if I were to change the cluster_formation.k8s.address_type=hostname). Perhaps I'm missing something here?

Thank you!

Matt

**Comment by alahijani** [comment]
This issue seems relevant:

https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/issues/18

**Comment by bdimcheff** [comment]
and https://groups.google.com/forum/#!searchin/rabbitmq-users/containers%7Csort:date/rabbitmq-users/wuOfzEywHXo/3ld82vKMAgAJ

It looks like maybe `cluster_formation.k8s.hostname_suffix` needs to be defined?

**Comment by alahijani** [comment]
Thanks @bdimcheff that did the trick.

This is the combination that worked:

```
- name: RABBITMQ_USE_LONGNAME
  value: "true"
- name: MY_POD_NAME
  valueFrom:
	fieldRef:
	  apiVersion: v1
	  fieldPath: metadata.name
- name: MY_POD_IP
  valueFrom:
	fieldRef:
	  apiVersion: v1
	  fieldPath: status.podIP
- name: RABBITMQ_NODENAME
  value: rabbit@$(MY_POD_NAME).my-rabbitmq-ha.default.svc.cluster.local
- name: K8S_HOSTNAME_SUFFIX
  value: .my-rabbitmq-ha.default.svc.cluster.local
- name: K8S_SERVICE_NAME
  value: my-rabbitmq-ha
```

I also had to change the service to be headless (`clusterIP: None`) for kube-dns to resolve individual pods. 
The reason it has to be headless is because of https://github.com/kubernetes/kubernetes/issues/39197

Now, can this be integrated back into the chart?
