### ISSUE TITLE
[stable/chronograf] doesn't work with oauth values set

### ISSUE THREAD

**Issue by ryuheechul** [helm/charts#3920]
**Is this a request for help?**:
Nope
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
2.7.2 and 1.8.7

**Which chart**:
stable/chronograf:0.4.2

**What happened**:

changed the value using the file like below to allow oauth

```
oauth:
  enabled: true
  token_secret: "cHrOnograFseCrET"
  google:
    enabled: true
    client_id: client@id
    client_secret: cLiEntSecREt
    public_url: https://public.url.com
    google_domains: domain.com
```

and got the error message like below
`Error: render error in "chronograf/templates/secret.yaml": template: chronograf/templates/secret.yaml:17:48: executing "chronograf/templates/secret.yaml" at <b64enc>: wrong number of args for b64enc: want 1 got 0`

**What you expected to happen**:
should work just fine

**How to reproduce it** (as minimally and precisely as possible):
install the chart with the values.yml file with enabling google auth

**Anything else we need to know**:
Not much
