### ISSUE TITLE
Building an improved Drupal chart with nginx and php-fpm, need some help

### ISSUE THREAD

**Issue by hyperfocus1337** [helm/charts#400]
Hi guys,

I have been busy with building an [improved chart for Drupal](https://github.com/SuperNami/helm-charts) which includes a pod with two containers, namely nginx and php-fpm. It should be almost done, however I'm having an issue which I haven't yet solved. 

I've read the [troubleshooting documentation](https://kubernetes.io/docs/user-guide/debugging-pods-and-replication-controllers/), but I can't quite put my finger on it. Since I only know kubernetes for a couple of weeks, maybe some Kubernetes experts can chime in. The php-fpm container is randomly crashing, this is the log output:

```
kubectl logs --previous quelling-ibis-drupal-1951785962-mbvp7 quelling-ibis-drupal-fpm
[15-Jan-2017 09:29:57] NOTICE: fpm is running, pid 1
[15-Jan-2017 09:29:57] NOTICE: ready to handle connections
127.0.0.1 -  15/Jan/2017:09:30:17 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:30:17 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:30:17 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:30:17 +0000 "GET /core/install.php" 200
::1 -  15/Jan/2017:09:30:27 +0000 "GET /index.php" 302
127.0.0.1 -  15/Jan/2017:09:30:27 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:30:27 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:30:27 +0000 "GET /core/install.php" 200
::1 -  15/Jan/2017:09:30:37 +0000 "GET /index.php" 302
127.0.0.1 -  15/Jan/2017:09:30:37 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:30:37 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:30:37 +0000 "GET /core/install.php" 200
::1 -  15/Jan/2017:09:30:47 +0000 "GET /index.php" 302
127.0.0.1 -  15/Jan/2017:09:30:47 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:30:47 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:30:47 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:30:57 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:30:57 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:30:57 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:30:57 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:07 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:07 +0000 "GET /index.php" 302
127.0.0.1 -  15/Jan/2017:09:31:07 +0000 "GET /core/install.php" 200
::1 -  15/Jan/2017:09:31:07 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:17 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:17 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:17 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:17 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:27 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:27 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:27 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:27 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:37 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:37 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:37 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:37 +0000 "GET /core/install.php" 200
127.0.0.1 -  15/Jan/2017:09:31:47 +0000 "GET /index.php" 302
::1 -  15/Jan/2017:09:31:47 +0000 "GET /index.php" 302
127.0.0.1 -  15/Jan/2017:09:31:47 +0000 "GET /core/install.php" 200
::1 -  15/Jan/2017:09:31:47 +0000 "GET /core/install.php" 200
::1 -  15/Jan/2017:09:31:57 +0000 "GET /index.php" 302
127.0.0.1 -  15/Jan/2017:09:31:57 +0000 "GET /index.php" 302
[15-Jan-2017 09:31:57] NOTICE: Terminating ...
[15-Jan-2017 09:31:57] NOTICE: exiting, bye-bye!
```

After php-fpm is down, nginx responds with some expected errors:
```
2017/01/15 09:52:07 [warn] 8#8: *21 upstream server temporarily disabled while connecting to upstream, client: 10.120.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "10.120.0.13:80"
10.120.0.1 - - [15/Jan/2017:09:52:07 +0000] "GET / HTTP/1.1" 502 537 "-" "Go-http-client/1.1" "-"
2017/01/15 09:52:07 [error] 8#8: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 10.120.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.120.0.13:80"
2017/01/15 09:52:07 [warn] 8#8: *21 upstream server temporarily disabled while connecting to upstream, client: 10.120.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.120.0.13:80"
2017/01/15 09:52:17 [error] 8#8: *24 no live upstreams while connecting to upstream, client: 10.120.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://localhost", host: "10.120.0.13:80"
2017/01/15 09:52:17 [error] 8#8: *25 no live upstreams while connecting to upstream, client: 10.120.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://localhost", host: "10.120.0.13:80"
10.120.0.1 - - [15/Jan/2017:09:52:17 +0000] "GET / HTTP/1.1" 502 537 "-" "Go-http-client/1.1" "-"
10.120.0.1 - - [15/Jan/2017:09:52:17 +0000] "GET / HTTP/1.1" 502 537 "-" "Go-http-client/1.1" "-"
```

If someone can [help me out](https://github.com/SuperNami/helm-charts), it would be greatly appreciated. Once it's working we can commit it to the official repositories.

Thx.

**Comment by andrewhowdencom** [comment]
Looks like its' getting a SIGTERM from Kubernetes. What does the health check look like?

Update: I see you linked it. 
```
      - name: {{ template "fullname" . }}-fpm
        image: "{{ default "drupal" .Values.drupal.image.repository }}:{{ default "8-fpm" .Values.drupal.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.drupal.image.PullPolicy | quote }}
        ports:
        - name: php-fpm
          containerPort: {{ default "9000" .Values.drupal.image.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: php-fpm
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: php-fpm
          initialDelaySeconds: 5
          timeoutSeconds: 1
```

You're running a HTTP health check for PHP-FPM, which is expecting a FastCGI request. You'll need to use the TCP heath check here, or if you're super keen rig up some sort of exec health check that fires a FastCGI request off and checks the response

**Comment by hyperfocus1337** [comment]
I decided to completely delete the health checks on the drupal-fpm container for now to make it stop sending the SIGTERM signals. However when running `kubectl describe pod {NAME}` I'm getting this:

`5m            5s              24      {kubelet gke-cluster-1-default-pool-3a91ae3c-75jz}      spec.containers{interesting-hare-drupal-nginx}  Warning         Unhealthy           Readiness probe failed: Get http://99.99.99.99:80/core/install.php: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

I'm now figuring out the best way to health check the php-fpm container.

Edit:

Implemented it like this, still facing above error.

```
        livenessProbe:
          tcpSocket:
            port: php-fpm
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: php-fpm
          initialDelaySeconds: 120
          timeoutSeconds: 5
```
