### ISSUE TITLE
[stable/consul] Render error when ingress is enabled

### ISSUE THREAD

**Issue by jakub-d** [helm/charts#4103]
**Version of Helm and Kubernetes**:
Helm Version: `v2.8.1`
Kubernetes Version: `v1.9.2`

**Which chart**:
stable/consul

**What happened**:
Deployment fails when ingress feature is enabled.
The error is:
```
Error: render error in "consul/templates/consul.yaml": template: consul/templates/consul.yaml:55:21: executing "consul/templates/consul.yaml" at <{{template "fullname...>: template "fullname" not defined
```

**What you expected to happen**:
Deployment should succeed.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the `stable/consul` chart with the Ingress enabled. My options were:
Deployment is with following parameters:
```
uiIngress:
  enabled: True
  hosts:
    - consul.tarako.io
StorageClass: slow-nfs
```
