### ISSUE TITLE
[stable/influxdb] Generated password can break the installation

### ISSUE THREAD

**Issue by fujexo** [helm/charts#4132]
**Is this a request for help?**:

No, it isn't.

---

**Is this a BUG REPORT or FEATURE REQUEST?**:

Things can break the installation so I call this a bug.

**Version of Helm and Kubernetes**:

I was running the installation in minikube v0.25.0. I'm running kubernetes v1.9.0
helm version:
```
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

**Which chart**:

stable/influxdb 0.8.2

**What happened**:

I wasn't able to install the chart with authentication enabled and creating a default user. I've initially used the following configuration which generates the user password:

``` yaml
setDefaultUser:
  enabled: true
  user:
    username: admin

config:
  admin:
    enabled: true
  http:
    auth_enabled: true
```

I've forced the password to contain a single quote for testing:
``` yaml
setDefaultUser:
  enabled: true
  user:
    username: admin
    password: "test'1234"

config:
  admin:
    enabled: true
  http:
    auth_enabled: true
```

This also breaks the installation of the chart with the following error from the set-auth pod:
```
{"error":"error parsing query: found 1234, expected ; at line 1, char 41"}
```

**What you expected to happen**:

The installation succeeds and I'm able to login into the Influx DB with the generated or set password.

**How to reproduce it** (as minimally and precisely as possible):
``` bash
cat << EOF >> myval.yaml
setDefaultUser:
  enabled: true
  user:
    username: admin
    password: "test'1234"

config:
  admin:
    enabled: true
  http:
    auth_enabled: true
EOF

helm install -f myval.yaml stable/influxdb
```
Then check the logs of the set-auth pod and try to login into influxdb:
```
export INFLUX_RN=<the name of the release>
kubectl logs $(kubectl get pods --namespace default -l job-name=$INFLUX_RN-influxdb-set-auth -o jsonpath='{ .items[0].metadata.name }')
kubectl get secret $INFLUX_RN-influxdb-auth -o yaml | grep password
echo <the password> | base64 -d

kubectl port-forward --namespace default $(kubectl get pods --namespace default -l app=$INFLUX_RN-influxdb -o jsonpath='{ .items[0].metadata.name }') 8086:8086
curl -X POST http://localhost:8086/query -u "admin:<the decoded password>" --data-urlencode "q=SHOW DATABASES"
```

**Anything else we need to know**:

The output of the function randAscii in https://github.com/kubernetes/charts/blob/1a381d1539b8fba7c9037b5eb6afcfa68ae3c162/stable/influxdb/templates/secret.yaml#L15 can contain single quotes which can break the installation.

For example, in stable/grafana, the function randAlphaNum is used instead: https://github.com/kubernetes/charts/blob/1a381d1539b8fba7c9037b5eb6afcfa68ae3c162/stable/grafana/templates/secret.yaml#L15
