### ISSUE TITLE
Prometheus node-exporter fail to pass arguments

### ISSUE THREAD

**Issue by ghost** [helm/charts#4409]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

Hi guys:

Refering to this issues https://github.com/kubernetes/charts/issues/3519 I was unable to start node-exporter with your fix, this time I debug the template and the results are:

Argument in values.yaml

**extraArgs: {collector.mountstats}**

The new logic does not work as expected:

```
{{- range $key, $value := .Values.nodeExporter.extraArgs }}
          {{- if $value }}
            - --{{ $key }}={{ $value }}
          {{- else }}
            - --{{ $key }}
          {{- end }}
          {{- end }}
```
This will generate a template for node-exporter as follow:
```
args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.mountstats=
```
...and **--collector.mountstats=** argument is an invalid argument for node-exporter due to **=** symbol. 

I think that **{{ if $value }}** will check for both "" and nil, and in the case of **collector.mountstats** the **$value** value are "" and then pass the conditional writing in the template  **--collector.mountstats=**

So, this should work:

```
{{- range $key, $value := .Values.nodeExporter.extraArgs }}
          {{- if $value != "" }}
            - --{{ $key }}={{ $value }}
          {{- else }}
            - --{{ $key }}
          {{- end }}
          {{- end }}
```
Please, could you fix it?

@djsly could you route the request to the team please?, like https://github.com/kubernetes/charts/issues/3519

Regards

Felix

**Comment by djsly** [comment]
what is your input? 

We are using this without problems

````
  extraArgs:
    collector.systemd: ""
    collector.textfile.directory: /srv/txt_collector
````

**Comment by ghost** [comment]
Hi @djsly 

extraArgs: {collector.mountstats} in values.yaml

Regards

**Comment by djsly** [comment]
try 
```
 extraArgs:
    collector.mountstats: ""
```

**Comment by ghost** [comment]
Same result:

node_exporter: error: unexpected , try --help

extraArgs:
     collector.mountstats: ""

**Comment by ghost** [comment]
Only for test, please, could yo run this in your cluster?
```
helm install -f values.yaml stable/prometheus --dry-run --debug
```
Download the same values.yaml that appear in the repo, and only change the nodeExporter extraArgs.

**Comment by djsly** [comment]
I get 
```
        - name: prometheus-node-exporter
          image: "<registry>/prom/node-exporter:v0.15.2"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.mountstats
```

with 

```
nodeExporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: True

  # Defines the serviceAccountName to use when `rbac.create=false`
  serviceAccountName: default

  ## node-exporter container name
  ##
  name: node-exporter

  ## node-exporter container image
  ##
  image:
    repository: <registry>/prom/node-exporter
    tag: v0.15.2
    pullPolicy: IfNotPresent

  ## Custom Update Strategy
  ##
  updateStrategy:
    type: OnDelete

  ## Additional node-exporter container arguments
  ##
  extraArgs:
    collector.mountstats: ""

  ## Additional node-exporter hostPath mounts
  ##
  extraHostPathMounts:
    - name: textfile-dir
      mountPath: /srv/txt_collector
      hostPath: /var/lib/node-exporter
      readOnly: true
    - name: system-dbus-socket
      mountPath: /var/run/dbus/system_bus_socket
      hostPath: /var/run/dbus/system_bus_socket
      readOnly: true

  ## Node tolerations for node-exporter scheduling to nodes with taints
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  tolerations: []
  ## Node labels for node-exporter pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  ## Annotations to be added to node-exporter pods
  ##
  podAnnotations: {}

  ## node-exporter resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 50Mi
    # requests:
    #   cpu: 100m
    #   memory: 30Mi

  service:
    annotations:
      prometheus.io/scrape: "true"
    labels: {}

    clusterIP: None

    ## List of IP addresses at which the node-exporter service is available
    ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
    ##
    externalIPs: []

    hostPort: 9100
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    servicePort: 9100
    type: ClusterIP
```
