### ISSUE TITLE
[stable/nginx-ingress] Adding additional volume mounts for ModSecurity configuration

### ISSUE THREAD

**Issue by logicfox** [helm/charts#4417]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

**Which chart**:
stable/nginx-ingress

**What happened**:
I would like to have additional volumes mounted to Nginx for including custom configuration files for ModSecurity rules. Prior to using charts, our deployment included ConfigMaps mounted as volumes under `/etc/nginx/` and `/etc/nginx/modsecurity`like so:

```
volumeMounts:
          - name: modsecurity-config
            mountPath: /etc/nginx/modsecurity/modsecurity.conf
            subPath: modsecurity.conf
          - name: crs-setup-config
            mountPath: /etc/nginx/owasp-modsecurity-crs/crs-setup.conf
            subPath: crs-setup.conf
          - name: crs-exceptions-rules-before-config
            mountPath: /etc/nginx/owasp-modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
            subPath: REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
          - name: crs-exceptions-rules-after-config
            mountPath: /etc/nginx/owasp-modsecurity-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
            subPath: RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
```
However, the Helm chart does not provide an option to mount additional configuration as volumes.

**What you expected to happen**:
Allow additional configuration (configmaps) to be mounted as volumes.

**How to reproduce it** (as minimally and precisely as possible):
Try mounting a configmap as a file under `/etc/nginx/`

**Anything else we need to know**:
