### ISSUE TITLE
[stable/prometheus] alertmanager config map issue

### ISSUE THREAD

**Issue by ghost** [helm/charts#4434]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

Hi all:

After update my helm stable repo **I cant** deploy my prometheus environment due to alertmanager.yml config file.
Before update helm stable repo, I successfully able to deploy my proemtheus environment, but for need about node-exporter to run some collector I update the helm repo and now **I cant deploy alertmanager**:

My alertmanager config are as follow:

```
alertmanagerFiles:
  alertmanager.yml: |-
   route:
     group_by: ['alertname']
     group_wait: 30s
     group_interval: 15m
     receiver: ineco
     repeat_interval: 30m
   receivers:
   - name: bla
     email_configs:
     - to: bla@bla.com
       from: bla@bla.com
       smarthost: bla.bla.com
       auth_username: bla
       auth_password: bla
       send_resolved: true
     webhook_configs:
     - send_resolved: true
       url: http://bla/bla
```

If I put this same config into docker alertmanager container then I can run the alertmanager without problems, but not with helm, the error as follow:

```
time="2018-03-23T09:56:04Z" level=info msg="Loading configuration file" file="/etc/config/alertmanager.yml" source="main.go:195"
time="2018-03-23T09:56:04Z" level=error msg="Loading configuration file failed: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `route:\n...` into config.plain" file="/etc/config/alertmanager.yml" source="main.go:198"
```

The configmap resulting of the config above are:

```
	   Data
====
alertmanager.yml:
----
"route:\n  group_by: ['alertname']\n  group_wait: 30s\n  group_interval: 15m\n  receiver:
  bla\n  repeat_interval: 30m\nreceivers:\n- name: bla\n  email_configs:\n  -
  to: bla@bla.com\n    from: bla@bla.com\n    smarthost: bla.bla.com\n
  \   auth_username: bla         \n    auth_password: bla\n
  \   send_resolved: true\n  webhook_configs:\n  - send_resolved: true\n    url: http://bla/bla"

Events:  <none>

```

Please, could you say me what is wrong in my config file, if this work in a alertmanager docker container with the same image that I have in the chart, but deployed as chart with helm this does not work??

Regards

**Comment by jaksky** [comment]
I am facing the same issue with much simpler configuration.

**Comment by ghost** [comment]
@jaksky remove |- from the line, so, the line should be:
alertmanager.yml:

Prometheus are a great tool, but the documentation suck!!!!, anybody make sense about changes in charts causing a terrible headache when you upgrade your helm repo locally.
Im fighting now with alert rules, my yaml does not like the rules that I was working for a months without problems, now, magically, prometheus dont like my rules!

**Comment by bweston92** [comment]
@felixPG I seem to get the following this once I remove the `|-`

```
Error: release metrics failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap: Data: ReadString: expects " or n, parsing 47 ...ger.yml":{... at {"apiVersion":"v1","data":{"alertmanager.yml":{"global":{"slack_api_url":"[RADECATED]"},"receivers":[{"name":"default-receiver","slack_configs":[{"channel":"alert-notifications","send_resolved":true}]}]}},"kind":"ConfigMap","metadata":{"labels":{"app":"prometheus","chart":"prometheus-5.3.3","component":"alertmanager","heritage":"Tiller","release":"metrics"},"name":"metrics-prometheus-alertmanager","namespace":"default"}}
```

Upon debugging and running manually I get this error:
```
error: error validating "test.yml": error validating data: ValidationError(ConfigMap.data.alertmanager.yml): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by ghost** [comment]
@bweston92 this error **got "map", expected "string"** in my experience means that your yaml does not correctly parsed. Please, verify in yaml that you write the correct value:key mapping, and respect indentation, example:

```
serverFiles:
#rules: {}

   prometheus.yml:
     rule_files:
       - /etc/config/rules
       - /etc/config/alerts

     scrape_configs:
       - job_name: prometheus
         static_configs:
           - targets:
             - localhost:9090
```
Note the identation!

Regards

**Comment by bweston92** [comment]
@felixPG it passed on yamllint and the moment I add ` |-` the end of `prometheus.yml` it works fine.

**Comment by bweston92** [comment]
YAML lint works on the following anyway: (am I doing something wrong?)

```
rbac:
  create: true

pushgateway:
  enabled: false

alertmanager:
  enabled: true
  persistentVolume:
    enabled: false

alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: '[RADECATED]'
    receivers:
    - name: default-receiver
      slack_configs:
      - channel: 'alert-notifications'
        send_resolved: true

server:
  persistentVolume:
    enabled: false

serverFiles:
  alerts:
    groups:
    - name: uptime.rules
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  rules: {}
```

**Comment by ghost** [comment]
try this

```
alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: '[RADECATED]'
    receivers:
      - name: default-receiver
        slack_configs:
        - channel: 'alert-notifications'
          send_resolved: true
```
