### ISSUE TITLE
[stable/prometheus] multi rules configmap yaml

### ISSUE THREAD

**Issue by JustEra** [helm/charts#4440]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
2.8.5

**Which chart**:
stable/prometheus 2.2

**What happened**:
the helm charts values.yaml specify a way to add rules and alerts by filling 

```
serverFiles:
  alerts: {}
```

if you try to specify multiple alert like 

```
serverFiles:
  alerts:  
      - groups:
          - name: xxx.rules
            rules:
            - alert: xxxx
              expr: up{app="xxx"} == 0
              [...]
      - groups:
          - name: xxx.rules
            rules:
            - alert: xxxx
              expr: up{app="xxx"} == 0
              [...]
```
only the first rules will load and ignore all other groups.

I also tried to inject it with the --set command but its converting the alert with a "|-" in the configmap and prometheus does not like it.

**What you expected to happen**:
be able to load multiple alerting rules with different group

**Comment by goshlanguage** [comment]
Are you certain that this isn't a configuration issue? 

It looks like you're redefining groups, instead of populating multiple items in your groups dictionary.
I believe what you would want to do would look like:
```
serverFiles:
  alerts:  
      - groups:
          - name: xxx.rules
            rules:
            - alert: xxxx
              expr: up{app="xxx"} == 0
              [...]
          - name: xxx.rules
            rules:
            - alert: xxxx
              expr: up{app="xxx"} == 0
              [...]
```

Unforunately, as best I can tell from the docs, I only see that rules is a list of alerts so I'm not 100% this will work, but here is that link if it helps at all: 
https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/

If this doesn't work, can you provide a workable, reproducible example?

**Comment by JustEra** [comment]
@RyanHartje this would only work if you only want a single group, per the docs you can define multiple groups that contains multiple alert rules like defined in https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/

as for the reproducing example, well I dont know the format that would make it working.

**Comment by goshlanguage** [comment]
I don't specifically see multiple instances of the groups variable in any supporting documentation. Have you found that specifically somewhere that you can share?

Is there any way you can make your configuration generic and share it so that I can deploy it locally to replicate it? That might help myself and others to troubleshoot this with you.

**Comment by JustEra** [comment]
The main issue seems that when I inject with the --set in helm the configmap will look like this : 

```
|-
        groups:
          - name: xxx.rules
            rules:
            - alert: xxxx
              expr: up{app="xxx"} == 0
              [...]
``` 

notice the `|-` if I remove it manually then the configmap is read correctly and successfully. 

I see that on the template you are hardcoding this addition of `-` 

Many issue ticket are talking about this since 2.2
