### ISSUE TITLE
[stable/percona-xtradb-cluster] re-creation of a cluster with existing persistent volumes fails

### ISSUE THREAD

**Issue by skriss** [helm/charts#4465]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

Kubernetes v1.9.2
Helm v2.8.2

**Which chart**:

stable/percona-xtradb-cluster

**What happened**:

Install the chart, using persistent storage.
Write some data to the database.
Delete the StatefulSet.
Recreate the StatefulSet.
The first pod enters a CrashLoop due to [safe-to-bootstrap protection](http://galeracluster.com/documentation-webpages/restartingcluster.html#safe-to-bootstrap-protection)
Manually edit the `grastate.dat` file within the volume mounted by the first node, and set `safe_to_bootstrap` to 1.
The StatefulSet properly gets created.

**What you expected to happen**:
Given that Kubernetes StatefulSets provide guarantees around the ordering of deletion of pods, I would expect that on a re-create, the SS should be able to properly start and bootstrap from the first pod.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else we need to know**:

**Comment by skriss** [comment]
cc @stephenlawrence

**Comment by dmitryzykov** [comment]
I'm using this job to edit `grastate.dat`. PXC cluster should be stopped first. Use proper claim name inside.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: safe-to-bootstrap
spec:
  template:
    spec:
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pxc-0
      containers:
      - name: safe-to-bootstrap
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - sed
          - -i 
          - "s|safe_to_bootstrap.*:.*|safe_to_bootstrap:1|1"
          - /var/lib/mysql/grastate.dat
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      restartPolicy: OnFailure
```
