### ISSUE TITLE
[stable/traefik] Do not expose metrics on service type loadbalancer

### ISSUE THREAD

**Issue by ajaegle** [helm/charts#4473]
**Is this a request for help?**:

NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.8.2
Kubernetes Client v1.9.5
Kubernetes Server v1.9.4-gke.1

**Which chart**:
stable/traefik:1.25.2

**What happened**:
Activating prometheus metrics (or other metrics) adds another `ports` section to the service of type LoadBalancer. See here: https://github.com/kubernetes/charts/blob/86e1f83ab1b0824d64cc52242422572a362facca/stable/traefik/templates/service.yaml#L50-L54
In a cloud environment this leads to the creation of another public port (8080) on the load balancer provided by e.g. GCP, so that the whole world can access the metrics publicly.

**What you expected to happen**:
Metrics should not be publicly accessible - I want to access them either directly from inside the cluster or via their own dashboard ingress so that the ingress can be authorized with basic auth or client certificate.

**How to reproduce it** (as minimally and precisely as possible):
Install the chart with the following values file:

```
rbac:
  enabled: true

loadBalancerIP: 'so.me.ip.here'

dashboard:
  enabled: true
  domain: dummy.domain
  ingress:
    annotations:
      kubernetes.io/ingress.class: "traefik"

metrics:
  prometheus:
    enabled: true
```

Access `so.me.ip.here:8080/metrics` and see the metrics.

**Anything else we need to know**:
Please let me know if I can assist.
