### ISSUE TITLE
incubator/zookeeper: do not use gcr.io/google-samples images

### ISSUE THREAD

**Issue by ahmetb** [helm/charts#4540]
incubator/zookeeper sample is using `gcr.io/google_samples/k8szk:v2` image:

https://github.com/kubernetes/charts/blob/a7e0c197407204843f5a2fd098fbab88009926c1/incubator/zookeeper/templates/statefulset.yaml#L39

Please do not use this image.

Images in `gcr.io/google-samples` are:

- meant to be used only in GKE tutorials and samples
- not patched/rebuilt actively with security fixes etc
- not actively maintained in general
- should not be used for production purposes
- there no guarantees whether they simply won't be deleted tomorrow.

Please refrain from using `gcr.io/google-samples` images in production.

**Comment by abraithwaite** [comment]
incubator zookeeper is still using the sample image

**Comment by alokrajiv** [comment]
Is there any update on this? We were deploying Kafka and found the zookeeper (a dependency) was using this image. Would like to know if there is a plan to fix this issue?

**Comment by abraithwaite** [comment]
FWIW we found a bug in the image:

```
-    echo "autopurge.purgeInteval=$ZK_PURGE_INTERVAL" >> $ZK_CONFIG_FILE
+    echo "autopurge.purgeInterval=$ZK_PURGE_INTERVAL" >> $ZK_CONFIG_FILE
```

(We reverse engineered  the image for our own internal use).

**Comment by stevie-** [comment]
@abraithwaite We also ran into the bug of zkGenConfig.sh in sample image. 
Are you able to provide us the Dockerfile or reference so we can build a new image?

**Comment by MartinX3** [comment]
@stevie-
https://github.com/helm/charts/pull/11343

**Comment by stevie-** [comment]
Thanks @MartinX3 ,

we use another workaround, but better use the official zookeeper images

`helm chart values-zk-fix.yaml`
```yaml
zookeeper:
  command:
    - /bin/bash
    - -xec
    - zkGenConfig.sh && sed -i 's/autopurge.purgeInteval/autopurge.purgeInterval/' /usr/etc/zookeeper/zoo.cfg && exec zkServer.sh start-foreground
```
