### ISSUE TITLE
[stable/nginx-ingress] 0.12.2 externalTrafficPolicy not applied

### ISSUE THREAD

**Issue by thomascooper** [helm/charts#4572]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm version
Client: v2.8.2
Server: v2.8.0

kubectl version
Client Version: v1.9.5
Server Version: v1.9.4-gke.1

**Which chart**:
stable/nginx-ingress: 0.12.2

**What happened**:
When setting controller.service.externalTrafficPolicy = Local, the service spec.externalTrafficPolicy is still defaulted to "Cluster"

**What you expected to happen**:
the service spec.externalTrafficPolicy is should be "Local"

**How to reproduce it** (as minimally and precisely as possible):
Create config file (updating loadBalancerIP and Source Range to appropriate values): 
```
# /tmp/values.yml
rbac:
  create: true
controller:
  ingressClass: nginx-static-find-jobs
  replicaCount: 2
  config:
    http-redirect-code: "301"
    body-size: "64m"
    server-name-hash-bucket-size: "256"
    large-client-header-buffers: "8 32k"
  stats:
    enabled: true
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: x.x.x.x
    loadBalancerSourceRanges:
      - 10.0.0.0/8
```

`helm install --name {{ ingress.name }} nginx-ingress --namespace=stage -f /tmp/values.yml`

**Anything else we need to know**:
Running on Google Cloud GKE
