### ISSUE TITLE
Adding custom keycloak theme for chart

### ISSUE THREAD

**Issue by Flowkap** [helm/charts#4633]
FEATURE REQUEST

I think we need the possibility to add a configurable PVC in order to be able to provide custom keyloack themes to the deployments. 

At least I don't know a better way for providing a custom theme. Don't want to build a custom keycloak image in order to do so. :/
 
**Which chart**:

Keycloak

**What happened**:

Theme not configurable as theres no optional mount point in the chart

**Comment by unguiculus** [comment]
Coud you check out #5372 and see if this suits your needs?

**Comment by clkao** [comment]
@unguiculus thanks for making it possible to have extra volumes. Providing the theme directory as volume seems still tricky though. Apart from manually creating the volume and cp, there should be an easier way to configure through helm from a local directory.  sadly configmap can't be recursive.

**Comment by unguiculus** [comment]
I'll try and look into this. Will need it myself.

**Comment by Flowkap** [comment]
We actually switched to a custom derived theme as suggested by keycloak for the time being as setting up volumes is too much effort for us in comparison. Recursive configmaps would be perfect..

**Comment by unguiculus** [comment]
@Flowkap Could you provide more details on your current solution? Also, I'm not sure what you mean by "recursive configmaps."

**Comment by unguiculus** [comment]
I played around with this and have a solution using an init container as theme provider. The statefulset gets an option to specify arbitrary init containers. The theme has to be packaged up into a Docker image.

**Dockerfile**
```
FROM busybox
COPY my_theme /my_theme
```

**Custom values.yaml**
```yaml
keycloak:
  extraInitContainers:
    - name: theme-provider
      image: myuser/mytheme:1
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /mytheme/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme

  extraVolumeMounts:
    - name: theme
      mountPath: /opt/jboss/keycloak/themes/mytheme

  extraVolumes:
    - name: theme
      emptyDir: {}
```

I'll create a PR for this. Feedback welcome.

**Comment by Flowkap** [comment]
Looks good on first glance. Didn't know that was possible. This would be actual a perfect fit for a lot of complex but static files on kubernetes as it does not need a PV. I will check that after my holiday :)

**Comment by Vetnametz** [comment]
Hi, thx for this ability, but how I can pass pullSecrets or imagePullSecrets if my theme image under private repo?
I have tried:
```
extraInitContainers: |
    - name: theme-provider
      image: myuser/mytheme:1
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - docker-secret
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /mytheme/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme 
```
or
```
extraInitContainers: |
    - name: theme-provider
      image: 
        ......
        pullSecrets:
          - docker-secret
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /mytheme/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme 
```
and no luck

**Comment by ravikumar1907** [comment]
This fix is not working for me. I can see only empty mounted directory in container even though I've populated some files in init container.

**Comment by bentatham** [comment]
I tried using this example (to [mount providers instead of themes](https://github.com/aerogear/keycloak-metrics-spi/issues/34#issuecomment-505605521)), but I think I have a permissions problem so keycloak doesn't see my jars.  The directory that is mounted has permissions `root jboss` instead of `jboss root` like the others:
```
[jboss@keycloak-id-dev-0 keycloak]$ ls -l /opt/jboss/keycloak/
total 528
drwxrwx--x 3 jboss root    4096 Apr 23 14:09 bin
drwxrwxr-x 7 jboss root      92 Apr 23 14:09 docs
drwxrwx--x 5 jboss root      50 Apr 17 06:24 domain
-rw-rw-r-- 1 jboss root  488551 Apr 17 06:24 jboss-modules.jar
-rw-rw-r-- 1 jboss root   10637 Apr 17 06:24 License.html
-rw-rw-r-- 1 jboss root   26530 Apr 17 06:24 LICENSE.txt
drwxrwxr-x 3 jboss root      39 Apr 23 14:09 modules
drwxrwsrwx 2 root  jboss     44 Jun 25 19:56 providers
drwxrwx--x 1 jboss root      61 Apr 23 14:09 standalone
drwxrwxr-x 5 jboss root      76 Apr 23 14:08 themes
-rw-rw-r-- 1 jboss root      25 Mar  4 07:16 version.txt
drwxrwxr-x 2 jboss root      42 Apr 23 14:09 welcome-content
```

Any idea how to fix that using the instructions above?  
(Note I am now using codecentric/keycloak chart 4.16.0)

**Comment by mboret** [comment]
@bentatham 

You can solve the permissions issue by using this config:

```
extraInitContainers: |
    - name: theme-provider
      image: gcr.io/my-project/keycloak-my-theme:v0.1.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "20m"
          memory: "64Mi"
        requests:
          cpu: "10m"
          memory: "32Mi"
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying My theme..."
          cp -R /my-theme/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme

  ## Custom script that is run before Keycloak is started.
  preStartScript: mkdir -p /opt/jboss/keycloak/themes/my-theme && cp -R /theme/* /opt/jboss/keycloak/themes/my-theme/ 


  extraVolumes: |
    - name: theme
      mountPath: /theme

  extraVolumeMounts: |
    - name: theme
      mountPath: /theme
      emptyDir: {}
```

My Dockerfile contains only:

```
FROM alpine:latest

COPY my-theme /my-theme
CMD ["sh"]
```

Hope this helps.
