### ISSUE TITLE
[stable/mongodb-replicaset] How to install a previous version of mongodb (e.g. 3.2)

### ISSUE THREAD

**Issue by kgujral** [helm/charts#4667]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm - 2.8.2
kubectl - 1.9.3

**Which chart**:
stable/mongodb-replicaset

**What happened**:
Unable to install a lower version (3.2) of mongodb replicaset.

**What you expected to happen**:
mongodb 3.2 replicaset should work like the latest one does.

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --name mongo stable/mongodb-replicaset --set persistentVolume.size=30Gi,image.tag=3.2,installImage.tag=0.3,installImage.name=gcr.io/google_containers/mongodb-install

helm install --name mongo stable/mongodb-replicaset --set persistentVolume.size=30Gi,image.tag=3.2

helm install --name mongo stable/mongodb-replicaset --set persistentVolume.size=30Gi,image.tag=3.2,installImage.tag=0.3


helm install --name mongo stable/mongodb-replicaset --set persistentVolume.size=30Gi,image.tag=3.2,installImage.tag=0.4
```

Tried all of the above commands but the first pod is always stuck at Init 2/4 and never initializes.

**Anything else we need to know**:

**Comment by erkez** [comment]
I noticed the same behavior using the latest 3.1.0 chart, but also when using MongoDB 3.4.

```
containerStatuses:
    - image: mongo:3.4
      imageID: ""
      lastState: {}
      name: mongodb-replicaset
      ready: false
      restartCount: 0
      state:
        waiting:
          reason: PodInitializing
    hostIP: 10.240.0.86
    initContainerStatuses:
    - containerID: docker://faf17efd6cd01c44acf65a2b7160e16f1544d1b35ad0dc60706a5f897db85a0c
      image: busybox:latest
      imageID: docker-pullable://busybox@sha256:186694df7e479d2b8bf075d9e1b1d7a884c6de60470006d572350573bfa6dcd2
      lastState: {}
      name: copy-config
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: docker://faf17efd6cd01c44acf65a2b7160e16f1544d1b35ad0dc60706a5f897db85a0c
          exitCode: 0
          finishedAt: 2018-04-12T14:26:58Z
          reason: Completed
          startedAt: 2018-04-12T14:26:58Z
    - containerID: docker://2b606fbd9db8cd20f366a0950187a8150652f0adfb4dd92b72fb30580c79a040
      image: k8s.gcr.io/mongodb-install:0.6
      imageID: docker-pullable://k8s.gcr.io/mongodb-install@sha256:869527d538d2428071008956dea45ef7b94326b62c8e07f099aff45c38e2292a
      lastState: {}
      name: install
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: docker://2b606fbd9db8cd20f366a0950187a8150652f0adfb4dd92b72fb30580c79a040
          exitCode: 0
          finishedAt: 2018-04-12T14:26:59Z
          reason: Completed
          startedAt: 2018-04-12T14:26:59Z
    - containerID: docker://f21c54582c1cb964bf4aaa1ab8008d7ef0e092c3d8ed0f4ef79cbf983b464b65
      image: mongo:3.4
      imageID: docker-pullable://mongo@sha256:cb4bc171143d4ad8eda5032ccb04a55f1cb48b5cb71833b455d5dd5a382b6b2e
      lastState: {}
      name: bootstrap
      ready: false
      restartCount: 0
      state:
        running:
          startedAt: 2018-04-12T14:27:05Z
    - image: busybox
      imageID: ""
      lastState: {}
      name: permissions
      ready: false
      restartCount: 0
      state:
        waiting:
          reason: PodInitializing
    phase: Pending
```

It is not possible to extract logs from the pod, because it is in initialization state.

`Error from server (BadRequest): container "mongodb-replicaset" in pod "landscapes-db-mongodb-replicaset-0" is waiting to start: PodInitializing`

**Comment by unguiculus** [comment]
Did you check the logs of the bootstrap init container? Also, this container writes a log file to `/work-dir/log.txt`.

**Comment by erkez** [comment]
So, I found out that version 2.3.0 broke the installation with previous MongoDB versions, e.g. 3.4.

I still don't exactly understand the reason for the problem, but if you remove `configmap.net.bindIpAll` it works. Even when setting that option to `false` it does not initialize.

The logs for `bootstrap` init container don't go past the following:

```
2018/04/13 06:54:04 Peer list updated
was []
now [landscapes-db-mongodb-replicaset-0.landscapes-db-mongodb-replicaset.landscapes.svc.cluster.local]
2018/04/13 06:54:04 execing: /work-dir/on-start.sh with stdin: landscapes-db-mongodb-replicaset-0.landscapes-db-mongodb-replicaset.landscapes.svc.cluster.local
```

As a workaround for people trying to use the chart with older MongoDB versions, use: 

`helm install ... --version 2.2.1`

Another option is to modify the configmap by removing `bindIpAll` and restart the pod.

**Comment by erkez** [comment]
Now to the latest chart version, the problem also happens because of bind all IP flag. To make it work with older versions of mongo, we need to remove it from the init script (`init/on-start.sh`) and from the container args `- --bind_ip_all`.

**Comment by lfaoro** [comment]
are we removing the flag or not?

**Comment by lfaoro** [comment]
guys, do you know if the `--bind_ip_all ` flag is really essential for the correct functionality of MongoDB in a container?

If we can just get rid of it and restore compatibility with older version, it would be great.

I'll submit a PR

**Comment by erkez** [comment]
@lfaoro I haven't tried it yet, but by removing this flag, the DBs will most likely not work properly in a replica set. As I have stated before, this flag was added on version 2.3.0, by someone who probably tried running with 3.6 and not the older versions :smile: 

Starting with 3.6, the default IP binding is localhost. We probably need to get the IP from the pod and try to use the `net.bindIp` setting.

Something like:

```
env:
- name: POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
```

https://docs.mongodb.com/v3.6/reference/configuration-options/#net.bindIp
