### ISSUE TITLE
Feature Request: jenkins chart svc type of LoadBalancer option for additional jenkins-internal svc of type ClusterIP

### ISSUE THREAD

**Issue by GeoffMillerAZ** [helm/charts#4710]
# Problem:
Currently it seems that you have to choose 1 service type for the master. If you choose `LoadBalancer` type you are generally exposing your jenkins service through something external to the k8s cluster and often the internet. Now your `JENKINS_URL` is going to be going through the load balancer that is external to the cluster. But for things like using Kubernetes slave agents with the kubernetes plugin, it would be nice to have a service available that was only internal to the cluster of type `ClusterIP`. But currently you have to choose between having a type `LoadBalancer` or having a type `ClusterIP`.

# Solution
If the type is set to `LoadBalancer`, have additional values options that flag if you want an internal service as well. I think this can be as simple as a true/false but you'll likely want additional parameters so people can control ports and what not.

I solved my problem with wanting to use jenkins slaves using an internal DNS with the following:

```
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: 2018-04-03T00:00:54Z
  labels:
    app: jenkins
    chart: jenkins-0.14.3
    component: jenkins-jenkins-master
    heritage: Tiller
    release: jenkins
  name: jenkins-internal
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: jenkins-jenkins-master

```

I was then able to set `JENKINS_URL` to `http://jenkins-internal:8080`

It would be nice if the helm chart itself would solve this and I didn't have to add additional resources after. Fairly new to helm so I may be missing something.
