### ISSUE TITLE
[stable/sonarqube] changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh': Read-only file system

### ISSUE THREAD

**Issue by shuraa** [helm/charts#4787]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.8.2 Kubernetes 1.9.6

**Which chart**: sonarqube-0.3.6

**What happened**: sonarqube pod fails with the message ``chown: changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh': Read-only file system``

```
NAME                                  READY     STATUS             RESTARTS   AGE       IP              NODE
sonarqube-sonarqube-6c8c666d7-bhcq8   0/1       CrashLoopBackOff   3          1m        10.233.65.157   kub02

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE       SELECTOR
sonarqube-postgresql   ClusterIP   10.233.60.130   <none>        5432/TCP   1m        app=sonarqube-postgresql
sonarqube-sonarqube    ClusterIP   10.233.9.11     <none>        9000/TCP   1m        app=sonarqube,release=sonarqube

NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS             IMAGES            SELECTOR
sonarqube-postgresql   1         1         1            1           1m        sonarqube-postgresql   postgres:9.6.8    app=sonarqube-postgresql
sonarqube-sonarqube    1         1         1            0           1m        sonarqube              sonarqube:6.7.2   app=sonarqube,release=sonarqube

NAME                            DESIRED   CURRENT   READY     AGE       CONTAINERS   IMAGES            SELECTOR
sonarqube-sonarqube-6c8c666d7   1         1         0         1m        sonarqube    sonarqube:6.7.2   app=sonarqube,pod-template-hash=274722283,release=sonarqube

NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS             IMAGES            SELECTOR
sonarqube-postgresql   1         1         1            1           1m        sonarqube-postgresql   postgres:9.6.8    app=sonarqube-postgresql
sonarqube-sonarqube    1         1         1            0           1m        sonarqube              sonarqube:6.7.2   app=sonarqube,release=sonarqube

NAME                            DESIRED   CURRENT   READY     AGE       CONTAINERS   IMAGES            SELECTOR
sonarqube-sonarqube-6c8c666d7   1         1         0         1m        sonarqube    sonarqube:6.7.2   app=sonarqube,pod-template-hash=274722283,release=sonarqube
```

**What you expected to happen**: sonarqube pod has to up and running

**How to reproduce it** (as minimally and precisely as possible):

``helm install -n sonarqube --namespace sonarqube -f values.yaml stable/sonarqube``

values.yaml
```yaml
---
image:
  repository: sonarqube
  tag: 6.7.2

service:
  name: sonarqube
  type: ClusterIP
  externalPort: 9000
  internalPort: 9000

ingress:
  enabled: false

persistence:
  enabled: false

postgresql:
  imageTag: "9.6.8"
  postgresUser: "sonarqube"
  postgresPassword: "sonarqube"
  postgresDatabase: "sonarqube"
  persistence:
    enabled: false
```

**Anything else we need to know**: Nope

**Comment by unguiculus** [comment]
cc @rjkernick

**Comment by shuraa** [comment]
Got the same issue with the chart **sonarqube-0.3.8**

```
chown: changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh/..data': Read-only file system
chown: changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh/install_plugins.sh': Read-only file system
chown: changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh/..2018_04_14_15_44_26.361580349/install_plugins.sh': Read-only file system
chown: changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh/..2018_04_14_15_44_26.361580349': Read-only file system
chown: changing ownership of '/opt/sonarqube/extensions/plugins/install_plugins.sh': Read-only file system
```

And the `values.yaml` file

```yaml
image:
  tag: 6.7.2

service:
  type: ClusterIP

postgresql:
  persistence:
    enabled: false
```
