### ISSUE TITLE
[stable/concourse] BUG workers keep restarting after failing to reach TSA

### ISSUE THREAD

**Issue by razvan-moj-zz** [helm/charts#4812]
**Version of Helm and Kubernetes**:
helm 2.8.2, k8s 1.8.6

**Which chart**:
stable/concourse

**What happened**:
Deployment successful, but web interface reports 'no workers' and indeed the worker containers keep restarting after error 137

**What you expected to happen**:
concourse-worker-* containers up, pipelines running

**How to reproduce it** (as minimally and precisely as possible):
helm install --namespace development --name concourse -f values.yaml stable/concourse
ingress enabled, type ClusterIP
atcPort and tsaPort are defined and forwarded back correctly
worker containers exit with 'failed to connect to TSA: dial tcp: address concourse-web: missing port in address'

**Anything else we need to know**:
other charts, of varied complexity, do deploy correctly onto the same cluster

**Comment by brunoban** [comment]
I can confirm this. 

You can get it to work by editing the statefulset's `CONCOURSE_TSA_HOST` to be `hostname:port` instead of just hostname.

Seems to come from this line, on `charts/stable/concourse/templates/worker-statefulset.yaml:79`:

```
          env:
            - name: CONCOURSE_TSA_HOST
          {{- if semverCompare "^3.10" .Values.imageTag }}
              value: "{{ template "concourse.web.fullname" . }}:{{ .Values.concourse.tsaPort}}"
          {{- else }}
              value: {{ template "concourse.web.fullname" . }}
            - name: CONCOURSE_TSA_PORT
              value: {{ .Values.concourse.tsaPort | quote }}
```

Not sure of why the cutout is exactly at 3.10, or if just readjusting it is the proper way to solve this.
