### ISSUE TITLE
automated deploy of grafana chart takes a long time

### ISSUE THREAD

**Issue by oldluke92** [helm/charts#4868]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:  
Helm version:  
Client: v2.8.1  
Server: v2.8.1  

Kubernetes version: v1.9.0

**Which chart**: 

stable/grafana v0.8.5

**What happened**:  

Installing the chart using another script blocks this script for a relatively long time as helm waits for the set-datasource job to complete. The pod generated by the set-datasource job will fail multiple times while waiting for `http://$(ADMIN_USER):$(ADMIN_PASSWORD)@monitoring-grafana:80/api/datasources` to become available. Sometimes even the job will fail because the default Deadline of 300 Seconds is reached. (I know, I can change that one and I will - if the script doesn't have to wait that even longer time to proceed)

**What you expected to happen**:

I expected Helm to start the job, continue and ingore the outcome of that job.

**How to reproduce it** (as minimally and precisely as possible):

Use a script to deploy the chart (and do other stuff afterwards) and enable setDatasource. We are using influxdb and telegraf - not sure if this matters.

```yml
setDatasource:
    enabled: true
    activeDeadlineSeconds: 300
    image: appropriate/curl:latest
    datasource:
      name: influx
      type: influxdb
      url: http://influx-influxdb:8086
      database: telegraf
      access: proxy
      isDefault: true      
    restartPolicy: OnFailure
```

**Anything else we need to know**:
Mostly happens on dev machines running minikube in a VM.

I tried to find the cause myself and found out that this behaviour is caused by the set-datasource job running as hook. I do however not understand why this is needed.
