### ISSUE TITLE
[stable/prometheus] adding custom scrape_configs seems convoluted

### ISSUE THREAD

**Issue by tuxpiper** [helm/charts#5092]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm v2.8.2
Kubernetes v1.9.6

**Which chart**:
stable/prometheus

**What happened**:
I couldn't find a simple way to add scrape configs. The only functional way I found to do that was to copy the whole contents of serverFiles.prometheus.yml.scrape_configs default over to my values.yaml and then append my scrape configs to that

**What you expected to happen**:
The contents of the prometheus.yml file could be broken in such a way to allow concise addition of content to each of its sections. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I implemented changes in my fork. I'll follow up with a PR

**Comment by monotek** [comment]
same problem here :-/

**Comment by ksiadz** [comment]
Similar problem. I tried both prometheus.yml value and extraScrapeConfigs.

**Comment by bcottinghamae** [comment]
`extraScrapeConfigs` works if I clone this repo and install from a local directory. Maybe the current version just needs to be published?

**Comment by spiffytech** [comment]
`extraScrapeConfigs` works if I clone this repo and install from a local directory. Maybe the current version just needs to be published?

**Comment by wehappyfew** [comment]
Hey @spiffytech !
Could you provide an example? 
I can successfully add extra configs directly from the `values.yml` file of the chart, but when I try to pass it as argument with `--set` nothing happens.
This works:
```
# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config
extraScrapeConfigs: |
  - job_name: 'sample-job'
    scrape_interval: 1s
    metrics_path: /
    kubernetes_sd_configs:
      - role: endpoints
```
this does not:
```
sudo helm upgrade --install prometheus \
--set rbac.create=true \
--set server.persistentVolume.enabled=false \
--set alertmanager.persistentVolume.enabled=false \
--set alertmanager.enabled=false \
--set kubeStateMetrics.enabled=false \
--set nodeExporter.enabled=false \
--set pushgateway.enabled=false \
--set extraScrapeConfigs="|
  - job_name: 'sample-pods'
    scrape_interval: 1s
    metrics_path: /
    kubernetes_sd_configs:
      - role: endpoints
" \
stable/prometheus
```
