### ISSUE TITLE
[stable/prometheus] Allow multiple server replicas for HA setup

### ISSUE THREAD

**Issue by serathius** [helm/charts#5115]
Prometheus HA setup is configuration where you can multiple prometheus servers with same configuration scraping same targets.
It really simple setup and usually it would require just setting `replicaCount` to 2.

Unfortunately it's not possible in current helm chart because it causes deploying 2 servers trying to use same persistent volume claim.
As result one server is deployed, other one is stuck waiting for volume that is already being used.

Proposed solution:
Migrate prometheus server deployment to stateful set and replace PVC with template inside server manifest.

**How to reproduce it**:
helm install stable/prometheus --set server.replicaCount=2

**Anything else we need to know**:
I can help with implementation.

cc @mgoodness

**Comment by serathius** [comment]
cc @mgoodness

**Comment by empyrean987** [comment]
I create the persistent volume claims, before launching prometheus, so the data lives through tearing prometheus down and back up again. This is the only thing I think that you really need to do so data is not lost. But the issue is if we use more than replica count of 1 for HA which is the next step towards redundancy. How do we map the persistent volume claims to the replicas??? 

`````
  persistentVolume:
    ## If true, Prometheus server will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true

    ## Prometheus server data Persistent Volume access modes
    ## Must match those of existing PV or dynamic provisioner
    ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    accessModes:
      - ReadWriteOnce

    ## Prometheus server data Persistent Volume annotations
    ##
    annotations: {}

    ## Prometheus server data Persistent Volume existing claim name
    ## Requires server.persistentVolume.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: "prometheus-1"
`````
