### ISSUE TITLE
[stable/prometheus] upgrade impossible since ClusterIP changes

### ISSUE THREAD

**Issue by vdboor** [helm/charts#5128]
**Is this a BUG REPORT or FEATURE REQUEST?** bug

**Version of Helm and Kubernetes**: 2.8.2, kube 10.0

**Which chart**: stable/prometheus 

**What happened**: upgrade failed from chart version 6.1.2 -> 6.2.1

```
$ helm whatup
...
There is an update available for release prometheus (prometheus)!
Installed version: 6.1.2
Available version: 6.2.1

$ helm upgrade prometheus stable/prometheus
Error: UPGRADE FAILED: Service "prometheus-kube-state-metrics" is invalid: spec.clusterIP: Invalid value: "": field is immutable && Service "prometheus-node-exporter" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**Anything else we need to know**:

This is likely due to the change in https://github.com/kubernetes/charts/commit/1b11ef35d676a95f50baaafb925835e9f309cd1a

my `values.yml` file:

```
alertmanager:
  enabled: true
  nodeSelector:
    purpose: apps
  persistentVolume:
    existingClaim: prometheus-apps
    subPath: alertmanager
  resources:
    requests:
      memory: 22Mi
  ingress:
    enabled: true
    hosts:
    - prometheus-alerts.example.nl
    tls:
    - secretName: example-ssl
      hosts:
      - prometheus-alerts.example.nl
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-realm: "Auth required"
      nginx.ingress.kubernetes.io/auth-secret: sysadmins
nodeExporter:
  # Run on master too
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  resources:
    requests:
      memory: 12Mi
pushgateway:
  resources:
    requests:
      memory: 12Mi
  ingress:
    enabled: true
    hosts:
    - prometheus-push.example.nl
    tls:
    - secretName: example-ssl
      hosts:
      - prometheus-push.example.nl
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-realm: "Auth required"
      nginx.ingress.kubernetes.io/auth-secret: sysadmins
server:
  baseURL: https://prometheus.example.nl/
  nodeSelector:
    purpose: apps
  persistentVolume:
    existingClaim: prometheus-apps
    subPath: server
  resources:
    requests:
      memory: 400Mi
  ingress:
    enabled: true
    hosts:
    - prometheus.example.nl
    tls:
    - secretName: example-ssl
      hosts:
      - prometheus.example.nl
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-realm: "Auth required"
      nginx.ingress.kubernetes.io/auth-secret: sysadmins
networkPolicy:
  enabled: false
```
