### ISSUE TITLE
Advice to produce a nested base64-encoded JSON structure for dockercfg

### ISSUE THREAD

**Issue by gintautassulskus** [helm/charts#5227]
What would be a reasonable approach to generating a dockercfg JSON for the following docker-secret:

```yaml
apiVersion:  v1
kind: Secret
metadata:
  name: docker-secret
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.docker_config}}
```
My main issue is that I am not certain how to base-64-encode a nested structure as the one below and retain a decent level of source code readability. The resulting helm chart should accept only credentials and perform all base 64 encoding automatically. 

`.Values.docker_config` is a base 64 encoded JSON structure:
```json
    {
      "${server}":{
        "username": "${username}",
        "password": "${password}",
        "email": "${email}",
        "auth": "${auth_string}"
      }
    }
```
Where `${}` is a placeholder for either a Maven property or a Helm value; `${auth_string}` is the authentication string, again, base 64 encoded:
```
${username}:${password}
```

So all in all, roughly the steps should be as follows:
1. Inject `${}` values and b64-encode the `auth_string`
2. Inject`${}`  values and b64-encode `docker_config`
3. Inject the end result intothe Secret yaml

A solution need not match the provided data structures.

Thanks!

**Comment by xoen** [comment]
Hello @gintautassulskus I've a similar situation and I found this.
It's a "shame" bot closed this as I imagine is fairly common :)

I haven't found a solution to my specific problem yet (as one of the values in the JSON config is using `.Release.Name`) but I think this may help you.

So, you could have the JSON blob in the values file (as JSON is a subset of YAML), e.g.

```yaml
# values.yaml
jsonConfig: |
    {
        "foo": "bar"
    }
```

And then in the secret you may have something like:

```yaml
# secrets.yaml
data:
    json-config: {{ printf .Values.jsonConfig | b64enc | quote }}
```

Or something like that. It's a bit weird that values contains a JSON and it's kinda error prone depending on chart users but it should work.

I'm still looking for a more elegant solution and something that I can use when part of the JSON needs to be constructed from `.Release.Name` - if I find anything better I'll drop a comment here with my findings (if I remember!).

**Comment by xoen** [comment]
Best solution to the need to interpolate `.Release.Name` I've found so far is to have a `%s` in the value and interpolate in the secret resource before base64-encode it, e.g.

```yaml
# values.yaml
jsonConfig: |
    {
        "foo": "bar",
        "the release name is": "%s"
    }
```
```yaml
# secrets.yaml
data:
    json-config: {{ printf .Values.jsonConfig .Release.Name | b64enc | quote }}
```

But again, this is quite brittle and rely on the user of the helm chart being careful and adding this `%s` marker in the value when installing the helm chart 🤷‍♂️ .
