### ISSUE TITLE
Concourse - One of the two workers fail to start

### ISSUE THREAD

**Issue by vikas027** [helm/charts#5355]
**Version of Helm and Kubernetes**:
Kubernetes 1.9.5
Helm 2.8.1

**Which chart**:
stable/concourse

**What happened**:
I have two K8s nodes provisioned and built exactly through Ansible.

One Concourse worker runs fine, but the other one fails with below error.
```
# kubectl get pods -l app=concourse-worker
NAME                 READY     STATUS             RESTARTS   AGE
concourse-worker-0   0/1       CrashLoopBackOff   820        3d
concourse-worker-1   1/1       Running            2          3d
# 
# kubectl logs --tail=100 concourse-worker-0
{"timestamp":"1525271673.596265316","source":"worker","message":"worker.setup.unpacking","log_level":1,"data":{"session":"1"}}
{"timestamp":"1525271679.114085913","source":"worker","message":"worker.setup.done","log_level":1,"data":{"session":"1"}}
{"timestamp":"1525271679.114521027","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-deployment","session":"2.1.1"}}
{"timestamp":"1525271679.684633970","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-io-release","session":"2.1.2"}}
{"timestamp":"1525271679.930649757","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"bosh-io-stemcell","session":"2.1.3"}}
{"timestamp":"1525271680.343657970","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"cf","session":"2.1.4"}}
{"timestamp":"1525271681.089042187","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"docker-image","session":"2.1.5"}}
{"timestamp":"1525271683.180324554","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"git","session":"2.1.6"}}
{"timestamp":"1525271683.916492939","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"github-release","session":"2.1.7"}}
{"timestamp":"1525271684.460904360","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"hg","session":"2.1.8"}}
{"timestamp":"1525271685.373307943","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"pool","session":"2.1.9"}}
{"timestamp":"1525271686.099325657","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"s3","session":"2.1.10"}}
{"timestamp":"1525271686.663558960","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"semver","session":"2.1.11"}}
{"timestamp":"1525271688.233308554","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"time","session":"2.1.12"}}
{"timestamp":"1525271688.538172245","source":"worker","message":"worker.garden.extract-resources.extract.extracting","log_level":1,"data":{"resource-type":"tracker","session":"2.1.13"}}
{"timestamp":"1525271689.120981932","source":"baggageclaim","message":"baggageclaim.failed-to-set-up-driver","log_level":2,"data":{"error":"overlay driver requires kernel version \u003e= 4.0.0"}}
overlay driver requires kernel version >= 4.0.0
# 
```

**What you expected to happen**:
I was expecting both the workers to be healthy

**How to reproduce it** (as minimally and precisely as possible):
Use similar values while creating a helm chart.
```
# cat /tmp/concourse_helm_values.yml | grep -v '#' | sed '/^$/d'
---
image: concourse/concourse
imageTag: "3.12.0"
imagePullPolicy: IfNotPresent
concourse:
  atcPort: 8080
  tsaPort: 2222
  allowSelfSignedCertificates: false
  authDuration: 6h
  resourceCheckingInterval: 1m
  oldResourceGracePeriod: 5m
  resourceCacheCleanupInterval: 30s
  externalURL: https://concourse.<my-domain>
  baggageclaimDriver: overlay
  containerPlacementStrategy: random
  encryption:
    enabled: false
  basicAuth:
    enabled:
  githubAuth:
    enabled:  true
    organization: vikas027-org
    team: admins
  gitlabAuth:
    enabled: false
  genericOauth:
    enabled: false
web:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
  tolerations: []
  service:
    type: ClusterIP
  ingress:
    enabled: false
  metrics:
    prometheus:
      enabled: false
      port: 9391
worker:
  replicas: 2
  minAvailable: 1
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
  nodeSelector: {}
  tolerations: []
  terminationGracePeriodSeconds: 60
  fatalErrors: |-
    guardian.api.garden-server.create.failed
    baggageclaim.api.volume-server.create-volume-async.failed-to-create
  updateStrategy: RollingUpdate
  podManagementPolicy: Parallel
persistence:
  enabled: true
  worker:
    accessMode: ReadWriteOnce
    size: 20Gi
postgresql:
  enabled: true
  postgresUser: concourse
  postgresPassword: concourse
  postgresDatabase: concourse
  persistence:
    enabled: true
credentialManager:
  kubernetes:
    enabled: true
    teams:
      - main
    keepNamespaces: true
  ssm:
    enabled: false
  vault:
    enabled: false
    pathPrefix: /concourse
rbac:
  create: true
  apiVersion: v1beta1
  webServiceAccountName: default
  workerServiceAccountName: default
secrets:
  create: true
  hostKey: |-
    <private_key>
  hostKeyPub: |-
    <public_key>
  sessionSigningKey: |-
    <private_key>
  workerKey: |-
    <private_key>
  workerKeyPub: |-
    <public_key>
  basicAuthUsername:
  basicAuthPassword:
  githubAuthClientId: <github_client_id>
  githubAuthClientSecret: <github_client_secret_id>
#
```

**Anything else we need to know**:
- I have built the cluster using Kubespray, not sure if that matters. My other helm charts work perfectly though.
- CentOS 7 AMI
- Kernel is 4.16.5-1.el7.elrepo.x86_64
