### ISSUE TITLE
stable/sonatype-nexus can't pass through the proxy

### ISSUE THREAD

**Issue by oz123** [helm/charts#5385]
**Version of Helm and Kubernetes**:
v1.9.2+coreos.0

**Which chart**:
sonatype-nexus-1.1.1

**What happened**:
Since the proxy container was added, I am not able to access nexus. Going to the IP address of the load balancer results in `Internal Server Error`.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
This is my configuration:
```
# configuration for sonatype/nexus
nexus:
   imageTag: 3.6.1
   nodeSelector:
     failure-domain.beta.kubernetes.io/zone: de-nbg6-1b
   serviceType: LoadBalancer

ingress:
  enabled: false

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: default-de-nbg6-1b
  storageSize: 50Gi

nexusBackup:
  #nexusAdminPassword: t0ps3kr3t
  persistence:
    enabled: false
    #storageClass: default-de-nbg6-1b
    #storageSize: 3Gi
```
I deployed with:
helm upgrade -f nexus.yml nude-nexus stable/sonatype-nexus

**Comment by oz123** [comment]
I  believe my problem is due to the fact that I didn't set
```
nexusProxy:
  env:
    nexusDockerHost: container.example.com
    nexusHttpHost: nexus.example.com
```

How ever, at the moment I don't know how to create a redirect from the dns record to the correct IP (which I still don't know because the Pod isn't scheduled before I do helm apply).
I would appreciate any help here.
