### ISSUE TITLE
[stable/kong] weird issue with secrets when deploying (secrets already exist)

### ISSUE THREAD

**Issue by neumachen** [helm/charts#5414]
**Is this a request for help?**: Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
kube:
`1.9.7` (or the latest in GKE)

**Which chart**:
[stable/kong]

**What happened**:
Getting an error of:
```
╰─$ helm install --debug --name=kong --namespace=api-gateway kong
[debug] Created tunnel using local port: '46083'

[debug] SERVER: "127.0.0.1:46083"

[debug] Original chart version: ""
[debug] CHART PATH: /home/kareem/src/github.com/sexybacks/helm-charts/kong

Error: release kong failed: secrets "kong-postgresql" already exists
```

**What you expected to happen**:
Deploy properly

**How to reproduce it** (as minimally and precisely as possible):
`requirements.yaml`
```
dependencies:
  - name: kong
    version: 0.2.6
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 0.11.0
    repository: https://kubernetes-charts.storage.googleapis.com/
```
`values.yaml`
```
kong:
  image:
    repository: kong
    tag: 0.13.1
    pullPolicy: IfNotPresent

  admin:
    useTLS: false
    servicePort: 8001
    containerPort: 8001
    type: NodePort

  proxy:
    useTLS: false
    servicePort: 8000
    containerPort: 8000
    type: NodePort #Options: NodePort, ClusterIP, LoadBalancer
    loadBalancerIP: null #Set this to an IP if you want your LoadBalancer to reuse an existing IP
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "traefik"
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: 100m

  logLevel: debug

  runMigrations: true

  env:
    database: postgres
    pg_database: kong
    pg_user: kong
    pg_password: kong
    pg_host: kong-postgresql.api-gateway.svc.cluster.local

  cassandra:
    enabled: false

  postgresql:
    enabled: false

postgresql:
  image: postgres
  imageTag: "10"
  imagePullPolicy: IfNotPresent
  postgresUser: kong
  postgresPassword: kong
  postgresDatabase: kong
```

**Anything else we need to know**:
