### ISSUE TITLE
[stable/grafana] Add annotation to PVC

### ISSUE THREAD

**Issue by BnMcG** [helm/charts#5417]
**Is this a request for help?**: Yes

**Version of Helm and Kubernetes**: Kubernetes v1.9.0, Helm 2.8.2

**Which chart**: stable/grafana

**What happened**:
I'm trying to add an annotation to the Grafana storage PVC so that I can use GlusterFS on my baremetal cluster for dynamic PVC provisioning. Creating a test PVC works fine, and it seems the key is to add an annotation to the PVC.

I've tried specifying this in the values.yaml file in as many ways as I can think of, and each time I cannot get Helm to add the annotation to the generated PVC. What am I doing wrong?

Here's the relevant section of my values.yaml:

```
persistence:
  enabled: true
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {volume.beta.kubernetes.io/storage-class: "gluster-heketi"}
  # subPath: ""
  # existingClaim:
```

And another format I tried:

```
persistence:
  enabled: true
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations:
    - volume.beta.kubernetes.io/storage-class: "gluster-heketi"
  # subPath: ""
  # existingClaim:
```
I've also tried various combinations of quoting/unquoting the annotation and its value, including:

* Both quoted
* Both unquoted
* Only the value quoted

Here is the output from `kubectl get pvc -o yaml`:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: 2018-05-06T23:18:38Z
    labels:
      app: inky-squid-grafana
      chart: grafana-0.6.1
      component: grafana
      heritage: Tiller
      release: inky-squid
    name: inky-squid-grafana
    namespace: default
    resourceVersion: "12433756"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/inky-squid-grafana
    uid: ce91ebbc-5183-11e8-b6c7-000c29a604a3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
As you might expect, the PVC hangs on "Pending" because a request is never fired off to GlusterFS.

**What you expected to happen**:
An annotated PVC should be created.

**How to reproduce it**:

* Install a GlusterFS cluster 
* Follow GlusterFS guide to setup Gluster storage class
* Follow GlusterFS guide to confirm that a test PVC works
* Attempt to add volume.beta.kubernetes.io/storage-class annotation to stable/grafana values.yaml

**Anything else we might need to know**:

Output of `kubectl get storageclass`:

```
kubectl get storageclass
NAME             PROVISIONER               AGE
gluster-heketi   kubernetes.io/glusterfs   1h
```

**Comment by rjkernick** [comment]
I think the correct overrides are: 

```yaml
persistence:
  enabled: true
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
```

I see the annotation when I do helm template with the overrides from above
```yaml
# Source: grafana/templates/pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: RELEASE-NAME-grafana
  labels:
    app: grafana
    chart: grafana-1.3.0
    release: RELEASE-NAME
    heritage: Tiller
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi

spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: gluster-heketi
```
