### ISSUE TITLE
Whitespace issue in prometheus/server-configmap.yaml

### ISSUE THREAD

**Issue by mdgreenwald** [helm/charts#5425]
---

**Is this a BUG REPORT**

**server-configmap.yaml:**
```yaml
{{- if (empty .Values.server.configMapOverrideName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.server.fullname" . }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.serverFiles }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- if eq $key "prometheus.yml" -}}
{{- if $root.Values.alertmanager.enabled -}}
    alerting:
      alertmanagers:
```

Line 18: ```{{- if $root.Values.alertmanager.enabled -}}```

Should be ```{{ if $root.Values.alertmanager.enabled }}```
So that the whitespace is correct in the configmap once its generated.

**Version of Helm and Kubernetes**:

* Helm 2.9.0
* Kubernetes: 1.9.7

**Which chart**:

* stable/prometheus

**What happened**:

Installed chart with custom values.yaml, prometheus-server gets stuck in a crashloop. When pulling the logs we find that the prometheus.yml is the problem. When we look at that file we find

```yaml
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_namealerting:
      alertmanagers:
      - kubernetes_sd_configs:
```

```bash
level=error ts=2018-05-07T19:04:32.715905167Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/etc/config/prometheus.yml): parsing YAML file /etc/config/prometheus.yml: yaml: line 160: mapping values are not allowed in this context"
```

**What you expected to happen**:
```yaml
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
```

**How to reproduce it** (as minimally and precisely as possible):

enable alertmanager to true and install.

**Anything else we need to know**:
