### ISSUE TITLE
[incubator/elasticsearch/] - no persistent volumes available for this claim and no storage class is set

### ISSUE THREAD

**Issue by IvanBiv** [helm/charts#5437]
values.yaml
```
# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "5.4"

image:
  repository: "centerforopenscience/elasticsearch"
  tag: "5.4"
  pullPolicy: "IfNotPresent"

cluster:
  name: "elasticsearch"
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"

client:
  name: client
  replicas: 2
  serviceType: ClusterIP

## (dict) If specified, apply these annotations to the client service
#  serviceAnnotations:
#    example: client-svc-foo

  heapSize: "512m"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      # memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"

  ## (dict) If specified, apply these annotations to each client Pod
  # podAnnotations:
  #   example: client-foo

master:
  name: master
  exposeHttp: false
  replicas: 3
  heapSize: "512m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "4Gi"
    storageClass: "gluster-heketi"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      # memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"

  ## (dict) If specified, apply these annotations to each master Pod
  # podAnnotations:
  #   example: master-foo

data:
  name: data
  exposeHttp: false
  replicas: 2
  heapSize: "1536m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "100Gi"
    storageClass: "gluster-heketi"
  terminationGracePeriodSeconds: 3600
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      # memory: "2048Mi"
    requests:
      cpu: "25m"
      memory: "1536Mi"

  ## (dict) If specified, apply these annotations to each data Pod
  # podAnnotations:
  #   example: data-foo

## Install Default RBAC roles and bindings
rbac:
  create: false
```
```
kube@server2:/data/glusterfs/data/gluster_volume/helm/elasticsearch$ kubectl describe sc gluster-heketi
Name:                  gluster-heketi
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           kubernetes.io/glusterfs
Parameters:            resturl=http://10.109.6.208:8080,restuser=joe,restuserkey=My Secret Life,volumetype=none
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```
In other PVC work with StorageClass `gluster-heketi`

helm call
`helm install --name elasticsearch1 -f values.yaml incubator/elasticsearch`

Result
```
kube@server2:/data/glusterfs/data/gluster_volume/helm/elasticsearch$ kubectl describe pvc data-elasticsearch1-elasticsearch-master-0
Name:          data-elasticsearch1-elasticsearch-master-0
Namespace:     default
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=elasticsearch
               component=master
               release=elasticsearch1
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type    Reason         Age                 From                         Message
  ----    ------         ----                ----                         -------
  Normal  FailedBinding  50s (x423 over 1h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

```

Where I see the problem: 
`no persistent volumes available for this claim and no storage class is set`
