### ISSUE TITLE
[stable/ghost] Ghost subdirectory support

### ISSUE THREAD

**Issue by BenderV** [helm/charts#5513]
BUG REPORT

**Version of Helm and Kubernetes**:
helm: v2.8.1
Kubernetes: v1.8.8

**Which chart**:
https://github.com/kubernetes/charts/tree/master/stable/ghost

**What happened**:
Tried to install ghost on a subdirectory, but the pod crash (the probe fail)

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
`helm install --set ghostHost='domain.com/blog'  stable/ghost --name blog`

**Anything else we need to know**:

**Comment by juan131** [comment]
Hi @BenderV I was able to reproduce it! The problem is that the readinessProbe defined on the [deployment.yaml](https://github.com/kubernetes/charts/blob/master/stable/ghost/templates/deployment.yaml) is the following:

```
        readinessProbe:
          httpGet:
            path: /ghost
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "ghost.host" . | quote }}
```

It's always expecting the blog to be running at `/ghost`. However, it's running at `/blog` and the probes fail. I'll do a PR to fix it
