### ISSUE TITLE
The DeamonSet gets always created in the kube-system namespace 

### ISSUE THREAD

**Issue by igoratencompass** [helm/charts#5587]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Version of Helm and Kubernetes**:
k8s: 1.9.7
helm: v2.6.2

**Which chart**:
kube2iam

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
```
helm install --debug --dry-run stable/kube2iam --name kube2iam --namespace=enc-system --set host.iptables=true --set rbac.create=true --set host.interface=kube-bridge
```

**Anything else we need to know**:
```
---
# Source: kube2iam/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube2iam
    chart: kube2iam-0.8.7
    heritage: Tiller
    release: kube2iam
  name: kube2iam
---
# Source: kube2iam/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: kube2iam
    chart: kube2iam-0.8.7
    heritage: Tiller
    release: kube2iam
  name: kube2iam
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - list
      - watch
---
# Source: kube2iam/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube2iam
    chart: kube2iam-0.8.7
    heritage: Tiller
    release: kube2iam
  name: kube2iam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube2iam
subjects:
  - kind: ServiceAccount
    name: kube2iam
    namespace: enc-system
---
# Source: kube2iam/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: kube2iam
    chart: kube2iam-0.8.7
    heritage: Tiller
    release: kube2iam
  name: kube2iam
spec:
  template:
    metadata:
      labels:
        app: kube2iam
        release: kube2iam
    spec:
      containers:
        - name: kube2iam
          image: "jtblin/kube2iam:0.10.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --host-interface=kube-bridge
            - --host-ip=$(HOST_IP)
            - --iptables=true
            - --app-port=8181
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8181
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          resources:
            {}
            
          securityContext:
            privileged: true
      hostNetwork: true
      serviceAccountName: kube2iam
      tolerations:
        []
        
  updateStrategy:
    type: OnDelete
```
Notice how the `namespace` is missing from the `ServiceAccount` and the `DaeminSet`.
