### ISSUE TITLE
[stable/prometheus]: impossible to add custom templates to alertmanager via alertmanagerFiles

### ISSUE THREAD

**Issue by hairyhenderson** [helm/charts#5608]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**: 2.9.1, 1.9.6

**Which chart**: stable/prometheus

**What happened**: I attempted to add an alertmanager [notification template file](https://prometheus.io/docs/alerting/notification_examples/) to the `alertmanagerFiles` section, and it was interpreted not as the literal content of a file, but as YAML - this behaviour would've changed in #3777

**What you expected to happen**: The file should've been interpreted as a literal string, as given.

**How to reproduce it** (as minimally and precisely as possible):

- create a file `v.yaml`:
    ```yaml
    alertmanagerFiles:
      alertmanager.yml:
        templates:
          - /etc/config/custom-template.tmpl
      custom-template.tmpl: |
        {{ define "slack.myorg.text" -}}
        https://internal.myorg.net/wiki/alerts/{{ .GroupLabels.app }}/{{ .GroupLabels.alertname }}
        {{- end}}
    ```
- deploy the chart with the values:
    ```console
    $ helm upgrade --install foo stable/prometheus -f v.yaml 
    ...
    ```
- have a look at the ConfigMap created for alertmanager's use:
    ```console
    $ kubectl get configmap foo-prometheus-alertmanager -o yaml                  
    ```
    ```yaml
    apiVersion: v1
    data:
      alertmanager.yml: |
        global: null
        receivers:
        - name: default-receiver
        route:
          group_interval: 5m
          group_wait: 10s
          receiver: default-receiver
          repeat_interval: 3h
        templates:
        - /etc/config/custom-template.tmpl
      custom-template.tmpl: |
        |
          {{ define "slack.myorg.text" -}}
          https://internal.myorg.net/wiki/alerts/{{ .GroupLabels.app }}/{{ .GroupLabels.alertname }}
          {{- end}}
    kind: ConfigMap
    metadata: <a bunch of metadata that's irrelevant>
    ```

The issue is that the `custom-template.tmpl` entry ends up with an extra `|` on the first line.

**Anything else we need to know**:

I think a reasonable solution could be to detect the key name to see if the suffix is `.yaml` or `.yml` (with `hasSuffix`) and only parse it as YAML in that situation. Otherwise leave it as a string.

For now, we're getting around this by duplicating the template content in-line in the alertmanager config, but that's not ideal...
