### ISSUE TITLE
[stable/cert-manager] if dns not reachable issuer pods are not deleted until cluster fails with "Pods unschedulable"

### ISSUE THREAD

**Issue by monotek** [helm/charts#5687]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: Helm 2.9.1  / Kubernetes 1.9.6 / GKE

**Which chart**:  stable/cert-manager version 0.2.10

**What happened**: 
Cert manager tries to issue a certificate via http01 but the dns is not ready. It creates a pod which should respond to the request of the letsencrypt server. Unfortunately this pod never times out and lives forever until a new pod is created which tries to issue the certificate again.

In the end you have hundreds of issuer pods and your cluster reaches "Pods unschedulable" unless auto scaling is activated, which is even worse...

**What you expected to happen**:
Issuer pods have a timeout and are replaced by the new pod if it has to try again.

**How to reproduce it** (as minimally and precisely as possible):
Just create some ingresses where the DNS entries are not using the cluster ip.

Use these values:

```
cert-manager:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 10m
      memory: 64Mi
  ingressShim:
    extraArgs: ['--default-issuer-name=letsencrypt-staging', '--default-issuer-kind=ClusterIssuer']
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 10m
        memory: 64Mi
```

**Anything else we need to know**:
