### ISSUE TITLE
[stable/pachyderm] Error: unable to access kubernetes nodeslist

### ISSUE THREAD

**Issue by minhdanh** [helm/charts#5865]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPOR

**Version of Helm and Kubernetes**:

```
helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: stable/pachyderm

**What happened**:
I got this error message when pachd pod is started:

```
time="2018-06-01T08:58:38Z" level=error msg="unable to access kubernetes nodeslist, Pachyderm will continue to work but it will not be possible to use COEFFICIENT parallelism. error: nodes is forbidden: User "system:serviceaccount:pachyderm:pachyderm" cannot list nodes at the cluster scope"

```

**What you expected to happen**: No such error

**How to reproduce it** (as minimally and precisely as possible):

I installed the chart with my values.yaml file:

```
helm upgrade --install --namespace pachyderm pachyderm stable/pachyderm -f values.yaml
```

values.yaml:

```
## Set default credentials for object store
credentials: "s3"

## S3 endpoint (i.e: Minio server) credentials
s3:
 accessKey: "XXX"
 secretKey: "XXX"
 bucketName: "pachyderm"
 ## The endpoint should be something like: <mydomain>.<subdomain>:<port>
 endpoint: "minio.minio:9000"
 ## For 'true' set the value to 1
 secure: "0"
 ## For 'S3v2' signature, set the value to 1. For 'S3v4', set this value to 0
 signature: "1"

## Set default image settings, resource requests and number of replicas of pachd
pachd:
 replicaCount: 1
 ## Size of pachd's in-memory cache for PFS files. Size is specified in bytes, with allowed SI suffixes (M, K, G, Mi, Ki, Gi, etc).
 pfsCache: 0G
 ## For available images please check: https://hub.docker.com/r/pachyderm/pachd/tags/
 image:
  repository: pachyderm/pachd
  tag: 1.7.3
  pullPolicy: IfNotPresent
 worker:
  repository: pachyderm/worker
  tag: 1.7.3
 resources:
  ## For non-local deployments, 1 cpu and 2G of memory requests are recommended
  requests:
   cpu: 250m
   memory: 512M

## Set default image settings and persistence settings of etcd
etcd:
 ## For available images please check: https://hub.docker.com/r/pachyderm/etcd/tags
 image:
  repository: pachyderm/etcd
  tag: v3.2.7
  pullPolicy: IfNotPresent
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
 persistence:
  enabled: true
  storageClass: "gluster-heketi"
  ## Set default PVC size
  size: 100M
  ## Set default PVC access mode: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessMode: ReadWriteOnce
 resources:
  ## For non-local deployments, 1 cpu and 2G of memory requests are recommended
  requests:
   cpu: 250m
   memory: 256M
```
