### ISSUE TITLE
[stable/coredns] The Kubernetes plugin is configured instead the etcd

### ISSUE THREAD

**Issue by arthur0** [helm/charts#5882]
BUG REPORT

**Version of Helm and Kubernetes**:
- Helm:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
- Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[coredns](https://github.com/kubernetes/charts/tree/master/stable/coredns)

**What happened**:
The Kubernetes plugin is configured instead the etcd 
I'm using the `Values`: 
 ```yaml
image: 
  tag: "1.1.3"
isClusterService: false
serviceType: "NodePort"
rbac: 
  create: true
middleware:
  prometheus:
    enabled: false
  kubernetes:
    enabled: false
  etcd:
    enabled: true
    zones:
    - "example.io"
    endpoint: "http://etcd-cluster-client.default:2379"
```  
The coredns ConfigMap is created with this data:
```
      .:53 {
          cache 30
          errors
          health
          kubernetes cluster.local 10.3.0.0/24
          loadbalance round_robin
          prometheus 0.0.0.0:9153
          proxy . /etc/resolv.conf
      }
```

**What you expected to happen**:
Configure the etcd plugin with a ConfigMap like this:
```
     .:53 {
           cache 30
           errors
           etcd example.io {
             path /skydns
             endpoint http://etcd-cluster-client.default:2379
           }
    }
```

**How to reproduce it** (as minimally and precisely as possible):
`helm install -f Values.yaml  stable/coredns` using the specified `Values` above

**Anything else we need to know**:
The etcd-cluster endpoint is healthy:
```
kubectl run --rm -i --tty fun --image quay.io/coreos/etcd --restart=Never -- /bin/sh
/ # ETCDCTL_API=3 etcdctl --endpoints http://etcd-cluster-client.default:2379 put foo bar
OK
/ # ETCDCTL_API=3 etcdctl --endpoints http://etcd-cluster-client.default:2379 get foo
foo
bar
/ # ETCDCTL_API=3 etcdctl --endpoints http://etcd-cluster-client.default:2379 del foo
1
```
