### ISSUE TITLE
Stable/Spinnaker kubeconfig bug

### ISSUE THREAD

**Issue by chz8494** [helm/charts#5897]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

I believe it's a bug in Spinnaker's Chart

**Version of Helm and Kubernetes**:
Helm 2.9.1, k8s 1.10.2

**Which chart**:
Stable/Spinnaker

**What happened**:
kubeconfig doesn't work properly. 

**What you expected to happen**:
1. Should keep old local profile while adding new arbitrary clusters.(I can make local kubeconfig as another context in secret, but still it's easier to be local with serviceaccount on)
2. Need to be better documented for how to use this feature, it's quite confusing, should we keep all clusters config in one secret and use them as secretKey and call them with context? can I put them in different config?

**How to reproduce it** (as minimally and precisely as possible):
create value file:
```
kubeConfig:
  # Use this when you want to register arbitrary clusters with Spinnaker
  # Upload your ~/kube/.config to a secret
  enabled: true
  secretName: config.prod
  secretKey: config.prod
  # List of contexts from the kubeconfig to make available to Spinnaker
  contexts:
  - admin-kubernetes.tdlab
```

Deploy Helm Spinnaker with -f value file.

**Anything else we need to know**:
Original code in Stable/Spinnaker spinnaker-config.yml
```
    kubernetes:
      enabled: true
      accounts:
        {{- if .Values.kubeConfig.enabled }}
        {{- range $index, $context := .Values.kubeConfig.contexts }}
        - name: {{ $context }}
          kubeconfigFile: /tmp/kube/{{ $.Values.kubeConfig.secretKey }}
          context: {{ $context }}
          dockerRegistries:
          {{- range $index, $account := $.Values.accounts }}
          - accountName: {{ $account.name }}
          {{ end }}
        {{ end }}
        {{- else }}
        - name: local
          serviceAccount: true
          dockerRegistries:
            {{- range $index, $account := .Values.accounts }}
            - accountName: {{ $account.name }}
            {{- end }}
        {{- end }}
    dockerRegistry:
```
