### ISSUE TITLE
cannot make ELB listens on https + set up IAM certificate

### ISSUE THREAD

**Issue by dusansusic** [helm/charts#6020]
**Is this a request for help?**: YES

**Version of Helm and Kubernetes**:
```bash
ubuntu@master:~/charts/incubator/vault$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

ubuntu@master~/charts/incubator/vault$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:
1. jenkins
2. vault

**What happened**:
ignored annotations, the load balancer is not loading certificate and not listening on 443 but 80

**What you expected to happen**:
make elastic load balancer to listen on https and set up certificate

**How to reproduce it** (as minimally and precisely as possible):
put annotations in service:

service:
```yaml
service:
  name: vault
  type: LoadBalancer
  externalPort: 443
  port: 8200
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::YYYYYYYYYYYYY:server-certificate/wildcard.example.com
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
```
