### ISSUE TITLE
Sonarqube Helm Chart mysql hostname not configurable

### ISSUE THREAD

**Issue by MatrixCrawler** [helm/charts#6039]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Client: 2.9.1
Server: 2.9.1
k8s: 1.8.7

**Which chart**:
stable/sonarqube

**What happened**:
Despite configuring an external mysql host the environement variable looks like this:

SONARQUBE_JDBC_URL: jdbc:mysql://cloudservice-sonarqube-mysql:3306/sonarDB?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

**What you expected to happen**:
That my conigured mysql-hostname would be added to the SONARQUBE_JDBC_URL

**How to reproduce it** (as minimally and precisely as possible):
Apply Chart with the following values
```
mysql:
  enabled: false
  mysqlServer: myServer.host
  mysqlUser: sonarQubeUser
  mysqlPassword: sonarQubePassword
```
