### ISSUE TITLE
Unable to install just Promethous exporter with RabbitMQ-HA

### ISSUE THREAD

**Issue by shahbour** [helm/charts#6072]
**Is this a request for help?**:

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
YES
**Version of Helm and Kubernetes**:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Which chart**:
rabbitmq-ha

**What happened**:
When trying to update it failed and then doing fresh install failed as below 

First i was trying to install rabbit-mq with prometheus enable and operator disabled  , it was complaining about monitoring namespace even though i changed that to another namespace in values.yaml
```
(⎈ |production:rabbitmq)➜  rabbitmq git:(master) ✗ helm install -f values.yaml stable/rabbitmq-ha --name rabbitmq --namespace rabbitmq
Error: release rabbitmq failed: namespaces "monitoring" not found
```
Then I tried to disable both exporter and operator and i got the below
```
(⎈ |production:rabbitmq)➜  rabbitmq git:(master) ✗ helm install -f values.yaml stable/rabbitmq-ha --name rabbitmq --namespace rabbitmq
Error: apiVersion "monitoring.coreos.com/v1" in rabbitmq-ha/templates/servicemonitor.yaml is not available
```
 

**What you expected to happen**:
Normal Installation with prometheus enabled

**How to reproduce it** (as minimally and precisely as possible):
Use the below values.yaml

```
## RabbitMQ application credentials
## Ref: http://rabbitmq.com/access-control.html
##
rabbitmqUsername: guest
rabbitmqPassword: lE2hcc1QHz

## RabbitMQ default VirtualHost
## Ref: https://www.rabbitmq.com/vhosts.html
##
rabbitmqVhost: "/"

## Erlang cookie to determine whether different nodes are allowed to communicate with each other
## Ref: https://www.rabbitmq.com/clustering.html
##
rabbitmqErlangCookie: DwPXaRRJkJFPP1Jrd8kREPP3KzxJnaf4

## RabbitMQ Memory high watermark
## Ref: http://www.rabbitmq.com/memory.html
##
rabbitmqMemoryHighWatermark: 512MB

## Set to true to precompile parts of RabbitMQ with HiPE, a just-in-time
## compiler for Erlang. This will increase server throughput at the cost of
## increased startup time. You might see 20-50% better performance at the cost
## of a few minutes delay at startup.
rabbitmqHipeCompile: true

## Number of replicas
replicaCount: 2

image:
  repository: docker-registry.xxxxxxx.com:5000/rabbitmq
  tag: 3.7-management-delayed
  pullPolicy: IfNotPresent

ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  path: /

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hostName: rabbitmqha.xxxxxxxxx.com

  ## Set this to true in order to enable TLS on the ingress record
  tls: true

  ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
  tlsSecret: rabbitmq-rabbitmq-ha-tls

  ## Ingress annotations done as key:value pairs
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: 89.108.155.160/28

prometheus:
  ## Configures Prometheus Exporter to expose and scrape stats.
  exporter:
    enabled: true
    env: {}
    image:
      repository: kbudde/rabbitmq-exporter
      tag: v0.28.0
      pullPolicy: IfNotPresent

    ## Port Prometheus scrapes for metrics
    port: 9419

    ## Allow overriding of container resources
    resources: {}
     # limits:
     #   cpu: 200m
     #   memory: 1Gi
     # requests:
     #   cpu: 100m
     #   memory: 100Mi

  ## Prometheus is using Operator.  Setting to true will create Operator specific resources like ServiceMonitors and Alerts
  operator:
    ## Are you using Prometheus Operator? [Blog Post](https://coreos.com/blog/the-prometheus-operator.html)
    enabled: false

    ## Configures Alerts, which will be setup via Prometheus Operator / ConfigMaps.
    alerts:
      ## Prometheus exporter must be enabled as well
      enabled: true

      ## Selector must be configured to match Prometheus Install, defaulting to whats done by Prometheus Operator
      ## See [CoreOS Prometheus Chart](https://github.com/coreos/prometheus-operator/tree/master/helm)
      selector:
        role: alert-rules
      labels: {}

    serviceMonitor:
      ## Interval at which Prometheus scrapes RabbitMQ Exporter
      interval: 10s

      # Namespace Prometheus is installed in
      namespace: prometheus

      ## Defaults to whats used if you follow CoreOS [Prometheus Install Instructions](https://github.com/coreos/prometheus-operator/tree/master/helm#tldr)
      ## [Prometheus Selector Label](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/prometheus.yaml#L65)
      ## [Kube Prometheus Selector Label](https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/values.yaml#L298)
      selector:
        prometheus: kube-prometheus
```
```
helm install -f values.yaml stable/rabbitmq-ha --name rabbitmq --namespace rabbitmq
```
**Anything else we need to know**:
