### ISSUE TITLE
Vault | optional consul-agent | Not starting | No private IPv4 address found

### ISSUE THREAD

**Issue by mmukherjee** [helm/charts#6088]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report (perhaps)

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
incubator/vault

**What happened**:
I am trying to install the vault along with the optional consul agent. I already have a consul server ring running on the same kubernetes cluster. However when I try to install the 'vault' helm chart using the following command - `helm install --name platformtest-vault incubator/vault -f helm-overrides/vault-values.yaml`, the consul-agent containers fail with this error -
`No private IPv4 address found`

My helm overrides file has (among other settings), the following settings -
```
vault:
  dev: False
  config:
    storage:
      consul:
        address: "localhost:8500"
        path: "vault"
consulAgent:
  join: platformtest-consul-consul-ui
  repository: docker.artifactory.mycompany.co.nz/consul
  tag: 1.0.6
  gossipKeySecretName: platformtest-consul-consul-gossip-key
```
..where the value `platformtest-consul-consul-ui` is the service exposed by the consul server ring.

**What you expected to happen**:
Expected the consult-agent containers to come up cleanly

**How to reproduce it** (as minimally and precisely as possible):
- Use the stable/consul helm-chart to install the consul-ring on the K8s cluster
- Create an overrides file with the values mentioned above
- Execute the command to install the helm-chart. The command is mentioned above.

**Anything else we need to know**:
None that I can think of.
