### ISSUE TITLE
[stable/fluent-bit] Add support for Time_as_Integer flag

### ISSUE THREAD

**Issue by max-lobur** [helm/charts#6141]
`Time_as_Integer` Output flag used for compatibility with old fluentd recievers. Currently it is not possible to set this flag via variable.

Docs: https://fluentbit.io/documentation/0.13/output/forward.html#config_tcp

Workaround:

```
backend:
  type: forward
  forward:
    host: ${forwarder_endpoint}
    port: "24224\n        Time_as_Integer True"
```
