### ISSUE TITLE
[stable/keycloak] db environments broken changes in the keycloak 4.0.0.Final docker image

### ISSUE THREAD

**Issue by topikachu** [helm/charts#6151]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
It's a Bug

**Version of Helm and Kubernetes**:

```
Gongs-MacBook-Pro:k8s gongyi$ helm version 
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Gongs-MacBook-Pro:k8s gongyi$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
**Which chart**:
keycloak

**What happened**:
The keycloak 4.0.0.Final docker image introduces some broken changes

**What you expected to happen**:
The keycloak chart configuration works with the new docker image

**How to reproduce it** (as minimally and precisely as possible):
Install a keycloak release using external database. The pod can't start 

**Anything else we need to know**:
Please check https://hub.docker.com/r/jboss/keycloak/
Below is a workaround to create the required env
 ```
 extraEnv: |
    - name: DB_ADDR
      value: {{ .Values.keycloak.persistence.dbHost | quote }}
    - name: DB_PORT
      value: {{ .Values.keycloak.persistence.dbPort | quote }}
    - name: DB_USER
      value: {{ .Values.keycloak.persistence.dbUser | quote }}
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ template "keycloak.externalDbSecret" . }}
          key: {{ include "keycloak.dbPasswordKey" . | quote }}
    - name: DB_DATABASE
      value: {{ .Values.keycloak.persistence.dbName | quote }}
```
