### ISSUE TITLE
[stable/grafana] Typo in ingress definition for tls secretName

### ISSUE THREAD

**Issue by KrustyHack** [helm/charts#6213]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
v2.9.1 / v.1.10.4-gke.0

**Which chart**:
Grafana

**What happened**:
TLS doesn't work with the actual ingress. There is a typo in the ingress definition

**What you expected to happen**:
TLS working

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart with ingress enabled and TLS secretName

**Anything else we need to know**:

**Comment by davidkarlsen** [comment]
Are you sure about this?
It works for me:
```
  ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - grafana.k8s.davidkarlsen.com
      tls:
      - hosts:
        - grafana.k8s.davidkarlsen.com
        secretName: grafana-secret
```
