### ISSUE TITLE
[stable/jenkins] Latest version is broken

### ISSUE THREAD

**Issue by huang-jy** [helm/charts#6271]
Similar to issue #3723 but now the workaround no longer works.

**Comment by huang-jy** [comment]
Possible solution in https://issues.jenkins-ci.org/browse/JENKINS-50132

I had to up my resource block to 

```
        resources:
          requests:
            cpu: "1"
            memory: 1536Mi
```

Before I started getting working runs
