### ISSUE TITLE
[incubator/vault] FEATURE REQUEST: Add loadBalancerIP to service definition

### ISSUE THREAD

**Issue by mjungsbluth** [helm/charts#6296]
**Version of Helm and Kubernetes**:
Kubernetes: v1.10.4-gke.0
Helm: v2.9.1

**Which chart**:
 [incubator/vault] 0.12.0

**What happened**:

Given the following values.yaml
```
service:
  type: LoadBalancer
  externalPort: 8200
  port: 8200
  loadBalancerIP: XXX.XXX.XXX.XXX
  loadBalancerSourceRanges:
  - ...
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
```

Deploying this to GKE is successful
An internal LoadBalancer ist created but assigned a random IP from the available pool.

**What you expected to happen**:

The created LoadBalancer should use the provided IP

**How to reproduce it** (as minimally and precisely as possible):

Specifying any loadBalanceIP has no effect, since it's value is not applied in the service template

**Anything else we need to know**:
