### ISSUE TITLE
How to add a custom configuration & proxy headers?

### ISSUE THREAD

**Issue by syst0m** [helm/charts#6323]
Hi,

I would like to add a custom configuration parameter for nginx-ingress, with a values.yaml file.
I am using nginx-ingress on GKE, used helm to deploy the controller.
So far, I managed to customize the **client_body_buffer_size** config by using annotations in the
yaml file for the Ingress resource,
like this:
`    nginx.ingress.kubernetes.io/client-body-buffer-size: 1m
`

I also need to set some proxy headers and other config parameters, which I think I can't customize with annotations.
For  example. proxy_http_version: 1.1, I assumed the proper place to put it is config:
Where/how should I set these config parameters:

>     proxy_set_header Connection "Keep-Alive";
>     proxy_set_header Proxy-Connection "Keep-Alive";

Here is my values.yaml:

```
## nginx configuration
## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
##
controller:
  name: controller
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.15.0"
    pullPolicy: IfNotPresent

  config:
    proxy_http_version: 1.1
  # Will add custom header to Nginx https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/customization/custom-headers
  headers:
    
## Liveness and readiness probe values
  ## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  ##
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    port: 10254
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
port: 10254

```
