### ISSUE TITLE
[GOGS] Unable to mount volume for pods

### ISSUE THREAD

**Issue by obeyler** [helm/charts#6446]
Version of Helm and Kubernetes**:
helm version : 2.9.1
Kubernetes : 1.10.3

**Which chart**:
gogs-0.6.0  

**What happened**:
I use as value.yml
```
persistence:
   storageClass: tf-cinder-storage-class
postgresql:
  persistence:
      storageClass: tf-cinder-storage-class

```
The Persistent Volumes are created  and boud to each PersistentVolumeClaim
But pods failed with this error

```
 pod has unbound PersistentVolumeClaims (repeated 3 times)
Unable to mount volumes for pod "gogs-gogs-66cb9c76c7-b9kzr_gogs(d263da38-7ecb-11e8-ae0b-fa163ec68601)": timeout expired waiting for volumes to attach or mount for pod "gogs"/"gogs-gogs-66cb9c76c7-b9kzr". list of unmounted volumes=[data]. list of unattached volumes=[config data default-token-66nc4] 

 pod has unbound PersistentVolumeClaims (repeated 3 times)
Unable to mount volumes for pod "gogs-postgresql-795bcd69dd-ck2vz_gogs(d2634ee6-7ecb-11e8-ae0b-fa163ec68601)": timeout expired waiting for volumes to attach or mount for pod "gogs"/"gogs-postgresql-795bcd69dd-ck2vz". list of unmounted volumes=[data]. list of unattached volumes=[data default-token-66nc4] 
```
