### ISSUE TITLE
[stable/grafana] dashboard provisioning not working

### ISSUE THREAD

**Issue by jalberto** [helm/charts#6450]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
2.9.1 and 1.10.3

**Which chart**:
grafana

**What happened**:

I created a folder 'Default' and use this config:
```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 2
      folder: 'Default'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    traefik:
      url: https://raw.githubusercontent.com/containous/traefik/master/contrib/grafana/traefik-kubernetes.json
    traefik2:
      gnetId: 4475
      revision: 1
      datasource: prometheus
```

**What you expected to happen**:
See 2 new dashbaords in grafana

**How to reproduce it** (as minimally and precisely as possible):
Install grafana chart backed by DB
