### ISSUE TITLE
[incubator/schema-registry] zookeeper jmx exporter can't be enabled

### ISSUE THREAD

**Issue by ljufa** [helm/charts#6466]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
v2.9.1 and v1.10.0

**Which chart**:
schema-registry

**What happened**:
Enabling jmx exporter on zookeeper is not producing jmx-exporter container in the pod.

```
zookeeper:
     exporters:
        jmx:
          enabled: true
```

**What you expected to happen**:
this condition in zookeeper/statefullset.yaml template should be meet.
```
{{- if .Values.exporters.jmx.enabled }}
        - name: jmx-exporter
          image: "{{ .Values.exporters.jmx.image.repository }}:{{ .Values.exporters.jmx.image.tag }}"
          imagePullPolicy: {{ .Values.exporters.jmx.image.pullPolicy }}
          ports:
```
**How to reproduce it** (as minimally and precisely as possible):

`values.yaml:`
```yaml
## confluent schema registry settings
schema-registry:
  replicaCount: 1
  configurationOverrides:
    kafkastore.topic.replication.factor: 1
    debug: false
    avro.compatibility.level: BACKWARD

  ## Kafka Settings
  kafka:
    enabled: true
    replicas: 1
    image: "confluentinc/cp-kafka"
    imageTag: "4.1.1-2"
    imagePullPolicy: "IfNotPresent"
    resources:
       limits:
         cpu: 1000m
         memory: 2Gi
    kafkaHeapOptions: "-Xmx2g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 \
                       -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M \
                       -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
    updateStrategy:
      type: "OnDelete"
    podManagementPolicy: OrderedReady
    rbac:
      enabled: true
    storageClass: rook-block
    configurationOverrides:
      "offsets.topic.replication.factor": 1
      "auto.leader.rebalance.enable": true
      "auto.create.topics.enable": true
      "controlled.shutdown.enable": true
      "controlled.shutdown.max.retries": 100
      "log.retention.hours": 720
      "log.retention.bytes": "107374182400"
      "num.partitions": 1
    persistence:
      enabled: false

    jmx:
      configMap:
        enabled: true
      port: 5555
      whitelistObjectNames:  # []
      - kafka.controller:*
      - kafka.server:*
      - java.lang:*
      - kafka.network:*
      - kafka.log:*
    prometheus:
      jmx:
        enabled: true
        interval: 10s
      kafka:
        enabled: true

    ## Zookeeper:
    zookeeper:
      enabled: true
      servers: 1
      resources:
        limits:
         cpu: 1000m
         memory: 0.5Gi
        requests:
          cpu: 500m
          memory: 0.5Gi
      heap: "256M"
      persistence:
        enabled: false
      exporters:
        jmx:
          enabled: true
        zookeeper:
          enabled: true
```

**Anything else we need to know**:
