### ISSUE TITLE
[incubator/schema-registry] can't disable zookeeper dependency in global chart

### ISSUE THREAD

**Issue by ljufa** [helm/charts#6468]
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
v2.9.1 and v1.10.0

**Which chart**:
schema-registry

**What happened**:
`kafka.enabled: false` is not going to stop zookeeper creation so it fails with `Error: release wayfaring-gecko failed: services "wayfaring-gecko-zookeeper" already exists`

**What you expected to happen**:
to not create zookeeper deployment if kafka  disabled

**How to reproduce it** (as minimally and precisely as possible):

`requirements.yaml:`
```yaml
dependencies:
- name: kafka
  version: 0.8.1
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
- name: schema-registry
  version: 0.4.3
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
```

`values.yaml:`
```yaml
## Kafka Settings
kafka:
  enabled: true
  replicas: 1
  image: "confluentinc/cp-kafka"
  imageTag: "4.1.1-2"
  imagePullPolicy: "IfNotPresent"
  resources:
     limits:
       cpu: 1000m
       memory: 2Gi
  kafkaHeapOptions: "-Xmx2g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 \
                     -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M \
                     -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
  updateStrategy:
    type: "OnDelete"
  podManagementPolicy: OrderedReady
  rbac:
    enabled: true
  storageClass: rook-block
  configurationOverrides:
    "offsets.topic.replication.factor": 1
    "auto.leader.rebalance.enable": true
    "auto.create.topics.enable": true
    "controlled.shutdown.enable": true
    "controlled.shutdown.max.retries": 100
    "log.retention.hours": 720
    "log.retention.bytes": "107374182400"
    "num.partitions": 1
  persistence:
    enabled: false

  jmx:
    configMap:
      enabled: true
    port: 5555
    whitelistObjectNames:  # []
    - kafka.controller:*
    - kafka.server:*
    - java.lang:*
    - kafka.network:*
    - kafka.log:*
  prometheus:
    jmx:
      enabled: true
      interval: 10s
    kafka:
      enabled: true

  ## Zookeeper:
  zookeeper:
    enabled: true
    servers: 1
    resources:
      limits:
       cpu: 1000m
       memory: 0.5Gi
      requests:
        cpu: 500m
        memory: 0.5Gi
    heap: "256M"
    persistence:
      enabled: false
    exporters:
      jmx:
        enabled: true
      zookeeper:
        enabled: true

## confluent schema registry settings
schema-registry:
  kafka:
    enabled: false
  replicaCount: 1
  configurationOverrides:
    kafkastore.topic.replication.factor: 1
    debug: false
    avro.compatibility.level: BACKWARD
```
```bash
helm create test
#copy requirements.yaml and values.yaml two files to test dir
helm dependency update test/
helm install test/
```
**Anything else we need to know**:

**Comment by drekle** [comment]
since kafka is a child chart for you your entry 
```
kafka:
  zookeeper:
    enabled: true
```
should be made false yes?

**Comment by ljufa** [comment]
Actually, I made kafka and schema-registry as requirements on the same level. 
So kafka is first requirements with zookeeper configured and schema-registry is next dependency with kafka and zookeeper disabled.
Is that possible? For me it make sense to make kafka primary dependency, and later expand my umbrella chart with additional tools like schema-registry...

**Comment by arolls** [comment]
I have the same issue.
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

I created a demo chart to show the problem here: https://github.com/arolls/helm-dependency-enable-disable

The chart is for Kafka and Schema Registry, both of which require Zookeeper. There are shared requirements in both charts so we have to be able to enable/disable them as required. Here is a map of the requirements:

- helm-dependency-enable-disable:  
  - Kafka
    - Zookeeper
  - Schema Registry
    - Kafka
    - Zookeeper

I want to enable Zookeeper in the Kafka Chart and disable it in the Schema Registry chart so I have a values file as follows:
```
kafka:
  enabled: true

schema-registry:
  enabled: true
  kafka:
    enabled: false
```

The nested enabled: false flag in the Schema Registry chart is not being honoured which results in:
```
helm install --name azure --namespace azure .
Error: release azure failed: poddisruptionbudgets.policy "azure-zookeeper" already exists
```
