### ISSUE TITLE
[stable/datadog] livenessProbe fails for datadog/dogstatsd

### ISSUE THREAD

**Issue by svyotov** [helm/charts#6481]
---
This is a BUG REPORT.

**Version of Helm and Kubernetes**:
helm: v2.7.2
kubernetes: 1.9.2

**Which chart**:
stable/datadog

**What happened**:
Kubernetes sends kill to docker as liveliness probe fails.
We observed in the docker 
```
2018-07-05 09:01:04 UTC | INFO | (main.go:190 in start) | See ya!
```
and after debugging we reached the conclusion this is happening due to the liveliness probe.

**What you expected to happen**:
liveliness probe not to fail

**How to reproduce it** (as minimally and precisely as possible):

change repository to `repository: datadog/dogstatsd `

**Anything else we need to know**:

The livenessProbe expects `probe.sh` to exist in the docker, however when using the `datadog/dogstatsd` image, it does not contain it.
image:
```
repository: datadog/dogstatsd         # Standalone DogStatsD
```
livenessProbe config:
```
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          initialDelaySeconds: 15
          periodSeconds: 5
```
What we observe is that the image fails with
```
2018-07-05 09:01:04 UTC | INFO | (main.go:190 in start) | See ya!
```
and when we debugged this we reached the conclusion that data-dog is is receiving a KILL from kubernetes because the livenessProbe has failed.
