### ISSUE TITLE
[stable/sumologic-fluentd] Way to collect non k8s container logs?

### ISSUE THREAD

**Issue by jmreicha** [helm/charts#6559]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): `Feature request`

Describe *in detail* the feature/behavior/change you'd like to see.

I noticed that there is currently no configuration option to allow log collection for paths outside of the default /var/log/container location.

It would be useful to be able to specify the path to other log file locations so that they can be collected as well.

**Version of Helm and Kubernetes**:

* Kubernetes 1.10.5
* Helm 2.9.1

**Which chart**: `stable/sumologic-fluentd`

**What happened**:

The use case I ran across is an application that logs its output to a file, which is volume mounted to the host.  Since these logs are available on the host, it would be useful to be able to collect them with SumoLogic.

**What you expected to happen**:

Expect the logs to get picked up correctly since I volume mounted them into `/var/log`.  They show up in the SumoLogic container, they just don't get picked up.

**How to reproduce it** (as minimally and precisely as possible):

* Volume mount a path with some logs into `/var/log`.

```
...
          volumeMounts:
          - mountPath: /var/log/test
            name: test-logs
            readOnly: true
volumes:
        - hostPath:
            path: /tmp
          name: test-logs
```
* Fire up sumologic-fluentd and watch its logs.

sumologic-fluentd doesn't ever seem to detect the logs in this customized location.  Maybe there could be a configuration option for specifying the path to non standard logs or something?
