### ISSUE TITLE
[stable/metrics-server] Expose command parameters to specify a metrics source

### ISSUE THREAD

**Issue by embik** [helm/charts#6619]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
$ kubectl version
[...]
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: `stable/metrics-server`

**What happened**:
It is not possible to set the metrics-server pod command parameters to specify a different metrics source. This is a problem because with our Kubernetes deplyoment as kubelet's read-only port 10255 is disabled (and as far as I know it's disabled by default with kubeadm 1.11 anyway). Thus, metrics-server deployed via `stable/metrics-server` is unable to gather metrics.

**What you expected to happen**:
I would like to be able to set command parameters via the Helm chart. The deployment spec key in question is `.spec.template.spec.containers[0].command`. This is how my deployment spec looks like:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      containers:
      - name: metrics-server
        image: gcr.io/google_containers/metrics-server-amd64:v0.2.1
        imagePullPolicy: Always
        command:
        - /metrics-server
        - --source=kubernetes.summary_api:''?kubeletPort=10250&kubeletHttps=true&insecure=true&useServiceAccount=true
```

**How to reproduce it** (as minimally and precisely as possible):

- Check [available values](https://github.com/kubernetes/charts/blob/master/stable/metrics-server/values.yaml).
- Notice there's no way to set the `/metrics-server` parameters.

**Anything else we need to know**:
