### ISSUE TITLE
stable/nginx-lego doesn't use its own resource configuration for the kube-lego container

### ISSUE THREAD

**Issue by dagvl** [helm/charts#664]
stable/nginx-lego has a configuration section in values.yaml for resources for the kube-lego container:
```yaml
lego:
  enabled: false
  replicaCount: 1
  image:
    repository: jetstack/kube-lego
    tag: "0.1.3"
    pullPolicy: IfNotPresent
  configmap:
    email: "my@email.tld"
    # Production Let's Encrypt server
    # url: "https://acme-v01.api.letsencrypt.org/directory"
    # Test Let's Encrypt server
    url: "https://acme-staging.api.letsencrypt.org/directory "
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 128Mi
```
However, the deployment uses the resources specified for the nginx-container instead:
https://github.com/kubernetes/charts/blob/master/stable/nginx-lego/templates/lego-deployment.yaml#L39
```yaml
        resources:
{{ toYaml .Values.nginx.resources | indent 10 }}
{{- end }}
```
