### ISSUE TITLE
[stable/datadog] Direct support for live process monitoring

### ISSUE THREAD

**Issue by cknowles** [helm/charts#6644]
Datadog Process Monitoring allows for real-time visibility of the most granular elements in a deployment.

It would be good to add direct support via a flag rather than having to figure out which options to override and if they are set correctly. It can be done today by adding the env var plus mount overrides just it'd be neater to have an option. It would also be more automated for users upgrading chart versions so they can easily stick with the latest recommendations.

From https://docs.datadoghq.com/graphing/infrastructure/process/#kubernetes-daemonset:

```yaml
env:
  - name: DD_PROCESS_AGENT_ENABLED
    value: "true"
volumeMounts:
  - name: passwd
    mountPath: /etc/passwd
    readOnly: true
volumes:
  - hostPath:
      path: /etc/passwd
    name: passwd
```
