### ISSUE TITLE
Pass Array values through --set

### ISSUE THREAD

**Issue by pluttrell** [helm/charts#672]
Please add the ability to pass Array values through `--set`.

For example, the `stable/aws-cluster-autoscaler` must receive the following:

```
autoscalingGroups:
  - name: my-asg-name
    maxSize: 50
    minSize: 2
```

If this is already possible, please do tell.. And update the docs to show how.
