### ISSUE TITLE
[stable/grafana] datasources provisioning not working

### ISSUE THREAD

**Issue by bentatham** [helm/charts#6728]
**Is this a request for help?**: yes

**Version of Helm and Kubernetes**:
Helm 2.9.1
Kuberenetes 1.10 (running on AWS EKS)

**Which chart**: stable/grafana

**What happened**: When trying to use `datasources` in the values.yaml, grafana fails to start with this message:
```
t=2018-07-19T18:17:15+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: read /etc/grafana/provisioning/datasources/datasources.yaml: is a directory"
```

**What you expected to happen**: 
I expected grafana to start, and have my configured data sources.

**How to reproduce it** (as minimally and precisely as possible):
My values.yaml contains the following:
```
datasources:
  - name: argo-test-soh
    type: influxdb
    access: proxy
    orgId: 1
    url: https://<redacted>.influxcloud.net:8086
    user: <redacted>
    password: "<redacted>"
    database: "argo-test-soh"
    basicAuth: false
    isDefault: false
    readonly: false
  - name: argo-stag-soh
    type: influxdb
    access: proxy
    orgId: 1
    url: https://<redacted>.influxcloud.net:8086
    user: <redacted>
    password: "<redacted>"
    database: "argo-stag-soh"
    basicAuth: false
    isDefault: false
    readonly: false
  - name: argo-prod-soh
    type: influxdb
    access: proxy
    orgId: 1
    url: https://<redacted>.influxcloud.net:8086
    user: <redacted>
    password: "<redacted>"
    database: "argo-prod-soh"
    basicAuth: false
    isDefault: false
    readonly: false
```

**Anything else we need to know**:
Instead of using persistent volume, I have grafana configured to use Postgres (hosted by AWS RDS). Before upgrading with these values.yaml, I had manually configured one data source.  It was all working before adding in the `datasources` to the yaml.
