### ISSUE TITLE
Neo4j does not expose bolt port

### ISSUE THREAD

**Issue by qbast** [helm/charts#6737]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm 2.9.0
Kubernetes 1.10  

**Which chart**:
stable/neo4j

**What happened**:
The service exposes only port 7474 (http). It is not really right way to connect to a neo4j cluster since http driver (at least for java) does not support routing, so writes quite often go to follower.

**What you expected to happen**:
Service defined in core-dns.yaml should export port 7678 as well to allow using bolt+routing:// protocol

**Comment by louspringer** [comment]
I have a possible patch but don't know how to do a proper PR with a proper test. 

Modifying `neo4j/core-dns.yaml` adding the bolt port seems to resolve the issue:
```
...
spec:
  clusterIP: None
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 7687
      targetPort: 7687
      name: bolt
...
```
