### ISSUE TITLE
[incubator/elasticsearch] not enough masters

### ISSUE THREAD

**Issue by aba182** [helm/charts#6741]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 BUG REPORT

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
[incubator/elasticsearch] - https://github.com/helm/charts/tree/master/incubator/elasticsearch

**What happened**:
Master nodes can't discover themselves. All pods start but it seems that the discovery service isn't allowing masters to see each other. Even after a hour of them sitting they just report the following:

```
[2018-07-20T14:33:51,481][WARN ][o.e.d.z.ZenDiscovery     ] [nd-infra-elasticsearch-master-1] not enough master nodes discovered during pinging (found [[Candidate{node={nd-infra-elasticsearch-master-1}{UPiTP94YTTiWz6R0COZmKw}{LYO7sVKSRvu4hNDSD7E0zg}{10.244.2.109}{10.244.2.109:9300}, clusterStateVersion=-1}]], but needed [2]), pinging again
```

Service looks like:

```
awilhelm@MBP ~/work/k8s-config (SRE-796)*$ kubectl describe svc nd-infra-elasticsearch-discovery
Name:              nd-infra-elasticsearch-discovery
Namespace:         nd-infra
Labels:            app=elasticsearch
                   chart=elasticsearch-1.3.0
                   component=master
                   heritage=Tiller
                   release=nd-infra
Annotations:       <none>
Selector:          app=elasticsearch,component=master,release=nd-infra
Type:              ClusterIP
IP:                None
Port:              <unset>  9300/TCP
TargetPort:        %!d(string=transport)/TCP
Endpoints:         10.244.2.109:9300,10.244.7.73:9300,10.244.2.145:9300
Session Affinity:  None
Events:            <none>
```

The service responds as expected to a dig call:

```
[root@nd-infra-elasticsearch-master-0 elasticsearch]# dig nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42802
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. IN	A

;; ANSWER SECTION:
nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. 30	IN A 10.244.2.109
nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. 30	IN A 10.244.7.73
nd-infra-elasticsearch-discovery.nd-infra.svc.cluster.local. 30	IN A 10.244.7.145

;; Query time: 2 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Jul 20 14:35:28 UTC 2018
;; MSG SIZE  rcvd: 109
```

I am able to telnet to the remote pod using the IP address which proves the other master is online and listening:

```
[root@nd-infra-elasticsearch-master-0 elasticsearch]# telnet 10.244.7.73 9300
Trying 10.244.7.73...
Connected to 10.244.7.73.
Escape character is '^]'.
```

**What you expected to happen**:

The "nd-infra-elasticsearch-discovery" service should allow all masters to detect each other and resolve quorum. 

**How to reproduce it** (as minimally and precisely as possible):

helm install --name elasticsearch --namespace infra incubator/elasticsearch

kubectl log -n infra elasticsearch-master-0

**Anything else we need to know**:

**Comment by GrantKlassy** [comment]
I am having the same problem. This could be related to kubedns?
```
$ kubectl logs service/kube-dns -n kube-system kubedns
...
I0723 16:41:57.332576       1 dns.go:601] Could not find endpoints for service "elasticsearch-discovery" in namespace "default". DNS records will be created once endpoints show up.
...
```
But it looks to me like elasticsearch-discovery does have endpoints listed.
```
$ kubectl get endpoints | grep discovery
elasticsearch-discovery   <Redacted, but they're listed here>   29m
```

**Comment by aba182** [comment]
I think the DNS error occurs when the service is first created but then the masters come online and the DNS entry is updated correctly. 

I have exposed each master node and updated the DISCOVERY_SERVICE to the node specific service end points but it still doesn't work. Which makes me think there is some sort of larger config issue here. 

Example of what I did:
Create services:
```
kubectl expose pod elasticsearch-master-2 --target-port 9300
kubectl expose pod elasticsearch-master-0 --target-port 9300
kubectl expose pod elasticsearch-master-1 --target-port 9300
```

Values.yml:
```
cluster:
  name: "elasticsearch"
  kubernetesDomain: cluster.local
  # If you want X-Pack installed, switch to an image that includes it, enable this option and toggle the features you want
  # enabled in the environment variables outlined in the README
  xpackEnable: false
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"
    DISCOVERY_SERVICE: elasticsearch-master-0.nd-infra.svc.cluster.local:9300,elasticsearch-master-1.nd-infra.svc.cluster.local:9300,elasticsearch-master-2.nd-infra.svc.cluster.local:9300
```

Proof ENV variable is setup correctly:

```
[root@dev-kube-master-001 ~]# kubectl exec -it elasticsearch-master-0 bash
[root@elasticsearch-master-0 elasticsearch]# echo $DISCOVERY_SERVICE
elasticsearch-master-0.nd-infra.svc.cluster.local:9300,elasticsearch-master-1.nd-infra.svc.cluster.local:9300,elasticsearch-master-2.nd-infra.svc.cluster.local:9300
```

I can still telnet using these newly created service endpoints:
```
[root@elasticsearch-master-0 elasticsearch]# telnet elasticsearch-master-2.nd-infra.svc.cluster.local 9300
Trying 127.0.0.1...
Connected to elasticsearch-master-2.nd-infra.svc.cluster.local.
Escape character is '^]'.
```
