### ISSUE TITLE
Traefik auth

### ISSUE THREAD

**Issue by weeco** [helm/charts#6756]
**Version of Helm and Kubernetes**:

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Which chart**:
Traefik

**What happened**:
Using dashboard.auth.basic the generated toml is invalid and therefore traefik doesn' run. Output toml is:
```toml
    address = ":8080"
      [web.auth.basic]
        users = ["0:map[weeco:6FC7F829C69BE6C14C450977A441C4DBEF535E1E]",]
```

**What you expected to happen**:

But toml should be:
```toml
    address = ":8080"
      [web.auth.basic]
        users = ["weeco:6FC7F829C69BE6C14C450977A441C4DBEF535E1E"]
```

**How to reproduce it** (as minimally and precisely as possible):

Use this in your values.yaml and make a dry-run:
```yaml
dashboard:
    enabled: true
    domain: traefik.brawlstats.com
    auth:
        basic: 
        - weeco: "6FC7F829C69BE6C14C450977A441C4DBEF535E1E"
```

**Anything else we need to know**:
- Relevant lines can be found here: https://github.com/helm/charts/blob/ebe24f6cc8612880acc4fa89cbee08212c78c140/stable/traefik/templates/configmap.yaml#L123-L127
