### ISSUE TITLE
[stable/grafana] - Sidecar not importing dashboards - bug ?

### ISSUE THREAD

**Issue by mprzygrodzki** [helm/charts#6803]
Hello everyone, i've started using official Helm chart for Grafana, and i'm facing problem with automatic dashboard import from JSON files. Inside Helm chart i've added dir called dashboards where i've some custom dashboards in .json format. I've added also a task to created ConfigMap based on those files - and until this point everythin is correct. 

As far as i understood reading docs etc, if i wan't to automatically import dashboard I should enable Sidecar in values. I've added to my custom ConfigMap with dashboard a label for sidecar to identify dashboard correctly like below:

```
sidecar:
  image: kiwigrid/k8s-sidecar:0.0.3
  imagePullPolicy: IfNotPresent
  resources:
#   limits:
#     cpu: 100m
#     memory: 100Mi
#   requests:
#     cpu: 50m
#     memory: 50Mi
  dashboards:
    enabled: true
    # label that the configmaps with dashboards are marked with
    label:
      dashboard: grafana
    # folder in the pod that should hold the collected dashboards
    folder: /var/lib/grafana/temp
```

Looking at the starting POD i see in logs that whole bunch of configmaps are being scanned by sidecar, but unfortunately my dashboard aren't visible in Grafana. I'm using latest chart version. Is this a bug or am I doing something wrong ?

Of if there's another way to auto import dashboards ( from json files ) while deploying release how it's possible to do it ? I'm totally blind at the moment.

Regards, Maciej

**Comment by monotek** [comment]
@Tim-Smyth can you have a look please...

**Comment by rekcah78** [comment]
@mprzygrodzki 
This PR https://github.com/helm/charts/pull/6815 fix the problem,
edit your values and change the path of your provider:
````
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      ...
      options:
        path: /var/lib/grafana/default/dashboards -> path: /var/lib/grafana/dashboards/default
```
