### ISSUE TITLE
[stable/keycloak] Crash trying to connect to cloud sql

### ISSUE THREAD

**Issue by ghost** [helm/charts#6844]
BUG REPORT:

**Version of Helm and Kubernetes**:

Helm: 2.9.1
Kubernetes: 1.9.7-gk.3

**Which chart**:

Last version of stable/keycloak

**What happened**:

`WARNING [org.postgresql.core.v3.ConnectionFactoryImpl] (ServerService Thread Pool -- 58) IOException occurred while connecting to 127.0.0.1:5432: java.net.SocketException: Connection reset
`

I followed this: https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine

In configuration, cloudsql-instance-credentials is set with the same namespace as Keycloak

Here are my events:

```
Events:
  Type     Reason                 Age                From                                            Message
  ----     ------                 ----               ----                                            -------
  Normal   Created                10m                kubelet, gke-external-agent-pool-b1749e9a-079f  Created container
  Normal   SuccessfulMountVolume  10m                kubelet, gke-external-agent-pool-b1749e9a-079f  MountVolume.SetUp succeeded for volume "scripts"
  Normal   SuccessfulMountVolume  10m                kubelet, gke-external-agent-pool-b1749e9a-079f  MountVolume.SetUp succeeded for volume "default-token-c9cjl"
  Normal   SuccessfulMountVolume  10m                kubelet, gke-external-agent-pool-b1749e9a-079f  MountVolume.SetUp succeeded for volume "cloudsql-creds"
  Normal   Started                10m                kubelet, gke-external-agent-pool-b1749e9a-079f  Started container
  Normal   Scheduled              10m                default-scheduler                               Successfully assigned keycloak-0 to gke-external-agent-pool-b1749e9a-079f
  Normal   Pulled                 10m                kubelet, gke-external-agent-pool-b1749e9a-079f  Container image "gcr.io/cloudsql-docker/gce-proxy:1.11" already present on machine
  Warning  Unhealthy              10m                kubelet, gke-external-agent-pool-b1749e9a-079f  Readiness probe failed: Get http://10.32.2.7:8080/auth/: EOF
  Warning  Unhealthy              9m                 kubelet, gke-external-agent-pool-b1749e9a-079f  Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Created                8m (x4 over 10m)   kubelet, gke-external-agent-pool-b1749e9a-079f  Created container
  Normal   Pulled                 8m (x4 over 10m)   kubelet, gke-external-agent-pool-b1749e9a-079f  Container image "jboss/keycloak:4.1.0.Final" already present on machine
  Normal   Started                8m (x4 over 10m)   kubelet, gke-external-agent-pool-b1749e9a-079f  Started container
  Warning  BackOff                49s (x33 over 9m)  kubelet, gke-external-agent-pool-b1749e9a-079f  Back-off restarting failed container

```
And here is the env of my Pod: 

```
env:
    - name: KEYCLOAK_USER
      value: keycloak
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: keycloak-http
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: 127.0.0.1
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: postgres
    - name: DB_USER
      value: proxyuser
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: cloudsql-db-credentials
```

I have no idea where it can possibly come from, any idea?Has it been tested?
