### ISSUE TITLE
[stable/redis] [bug] invalid image name

### ISSUE THREAD

**Issue by bweston92** [helm/charts#6878]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

```bash
$ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/redis

**What happened**:

A dodgy image name generated in the YAML file. Causing Kubernetes pod status to be `InvalidImageName`

Output:
```
NAME                             READY     STATUS             RESTARTS   AGE
redis-db-redis-fd87bd9cd-ft4bs   0/2       InvalidImageName   0          5m
```

You can see invalid image name in the output below:

```bash
$ kubectl get pods -n db redis-db-redis-fd87bd9cd-ft4bs -o yaml | grep image
    image: map[repository:bitnami/redis tag:4.0.10-debian-9 pullPolicy:IfNotPresent
    imagePullPolicy: IfNotPresent
    image: map[repository:oliver006/redis_exporter tag:v0.20.2 pullPolicy:IfNotPresent
    imagePullPolicy: IfNotPresent
  - image: map[repository:oliver006/redis_exporter tag:v0.20.2 pullPolicy:IfNotPresent
    imageID: ""
        message: 'Failed to apply default image tag "map[repository:oliver006/redis_exporter
          parse image reference "map[repository:oliver006/redis_exporter tag:v0.20.2
  - image: map[repository:bitnami/redis tag:4.0.10-debian-9 pullPolicy:IfNotPresent
    imageID: ""
        message: 'Failed to apply default image tag "map[repository:bitnami/redis
          parse image reference "map[repository:bitnami/redis tag:4.0.10-debian-9
```

**What you expected to happen**:

Use the correct image name.

**How to reproduce it** (as minimally and precisely as possible):

```
$ helm install --namespace=db --name redis-db -f values.yaml stable/redis
```

values.yaml:
```
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 4.0.10-debian-9
  pullPolicy: IfNotPresent

cluster:
  enabled: true
  slaveCount: 1

metrics:
  enabled: true
  service:
    type: ClusterIP
    annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    loadBalancerIP:
  image:
    registry: docker.io
    repository: oliver006/redis_exporter
    tag: v0.20.2
    pullPolicy: IfNotPresent

networkPolicy:
  enabled: false

usePassword: true
existingSecret: redis-db-password

master:
  port: 6379
  disableCommands: "FLUSHDB,FLUSHALL"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

  service:
    type: ClusterIP

  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  persistence:
    enabled: true
    path: /bitnami/redis/data
    subPath: ""
    accessModes:
    - ReadWriteOnce
    size: 8Gi

  statefulset:
    updateStrategy: OnDelete

slave:
  service:
    type: ClusterIP

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
```
