### ISSUE TITLE
[stable/presto] Can I set -Xms to JVM and PVC to node data dir?

### ISSUE THREAD

**Issue by hongmengwang** [helm/charts#6883]
I set memory in value.yml as below:
```
server:
    query:
      maxMemory: "160GB"
      maxMemoryPerNode: "16GB"
  jvm:
    maxHeapSize: "16G"
```
when started, I got this error:
`Error injecting constructor, java.lang.IllegalArgumentException: query.max-memory-per-node set to 16GB, but only 10307921511B of useable heap available
`
### I have two questions:
- Why doesn't set -Xms when starting JVM?
- Can I add PersistentVolumeClaim to _**node.data-dir**_?
@bivas
