### ISSUE TITLE
[stable/mysql] SSL is not enabled when ssl.enabled=true

### ISSUE THREAD

**Issue by bakayolo** [helm/charts#6920]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/mysql]
0.8.2

**What happened**:
SSL is not enabled when ssl.enabled=true (and certificates are provided and mounted in /ssl)

**What you expected to happen**:
SSL should be enabled.

**How to reproduce it** (as minimally and precisely as possible):
Create this SSL secret in K8S. Name it `mysql-ssl`

```
apiVersion: v1
data:
  ca.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxRENDQXBBQ0NRRGR2cVAwOW9ybW1UQU5CZ2txaGtpRzl3MEJBUXNGQURDQmxURUxNQWtHQTFVRUJoTUMKU0VzeEVqQVFCZ05WQkFnTUNVaHZibWNnUzI5dVp6RVNNQkFHQTFVRUJ3d0pTRzl1WnlCTGIyNW5NUkV3RHdZRApWUVFLREFoTGFXNTBiMGgxWWpFUk1BOEdBMVVFQ3d3SVMybHVkRzlJZFdJeEZ6QVZCZ05WQkFNTURtMTVjM0ZzCkxYQmhjM05pYjJ4ME1SOHdIUVlKS29aSWh2Y05BUWtCRmhCaVpXNUFhMmx1ZEc5b2RXSXVZMjl0TUI0WERURTQKTURjek1UQXlNREEwTkZvWERUSTRNRGN5T0RBeU1EQTBORm93Z1pVeEN6QUpCZ05WQkFZVEFraExNUkl3RUFZRApWUVFJREFsSWIyNW5JRXR2Ym1jeEVqQVFCZ05WQkFjTUNVaHZibWNnUzI5dVp6RVJNQThHQTFVRUNnd0lTMmx1CmRHOUlkV0l4RVRBUEJnTlZCQXNNQ0V0cGJuUnZTSFZpTVJjd0ZRWURWUVFEREE1dGVYTnhiQzF3WVhOelltOXMKZERFZk1CMEdDU3FHU0liM0RRRUpBUllRWW1WdVFHdHBiblJ2YUhWaUxtTnZiVENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHVKaDZtWHhQNHBldUR5QWoxVHdEZXdjTWxGL0RXMDZlNGUvbXBXCkNhcDR2eWowUjNvQU03c1hZZ3hFeDFaTVA5anlrdkJJVHhWYVNCQU5uSG0xT1ZxWXVtSHR5UHluWUpXTFFsTWMKQVAxT2FEL1k1UlJPT2k2K3YvY2M4N3R5dHQybDdKbG5VVjR4Vk1jdlhtb2RSRi83TjZIV09uZ0xpUkV5L2Z1bApEYXR1Y1VXdXNnQkd4eFFPVlJmbkJ0ZU9Ddy80VDhQRFhJQlM2NVFDWFIvbzZTTmxSSVgvRnQvSElqbFUxS0tXClYrYkVZTzJHSXdlck9QVmp0NlZ3YXM1TXFYWDJBZmJyYjhpRU5UTDN0M1BnL0dYTm14VlZESEk5RTh3V0ZCL2YKUC96VDYvWnRUajkvR0RpSHB1a2hpZzh1eFUwWXEyRlRGb0p1M1RaVmw1YzUxL01DQXdFQUFUQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBSTlNTzgzL2JUUExJV0h5NDV0cUNIRUxmVDdwb25VWWU1cittRDU3SnBhR1FYVXk3Ck16R0tUUWFwYnBndVc2TGd0NFFiTFdzaGZQYTNDYm53SUd6dVR1alEvOElRS1FVc0tmbmxoUlVxZkxGRmtwY3QKdVhIMmMrTkJiYXhXNXZkeHpvbk9iL2F5Nk0wbm5IeTFyRVJpdkFobzZ3UFZxR1hPdjVxZXZySU5OOTUxYXlDYwpjSm5CUXVyQTQ0RDVQaEFzTHhYeGZ6Tlo1NWVTOUd4Y3BhY0FFUUpYcDNBejl5ZEM3cDJmYXEvWkhrVm54V3dUCkovVk5RV0ZiUWtlUnFnc2w0VE9nY200MXVBVzdzaUtXREFuc2JLbVZqNWsxVEhUMytEYUdSMUJBN2prbVVXQ0IKZm9QK3k0WHZNTWFMY0lHdmt4Q3BKaEx6SlRuMDZsNjlSaFRtdHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvRENDQW9nQ0FRQXdEUVlKS29aSWh2Y05BUUVGQlFBd2daVXhDekFKQmdOVkJBWVRBa2hMTVJJd0VBWUQKVlFRSURBbEliMjVuSUV0dmJtY3hFakFRQmdOVkJBY01DVWh2Ym1jZ1MyOXVaekVSTUE4R0ExVUVDZ3dJUzJsdQpkRzlJZFdJeEVUQVBCZ05WQkFzTUNFdHBiblJ2U0hWaU1SY3dGUVlEVlFRRERBNXRlWE54YkMxd1lYTnpZbTlzCmRERWZNQjBHQ1NxR1NJYjNEUUVKQVJZUVltVnVRR3RwYm5SdmFIVmlMbU52YlRBZUZ3MHhPREEzTXpFd01qSXkKTVRoYUZ3MHhPREE0TXpBd01qSXlNVGhhTUlHVk1Rc3dDUVlEVlFRR0V3SklTekVTTUJBR0ExVUVDQXdKU0c5dQpaeUJMYjI1bk1SSXdFQVlEVlFRSERBbEliMjVuSUV0dmJtY3hFVEFQQmdOVkJBb01DRXRwYm5SdlNIVmlNUkV3CkR3WURWUVFMREFoTGFXNTBiMGgxWWpFWE1CVUdBMVVFQXd3T2JYbHpjV3d0Y0dGemMySnZiSFF4SHpBZEJna3EKaGtpRzl3MEJDUUVXRUdKbGJrQnJhVzUwYjJoMVlpNWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUUNwOUZtcmg2bkc1S3dOcnJ1OXNSSVk0WitsK3hrWEsxS2p1L3hqVHo0aGd5ZVFuNmRLCkpmaldaOHduckdFUGNURXdHVnJXNHhza1B1eVY5ZitiTHVaTnRJQnp5eWt1UVZJbWpmVnNNT2pkM2tKSGYycmEKbVJQUElvaWxmSzQ0dEQvZjFldVVXYlUrNjhsK3hMMTM0a1BKOWo2dHVQSGRoUE5mUE8zQmhEaTdBOXdSeGtWVwpXWnJyVmMyRWpXTldYOGcyU0E2dTFCNGFOelB6ckl6Rlc2K3FGNmZOTnVyRE90RG1KTjVEVm9SWVZ0MDY0ZTQrCmkxazJmRkc5NVZIbGoxbFlkOGh5c0lXU1JOSU1qUEtyR2ZQbUN1Y2duWDg5UUQ3QkJxR2xPb3JVbFpBSHJkZ2kKbWNyNVlONEJwM1YzMUlETE5kd0F4UVZCdWZaVjJvWlV3eFZ4QWdNQkFBRXdEUVlKS29aSWh2Y05BUUVGQlFBRApnZ0VCQUFuQTN4WlFPUmJUdDJ1VncrVUZuMzFyQis5dFdBb0FxM3lnWThwTWsybFQ5WTBSMUFhVk5IR2pjeGJQCjFFd0VBTG9HNU9MMWh5enJJU1FpWk5CS1lnbnppb2JIVDRBOG9nbklXSmlsM1JPTGVDdy9EbGdpNkk5SWFvT24KUGt1dWgwQUdaeGxLVFhtWnVIYVd4VUtWWkdSTU1TOTN4dk04RzI0RC9kNkNHMWpzZDlrcXhOeC92T0JMelhtZAphK2NuQmZZMmExcGdUdG5jYmNJbVBFSWxjOW9WREd3VFhTc0VwNXZsd05lSm9zNjRuK09RVUMzMllWdktQL3VSCmlRemloNlpFcXp4TWxSV20xdXVDKzlMU1d2RndVVTI5MDVvY3p4ZDZHR1REcGlGT2hPSFI4UWwzZGYxT3J4dTIKSGdzQlh5dWRWSGR3cno3Nm02Z0VvU29rRmJjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server-key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3A5Rm1yaDZuRzVLd04KcnJ1OXNSSVk0WitsK3hrWEsxS2p1L3hqVHo0aGd5ZVFuNmRLSmZqV1o4d25yR0VQY1RFd0dWclc0eHNrUHV5Vgo5ZitiTHVaTnRJQnp5eWt1UVZJbWpmVnNNT2pkM2tKSGYycmFtUlBQSW9pbGZLNDR0RC9mMWV1VVdiVSs2OGwrCnhMMTM0a1BKOWo2dHVQSGRoUE5mUE8zQmhEaTdBOXdSeGtWV1dacnJWYzJFaldOV1g4ZzJTQTZ1MUI0YU56UHoKckl6Rlc2K3FGNmZOTnVyRE90RG1KTjVEVm9SWVZ0MDY0ZTQraTFrMmZGRzk1VkhsajFsWWQ4aHlzSVdTUk5JTQpqUEtyR2ZQbUN1Y2duWDg5UUQ3QkJxR2xPb3JVbFpBSHJkZ2ltY3I1WU40QnAzVjMxSURMTmR3QXhRVkJ1ZlpWCjJvWlV3eFZ4QWdNQkFBRUNnZ0VCQUoyK0tpeEc4cEdrVlAwdUhScm5hc0NsU2FTbzlwVEdwU0ZMcmVvTzlyL3MKRjZEb1RrRklGVG9MaFRXZGpVamo2cCtXS1BZaVBHTGI5SU1Mbkg3UWZQbktleDcraGU1a3VuY0djN0JEaFIvSQoxd085ZzlQNUdLVzhpOC90ZFZjMEZjVVByR1E1RHp5alpKWEF6WXFqKy85TUNzajdTNklyY0NnSlNUUEFJVmVSCnJrbmJ3eDA2bWZnaFgyNkFQZ2xtQVU1V090RE1vREh2Yjd6Z1c1clcxcTdqQnFaaTdFejc2bUFrSjg4M0J4MEsKVTFiTy80NlZqVHkxV1hRYnBlMy9wbnpXQlZOSkZQa0RwdW4vSlg2bnVVdkJiK2xPdnQ4YWNXTkxmRS8zL3h3TQplWVdQZUlxcFNCNHN5aXp0UUYxZ3U4c0FGZFBFMmxjK2VxWkxTNE9pZHZFQ2dZRUEwd3BhWjZvVG10QW1sQ1hNCitybzBIZDJWNld2aGlPS0p4bDFHblpJWDJvT1JlcmJRbzlnUWxPZTJhT1AwWUdKY0tqOWp4dmdxQjJRRTZxV24KUVZ6eXVHMFg4Rktzd2JpTVFRZ3R6aWRPOGQvRVJrQnppNW1nUExXNS9tMlBnSjZXSUJadU9yYW9zYjF6QlB3bQovQ2cyMHNHeUZxSHRON1MwQXQzOVNIcU9BUDhDZ1lFQXppbEVRQ1pWQlNEUFZtU2d6dXdkNGk5QWJMWHBaMnJTClgxZ2s4NlhjNnZYbU9mb0c2bnRJY0JpUWlBdG0wOVE4dU0xajkwNmtJc3RWcUZhbzJtZDk5RkNVazhGWVVxb1AKYnBuSTRaL1ZlcVVVWldlNFFISlB5a3hjUjBEeFN5UU4yNUthQWEyV2pUM3R0aXJLMTdUODM0Z0NNWWdrcU9LZgpXc0t6bWtjSWVZOENnWUVBbCtMSW8va2MrUHU3K0Qyb1kvOGxTU1ZVSWxYWlVRb3h2RWtmYklKYmxwSEFYMEE1CnN1SHJOUy82OFV5MmNiUDR2eE0yUFZvWDdZL0hsaFU0NWVyK2FVdGl3anpPUnZJS1J6ZWF0OWRFa3dISUlnTjYKNVVyZ3J6RGZOc1VsVloxTlVMUzBDcCt4azVKVXVJNjloQmR4TllmZ0l6ZlJJWmwxUU9jQnhtc2x6b01DZ1lBRApjYzhSSDFMV1Zoa0F3WWVxVFdtbWFOR3p2MHBhRHYvYTFmY3dGdnBjOXFUVkhTZFdiWjdsT0pQWm9nOGl4TzRLCnpHdTZLeGMwK1o3QnhFam45VWkyZDA0ME5jdksvY3BxTjZtU2s0QVduNEY2dkVQbzE4QWJpakVVZzdKRVppTFIKSTE3dFhrQWd0Z010d3dOR25XQ0lQNWFCeTF1SmN0Zmt4VklJNXR6dVl3S0JnQlBwWHoxNFN6YlFCaUgvcUs1SwplaVZUUDE2YU1FbUtNL0RWUDFCMWJVZEpQM0ZHdTNETXdEN214Rk1yWVJrMXlBL0RNQjFVYWE4Q0FLRm1KSlFhCi90OUluMndlL0FSZ1FMY21TYnM3SUpCNnNKWFI2SWRuVlNycHRQSi9sWFhvTW92cXN3elc1dlVzZmpsWnRkTlgKa01vdjUrQnZiV09zYWhzbmNpdUUvMWJxCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
type: Opaque
```

Then install the charts:

values.yaml
```
mysqlRootPassword: root123

ssl:
  enabled: true
  secret: mysql-ssl

configurationFiles:
  mysql_custom.cnf: |-
    [mysqld]
    require_secure_transport = ON
    ssl-ca = /ssl/ca.pem
    ssl-cert = /ssl/server-cert.pem
    ssl-key = /ssl/server-key.pem
```

```
helm upgrade --wait --install  -f values.yaml mysql-test stable/mysql
```

**Anything else we need to know**:
For testing

```
$ mysql -u root -p
Enter password: root123
...
mysql> status
``` 

SSL field should not be `Not in use`
