### ISSUE TITLE
[incubator/elasticsearch/]

### ISSUE THREAD

**Issue by bartwalczak1** [helm/charts#6922]
**FEATURE REQUEST**:

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"
```
**Which chart**:
[incubator/elasticsearch/]
**What happened**:
support passing variables via values file.

**What you expected to happen**:
Instead of passing variables via `--set` it would be nice to provide values.yaml via `-f` or `--values`. 
Not sure but this might be a bug in case it was expected behavior

```
helm install --name zez --values state.yaml incubator/elasticsearch
```
content of values.yaml:
```
appVersion=5.6,image.repository=docker.elastic.co/elasticsearch/elasticsearch
image.tag: "5.6.10"
cluster.name: zzz
client.name: zzz-client
client.heapSize: 256m
cluster.kubernetesDomain: "tenable.prem."
client.replicas: 1
client.serviceType: ClusterIP
master.name: zzz-master
master.exposeHttp: false
master.replicas: 3
master.heapSize: 256m
master.persistence.name: master
data.persistence.name: data
data.persistence.size: 2Gi
data.persistence.enabled : true
```
**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by bartwalczak1** [comment]
@aba182 Can you please share your values.yml and command, please.

**Comment by aba182** [comment]
Command
```
helm install --name elastic-test --namespace elastic-test incubator/elasticsearch -f /tmp/x.yml
```

Yaml (Defaults besides storage class) I know it works because it takes my storageclass modifications:
```
# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "6.3.1"

image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  tag: "6.3.1"
  pullPolicy: "IfNotPresent"

cluster:
  name: "elasticsearch"
  kubernetesDomain: cluster.local
  # If you want X-Pack installed, switch to an image that includes it, enable this option and toggle the features you want
  # enabled in the environment variables outlined in the README
  xpackEnable: false
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"

client:
  name: client
  replicas: 2
  serviceType: ClusterIP
## (dict) If specified, apply these annotations to the client service
#  serviceAnnotations:
#    example: client-svc-foo
  heapSize: "512m"
  antiAffinity: "soft"
  nodeSelector: {}
  tolerations: {}
  resources:
    limits:
      cpu: "1"
      # memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"
  priorityClassName: ""
  ## (dict) If specified, apply these annotations to each client Pod
  # podAnnotations:
  #   example: client-foo
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1

master:
  name: master
  exposeHttp: false
  replicas: 3
  heapSize: "512m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "4Gi"
    storageClass: "rook-block"
  antiAffinity: "soft"
  nodeSelector: {}
  tolerations: {}
  resources:
    limits:
      cpu: "1"
      # memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"
  priorityClassName: ""
  ## (dict) If specified, apply these annotations to each master Pod
  # podAnnotations:
  #   example: master-foo
  podDisruptionBudget:
    enabled: false
    minAvailable: 2  # Same as `cluster.env.MINIMUM_MASTER_NODES`
    # maxUnavailable: 1

data:
  name: data
  exposeHttp: false
  replicas: 2
  heapSize: "1536m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "30Gi"
    storageClass: "rook-block"
  terminationGracePeriodSeconds: 3600
  antiAffinity: "soft"
  nodeSelector: {}
  tolerations: {}
  resources:
    limits:
      cpu: "1"
      # memory: "2048Mi"
    requests:
      cpu: "25m"
      memory: "1536Mi"
  priorityClassName: ""
  ## (dict) If specified, apply these annotations to each data Pod
  # podAnnotations:
  #   example: data-foo
  podDisruptionBudget:
    enabled: false
    # minAvailable: 1
    maxUnavailable: 1
```

Notice though that I have another issue open against this chart here: https://github.com/helm/charts/issues/6741
