### ISSUE TITLE
[stable/grafana] Can't enable grafana https

### ISSUE THREAD

**Issue by dtshepherd** [helm/charts#6932]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature Request?  Sort of a bug.

**Version of Helm and Kubernetes**:

Helm: 2.9.1
Kubernetes: 1.10.4

**Which chart**:

Grafana 1.12.0

**What happened**:

I updated the grafana `values.yaml` to include:
```
  grafana.ini:                                                                   
    server:                                                                      
      protocol: https                                                            
      cert_file: <my secret crt>
      cert_key: <my secret key>
```

Grafana started up fine and HTTPS was working as expected until the pod health checks failed against the HTTPS server.

**What you expected to happen**:

Grafana pod stays running with HTTPS enabled.

**How to reproduce it** (as minimally and precisely as possible):

Install grafana Helm chart and include the following in the values.yaml:
```
  grafana.ini:                                                                   
    server:                                                                      
      protocol: https                                                            
      cert_file: <my secret crt>
      cert_key: <my secret key>
```

**Anything else we need to know**:

The problem seems to be here: https://github.com/helm/charts/blob/master/stable/grafana/templates/deployment.yaml#L196-L203.

Kubernetes supports a `scheme` of HTTPS for the `httpGet` checks.  Maybe the chart can promote enabling `https` as a first class citizen?

Refer to http://docs.grafana.org/installation/configuration/ for enabling HTTPS.
