### ISSUE TITLE
[stable/rabbitmq] Can't spin up cluster with PV's created manually.

### ISSUE THREAD

**Issue by mprzygrodzki** [helm/charts#6934]
Hello everyone, i have a task to extend our RabbitMQ deployment to the cluster with 3 replicas running. Main issue i'm facing, is that the requester would like to have persistent volumes created manually in AWS (not dynamically) But i'm facing issues to attach those PVC's to POD's. I'm running latest helm chart for RabbitMQ. When starting up new deployment, i would like that PVC which will be created will bound into existing PersistentVolume which was created "by hand" lets say.

So from the beginning, at the moment i'm starting with only one PV.

1) I've created manually 1 volume in AWS.
2) I've added to the chart file called pv.yaml which contains configuration for the creation of persistence volumes, like below:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    aws: "yes"
  namespace: {{ .Values.namespace }}  
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    {{ .Values.persistence.accessModes }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  awsElasticBlockStore:
    volumeID: 'vol-xxxxxxxxxxxxx'
    fsType: ext4
```
3. Enabled persistence in values with this configs:
```
persistence:
  enabled: true
  storageClassName: "rabbit-class"
  storageClass: "rabbit-class"
  accessModes: 
    - ReadWriteOnce
  size: 10Gi  
```
4. PV is created, PVC is also created and bound correctly to existing PV. 
5. POD isn't starting, following errors occurs:
`pod has unbound PersistentVolumeClaims (repeated 2 times)`
and from POD logs, which might be a result of previous one:
`bash: line 1: /opt/bitnami/rabbitmq/var/lib/rabbitmq/.erlang.cookie: Permission denied`

Looking at POD's details:
![image](https://user-images.githubusercontent.com/20643317/43492675-60dd5c20-952a-11e8-93bb-2173be8e3940.png)

So my question is, what is wrong with my current setup to get it running - or maybe this isn't supported when running statefulset ?
