### ISSUE TITLE
[stable/traefik] Traefik fails when ACME is enabled

### ISSUE THREAD

**Issue by sundeer** [helm/charts#6974]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug?

**Version of Helm and Kubernetes**:
helm: v2.9.1 
Kube: 1.10.5-gke.3

**Which chart**: traefik

**What happened**:
```
# values-override.yaml

image: traefik
imageTag: 1.6.5-alpine

rbac:
  enabled: true

dashboard:
  enabled: true
  domain: traefik.mydomain.com

#ssl:
#  enabled: true
#  enforced: true

acme:
  enabled: true
  logging: true
  email: myname@mydomain.com
  staging: true
  domains:
    enabled: true
    domainList:
      - main: "*.mydomain.com"
    challengeType: dns-01
  dnsProvider:
    name: route53
    route53:
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "..."
      AWS_SECRET_ACCESS_KEY: "..."
```
```
helm install stable/traefik  --name ingress --namespace traefik --values ./values-override.yaml
```
traefik container dies with error
```
level=fatal msg="Unknown entrypoint \"https\" for provider ACME configuration"
```
 If I uncomment ssl section, pod starts and I'm able to access https://traefik.mydomain.com. However the cert in not from LE, it's the default one for *.example.com.

I'm also now seeing errors like this in the log
```
level=error msg="Unable to obtain ACME certificate for domains \"traefik.mydomain.com\" detected thanks to rule \"Host:traefik.mydomain.com\" : cannot get ACME client ACME challenge not specified, please select HTTP or DNS Challenge"
```
Is there something I'm missing?

**What you expected to happen**:
To be able to access the dashboard at https://traefik.mydomain.com with my LE wildcard cert

**How to reproduce it** (as minimally and precisely as possible):
see above
