### ISSUE TITLE
[stable/Jenkins] How to run docker commands in agents?

### ISSUE THREAD

**Issue by BrunoQuaresma** [helm/charts#7002]
**Is this a request for help?**:
Yes
---

**Which chart**:
Jenkins

**What happened**:
I can't run docker commands in steps.
`/home/jenkins/workspace/vision_front_new_master-PTH4UDTQVSAS7VICPCO2UFHIE5M6B37LQYLEJT5BMAT36AYX77KA@tmp/durable-e821ca88/script.sh: docker: not found`

**What you expected to happen**:
Can run docker commands

**Anything else we need to know**:
I tried to create a new Docker image with docker but still not working. 
```
FROM jenkinsci/jnlp-slave:latest
USER root
RUN apt-get -q update && \
    apt-get -q install -y apt-transport-https ca-certificates curl software-properties-common && \
    echo 'deb https://apt.dockerproject.org/repo debian-jessie main' >> /etc/apt/sources.list.d/docker.list && \
    curl https://apt.dockerproject.org/gpg > docker.gpg.key && \
    echo "c836dc13577c6f7c133ad1db1a2ee5f41ad742d11e4ac860d8e658b2b39e6ac1 docker.gpg.key" | sha256sum -c && \
    apt-key add docker.gpg.key && \
    rm docker.gpg.key && \
    apt-get -q update && \
    apt-cache policy docker-engine && \
    apt-get -q install -y docker-engine=1.11.2-0~jessie && \
    service docker start && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*
```
Configuration:
```
variable "project_id" { default = "project" }
variable "region" { default = "us-central1-a" }

variable "plugins" { default = [
  "kubernetes:1.12.0",
  "workflow-job:2.23",
  "workflow-aggregator:2.5",
  "credentials-binding:1.16",
  "git:3.9.1",
  "blueocean:1.7.1"
]}

provider "google" {
  version = "~> 1.0"
  region  = "${var.region}"
  project = "${var.project_id}"
}

resource "helm_release" "jenkins" {
  name      = "jenkins"
  chart     = "stable/jenkins"

  set {
    name  = "Master.AdminUser"
    value = "user"
  }

  set {
    name  = "Master.AdminPassword"
    value = "password"
  }

  set {
    name = "Master.InstallPlugins"
    value = "{${join(",", var.plugins)}}"
  }

  set {
    name = "Agent.AlwaysPullImage"
    value = true
  }

  set {
    name = "Agent.Image"
    value = "us.gcr.io/project/jenkins-docker-agent"
  }

  set {
    name = "Agent.ImageTag"
    value = "latest"
  }
}
```
Before posted this question here I tried in Stackoverflow: https://stackoverflow.com/questions/51681713/jenkins-helm-docker-not-found-when-try-to-run-a-test

**Comment by BrunoQuaresma** [comment]
My values.yaml

```
Master:
  AdminUser: user
  AdminPassword: user
  InstallPlugins:
   - kubernetes:1.12.0
   - workflow-job:2.23
   - workflow-aggregator:2.5
   - credentials-binding:1.16
   - git:3.9.1
   - blueocean:1.7.1 
Agent:
  Image: adriagalin/jenkins-jnlp-slave
  ImageTag: 1.4
  AlwaysPullImage: true
  volumes:
   - type: HostPath
     volumeName: docker-sock
     hostPath: /var/run/docker.sock
     mountPath: /var/run/docker.sock
```
