### ISSUE TITLE
[stable/external-dns]  Azure Config File Volume Type

### ISSUE THREAD

**Issue by garethmorris78** [helm/charts#7058]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

external-dns helm chart, when provider "azure" is set, the volume type used to present the service principal credential is hostpath: 

```
 volumes:
      - name: azure-config-file
        hostPath:
          path: /etc/kubernetes/azure.json
          type: File
```
Can an additional option please be added to select the volume type within value.yaml ? Specifically a secret to support helm deployment of external-dns on Azure Kubernetes Service clusters (see https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/azure.md) ?

Or perhaps a better option would be to align the azure volume configuration with AWS/GKE within the deployment.yaml template,  which both use secrets ?

**Version of Helm and Kubernetes**: 
AKS Cluster: 1.9.6
Helm 2.9.1

**Which chart**:
external-dns

**What happened**:
Unable to use chart to deploy external-dns on AKS

**What you expected to happen**:
Be able to set secret as a volume type for azure service principle credentials json or chart is updated align Azure with GKE/AWS secret volume type.
