### ISSUE TITLE
[stable/datadog] use Service to create DataDog agent for APM metric collection

### ISSUE THREAD

**Issue by gajus** [helm/charts#7111]
**Which chart**:

https://github.com/helm/charts/tree/master/stable/datadog

**What happened**:

DataDog chart requires use of `hostPort` on a DaemonSet to enable APM metric collection.

**What you expected to happen**:

I expect chart to create a service that I could use to send metrics to without using `hostPort`, e.g.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  labels:
    app: datadog-datadog
spec:
  type: NodePort
  ports:
  - port: 8126
    targetPort: 8126
    protocol: TCP
  selector:
    app: datadog-datadog

```
