### ISSUE TITLE
[stable/phabricator] mariadb pod not ready

### ISSUE THREAD

**Issue by cabrinoob** [helm/charts#7174]
Hi,
I'am trying to install the last stable version of phabricator (phabricator-2.1.7).

I'am using helm : 

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
And kubectl : 
 ```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I'am installing phabricator chart with these values : 

```
serviceType: ClusterIP
ingress:
  enabled: true
  path: /
  hosts:
    - phabricator.exemple.com
  annotations:
    kubernetes.io/ingress.class: internal
image:
  tag: latest
mariadb:
    rootUser:
      password: azerty123
```

You can see that I force the mariadb root password to azerty123. But the problem is that the mariadb pod is never ready because the readyness probe crashes : 

 ```
Warning  Unhealthy              0s    kubelet, ip-10-27-22-89.eu-west-1.compute.internal  Readiness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'
```

When I connect into the mariadb container I can see that there is a $MARIADB_ROOT_PASSWORD=azerty123, so it has been well setted by helm. But I don't know why the probe fails.

If I manually launch `mysqladmin -uroot -pazerty123` inside the container it crashes: Access denied for user 'root'@'localhost.

If I install the mariadb chart alone with the same values and in the same version (mariadb-4.3.3) than the mariadb required by fabricator, the mariadb db pod is working.

Any idea?

Thank you
