### ISSUE TITLE
[stable/grafana] Ingress definition requires host route

### ISSUE THREAD

**Issue by sfitts** [helm/charts#7213]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
$ helm version --short
Client: v2.9.1+g20adb27
Server: v2.9.1+g20adb27

$ kubectl version --short
Client Version: v1.10.3
Server Version: v1.10.3

**Which chart**:
[stable/grafana](https://github.com/helm/charts/tree/master/stable/grafana)

**What happened**:
Defined a `values.yaml` file with the following ingress settings:

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels: {}
  hosts: {}
  path: /grafana
```

This resulted in the following error:

```
$ helm upgrade grafana stable/grafana -f grafana.yaml
Error: UPGRADE FAILED: Ingress.extensions "grafana" is invalid: spec: Invalid value: []extensions.IngressRule(nil): either `backend` or `rules` must be specified
```

I also tried setting `hosts` to `null` (which the template docs indicates is a way to "undefine" a default key.  This resulted in the same error.  Not putting any value for `hosts` caused it to use the default value of `charts.example.com`.

**What you expected to happen**:
I would like to have it create an ingress with a definition like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: 2018-08-15T22:00:59Z
  generation: 1
  name: grafana-http
  namespace: default
  resourceVersion: "184347"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/grafana-http
  uid: b12715d5-a0d6-11e8-809a-06e5d0991c68
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
        path: /grafana
```

Since routing on virtual hosts isn't required in general, it would be nice if it wasn't required here.

**How to reproduce it** (as minimally and precisely as possible):

    helm install --name grafana stable/grafana -f values.yaml

Where the file `values.yaml` contains the previously provided ingress settings.

**Anything else we need to know**:
No.

**Comment by giacomoguiulfo** [comment]
Hello @sfitts

In order to do what you described, your values will need to look like this:
```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels: {}
  hosts:
    - ""
  path: /grafana
```
