### ISSUE TITLE
[stable/grafana] pod.Spec.SecurityContext.RunAsUser is forbidden

### ISSUE THREAD

**Issue by obeyler** [helm/charts#7231]
I use of kubernetes version 1.11.1 and grafana helm chart: 1.14.0

when I try to install grafana with helm I haven't got any pod created and in event of replica set I've got an error
pod.Spec.SecurityContext.RunAsUser is forbidden

I've try with both option for rbac.pspEnabled (true or false) with same result

 
this is my value.yaml
```
adminUser: admin
deploymentStrategy: RollingUpdate
downloadDashboardsImage:
  pullPolicy: IfNotPresent
  repository: appropriate/curl
  tag: latest
grafana.ini:
  auth.ldap:
    allow_sign_up: true
    config_file: /etc/grafana/ldap.toml
    enabled: true
image:
  pullPolicy: IfNotPresent
  repository: grafana/grafana
  tag: 5.2.2
ldap:
  config: |-
    verbose_logging = true
    [[servers]]
    host = "xxxxxxxxxxxx"
  ...
    group_dn = "*"
    org_role = "Viewer"
persistence:
  accessModes:
  - ReadWriteOnce
  enabled: true
`  enabled: true
  size: 8Gi
  storageClassName: tf-cinder-storage-class
plugins: grafana-kubernetes-app,grafana-clock-panel
rbac:
  create: true
  pspEnabled: false
securityContext:
  fsGroup: 472
  runAsUser: 472
serviceAccount:
  create: true
  name: tiller


```
