### ISSUE TITLE
[stable/mongodb]: selector does not work anymore

### ISSUE THREAD

**Issue by ghost** [helm/charts#7315]
Helm version: 2.10.0

I upgrade to Helm 2.10.0 and it looks like it doesn't like to have the chart version into the template selector.

I realize you had the chart version into it pretty recently:

https://github.com/helm/charts/commit/5fd76979a15e6983ee607067b5ace7d737d7e8d8#diff-a4454c0d265cc0960a96da78193e63b2

Now I have an error trying to upgrade my system: 

`helm upgrade data-mongodb-dev stable/mongodb --namespace dev --install`

`Error: UPGRADE FAILED: Deployment.apps "data-mongodb-dev" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"release":"data-mongodb-dev", "app":"mongodb", "chart":"mongodb-4.2.0"}: `selector` does not match template labels
`

My current labels for data-mongo-dev is:

```
  labels:
        app: mongodb
        chart: mongodb-4.1.1
        release: data-mongodb-dev

```
