### ISSUE TITLE
jenkins install has a problem" provided port:50000 is not reachable"

### ISSUE THREAD

**Issue by moyuanhui** [helm/charts#7360]
this is a problem:
![image](https://user-images.githubusercontent.com/18112282/44639767-34ed1d00-a9f0-11e8-83f4-d47b3154332b.png)
![image](https://user-images.githubusercontent.com/18112282/44639848-af1da180-a9f0-11e8-9ed6-82c10603b220.png)

![image](https://user-images.githubusercontent.com/18112282/44639833-9d3bfe80-a9f0-11e8-8246-461aa2501290.png)

**Comment by SinghNitesh84** [comment]
I am also facing the similar issue, Were you able to resolved the problem?

**Comment by azelezni** [comment]
To fix this set the below env in the jnlp container.
```
env:
  - name: JENKINS_URL
    value: http://jenkins.operations:8080
  - name: JENKINS_TUNNEL
    value: jenkins-agent.operations:50000
```
