### ISSUE TITLE
[stable/ark] s3ForcePathStyle must be a string

### ISSUE THREAD

**Issue by xrstf** [helm/charts#7373]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is a bug report.

**Version of Helm and Kubernetes**:
* Helm 2.9.1
* Kubernetes v1.10.6-gke.2

**Which chart**:
stable/ark

**What happened**:
I tried to configure the the `backupStorageProvider` using a `values.yaml`. As I'm using Minio as my S3 backend, I needed to set `s3ForcePathStyle` to `true` and so I did:

```yaml
configuration:
  backupStorageProvider:
    name: aws
    bucket: ark
    config:
      region: eu-west-1
      s3Url: http://minio.minio.svc.cluster.local:9000
      s3ForcePathStyle: true
```

The `configmap.yaml` in turn generated the following YAML for the Ark config:

```yaml
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  name: default
backupStorageProvider:
  name: aws
  bucket: ark
  config:
    region: eu-west-1
    s3Url: http://minio.minio.svc.cluster.local:9000
    s3ForcePathStyle: true
```

**What you expected to happen**:
I expected this to work, i.e. Ark starting and not prepending the bucket name into the minio URL, but instead appending it as a path element.

Instead, Ark errored out with

```
time="2018-08-27T19:15:02Z" level=error msg="Error retrieving configuration" error="v1.Config: BackupStorageProvider: v1.ObjectStorageProviderConfig: CloudProviderConfig: Config: ReadString: expects \" or n, but found t, error found in #10 byte of ...|thStyle\":true,\"s3Url|..., bigger context ...|config\":{\"region\":\"eu-west-1\",\"s3ForcePathStyle\":true,\"s3Url\":\"http://minio.minio.svc.cluster.local:|..." logSource="pkg/cmd/server/server.go:348"
```

I suspect this to be similar/related to kubernetes/kubernetes#57509, as in the value of labels must be strings. This is confirmed by Ark doing a manual cast to bool.

The error can be fixed by specifying `"true"` in my `values.yaml` and changing the `configmap.yaml` to do

```yaml
  {{- with .s3ForcePathStyle }}
    s3ForcePathStyle: {{ . | quote }}
  {{- end }}
```

**How to reproduce it** (as minimally and precisely as possible):
Deploy Ark as documented and then try to set a raw bool value, then look at the log of the Ark pod.
