### ISSUE TITLE
mongodb pods do not honour resource limit or request values

### ISSUE THREAD

**Issue by ostigley** [helm/charts#7539]
**BUG REPORT** 
cpu and memory resource requests are not honoured when replication is enabled.

**Version of Helm and Kubernetes**:
helm 2.10.0
kubernetes 1.9.0

**Which chart**:
stable/mongodb

**What happened**:
using the following values spins up all the required pods, and puts them in my nodes.  However the pod resources are empty

values:
```
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 3.6.7
  pullPolicy: Always
usePassword: false
mongodbEnableIPv6: false

mongodbExtraFlags: ["--wiredTigerCacheSizeGB=10"]

service:
  annotations: {}
  type: ClusterIP
  port: 27017

replicaSet:
  ## Whether to create a MongoDB replica set for high availability or not
  enabled: true
  useHostnames: true

  name: dnz

  replicas:
    secondary: 2
    arbiter: 0
  pdb:
    minAvailable:
      arbiter: 0
      primary: 1
      secondary: 2

nodeSelector:
  type: mongodb-production

resources:
  requests:
    cpu: 3
    memory: 11Gi
  limits:
    cpu: 4
    memory: 12Gi

persistence:
  enabled: true
  storageClass: "mongodb-ebs-production"
  accessModes:
    - ReadWriteOnce
  size: 160Gi
  annotations: {
    purpose: 'mongodb production data'
  }
```

My storage class incase you want to see it:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-ebs-production
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: io1
  zones: ap-southeast-2b, ap-southeast-2c
  encrypted: "true"
  kmsKeyId: yadayada
```

kubectl describe pod shows the pod is pretty happy:

**What you expected to happen**:
Inspecting the nodes shows that each mongo pod does not request the above values.  
Inspecting the stateful sets shows `"resource": {}`

**How to reproduce it** (as minimally and precisely as possible):
Do the above values work  for anyone?  My nodes are m4.large
Has anyone else used this chart for replication successfully?  Or should I go with mongodb-replication?

**Anything else we need to know**:
