### ISSUE TITLE
[stable/selenium] Selenium hub fails health probes and is restarted.

### ISSUE THREAD

**Issue by mdgreenwald** [helm/charts#7552]
**Is this a request for help?**:

Nay.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request (Change I would like to see)

**Version of Helm and Kubernetes**:
Helm:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
Kubernetes:
```
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

NOTE: Our cluster uses t2.medium AWS instances. This issue might not appear on higher performance instance types.

**Which chart**:
`charts/tree/master/stable/selenium`

**What happened**:
When scaling down the number of chrome-nodes:

`kubectl --kubeconfig=kubeconfig scale --replicas=1 deploy selenium-chrome`

selenium-hub fails its health-checks and is restarted: 
 ```
Warning  Unhealthy              43s (x2 over 1m)  kubelet, ip-172-22-30-239.ec2.internal  Liveness probe failed: Get http://10.2.106.108:4444/grid/console: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Warning  Unhealthy              39s (x2 over 1m)  kubelet, ip-172-22-30-239.ec2.internal  Readiness probe failed: Get http://10.2.106.108:4444/grid/console: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

this can cause subsquent/concurrent tests to fail because the nodes are disconnected from the hub.

**What you expected to happen**:

Normally I would expect to be able to scale down the number of chrome nodes without any failures.

**How to reproduce it** (as minimally and precisely as possible):

1. Install the selenium stable chart.
2. Set the number of chrome-node replicas to a integer greater than 1. e.g. 3: `kubectl --kubeconfig=kubeconfig scale --replicas=3 deploy selenium-chrome`
3. Sleep 60
4. Scale the chrome-node deployment back down to 1. e.g. `kubectl --kubeconfig=kubeconfig scale --replicas=1 deploy selenium-chrome`
5. `kubectl --kubeconfig=kubeconfig get po | grep selenium-hub`
6. Sleep 45
7. `kubectl --kubeconfig=kubeconfig get po | grep selenium-hub` should have a higher restart count than it did before Step 4.
8. `kubectl --kubeconfig=kubeconfig describe po selenium-selenium-hub-ab123456c-abcde` should show failing health checks in the events log.

**Anything else we need to know**:

Selenium Developers reccomended using the health endpoint: `/wd/hub/status` and NOT: `/grid/console`.

This is because: "I do notice /grid/console hangs for a bit after a node loses connection." **and** "...when a node dies the grid server stalls for a while..." **and** "...registering and unregistering lots nodes is an expensive operation for the Grid, it tends to block it."

Additionally I added `readinessProbe.initialDelaySeconds: 15` which also eliminated health check failures.

NOTE: Our cluster uses t2.medium AWS instances. This issue might not appear on higher performance instance types.

**These are the changes I made to our template**:

```yaml
  livenessProbe:
    httpGet:
      path: /wd/hub/status
      port: {{ .Values.hub.port }}
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: {{ .Values.hub.livenessTimeout }}
  readinessProbe:
    httpGet:
      path: /wd/hub/status
      port: {{ .Values.hub.port }}
    initialDelaySeconds: 15
    timeoutSeconds: {{ .Values.hub.readinessTimeout }}
```
