### ISSUE TITLE
[stable/rabbitmq-ha] add custom definitions in definitions.json

### ISSUE THREAD

**Issue by kaizensparc** [helm/charts#7553]
**Is this a request for help?**: Yes and no :)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Version of Helm and Kubernetes**: Helm v2.9.1, Kubernetes v1.10.0

**Which chart**: stable/rabbitmq-ha

**What happened**: Since v1.9.0, a `definitions.json` file have been created, needed for users creation for health check, prometheus, etc. It is thus impossible to get these features using a custom `definitions.json` file without patching it. 

Is using the definitions file not a normal workflow to get a declarative way to configure rabbitmq? (I'm a rabbitmq newbie)

I would like to deploy a pre-configured rabbitmq with already defined queues, bindings, etc. but I cannot figure out how to do it without patching this file. 

**Anything else we need to know**: I can make a PR to add the ability to add custom definitions inside the generated `definitions.json` if it is a correct way to do it.

I could add the following variables in the values file:
```yaml
definitions:
  users: |-
    { "name": "username", ... }
  vhosts: |-
    {"name": "/" }
  permissions: |-
    { "user": "username", ...}
  other:
  - policies: |-
  - queues: |-
  - exchanges: |-
  - bindings: |-
  - ...
```
