### ISSUE TITLE
[stable/mariadb] Mounting existing PersistentVolumeClaim to data dir?

### ISSUE THREAD

**Issue by pentago** [helm/charts#7647]
**Is this a request for help?**: Yes

**Is this a BUG REPORT or FEATURE REQUEST?**: None

1. Can someone clarify how to use **MariaDB** chart with **existing PersistentVolumeClaim**.
2. Can it be used to mount data dir (_/bitnami/mariadb_)?

**Version of Helm and Kubernetes**:
Any

**Which chart**:
stable/mariadb

**What happened**:
`create Pod mariadb-mariadb-master-0 in StatefulSet mariadb-mariadb-master failed error: Pod "mariadb-mariadb-master-0" is invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/bitnami/mariadb": must be unique`

**What you expected to happen**:
Mounting of existing volume to data dir by specifying `master.persistence.existingClaim`

**How to reproduce it** (as minimally and precisely as possible):

**Deployment:**
```
helm install --name mariadb bitnami/mariadb --set \
image.tag=10.2.17-debian-9-r20,\
master.persistence.enabled=true,\
master.persistence.storageClass=ssd,\
master.persistence.existingClaim=mysql-master-storage,\
master.persistence.mountPath="/bitnami/mariadb",\
master.persistence.size=1000Gi,\
rootUser.password=password,\
rootUser.forcePassword=true,\
db.name='',\
replication.password=password,\
slave.replicas=2,\
slave.persistence.storageClass=ssd,\
slave.persistence.size=1000Gi,\
metrics.enabled=true
```

**StorageClass** + **PersistentVolumeClaim**:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-master-storage
spec:
  storageClassName: ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
```

**Anything else we need to know**:
N/A
