### ISSUE TITLE
[stable/datadog] Add volume monitoring documentation

### ISSUE THREAD

**Issue by vvbogdanov87** [helm/charts#7660]
FEATURE REQUEST

It's not clear how to monitor free space on persistent volumes which is crucial for databases. It should be documented.
Example:
```
volumes:
   - hostPath:
       path: /var/lib/kubelet/pods
     name: disks
  volumeMounts:
    - name: disks
      mountPath: /host/disks
      readOnly: true
```
