### ISSUE TITLE
[stable/mariadb] Install-time master.resources syntax?

### ISSUE THREAD

**Issue by pentago** [helm/charts#7690]
**Is this a request for help?**:

Yes
---

Just a simple installation syntax question.

I'm not sure how to set install-time configuration for **master.resources** part.
Documentations says just **{}** but I don't know what does that mean compares to other syntax parts where everything is just a string.

For example, I install the chart this way:

```
helm install --name mariadb bitnami/mariadb --set \
image.tag=10.2.17-debian-9-r22,\
master.persistence.storageClass=ssd,\
master.persistence.existingClaim=mysql-master-storage,\
master.persistence.size=100Gi,\
master.persistence.mountPath=/bitnami,\
rootUser.password=password,\
rootUser.forcePassword=true,\
db.name='',\
slave.replicas=2,\
replication.password=password,\
slave.persistence.storageClass=ssd,\
slave.persistence.size=100Gi,\
metrics.enabled=true,\
master.resources=??? <-----
```

How would this oneliner look with **master.resources** configured with these resources/limits:

```
resources:
  requests:
    cpu: 2
    memory: 3Gi
  limits:
    cpu: 2.5
    memory: 4Gi
```
--

**Version of Helm and Kubernetes**:
Any

**Which chart**:
stable/mariadb

**What happened**:
N/A

**What you expected to happen**:
N/A

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
N/A

Thank you in advance!

**Comment by prydonius** [comment]
Hey @pentago, I think you can do this with `--set master.resources.requests.cpu=2,master.resources.requests.memory=3Gi,master.resources.limits.cpu=2.5,master.resources.limits.memory=4Gi`. However, why not create your own values.yaml file and set all these values within there?

**Comment by pentago** [comment]
@prydonius you're rught about values.yaml, will di that.
Thanks for letting  me know, I'll test this.

**Comment by pentago** [comment]
@prydonius is this how properly formatted custom values.yaml should look?
I'm sure about everything else except **resources** sections.

```
image:
  tag: 8.0.12-debian-9-r25

root:
  password: password

db:
  user: ''
  password: ''
  name: ''

replication:
  enabled: true
  user: replicator
  password: password

master:
  persistence:
    enabled: true
    mountPath: /bitnami
    existingClaim: mysql-master-storage
      storageClass: ssd
    accessModes:
    - ReadWriteOnce
    size: 100Gi
  resources: {
    requests:
      cpu: 2
      memory: 3Gi
    limits:
      cpu: 2.5
      memory: 4Gi
  }

slave:
  replicas: 2
  persistence:
    enabled: true
      storageClass: ssd
    accessModes:
    - ReadWriteOnce
    size: 100Gi
  resources: {
    requests:
      cpu: 2
      memory: 3Gi
    limits:
      cpu: 2.5
      memory: 4Gi
  }

metrics:
  enabled: true
  resources: {
    requests:
      cpu: 0.5
      memory: 100Mi
    limits:
      cpu: 1
      memory: 300Mi
  }
```
