### ISSUE TITLE
[stable/prometheus-adapter] Allow the resource-reader-cluster-role to access Deployments

### ISSUE THREAD

**Issue by jasonwc** [helm/charts#7700]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
Helm Client: v2.9.1
Helm Server: v2.9.1
Kubernetes Version: v1.10.6-gke.2

**Which chart**:
Prometheus Adapter

**What happened**:
When implementing autoscaling for a queue based workload, I found it easiest to associate a `jobs_per_worker` metric with the deployment that works that queue. The metrics are exported by a single pod and associated via correctly labeling the metric.

When configuring my HPA, I used something similar to the following:

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "queue-one-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "queue-one-workers"
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Deployment
        name: queue-one-workers
      metricName: jobs_per_worker
      targetValue: 100
```

When attempting to scale in this fashion, I received errors in the logs of the adapter that indicated that it the cluster role did not have access to deployments and therefore could not fetch the metric.

**What you expected to happen**:
Since `Object` metrics can be associated with `Services`, `Deployments`, etc... I would expect this adapter to be able to scale correctly with object metrics for those resources.

**How to reproduce it** (as minimally and precisely as possible):
Try to scale on an `Object` metric using a Deployment object as the target.

**Anything else we need to know**:
I'd be happy to work on this change. In my fork I simply added `extensions` to the `apiGroups` and `deployments` to the `resources` configuration in https://github.com/helm/charts/blob/master/stable/prometheus-adapter/templates/custom-metrics-resource-reader-cluster-role.yaml

We could make the same change here as well but I wanted to solicit some feedback to see if this makes sense or has other ramifications.

**Comment by steven-sheehy** [comment]
I'm able to associate a metric with a Deployment in my HPA with the existing chart. prometheus-adapter doesn't fetch metrics from a deployment, it fetches it from prometheus and uses your rule to group it by the deployment and expose it via its own REST API to be consumed by HPA. Thus, it shouldn't really need access to Deployment.

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: edge-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metricName: foo_rate
      targetValue: 0.05
      target:
        apiVersion: apps/v1
        kind: Deployment
        name: worker
```
One thing I noticed with your HPA is that it doesn't have "apiVersion: apps/v1" in target like mine. Not sure if it makes a difference. Can you post your custom rule as well? Here's mine:

```yaml
rules:
  custom:
  - seriesQuery: '{__name__=~"^foo_seconds_count$"}'
    resources:
      overrides:
        app:
          group: apps
          resource: deployments
        kubernetes_namespace:
          resource: namespace
    name:
      matches: ""
      as: "foo_rate"
    metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
```
