### ISSUE TITLE
[stable/jenkins] Not able to use Ingress on GKE

### ISSUE THREAD

**Issue by jonstacks** [helm/charts#772]
I was recently trying to deploy jenkins on GKE with an ingress. Here is my config that I'm passing to helm:

```yaml
Master:
  HostName: my.test.domain
  ServiceType: NodePort
  Ingress:
    Annotations:
      kubernetes.io/ingress.allow-http: "false"
    TLS:
      - secretName: mycert
  Cpu: "500m"
  Memory: "512Mi"

Persistence:
  Size: 50Gi
```

From my initial troubleshooting, it appears that when requesting the root page using `kubectl port-forward`, I get the following:

```
HTTP/1.1 403 Forbidden
Date: Thu, 09 Mar 2017 06:25:49 GMT
...
X-You-Are-Authenticated-As: anonymous
...
```

It appears that this response is causing the Google Load Balancer to report the backend as unhealthy and never route traffic to it, so instead it uses the default backend and I just get the standard 502 page.

My first thought was to just use a regular L4 load balancer, but I didn't see any way to add TLS support through kubernetes. I think I will probably end up doing that and just adding the cert out of band.

If it is the case that you can't use ingress on GKE with jenkins, I'd be more than happy to submit a PR adding a notes section and saving someone else the issue I ran into.

*Edit*: I couldn't find a way to add TLS to the load balancerr that kubernetes spins up. It looks like it is only supported if kubernetes were to create a [SSL Load balancer](https://cloud.google.com/compute/docs/load-balancing/tcp-ssl/) instead. Thinking about how to manage this now...
