### ISSUE TITLE
Help with new existingClaim Feature

### ISSUE THREAD

**Issue by franrebo84** [helm/charts#7738]
**Is this a request for help?**: Yes!  I'm trying to deploy this chart with an existing PVC with data. I tried sereral combinations but with no success yet.

This is my config in production-values.yaml:

```
...
master:
  antiAffinity: soft
  persistence:
    enabled: true
    existingClaim: mariadb-data-pvc
    mountPath: /bitnami/mariadb
    annotations:
  config: |-
...
```
Every time I try to install the chart, It creates a new pvc and ignores the existing pvc that I set.

The kubectl describe statefulset.apps

```
Events:
  Type     Reason            Age               From                    Message
  ----     ------            ----              ----                    -------
  Normal   SuccessfulCreate  7m                statefulset-controller  create Claim data-syndb-mariadb-master-0 Pod syndb-mariadb-master-0 in StatefulSet syndb-mariadb-master success
  Warning  FailedCreate      2m (x26 over 7m)  statefulset-controller  create Pod syndb-mariadb-master-0 in StatefulSet syndb-mariadb-master failed error: Pod "syndb-mariadb-master-0" is invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/bitnami/mariadb": must be unique
```

thanks in advance!

---
