### ISSUE TITLE
EFS-Provisioner chart: missing config for endpoints on rbac clusterrole

### ISSUE THREAD

**Issue by innovia** [helm/charts#7767]
**Is this a request for help?**:
update the efs-provisioner chart
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubernetes 1.11.3

**Which chart**:
stable/efs-proviosioner

**What happened**:
`User "system:serviceaccount:default:efs-provisioner" cannot get endpoints in the namespace "default"`

efs-proviosner does not work.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
install the chart on kubernetess 1.11

**Anything else we need to know**:
i added the following section 

missing the rbac section for endpoints:
(not sure all the verbs are needed...)
`clusterrole.yaml`
```yaml
 - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "create", "update", "patch"]
```
