### ISSUE TITLE
[stable/concourse] Workers restart, CrashLoopBackoff

### ISSUE THREAD

**Issue by oded-dd** [helm/charts#7781]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
```
stable/concourse. 1.16.0
```

**What happened**:
Workers keep stalling and crashing/restarting with no clear understanding:
```concourse-postgresql-8589c84fbf-gpl28                             1/1       Running            0          15h
concourse-web-76fc6f6d45-cql8j                                    1/1       Running            0          15h
concourse-worker-0                                                1/1       Running            0          3m
concourse-worker-1                                                1/1       Running            1          16h
concourse-worker-2                                                1/1       Running            2          16h
concourse-worker-3                                                0/1       CrashLoopBackOff   235        16h
```
**What you expected to happen**:
 Workers staying running without stalls/crashes and provide an appropriate log

**How to reproduce it** (as minimally and precisely as possible):
*    Spin up a fresh k8s cluster using kops in AWS
*   Deploy Concourse using the "stable" Helm chart.
*   Wait a few hours and the crashes will start

**Anything else we need to know**:

**Additional Information**:
Relates to issue  #6103

**Comment by oded-dd** [comment]
Hi,

We are using `c5.2xlarge` instances (running concourse helm/chart), using
coreos image :CoreOS-stable-1855.4.0-hvm
And it happens all the time

**Comment by Firebladee** [comment]
The only other thing i did was to up the disk space on the workers from 20Gi to 30Gi.  Other than that I can only suggest getting some monitoring and logs out of the workers to see what is happening.
Sorry I can't be any more help.

**Comment by oded-dd** [comment]
We have 60G disk per worker

**Comment by Yacine-A** [comment]
+1 here anyone working on it ?

**Comment by cirocosta** [comment]
Hi @oded-dd ,

Do you have some more information to share, like logs from the workers? 

Also, it'd be great if you could also share the Concourse version 😁 

The team is now putting some bigger efforts into providing a better experience for Helm (thus, k8s) users, and that would really help!

Thanks!

**Comment by vaughansharman** [comment]
hey @cirocosta, we are experiencing stability issues too, our workers have crashed and restarted hundreds of times in our cluster (they usually recover) but nodes are often getting stuck in a stalled state and then require manual intervention (pruning nodes via fly) which really shouldn't be required, it is making it it difficult for us as a small team and definitely makes it harder to sell the positive points of concourse with such annoying niggles

We are using the latest helm chart with the following overrides on GCP (google cloud), we are also using the vault helm chart to support secrets. Early on we found that upping the storage helped delay stability issues thus the large allocation in the overrides below

```
---
concourse:
  web:
    externalUrl: redacted
    auth:
      github:
        enabled: true
      mainTeam:
        github:
          org: redacted
          team: redacted
    localAuth:
      enabled: false
    kubernetes:
      enabled: false
    vault:
      enabled: true
      authBackend: token
      url: redacted
  worker:
    baggageclaim:
      driver: overlay
web:
  service:
    type: NodePort
secrets:
  githubClientId: redacted
  githubClientSecret: redacted
  vaultClientToken: redacted
persistence:
  worker:
    size: 900Gi
worker:
  replicas: 5
```
