### ISSUE TITLE
Hello, this is more of a question.

### ISSUE THREAD

**Issue by arturgvieira-zz** [helm/charts#7809]
**Is this a request for help?**:
Yes
---

**Version of Helm and Kubernetes**:
v2.9.1

**Which chart**:
incubator/elasticsearch

**What happened**:
I am trying to run this command. I keep getting an error, 
```
helm install incubator/elasticsearch --name cashier-tk-es \
--namespace gitlab-managed-apps \
--set image.repository=docker.elastic.co/elasticsearch/elasticsearch \
--set cluster.xpackEnable=true \
--set cluster.env={XPACK_SECURITY_ENABLED:"true", MINIMUM_MASTER_NODES: "2"}
```

`Error: This command needs 1 argument: chart name`

The error is here,
`{XPACK_SECURITY_ENABLED:"true", MINIMUM_MASTER_NODES: "2"}`

How do I name two values, I am not able to find a symbol that will do. I tried comma, semi-colon,
I also looked at the yaml and kubernetes documentation. I know yaml is a superset of JSON so, a comma should work. However, since it's a shell command I am not sure.

In the documentation, you have the defaults. However, I was unable to locate even one instance of two elements in an object. Therefore unable to install this chart.

**Anything else we need to know**:
Thank you, helm rocks!

**Comment by floriantraber** [comment]
use `--set cluster.env="{XPACK_SECURITY_ENABLED:\"true\", MINIMUM_MASTER_NODES: \"2\"}"` for the last line

**Comment by arturgvieira** [comment]
Hi, thank you for the response, this has me scratching my head. I am trying to enable the user login to secure an ELK stack for a gc kube. I really appreciate the support.

**Comment by cpanato** [comment]
the easiest way is get the values.yaml and make all the changes you want there and then apply
```
helm install incubator/elasticsearch --name cashier-tk-es \
--namespace gitlab-managed-apps \
--values values.yaml
```

**Comment by cpanato** [comment]
I think the way the chart is set it is wrong. I will try to check earlier next week and make a PR if need

**Comment by arturgvieira** [comment]
Ok, thank you

**Comment by arturgvieira** [comment]
I recently tried it with the values.yaml file, here are the results.

I changed the file as follows.
```
cluster:
  name: "elasticsearch"
  # If you want X-Pack installed, switch to an image that includes it, enable this option and toggle the features you want
  # enabled in the environment variables outlined in the README
  xpackEnable: true
  # Some settings must be placed in a keystore, so they need to be mounted in from a secret.
  # Use this setting to specify the name of the secret
  # keystoreSecret: eskeystore
  config: {}
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"
    XPACK_SECURITY_ENABLED: "true"
```
Here are the results:
![screen shot 2018-09-24 at 5 46 08 am](https://user-images.githubusercontent.com/7041980/45952861-309b2c00-bfbd-11e8-8bb6-74362404cb1c.png)

I will keep trying, if you spot the error, please give me a shout. Ok, thank you.
