### ISSUE TITLE
[stable/coredns]I dont understand how to add DNS registers with etcd plugin

### ISSUE THREAD

**Issue by fernandodelaiglesia** [helm/charts#7829]
**Is this a request for help?**:
YES

---

**Version of Helm and Kubernetes**:
helm version: 2.9.1
kube version: 1.7.3

**Which chart**:
stable/coredns

**What happened**:
I'm trying to use a coredns with etcd plugin and add DNS registers using the etcd, but no way, I don't know how to success

**What you expected to happen**:
Once CoreDNS is running, add a simple register using etcd and obtain the register using dig (as per https://coredns.io/plugins/etcd/)

```
%etcdctl put /skydns/local/skydns/x1 "{"ttl":60,"text":"Simpletext"}"
%etcdctl get /skydns/local/skydns/x1
{ttl:60,text:Simpletext}
% dig +short skydns.local TXT @localhost
"Simpletext"
```

**How to reproduce it** (as minimally and precisely as possible):
values.yaml file:
```
isClusterService: false
serviceType: "LoadBalancer"
serviceProtocol: "TCP"
plugins:
  kubernetes:
    enabled: false
  etcd:
    enabled: true
    zones:
    - "skydns.local."
    endpoint: "http://etcd-cluster.my-dns-coredns:2379"
```

```
%helm install --namespace my-dns-coredns --name coredns -f values.yaml stable/coredns

%dig  @localhost skydns.local

; <<>> DiG 9.10.4-P8 <<>> @localhost skydns.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 60274
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;skydns.local.                  IN     A

;; AUTHORITY SECTION:
skydns.local.           30      IN     SOA      ns.dns.skydns.local. hostmaster.skydns.local. 1537367104 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Sep 19 14:25:04 UTC 2018
;; MSG SIZE  rcvd: 95

%etcdctl put /skydns/local/skydns/x1 "{"ttl":60,"text":"Simpletext"}"
%dig +short skydns.local TXT @localhost
%
(empty response)
```

**Anything else we need to know**:

Thanks

**Comment by fernandodelaiglesia** [comment]
Just by changing the values.yalm a little bit makes it work seamssly. Enable log pluging just for logging and set a coredns image version different from the default one: 1.2.0

```
isClusterService: false
serviceType: "LoadBalancer"
serviceProtocol: "TCP"
plugins:
  kubernetes:
    enabled: false
  etcd:
    enabled: true
    zones:
    - "skydns.local."
    endpoint: "http://etcd-cluster.my-dns-coredns:2379"
  log:
    enabled: true
image:
  tag: "1.2.0"

```
