### ISSUE TITLE
[stable/mssql-linux] Inform SQL Server of limits.memory using env MSSQL_MEMORY_LIMIT_MB

### ISSUE THREAD

**Issue by chrisvanderpennen** [helm/charts#7841]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Version of Helm and Kubernetes**:
2.10.0 / 1.10.3

**Which chart**:
stable/mssql-linux

**What happened**:
By default, SQL Server limits itself to 80% of system memory - this may be significantly higher than the value specified by `limits.memory`.
If the environment variable `MSSQL_MEMORY_LIMIT_MB` is set, SQL Server will set its memory limit to that value instead.  [MS docs article](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017)

**What you expected to happen**:
Setting `resources.limits.memory` to also set SQL Server's internal memory limit.

Adding:
```
{{ if .Values.resources.limits.memory }}
  - name: MSSQL_MEMORY_LIMIT_MB
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
        divisor: 1Mi
{{ end }}
```
to the list of environment variables should be enough, and adding this by hand to the deployment looks good locally, but I'm not sure if it should be accompanied by a Kubernetes version check.
