### ISSUE TITLE
Support helm.sh/hook for ordering install

### ISSUE THREAD

**Issue by mdeterman** [helm/charts#7907]
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?** Feature Request / Bug

**Version of Helm and Kubernetes**: N/A

**Which chart**: postgresql / Any

**What happened**: N/A
When setting [helm.sh/hook](https://github.com/helm/helm/blob/master/docs/charts_hooks.md) not all templates are created before the deployment starts

**What you expected to happen**: 
The chart to create all the objects in the correct order

**How to reproduce it** (as minimally and precisely as possible): 

```yaml
---
## postgresql settings
postgresql:
  deploymentAnnotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
```

**Anything else we need to know**:
