### ISSUE TITLE
[stable/percona-xtradb-cluster] Add pod anti-affinity for statefulset's pods

### ISSUE THREAD

**Issue by jaypipes** [helm/charts#7932]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Feature Request**

Since the point of Galera is to provide multi-master no-slave-lag MySQL replication, I don't really see the point of having 3 pods all running Percona XtraDB Cluster on the same physical machine. To spread the Galera cluster over a large failure domain, I think it would be good to add a pod anti-affinity section to the stable/percona-xtradb-cluster's statefulset template. Something like this would work I think?

```
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{ template "percona-xtradb-cluster.fullname" . }}
          topologyKey: kubernetes.io/hostname
```

Unless, of course, I'm missing something and the stateful set automatically places replicas on different nodes in a cluster?
