### ISSUE TITLE
stable/nginx-ingress aws-load-balancer-additional-resource-tags (multiple kv)

### ISSUE THREAD

**Issue by cdenneen** [helm/charts#7993]
```
helm install -n myingress stable/nginx-ingress --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-internal"="yes" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-cert"="arn:aws:acm:us-east-1:XXXXXXXX:certificate/2097f0bc-d43d-4525-822d-03b9b6240840" --set controller.publishService.enabled=true --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol"="http" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports"="https" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-connection-idle-timeout"="3600" --set controller.service.targetPorts.https=http --set controller.service.targetPorts.http=http --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-additional-resource-tags"="Name=ingress,Service=nginx"

```
the only tag created is Name, if you look at the output of the release values it munges the Service into a top level of the values:

```
Service: nginx
controller:
  publishService:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=ingress
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 3600
      service.beta.kubernetes.io/aws-load-balancer-internal: "yes"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:XXXXXXXXX:certificate/2097f0bc-d43d-4525-822d-03b9b6240840
      service.beta.kubernetes.io/aws-ssl-ports: https
    targetPorts:
      https: http
      http: http
```
