### ISSUE TITLE
percona-xtradb-cluster CrashLoopBackOff on container

### ISSUE THREAD

**Issue by mayconfsbrito** [helm/charts#7994]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubectl server 1.11
rke version v0.1.9
helm v2.9.1

**Which chart**:
percona-xtradb-cluster with stable/nfs-client-provisioner

**What happened**:
I've deployed a release of percona-xtradb-cluster with persitence provided by my nfs-client-provisioner, but an error occurs in one of  percona-xtradb-cluster containers.

**What you expected to happen**:
Run all containers of percona-xtradb-cluster without errors with NFS persistence.

**How to reproduce it** (as minimally and precisely as possible):
$ helm install --name nfs-client-release -f nfs-client-values.yaml stable/nfs-client-provisioner

nfs-client-values.yaml:
```
---
# Default values for nfs-client-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategyType: Recreate

image:
  repository: quay.io/external_storage/nfs-client-provisioner
  tag: v3.1.0-k8s1.11
  pullPolicy: IfNotPresent

nfs:
  server: 192.168.100.104
  path: /var/nfs/lib/mysql

# For creating the StorageClass automatically:
storageClass:
  create: true

  # Set a provisioner name. If unset, a name will be generated.
  # provisionerName:
  provisionerName: nfs

  # Set StorageClass as the default StorageClass
  # Ignored if storageClass.create is false
  defaultClass: false

  # Set a StorageClass name
  # Ignored if storageClass.create is false
  name: nfs-percona

  # Allow volume to be expanded dynamically
  allowVolumeExpansion: true

  # Method used to reclaim an obsoleted volume
  reclaimPolicy: Delete

  # When set to false your PVs will not be archived by the provisioner upon deletion of the PVC.
  archiveOnDelete: true

## For RBAC support:
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# If true, create & use Pod Security Policy resources
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/
podSecurityPolicy:
  enabled: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true

  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {kubernetes.io/hostname: '192.168.100.104'}

tolerations: []

affinity: {}
```

$ helm install --name percona-release -f values.yaml stable/percona-xtradb-cluster

values.yaml:
```
# Default values for Percona XtraDB Cluster

## percona image and version
## ref: https://hub.docker.com/r/percona/percona-xtradb-cluster/tags/
image:
  repository: "percona/percona-xtradb-cluster"
  tag: "5.7.19"
  pullPolicy: IfNotPresent

# Desired number of members of xtradb cluster
replicas: 2

## Specify password for root user
##
# mysqlRootPassword: not-a-secure-password
mysqlRootPassword: sqlmestre

## Specify password for xtradb backup user
##
# xtraBackupPassword: replicate-my-data

## Uncomment to create a database user
##
#mysqlUser: test
#mysqlPassword: test

## Allow unauthenticated access, uncomment to enable
##
#mysqlAllowEmptyPassword: true

## Uncomment to Create a database
##
mysqlDatabase: mysql

## hosts to allow root user access from
# set to "127.0.0.1" to deny remote root.
allowRootFrom: "%"

## Persist data to a persistent volume
persistence:
  enabled: true
  ## percona data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  #storageClass: "-"
  storageClass: nfs-percona
  accessMode: ReadWriteMany
  size: 200Gi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {kubernetes.io/hostname: '192.168.100.104' }

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m

configFiles:
  node.cnf: |+
    [mysqld]
    datadir=/var/lib/mysql
    default_storage_engine=InnoDB
    binlog_format=ROW
    innodb_flush_log_at_trx_commit  = 0
    innodb_flush_method             = O_DIRECT
    innodb_file_per_table           = 1
    innodb_autoinc_lock_mode=2
    bind_address = 0.0.0.0
    wsrep_slave_threads=2
    wsrep_cluster_address=gcomm://
    wsrep_provider=/usr/lib/galera3/libgalera_smm.so
    wsrep_cluster_name=galera
    wsrep_sst_method=xtrabackup-v2
    log-bin=percona-release-pxc-0-bin

## When set to true will create sidecar for `prom/mysqld-exporter`
## metrics exporting
metricsExporter: false

## When set to true will create sidecar to tail mysql log
logTail: true
````

**Debugging**
```
NAME                                                             READY   STATUS             RESTARTS   AGE
pod/nfs-client-release-nfs-client-provisioner-5dff88c4bc-4dsw9   1/1     Running            0          19m
pod/percona-release-pxc-0                                        1/2     CrashLoopBackOff   8          19m

NAME                                                              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   A
GE
deployment.extensions/nfs-client-release-nfs-client-provisioner   1         1         1            1           1
9m

NAME                                   DESIRED   CURRENT   AGE
statefulset.apps/percona-release-pxc   2         1         19m

NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
service/kubernetes                 ClusterIP   10.43.0.1      <none>        443/TCP                      2d
service/mysql-service              NodePort    10.43.13.232   <none>        3306:31506/TCP               48m
service/percona-release-pxc        ClusterIP   10.43.96.45    <none>        3306/TCP                     19m
service/percona-release-pxc-repl   ClusterIP   None           <none>        4567/TCP,4568/TCP,4444/TCP   19m

NAME                                      PROVISIONER   AGE
storageclass.storage.k8s.io/nfs-percona   nfs           19m

NAME                                                     STATUS   VOLUME                                     CAP
ACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/mysql-data-percona-release-pxc-0   Bound    pvc-6293dffd-c1cf-11e8-98c0-d094666c59cf   200
Gi      RWX            nfs-percona    19m
```

kubectl logs pod/percona-release-pxc-0 -c database
```
+ . /startup-scripts/functions.sh
++ hostname -i
++ awk ' { print $1 } '
+ ipaddr=10.42.0.80
++ hostname
+ hostname=percona-release-pxc-0
+ echo 'I AM percona-release-pxc-0 - 10.42.0.80'
+ '[' '' = - ']'
I AM percona-release-pxc-0 - 10.42.0.80
++ resolveip -s percona-release-pxc-repl
resolveip: Unable to find hostid for 'percona-release-pxc-repl': host not found
++ echo ''
+ cluster_join=
+ [[ -z '' ]]
+ echo 'I am the Primary Node'
+ init_mysql
+ DATADIR=/var/lib/mysql
+ '[' '!' -e /var/lib/mysql/mysql ']'
I am the Primary Node
+ write_password_file
+ [[ -n sqlmestre ]]
+ cat
+ exec mysqld --user=mysql --wsrep_cluster_name=percona-release-pxc --wsrep_node_name=percona-release-pxc-0 --wsrep_cluster_address=gcomm:// --wsrep_sst_method=xtrabackup-v2 --wsrep_sst_auth=xtrabackup:UKBhBDcfUF --wsrep_node_address=10.42.0.80
```

kubectl logs pod/percona-release-pxc-0 -c logs
```
2018-09-26T21:02:08.808001Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-09-26T21:02:08.808086Z 0 [Warning] WSREP: Node is running in bootstrap/initialize mode. Disabling pxc_strict_mode checks
2018-09-26T21:02:09.026961Z 0 [Warning] InnoDB: New log files created, LSN=45790
2018-09-26T21:02:09.063597Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2018-09-26T21:02:09.117629Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 6e81911a-c1cf-11e8-ade0-423e36b29d4b.
2018-09-26T21:02:09.118003Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2018-09-26T21:02:09.329170Z 0 [Warning] CA certificate ca.pem is self signed.
2018-09-26T21:02:09.362347Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
```

kubectl describe pod/percona-release-pxc-0
```
Name:           percona-release-pxc-0
Namespace:      default
Node:           192.168.100.104/192.168.100.104
Start Time:     Wed, 26 Sep 2018 18:02:06 -0300
Labels:         app=percona-release-pxc
                chart=percona-xtradb-cluster-0.1.5
                controller-revision-hash=percona-release-pxc-5547556657
                heritage=Tiller
                release=percona-release
                statefulset.kubernetes.io/pod-name=percona-release-pxc-0
Annotations:    cni.projectcalico.org/podIP: 10.42.0.80/32
                field.cattle.io/publicEndpoints:
                  [{"addresses":["192.168.100.104"],"port":31506,"protocol":"TCP","serviceName":"default:mysql-service","allNodes":true}]
Status:         Running
IP:             10.42.0.80
Controlled By:  StatefulSet/percona-release-pxc
Init Containers:
  remove-lost-found:
    Container ID:  docker://cca08a06bea5124e1527a9eb4082866688eb2aef357e330fa7506d8ad5b2bc4c
    Image:         busybox:1.25.0
    Image ID:      docker-pullable://busybox@sha256:a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6
    Port:          <none>
    Host Port:     <none>
    Command:
      rm
      -fr
      /var/lib/mysql/lost+found
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 26 Sep 2018 18:02:08 -0300
      Finished:     Wed, 26 Sep 2018 18:02:08 -0300
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/mysql from mysql-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9tjdz (ro)
Containers:
  database:
    Container ID:  docker://34953a4c5b56de787c4133861cf28044e2d4d30cb302534691ee5d5909288a3e
    Image:         percona/percona-xtradb-cluster:5.7.19
    Image ID:      docker-pullable://percona/percona-xtradb-cluster@sha256:eaa3fcb7a5a2aaa03498761962c503f9e5f635e7e997d30fcc7544ec08686c43
    Ports:         3306/TCP, 4567/TCP, 4568/TCP, 4444/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      /startup-scripts/entrypoint.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 26 Sep 2018 18:18:32 -0300
      Finished:     Wed, 26 Sep 2018 18:18:32 -0300
    Ready:          False
    Restart Count:  8
    Liveness:       exec [mysqladmin ping] delay=30s timeout=2s period=10s #success=1 #failure=3
    Readiness:      exec [mysql -h 127.0.0.1 -e SELECT 1] delay=30s timeout=2s period=10s #success=1 #failure=3
    Environment:
      MYSQL_ROOT_PASSWORD:  <set to the key 'mysql-root-password' in secret 'percona-release-pxc'>  Optional: false
      MYSQL_PASSWORD:       <set to the key 'mysql-password' in secret 'percona-release-pxc'>       Optional: false
      XTRABACKUP_PASSWORD:  <set to the key 'xtrabackup-password' in secret 'percona-release-pxc'>  Optional: false
      MYSQL_USER:           
      MYSQL_DATABASE:       mysql
      ALLOW_ROOT_FROM:      %
      CLUSTER_NAME:         percona-release-pxc
      K8S_SERVICE_NAME:     percona-release-pxc-repl
      DEBUG:                true
    Mounts:
      /etc/mysql/conf.d from mysql-config-files (rw)
      /root from slash-root (rw)
      /startup-scripts from mysql-startup-scripts (rw)
      /var/lib/mysql from mysql-data (rw)
      /var/log from var-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9tjdz (ro)
  logs:
    Container ID:  docker://7f3f5f00c37c1228929f67edef92252db4bbcab4a881326a82219d43940b1326
    Image:         busybox:1.25.0
    Image ID:      docker-pullable://busybox@sha256:a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6
    Port:          <none>
    Host Port:     <none>
    Command:
      tail
      -f
      /var/log/mysqld.log
    State:          Running
      Started:      Wed, 26 Sep 2018 18:02:09 -0300
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/log from var-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9tjdz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mysql-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mysql-data-percona-release-pxc-0
    ReadOnly:   false
  slash-root:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  var-log:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  mysql-config-files:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      percona-release-pxc-config-files
    Optional:  false
  mysql-startup-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      percona-release-pxc-startup-scripts
    Optional:  false
  default-token-9tjdz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9tjdz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=192.168.100.104
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From                      Message
  ----     ------            ----                ----                      -------
  Warning  FailedScheduling  21m (x7 over 21m)   default-scheduler         pod has unbound PersistentVolumeClaims
  Normal   Scheduled         21m                 default-scheduler         Successfully assigned default/percona-release-pxc-0 to 192.168.100.104
  Normal   Pulled            21m                 kubelet, 192.168.100.104  Container image "busybox:1.25.0" already present on machine
  Normal   Created           21m                 kubelet, 192.168.100.104  Created container
  Normal   Started           21m                 kubelet, 192.168.100.104  Started container
  Normal   Pulled            21m                 kubelet, 192.168.100.104  Container image "busybox:1.25.0" already present on machine
  Normal   Created           21m                 kubelet, 192.168.100.104  Created container
  Normal   Started           21m                 kubelet, 192.168.100.104  Started container
  Normal   Pulled            19m (x4 over 21m)   kubelet, 192.168.100.104  Container image "percona/percona-xtradb-cluster:5.7.19" already present on machine
  Normal   Created           19m (x4 over 21m)   kubelet, 192.168.100.104  Created container
  Normal   Started           19m (x4 over 21m)   kubelet, 192.168.100.104  Started container
  Warning  BackOff           53s (x93 over 20m)  kubelet, 192.168.100.104  Back-off restarting failed container
```

**Anything else we need to know**:
My NFS server it's ok and a new directory with all persistence is created when the release for percona-xtradb-cluster are deployed.
