### ISSUE TITLE
[stable/kiam] Update serer.service.name from grpc to grpclb

### ISSUE THREAD

**Issue by alvgarvilla** [helm/charts#8002]
**Is this a request for help?**:

---

**BUG REPORT**:

**Version of Helm and Kubernetes**:
Helm 2.10.0
Kubernetes 1.10.7

**Which chart**:
stable/kiam

**What happened**:
One of the templates (server-service.yaml) hasn't been updated with the original template https://github.com/uswitch/kiam/blob/master/deploy/server.yaml. The value:

```
  ports:
    - name: grpc
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
```
should be

```
  ports:
    - name: grpclb
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
```
So it causes issues with the DNS discovery:
https://github.com/uswitch/kiam/issues/144

**What you expected to happen**:
server-service port name is equal to grpclb

**How to reproduce it** (as minimally and precisely as possible):
Install latest chart and see the logs of any of the agents, error like:
_"INFO: grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.kiam-server on 100.64.0.10:53: no such host"_
appears
