### ISSUE TITLE
[stable/mattermost-team-edition] Passthrough configuration

### ISSUE THREAD

**Issue by consideRatio** [helm/charts#8008]
## Feature request
It would  be great to be able to pass through arbitrary configuration that makes sense to the mattermost server. This is certainly not easy with Helm 2 where everything you have entered in anything except within `.Values` is treated as text.

Perhaps you could move the default values declared in `config.tpl` to values.yaml, like auth.gitlab already is. But, you need also an intermediary step...

Look at this, from `config.tpl` for example, notice how you set certain fields based on externalDB.enabled:

```yaml
    "SqlSettings": {
        {{ if .Values.externalDB.enabled }}
        "DriverName": "{{ .Values.externalDB.externalDriverType }}",
        "DataSource": "{{ .Values.externalDB.externalConnectionString }}",
        {{ else }}
        "DriverName": "mysql",
        "DataSource": "{{ .Values.mysql.mysqlUser }}:{{ .Values.mysql.mysqlPassword }}@tcp({{ .Release.Name }}-mysql:3306)/{{ .Values.mysql.mysqlDatabase }}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s",
        {{ end }}
```

So, you want to adjust the value based on something, or not allow the user to configure anything, etc. How would you do this? Well... Consider how my friend @minrk does it in the following essential PR for the Helm chart I'm working on as well: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/941/files#diff-96a1791deadeccb98a6f334d195c73a7R23

By importing the values from `values.yaml`, storing them in a Helm template variable, and manipulating them, and then rendering them as JSON!

---

The benefits of doing it like this can be immense. You would not need to duplicate documentation, but instead refer to the mattermost-server documentation. I would also have been able to configure other hardcoded settings which I now can't like `EmailSettings.EnableSignInWithEmail` etc.

If you feel like a video chat about this, I'm happy to help you discuss this with you.

/cc: @cpanato @jwilander (because Chart.yaml indicates you to be the maintainers)
