### ISSUE TITLE
[stable/traefik] Default *.example.com certificate is still the one showing up despite setting ACME/SSL values

### ISSUE THREAD

**Issue by terenceponce** [helm/charts#8061]
**Is this a request for help?**: 

Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Kubernetes is on 1.9.7-gke.6
Helm/Tiller is on v2.10.0

**Which chart**:

stable/traefik

**What happened**:

Fresh install of Traefik with ACME/SSL settings still load the default `*.example.com` certificate when going to Traefik's Web UI on https://traefik.domain.com

**What you expected to happen**:

Certificate for my site (`*.domain.com`) should be loaded instead when going to https://traefik.domain.com.

**How to reproduce it** (as minimally and precisely as possible):

This is my `traefik-values.yaml`:

```yaml
loadBalancerIP: 12.123.123.123

dashboard:
  enabled: true
  domain: traefik.domain.com
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik

metrics:
  prometheus:
    enabled: true

rbac:
  enabled: true

ssl:
  enabled: true
  enforced: true

acme:
  enabled: true
  staging: true
  logging: true
  email: admin@domain.com
  challengeType: dns-01
  dnsProvider:
    name: digitalocean
    digitalocean:
      DO_AUTH_TOKEN: abcd1234
  domains:
    enabled: true
    domainsList:
      - main: "*.domain.com"
```

This is the run command:

```
helm install stable/traefik --namespace kube-system --values traefik-values.yaml --tls
```

**Anything else we need to know**:

I'm new to Kubernetes, Helm, and Traefik. I'm still trying to wrap my head around everything so please bear with me.

**Comment by terenceponce** [comment]
Managed to make it work now. Here's my final `traefik-values.yaml` for those who encountered the same problem:

```
loadBalancerIP: 12.123.123.123

dashboard:
  enabled: true
  domain: traefik.domain.com
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
  auth:
    basic:
      admin: md5passwordhere

metrics:
  prometheus:
    enabled: true

rbac:
  enabled: true

ssl:
  enabled: true
  enforced: true

acme:
  enabled: true
  staging: false
  logging: true
  email: admin@domain.com
  challengeType: dns-01
  dnsProvider:
    name: digitalocean
    digitalocean:
      DO_AUTH_TOKEN: asdfghjkl
```

I just removed the `domains` part and all of the ingress installed had their own certificates.
