### ISSUE TITLE
[stable/keycloak] The initial admin user creation does not work

### ISSUE THREAD

**Issue by hans-d** [helm/charts#8067]
**BUG REPORT**

**Version of Helm and Kubernetes**:
Helm: 2.11
K8s Client Version: v1.11.3
K8s Server Version: v1.10.6-gke.2

**Which chart**:
stable/keycloak

chart: keycloak-3.4.0
app version: 4.2.1.Final

**What happened**:
Initial user as specified by the values.yml is not created

**What you expected to happen**:
Being able to login with the credentials as set in the applied values

**How to reproduce it** (as minimally and precisely as possible):
Using the values:
```
  ingress:
    enabled: true
    hosts:
      - keycloak.my-url.net

  username: keycloak
  password: "secret"
```
Trying to log in into the console with keycloak:secret fails. (username or password not recognised)

**Anything else we need to know**:
also reported in  #6373 (closed, but not resolved)

applied the prescript settings to make it work
```
preStartScript: |
      /opt/jboss/keycloak/bin/add-user.sh -u keycloak -p secret
      /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u keycloak -p secret
```

**Comment by svyotov** [comment]
I am seeing the same issue happening when in HA mode and with load balancers.

**Comment by dojadop** [comment]
@svyotov @hans-d can you please try with the latest chart.

**Comment by svyotov** [comment]
@dojadop I managed to login without the sticky session and without the PROXY env var.

**Comment by dojadop** [comment]
awesome I'm guessing this issue should be closed then.

**Comment by unguiculus** [comment]
Should be fixed by now.

**Comment by burizz** [comment]
I have the same issue using Chart - keycloak-5.1.2. I cannot login either with the default keycloak user nor with a user created with  :

      /opt/jboss/keycloak/bin/add-user.sh -u admintest -p adminpass
      /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admintest -p adminpass

Tried both with 2 replicas, with 1 replica, wihtout setting any replicas flag at all, etc.

**Comment by Deviad** [comment]
Hello, I have encountered this issue, but I managed to find a workaround (for local development), app is not in prod yet.
```
# PODS >> BEGIN
apiVersion: v1
kind: Pod
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  volumes:
    - name: user-db
  containers:
    - name: user-db
      image: mongo:4.0.12
      ports:
        - name: mongodb-port
          containerPort: 27017
      volumeMounts:
        - name: user-db
          mountPath: /data/db
---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  containers:
    - name: keycloak-db
      image: postgres
      ports:
        - name: kc-db-port
          containerPort: 5432
      volumeMounts:
        - name: keycloak-db-volume
          mountPath: /var/lib/postgresql/data
      env:
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_PORT
          value: "5432"
  volumes:
    - name: keycloak-db-volume
      emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-app
  labels:
    app: keycloak-app
spec:
  containers:
    - image: jboss/keycloak
      name: keycloak-app
      ports:
        - name: kc-port1
          containerPort: 9080
        - name: kc-port2
          containerPort: 9443
        - name: kc-port3
          containerPort: 10990
      env:
        - name: DB_VENDOR
          value: "POSTGRES"
        - name: DB_ADDR
          value: "kc-db-service"
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_USER
          value: "keycloak"
        - name: DB_SCHEMA
          value: "public"
        - name: DB_PASSWORD
          value: "password"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
      command: ["/bin/sh"]
      args: ["-c",
             "echo sleeping 30 secs: hopefully postgres will start;
             sleep 0;
             keycloak/bin/add-user-keycloak.sh -r master -u superadmin -p password;
             keycloak/bin/standalone.sh -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config -Dkeycloak.migration.strategy=OVERWRITE_EXISTING -Djboss.socket.binding.port-offset=1000"]
      volumeMounts:
        - mountPath: /opt/jboss/keycloak/realm-config
          name: keycloak-settings-volume
  volumes:
    - name: keycloak-settings-volume
      hostPath:
        # directory location on host
        path: /Volumes/Data/Projects/clarity/keycloak-realm-config
        # this field is optional
        type: Directory
---
# SERVICES >> BEGIN
apiVersion: v1
kind: Service
metadata:
  name: mongo-user-service
spec:
  ports:
    - port: 27017
      targetPort: mongodb-port
      nodePort: 32000
      protocol: TCP
  selector:
    app: user-db
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: kc-db-service
spec:
  ports:
    - port: 5432
      targetPort: kc-db-port
      nodePort: 32004
      protocol: TCP
  selector:
    app: keycloak-db
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: kc-service
spec:
  ports:
    - port: 9080
      name: "kc-port1"
      targetPort: kc-port1
      nodePort: 32001
      protocol: TCP
    - port: 9443
      name: "kc-port2"
      targetPort: kc-port2
      nodePort: 32002
      protocol: TCP
    - port: 1090
      name: "kc-port3"
      targetPort: kc-port3
      nodePort: 32003
      protocol: TCP
  selector:
    app: keycloak-app
  type: NodePort
```
