### ISSUE TITLE
[stable/prometheus] Add namespace filtering for alert manager service discovery (fails to discover alertmanager)

### ISSUE THREAD

**Issue by quantumlicht** [helm/charts#8130]
**Is this a request for help?**:

No, thanks for the awesome work, I would just like to request a feature or understand the current reason it's implemented like that.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
> helm version 
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
> kubectl version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
`version stable/prometheus:7.1.3`
`appversion: 2.4.2`

**What happened**:
Prometheus cannot scrape targets outside a given namespace so the service discovery for the alertmanager fails.

The current chart implementation assumes that the service account used to discover the prometheus alert manager has access to all namespaces. The file that is "problematic" is:
[server-configmap](https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-configmap.yaml)

This is not the case for me. I only have access to a namespace, where I deploy each of my service as well as the prometheus stack. *Is this bad practice?*

Therefore, for my scrape jobs to succeed, I customize the [default values](https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml)  to specify the namespace. For example:
```
      - job_name: 'prometheus-pushgateway'
        honor_labels: true
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - my-namespace
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
            action: keep
            regex: pushgateway
```
Unfortunately, the [server-configmap](https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-configmap.yaml)
Does not allow to specify this, which causes the scrape job to fail, which ultimately leads to no alertmanager available.

**What you expected to happen**:
I would like to be able for the scrape to only happen in the current namespace. I was able to confirm that this config, in combination with specifying the `server.configMapOverrideName` works:
```
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
->>>  - namespaces:
            names:
            - my-namespace
          role: pod
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: kubernetes_pod_name
```

**How to reproduce it** (as minimally and precisely as possible):
- Create a service account with only access to a certain namespace
- Enable alertmanager
- Notice that the alert manager is not discoverable.

**Anything else we need to know**: Nope :)
