### ISSUE TITLE
[stable/concourse] Chart version 2 - AWS SSM Template Error

### ISSUE THREAD

**Issue by Jeeppler** [helm/charts#8153]
BUG REPORT

**Version of Helm and Kubernetes**:

Helm v2.11.0
Kubernetes  1.10 (AWS EKS)

**Which chart**:

[Concourse CI](https://github.com/helm/charts/tree/master/stable/concourse)

**What happened**:

Enabling [AWS SSM](https://aws.amazon.com/systems-manager/) in the `concourse-values.yaml` with the configurations below will result in an error.

```
concourse:
  web:
    awsSsm:
      # Enable the use of AWS SSM.
      #
      enabled: true

      # AWS region to use when reading from SSM
      #
      region: "us-east-1"
```

or

```
concourse:
  web:
    awsSsm:
      # Enable the use of AWS SSM.
      #
      enabled: true
```
Both configurations will result in the same error:
```
$ helm install --name concourse --namespace cicd stable/concourse -f configs/concourse-values.yaml

Error: render error in "concourse/templates/web-deployment.yaml": template: concourse/templates/web-deployment.yaml:274:26: executing "concourse/templates/web-deployment.yaml" at <.Values.concoures.we...>: can't evaluate field web in type interface {}
```

**What you expected to happen**:

I can deploy concourse using AWS SSM to store parameters and secrets.

**How to reproduce it** (as minimally and precisely as possible):
See `What happened` for more details.

**Anything else we need to know**:

This seems to be a regression in the after bumping Concourse up to 4.2.1: https://github.com/helm/charts/commit/263bc80322056455c7120b51f1992a40667ec686

**Comment by tareks** [comment]
I've also experienced issues that are very likely related to this, but trying to get concourse to consume AWS Secrets Manager. It appears that the template confuses Secrets Manager and Systems Manager resulting in a bit of a configuration deadlock.

I think there's probably a few things that need to be looked at. I've made these changes to get things going at my end for now. These are all in `templates/web-deployment.yaml`.

1) Minor typos (note `concoures` vs `concourse`)
```
            {{- if .Values.concoures.web.awsSecretsManager.region }}
            - name: AWS_REGION
              value: {{ .Values.concoures.web.awsSecretsManager.region }}
            {{- end }}
            {{- if .Values.concoures.web.awsSecretsManager.pipelineSecretTemplate }}
            - name: CONCOURSE_AWS_SECRETSMANAGER_PIPELINE_SECRET_TEMPLATE
              value: {{ .Values.concoures.web.awsSecretsManager.pipelineSecretTemplate | quote }}
...
            {{- if .Values.concoures.web.awsSsm.region }}
            - name: AWS_REGION
              value: {{ .Values.concoures.web.awsSsm.region }}
            {{- end }}
```
2) SSM Seems to be creeping into a Secrets Manager block (not sure if this is on purpose?)

```
            {{- if .Values.concourse.web.awsSecretsManager.enabled }}
            - name: CONCOURSE_AWS_SECRETSMANAGER_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "concourse.concourse.fullname" . }}
                  key: aws-secretsmanager-access-key
            - name: CONCOURSE_AWS_SECRETSMANAGER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "concourse.concourse.fullname" . }}
                  key: aws-secretsmanager-secret-key
            {{- if .Values.secrets.awsSsmSessionToken }}            <======= Is this meant to be here? 
            - name: CONCOURSE_AWS_SECRETSMANAGER_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "concourse.concourse.fullname" . }}
                  key: aws-secretsmanager-session-token
            {{- end }}
```

3) I also experimented with removing the requirement of a key/secret/token for using Secrets Manager as opposed to just allowing an assumeRole to take its place, but that's probably a different issue to be discussed separately.
