### ISSUE TITLE
Enable multiple http/https ports for service that map to Ingress' ports 80/443

### ISSUE THREAD

**Issue by wpnpeiris** [helm/charts#8170]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Version of Helm and Kubernetes**:
Kubernetes  1.11.0
Helm 2.9

**Which chart**:
nginx-ingress

**What happened**:
Cannot expose multiple http/https ports from Ingress Controller Service.

**What you expected to happen**:
It should be configurable (nginx-ingress/value.yaml) Nginx Controller service to expose multiple http/https ports that map to Ingress' ports 80/443. For example, the nginx-ingress chart should be flexible to define target Nginx Controller Service as the following;

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
  name: nginx-ingress-controller-svc
spec:
  loadBalancerIP: xx.xxx.xxx.xxx
  ports:
  - name: 80-http
    nodePort: xxxxx
    port: 80
    protocol: TCP
    targetPort: http
  - name: 8080-http
    nodePort: xxxxx
    port: 8080
    protocol: TCP
    targetPort: http
  - name: 443-https
    nodePort: xxxxx
    port: 443
    protocol: TCP
    targetPort: https
  - name: 8443-tcp
    nodePort: xxxxx
    port: 8443
    protocol: TCP
    targetPort: https
  type: LoadBalancer
```
