### ISSUE TITLE
[Mailhog] - Auth does not seems to work

### ISSUE THREAD

**Issue by g0blin79** [helm/charts#8171]
**Is this a request for help?**:
help
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
seems a bug

**Version of Helm and Kubernetes**:
Helm Version: 2.10.0
Kubernetes Version: 1.9.7-gke.5

**Which chart**:
stable/mailhog

**What happened**:
I try to deploy this chart on a Google Kubernetes Engine Cluster enabling auth, but it doesn't seems to work. I followed instructions contained in chart README to enable the authentication system. This is my values.yaml

```
image:
  repository: mailhog/mailhog
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port:
    http: 8025
    smtp: 1025
  nodePort:
    http: ""
    smtp: ""

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - mailhog.bmeme.cloud
  tls:
    - hosts:
        - mailhog.bmeme.cloud
      secretName: tls-mailhog

auth:
  enabled: true
  existingSecret: ""
  fileName: auth.txt
  fileContents: "mailhog:$2a$04$1xy1SG/3NiSH9TwMWHv97exAuZKqGpojnlQEZTUrZAiqEGOYkHaOK"
## Credentials: 
## user: mailhog
## pwd: mailhog

podAnnotations: {}
resources: {}
env: {}
```

Deploy goes well, when I try to access to web UI, I have the HTTP Basic form (correctly). Insert user and pwd, but I cannot access to the web UI.

**What you expected to happen**:
Access to the UI with the user and password chosen.

**How to reproduce it** (as minimally and precisely as possible):
Try to install this chart using the same values.yml posted before.

`helm install --name mailhog --namespace mailhog stable/mailhog -f values.yml`

**Anything else we need to know**:
Following official authentication instructions at this address https://github.com/mailhog/MailHog/blob/master/docs/Auth.md, it seems that in this chart the needed **args** are missing.
