### ISSUE TITLE
[stable/concourse] Cannot configure `sslmode` without using database client cert/key

### ISSUE THREAD

**Issue by wendorf** [helm/charts#8237]
**Version of Helm and Kubernetes**:

Helm: 2.11.0
Kubernetes: 1.10

**Which chart**:

stable/concourse

**What happened**:

We set the `concourse.web.postgres.sslmode: require` instead of the default `disable` and that caused env vars for CONCOURSE_POSTGRES_CLIENT_CERT, CONCOURSE_POSTGRES_CLIENT_KEY, and CONCOURSE_VAULT_CA_CERT to be set. We are using neither Vault nor client certs, but do want to connect to our database over SSL. Unfortunately, with these set, the ATC cannot connect to our database because it tries to provide the (missing) client cert/key and cannot authenticate to the postgres database.

**What you expected to happen**:

We should be able to set `sslmode` without using Vault or a client cert/key

**How to reproduce it** (as minimally and precisely as possible):

Create a database that can only be accessed over SSL, and whose only user is able to authenticate with a username/pass combo instead of a client cert/key. Then set `concourse.web.postgres.sslmode: require`. The pod will not come up because it cannot authenticate to the database.

**Anything else we need to know**:

We are able to work around this issue with:

```
web:
  env:
  - name: CONCOURSE_POSTGRES_CLIENT_CERT
    value: null
  - name: CONCOURSE_POSTGRES_CLIENT_KEY
    value: null
  - name: CONCOURSE_VAULT_CA_CERT
    value: null
```
