### ISSUE TITLE
[stable/grafana] Grafana pod has unbound PersistentVolumeClaims (will not schedule)

### ISSUE THREAD

**Issue by kabudu** [helm/charts#8245]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes: v1.10.0
Helm: v2.8.2

**Which chart**:
stable/grafana

**What happened**:
Tried to install Grafana but the Grafana pod could not be scheduled because of the error: `pod has unbound PersistentVolumeClaims`, even though I disabled persistence using a custom config, it tried to configure a persistent volume.

**What you expected to happen**:
Grafana pod should have started successfully

**How to reproduce it** (as minimally and precisely as possible):
values.yaml

```
rbac:
  create: true
  pspEnabled: true
serviceAccount:
  create: true
  name:

replicas: 1

deploymentStrategy: RollingUpdate

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10
  periodSeconds: 10

image:
  repository: grafana/grafana
  tag: 5.2.4
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 472
  fsGroup: 472

downloadDashboardsImage:
  repository: appropriate/curl
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

ingress:
  enabled: false
  annotations: {}
  labels: {}
  path: /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false

adminUser: adminuser
adminPassword: thepassword

env: {}

envFromSecret: ""

extraSecretMounts: []

plugins: []

datasources: {}

dashboardProviders: {}

dashboards: {}

dashboardsConfigMaps: {}

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net

ldap:
  existingSecret: ""
  config: ""

smtp:
  enabled: true
  existingSecret: "kube-grafana-smtp"

sidecar:
  image: kiwigrid/k8s-sidecar:0.0.3
  imagePullPolicy: IfNotPresent
  resources:

  dashboards:
    enabled: false
    label: grafana_dashboard
    folder: /tmp/dashboards
  datasources:
    enabled: false
    label: grafana_datasource
```

**Anything else we need to know**:

Output of pod describe:

```
Name:           kube-grafana-7cbf8d8588-24j7p
Namespace:      default
Node:           <none>
Labels:         app=kube-grafana-grafana
                component=grafana
                pod-template-hash=3769484144
                release=kube-grafana
Annotations:    checksum/config=4fa36d33f7bbdc218145adc7680f4e668fb4a5b97087d2977733bba3a319eb72
                checksum/dashboards-config=c60e4ee88c9d3f060dde064744346163eea3c2a7a645cc9250022c436193d3e9
Status:         Pending
IP:
Controlled By:  ReplicaSet/kube-grafana-7cbf8d8588
Init Containers:
  copy-configs:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      cp /tmp/config-volume-configmap/* /tmp/config-volume 2>/dev/null || true; cp /tmp/dashboard-volume-configmap/* /tmp/dashboard-volume 2>/dev/null || true
    Environment:  <none>
    Mounts:
      /tmp/config-volume from config-volume (rw)
      /tmp/config-volume-configmap from config-volume-configmap (rw)
      /tmp/dashboard-volume from dashboard-volume (rw)
      /tmp/dashboard-volume-configmap from dashboard-volume-configmap (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-74z8v (ro)
Containers:
  grafana:
    Image:      grafana/grafana:5.0.4
    Port:       3000/TCP
    Host Port:  0/TCP
    Requests:
      cpu:      100m
      memory:   100Mi
    Readiness:  http-get http://:3000/api/health delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:
      GF_SECURITY_ADMIN_USER:      <set to the key 'grafana-admin-user' in secret 'kube-grafana'>      Optional: false
      GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'grafana-admin-password' in secret 'kube-grafana'>  Optional: false
    Mounts:
      /etc/grafana from config-volume (rw)
      /var/lib/grafana from storage-volume (rw)
      /var/lib/grafana/dashboards from dashboard-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-74z8v (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  config-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  dashboard-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  config-volume-configmap:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-grafana-config
    Optional:  false
  dashboard-volume-configmap:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-grafana-dashs
    Optional:  false
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  kube-grafana
    ReadOnly:   false
  default-token-74z8v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-74z8v
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  1m (x37 over 11m)  default-scheduler  pod has unbound PersistentVolumeClaims
```

Output of `kubectl describe persistentvolumeclaim kube-grafana`:

```
Name:          kube-grafana
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        app=kube-grafana-grafana
               chart=grafana-0.8.5
               component=grafana
               heritage=Tiller
               release=kube-grafana
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type    Reason         Age                From                         Message
  ----    ------         ----               ----                         -------
  Normal  FailedBinding  1m (x63 over 16m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

Persistence has been disabled, so the fact that it has tried to create a PVC is odd. It might be worth noting that I tried to install Grafana with persistence enabled and storage parameters defined, but had the exact same issue.
