### ISSUE TITLE
[stable/influxdb] deploying with config.http.auth_enabled true and setDefaultUser.enabled true does not create the default user

### ISSUE THREAD

**Issue by gboor** [helm/charts#8336]
**Is this a request for help?**:

No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug.

**Version of Helm and Kubernetes**:

Helm: 2.919
Kubernetes: 1.9.7-gke.5

**Which chart**:

stable/influxdb

**What happened**:

When I modified the values.yaml and set both config.http.auth_enabled and setDefaultUser.enabled to true, influxdb deployed, but I could not log in to it.

After disabling authentication, I could log in and saw that no user was created.

This makes sense, because if influxdb is deployed with config.http.auth_enabled set to true, then the setDefaultUser job can never execute the user creation. InfluxDB documentation even states that the first user must be created before auth is turned on, or you will not be able to get into the instance.

Purging influxdb and re-installing it with config.http.auth_enabled set to false created the user as expected.

I then set config.http.auth_enabled to true and tried a helm upgrade, but that did not restart the pod. It did update the config. I had to manually delete the pod and once it restarted, authentication worked fine.

So there is a workaround, but this should "just work", or at least be documented to be a 2-3 stage process.

**What you expected to happen**:

InfluxDB to be deployed with authentication enabled and the user created.

**How to reproduce it** (as minimally and precisely as possible):

helm install influxdb --set setDefaultUser.enabled=true --set config.http.auth_enabled=true stable/influxdb

**Anything else we need to know**:

Given the odd nature of how influx handles authentication, I think the only way for this to work is to deploy influxdb with config.http.auth_enabled set to false (even if it is true in values), create the default user, set config.http.auth_enabled to true and delete the influxdb pod so it is recreated.

**Comment by cam-cen** [comment]
I'm having a similar issue. Setting up influxdb with environment variables to create the default DB/users fails for me. I'm assuming the setDefaultUser stuff interferes with the usual docker route?

For reference these are the extra values I'm passing in. I've verified that they're being passed to helm properly, as well as being passed to the influxdb pod as environment variables

```
persistence:
  enabled: true

setDefaultUser:
  enabled: true

env:
  - name: INFLUXDB_DB
    value: "telegraf"
  - name: INFLUXDB_WRITE_USER_PASSWORD
    value: "telegraf"
  - name: INFLUXDB_WRITE_PASSWORD
    value: "testpassword"

config:
  http:
    auth_enabled: true
```
