### ISSUE TITLE
incubator/elasticsearch Performance Suggestions

### ISSUE THREAD

**Issue by rewt** [helm/charts#8348]
**Is this a request for help?**:
Is it possible to install plugins using this chart?
---

**Comment by rewt** [comment]
After running into [issues](https://github.com/pires/kubernetes-elasticsearch-cluster/issues/237) with [Paulo's kubernetes-elasticsearch-cluster](https://github.com/pires/kubernetes-elasticsearch-cluster) and [figuring out mlockall](https://github.com/kubernetes/kubernetes/issues/3595#issuecomment-423253874), I've carried lessons over to helm and happy to report things working well.

I'd also like to report some performance issues with the stock config.  

Having [elasticsearch service](https://github.com/helm/charts/blob/master/incubator/elasticsearch/templates/client-svc.yaml) associated with client nodes reduces performance significantly if client nodes are not spec'd out with high CPU and RAM.  Using stock version with client nodes, data loads perform extremely slow.

I'm not sure what the client nodes serve in this implementation and have instead pointed elasticsearch service at data nodes instead.  Data loads perform much faster since those nodes are loaded with CPU and RAM.  I do not see any benefit to running additional client nodes to handle requests at this time.

I've also worked out a solution for allowing mlock to run on kubernetes and have created repository https://github.com/rewt/elasticsearch-mlock

- Clone repo and build new image
- Load image to private repo
- Use private repo path in values.yaml
- update both master and data statefulset templates and client deployment as follows

insert 
```
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE 
```
directly above image path in elasticsearch container definition resulting in:

```
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .Values.data.heapSize }} -Xmx{{ .Values.data.heapSize }}"
        {{- range $key, $value :=  .Values.cluster.env }}      
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
#begin new code
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
#end new code            
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

- After updates, repackage chart and deploy.

Is there a way to build these options into the existing chart?
