### ISSUE TITLE
[stable/keycloak] Bug report: Redirection loop when replicas > 1

### ISSUE THREAD

**Issue by swistaczek** [helm/charts#8355]
I am using chart with **Keycloak 4.5.0.Final** which is provided by keycloak chart version 4.0.0. I am trying to deploy HA version on Istio enabled cluster (1.0.2). I managed to run one replica without any troubles but when I set 2 (>1) replicas I get a problem with infinite redirections. It looks like there may be some problem with Infinispan cluster? As I understand it is used for distributed session management?

```
# keycloak-0 instance
[0m[33m06:15:58,460 WARN [org.keycloak.events] (default task-5) type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=10.56.1.1, error=expired_code, restart_after_timeout=true

# keycloak-1 instance
[0m[33m06:15:57,974 WARN [org.keycloak.events] (default task-3) type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=10.56.1.1, error=expired_code, restart_after_timeout=true
```

I deployed istio Gateway & Virtual Service with HTTPS in front of service provided by keycloak Helm Chart.

## Details
Chart maintainer: @unguiculus 
K8s version: 1.10.7-gke.2
I use let's encrypt ssl certificate

**Comment by swistaczek** [comment]
Sticky sessions on networking.istio.io/v1alpha3/**DestinationRule** solved issue but is sticky session required for keycloak cluster @unguiculus?

**Comment by sfitts** [comment]
They weren't in the 3.4.0 version of the chart (which uses 4.2.1.Final of Keycloak).  We only started seeing this behavior when we updated to 4.0.0.

We are actually seeing an issue with only one replica when using the following ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: keycloak
    chart: keycloak-4.0.0
    heritage: Tiller
    release: keycloak
  name: keycloak
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: keycloak-http
          servicePort: http
        path: /auth
```

This works fine using the 3.4.0 version of the chart, but in 4.0.0 we get an error when we go to the admin console -- "invalid parameter redirect_uri".  This is with a single replica.

**Comment by sfitts** [comment]
To clarify, we get the above error when we attempt to navigate to the admin console using the link on the "home page" (the one you get via /auth).

**Comment by vsomasvr** [comment]
I tried the latest version on Google Kubernetes Engine and found severe issues when replicas > 1.
(I haven't tried the previous version though. I will try it ASAP)
When replicas =1 everything is fine.
I had included all the details in my conversation here
https://github.com/helm/charts/pull/8192#issuecomment-429592731

**Comment by weisjohn** [comment]
To @sfitts point, I'm also having this issue with only one replica with an ingress controller with HTTPS. 
It was working fine when using a simple service as a LoadBalancer.

**Comment by weisjohn** [comment]
Seems like #4066 is related.

**Comment by weisjohn** [comment]
Based on the keycloak docs, I think this has everything to do with the way the helm chart is configured or rather the way that keycloak understands host names / protocols, etc.

I did find a fix, but I thought I'd document my lengthy process, maybe to give hope to others.

https://www.keycloak.org/docs/latest/server_installation/index.html#verify-configuration says to go to `https://keycloak.example.com/auth/realms/master/.well-known/openid-configuration` in order to verify the configuration. 

On my server, this looks like:

```json
{
    "issuer": "http://keycloak.example.com/auth/realms/master",
    "authorization_endpoint": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/auth",
    "token_endpoint": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/token",
    "token_introspection_endpoint": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/token/introspect",
    "userinfo_endpoint": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/userinfo",
    "end_session_endpoint": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/logout",
    "jwks_uri": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/certs",
    "check_session_iframe": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/login-status-iframe.html",
    "grant_types_supported": ["authorization_code", "implicit", "refresh_token", "password", "client_credentials"],
    "response_types_supported": ["code", "none", "id_token", "token", "id_token token", "code id_token", "code token", "code id_token token"],
    "subject_types_supported": ["public", "pairwise"],
    "id_token_signing_alg_values_supported": ["ES384", "RS384", "HS256", "HS512", "ES256", "RS256", "HS384", "ES512", "RS512"],
    "userinfo_signing_alg_values_supported": ["ES384", "RS384", "HS256", "HS512", "ES256", "RS256", "HS384", "ES512", "RS512", "none"],
    "request_object_signing_alg_values_supported": ["none", "RS256"],
    "response_modes_supported": ["query", "fragment", "form_post"],
    "registration_endpoint": "http://keycloak.example.com/auth/realms/master/clients-registrations/openid-connect",
    "token_endpoint_auth_methods_supported": ["private_key_jwt", "client_secret_basic", "client_secret_post", "client_secret_jwt"],
    "token_endpoint_auth_signing_alg_values_supported": ["RS256"],
    "claims_supported": ["sub", "iss", "auth_time", "name", "given_name", "family_name", "preferred_username", "email"],
    "claim_types_supported": ["normal"],
    "claims_parameter_supported": false,
    "scopes_supported": ["openid", "phone", "address", "email", "profile", "offline_access"],
    "request_parameter_supported": true,
    "request_uri_parameter_supported": true,
    "code_challenge_methods_supported": ["plain", "S256"],
    "tls_client_certificate_bound_access_tokens": true,
    "introspection_endpoint": "http://keycloak.example.com/auth/realms/master/protocol/openid-connect/token/introspect"
}
```

You can see that there's only `http://` values in there. 

So what I seem I need to do is tell Keycloak to use HTTPS for all connections: 
https://www.keycloak.org/docs/latest/server_installation/index.html#setting-up-https-ssl

But then here I see that I need to actually use the admin to turn on SSL for the admin: https://www.keycloak.org/docs/4.5/server_admin/#_ssl_modes

So, my approach to fixing it was to use `kubectl port-forward svc/keycloak-http 8888:80` to browse to `http://localhost:8888` on my local machine to turn on SSL.

But then I hit a dead end when I refreshed the page and discovered the error message: "HTTPS required".

I need some way of telling the environment variables that I already am behind HTTPS....

So then I discovered additional environment config inside the docker specifications: https://github.com/jboss-dockerfiles/keycloak/blob/master/server/README.md#enabling-proxy-address-forwarding

I discover `PROXY_ADDRESS_FORWARDING`, which seems promising.

Here's the config that worked form me:

```yaml

## https://github.com/helm/charts/tree/master/stable/keycloak

keycloak:
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

  persistence:
    deployPostgres: true
    dbVendor: postgres

  ## Ingress configuration.
  ## ref: https://kubernetes.io/docs/user-guide/ingress/
  ingress:
    enabled: true
    path: /

    annotations:
      kubernetes.io/ingress.class: nginx

    ## List of hosts for the ingress
    hosts:
      - keycloak.example.com

    ## TLS configuration
    tls:
      - hosts:
          - keycloak.example.com
        secretName: keycloak-ssl
```

The part that I had to enable specifically was:

```yaml
keycloak:
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
```

Now, another issue is that trying to `helm upgrade` breaks things, but I'll save that for tomorrow.

cc: @sfitts

**Comment by vsomasvr** [comment]
@weisjohn Thanks for sharing that.
I got the single replica working with similar config as I mentioned here
https://github.com/helm/charts/pull/8192#issuecomment-429592731

Did you try with replicas > 1 ? If so, what's the behavior?
The ultimate goal is to have replication working for prod..

**Comment by weisjohn** [comment]
@vsomasvr I haven't tried with more than one replica yet.  I'm currently unable to scale the deployment at all right now.

**Comment by sfitts** [comment]
FWIW, we have the 3.4.0 chart deployed in multiple clusters, fully replicated and behind multiple ingress definitions using the following values file:

```
keycloak:
  replicas: 3

  ## Username for the initial Keycloak admin user
  username: keycloak

  ## Password for the initial Keycloak admin user
  ## If not set, a random 10 characters password will be used
  password: ""

  ## Ingress configuration.
  ## ref: https://kubernetes.io/docs/user-guide/ingress/
  ## This is the default ingress -- realm specific access is created as part of the Vantiq deploy
  ingress:
    enabled: true
    path: /auth

    annotations:
       kubernetes.io/ingress.class: nginx

    ## List of hosts for the ingress
    hosts:
      - ""

    ## TLS configuration
    tls: []
    # - hosts:
    #     - keycloak.example.com
    #   secretName: tls-keycloak
    
  persistence:

    # Disable deployment of the PostgreSQL chart
    deployPostgres: false

    # The database vendor. Can be either "postgres", "mysql", "mariadb", or "h2"
    dbVendor: postgres

    ## The following values only apply if "deployPostgres" is set to "false"

    # Optionally specify an existing secret
    existingSecret: keycloakdb
    existingSecretKey: password

    dbHost: <ourDBHost>
    dbPort: 5432 # 5432 is PostgreSQL's default port. For MySQL it would be 3306
    dbName: keycloak
    dbUser: keycloak
    dbPassword: <ourDBPassword>

  resources:
    limits:
      cpu: 1
      memory: 4Gi

    requests:
      cpu: 100m
      memory: 1Gi
```

In addition to the ingress created by the chart (which we only use for master realm access) we also deploy an ingress that looks like this (in any given cluster there may be multiple of these, each for a different v-host):

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: vantiq-alik8s
    namespace: alik8s
  spec:
    rules:
    - host: alik8s.vantiq.com
      http:
        paths:
        - backend:
            serviceName: keycloak-http
            servicePort: 80
          path: /auth/
        - backend:
            serviceName: vantiq
            servicePort: 8080
          path: /
    tls:
    - hosts:
      - alik8s.vantiq.com
      secretName: vantiq-cert
```

Other details that may (or may not) matter:

* We use the Nginx Ingress controller (installed from the stable chart hosted here).
* We use a wildcard certificate for our domain
* We have deployed this on multiple Amazon EKS clusters, an Alicloud CS for K8s cluster, and an OpenStack cluster (created via Magnum).
* We've used several different PostgreSQL servers as well, so I doubt that's a factor.

All of this works perfectly using 3.4.0.

Switching to 4.0.0 while leaving everything else the same results in:

* Cluster formation failure when running replicated (exactly as reported by @vsomasvr )
* "invalid parameter" failure when running non-replicated (when accessed via the initial Ingress, we haven't tested it with the second Ingress).

Not sure if this will help anyone, but...  For now we are sticking with 3.4.0 since it is working with our configuration.

**Comment by elvinasp** [comment]
@weisjohn 

Thanks for sharing. I can confirm that on single replica install adding this `extraEnv` to Keycloak helm chart (version 4.0.0) _values.yaml_,  fixes issue with _Invalidparameter: redirect_uri_ for HTTPS ingress to access Keycloak admin interface. 

``` yaml
  keycloak:
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true" 
```

Will deploy 2 node replica soon and update.
