### ISSUE TITLE
[stable/cockroackdb] StatefulSet port name should follow parameter

### ISSUE THREAD

**Issue by nvcnvn** [helm/charts#8410]
https://github.com/helm/charts/blob/97d510b65a8857fe17a7c79afc7f8dd10dee4aeb/stable/cockroachdb/templates/cockroachdb-statefulset.yaml#L255
```
        ports:
        - containerPort: {{ .Values.InternalGrpcPort }}
          name: grpc
        - containerPort: {{ .Values.InternalHttpPort }}
          name: http
```

I think it should follow the name: {{ .Values.ExternalGrpcName }}
