### ISSUE TITLE
[stable/coredns] template.metadata.labels.app does not match selector

### ISSUE THREAD

**Issue by josecv** [helm/charts#8419]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
helm v2.10.0
kubernetes v1.10.8

**Which chart**: `stable/coredns`

**What happened**: attempted to install with `isClusterService: false` and got error from k8s that the pod template's labels do not match the deployment's selector.

**What you expected to happen**: `helm install` goes through successfully.

**How to reproduce it** (as minimally and precisely as possible):
Try to install with values like these:
```
replicaCount: 1

image:
  repository: coredns/coredns
  tag: "1.2.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

serviceType: "ClusterIP"
serviceProtocol: ""
service: {}
rbac:
  create: true
isClusterService: false

servers:
- zones:
  - zone: .
  port: 53
  plugins:
  - name: cache
    parameters: 30
  - name: errors
  - name: health
  - name: loadbalance
    parameters: round_robin
```

**Anything else we need to know**:

It seems like [this line](https://github.com/helm/charts/blob/master/stable/coredns/templates/deployment.yaml#L23) should match [this line](https://github.com/helm/charts/blob/master/stable/coredns/templates/deployment.yaml#L30). Looks like this was introduced by 6aac85d50efc84b90e7928e92ef218e0158a835c which unfortunately forgot to update the `app` label for created pods to `coredns.name` after updating the selector.
