### ISSUE TITLE
[stable/lamp] Cannot write files with sftp

### ISSUE THREAD

**Issue by braykov** [helm/charts#8425]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm - v2.11.0
K8s - v1.9.7-gke.6

**Which chart**: lamp

**What happened**: Tried to copy some files using the sftp feature. The server returned with failure - read only. 

```
Status:	Starting upload of /home/my-user/amp-stack/index.php
Status:	Retrieving directory listing of "/web"...
Status:	Listing directory /web
Command:	put "/home/my-user/amp-stack/index.php" "index.php"
Error:	/web/index.php: open for write: permission denied
Error:	File transfer failed
```

**What you expected to happen**: The files should be transferred successfully

**How to reproduce it** (as minimally and precisely as possible):
Deploy on GCP. Set sftp username and password to activate sftp container. Try to upload a file.

**Anything else we need to know**: This is part of the pod information for sftp:

```
    volumeMounts:
    - mountPath: /home/user/web
      name: httpd-data
      subPath: web
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hg776
      readOnly: true
```

**Comment by HaveFun83** [comment]
Same issue here:
```
sftp> put index.html 
Uploading index.html to /web/index.html
remote open("/web/index.html"): Permission denied
```

**Comment by braykov** [comment]
Here, take some activity

**Comment by lead4good** [comment]
By default, if you log into the sftp container you will be in the home folder of the configured user which is non writable (some weird configuration of the atomz/sftp container). if you cd into the web subfolder or put directly into the web subfolder, the command succeeds. Since this has caused quite some confusion I will add a note in the documentation about this.

**Comment by antoine-briand** [comment]
Hello :wave: I used your chart to install some LAMP environments on a Kubernetes cluster and I have the exact same problem. I can connect, but I can't create or upload folders / files in the web sub-folder. Any ideas? Thank you. 😊 

```
sftp:
  ## sftp.repository default sftp image
  repository: "atmoz/sftp"

  ## sftp.tag default sftp image tag
  tag: "alpine"

  ## sftp.enabled Enables sftp service
  enabled: true

  ## sftp.port Port to advertise service in LoadBalancer mode
  #port: 22

  ## sftp.nodePort  Port to advertise service in Ingress mode
  #nodePort: 30111

  ## sftp.user SFTP User
  user: ajinnov

  ## sftp.password SFTP Password
  password: <<<ERASED>>>

  ## sftp.resources resource requests/limits
  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi
```

![Capture d’écran 2019-09-05 à 14 51 02](https://user-images.githubusercontent.com/4669715/64343451-de47f500-cfec-11e9-8fb3-7f4117e430f7.png)
