### ISSUE TITLE
Prometheus can't get node stats because of IP SAN issue

### ISSUE THREAD

**Issue by BrianHicks** [helm/charts#852]
In GKE and Minikube, using prometheus-2.0.4 against Kubernetes 1.5, the node discovery doesn't work by default because it tries to connect via IP. Neither minikube nor GKE add IP SANs to their certificates, making the scrapes fail. Adding the following to set `__address__` to the hostname works for me on GKE, but I don't think it will work on minikube.

```yaml
- source_labels: [__meta_kubernetes_node_address_Hostname]
  action: replace
  target_label: __address__
  regex: (.+)
  replacement: $1:10250
```
