### ISSUE TITLE
Secret name in create bucket job

### ISSUE THREAD

**Issue by domcar** [helm/charts#8573]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
K8s 1.11.3
Helm 2.10

**Which chart**:
Minio Chart

**What happened**:
If I use an existent secret, the job to create a bucket does not start.

**What you expected to happen**:
Bucket created

**How to reproduce it** (as minimally and precisely as possible):
Just normal deploy with an existing secret for accesskey and secretkey

**Anything else we need to know**:
I gues the problem is in the file 'post-install-create-bucket-job.yaml'
line 30:
```
 - configMap:
        name: {{ template "minio.fullname" . }}
 - secret:
        name: {{ template "minio.fullname" . }}
```
It exept the secret to be called like the `minio.fullname`.

I think it should be something like `{{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ template "minio.fullname" . }}`
