### ISSUE TITLE
[stable/mongodb-replicaset] first pod stuck in status  Init:2/3 

### ISSUE THREAD

**Issue by LuckySB** [helm/charts#8576]
**BUG REPORT**

**Version of Helm and Kubernetes**:
kubernetes 1.12.1
helm 2.9.1

**Which chart**:
[stable/mongodb-replicaset]

**What happened**:
Mongo not started. First pod stuck in status Init:2/3
no logs pod/m-mongodb-replicaset-0 -c bootstrap
no file /work-dir/log.txt
```
NAME                         READY   STATUS     RESTARTS   AGE
pod/m-mongodb-replicaset-0   0/1     Init:2/3   0          2m13s
```

**How to reproduce it** (as minimally and precisely as possible):
values.yaml
```
replicas: 1

persistentVolume:
  enabled: true
  storageClass: "kube"
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}
```
helm upgrade --install m stable/mongodb-replicaset --namespace mongo --values v.yml
