### ISSUE TITLE
[stable/kube2iam] . Chart installs but no pods created 

### ISSUE THREAD

**Issue by Office-Manager** [helm/charts#8630]
**Is this a request for help?**:
Yes 

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Neither

**Version of Helm and Kubernetes**:
helm 2.9.1
kubernetes 1.10  (EKS)

**Which chart**:
stable/kube2iam

**What happened**:
After running the chart I'm not seeing expected output of pods from Daemon set 
```
NOTES:
To verify that kube2iam has started, run:

  kubectl --namespace=kube-system get pods -l "app=kube2iam,release=kube2iam"

kubectl --namespace=kube-system get pods -l "app=kube2iam,release=kube2iam"
No resources found.

```
**What you expected to happen**:
Pods to appear after running `kubectl --namespace=kube-system get pods -l "app=kube2iam,release=kube2iam"`

**How to reproduce it** (as minimally and precisely as possible):

Running the kube2iam chart 
`helm install kube2iam/ --name=kube2iam --namespace=kube-system`

```
19:43 $ helm del --purge kube2iam ; helm install kube2iam/ --name=kube2iam --namespace=kube-system
Error: release: "kube2iam" not found
NAME:   kube2iam
LAST DEPLOYED: Sun Oct 21 19:44:11 2018
NAMESPACE: kube-system
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/ClusterRoleBinding
NAME      AGE
kube2iam  0s

==> v1beta1/DaemonSet
NAME      DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE SELECTOR  AGE
kube2iam  0        0        0      0           0          <none>         0s

==> v1/ServiceAccount
NAME      SECRETS  AGE
kube2iam  1        0s

==> v1beta1/ClusterRole
NAME      AGE
kube2iam  0s


NOTES:
To verify that kube2iam has started, run:

  kubectl --namespace=kube-system get pods -l "app=kube2iam,release=kube2iam"
```

Using the following in the values.yaml 
```
image:
  repository: jtblin/kube2iam
  tag: 0.10.0
  pullPolicy: IfNotPresent


# AWS Access keys to inject as environment variables
aws:
  secret_key: ""
  access_key: ""
  region: ""


verbose: false
rbac:
  create: true
updateStrategy: RollingUpdate
host:
  ip: $(HOST_IP)
  iptables: true
  interface: cni0
  port: 8181
resources:
  limits:
    cpu: 5m
    memory: 16Mi
  requests:
    cpu: 5m
    memory: 16Mi

```

**Anything else we need to know**:

Running on AWS EKS. 
Everything is successfully deployed but I was expecting to see pods being spun up rather than it being empty. There is existing deployments running. 
Even if i could get tips on debugging why nothing is showing it would help me.
