### ISSUE TITLE
missing role verb

### ISSUE THREAD

**Issue by amirkibbar** [helm/charts#8666]
**Is this a request for help?**:
No
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.11.0
Kubernetes: v1.10.3-eks

**Which chart**:
kube2iam

**What happened**:
when installing kube2iam with the image tag 0.10.4 (or anything newer than 0.10.0), the cluster role seem to be missing the "get" verb.

From the kube2iam examples https://github.com/jtblin/kube2iam/blob/master/examples/eks-example.yml:
```
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: kube2iam
    rules:
      - apiGroups: [""]
        resources: ["namespaces","pods"]
        verbs: ["get","watch","list"]
```

but with the chart this cluster role is created (from the code: https://github.com/helm/charts/blob/master/stable/kube2iam/templates/clusterrole.yaml): 
```
   verbs:
      - list
      - watch
```

The kube2iam seem to require the "get" verb to function correctly, without it some pods don't get their AWS credentials as expected.

**What you expected to happen**:
When adding the "get" verb to the cluster role manually post-install kube2iam functions without a problem.

**How to reproduce it** (as minimally and precisely as possible):
Install kube2iam with `--set image.tag=0.10.4`, then try to start a pod with an IAM role annotation. This pod will not be able to use AWS as expected. Then edit the cluster role and add the "get" verb, and the restart the test pod.

**Anything else we need to know**:
