### ISSUE TITLE
[stable/prometheus-operator] Ability to load alertmanager config from ConfigMap

### ISSUE THREAD

**Issue by ev1lm0nk3y** [helm/charts#8706]
Feature Request

**Which chart**:
stable/prometheus-operator

I would like to be able to dynamically load the alertmanager config from a configMap. Right now, it looks like you can either do it from a persitent volume claim or a secret.

**Comment by ajfriesen** [comment]
I think this is already possible with this configuration flag:
alertmanager.configMapOverrideName

It defaults to "" because the alertmanager config is generated through the values.yaml

**Comment by ev1lm0nk3y** [comment]
Actually, I found prometheus.prometheusSpec.additionalAlertManagerConfigs which should allow you to define Secret keys to load up that will configure the alertmanager. Thanks for having me dig deeper into this.

**Comment by ev1lm0nk3y** [comment]
Actually, the description of that variable and the actual implementation of it are different. ([The description](https://github.com/helm/charts/blob/f38d6464c408842dddf649598062b7584fe04b6b/stable/prometheus-operator/README.md#L139)) and the implementations [1](https://github.com/helm/charts/blob/7d0450231c4fe88483d5cb15b760a5886f3c1903/stable/prometheus-operator/templates/prometheus/additionalAlertmanagerConfigs.yaml#L10) and [2](https://github.com/helm/charts/blob/7d0450231c4fe88483d5cb15b760a5886f3c1903/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L138) don't really match up.

**Comment by vsliouniaev** [comment]
@ev1lm0nk3y Here is an example configuration that works using Consul service discovery that I'm using
```
prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
    - consul_sd_configs:
      - server: consul.dev.test:8500
        scheme: http
        datacenter: dev
        tag_separator: ','
        services:
          - metrics-prometheus-alertmanager
```
