### ISSUE TITLE
[stable/nginx-ingress] hostPort for daemonsets

### ISSUE THREAD

**Issue by sander-su** [helm/charts#872]
Can you please add hostPort for daemonsets in the nginx chart?

Our infrastructure has a few dedicated nodes which we use for our ingress controllers. 
These controllers use hostPort to bind to the vm port. The iaas platform takes care of loadbalancing to the ingress instances, don't want to use NodePort as this bounces traffic too much around.

(and preparing for 1.6, rolling updates for daemonsets would also be a nice feature toggle :) )

**Comment by 21stio** [comment]
https://github.com/kubernetes/charts/pull/892 :)

**Comment by sander-su** [comment]
thanks

**Comment by gam-phon** [comment]
Hello, why not doing this also for deployment. I have tried 3 days to use Nginx-ingress without google load balancer on google container engine. to solve it I have just added host port to the deployment.

```
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              hostPort: 443
              protocol: TCP
```
