### ISSUE TITLE
[stable/prometheus-operator] Alert rules are created for components even if scrapes are disabled

### ISSUE THREAD

**Issue by Evesy** [helm/charts#8749]
*Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Version of Helm and Kubernetes**:
*Helm*: 2.10.0
*Kubernetes*: 1.10.6

**Which chart**:
stable/prometheus

**What happened**:
If scraping of a particular Kubernetes components (e.g. API server) is disabled via Helm values, corresponding alert rules are still configured in Prometheus leading to alerts that are constantly firing.

**What you expected to happen**:
If scraping configurations are disabled then alert rules that would rely on those metrics should also be disabled.

**How to reproduce it** (as minimally and precisely as possible):
- Deploy the prometheus operator chart with the below values set:
  ```
  kubeControllerManager:
    enabled: false
  ```
- The below alert rule is still configured in the  `PrometheusRule` resource and will immediately enter an alerting state:
  ```
    - alert: KubeControllerManagerDown
      annotations:
        message: KubeControllerManager has disappeared from Prometheus target discovery.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
      expr: |
        absent(up{job="kube-controller-manager"} == 1)
      for: 15m
      labels:
        severity: critical
  ```
