### ISSUE TITLE
[stable/prometheus-operator] Invalid serviceMonitorNamespaceSelector in prometheus spec

### ISSUE THREAD

**Issue by faheem-nadeem** [helm/charts#8771]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Helm: 2.11.0
Kubernetes: 1.10.8

**Which chart**:
stable/prometheus

**What happened**:
Extra indent in rendered `templates/prometheus/prometheus.yaml` on externally provided `serviceMonitorNamespaceSelector`.

**What you expected to happen**:
Rendered prometheus spec should have been:
```
  serviceMonitorNamespaceSelector:
      matchExpressions:
      - key: name
        operator: Exists
``` 
rather than:
```
  serviceMonitorNamespaceSelector:
      matchExpressions:
    - key: name
      operator: Exists
```

**How to reproduce it** (as minimally and precisely as possible):
Provide values
  ```
  prometheus:
    prometheusSpec:
      serviceMonitorNamespaceSelector:
        matchExpressions:
        - key: name
          operator: Exists
```

**Anything else we need to know**:
Not really just need to remove extra space
