### ISSUE TITLE
[stable/kubernetes-dashboard] serviceaccounts "kubernetes-dashboard" already exists

### ISSUE THREAD

**Issue by omerlh** [helm/charts#8853]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Kubernetes 1.11.3
Helm 2.1.1

**Which chart**:
Kubernetes-Dashboard, 0.7.4

**What happened**:
I tried to install the dashboard using the following command:
```
 helm upgrade --install kubernetes-dashboard stable/kubernetes-dashboard --version 0.7.4 -f values.yaml --namespace kube-system --wait
```
The install failed, with the following error:
```
Error: release kubernetes-dashboard failed: serviceaccounts "kubernetes-dashboard" already exists
```
I delete the service account before running the command.

**What you expected to happen**:
Dashboard installed successfully. 

**How to reproduce it** (as minimally and precisely as possible):
Try to install dashboard using helm.

**Anything else we need to know**:
values.yaml:
```
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: <>
    nginx.ingress.kubernetes.io/auth-url: <>
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.allow-http: "false"
  hosts:
  -  <>
  tls:
  - hosts:
    - <>
    secretName: <>
```
