### ISSUE TITLE
[stable/prometheus] Ability to add extra service labels

### ISSUE THREAD

**Issue by h0tbird** [helm/charts#886]
I would like to set extra service labels in `prometheus` and `alertmanager` services.

For instance:

```
alertmanager:                                                                                                                            
  service:
    labels:
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: "Alertmanager"
server:
  service:
    labels:
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: "Prometheus"
```
