### ISSUE TITLE
[stable/consul] random resource name causing issues

### ISSUE THREAD

**Issue by michaelgeorgeattard** [helm/charts#8879]
We are using https://github.com/roboll/helmfile to define our cluster setup through GitOps.

Helmfile runs diff and only does a `helm upgrade` when there are changes.

Consul has `consul-test.yaml` template with a random name, causing Helmsfile to always detect changes and try to upgrade.

```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-ui-test-{{ randAlphaNum 5 | lower }}"
  annotations:
    "helm.sh/hook": test-success
```

Would it be possible to remove the random part from the resource name, or atleast make the test optional?
