### ISSUE TITLE
[stable/docker-registry] 503 Error

### ISSUE THREAD

**Issue by hbceylan** [helm/charts#8897]
Hi, 
I have installed docker-registry with below command and values file, but readiness and liveness probe always failed with 503 error.

`helm install -f registry-values.yaml stable/docker-registry
`

**registry-values.yaml**

```
ReplicaCount: 1

updateStrategy:
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

podAnnotations: {}

image:
  repository: registry
  tag: 2.6.2
  pullPolicy: IfNotPresent
# imagePullSecrets:
    # - name: docker
service:
  name: registry
  type: ClusterIP
  # clusterIP:
  port: 5000
  # nodePort:
  annotations: {}
  # foo.io/bar: "true"
ingress:
  enabled: true
  path: /
  # Used to create an Ingress record.
  hosts:
    - registry.example.com
  annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
  tls:
    - secretName: registry-ssl
      hosts:
        - "*.example.com"
resources: {}

persistence:
  accessMode: 'ReadWriteOnce'
  enabled: true
  size: 10Gi
  # storageClass: '-'

# set the type of filesystem to use: filesystem, s3
storage: s3

# Set this to name of secret for tls certs
tlsSecretName: registry-ssl
secrets:
  haSharedSecret: ""
  htpasswd: ""


configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: 0.0.0.0:5000
    host: https://registry.example.com
    headers:
      X-Content-Type-Options: [nosniff]
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3

securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 1000

priorityClassName: ""

nodeSelector: {}

tolerations: []
```

**docker-registry pod log**

```
time="2018-10-30T14:49:25Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=fdb22478-23a8-46d0-b5a1-58f42536f843 version=v2.6.2
time="2018-10-30T14:49:25Z" level=info msg="Starting upload purge in 40m0s" go.version=go1.7.6 instance.id=fdb22478-23a8-46d0-b5a1-58f42536f843 version=v2.6.2
time="2018-10-30T14:49:25Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.6 instance.id=fdb22478-23a8-46d0-b5a1-58f42536f843 version=v2.6.2
time="2018-10-30T14:49:25Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=fdb22478-23a8-46d0-b5a1-58f42536f843 version=v2.6.2
172.20.125.220 - - [30/Oct/2018:14:49:27 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:49:34 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:49:37 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:49:44 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:49:47 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:49:54 +0000] "GET / HTTP/2.0" 200 0 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:49:57 +0000] "GET / HTTP/2.0" 503 125 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:50:04 +0000] "GET / HTTP/2.0" 503 125 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:50:07 +0000] "GET / HTTP/2.0" 503 125 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:50:14 +0000] "GET / HTTP/2.0" 503 125 "" "kube-probe/1.10"
172.20.125.220 - - [30/Oct/2018:14:50:17 +0000] "GET / HTTP/2.0" 503 125 "" "kube-probe/1.10"
```

**Liveness and Readiness probes**

```
Liveness:       http-get https://:5000/ delay=0s timeout=1s period=10s #success=1 #failure=3
Readiness:      http-get https://:5000/ delay=0s timeout=1s period=10s #success=1 #failure=3
```

**docker-registry pod events**

```
Events:
  Type     Reason                 Age                     From                                     Message
  ----     ------                 ----                    ----                                     -------
  Normal   Scheduled              12m                     default-scheduler                        Successfully assigned docker-registry-d477c5d8c-qscth to ip-1.1.1.1.ec2.internal
  Normal   SuccessfulMountVolume  12m                     kubelet, ip-1.1.1.1.ec2.internal  MountVolume.SetUp succeeded for volume "docker-registry-config"
  Normal   SuccessfulMountVolume  12m                     kubelet, ip-1.1.1.1.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-gsxgv"
  Normal   SuccessfulMountVolume  12m                     kubelet, ip-1.1.1.1.ec2.internal  MountVolume.SetUp succeeded for volume "tls-cert"
  Normal   Pulling                12m                     kubelet, ip-1.1.1.1.ec2.internal  pulling image "registry:2.6.2"
  Normal   Pulled                 12m                     kubelet, ip-1.1.1.1.ec2.internal  Successfully pulled image "registry:2.6.2"
  Normal   Started                11m (x2 over 12m)       kubelet, ip-1.1.1.1.ec2.internal  Started container
  Normal   Created                11m (x2 over 12m)       kubelet, ip-1.1.1.1.ec2.internal  Created container
  Warning  Unhealthy              10m (x6 over 11m)       kubelet, ip-1.1.1.1.ec2.internal  Liveness probe failed: HTTP probe failed with statuscode: 503
  Normal   Killing                10m (x2 over 11m)       kubelet, ip-1.1.1.1.ec2.internal  Killing container with id docker://docker-registry:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled                 10m (x2 over 11m)       kubelet, ip-1.1.1.1.ec2.internal  Container image "registry:2.6.2" already present on machine
  Warning  Unhealthy              6m49s (x16 over 11m)    kubelet, ip-1.1.1.1.ec2.internal  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  BackOff                2m15s (x17 over 6m25s)  kubelet, ip-1.1.1.1.ec2.internal  Back-off restarting failed container
```
