### ISSUE TITLE
[incubator/vault] feature request: expose consul datacenter via values

### ISSUE THREAD

**Issue by mrbobfrog** [helm/charts#8917]
I would like to see the consul datacenter exposed as a variable in the values file.

**Is this a request for help?**:

No, I have a pull-request prepared.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Version of Helm and Kubernetes**:
kubectl client: v1.12.2
kubernetes server v1.10.8
helm client: v2.11.0
(not using tiller -- using template and deploying from manifest)

**Which chart**:
incubator/vault

**What happened**:
When I started deploying a vault sever via the helm chart, I was hoping to use consul (from the stable chart) as the storage backend. I attempted to deploy the consul-agent container, I received an error in the logs from the `vault-consul-agent` container:
```
* Failed to join 172.17.0.9: Member 'dev-consul-0' part of wrong datacenter 'minikube'
```

**What you expected to happen**:
I expected to be able to provide the datacenter by a parameter in the values file.

**How to reproduce it** (as minimally and precisely as possible):
1. launch consul service from the stable chart, specify any datacenter other than `dc1`
2. launch vault service using consul storage backend and basic example from existing docs
3. check logs from `vault-consul-agent`

**Anything else we need to know**:
Here is a sample vault-values.yaml file to help reproduce the error
```
replicaCount: 1
vault:
  dev: false
  config:
    storage:
      consul:
        address: "localhost:8500"
        path: "vault/"
consulAgent:
  tag: 1.3.0
  join: dev-consul.consul
  gossipKeySecretName: dev-consul-gossip-key
```
