### ISSUE TITLE
[stable/prometheus] Rules yaml not being picked up by prometheus server 

### ISSUE THREAD

**Issue by rishiraaz** [helm/charts#8925]
Is this a request for help?:
**Yes**
Is this a BUG REPORT or FEATURE REQUEST? (choose one):
BUG

**Version of Helm and Kubernetes**:
helm: 2.9.1
k8s: 1.9.10

**Which chart**:
stable/prometheus

**What happened**:
I passed prometheus alert configuration using the below and installed the chart by passing the file which had the below content

```
serverFiles:
  rules.yml:
  groups:
  - name: prometheus.rules
    rules:
    - alert: PrometheusConfigReloadFailed
      expr: prometheus_config_last_reload_successful == 0
      for: 10m
      labels:
        severity: warning
      annotations:
        description: "Reloading Prometheus' configuration has failed for {{$labels.namespace}}/{{$labels.pod}}"
        summary: "Reloading Promehteus' configuration failed"
```

**What you expected to happen**:
To have the above alert taken up by prometheus, which didnt happen

**How to reproduce it**
Place the above contents in a file and execute the below

` helm upgrade prometheus stable/prometheus --version 7.0.0 --recreate-pods --wait -f conent-file.yaml --force`
