### ISSUE TITLE
[stable/grafana] Adding a datasource did not work

### ISSUE THREAD

**Issue by r-divakaran-hrs** [helm/charts#8928]
**Is this a request for help?**:
Yes its a help request.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

I am using the prometheus operator helm chart and everything is working, expect adding a new data source. 
I have enabled the extra data sources option and the side card container is running. 

The datasource I am trying to add is of type cloudwatch. The configmap used looks as below
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-grafana-datasource
  labels:
     grafana_datasource: "1"
  namespace: monitoring
data:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
      - name: Cloudwatch
        type: cloudwatch
        jsonData:
          authType: keys
          defaultRegion: eu-west-1
        secureJsonData:
          accessKey: "AAAAAAAAAAAAAA"
          secretKey: "BBBBBBBBBBBBBBBBBBBBBBBB"
```
When I apply the configmap its getting created successfully and could see as below in grafana-sc-datasources container's logs
```
Working on configmap cloudwatch-grafana-datasource
Configmap with label found
File in configmap datasource.yaml ADDED
```
Checked the grafana container logs and didn't see any errors.
As per https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources I noticed it is mentioned the configmap will be created and picked up during start up. So I tried restarting grafana pod, but with no luck.
To check if my access credentials are correct, using same data when I try to create it from Grafana UI, its working properly.

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
````

**Which chart**:
Using prometheus-operator chart.

**What happened**:
Adding extra data source using configmaps is not working as expected. Please check my explaination above.

**What you expected to happen**:
Expected to see the datasource ready to be consumed as the configmap is created without errors and also container logs looks clean.

**How to reproduce it** (as minimally and precisely as possible):
Please try creating a data source using the configmap I posted above. You might need to use valid AWS access key and password.

**Anything else we need to know**:
