### ISSUE TITLE
nginx-ingress: HealthCheckNodePort can only be set on LoadBalancer service with ExternalTrafficPolicy=Local

### ISSUE THREAD

**Issue by luisyonaldo** [helm/charts#8933]
**BUG REPORT** :
Is not possible to set `HealthCheckNodePort` if the service type is not `LoadBalancer` and `ExternalTrafficPolicy=Local`.

Current documentation specify that it will work for both `NodePort` or `LoadBalancer` which is wrong.

**Which chart**:
nginx-ingress

**What happened**:
you get the following error:
```
spec.healthCheckNodePort: Invalid value: xxx: HealthCheckNodePort can only be set on LoadBalancer service with ExternalTrafficPolicy=Local
```

**What you expected to happen**:
The helm chart should check that `HealthCheckNodePort` is set only when `service.type=LoadBalancer` and `ExternalTrafficPolicy=Local`

**How to reproduce it** (as minimally and precisely as possible):
```yaml
controller:
  service:
    externalTrafficPolicy: "Local"
    type: NodePort
    healthCheckNodePort: 32001 # 32254
```

**Anything else we need to know**:
Also, would be nice to add the option to set the `NodePort` of controller `metrics` service. This way you can do health checks for bare metal clusters. Let me know if this is needed to a PR.
