### ISSUE TITLE
[stable/nginx-ingress] how to do 30x redirect instead of 301 redirect?

### ISSUE THREAD

**Issue by tuananh** [helm/charts#896]
Hi all,

I have 1 service that has only 1 method POST. I've setup nginx-ingress and kube-lego and it works fine for https.

However, it doesn't work on http because 

> POST data is discarded on redirect as a client will perform a GET request to the URL specified by the 301. Period.

According to [this stackoverflow answer](http://stackoverflow.com/questions/13628831/apache-301-redirect-and-preserving-post-data)

Is there anyway for me to change that 301 redirect to sth else, say 307.

Thank you all in advance.

**Comment by mgoodness** [comment]
This doesn't seem to be a Chart problem, but an nginx or nginx-ingress one. I recommend asking in one of those upstream projects.

**Comment by Yo1L** [comment]
Hello,

I know it's an old issue, but if you need to change 308 to 301, just add http-redirect-code in the config part of your controller section (values.yml) like so:
```
controller:
  name: controller
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.21.0"
    pullPolicy: IfNotPresent
    # www-data -> uid 33
    runAsUser: 33

  config: {
    http-redirect-code: "301"
  }
```
