### ISSUE TITLE
[stable/verdaccio] Taint tolerations

### ISSUE THREAD

**Issue by Wenzil** [helm/charts#8982]
**Is this a request for help?**:
---
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Version of Helm and Kubernetes**:
Helm: v2.10.0
Tiller: v2.10.0
Kubernetes: v1.10.7-gke.6

**Which chart**:
stable/verdaccio

**What happened**:
Pod isn't being scheduled because it doesn't tolerate the nodes specified by `nodeSelector`

**What you expected to happen**:
`tolerations` option to add node toleration to verdaccio pods as specified.

E.g.:

```yaml
# config.yaml
nodeSelector:
  dedicated: ops
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "ops"
    effect: "NoSchedule"
```

**How to reproduce it** (as minimally and precisely as possible):
- Create node with label `dedicated=ops` and taint `dedicated=ops`
- Install the chart
  ```sh
  helm install -n ops --name verdaccio stable/verdaccio -f config.yaml
  ```

**Anything else we need to know**:
Don't think so
