### ISSUE TITLE
 [stable/grafana] Allow to add default backend for ingress

### ISSUE THREAD

**Issue by richerlariviere** [helm/charts#9049]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Version of Helm and Kubernetes**:

Helm Client Version: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Helm Server Version: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Kubernetes version: v1.11.3

**Which chart**: stable/grafana

**What happened**: I wanted to setup a default backend in my ingress so I can call my service endpoint using its IP address (I need this because we perform some kind of Health check in an Azure Traffic Manager and our traffic manager only know the ip address.)

**What you expected to happen**: The helm chart should support the possibility to add a default backend:

```yaml
# Ingress manifest example
spec:
  backend:
    serviceName: grafana
    servicePort: '80'
   tls:
   - secretName: cert-grafana
     hosts: "example.com"
...
```

With the current chart, it's impossible.

**Anything else we need to know**: I have experience with Helm charts. I can contribute a PR with such feature. I imagine a declaration like that in the values.yaml

```yaml
# Default backend
ingress:
  defaultBackend:
    serviceName: grafana
    servicePort: '80'
```
