### ISSUE TITLE
[stable/kibana] Ingress with Terraform

### ISSUE THREAD

**Issue by jonatasfreitasv** [helm/charts#9058]
Hi!

How I make this Ingress configuration.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: Kibana.xpto.com
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 5601
        path: /
```

With Terraform Helm with set? My current file is this:

```
resource "helm_release" "kibana" {
  name      = "kibana"
  chart     = "stable/kibana"
  namespace = "backoffice"

  set {
    name = "rbac.create"
    value = "true"
  }

  set {
    name = "env.SERVER_HOST"
    value = "0.0.0.0"
  }

  set {
    name = "env.ELASTICSEARCH_URL"
    value = "http://elasticsearch-client.backoffice:9200"
  }

  set {
    name = "service.externalPort"
    value = "5601"
  }

  timeout="600"
}
```
