### ISSUE TITLE
[incubator/kafka] external connection broke since version 0.11.0

### ISSUE THREAD

**Issue by ericwangqing** [helm/charts#9062]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm: 2.10.0  Kubernetes: 1.10.3

**Which chart**:
incubator/kafka

**What happened**:
Can't connect from external with the version 0.11.0, and the version 0.10.1 is good.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by vemv** [comment]
Kinda off-topic, but @ericwangqing could you please share a working config for 0.10.1?

I've never gotten the external setup working, at any version whatsoever. It always happens one of the following:

* Initial deployment goes badly, e.g. https://github.com/helm/charts/issues/7556
* Deployment goes fine, but the advertised host is still an internal cluster IP, so I can write to Kafka from outside the cluster but not read from it.

**Comment by cablespaghetti** [comment]
I've just got this working. The step missing in the documentation is to update the "listeners" configuration property. Here's my config:
```
configurationOverrides:
  "offsets.topic.replication.factor": 3
  "auto.leader.rebalance.enable": true
  "auto.create.topics.enable": true
  "confluent.support.metrics.enable": false
  "advertised.listeners": |-
    EXTERNAL://{{ .Environment.Name }}-kafka.internal.mydomain.com:$((31090 + ${KAFKA_BROKER_ID}))
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  "listeners": "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092"
external:
  enabled: true
  domain: internal.mydomain.com
```

I'll make a pull request with the documentation update.

**Comment by mrobakowski** [comment]
It seems to work for me if I set:
```yaml
kafka:
  external:
    enabled: true
    servicePort: 9092 # instead of the default 19092
```
