### ISSUE TITLE
[stable/keycloak] basepath problem

### ISSUE THREAD

**Issue by Hokwang** [helm/charts#9070]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm 2.11.0
kubectl 1.12.0

**Which chart**:
stable/keycloak

**What happened**:
I am in enterprise env ( http_proxy, firewall, etc).

this is my values.yaml
```
keycloak:
  basepath: keycloak
  username: keycloakadmin
  password: "1qaz2wsx

  persistence:
    deployPostgres: true
    dbVendor: "postgres"

postgresql:
  postgresUser: keycloak
  postgresPassword: "1qaz2wsx"
  persistence:
    enabled: false
```

If I remove basepath, I can use keycloack normally,
but I write "keycloak" or "keycloak/auth" instead of "auth", keycloak-0 pod always said

Warning  Unhealthy  10s (x6 over 60s)  kubelet, resisa-5  Readiness probe failed: HTTP probe failed with statuscode: 404

Normal   Killing    82s                   kubelet, resisa-5  Killing container with id docker://keycloak:Container failed liveness probe.. Container will be killed and recreated.

**What you expected to happen**:
pod running normally

**How to reproduce it** (as minimally and precisely as possible):
use this values.yaml for test

**Anything else we need to know**:
