### ISSUE TITLE
[stable/prometheus] Can't load gce_sd_config 

### ISSUE THREAD

**Issue by cyrilbkr** [helm/charts#9075]
**Version of Helm and Kubernetes**:
 v1.10.7-gke.6 
helm : 2.9.1
tiller : 2.9.1 

**Which chart**:
stable/prometheus

**What happened**:
Can't load GCE Sd config 

in an already running prometheus values.yaml chart i add this and upgrade my helm config :

      - job_name: node-discovery
        gce_sd_config:
          - project: xxxxxx
            zone: us-east1-c
            port: 9100

but after deleting the existing pod, the prometheus-server pod don't start anymore 

    prometheus-server-6b499f456f-4d24m               1/2       CrashLoopBackOff   6          1m

pod logs : 

    # kubectl logs prometheus-server-6b499f456f-4d24m  -c prometheus-server

    level=error ts=2018-11-07T17:29:01.444929865Z caller=main.go:625 err="error loading config from \"/etc/config/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/config/prometheus.yml\"): parsing YAML file /etc/config/prometheus.yml: yaml: unmarshal errors:\n  line 14: field gce_sd_config not found in type config.plain"

**Comment by europemaster** [comment]
I have the same issue.

**Comment by europemaster** [comment]
@cyrilbkr 
this works for me:
```
global:
  scrape_interval: 60s
  evaluation_interval: 60s
  external_labels:
    monitor: '{name}'
scrape_configs:
  - job_name: '{job_name}'
    scrape_interval: 30s
    gce_sd_configs:
      - project: '{project name}'
        zone: '{zone}'
        filter: '{filter expression}'
        port: {port number for e.g. exporter}
```
