### ISSUE TITLE
[stable/prometheus-operator] servicemonitor are not loaded

### ISSUE THREAD

**Issue by jbouzekri** [helm/charts#9140]
**Is this a request for help?**: Maybe

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm : 2.11.0
K8s : 1.11.3
On Azure AKS

**Which chart**: stable/prometheus-operator

**What happened**:

I created a custom `ServiceMonitor` in my `monitoring` namespace where I installed the chart:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-prometheus-oper-influxdb
  namespace: monitoring
spec:
  jobLabel: influxdb
  selector:
    matchLabels:
      app: influxdb
  namespaceSelector:
    matchNames:
      - prod
  endpoints:
    - port: exporter
      interval: 30s
```

However it is not pick up by Prometheus. After more tant 20 minutes, I still don't see the target on Prometheus web UI.

**What you expected to happen**:

The target to be created.

**How to reproduce it** (as minimally and precisely as possible):

1. Create an AKS cluster
2. Install the chart with standard values but with rbac disabled
3. Create any custom servicemonitor resources. 

It is not picked up.

**Anything else we need to know**: None

**Comment by dojadop** [comment]
Prometheus has `serviceMonitorSelector` that only picks up on service monitors with specific labels. If you didn't customize the values file you will need to add the label to the service monitor that matches the release name of your prometheus operator:

release: <operator_release_name>

Here is an example for nginx-ingress.  My chart release for the operator was called **monitoring**
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: nginx-ingress
spec:
  selector:
    matchLabels:
      release: nginx
  endpoints:
  - port: metrics
```
