### ISSUE TITLE
[stable/prometheus-operator] additionalScrapeConfigs not loaded

### ISSUE THREAD

**Issue by jbouzekri** [helm/charts#9144]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Helm : 2.11.0
K8S : 1.11.3
Azure AKS

**Which chart**: stable/prometheus-operator

**What happened**: I configured the following addtional scrape config:

```
    additionalScrapeConfigs:
      - job_name: 'apiserver'
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https
          # replace the address with the kubernetes service cluster DNS address for AKS
          # since the endpoint address is not reachable
          - target_label: __address__
            replacement: kubernetes.default.svc:443
```

I see it in the Prometheus configuration section on the web UI:

```
- job_name: apiserver
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: default;kubernetes;https
    replacement: $1
    action: keep
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: kubernetes.default.svc:443
    action: replace
```

However nothing in the service discovery tab for this new scrape config.

**What you expected to happen**: It should add a service discovery visible in the web UI section.

**How to reproduce it** (as minimally and precisely as possible):

1. Create an AKS cluster
2. Install the chart with default settings but RBAC disable and the above `additionalScrapeConfigs` configuration

**Anything else we need to know**: None

**Comment by vsliouniaev** [comment]
Looks like the same issue as https://github.com/helm/charts/issues/9140, documentation probably needs an update

**Comment by jbouzekri** [comment]
@vsliouniaev : thanks for your answer. I submitted a pull request #9190 to fix #9140.

However I don't understand how can I update my `additionalScrapeConfigs` config to target the `kubernetes` service.

This is the `kubernetes` service in an AKS cluster:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
spec:
  clusterIP: <ip in the cluster>
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
