### ISSUE TITLE
[stable/prometheus/operator] selector gets merged instead of overwritten

### ISSUE THREAD

**Issue by Morriz** [helm/charts#9181]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bugreport

**Version of Helm and Kubernetes**:
v2.11.0

**Which chart**:
[stable/prometheus/operator] v0.1.16

**What happened**:
I followed the docs that allow to override service selectors, because the helm chart is STILL pointing to a very old k8s version (I suggest to use `component` instead of `k8s-app` asap):
```
# values.yaml:
kubeControllerManager:
  service:
    selector: 
      component: kube-controller-manager
coreDns:
  service:
    selector: 
      component: kube-dns
kubeEtcd:
  service:
    selector: 
      component: etcd-server
kubeScheduler:
  service:
    selector: 
      component: kube-scheduler
```
but they get merged in the services:
```kubectl -n kube-system get svc prometheus-operator-kube-etcd -o yaml```
you see:
```
selector:
    component: etcd-server
    k8s-app: etcd-server
```

**What you expected to happen**:
the old version was:
```
selector:
    k8s-app: etcd-server
```
which should be looking like:
```
selector:
    component: etcd-server
```
**How to reproduce it** (as minimally and precisely as possible):
Use the values as specified.
