### ISSUE TITLE
[stable/concourse] AWS SSM Syntax Error

### ISSUE THREAD

**Issue by Jeeppler** [helm/charts#9199]
**Is this a BUG REPORT** 

The `credentialManager` references in [web-deployment.yaml#L291](https://github.com/helm/charts/blob/master/stable/concourse/templates/web-deployment.yaml#L291) and [web-deployment.yaml#L295](https://github.com/helm/charts/blob/master/stable/concourse/templates/web-deployment.yaml#L295) cause a Go Templating syntax error. I does not matter if the values are specified or not. This issue is a simple typo in the `web-deployment.yaml` file.

```
            {{- if .Values.credentialManager.awsSsm.pipelineSecretTemplate }}
            - name: CONCOURSE_AWS_SSM_PIPELINE_SECRET_TEMPLATE
              value: {{ .Values.credentialManager.awsSsm.pipelineSecretTemplate | quote }}
            {{- end }}
            {{- if .Values.credentialManager.awsSsm.teamSecretTemplate }}
            - name: CONCOURSE_AWS_SSM_TEAM_SECRET_TEMPLATE
              value: {{ .Values.credentialManager.awsSsm.teamSecretTemplate | quote }}
            {{- end }}
```

The error message while trying to install the Helm Concourse Chart using the [Helm](https://www.terraform.io/docs/providers/helm/index.html) provider is:

```
* helm_release.concourse: rpc error: code = Unknown desc = render error in "concourse/templates/web-deployment.yaml": template: concourse/templates/web-deployment.yaml:289:26: executing "concourse/templates/web-deployment.yaml" at <.Values.credentialMa...>: can't evaluate field awsSsm in type interface {}
```

**Version of Helm and Kubernetes**:

Kubernetes 1.10 (AWS EKS)

Helm v2.11.0
Tiller v2.11.0

**Which chart**:

Helm Chart [Concourse](https://github.com/helm/charts/tree/master/stable/concourse) v3.x (Concourse 4).

**What happened**:

Unable to use Helm Chart Concourse v3.x (Concourse 4) together with the [AWS SSM Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html)

**What you expected to happen**:

Able to use AWS SSM Parameter Store together with Helm Chart Concourse v3.x (Concourse 4).

**How to reproduce it** (as minimally and precisely as possible):

Insert the desired configuration in to use the `awsSsm` values in the values.yaml for the Concourse chart and try to deploy it.

```
...
concourse:
  web:

    awsSsm:
      # Enable the use of AWS SSM.
      #
      enabled: true

      ## AWS region to use when reading from SSM
      ##
      region: "us-east-1"
...
secrets:
  awsSsmAccessKey: "<your-aws-access-key>"
  awsSsmSecretKey: "<your-aws-secret-key>"
...
```

The `awsSsmAccessKey` and `awsSsmSecretKey` are normal AWS API Credentials.

**Anything else we need to know**:

This issue was not fixed with: https://github.com/helm/charts/pull/8423
