### ISSUE TITLE
Import Prometheus configMaps from external files

### ISSUE THREAD

**Issue by kenden** [helm/charts#922]
The file [values.yml](https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml) for the Prometheus chart can be pretty long as it contain the content of the configMaps:
- [prometheus.xml](https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L405)
- [alertmanager.xml](https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L383) (is short in this example but could be long)
- [alerts](https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L402) (is empty in this example but could be long)
- [rules](https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L403)

From the documentation [[Accessing Files Inside Templates]](https://github.com/kubernetes/helm/blob/1aafaf84fb2dbed0a24e24e7b5a6a0f0a1454dc5/docs/chart_template_guide/accessing_files.md), it is possible to import external files using `{{ $files.Get . }}`.
This would make the values file shorter, and allow better text editing of the files

**Comment by tomqwu** [comment]
I simply create separate config yaml and override the serverFiles section
```
serverFiles:
  alerts: ""
  rules: ""

  prometheus.yml: |-
```

**Comment by kenden** [comment]
@tomqwu It's a nice idea.
Then we can pass multiple values files with `-f` / `--values` to `helm install/upgrade`

Using this , I then have:
```
$ helm upgrade --install test \
 stable/prometheus \
 --values values.yaml \
 --values values-serverFiles.yaml \
 --values values-alertmanagerFiles.yaml
```

It is nicer as the files are not that long. 
But, it still doesn't allow better text editing of the files. For example, `prometheus.xml` wouldn't look good.

**Comment by travishaagen** [comment]
**Update:** see #1310

In the process of improving this, I am wondering if anyone has ideas about how a _parent_ Helm Chart that includes the Prometheus chart as a child could more easily customize the config.

For example, in my `requirements.yaml` I have,

```
dependencies:
  - name: prometheus
    version: 3.0.2
    repository: https://kubernetes-charts.storage.googleapis.com
```
And in `values.yaml`:

```
prometheus:
  serverFiles:
    prometheus.yml: |-
      rule_files:
        - /etc/config/rules
        - /etc/config/alerts
      scrape_configs:
        - job_name: 'my-other-service'
          scrape_interval: 5s
          metrics_path: '/metrics/prometheus'
          scheme: http
          static_configs:
            - targets: ['my-other-service:8080']
```
As you can see, `my-other-service:8080` is hard-coded, and you cannot currently use template variables in `values.yaml`.

So, the gist of what I am after is some way to configure this, but the flexibility to not have to have things hard coded.

There is the concept of "[global values](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#global-chart-values)".

**Comment by empyrean987** [comment]
Can someone provide an example on how you override the alerts section to create alerts? Not the AlertManager but Alerts themselves.

**Comment by kenden** [comment]
@empyrean987 
We're calling `helm upgrade --values values-serverFiles.yaml`  
with `values-serverFiles.yaml` having the content:
```
## Prometheus server ConfigMap entries
serverFiles:
  alerts: |-
    ## alert.rules ##
    ALERT NodeLoadAverage
      IF ((node_load5 / count without (cpu, mode) (node_cpu{mode="system"})) > 3)
      FOR 2m
      ANNOTATIONS {
        SUMMARY = "{{$labels.instance}}: High LA detected",
        DESCRIPTION = "{{$labels.instance}}: LA is high"
      }
    # more alerts below
    ....
```
Hope this helps.

**Comment by wangybelle** [comment]
Hello, kenden

serverFiles:
  alerts: {}
  rules: |-
    ALERT K8SNodeDown
      IF up{job="kubelets"} == 0
      FOR 1h
      LABELS {
        service = "k8s",
        severity = "warning"
      }
      ANNOTATIONS {
        prefix = "[{{ .Labels.cluster }}]",
        summary = "Kubelet cannot be scraped",
        description = "Prometheus could not scrape a {{ .Labels.job }} for more than one hour",
      }
 prometheus.yml:
    rule_files:
      - "/etc/config/rules"
      - "/etc/config/alerts"

**I installed prometheus 2.0. In vlaues.yaml file, rules are configured as the above.
But I got following error. Can you help me? Thanks a lot!**

level=info ts=2018-01-25T09:21:45.950360872Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-25T09:21:45.9518776Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2018-01-25T09:21:45.953629284Z caller=manager.go:485 component="rule manager" msg="loading groups failed" err="yaml: unmarshal errors:\n line 1: cannot unmarshal !!str ALERT K... into rulefmt.RuleGroups"
level=error ts=2018-01-25T09:21:45.95372839Z caller=main.go:413 msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
level=info ts=2018-01-25T09:21:45.954347917Z caller=kubernetes.go:100 component=notifier discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2018-01-25T09:21:45.95539898Z caller=main.go:356 msg="Error loading config" err="one or more errors occurred while applying the new configuration (--config.file=/etc/config/prometheus.yml)"

**Comment by ubhide** [comment]
I had the same problem. The format must be YAML and not the plain text syntax. For e.g.
```
serverFiles:
  rules: {}
  alerts:
    groups:
    - name: resource-usage.rules
      rules:
      - alert: NodeSwapUsage
        expr: (((node_memory_SwapTotal-node_memory_SwapFree)/node_memory_SwapTotal)*100) > 75
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "{{$labels.instance}}: Swap usage detected"
          description: "{{$labels.instance}}: Swap usage usage is above 75% (current value is: {{ $value }})"
```
