### ISSUE TITLE
[stable/traefik] Be able to specify existing Kubernetes secrets as mounts for etcd backend

### ISSUE THREAD

**Issue by gaui** [helm/charts#9259]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

Helm 2.11, Kubernetes 1.12

**Which chart**:

stable/traefik

**What happened**:

Paths for etcd certs have to be mounted by hand into the Traefik pod, there is no functionality that auto-mounts those secrets into the pod.

**What you expected to happen**:

Be able to specify pre-existing secrets (for example those created by Kubernetes) that will be mounted into the Traefik pod.

Something like this in the `values.yml` for `etcd`:

```
etcd:
  endpoint: etcd-service:2379
  useAPIV3: false
  watch: true
  prefix: traefik

  tls:
    ca:
      name: kube-ca
      secret: true
    cert:
      name: kube-etcd
      secret: true
    key:
      name: kube-etcd-key
      secret: true
```

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

This feature could also be good for other backends as well. This methodology applies to all.
