### ISSUE TITLE
[stable/postgres] does not create user or database

### ISSUE THREAD

**Issue by chris-malloy-mri** [helm/charts#9269]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**: 
Helm 2.11.0
Kubernetes 1.12

**Which chart**: stable/postgres

**What happened**: did not create user or database

**What you expected to happen**: create user and database

**How to reproduce it** (as minimally and precisely as possible):
```
  postgresqlUsername: exampleuser
  postgresqlPassword: examplePassword123
  postgresqlDatabase: exampledb

  service:
    type: LoadBalancer
  persistence:
    storageClass: "-"
  master:
    persistence:
        existingClaim: "existing-claim" # this is a NFS PV

  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true

  replication:
    enabled: false
```

**Anything else we need to know**:
If you exec into the container and create the user and database manually everything else works well. You may also need to delete the empty volume from the volumeClaimTemplates in statefulset.yaml.

The bitnami chart for MySQL already works great. It would be nice to make this chart consistent with that one.
