### ISSUE TITLE
[stable/prometheus-operator] how to use an existed Persistent Volume Claim

### ISSUE THREAD

**Issue by shangjin92** [helm/charts#9288]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm: v2.11.0
k8s: v1.11.2

**Which chart**:
stable/prometheus-operator

**What happened**:
I have already created PV and PVC, and I want to use the existed PVC for prometheus server. But in prometheus-operator, I found that value.yaml only has volumeClaimTemplate configuration.  In prometheus-operator storage's user-guide, it seems like volumeClaimTemplate is to create PVC dynamic. So I wander how to use PVC which I have created, like volumeMounts in prometheus.

link
https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md

```yaml
volumeClaimTemplate:
    description: PersistentVolumeClaim is a user's request for and claim
     to a persistent volume
```

**What you expected to happen**:
I want to use PVC that I have created

**Comment by chrisob** [comment]
You should only create the PV (_not_ the PVC) beforehand.  `prometheus-operator` can automatically create a PVC based on an existing PV.

For example, my `default-values.yaml`:
```yaml
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          # Name of the PV you created beforehand
          volumeName: MY-PREEXISTING-PV
          accessModes: ["ReadWriteOnce"]
          # StorageClass should match your existing PV's storage class
          storageClassName: gp2
          resources:
            requests:
              # Size below should match your existing PV's size
              storage: 500
```

Keep in mind, if you do a `helm delete` on your chart, [the PVC **will not be cleaned up**](https://github.com/coreos/prometheus-operator/issues/1897).
