### ISSUE TITLE
[stable/prometheus] Node exporter not running on master node

### ISSUE THREAD

**Issue by muhammadhanif** [helm/charts#9340]
**Is this a request for help?**:

Yes

---

**Version of Helm and Kubernetes**:

Version of Helm:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
Version of Kubernetes:
```
v1.11.3
```

**Which chart**:
prometheus

**What happened**:
I succesfully deployed prometheus on my kubernetes cluster (3 master nodes & 2 worker nodes). When I tried some queries on prometheus dashboard (for example: `node_memory_Cached`), I only got metrics from worker node. There are no metrics from master node.  

I checked on every node, node exporter only running on worker nodes.

**What you expected to happen**:
Node exporter runs on master nodes and exposes their metrics.

**Comment by muhammadhanif** [comment]
I have solved this issue by adding this to [`values.yaml`](https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L419):

```
## Node tolerations for node-exporter scheduling to nodes with taints
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
```

Thank you.

**Comment by muhammadhanif** [comment]
I have solved this issue by adding this to [`values.yaml`](https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L419):

```
## Node tolerations for node-exporter scheduling to nodes with taints
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
```

Thank you.
