### ISSUE TITLE
[stable/ghost] Unable to use externalDatabase info

### ISSUE THREAD

**Issue by kristianfreeman** [helm/charts#9347]
**Is this a request for help?**:

Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** Bug report

**Version of Helm and Kubernetes**:

```
byteconf $ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

byteconf $ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Which chart**:

[stable/ghost](https://github.com/helm/charts/tree/master/stable/ghost)

**What happened**:

I'm trying to start up a new Ghost blog inside of my k8s cluster. The default values work when I install a new Ghost blog (meaning the built-in MariaDB/persistence support), but I've recently moved the DB out into RDS and want to use the external db functionality in the chart (via the `externalDatabase` section of the config). 

Here's the command I'm running: `helm install stable/ghost --name blog -f k8s/ghost-values.yaml`

Passing in `externalDatabase` values to configure ghost returns the error:

`2018/11/17 11:48:07 warning: skipped value for externalDatabase: Not a table.`

The relevant section of the chart values (`k8s/ghost-values.yaml`) looks like this:

```yaml
externalDatabase:
  host: myhost
  port: myport
  user: myuser
  password: mypass
  database: mydb
```

If it's relevant, I've created [a gist](https://gist.github.com/signalnerve/100a8bcacaad829fe9aae0669adf8745) with the full chart info here, too!

**What you expected to happen**:

The chart parses the fields within the `externalDatabase` section of my config and passes them into the Ghost pod!

**How to reproduce it** (as minimally and precisely as possible):

Should be recreatable by attempting to install stable/ghost in a cluster using the provided config values.

**Anything else we need to know**:

I'm pretty new to Helm, so let me know if I can clarify anything! Appreciate the help :)

**Comment by tompizmor** [comment]
Hello @signalnerve,

Your settings seem correct to me. Did you create the user and database in RDS before launching the ghost chart? 
Note the chart expect this database to already exists.

**Comment by signalnerve** [comment]
Hey @tompizmor! Yep, the RDS database has already been created. FWIW, I interpreted this as a YAML parsing error of some kind, not necessarily something at the DB level. Does that seem correct to you?

**Comment by tompizmor** [comment]
Yes, it seems a parsing error that should be fixed: https://github.com/helm/helm/issues/3939

In any case, I am not able to reproduce it and I have the same helm version (2.11.0). I didn't tried with an RDS database but with an external mariadb chart deployed with this options:

```
helm install --name mariadb-ghost stable/mariadb --set db.user=ghost,db.password=qwer1234,db.name=bitnami_ghost
```

Then I installed Ghost with this values.yaml file:

```
image:
  registry: docker.io
  repository: bitnami/ghost
  tag: 2.8.0
  pullPolicy: IfNotPresent

volumePermissions:
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: latest
    pullPolicy: Always

ghostHost: ghosty.io
ghostPath: /
ghostUsername: user@example.com
ghostEmail: user@example.com
ghostBlogTitle: Testing External DB
allowEmptyPassword: "yes"

externalDatabase:
  host: mariadb-ghost-mariadb
  port: 3306
  user: ghost
  password: qwer1234
  database: bitnami_ghost

mariadb:
  enabled: false
  replication:
    enabled: false
  db:
    name: bitnami_ghost
    user: bn_ghost
  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi

service:
  type: ClusterIP
  port: 80
  nodePorts:
    http: ""
  externalTrafficPolicy: Cluster

securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /bitnami

resources:
  requests:
    memory: 512Mi
    cpu: 300m

ingress:
  enabled: true
  hosts:
  - name: ghosty.io
    tls: false
    certManager: false
    tlsSecret: ghost.local-tls
    annotations:
  secrets:
```

And checking the logs I see how Ghost was able to find the database service:

```
k logs -f ghost-854ddc9b78-md74g

Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb-ghost-mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb-ghost-mariadb:3306
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Creating admin user...
ghost   INFO  The admin user was created
ghost   INFO
ghost   INFO  ########################################################################
ghost   INFO   Installation parameters for ghost:
ghost   INFO     Email: ghost@email.com
ghost   INFO     Password: **********
ghost   INFO   (Passwords are not shown for security reasons)
ghost   INFO  ########################################################################
ghost   INFO
nami    INFO  ghost successfully initialized
```
