### ISSUE TITLE
Unable to setup Docker Registry with persistence enabled

### ISSUE THREAD

**Issue by ishantanu** [helm/charts#9350]
**Is this a request for help?**:

YES

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:
Helm version:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Kubernetes version:
```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
Docker registry (stable)

**What happened**:
Docker registry not deploying due to timeout while attaching volumes. Here's what I am seeing:
```
Events:
  Type     Reason            Age                 From                   Message
  ----     ------            ----                ----                   -------
  Warning  FailedScheduling  22m (x5 over 22m)   default-scheduler      pod has unbound PersistentVolumeClaims (repeated 4 times)
  Normal   Scheduled         22m                 default-scheduler      Successfully assigned docker-reg/docker-private-registry-docker-registry-d49dc6fdd-d6slh to 192.168.1.19
  Warning  FailedMount       2m6s (x9 over 20m)  kubelet, 192.168.1.19  Unable to mount volumes for pod "docker-private-registry-docker-registry-d49dc6fdd-d6slh_docker-reg(cef52eea-eb07-11e8-85c9-b06ebfd124ff)": timeout expired waiting for volumes to attach or mount for pod "docker-reg"/"docker-private-registry-docker-registry-d49dc6fdd-d6slh". list of unmounted volumes=[data]. list of unattached volumes=[auth data docker-private-registry-docker-registry-config default-token-xc4p7]
```

**What you expected to happen**:
Docker registry should be deployed without such issues.

**How to reproduce it** (as minimally and precisely as possible):
Run:
```
helm install stable/docker-registry \
--namespace docker-reg \
--name docker-private-registry \
--values values.yml
```

**Anything else we need to know**:
`values.yml` config:
```
# Default values for docker-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy:
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

podAnnotations: {}

image:
  repository: registry
  tag: 2.6.2
  pullPolicy: IfNotPresent
# imagePullSecrets:
    # - name: docker
service:
  name: registry
  type: ClusterIP
  # clusterIP:
  port: 5000
  # nodePort:
  annotations: {}
  # foo.io/bar: "true"
ingress:
  enabled: false
  path: /
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
persistence:
  accessMode: 'ReadWriteOnce'
  enabled: true
  size: 10Gi
  storageClass: 'rook-ceph-block'

# set the type of filesystem to use: filesystem, s3
storage: filesystem

# Set this to name of secret for tls certs
# tlsSecretName: registry.docker.example.com
secrets:
  haSharedSecret: ""
  htpasswd: "huhuma:$2y$05$bnLaYEdTLSpXXXXz2ULza2Ob.XXXXXXXXar9WUujiGzuaZ7TIsTK2W"
# Secrets for Azure
#   azure:
#     accountName: ""
#     accountKey: ""
#     container: ""
# Secrets for S3 access and secret keys
#   s3:
#     accessKey: ""
#     secretKey: ""
# Secrets for Swift username and password
#   swift:
#     username: ""
#     password: ""

# Options for s3 storage type:
# s3:
#  region: us-east-1
#  bucket: my-bucket
#  encrypt: false
#  secure: true

# Options for swift storage type:
# swift:
#  authurl: http://swift.example.com/
#  container: my-container

configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3

securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 1000

priorityClassName: ""

nodeSelector: {}

tolerations: []
```

The pvc gets provisioned correctly and is also bound:
```
root@gamman4:/home/devops/rke-k8s/helm-docker-reg# kubectl get pvc -n docker-reg
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
docker-private-registry-docker-registry   Bound    pvc-ce4cb46d-eb07-11e8-9b5d-2cfda16d3cfd   10Gi       RWO            rook-ceph-block   28m
```
