### ISSUE TITLE
[stable/redmine] smtp config from env is not working

### ISSUE THREAD

**Issue by Huangsir** [helm/charts#9530]
My smtp config in values.yml: 

```
smtpHost: localhost
smtpPort: 25
smtpUser: user
smtpPassword: pass
smtpTls: false
```

And the env in container is like: 

```sh
# env | grep SMTP
SMTP_TLS=false
SMTP_PORT=25
SMTP_PASSWORD=pass
SMTP_HOST=localhost
SMTP_USER=user
```

But i can't see any value about smtp in `/opt/bitnami/redmine/config/configuration.yml` and the web page shows 
![image](https://user-images.githubusercontent.com/3870517/48976908-be34ee00-f0ca-11e8-9233-d32a93f2887a.png)

**Comment by tompizmor** [comment]
I just tried and I can see the SMTP section propery configured  in the `/opt/bitnami/redmine/config/configuration.yml`.

```
# default configuration options for all environments
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.gmail.com
      port: 587
      domain: example.net
      authentication: :login
      user_name: XXXXXXXXXXXX@gmail.com
      password: XXXXXXXXXXXX
```

Do you have the logs of the redmine pod during the first initialization?
