### ISSUE TITLE
[stable/prometheus-operator] prometheus-config-reloader and rules-configmap-reloader have insufficient CPU resources

### ISSUE THREAD

**Issue by paskal** [helm/charts#9540]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?**: Bug rereport

**Version of Helm and Kubernetes**:
```
➜  ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.11", GitCommit:"42df8ec7aef509caba40b6178616dcffca9d7355", GitTreeState:"clean", BuildDate:"2018-11-08T20:06:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus-operator from https://github.com/helm/charts/pull/9516

**What happened**:
Following alerts fire:

>message
>    41% throttling of CPU in namespace monitoring for container prometheus-config-reloader in pod prometheus-operator-prometheus-0.
>runbook_url
>    https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh

>message
>    33% throttling of CPU in namespace monitoring for container rules-configmap-reloader in pod prometheus-operator-prometheus-0.
>runbook_url
>    https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh 

**What you expected to happen**:
No alerts on prometheus-operator itself

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/prometheus-operator` with https://github.com/helm/charts/pull/9516 patch applied (new alerts) on GKE cluster

**Anything else we need to know**:
It seems like limits for this pod are not enough and should be increased:
```
    name: rules-configmap-reloader
    resources:
      limits:
        cpu: 5m
        memory: 10Mi
      requests:
        cpu: 5m
        memory: 10Mi
---
    name: prometheus-config-reloader
    resources:
      limits:
        cpu: 10m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 50Mi
```
Other possible case is busy loop, in this case no resources will be enough.
