### ISSUE TITLE
[stable/metricbeat] unable to use extraVolumes

### ISSUE THREAD

**Issue by david-maumenee** [helm/charts#9547]
**BUG REPORT**:

**Version of Helm and Kubernetes**: helm v2.11.0 / K8s 1.11

**Which chart**:
stable/metricbeat

**What happened**:
When using extraVolumes and extraVolumeMounts in the values.yaml (to setup the elasticsearch ssl access via secret) I get an the error
```
Error: release metricbeat failed: Deployment.apps "metricbeat" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "conf"
```

**What you expected to happen**:
Volume are created without error.

**How to reproduce it** (as minimally and precisely as possible):

1] edit the default values.yaml and uncomment extraVolumes and extraVolumeMounts
```yaml
extraVolumes:
  - hostPath:
    path: /var/log
    name: varlog
extraVolumeMounts:
  - name: varlog
    mountPath: /host/var/log
    readOnly: true
```
see [values-volume.yaml.txt](https://github.com/helm/charts/files/2616402/values-volume.yaml.txt)

2] install the app
```
helm install stable/metricbeat --name metricbeat -f values-volume.yaml
Error: release metricbeat failed: Deployment.apps "metricbeat" is invalid: spec.template.spec.containers[0].volumeMounts[2].name: Not found: "varlog"
```
**Anything else we need to know**:
To fix the issue, add this at end of https://github.com/helm/charts/blob/master/stable/metricbeat/templates/deployment.yaml 

```yaml
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
```
The file https://github.com/helm/charts/blob/master/stable/metricbeat/templates/daemonset.yaml is OK.

After this correction maybe you an add an example on the documentation to explain how to use extraVolumes, extraVolumeMounts and secret to set the SSL key and cert to access a secure elastic

create a secret
```
kubectl create secret generic elastic-ssl-config --from-file=./cert.key --from-file=./cert.pem
```
update the values.yaml
```yaml
...
    output.elasticsearch:
      hosts: ["https://my-elastic:9200"]
...
      ssl.certificate: "/my-elastic-ssl-config/cert.pem"
      ssl.key: "/my-elastic-ssl-config/cert.key"

...

extraVolumes:
  - name: elastic-ssl-config-vol
    secret:
      secretName: elastic-ssl-config

extraVolumeMounts:
  - name: elastic-ssl-config-vol
    mountPath: "/my-elastic-ssl-config"
    readOnly: true
```
