### ISSUE TITLE
Prometheus might not work correctly with 1.6 RBAC

### ISSUE THREAD

**Issue by andrewhowdencom** [helm/charts#955]
See https://github.com/kubernetes/charts/blob/master/stable/prometheus/values.yaml#L468
Also, see https://github.com/prometheus/prometheus/pull/2641

**Comment by h0tbird** [comment]
> FWIW I just pulled the changes out of this and applied it to my own helm chart. Worked wonderfully.

@andrewhowdencom can you share your updated helm chart? I have the same problem after updating to GKE `1.6.1`. Thank you!

**Comment by h0tbird** [comment]
Nevermind, all I needed was:
```yaml
      - job_name: 'kubernetes-nodes'                                                                                                     
        kubernetes_sd_configs:
        - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
```
