### ISSUE TITLE
[stable/prometheus-operator] Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/exporters/.../servicemonitor.yaml is not available

### ISSUE THREAD

**Issue by TommyKTheDJ** [helm/charts#9597]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/prometheus-operator

**What happened**:
```
helm install --name prometheus-operator stable/prometheus-operator --namespace monitoring
Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/prometheus-operator/servicemonitor.yaml is not available
```

**What you expected to happen**:
Prometheus-operator chart to install.

**How to reproduce it** (as minimally and precisely as possible):
`helm install stable/prometheus-operator`

**Anything else we need to know**:
Error is similar to others logged, but they are not the same, so the fixes don't work. e.g. https://github.com/coreos/prometheus-operator/issues/861

Same error but different path each time it is run:
```
helm install stable/prometheus-operator
Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/exporters/kube-scheduler/servicemonitor.yaml is not available
root@hostname:~# helm install stable/prometheus-operator
Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/alertmanager/alertmanager.yaml is not available
root@hostname:~# helm install stable/prometheus-operator
Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml is not available
root@hostname:~# helm install stable/prometheus-operator
Error: apiVersion "monitoring.coreos.com/v1" in prometheus-operator/templates/alertmanager/servicemonitor.yaml is not available

**Comment by TommyKTheDJ** [comment]
I have also used the following values.yaml so only the prometheus-operator is deployed, but the error still appears.
```
alertmanager:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
```

**Comment by TommyKTheDJ** [comment]
I used the following values.yaml and it worked, only the operator is deployed.  I then used a separate values.yaml with everything enabled once the operator is in the cluster, and the apiversion is recognised.
```
defaultRules:
  create: false
prometheusOperator:
  serviceMonitor:
    selfMonitor: false
alertmanager:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
kubeScheduler:
  enabled: false
```

Is this a bug, or just a caveat that needs documenting?  (Given that the README.md doesn't mention this at all - nor does any of the CoreOS documentation I looked through.)
