### ISSUE TITLE
consul - unable to recover cluster

### ISSUE THREAD

**Issue by ajohnstone** [helm/charts#965]
If you increase and then decrease the cluster size... you lose the cluster leader and are then unable to recover.
I mentioned this [here](https://github.com/kelseyhightower/consul-on-kubernetes/issues/6) and submitted a PR, when this was still in the incubator, but never came to a final solution.

Issue: https://github.com/kelseyhightower/consul-on-kubernetes/issues/6
PR: https://github.com/kelseyhightower/consul-on-kubernetes/pull/7

Tested again on  consul:0.2.0

```
kubectl --namespace=consul patch statefulset/consul-consul -p '{"spec":{"replicas": 10}}' --namespace=consul
sleep 100
kubectl --namespace=consul patch statefulset/consul-consul -p '{"spec":{"replicas": 5}}' --namespace=consul
sleep 60
for i in $(seq 0 9); do kubectl --namespace=consul exec consul-consul-$i -- sh -c 'consul operator raft -list-peers '; done
...
Operator "raft" subcommand failed: Unexpected response code: 500 (No cluster leader)
```

@lachie83 Any further ideas on this?

The following is a good suggestion, but does not fix the underlying problem.
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: consul
spec:
  minAvailable: {{default 3 .Values.Replicas}} # -1 unsure how to do math in the templates?
  selector:
    matchLabels:
      heritage: {{.Release.Service | quote }}
      release: {{.Release.Name | quote }}
      chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      component: "{{.Release.Name}}-{{.Values.Component}}"
```
