### ISSUE TITLE
[Grafana] template "server.fullname" not defined

### ISSUE THREAD

**Issue by kminehart** [helm/charts#968]
I ran:

```
helm install -f values.yaml --name=dashboard stable/grafana
```

with the values:

```yaml
server:
  adminUser: admin
  installPlugins: ['raintank-kubernetes-app']
  ingress:
    enabled: true
    hosts:
      - grafana.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'                                                                                                                                                                                                                    
    tls:
    - secretName: dashboard-grafana-tls
      hosts:
        - grafana.example.com
```

And it worked when I ran

```
helm install -f values.yaml --name=dashboard stable/grafana --version=0.3.0
```
