### ISSUE TITLE
MountVolume.SetUp failed for volume “mongo-two”: lstat /mongo/data: no such file or directory

### ISSUE THREAD

**Issue by slimee** [helm/charts#9794]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: helm v2.10.0-rancher5, kubernetes v1.11.5

**Which chart**: mongo-replicaset 3.8.0

**What happened**: 
Deploying never end, kubelet logs infinitely: 
`MountVolume.SetUp failed for volume “mongo-two”: lstat /mongo/data: no such file or directory`
But /mongo/data folder exists on all nodes hosts.

**What you expected to happen**:
Local Persistent Volumes for mongo data should be mounted correctly.

**How to reproduce it** (as minimally and precisely as possible):
Get a cluster with three nodes, named one, two and three.

**Create storage class:**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
```

**Create 3 PVs:**
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-[one/two/three]
spec:
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mongo/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - [one/two/three]
```

**Deploy mongo-replicaset helm chart 3.8.0:
yaml config:**
```
replicas: 3
replicaSetName: rs0
port: 27017
auth:
  enabled: true
  adminUser: admin
  adminPassword: password
  key: fsz1468fez468
image:
  repository: mongo
  tag: xenial
  pullPolicy: IfNotPresent
persistentVolume:
  enabled: true
  storageClass: local-storage
  accessModes:
  - ReadWriteOnce
  size: 40Gi
```
**Resulting stateful-set yaml extract:**
```
...
  volumeMounts:
    - mountPath: /data/db
      name: datadir
...
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage
      resources:
        requests:
          storage: 40Gi
...
```

**Anything else we need to know**:
-While deploying, PV status is "Bound" with correct claim name, but fail to be mounted.
-When I deploy chart with persistentVolume.enabled: false, deployment succeeds
-My nodes hosts are ubuntu 16.04
-Sometimes the first pod deployment finish, but the second fails.
-On hosts, running "lstat /mongo/data" gives no command found
-On hosts, running "stat /mongo/data" succeeds

Thanks you
