### ISSUE TITLE
[stable/spinnaker] when using GCE ingress static ip, static files give a 404

### ISSUE THREAD

**Issue by retpolanne** [helm/charts#9822]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
Helm
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.11", GitCommit:"dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c", GitTreeState:"clean", BuildDate:"2018-11-10T20:22:02Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/spinnaker

**What happened**:
When setting the ingress to true and using a GCE ingress, any .js file will give a 404 because they fall to the default-backend and Spinnaker gets stuck on the "Hello" screen. 

**What you expected to happen**:
.js files should load and Spinnaker should proceed to its UI. 

**How to reproduce it** (as minimally and precisely as possible):
First, you have to create an ingress on GCE by reserving a static ip. 

`gcloud compute addresses create my-app-ingress --global --project my-project`

Then, you install using these values:
`helm install --dry-run --debug stable/spinnaker --set "ingress.enabled=true,ingress.annotations.kubernetes\.io\/ingress\.global-static-ip-name=my-app-ingress"`

**Anything else we need to know**:
When removing the ingress rules, the chart works as expected. When using GCE ingress, it's ok to use a catch-all rule because we're not relying on an nginx ingress controller.

**Comment by jgunnink** [comment]
Hi @vinicyusmacedo did you find a solution to this or did you solve it in some way? I have recently come across this issue and my searching found this thread.

**Comment by vinicyusmacedo** [comment]
Hi @jgunnick, please take a look at this PR:
https://github.com/helm/charts/pull/9824

If I'm not mistaken, I have changed the paths on my ingress to `/*`. This way all the paths will be handled by the ingress.

**Comment by jgunnink** [comment]
Thanks for getting back to me @vinicyusmacedo. We did solve it, but not just by setting `/*`. I noticed that when the config is set as so:
```yaml
ingress:
  enabled: true
  # host: spinnaker.example.org
  # annotations:
    # ingress.kubernetes.io/ssl-redirect: 'true'
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
  # tls:
  #  - secretName: -tls
  #    hosts:
  #      - domain.com
```
It already provisions an ingress rule which matches `/*`. However, the default backend is not set which means kubernetes responds with a 404 for all the other required files for the page to load.

To solve, I just created a simple ingress file, specifying the default back-end and applied it to the cluster.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-spinnaker-spindeck
spec:
  backend:
    serviceName: spin-deck
    servicePort: 9000
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: spin-deck
          servicePort: 9000
```
I can see you've done this too, in your PR, but it has not been merged yet! Thanks for pointing me in that direction. :smile:
