### ISSUE TITLE
[stable/postgresql] using existing PVC is broken

### ISSUE THREAD

**Issue by flypenguin** [helm/charts#9832]
**Is this a BUG REPORT or FEATURE REQUEST? (choose one):**
Feature request

**Version of Helm and Kubernetes**:
Helm: 2.11.0, K8S: 1.11.3 (Server), kubectl 1.12.2

**Which chart**:
stable/postgresql, v3.0.0

**What happened**:
I tried deploying using an existing PVC.

**What you expected to happen**:
The state would be as before (the PVC would be used as data mount)

**How to reproduce it** (as minimally and precisely as possible):
```bash
$ echo -e "persistence:\n  existingClaim: some_existing_claim_name" > values.yaml
$ helm install stable/postgresql -f values.yaml -n pg-test
```
**Anything else we need to know**:
If you look at the generated pod yaml, it's clear what happens:

```yaml
# pod spec. truncated to show the essential parts.
spec:
  containers:
  - image: docker.io/bitnami/postgresql:10.6.0
    # ...
    volumeMounts:
    - mountPath: /bitnami/postgresql
      # THIS IS THE SOURCE OF THE ERROR IMO
      name: data
  dnsPolicy: ClusterFirst
  # ...
  volumes:
  - name: data-pg-main
    # BECAUSE **HERE** IT'S NO LONGER 'data', BUT 'data-pg-main'
    # 'data-pg-main' IS NOWHERE MOUNTED, BTW.
    persistentVolumeClaim:
      claimName: data-pg-main
  - emptyDir: {}
    # ... AND HERE IS THE 'data' VOLUME AS emptyDir, WHICH *CAN'T* BE RIGHT.
    name: data
  # other volumes omitted.
```
