### ISSUE TITLE
[stable/chartmuseum] Make /storage writable by chartmuseum user

### ISSUE THREAD

**Issue by pho-enix** [helm/charts#9913]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: N/A

**Which chart**: chartmuseum

**What happened**: Deploying with pvc as storage. The /storage is owner root 755. It's not possible to upload charts via the API because the user chartmuseum does not have write access to /storage.

**How to fix**: I added spec.securityContext.fsGroup: 1000. After that chartmuseum is able to write to /storage and the upload via API works.

```
    spec:
      securityContext:
        fsGroup: 1000
      containers:
```
