### ISSUE TITLE
[stable/jenkins] Backup/restore feature

### ISSUE THREAD

**Issue by jpigree** [helm/charts#9987]
**Is this a request for help?**:
no

**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

Adding a backup/restore mecanism could be great in the Jenkins chart (I had plenty of issues with backup jenkins plugins). Actually I implemented it quick and dirty with AWS S3 as a storage but never opensourced it. Is the community interested in this? I saw a rotten feature request #3344. 

The configuration I created in the values.yaml looked like this:

```
backup:
  aws_access_key_id: "${BACKUP_ACCESS_KEY_ID}"
  aws_access_key_secret: "${BACKUP_ACCESS_KEY_SECRET}"
  retrieve:
    enabled: false
    name: jenkins.tar.gz
    path: "s3://${BACKUP_S3_BUCKET}/jenkins"
    image:
      repository: "devopsexperience/backup-retriever"
      tag: "1.0"
  upload:
    enabled: true
    name: jenkins.tar.gz
    path: "s3://${BACKUP_S3_BUCKET}/jenkins"
    schedule: "0 10 * * *"
    image:
      repository: "devopsexperience/backup-companion"
      tag: "1.0"
```

What the chart does is spawn a sidecar container which backups on schedule "/var/jenkins_home". And for the restore part, it is an initcontainer which fetches the archive, untar it then let the copy-default-config do its job.

I think, this gives the user an easy way to override too (change the container image). Will need to find a better way of passing the cloud provider credentials though.

If you are interested, I am willing to submit a PR.
