### ISSUE TITLE
[stable/sentry] When I deploy a sentry chart there is always a pv created for redis

### ISSUE THREAD

**Issue by sidohaakma** [helm/charts#9991]
**BUG REPORT**

**Chart**
Sentry/stable

**How to reproduce**
I override the existing redis persistence configuration as follows:

```yaml
redis:
  persistence:
    enabled: false
```
 
**Expected behaviour**
The pv for redis is not created.

**Observed behavoir**
The pv for redis is created

**Possible solution**
If I look into the redis chart, the keys for enabling persistence are on the master level so:

```yaml
redis:
  master:
    persistence: 
      enabled: true
```
